### ISSUE TITLE
Hide husky error message in Git client i.e GitHub Desktop

### ISSUE THREAD

**Issue by shivapoudel** [typicode/husky#1004]
I have `pre-push` hook defined which protects `main` branch and won't allow pushing to repo using Git client i.e. GitHub desktop by checking variable `"$TERM" = "dumb"`. For the context of CLI, we show confirm message like this:

```sh
You're about to push to main, is that what you intended? [y/N]:
```

This is the `pre-push` hook shell script:

```sh
#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

protected_branch="main"

if read local_ref local_oid remote_ref remote_oid; then
    if [ "refs/heads/${protected_branch}" = "$remote_ref" ]; then
		if [ "$TERM" = "dumb" ]; then
			>&2 echo "Sorry, you are unable to push to ${protected_branch} using a GUI client! Please use git CLI."
			exit 1
		fi

		printf "%sYou're about to push to ${protected_branch}, is that what you intended? [y/N]: %s" "$(tput setaf 3)" "$(tput sgr0)"
		read -r proceed < /dev/tty
		echo

		if [ "$(echo "${proceed:-n}" | tr "[:upper:]" "[:lower:]")" = "y" ]; then
			echo "$(tput setaf 2)Brace yourself! Pushing to the ${protected_branch} branch...$(tput sgr0)"
			echo
			exit 0
		fi

		echo "$(tput setaf 2)Push to ${protected_branch} cancelled!$(tput sgr0)"
		echo
		exit 1
	fi
fi
```

Now the main issue is that I received this kind of error message on the GitHub desktop if the push is not allowed:

```
Sorry, you are unable to push to main using a GUI client! Please use git CLI.
husky - pre-push hook exited with code 1 (error) <--- I wanted to hide this line in GitHub Desktop error popup
error: failed to push some refs to 'github.com:shivapoudel/test-husky.git'
```

So my question is how to hide text like `husky - pre-push hook exited with code 1 (error)` because I don't want this info in Git client but CLI is okay so far.

CC @typicode

**Comment by typicode** [comment]
I think if you add `set +e` it should prevent script from exiting on first error.

**Comment by shivapoudel** [comment]
@typicode where should I use `set +e` if I don't want to show a husky error and only display a error message we have added:

> Sorry, you are unable to push to test using a GUI client! Please use git CLI.

![image](https://user-images.githubusercontent.com/3774827/124775419-54597200-df5e-11eb-9355-d71e4bcbe33d.png)
