### ISSUE TITLE
Can't open .husky/_/husky.sh in GitLab CI

### ISSUE THREAD

**Issue by SevenOutman** [typicode/husky#1013]
Hi, I was using husky v7 in my project to setup a pre-commit hook for `lint-staged`. The problem happened when I added `semantic-release` integration into my pipeline.

### The result

My job keeps failing with following message:

    ".husky/pre-commit: 2: .: Can't open .husky/_/husky.sh"

### The cause

I tried adding environment variable `HUSKY: 0` but the job failed again with the same reason. I went through the job's log and found this warning from `prepare` script run in `npm ci` phase.

    npm WARN lifecycle [xxx]@1.0.0~prepare: cannot run in wd [xxx]@1.0.0 husky install (wd=/builds/[xxx])

Then I noticed that husky is dealing with `$HUSKY = 0` check in this `husky.sh`, which means `HUSKY: 0` only prevents hooks to run **if husky was installed correctly**. And this made me confused. Why wasn't it preventing installing from the very beginning?

**Comment by purejgleason** [comment]
I seem to be having a similar issue. Works fine locally but on Github I get...

`EACCES: permission denied, open '.husky/_/.gitignore'`

**Comment by codinggnome** [comment]
@SevenOutman I don't know if this will help but I had this problem today and it turned out that something had changed the line endings on my pre-commit file to the Windows format. Changing it back to the Unix format fixed it

**Comment by SevenOutman** [comment]
For anyone that comes across the same problem, husky is now handling `$HUSKY=0` correctly - prevents `husky install` to run - since 8.0 https://github.com/typicode/husky/commit/21bc34286fe69a3212b24516b1475a5e41956eed
