### ISSUE TITLE
Husky pre-commit fails with code 1 (error) 

### ISSUE THREAD

**Issue by abhinavkgrd** [typicode/husky#1014]
Committing from vs-code Source control returns this error but the command line works fine

vscode version - `1.58.2`

Command output
```> git -c user.useConfigOnly=true commit --quiet --allow-empty-message --file -
husky - pre-commit hook exited with code 1 (error)
```

pre-commit

 ```
#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

yarn lint-staged
```

package json
```
{
"scripts": {
    "lint-staged": "lint-staged",
    "postinstall": "husky install"
  },
"devDependencies":{
    "husky": "^7.0.0",
    "lint-staged": "^11.0.0",
}

 "lint-staged": {
    "src/**/*.{js,jsx,ts,tsx}": "eslint"
  },

"husky": {
    "hooks": {
      "pre-commit": "yarn run lint-staged"
    }
  }
}

```

**Comment by zackseuberling** [comment]
Similar issues with VS Code `Version: 1.59.0`

**Comment by kapilrc** [comment]
Having same issue with VS code `version 1.60.2`

**Comment by Zerzavot** [comment]
Husky can prevent you from bad git commit, git push and more. If you are getting this error check your code syntax, in case if you are getting this error even your code is valid. Please use the below command.

`git commit -m "message" --no-verify`

from: [here](https://stackoverflow.com/questions/63943401/husky-pre-commit-hook-failed-add-no-verify-to-bypass)

**Comment by ooliver1** [comment]
same with vscode for me 
```
> git -c user.useConfigOnly=true commit --quiet --allow-empty-message --file - -S
C:\Users\olive\OneDrive\Documents\sorted\programming\cpp\tooty\commitlint.config.js:1
��m


SyntaxError: Invalid or unexpected token
    at wrapSafe (internal/modules/cjs/loader.js:988:16)
    at Module._compile (internal/modules/cjs/loader.js:1036:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at module.exports (C:\Users\olive\node_modules\import-fresh\index.js:32:59)
    at loadJs (C:\Users\olive\node_modules\cosmiconfig\dist\loaders.js:16:18)
    at Explorer.loadFileContent (C:\Users\olive\node_modules\cosmiconfig\dist\Explorer.js:84:32)
    at Explorer.createCosmiconfigResult (C:\Users\olive\node_modules\cosmiconfig\dist\Explorer.js:89:36)
husky - commit-msg hook exited with code 1 (error)
```

**Comment by ooliver1** [comment]
randomly closed, it was the encoding was utf-16

maybe dont close without a comment

**Comment by sally2015** [comment]
try to restart your vscode

**Comment by Zerzavot** [comment]
I changed pre-commit file like that

```
#!/bin/sh

# ~/.huskyrc
# This loads nvm.sh and sets the correct PATH before running hook
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
```
pre-commit file:
![image](https://user-images.githubusercontent.com/50207648/147733955-2bed98f2-2312-445f-8dc6-3de8ab67b563.png)

my reference: [here](https://typicode.github.io/husky/#/?id=command-not-found)

**Comment by Zerzavot** [comment]
> Husky can prevent you from bad git commit, git push and more. If you are getting this error check your code syntax, in case if you are getting this error even your code is valid. Please use the below command.
> 
> `git commit -m "message" --no-verify`
> 
> from: [here](https://stackoverflow.com/questions/63943401/husky-pre-commit-hook-failed-add-no-verify-to-bypass)

or ``` git config --unset core.hooksPath   ```

**Comment by TheExGenesis** [comment]
`yarn lint-staged` and `git commit` work fine, the only occasion in which it doesn't work is when I commit from VS Code Source Control (VSC's GUI for git commands). Output console reads

```
> git cat-file -s 3a16d887abe6a7a51bc03914b1a46e741ae522f0
> git -c user.useConfigOnly=true commit --quiet --allow-empty-message --file -
Unexpected identifier
husky - pre-commit hook exited with code 1 (error)
```

**Comment by chicken-suop** [comment]
Why is this closed? I can still reproduce it. Please reopen

**Comment by annielmenezes** [comment]
Hi people, a have a similar issue to run commands in pre-push hook. Via command-line it works without problems.
I'm using nvm with a specific version to the project path.

My VS Code version is:
> Version: 1.64.0
Commit: 5554b12acf27056905806867f251c859323ff7e9
Date: 2022-02-03T04:20:17.224Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0

Output error:
`.husky/pre-push: line 4: npm: command not found`

Inside file I have a npm command:
`npm run test:ci`

**Comment by bivainis** [comment]
In my case "lint-staged" configuration was missing from `package.json` after a merge conflict was resolved. Added it back and no more issues.

**Comment by prapurnakumariTR** [comment]
> git config --unset core.hooksPath

This worked for me

**Comment by Liiva** [comment]
In my case when trying to commit from my IDE it would give the non-descriptive error `Unexpected identifier`, while committing from command line worked fine.

It turned out my IDE used an earlier node version (6.14.4 vs 7.19.1 from my terminal), upping the version fixed this for me.

**Comment by ooliver1** [comment]
it seems from this thread that husky can have a lot of issues that cause the same vague error, this might need to be addressed

**Comment by XuXiaowen** [comment]
> > git config --unset core.hooksPath
> 
> 这对我有用



> > git config --unset core.hooksPath
> 
> This worked for me

Me too, greate~

**Comment by magnus-bakke** [comment]
> > git config --unset core.hooksPath
> 
> This worked for me

This just disables husky for me.

**Comment by sh977218** [comment]
> > Husky can prevent you from bad git commit, git push and more. If you are getting this error check your code syntax, in case if you are getting this error even your code is valid. Please use the below command.
> > `git commit -m "message" --no-verify`
> > from: [here](https://stackoverflow.com/questions/63943401/husky-pre-commit-hook-failed-add-no-verify-to-bypass)
> 
> or `git config --unset core.hooksPath `

This does NOT resolve the issue, but a work around to ignore the issue.

**Comment by Nase00** [comment]
I was able to resolve this error by running each precommit command individually. Turns out my test command (`jest`) was causing the error due to an obsolete snapshot.

Note that Jest seems to hide that this actually causes an error code 🤦 and instead makes it look like a warning, so if this is your problem you'll never actually see an error code directly from Jest. That's probably why this only appeared as an error through Husky for me, and I imagine there could be many other situations where an individual command is swallowing the error code to make it look like Husky's fault.

**Comment by aghwotu** [comment]
> I was able to resolve this error by running each precommit command individually. Turns out my test command (`jest`) was causing the error due to an obsolete snapshot.
> 
> Note that Jest seems to hide that this actually causes an error code 🤦 and instead makes it look like a warning, so if this is your problem you'll never actually see an error code directly from Jest. That's probably why this only appeared as an error through Husky for me, and I imagine there could be many other situations where an individual command is swallowing the error code to make it look like Husky's fault.

This was my issue. Thank you for your comment.

**Comment by jeyhunhasanov** [comment]
I just renamed from `commitlint.config.js` to `commitlint.config.cjs`
It worked without any error.

**Comment by yangyueche** [comment]
Got the same error.
My issue might be that hooks that should be run before committing or pushing have an error.
eg., in my .husky/pre-commit 
it will run `yarn lint` before I commit.
so after solving the error in `yarn lint`, mine commit works.

**Comment by Tsekhmister** [comment]
Maybe it will help someone, everything worked out for me after changing single quotes to double ones in package.json
![image](https://user-images.githubusercontent.com/61798188/206259130-8ad682c4-7e3b-4b50-9cad-787ec05bd7e6.png)

**Comment by allygraham** [comment]
I got the same error as well.
Turns out I was running Node v10 when trying to commit, a quick swap over to v16 and all was good.

**Comment by fmruiz** [comment]
> > git config --unset core.hooksPath
> 
> This worked for me

You must to verify this because with this command you're disabling commit checks

**Comment by mushyoom** [comment]
> > git config --unset core.hooksPath
> 
> This worked for me

Thanks, you saved my time.

**Comment by Chynnie** [comment]
I realized that the right way to fix this error is not by bypassing it else your GitHub commit checks will fail when merging your branch.
The best way to fix this issue is by simply making your commits the way husky understands it. For example:

`git commit -m "feat: my commit message"`

This solution worked for me. I hope this helps.

**Comment by andrii-lundiak** [comment]
I hope you all know that by setting `git config --unset core.hooksPath` you basically DISABLE Husky at all from codebase. So it's NOT a fix for Husky, it's a break of Husky.

**Comment by mort3za** [comment]
> VS Code required actual restart, and OF ALL instances!!!

This fixed my issue. Just opened a new terminal in iTerm2

**Comment by ramBlanco** [comment]
this worked for me: 

create a file named ".lintstagedrc" with this inside 

```json
{
  "*.{ts,tsx}": ["eslint --fix", "prettier --write"]
}
```

my current version of lint-staged is: 13.2.0

**Comment by latanoel** [comment]
This worked for me:

First I ran `npx commitlint` and I got a prompt to update commitlint. Apparently, it seemed that commitlint needed an update

```code
Need to install the following packages:
  commitlint@17.6.1
Ok to proceed? (y) y
```

And voila! Subsequent commits were successful

**Comment by bravo-stack** [comment]
> > Husky can prevent you from bad git commit, git push and more. If you are getting this error check your code syntax, in case if you are getting this error even your code is valid. Please use the below command.
> > `git commit -m "message" --no-verify`
> > from: [here](https://stackoverflow.com/questions/63943401/husky-pre-commit-hook-failed-add-no-verify-to-bypass)
> 
> or `git config --unset core.hooksPath `

The `git config --unset core.hooksPath` worked for me.

**Comment by agustingorgni** [comment]
Just create a file called .lintstagedrc and put this:

```
{
  "*.{js,jsx}": ["npm run lint:js"]
}
```

**Comment by SiegeSailor** [comment]
Your `package.json` must be an actual JSON rather than just JavaScript Object. I change the following from:

```json
  "lint-staged": {
    "**/*": ["prettier --write --ignore-unknown"],
    "**/*.{ts,tsx}": ["jest --bail"]
  },
```

to

```json
  "lint-staged": {
    "**/*": "prettier --write --ignore-unknown",
    "**/*.{ts,tsx}": "jest --bail"
  },
```

And the issue was fixed.

**Comment by kojikojiXX** [comment]
That error happened me, too. 
I add following line to my `package.json`, then that error was fixed.

`"lint-staged": {
    "src/**/*.{js,jsx,ts,tsx,json,css,scss,md}": [
      "prettier --write"
    ]
  }`

**Comment by DeadLoss1801** [comment]
{
 "test" : "mocha" 
}

**Comment by jcubic** [comment]
I have the same error without any output:

```bash
#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

FILES=`git diff --name-only --cached --diff-filter=d | grep -E '(ts|tsx)$'`;

if [ ! -z "$FILES" ]; then
  for file in $FILES; do
      npx prettier --write $file;
      npx eslint --fix $file;
  done
  git add $FILES
else
  true
fi
```

Is there any way to force Husky to show what is the error? My script works fine If I comment out `. "$(dirname -- "$0")/_/husky.sh"` and return true.

I've also tried this:

```bash
FILES=`git diff --name-only --cached --diff-filter=d | grep -E '(ts|tsx)$'`;

for file in $FILES; do
    npx prettier --write $file;
    npx eslint --fix $file;
done
test ! -z "$FILES" && git add $FILES || true
```

and Husky keep showing an error.

**Comment by jcubic** [comment]
So the problem was if the FILES is empty grep will return non-zero code and the whole hook will fail and the rest will not be executed.

I've solved the issue with this code:
```bash
SKIP="__HUSKY__"

FILES=`git diff --name-only --cached --diff-filter=d | grep -E '(ts|tsx)$' || echo $SKIP`;

if [ "$FILES" != "$SKIP" ]; then
  for file in $FILES; do
      npx prettier --write $file;
      npx eslint --fix $file;
  done
  git add $FILES
fi
```

**Comment by fnavarrodev** [comment]
In my case husky was always getting node 14. Changing nvm default version didn't work or changing the PATH variable because the version was pinned in my .huskyrc file. I recommend you all checking that evil file.

**Comment by mjaynixxz** [comment]
In my case I keep getting this error, I really dunno where the issue is coming from, there is not a clear message to indicate the problem, husky is installed properly, if I am to comment out the script related to npm or npx, it just works fine. But the npm n npx commands keeps getting canceled

![image](https://github.com/typicode/husky/assets/41976904/dbb886ea-72dc-4b65-858b-b8946ff699c2)

**Comment by jcubic** [comment]
@mjaynixxz this is something different because you have an error from npm, not only the error code. Did you look into the log file?

**Comment by Haseeb78692** [comment]
> > Husky can prevent you from bad git commit, git push and more. If you are getting this error check your code syntax, in case if you are getting this error even your code is valid. Please use the below command.
> > `git commit -m "message" --no-verify`
> > from: [here](https://stackoverflow.com/questions/63943401/husky-pre-commit-hook-failed-add-no-verify-to-bypass)
> 
> or `git config --unset core.hooksPath `

WORKED 😀

**Comment by NakZMichael** [comment]
I updated my VSCode version.This fixed my issue.
Maybe restarting all VSCode window is the solution for this issue.

**Comment by amanr-dev** [comment]
> Husky can prevent you from bad git commit, git push and more. If you are getting this error check your code syntax, in case if you are getting this error even your code is valid. Please use the below command.
> 
> `git commit -m "message" --no-verify`
> 
> from: [here](https://stackoverflow.com/questions/63943401/husky-pre-commit-hook-failed-add-no-verify-to-bypass)

It Worked for me 👍

**Comment by OahMada** [comment]
In my case, everything works if I commit from VSCode's integrated terminal, but it's not the case in SourceTree.

**Comment by ktsangop** [comment]
> I was having this problem and the output was complaining about "Unexpected token '??='". I'm using nvm, and this seems to be related to which version of node is loaded by default in the terminal (in this case, one which didn't understand this operator), regardless of my config switching node version based on the presence of a `.nvmrc` file.
> 
> In my case when I checked I had version 14 pinned in my path.
> 
> I was able to work around this by:
> 
> 1. Setting `nvm alias default <desired default, e.g. lts/hydrogen>`
> 2. Removing version 14 from my path, and adding `<.nvm_path>/alias/default` instead

Thanks for this

Just adding that I had nvm installed inside git bash (for Windows), and I wasn't able to find the path to the nvm installed nodejs instances. 
So I removed my system's default nodejs installation (which was an older one), and installed a more recent one.
That way, husky was able to point to a compatible nodejs version, and my CLI (git bash) kept pointing to the nvm defined "default" version.

**Comment by carolisc** [comment]
I had this problem today with `"lint-staged": "^15.2.2" `

Tried many things from this thread and another, but nothing worked so I decided to go with `git commit -m "message" --no-verify`

P.S. if anyone would like to know: `"husky": "^8.0.0",
    "prettier": "^3.2.5",
    "vite": "^5.2.0"`

**Comment by kamwithak** [comment]
> git config --unset core.hooksPath

This works but you are now missing your hooks 😆

**Comment by JJozef** [comment]
###  **Same error** 

![image](https://github.com/typicode/husky/assets/101532359/c43d7e18-010b-4d1b-944f-febb1e774e6b)

```json
"husky": "9.0.11",
"@commitlint/cli": "19.2.2",
"@commitlint/config-conventional": "19.2.2",
"lint-staged": "15.2.2",
```

**Comment by veeramani-arthanari** [comment]
`lint-staged` not supporting nodejs version 12 anymore. Update your node, it'll work

https://github.com/serverless/serverless/issues/11249#issuecomment-1186439595

**Comment by brodyd795** [comment]
For those who tried `git config --unset core.hooksPath` with a custom Husky setup in a root `.husky` directory, you'll need to run `git config --local core.hooksPath .husky` to get Husky working again.

**Comment by kingofsevens** [comment]
In my case, I had below line in my pre-commit file..

```
FILES=$(git diff --cached --name-only | grep '^APIs/.*\.json')
[ -z "$FILES" ] && echo "No changes detected..." && exit 0;
```

This returned an empty `FILES`, so husky was giving the above error. With a little bit of digging I have changed the line to below, it worked fine. I don't know why husky is exiting there and not just allowing the below line to work, that needs to be checked. But for those struggling like me here is the corrected version.

```FILES=$(git diff --cached --name-only | grep '^APIs/.*\.json' || true)```

This runs expectedly in each case...

**Comment by osama-dev-logiciel** [comment]
I came across same issue and I deleted my node_modules file than run yarn and it worked for me.

**Comment by Matheus-SS** [comment]
> I checked mine and saw that my `lint-stages` config
> 
> ```
> 
>   "lint-staged": {
>     "**/*.{js,jsx,ts,tsx}": [
>       "npm run lint"
>     ]
>   }
> ```
> 
> was not directly in the root of the package.json

For that was the issue.
Node version 22.12.0  using nestjs
