### ISSUE TITLE
HUSKY_SKIP_HOOKS no longer respected by Husky 7

### ISSUE THREAD

**Issue by Sidnioulz** [typicode/husky#1015]
The `HUSKY_SKIP_HOOKS` environment variable appears to no longer be respected in Husky 7. When I add it to my env and run a commit, Husky still triggers my pre-commit hook.

This is breaking my workflow as I am currently rebasing an entire feature branch to fix a typo in a commit message. I am totally able to take it upon myself to manually run my tests and commitlint on the relevant commit, but I need to not watch an entire test suite run 10 times in a row for commits that have not changed in the slightest and are still passing.

- Bash terminal, not in CI mode
- Husky 7

**Comment by juergba** [comment]
@Sidnioulz see [Breaking changes](https://typicode.github.io/husky/#/?id=breaking-changes):

> HUSKY_SKIP_HOOKS becomes HUSKY

**Comment by PhiLhoSoft** [comment]
A little remark on this: you should have a CHANGELOG file or section listing the breaking changes by version number.
I went to the doc to see why we went from 6 to 7 and found nothing specific, except this Breaking changes section which doesn't tell which version introduces these changes.
Thanks for your useful tool.

**Comment by Sidnioulz** [comment]
> @Sidnioulz see [Breaking changes](https://typicode.github.io/husky/#/?id=breaking-changes):
> 
> > HUSKY_SKIP_HOOKS becomes HUSKY

Oof, my bad, I missed this change! My apologies for the issue noise.
