### ISSUE TITLE
Permission Denied - NPM: Should we add instructions to make bin.js executable?

### ISSUE THREAD

**Issue by ElijahLynn** [typicode/husky#1017]
**Troubleshoot**
- [x] Before creating an issue, please check:
https://typicode.github.io/husky/#/?id=troubleshoot

**Context**
Please describe your issue and provide some context:
- Terminal or GUI client (PowerShell, Git Bash, GitHub Desktop, ...)
- If applicable, content of the failing hook
- If possible, minimal steps to reproduce the issue

I'm working on an existing implementation of Husky and ran into an issue where we were getting a permission denied on a `yarn install` which appears to call `husky install` from the `yarn prepare` command in package.json. 

I read through the README and don't see any suggestions on setting the bin.js to be executable but I was able to `strace -f yarn install` the issue and found that was the issue:

```
[pid  3182] clone(strace: Process 3183 attached
child_stack=NULL, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7fbfe23e2850) = 3183
[pid  3182] wait4(-1,  <unfinished ...>
[pid  3183] execve("/var/lib/tugboat/docroot/vendor/va-gov/content-build/node_modules/.bin/husky", ["husky", "install"], 0x56228b666518 /* 346 vars */) = -1 EACCES (Permission denied)
```

Which was symlinked:
```
root@php:/var/lib/tugboat/web# ls -al /var/lib/tugboat/docroot/vendor/va-gov/content-build/node_modules/.bin/husky
lrwxrwxrwx 1 www-data www-data 19 Aug  2 21:15 /var/lib/tugboat/docroot/vendor/va-gov/content-build/node_modules/.bin/husky -> ../husky/lib/bin.js
```

And the perms were: 
```
root@php:/var/lib/tugboat/web# ls -al /var/lib/tugboat/docroot/vendor/va-gov/content-build/node_modules/husky/lib/bin.js 
-rw-rw-r-- 1 www-data www-data 1030 Aug  2 21:15 /var/lib/tugboat/docroot/vendor/va-gov/content-build/node_modules/husky/lib/bin.js
```

So, my question. Is this a known thing to do in the NPM community, to chmod your executables? Or should we add this to the docs? Thanks

**Comment by ndouglas** [comment]
This appears to have been caused by an issue with one of our deployment scripts, and didn't imply an issue with this package 😅

**Comment by ElijahLynn** [comment]
Thanks @ndouglas, [your solution](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/6077/files) for our situation was modifying our script that added that executable permission to scripts within `node_modules/.bin` but it wasn't following symlinks, which was resolved with the `-L` flag on the `find` command, e.g. `find "${DOCROOT}/vendor/va-gov/content-build/node_modules/.bin" -type f -exec chmod +x {} \+`. 

I suppose we can close for now, although do wonder if some docs can be added to clarify this.

**Comment by Michael-Xie** [comment]
> This appears to have been caused by an issue with one of our deployment scripts, and didn't imply an issue with this package 😅

It seems like this issue is popping up again for `"husky": "^8.0.2"`

**Comment by ElijahLynn** [comment]
> > This appears to have been caused by an issue with one of our deployment scripts, and didn't imply an issue with this package 😅
> 
> It seems like this issue is popping up again for `"husky": "^8.0.2"`

Can you open a new issue and link it to this one? I think that will get better visibility for your issue.
