### ISSUE TITLE
husky add command escapes string with positional parameters ($1)

### ISSUE THREAD

**Issue by remarkablemark** [typicode/husky#1019]
**Troubleshoot**
- [x] Before creating an issue, please check:
https://typicode.github.io/husky/#/?id=troubleshoot

If you're migrating from husky 4, see:
https://typicode.github.io/husky/#/?id=migrate-from-v4-to-v7

**Context**
Please describe your issue and provide some context:
- Terminal or GUI client (PowerShell, Git Bash, GitHub Desktop, ...)
  - macOS iTerm2 ZSH
- If applicable, content of the failing hook
  - See below
- If possible, minimal steps to reproduce the issue:

Create empty directory with git:

```sh
$ mkdir test && cd test && git init
```

Install husky:

```sh
$ npx husky install
husky - Git hooks installed
```

Running command from [docs](https://typicode.github.io/husky/#/?id=automatic-recommended):

```sh
$ npx husky add .husky/commit-msg 'npx --no-install commitlint --edit "$1"'
husky - created .husky/commit-msg
```

**Expected** output of `.husky/commit-msg`:

```sh
#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npx --no-install commitlint --edit "$1"
```

**Actual** output of `cat .husky/commit-msg`:

```sh
#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npx --no-install commitlint --edit ""
```

My version of husky:

```sh
$ npm ls husky
test@1.0.0 /Users/remarkablemark/test
└── husky@7.0.1
```

Thank you!

**Comment by eliezio** [comment]
This worked for me:

```console
npx husky add .husky/commit-msg 'npx --no -- commitlint --edit `echo "\$1"`'
```

**Comment by shuckster** [comment]
Thanks for that @eliezio . I had to escape the double-quotes, too:

```sh
npx husky add .husky/commit-msg 'npx --no -- commitlint --edit `echo \"\$1\"`'
                                                                     ^    ^
```
