### ISSUE TITLE
Why preuninstall called when run npm install

### ISSUE THREAD

**Issue by quicklearning123** [typicode/husky#1020]
**Troubleshoot**
![image](https://user-images.githubusercontent.com/70048681/128590907-10aa9a9b-1eec-4a9a-acdd-8710a70d5438.png)

![image](https://user-images.githubusercontent.com/70048681/128590929-32ffc14e-e3f5-4602-aa47-fe4776223bab.png)

If you're migrating from husky 4, see:
https://typicode.github.io/husky/#/?id=migrate-from-v4-to-v7

**Context**
Please describe your issue and provide some context:
- Terminal or GUI client (PowerShell, Git Bash, GitHub Desktop, ...)
- If applicable, content of the failing hook
- If possible, minimal steps to reproduce the issue

Thank you!

**Comment by typicode** [comment]
It's to clean what was installed by husky 4.3.8 :)
