### ISSUE TITLE
git.exe cannot find hook, even though it exists

### ISSUE THREAD

**Issue by cinderblock** [typicode/husky#1021]
**Troubleshoot**
- [x] Before creating an issue, please check:
https://typicode.github.io/husky/#/?id=troubleshoot

If you're migrating from husky 4, see:
https://typicode.github.io/husky/#/?id=migrate-from-v4-to-v7

**Context**
Please describe your issue and provide some context:
- Terminal or GUI client (PowerShell, Git Bash, GitHub Desktop, ...) **PowerShell**
- If applicable, content of the failing hook **N/A**
- If possible, minimal steps to reproduce the issue

1. On Windows, install husky: `npx husky install`
2. Create a file: `.husky/commit-msg`
3. Run `npm version minor`

Expected result: No errors.

Actual result:

```log
npm ERR! code 1
npm ERR! command failed
npm ERR! command C:\Program Files\Git\cmd\git.EXE --no-replace-objects commit -m 1.2.0
npm ERR! error: cannot spawn .husky/commit-msg: No such file or directory
```

Thank you!

**Comment by fabiolmorato** [comment]
Also happening here

**Comment by brick9527** [comment]
I resolved this problem as follows:

1. Re-install your `.husky` file with `husky install` 
1. Check your file end of line sequence, change 'CRLF' to 'LF'

**Comment by AssisrMatheus** [comment]
> 1. husky install



> I resolved this problem as follows:
> 
> 1. Re-install your `.husky` file with `husky install`
> 2. Check your file end of line sequence, change 'CRLF' to 'LF'

Did not work for me

**Comment by douglasg14b** [comment]
Still a problem for me too... Can this be reopened? Just because there is no solution for x# of days doesn't mean it's resolved...

**Comment by brick9527** [comment]
已经收到邮件。我会尽快回复的。

**Comment by douglasg14b** [comment]
Has anyone found a solution to this problem?
