### ISSUE TITLE
Husky Fails with "Unknown argument: .git/COMMIT_EDITMSG"

### ISSUE THREAD

**Issue by thoughtassassin** [typicode/husky#1026]
**Troubleshoot**
- [x] Before creating an issue, please check:
https://typicode.github.io/husky/#/?id=troubleshoot

If you're migrating from husky 4, see:
https://typicode.github.io/husky/#/?id=migrate-from-v4-to-v7

**Context**
Please describe your issue and provide some context:
Terminal

For no reason husky started failing with a cryptic message:

```
Unknown argument: .git/COMMIT_EDITMSG
husky - commit-msg hook exited with code 1 (error)
```

Thank you!

**Comment by typicode** [comment]
This looks like some error message from another command used in `commit-msg` hook.
To ensure that it's not related to husky code, you can delete `. "$(dirname "$0")/_/husky.sh"` line and make another commit.
