### ISSUE TITLE
husky with sourcetree?

### ISSUE THREAD

**Issue by badtant** [typicode/husky#103]
I'm trying to use husky precommit with sourcetree. The precommit command is run but i get the following error:
env: node: No such file or directory

Does anybody know what's wrong? I'm using nvm.

**Comment by iamstarkov** [comment]
have you read [tricks in the README](https://github.com/typicode/husky#tricks)?

**Comment by badtant** [comment]
yes, and I didn't find any trick there. I'm fine with using what nvm has set as default but I don't think that is where my problem lies.

**Comment by badtant** [comment]
I had some old node stuff except for nvm but I've removed that now and now I get this error:

.git/hooks/pre-commit: line 11: exists: command not found
.git/hooks/pre-commit: line 11: exists: command not found
> husky - Can't find npm in PATH. Skipping precommit script in package.json

So, for some reason husky doesn't seem to be able to load nvm.

**Comment by typicode** [comment]
Hi @badtant,

Seems like it's a bug and more particularly a typo. Could you try replacing `exists` with `command_exists` in `.git/hooks/pre-commit`?

**Comment by typicode** [comment]
Actually there's @rainboxx's PR that fixes it, a new version should be published soon.

**Comment by typicode** [comment]
@badtant PR has been merged and new version has been published, it should better now :)

**Comment by iamstarkov** [comment]
@badtant can you verify it with new husky's version?

**Comment by ohana54** [comment]
I still had an issue with SourceTree, adding this comment in case it helps someone.
The pre-commit-hook looks for `npm`, and I had a leftover `npm` in `/usr/local/bin`, so the hook didn't run `nvm` like it's supposed to.
I removed `usr/local/bin/npm`, the hook then properly ran `nvm use` and everything worked.

**Comment by rainboxx** [comment]
@ohana54 check out the discussion at https://github.com/typicode/husky/pull/101. The code has changed but it was loading `nvm` when there's a `.nvmrc` file in the project folder, even when `npm` was in the path. We didn't come to a solution how to handle such a case (it's also a breaking change) but IMHO comments are welcome.

In the end I also uninstalled the system-wide node, since it's not used.

**Comment by zachleat** [comment]
@ohana54 This did help me—thank you!

**Comment by chimurai** [comment]
`nvm uninstall <old node version>` did it for me. No need to temper with the symlinks

use `nvm ls` to list the installed node versions

**Comment by brettz9** [comment]
I was getting the error message, "util.getSystemErrorName is not a function" (due to using an older Node version), and @chimurai's advice helped. Adding for anyone else who may come across that message.
