### ISSUE TITLE
Possible addition to the troubleshooting workaround section of the docs

### ISSUE THREAD

**Issue by jcollum** [typicode/husky#1030]
Not an issue per se, just a potential fix for some people who use global git hooks. I've tested this prepare-commit-msg hook and it works as expected: 

`.husky/prepare-commit-msg`: 

```
#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# run the global prepare-commit-msg if it is present
if [ -e `git config --global core.hookspath`/prepare-commit-msg ]; then
    `git config --global core.hookspath`/prepare-commit-msg "$@"
fi
# otherwise do nothing
```

Our global hook appends a chunk of text (that pulls from our branch naming convention) to the commit message. Tested it and it works fine.

**Comment by typicode** [comment]
Pretty cool, thanks for sharing.
