### ISSUE TITLE
documentation: npm set-script doesn't work universally

### ISSUE THREAD

**Issue by glensc** [typicode/husky#1031]
With Node 14 provided `npm` (`brew install node@14`):

```
npm set-script prepare "husky install"
```

gives error:
```
...
npm@6.14.14 /usr/local/Cellar/node@14/14.17.5/lib/node_modules/npm

Did you mean this?
    run-script
```

So, I think it's better to outline in documentation that this command requires npm@7:

> 
> To automatically have Git hooks enabled after install, edit package.json
>
> `npm set-script prepare "husky install"`
> 

Source:
- https://typicode.github.io/husky/#/?id=install

**Comment by AlokMishra051298** [comment]
Exactly, I m also facing same issue with npm version <7

**Comment by AlokMishra051298** [comment]
If I set prepare script manually then also pre-commit is not working. ☹️

**Comment by glensc** [comment]
@AlokMishra051298 please create a new issue for the new problem. this issue is about documentation.

**Comment by glensc** [comment]
activity!

**Comment by heythanks** [comment]
I meet same problem with node@14, so I add scripts "prepare": "husky install"  in  package.json

**Comment by hiiamtrong** [comment]
Check your npm version. `npm set-script command requires at least npm v7.x. See [here](https://prettier.io/docs/en/install.html)

**Comment by typicode** [comment]
Thanks for the feedback 👍 
It's always tricky to account for the different versions of package managers without making the docs too heavy to read/write.

At some point, I'll revisit all docs at once. Soon also Node 12 will be end of life and only Node 14 will have npm 6.

**Comment by dipakparmar** [comment]
Upgrading to node `v16.14.0` and npm `8.3.1` worked for me. I use nvm, easy to switch and test on other versions.

**Comment by edgardz** [comment]
If upgrading isn't an option, I did this for npm 6.x instead o set-script : `npx npe scripts.prepare "..."`

**Comment by elliot40404** [comment]
```console
npm pkg delete scripts.prepare
```
Seems to be a better alternative and work 95% of the time in all cases
