### ISSUE TITLE
For npm version < 7, pre-commit hooks are not running.

### ISSUE THREAD

**Issue by AlokMishra051298** [typicode/husky#1036]
I'm setting up husky in my project. 
Npm (version < 7) 

But after adding file, pre-commit/per-push hooks are not running.

Please provide resolution.
Thanks in advance :)

**Comment by uniquejava** [comment]
oh, I was not aware of it. I just commented here:  #912 
let me try to upgrade my node.js from 12 to 14

**Comment by AdrianValdes** [comment]
Thanks @uniquejava , restarting the computer solved it! I was going crazy.
