### ISSUE TITLE
error Command "husky-run" not found.

### ISSUE THREAD

**Issue by zx-zx22** [typicode/husky#1042]
**Troubleshoot**
- [ ] Before creating an issue, please check:
https://typicode.github.io/husky/#/?id=troubleshoot

If you're migrating from husky 4, see:
https://typicode.github.io/husky/#/?id=migrate-from-v4-to-v7

**Context**
Please describe your issue and provide some context:
- Terminal or GUI client (PowerShell, Git Bash, GitHub Desktop, ...)
- If applicable, content of the failing hook
- If possible, minimal steps to reproduce the issue

Thank you!

**Comment by typicode** [comment]
You have an older install of husky that is still present. You can remove it by running `rm -rf .git/hooks`. You may want to check that you don't have any personal hook in this directory before deleting it.
