### ISSUE TITLE
When the project folder does not exist in the root directory of the git repository, the error ".git can’t be found" will appear

### ISSUE THREAD

**Issue by qinchenno1** [typicode/husky#1045]
As shown in the title, My git repository has two folders, one is docs, and others is project which has all of codes.
So ,when I try to add husky to my project folder, the error occurs. I  have checked the code of husky and I think I got it. The error is caused by these codes as shown below:
![image](https://user-images.githubusercontent.com/45233388/133616958-3b2e72d6-9e53-4ac8-a1fe-a8d1ae3020f6.png)

According my understanding, husky doesn't need to know the .git folder, it just change default git hooks path to its own folder. So these codes ' usage is checking current path is a git repository, but if project isn't exist the root directory of git, the check will cause error.

So, may i ask if you can consider letting developers specify the path of '.git' ?

**Comment by typicode** [comment]
It's possible to specify a path, however as a safeguard it and to avoid previous issues, prevents exiting from `package.json` directory.

However, you can do the following which is allowed:
https://typicode.github.io/husky/#/?id=custom-directory

**Comment by qinchenno1** [comment]
I see! Thanks for your solution!

**Comment by KayLinCT** [comment]
I also have this issue, what i do:
1. Block the following code：
// if (!fs.existsSync('.git')) {
//     throw new Error(`.git can't be found (see ${url})`);
// }
2. Execute 'npm run prepare' to create '.husky' dic.
3. Execute 'npx husky add .husky/pre-commit "cd project path && npm test" ' to create 'pre-commit' file.
4. Execute 'git add .husky/pre-commit'
5. Move the '.husky' to the same directory as .git.

Hope this help you.

**Comment by KayLinCT** [comment]
There have a best solution:
https://typicode.github.io/husky/guide.html
