### ISSUE TITLE
Husky does not exit early when HUSKY=0

### ISSUE THREAD

**Issue by dotnetCarpenter** [typicode/husky#1046]
I upgraded from 4 to 7 today and pushed to our staging server. After reading the build log i'm a little concerned about pushing this to production.

**I have set environment variable `HUSKY=0` on our staging server.**

### Expected result:

```
> firefund-production@1.13.0 prepare
> husky install

husky disabled
```

### Actual result:

```
> firefund-production@1.13.0 prepare
> husky install

fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```

So contrary to [what I would expect according to the documentation](https://typicode.github.io/husky/#/?id=with-env-variables), Husky does not exit early when disabled but continue to search for a git repository.

**Not running hooks is IMO not enough - when husky is being disabled it should be disabled.**

At the moment I think we can live with husky executing on our production server but this put us in a difficult spot where bugs in Husky can influence our production environment.
That means **Husky is no longer a developer dependency** but a production dependency which need stricter vetting for security vulnerabilities for each update of Husky. That's a needless heavy requirement to put on teams that wish to automate git tasks.

A workaround could be is-ci but I whole heartily agree with [@ext here](https://github.com/typicode/husky/issues/914#issuecomment-832897215), adding another dependency to get rid of one dependency does not make sense. 

Using packages to develop software is great! 
Spending lots of time vetting/upgrading packages for security reasons is not!

**Comment by dotnetCarpenter** [comment]
A check for `! process.env.HUSKY` could be added here: https://github.com/typicode/husky/blob/main/src/index.ts#L13

Example:
```js
if (process.env.HUSKY === 0) {
  l('Husky is disabled')
  return
}
```

**Comment by dotnetCarpenter** [comment]
@typicode would you accept a PR to fix this?

**Comment by achamas-playco** [comment]
Worth mentioning that you may need to use the `export` keyword to make sure the environment variable is available to other bash script contexts.

So try:

```bash
export HUSKY=0
```

Instead of:

```bash
HUSKY=0 
```

This fixed the problem for me on Mac after getting nowhere trying to disable Husky with all sorts of combinations.
