### ISSUE TITLE
Husky commit-msg hook not firing from makefile

### ISSUE THREAD

**Issue by iameduardod** [typicode/husky#1057]
"husky": "^7.0.2"

I have a makefile with the following content:
`git:
git add -A
git commit -m "$m"
git push -u origin
`

Running 
` make git m="test"` in the terminal does not fire the "commit-msg" hook

**Comment by typicode** [comment]
Hi @iameduardod

See https://typicode.github.io/husky/#/?id=hooks-not-running there should be all that you need to debug your issue :)
