### ISSUE TITLE
npx: command not found

### ISSUE THREAD

**Issue by baboon-king** [typicode/husky#1058]
### Describe the bug
```shell
.husky/pre-commit: line 5: npx: command not found
```
![image](https://user-images.githubusercontent.com/63645337/136908291-03a456b0-4348-4bbb-9d28-8c7a5df7ef80.png)

### Reproduction

at the time of submission a commit

Maybe I used  `npm 8` ?

### System Info 
```shell
  System:
    OS: macOS 12.0
    CPU: (8) arm64 Apple M1
    Memory: 106.66 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.11.0 - ~/.nvm/versions/node/v16.11.0/bin/node
    npm: 8.0.0 - ~/.nvm/versions/node/v16.11.0/bin/npm
  Browsers:
    Chrome: 94.0.4606.71
    Edge: 92.0.902.67
    Safari: 15.0
  npmPackages:
    husky: ^7.0.0 => 7.0.2 
    lint-staged: ^11.2.3 => 11.2.3 
```

**Comment by baboon-king** [comment]
because I used `nvm`. 
try see https://typicode.github.io/husky/#/?id=command-not-found

**Comment by baiwusanyu-c** [comment]
> because I used `nvm`. try see https://typicode.github.io/husky/#/?id=command-not-found

使用了 nvm的话 这个配置加在哪儿呢
![image](https://user-images.githubusercontent.com/32354856/165687266-e71ed5e1-ea7c-4ceb-a6b3-7a16bd7baa37.png)
