### ISSUE TITLE
nvm shouldn't be skipped even if a global Node installation (e.g. via Homebrew) is present

### ISSUE THREAD

**Issue by mgol** [typicode/husky#106]
I have a few Node.js versions installed via nvm but I also have one from Homebrew. nvm supports such scenario; it lists the globally installed Node as "system", allows to switch to it etc.

In one of my projects I require a Node version matching `>=6.5.0 <7.0.0`; other versions are rejected. However, the global package is now at 7.1.1. I have a proper `.nvmrc` (with contents: `6`) in my project but now it seems not invoked. The hooks get invoked with the global Node.js and the whole script fails.

I've seen the following entry in the `0.13.0` changelog entry:
> Fixes issue with `OS X + brew` where `nvm` was loaded even when `npm` was already present

It seems this change is doing exactly opposite to what I'd expect. :/

It works fine in 0.12.0.

**Comment by typicode** [comment]
Thank you for the report @mgol, it's an unexpected side effect.
I'll have a look this week-end.

**Comment by typicode** [comment]
Could you try with `npm install --save-dev husky@0.13.3-0`?

**Comment by mgol** [comment]
Sorry for the delay. I confirmed `0.13.3-0` fixes my issue.

**Comment by typicode** [comment]
It's published `v0.13.3` :)
