### ISSUE TITLE
Documentation change request

### ISSUE THREAD

**Issue by gnesher** [typicode/husky#1068]
**Troubleshoot**
- [X] Before creating an issue, please check:
https://typicode.github.io/husky/#/?id=troubleshoot

If you're migrating from husky 4, see:
https://typicode.github.io/husky/#/?id=migrate-from-v4-to-v7

**Context**
The current documentation relies on NPM 7 for set-script (Node LTS still uses NPM 6) and doesn't work on Windows (see https://github.com/typicode/husky/issues/978). While I understand the appeal of using newer features the current installation guide will fail for a reasonable number of users.

Would it be possible to revise the instructions with a more complex (but useful) set of instructions, possibly mentioning that for a subset of users there's a faster way to get going? I'd be happy to help with a pull request.

**Comment by louwers** [comment]
Annnd it's deprecated again!  #1150
