### ISSUE TITLE
Seems to have a problem with github-desktop on windows 10.

### ISSUE THREAD

**Issue by DindoLeonard** [typicode/husky#1071]
Can't find path to nodejs/npm. 
![Capture](https://user-images.githubusercontent.com/76790991/140249215-ed371276-e9f3-40f2-8235-99c8bca27536.PNG)

**Comment by talelk** [comment]
same problem here

**Comment by DindoLeonard** [comment]
@talelk just found this solution, my husky now works.

https://github.com/typicode/husky/issues/950

just fix your PATH in the system environment variables
