### ISSUE TITLE
The eslint is not working in lint-staged

### ISSUE THREAD

**Issue by Moonachi** [typicode/husky#1073]
Hi, I'm going to try the husky package because it looks so good.

If you type "eslint src/" in the project terminal, a warning is displayed.
But, If it is written in package.json and executed as pre-commit, no warning is displayed and commit proceeds after pass.

## package version 
`
"husky": "^7.0.0",
"lint-staged": "^12.0.2",
`
<img width="193" alt="스크린샷 2021-11-15 오후 7 52 54" src="https://user-images.githubusercontent.com/46507959/141769490-a04cb343-22a1-43d1-96d4-55328a7a660c.png">

## package.json `script` 
`
"lint-staged": {
    "*.js": [
      "yarn eslint",
      "eslint src/",
      "yarn prettier --write"
    ]
  }
`
<img width="212" alt="스크린샷 2021-11-15 오후 7 53 49" src="https://user-images.githubusercontent.com/46507959/141769622-50460a9c-d266-444a-b5e3-7d402b48f1f2.png">

## .husky/pre-commit 
`
#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

yarn lint-staged
`
<img width="239" alt="스크린샷 2021-11-15 오후 7 54 19" src="https://user-images.githubusercontent.com/46507959/141769678-dbf05456-3fb5-4688-9c63-4a0cdd549757.png">

How do I fix it so that the warning is displayed? Thanks

**Comment by linden-dg** [comment]
I believe either `husky` or `lint-staged` ignores warnings by default. I got around this by adding the `--max-warnings=0` flag to the eslint script, e.g. `eslint --fix --max-warnings=0`

This forces the script to throw an error if at least 1 warning is present.
