### ISSUE TITLE
Look forward to the support of gerrit in Husky 7.0.4

### ISSUE THREAD

**Issue by eyunhua** [typicode/husky#1076]
Hi @typicode 
I want to generate a `Change-Id` in the end of message in `commit-msg` hook.
in Husky 7.0.4, How to achieve?

**Comment by CJKay** [comment]
Hi, this is not Husky's responsibility. I introduced this to my own project [here](https://github.com/ARM-software/arm-trusted-firmware/tree/master/.husky).

**Comment by typicode** [comment]
Thanks for sharing @CJKay 👍 
Closing as it solves the issue.
