### ISSUE TITLE
Please mention set command in docs!

### ISSUE THREAD

**Issue by julix-unity** [typicode/husky#1085]
# Docs don't mention `set` command, only `add`

![Screen Shot 2021-12-21 at 3 48 22 PM](https://user-images.githubusercontent.com/69219981/147012574-9bb725a0-c3ee-4646-b408-84f172640658.png)

![Screen Shot 2021-12-21 at 3 48 35 PM](https://user-images.githubusercontent.com/69219981/147012587-c310901c-b82a-48c8-a362-2fa0b8d4e493.png)

### This lead me on a crazy goose chase

* I had the `add` run as `postinstall` hook, which kept appending the command every time `npm install` runs (logically) - so that doesn't work.
* I considered adding the generated files to version control and running just the `chmod` in the postinstall hook. I didn't realize I can mark scripts as executable in git. (I am still not sure if that would just make it work locally as well when cloning the project?) - but chmod isn't very win friendly.
* Started looking into doing it via a js script and looked at how husky "[does it](https://github.com/typicode/husky/blob/main/src/index.ts)" -- I couldn't see any mention of `fs.chmodSync` or the like, which I needed when trying to do it myself locally. Only much later did I discover `{ mode: 0o0755 }` is provided as argument to the writeFileSync! 👍 - sanity restored

Eventually I found this [here](https://github.com/typicode/husky/issues/934) and learned:

- you can mark version controlled files as executable (does that then just work locally when you clone it?)
- there's a `husky set` command, which obviously doesn't append.

That shouldn't have taken as long as it did and I blame the docs.

> Verify that hook files are executable. This is automatically set when using `husky add` command but you can run `chmod +x .husky/<hookname>` to fix that.

The main solution seems to be targeted at people trying to set up tooling locally. 

Configuring the editor does it better (i.e. linting on save rather than on commit) - the point for me of a tool like Husky is making sure my entire team is "forced" to use linting automagically.

Thank you for your attention!

Julian

**Comment by typicode** [comment]
Thanks for the feedback, I'll probably update all the docs at once. There's also an API `require('husky')` which gives the same commands but programmatically.
