### ISSUE TITLE
`npx husky-init && npm install` enters an infinite loop

### ISSUE THREAD

**Issue by Otumian-empire** [typicode/husky#1087]
This keeps repeating after I run `npx husky-init && npm install`

```
husky-init updating package.json
  "husky install" command already exists in prepare script, skipping.
husky - Git hooks installed
husky - created .husky/pre-commit

please review changes in package.json
```

My system
- Ubuntu 16
- node v16.11.0
- npm 8.0.0
- and Typescript project (Didn't happen in js project)

**Comment by haneenmahd** [comment]
Didn't happen to my Typescript project.
I have been looking to try out **husky** for the first time.
If you want to checkout the source [here](https://github.com/imagable/imagable)

**Comment by typicode** [comment]
I can't reproduce the issue. I don't think it's related to husky though.

**Comment by Otumian-empire** [comment]
Okay..  Thanks anyway.. I appreciate it
