### ISSUE TITLE
Git hooks fail to replace environment variable. 

### ISSUE THREAD

**Issue by carpben** [typicode/husky#1088]
When I run run commits for the CLI the environment variable on my mac is properly replaced. But when I try to commit from SourceTree it fails, and I get this error message: 
```
husky > pre-commit (node v14.16.1)
Error: Failed to replace env in config: ${GITHUB_TOKEN}
```

A similar issue was opened in 2017, and closed in 2019, but still reported by users https://github.com/typicode/husky/issues/131. Can we give it another look? Or at least explain why it has was closed?

**Comment by belgattitude** [comment]
FWIW, as NPM_TOKEN is not needed for most hooks... I tend to just to edit the hooks (precommit...) and add the env there. 

So I'm sure it's there if the shell miss it.

```
#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

NPM_TOKEN=UNUSED yarn lint

```

**Comment by typicode** [comment]
Hi @carpben,

Thanks for sharing your solution on SO :)

Based on this, it seems like GUI don't have access to environment variable. I don't have a Mac but your solutions seems fine.

As an additional way to solve it, you can also source `.bashrc` or `.zshrc` in `.huskyrc`, your GUI should have access to the same variables as your terminal without having to use `open /Applications/...`.

**Comment by eloisetaylor5693** [comment]
> FWIW, as NPM_TOKEN is not needed for most hooks... I tend to just to edit the hooks (precommit...) and add the env there.
> 
> It's a hack, but might be helpful
> 
> ```
> #!/bin/sh
> . "$(dirname "$0")/_/husky.sh"
> 
> NPM_TOKEN=UNUSED yarn lint
> ```

This fixed it for me.  Searched for ages for this simple workaround
