### ISSUE TITLE
`npx husky install` doesn't work on the powershell terminal inside vscode

### ISSUE THREAD

**Issue by kaysond** [typicode/husky#1096]
**Troubleshoot**
- [X ] Before creating an issue, please check:
https://typicode.github.io/husky/#/?id=troubleshoot

If you're migrating from husky 4, see:
https://typicode.github.io/husky/#/?id=migrate-from-v4-to-v7

**Context**
Working on a fairly fresh workspace in vscode with husky 7.0.4, npx 8.1.2

If I open a powershell terminal from within vscode and run `npx husky install` in my root directory, nothing happens. There's no output whatsoever, and it doesn't create a `.husky` directory. If I run the exact same command in an external powershell terminal, it works just fine.

**Comment by typicode** [comment]
Hi,

I'm not using Windows currently so can't really help here.
I don't think anything can be done on husky's side.

I would check if there's the same issue with other commands started with `npx`.

**Comment by kaysond** [comment]
It was just husky that had the problem (`npx eslint` worked fine). But in any case, re-creating my repo/workspace seems to have fixed it.

**Comment by Handaz** [comment]
> It was just husky that had the problem (`npx eslint` worked fine). But in any case, re-creating my repo/workspace seems to have fixed it.

Were you able to fix this issue? I have the exact same one

**Comment by kaysond** [comment]
@Handaz it fixed itself. no idea what the issue was sorry
