### ISSUE TITLE
commit-msg hook fails when using a git client (Fork)

### ISSUE THREAD

**Issue by eMdOS** [typicode/husky#1097]
**Troubleshoot**
- [x] Before creating an issue, please check:
https://typicode.github.io/husky/#/?id=troubleshoot

**Context**
Please describe your issue and provide some context:
#### Terminal or GUI client (PowerShell, Git Bash, GitHub Desktop, ...)
- `Fork` git client 

#### Content of the failing hook

```sh
#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npx --no -- commitlint --edit 
```
 
#### Minimal steps to reproduce the issue

When I commit changes directly from the `Terminal` it works great (as expected), BUT when trying to commit changes by using the `Fork` client, I do get the following error:

```
.husky/commit-msg: line 4: npx: command not found
husky - commit-msg hook exited with code 127 (error)
```

It seems like it isn't finding `npx`. I've set the recommended config to the `.huskyrc` file in the troubleshooting guide, but still not working.

Thanks in advance!!

**Comment by gstvds** [comment]
@eMdOS
Apparently, this happens because Fork can't load the `PATH` properly
As a quick fix, you can open Fork using the CLI `open -a Fork.app`.

**Comment by typicode** [comment]
Thank you @gstvds

You can add `echo $PATH` to `commit-msg` to compare PATH in the terminal and Fork. Alternatively you can also use `~/.huskyrc` to modify PATH before `commit-msg`.
