### ISSUE TITLE
husky install not found for deploy in Google Cloud Function

### ISSUE THREAD

**Issue by lucascognamiglio1** [typicode/husky#1100]
**Troubleshoot**
- [x] Before creating an issue, please check:
https://typicode.github.io/husky/#/?id=troubleshoot

If you're migrating from husky 4, see:
https://typicode.github.io/husky/#/?id=migrate-from-v4-to-v7

**Context**
the script "prepare" in my local system, function correctly, but when i start the script "deploy" for deploy the application in the google cloud functions, i receive this issue:

'ERROR: (gcloud.functions.deploy) OperationError: code=3, message=Build failed: > application@0.0.1 prepare
> husky install

sh: 1: husky: not found
npm ERR! code 127
npm ERR! path /workspace
npm ERR! command failed
npm ERR! command sh -c husky install`

**Version of husky:** 7.0.4

**Comment by typicode** [comment]
Hi @lucascognamiglio1,

`prepare` script needs to be disabled.
See ttps://typicode.github.io/husky/#/?id=disable-husky-in-cidocker

**Comment by lucascognamiglio1** [comment]
Okay, thanks @typicode
