### ISSUE TITLE
Issue with packageManager variable in husky.local.sh

### ISSUE THREAD

**Issue by fnandoz21** [typicode/husky#1101]
For some reason, in my project, after running npm install in my project, the husky.local.sh file run on my project when I try to commit is formatted incorrectly. It has:
`packageManager="npm`
`cd "."`

As you can probably see, it is missing the closing quotation around npm. My commit then fails because of this. When I manually fix this file to the following, it works: 
`packageManager="npm"`
`cd "."`

If someone could advise as to why this is the case and how I could perhaps resolve this, I would appreciate it. Thanks.

**Comment by typicode** [comment]
Hi @fnandoz21,

This looks like husky 4, I would suggest upgrading to the latest version.

**Comment by fnandoz21** [comment]
Ok, which version do you recommend?

**Comment by typicode** [comment]
Latest is v7.0.4, there's a migration guide and CLI
https://typicode.github.io/husky/#/?id=migrate-from-v4-to-v7
