### ISSUE TITLE
[question] should i install husky again after cloning a git repositry?

### ISSUE THREAD

**Issue by zzzgit** [typicode/husky#1105]
There's a project on `GitHub` which uses `husky`. 

After cloning it to my computer, should I install it again by running `npx husky install` to have husky work?

**Comment by typicode** [comment]
It should be installed automatically after `npm install` (or equivalent) if the project has a `"prepare": "husky install"` script in `package.json`

**Comment by shinelp100** [comment]
`postinstall` will be better for `prepare` in npm package registry
