### ISSUE TITLE
[Question] How to bypass pre-push for some specific push actions

### ISSUE THREAD

**Issue by thegoatherder** [typicode/husky#1107]
I understand that I can bypass pre-push manually like:

```bash
git push --no-verify
```

Is there any way to configure husky so that it **always** will `no-verify` in the following circumstances:

```bash
# push git tags 
git push --tags 

# delete a remote branch
git push origin :branchname
```

So that my developers don't have to remember this or read a readme/documentation to figure it out.

I would still like it to run pre-push on any other normal push e.g.

```bash
git push
git push origin branchname
```

**Comment by typicode** [comment]
Hi @thegoatherder,

See https://git-scm.com/docs/githooks#_pre_push there are maybe params that you can use in a condition to exit with 0 and therefore skip the hook.

**Comment by thegoatherder** [comment]
@typicode thanks for the feedback. I’m not sure I understand what params you’re referring to on that help page? How can I tell from husky whether the user pushed tags or deleted a branch? Can you give a short example to put me in the right direction?

It occurs to me that I could use some regex checks against the user command ran to see  for example if it ends with `-tags` or `:branchname`? It doesn’t seem like a very robust approach though against command edge cases.
