### ISSUE TITLE
npm install using tgz doesn't work

### ISSUE THREAD

**Issue by shareefj** [typicode/husky#1109]
Terminal: Bash

Sorry, this may well be a user issue but I'm a noob so I'll ask here first.  I'm trying to install on a cluster machine where I have to jump through hoops to get ports opened to the real world so I tried installing using the tarred source files and it failed.  I then moved to a machine that has internet access to debug a bit more and I still can't install from the downloaded tar file.  Should I be able to or am I misunderstanding the npm help?

So I can do `npm i husky` with no issues but `npm i husky-7.0.4.tar.gz` seems to succeed but there's nothing in the .bin directory:

```
sjalloq@JALAPINO:~/testing$ npm i husky-7.0.4.tar.gz

added 1 package, and audited 2 packages in 780ms

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities
sjalloq@JALAPINO:~/testing$ ll node_modules/
total 16K
drwxr-xr-x 3 sjalloq sjalloq 4.0K Feb 25 19:07 .
drwxr-xr-x 3 sjalloq sjalloq 4.0K Feb 25 19:07 ..
-rw-r--r-- 1 sjalloq sjalloq  522 Feb 25 19:07 .package-lock.json
drwxr-xr-x 7 sjalloq sjalloq 4.0K Feb 25 19:07 husky
```

**Comment by typicode** [comment]
Hi, try downloading tar from npm with `npm pack husky`. It will be the compiled version with the right folders.
