### ISSUE TITLE
Silence echos

### ISSUE THREAD

**Issue by milesj** [typicode/husky#111]
I'm loving husky so far as it makes hook management super easy. However, the output of husky is a bit much. It would be nice if we could disable all the `echo`s that occur within the bash scripts.

**Comment by dsernst** [comment]
Yes, I found all these:

```
husky > pre-commit (node v12.12.0)
```

messages distracting and unnecessary for my use-case.

So using [patch-package](https://www.npmjs.com/package/patch-package), I simply commented out this  `console.log`: 

`husky+4.2.5.patch`
```patch
diff --git a/node_modules/husky/lib/runner/index.js b/node_modules/husky/lib/runner/index.js
index 861eb91..a602954 100644
--- a/node_modules/husky/lib/runner/index.js
+++ b/node_modules/husky/lib/runner/index.js
@@ -28,7 +28,7 @@ function getCommand(cwd, hookName) {
     return config && config.hooks && config.hooks[hookName];
 }
 function runCommand(cwd, hookName, cmd, env) {
-    console.log(`husky > ${hookName} (node ${process.version})`);
+    // console.log(`husky > ${hookName} (node ${process.version})`);
     const { status } = child_process_1.spawnSync('sh', ['-c', cmd], {
         cwd,
         env: Object.assign(Object.assign({}, process.env), env),
```
Much cleaner 😄

**Comment by typicode** [comment]
Husky v5 output is less verbose (not completely silenced though). Closing this issue.
Thanks for the feedback.
