### ISSUE TITLE
Add support to skip install when CI=true

### ISSUE THREAD

**Issue by glensc** [typicode/husky#1112]
Context: Setting up Husky in CI is usually pointless, `git` usually used as read-only, not making commits in CI. But having `.git/hooks` initialized with husky can cause trouble if the next CI job is without `node_modules` and CI Runner has not provided clean `.git`.

Disabling husky install can be done with testing for `$CI` value:

```diff
"scripts": {
- "prepare": "husky install"
+ "prepare": "test -n \"$CI\" || husky install"
}
```

However, that is not portable (no POSIX shell on windows), so perhaps add `--skip-ci` option to `husky install` command:

```diff
"scripts": {
- "prepare": "husky install"
+ "prepare": "husky install --skip-ci"
}
```

**Comment by glensc** [comment]
Background:

We use GitLab CI, and the pipeline is composed of multiple jobs:
- setup node_modules
- run tests, validation
- run npm publish

the npm publish is without node_modules because it is not needed for the job, but .git/hooks is (sometimes) filled with workspace of previous job, which means hooks run huskuyl but huskuy is not present.

Indeed, it may be a gitlab bug that .git/hooks is not made prestine for next job, but you can't complain on them, because there's no easy way to do that properly.

**Comment by mondeja** [comment]
You can use a global installation of the [`is-ci` npm package](https://www.npmjs.com/package/is-ci) as is described in the Husky documentation section ["With is-ci"](https://typicode.github.io/husky/#/?id=with-is-ci). Just install it with `npm i -g is-ci`, so no need for a local `node_modules`.

**Comment by glensc** [comment]
Depending on global state is not portable.

**Comment by mondeja** [comment]
I suppose that the only portable fix would be to vendor the is-ci package or their intenal logic with Husky. What other options do you propose?

**Comment by glensc** [comment]
I proposed `--skip-ci` option, why should I propose something else?

and no need to vendor, at the time "prepare" script is present, `husky` and `node_modules` are there.
