### ISSUE TITLE
我的husky不能执行，我不知道为什么？

### ISSUE THREAD

**Issue by BianXuerui** [typicode/husky#1113]
hint: The '.husky/pre-commit' hook was ignored because it's not set as executable.
hint: You can disable this warning with `git config advice.ignoredHook false`.
hint: The '.husky/commit-msg' hook was ignored because it's not set as executable.
hint: You can disable this warning with `git config advice.ignoredHook false`.

Thank you!

**Comment by HeVictor** [comment]
Hi @BianXuerui

I was actually encountering the same problem as this just now. The error message just means you need to change your `pre-commit` and `commit-msg` files to be executable. See if running `chmod +x .husky/pre-commit` and `chmod +x .husky/commit-msg` from the same directory and doing a commit again will work.

**Comment by typicode** [comment]
Thanks @HeVictor this the correct solution :+1:

**Comment by BianXuerui** [comment]
Thanks @HeVictor

**Comment by qiguiao** [comment]
Thank you!

**Comment by mczhaozl** [comment]
Thank you for your tips, very useful @HeVictor
