### ISSUE TITLE
Improve uninstall docs

### ISSUE THREAD

**Issue by vhscom** [typicode/husky#1114]
The issue is that there are two different places in the docs providing uninstall instructions for Husky and neither of them worked for me. Even after following the docs and a number of different suggestions in the various related GitHub issues I kept seeing messages like:

```
Can't find Husky, skipping commit-msg hook
You can reinstall it using 'npm install husky --save-dev' or delete this hook
```

This is very confusing as the instructions for uninstalling (both of them, if I recall correctly) suggest re-installing Husky. Please change this and make one way to uninstall husky that works across the board. If it's potentially destructive tell the user to back-up their hooks first then make it manual if necessary so I don't have to install anything to remove software I've already uninstalled.

**Troubleshoot**
- [x] Before creating an issue, please check:
https://typicode.github.io/husky/#/?id=troubleshoot

**Context**
Please describe your issue and provide some context:
- Terminal or GUI client (Git Bash)
- If applicable, content of the failing hook (most hooks, until they're deleted)
- If possible, minimal steps to reproduce the issue: Uninstall husky

**Comment by typicode** [comment]
Hi,

You seem to be upgrading from husky 4 (at least this message can be found in husky 4 code). In the past, when upgrading/uninstalling `npm` would run husky 4 uninstall script automatically. With recent versions of npm, this behavior has been disabled and as a consequence there are hooks left in `.git/hooks`.

To fix that you can run `rm -rf .git/hooks` (check before that you don't have any personal hook in there).

**Comment by vhscom** [comment]
That's what I ended up having to do.

**Comment by vhscom** [comment]
That's what I ended up having to do more or less. Only I waited until I saw Husky messages and deleted only those individual hooks to be more surgical about it. Perhaps uninstall could loop over any hook using Husky, create a backup, then remove that particular hook until each hook using Husky has been cleared.
