### ISSUE TITLE
CI detected takes ages

### ISSUE THREAD

**Issue by JPeer264** [typicode/husky#112]
On AppVeyor and TravisCI my builds always take 3 more minutes with the `skip CI`. Wouldn't it be better to make a `if / else` in `bin/install.js` rather than a `process.exit(0)`?

**Comment by typicode** [comment]
That's stange, I'm not noticing any particular slowness on TravisCI/AppVeyor with Husky.
Maybe others can relate?

That said, `process.exit(0)` should immediately exit. Do you think you could have other things running after?

**Comment by JPeer264** [comment]
Sorry I didn't see that reply. I guess `process.exit(0)` cause this behavior, as this will exit the entire nodejs program.

**Comment by JPeer264** [comment]
I also cannot reproduce it anymore.

**Comment by typicode** [comment]
Glad it's solved, thank you for the update
