### ISSUE TITLE
PNPM latest husky version is stuck on 4.3.0

### ISSUE THREAD

**Issue by yairEO** [typicode/husky#1120]
```
$ pnpm --version
6.32.3
```

`$ pnpm up husky` only installs version `4.3.0` as the latest one. 
Trying to install high results in an error as so:

> *No matching version found for husky@7.0.4*

**Comment by typicode** [comment]
Hi, I don't think anything can be done on husky's side. Sorry.

**Comment by yairEO** [comment]
Just want to inform you and you can continue taking it with the *pnpm* people I guess.. 

This is only happening with `husky` but not with lots of other libs I've been using, which is strange.

**Comment by typicode** [comment]
Thank you. However I can't seem to reproduce:

```
❯ pnpm i husky@latest
Packages: +1 -47
+-----------------------------------------------

dependencies:
- husky 4.3.8
+ husky 7.0.4

Progress: resolved 1, reused 0, downloaded 1, added 1, done
```

It may be something local to your project (maybe some cache?). I don't know pnpm enough to help here though.
