### ISSUE TITLE
HUSKY_SKIP_INSTALL doesn't seem to be working

### ISSUE THREAD

**Issue by nicknisi** [typicode/husky#1128]
**Troubleshoot**
- [x] Before creating an issue, please check:
https://typicode.github.io/husky/#/?id=troubleshoot

It seems like `HUSKY_SKIP_INSTALL`, introduced in #178 is no longer preventing husky install in v7 (or since the change to set `core.hooksPath` rather than adding hooks to `.git/hooks`. Is this option no longer supported, or is there a way to prevent hooks installation for those who do not want them set up in their clones? Thanks!

**Comment by SleepWalker** [comment]
I think this is an answer:

![image](https://user-images.githubusercontent.com/2536916/161479654-50d572f8-b488-4945-9142-9f0d43ff7f66.png)

https://github.com/typicode/husky/search?q=HUSKY_SKIP_INSTALL

**Comment by friederbluemle** [comment]
Related: #468
Unless you really have to use husky, I'd recommend to remove it from your repo, for two simple reasons:

1. Running side effects as part of standard Git operations can be done without Husky (e.g. by editing default hooks in `.git/hooks`)
2. Trying to enforce checks client side makes little sense, as these checks can easily be skipped with `--no-verify`, so Husky hooks are **not** a replacement for a proper CI setup
