### ISSUE TITLE
GIT_PARAMS

### ISSUE THREAD

**Issue by sospedra** [typicode/husky#113]
is always empty :/

`"precommit": "echo $GIT_PARAMS"`

node v7.4.0
husky v0.13.3

**Comment by pcoltau** [comment]
I also have this issue - any workaround for this?

**Comment by pcoltau** [comment]
I investigated the issue further and concluded that this is in fact not an issue in husky.

The different available git hooks all have various parameters. The git hook "pre-commit" does not take any parameters, so `$GIT_PARAMS` will always be empty for this hook. On the other hand the git hook "prepare-commit-msg" has one to three parameters. See more at https://git-scm.com/docs/githooks

**Comment by JohnAllen** [comment]
Anyone fix this?  When I run my `prepare-commit-msg` in .git/hooks it works properly and the commit-message is available as $1 but no additional params are passed when using husky.

**Comment by TechQuery** [comment]
@JohnAllen , you can get the **commit message** by code like below:

```JavaScript
require('fs').readFileSync( process.env.GIT_PARAMS );
```

**Comment by BigZ** [comment]
`"commitmsg": "./bin/commit-checks.sh ${GIT_PARAMS}"`

works for me.
$1 will contain the filename, and you can get the commit message with
`msg=$(cat $GIT_PARAMS)`

**Comment by typicode** [comment]
I think it's safe to close the issue. Feel free to update if you still have this issue with `husky@next`.

**Comment by tanguyantoine** [comment]
Using `HUSKY_GIT_PARAMS` fixed the issue for me

**Comment by Inchill** [comment]
Neither GIT_PARAMS nor HUSKY_GIT_PARAMS works incorrectly. Does someone has the same case?

**Comment by ajsaraujo** [comment]
Note that HUSKY_GIT_PARAMS was only supported in v4, v7's API is different. Check https://typicode.github.io/husky/#/
