### ISSUE TITLE
Using the add command multiple times

### ISSUE THREAD

**Issue by shezhangzhang** [typicode/husky#1130]
When I use the add command multiple times, the result will be like this:

<img width="310" alt="S pre-commit" src="https://user-images.githubusercontent.com/26793777/160319166-0318e17e-6174-4c74-8f55-97aa377beeb1.png">

So the question is: if user add the same command `multiple times`, can it be added only once, ignoring redundant additions?

**Comment by typicode** [comment]
hi,

there's also `set` command but it replaces everything. You can also `require` husky if you need to script things.
