### ISSUE TITLE
Incorrect alternative command in the documentation to add a hook on Windows machines

### ISSUE THREAD

**Issue by MarcoSimon** [typicode/husky#1133]
I'm working in a Windows (10) environment, using node 14.16.1 which is coming with npm 6.14.12

When following the [instructions in the documentation to 'Create a hook'](https://typicode.github.io/husky/#/?id=create-a-hook), I'm running into a problem that is described in your documentation: the help message appears instead of adding the hook.

Command: `npx husky add .husky/pre-commit "npm run pretest"`

Output:
```
Usage:
  husky install [dir] (default: .husky)
  husky uninstall
  husky set|add <file> [cmd]
```

In this case, your documentation says:
![2022-04-21 15_55_04-Window](https://user-images.githubusercontent.com/6904649/164474099-c5019635-8d02-437d-b54f-59645fa2121e.png)

So I tried `node node_modules/.bin/husky add .husky/pre-commit "npm run pretest"`.

But then I'm receiving the following error message:

```
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
```

There are three errors in this command: as it is not a JavaScript file it must not use the 'node' command, but to execute the .cmd file. And the slashes have to be changed to back slashes.

Finally, the following command will work as expected:
`node_modules\.bin\husky.cmd add .husky/pre-commit "npm run pretest"`

P.S.: When using node 16.13.0 with npm 8.1.0, everything works fine as you wrote in the documentation.

**Comment by typicode** [comment]
Thanks for the heads up. I've updated docs, it should be good now.
