### ISSUE TITLE
Node not recognized on Windows

### ISSUE THREAD

**Issue by nicflower** [typicode/husky#1135]
**Context**
I am setting up a precommit hook on an existing electron project (on Windows) using Husky (7.0.0). To install Husky I followed the documentation and the .husky folder was correctly created with the two files: husky.sh and pre-commit.

So now before commiting the test script should be run (the test script consists just in running jest, i.e. "test":"jest"). But when I run git commit (from terminal) it fails with this output: 

 ![output](https://user-images.githubusercontent.com/50106721/165294039-719b63ae-703f-4a81-bf04-2fa0deaaafd7.png)

The error message states that git is not able to find node, but what it looks really strange are the first two lines of the ouput, which are suggesting that jest actually run. I am using node 18.0.0 (managed via nvm-windows) and npm 7.24.2 (these two are confirmed both in powershell:

![windows terminal](https://i.stack.imgur.com/FCVyZ.png) 
and in git bash: 
![git bash](https://i.stack.imgur.com/KN7Kp.png)
).

The path to node is already in my $PATH environment variable.
It looks like my problem is that double quotes that are shown on "node" but I can  not find any node entry both in git-bash or in the powershell.

**Comment by ioofy** [comment]
got this error too, is there any solutions? or you just solved by yourself?

**Comment by nicflower** [comment]
@ioofy unfortunately I was not able to find any "clean" solution. The only way I found to make things work at the moment is forcing a call to the windows powershell, in this way:
![image](https://user-images.githubusercontent.com/50106721/167367883-b0768188-2581-4695-9d74-999df0eeb02b.png)
But this is just a workaround and I would like to remove it as soon as possible

**Comment by nicflower** [comment]
ehi @ioofy, I was finally able to solve this, I link the stackoverflow question [here](https://stackoverflow.com/questions/71950446/node-not-reconized-with-git-hook-on-windows/72446078#72446078)

**Comment by louiebb** [comment]
in win10 do not use nvm,  if use nvm when git commit will clg 'Node not recognized'，please delete related nvm eg: 'install files' , ‘sys env’ Reset computer

**Comment by Shuo-Mr** [comment]
Hey, thank you for your prompt. Finally, an abnormal environment variable was discovered, which was preceded by an ';' 
![image](https://github.com/typicode/husky/assets/50469430/f1a5e900-2066-48f8-99d3-c6b7a0840eb9)
