### ISSUE TITLE
Husky with zsh/ohmyzsh

### ISSUE THREAD

**Issue by m-avagyan** [typicode/husky#1140]
## Running pre-commit hook with zsh (version 7.0.0)

**When I try to run husky from zsh (ohmyzsh) pre-commit hook not worked**
**I use conventional commits rules, but I can commit that's all I want.**

**Comment by sowizz** [comment]
@m-avagyan did you solve the issue? If so, how?

**Comment by m-avagyan** [comment]
oh, yes! The husky script isn't executable and we can't run it for example `./husky.sh` in mac or linux, so we need to make it executable. We can do it with running `chmod +x .husky/*` command from main directory in project

**Comment by ryancwalsh** [comment]
`chmod +x .husky/*` did not work for me.

I still get:
```
> git -c user.useConfigOnly=true commit --quiet --allow-empty-message --file -
fatal: cannot run .husky/pre-commit: No such file or directory
```
https://github.com/lint-staged/lint-staged/issues/1354

**Comment by m-avagyan** [comment]
@ryancwalsh are you sure that you have .husky/ dir?

**Comment by ryancwalsh** [comment]
Yes, I do have that directory.

An update is that I found out that lint-staged and husky are working fine in Ubuntu's terminal, so I'll try figure out what's wrong with VSC.

https://github.com/lint-staged/lint-staged/issues/1354#issuecomment-1806694011

Thanks.
