### ISSUE TITLE
.husky/pre-commit: 31: [: 0: unexpected operator

### ISSUE THREAD

**Issue by MohamadKh75** [typicode/husky#1144]
**Troubleshoot**

- [x] Before creating an issue, please check:
      https://typicode.github.io/husky/#/?id=troubleshoot

If you're migrating from husky 4, see:
https://typicode.github.io/husky/#/?id=migrate-from-v4-to-v7

**Context**
Please describe your issue and provide some context:

- Terminal or GUI client (PowerShell, Git Bash, GitHub Desktop, ...):
  Terminal (bash)

- If applicable, the content of the failing hook:

```bash
#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

pnpm prettier && pnpm lint
```

- If possible, minimal steps to reproduce the issue:

1. Upgrade to v8.0.0.
2. Change pre-commit hook

Thank you!

Node: v16.15.0
pnpm: 7.0.1

**Comment by typicode** [comment]
Thanks @MohamadKh75 for the report! It should be good with 8.0.1.

**Comment by paulsouche** [comment]
I can confirm this ! :tada: 

Thank you for the quick fix
