### ISSUE TITLE
Project under the Chinese path With Husky V8

### ISSUE THREAD

**Issue by A0150315** [typicode/husky#1145]
**Troubleshoot**
- [x] Before creating an issue, please check:
https://typicode.github.io/husky/#/?id=troubleshoot

**Context**
Husky: v8.0.1

If the project is under the Chinese path, When I run "husky install", it will CRASHED. Here's the ERROR:

```
Error: Cannot find module 'D:\RN闇€姹俓release22\mcpe_rn\node_modules\husky\lib\bin.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

"RN闇€姹俓release22" means "RN需求\release22", garbled here, so "Cannot find module"

Thank you!

**Comment by typicode** [comment]
Hi @A0150315,

I don't think anything can be done at husky's level, sorry :/

**Comment by A0150315** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
