### ISSUE TITLE
[Question] How to avoid prepare script "Husky install" step when installing a npm package?

### ISSUE THREAD

**Issue by luisxiaomai** [typicode/husky#1146]
I developed a npm package with prepare script "Husky Install".  When someone install this package , it will pop up `husky: command not found` error.

I know it can be bypassed with adding "--ignore-script" when do install action, but is there another approach to disable prepare script when install this npm package?

Thank you.

**Comment by luisxiaomai** [comment]
@typicode  thanks

**Comment by Andarist** [comment]
@typicode `prepare` might get run when installing git dependencies though (mentioned in the npm's docs: https://docs.npmjs.com/cli/v8/using-npm/scripts#life-cycle-scripts ).
