### ISSUE TITLE
v8 is very slow compare to v4

### ISSUE THREAD

**Issue by unional** [typicode/husky#1148]
**Troubleshoot**
- [x] Before creating an issue, please check:
https://typicode.github.io/husky/#/?id=troubleshoot

**Context**
When upgrading from v7 to v8, I notice the commit takes much longer.
I'm using commitlint `yarn commitlint edit $1` in `.husky/commit-msg`

In v7, it finish almost immediately (within 4 seconds).
In v8, it takes 9 seconds+

I have test that by just downgrading husky from 8 back to 7, without any other change.
And that fixed the issue.

You can try it out using this repo: https://github.com/unional/path-equal

For comparison, the husky 8 version is here: https://github.com/unional/path-equal/tree/husky8

UPDATE: there are some problem with my repro steps. I'll update the issue in a moment

**Comment by typicode** [comment]
Hi,

I don't think it's related to husky. Also both examples don't load `husky.sh` script and are therefore pure Git hooks (which excludes husky as the bottleneck). I'd try looking maybe for another cause :)

Best of luck.
