### ISSUE TITLE
Amend git commit message - hangs on git commit --amend

### ISSUE THREAD

**Issue by MyNameIsOka** [typicode/husky#1151]
Hi everybody,

I am trying to setup a hook with husky which updates the commit message. 
I can see that husky is executing the script but I can't get `git commit --amend` to work.

Other `git` commands work, but `commit` is not working.

A simple version would be the following script in the folder `scripts`:
```
import { execSync } from 'child_process';

console.log("DEBUG: started prefix script");
const commitMsg = execSync('git log -1 --pretty=%B', { encoding: 'utf8' });
console.log("DEBUG: current commitMsg:", commitMsg );
execSync('git commit -m "[TEST] FOOBAR"');
```
and in package.json:
```
...
scripts: {
...,
    "prefix-commit-msg": "node scripts/prefixCommitMsg.mjs",
}
```

I then added `npm run prefix-commit-msg` to the file `commit-msg` in the `.husky` folder.

When executing `git commit -m "test"`, I can see that the script is executed but there are 2 weird things:
1. the "current commitMsg" doesn't show "test" but the previous commit message
2. After `console.log("DEBUG: current commitMsg:", commitMsg );` the script hangs

Is there anything that I am missing?

Any input is welcomed!

**Comment by SoldierAb** [comment]
> Hi everybody,
> 
> I am trying to setup a hook with husky which updates the commit message. I can see that husky is executing the script but I can't get `git commit --amend` to work.
> 
> Other `git` commands work, but `commit` is not working.
> 
> A simple version would be the following script in the folder `scripts`:
> 
> ```
> import { execSync } from 'child_process';
> 
> console.log("DEBUG: started prefix script");
> const commitMsg = execSync('git log -1 --pretty=%B', { encoding: 'utf8' });
> console.log("DEBUG: current commitMsg:", commitMsg );
> execSync('git commit -m "[TEST] FOOBAR"');
> ```
> 
> and in package.json:
> 
> ```
> ...
> scripts: {
> ...,
>     "prefix-commit-msg": "node scripts/prefixCommitMsg.mjs",
> }
> ```
> 
> I then added `npm run prefix-commit-msg` to the file `commit-msg` in the `.husky` folder.
> 
> When executing `git commit -m "test"`, I can see that the script is executed but there are 2 weird things:
> 
> 1. the "current commitMsg" doesn't show "test" but the previous commit message
> 2. After `console.log("DEBUG: current commitMsg:", commitMsg );` the script hangs
> 
> Is there anything that I am missing?
> 
> Any input is welcomed!

I am having same issue on node 17
