### ISSUE TITLE
`npx --no commitlint --edit` command works fine?

### ISSUE THREAD

**Issue by pers0n4** [typicode/husky#1157]
**Context**

- Ubuntu 18.04
- zsh 5.4.2
- Node v16.14.2
- pnpm v7.2.1

I added a `commit-msg` hook as described in document

```shell
#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx --no commitlint --edit $1
```

But this script failed with an error 

```shell
[input] reads from stdin if --edit, --env, --from and --to are omitted
# ...
[input] is required: supply via stdin, or --env or --edit or --from and --to
husky - commit-msg hook exited with code 1 (error)
```

I solved this problem by fixing the script as follows.

```shell
#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx --no -- commitlint --edit $1
```

Does this command(`npx --no commitlint --edit $1`) work for others without any problems?

**Comment by lichong-a** [comment]
I also encountered this problem. The document needs to be updated

**Comment by pers0n4** [comment]
@typicode Yes, I will create a PR that changes the document
