### ISSUE TITLE
Precommit not stopping commit from taking place

### ISSUE THREAD

**Issue by tobiasbueschel** [typicode/husky#116]
Hi :wave: 

when running `git commit` or `git push`, husky executes the linter but does not stop the commit / push from taking place even though the linting returned errors.

I have the following setup:

>package.json
```json
"lint": "standard || return 0",
"precommit": "npm run lint",
"prepush": "npm run lint"
```

> director structure
```
/root
   .git
   /docker-container-web
       package.json
   /docker-container-java
   /docker-container-redis
```

I'm running `git commit` or `git push` in the `/docker-container-web` directory.

Does anyone have some ideas / suggestion on what might cause this?

Thanks 🙂

**Comment by glebec** [comment]
Why is your lint script returning 0? It will always pass in that case. You're basically throwing away the error code from standard. Unless I am misunderstanding some aspect of shell scripting, which is very possible.

**Comment by ix-xerri** [comment]
I looks like its still happening on 0.15.0-rc7. Running `npm run lint` on `pre-commit` and it is not stopping the commit if there are listing warnings.

**Comment by alexeyten** [comment]
Warnings are not errors.

**Comment by ix-xerri** [comment]
I'm trying to stop the commit if there are any warnings/errors. With `"defaultSeverity": "warning"` or `"defaultSeverity": "error"` but the commits are happening anyway. Is there something else I should add?

**Comment by glebec** [comment]
@ix-xerri, what is `defaultSeverity` for? A linter? A plugin? And what is your script / config? How are you using Husky? There isn’t enough info in your post.

Husky is working as expected for me. If a script returns a nonzero exit code, the `precommit` hook fails and no commit is made. For us to help you debug your code we need to see what script you are using in `precommit`.

Also, the whole point of linter warnings is that they do not cause failure. Linting engines pipe warnings and success and debug info all to STDOUT. Errors are piped to STDERR. It will be difficult or unfeasible to make warnings behave the same as errors with respect to exit code etc., you may have to parse the STDOUT stream and disambiguate warnings from ordinary messages somehow, which is unstable from an API use perspective… if your linter has a way of forcing all warnings to behave like errors w.r.t. exit code, that could work but is a weird / unlikely thing for the linter to support. Otherwise what’s the difference between warning and error?

**Comment by glebec** [comment]
Thanks for the additional info. I assume your `lint` npm script just runs `tslint` then?

**Comment by ix-xerri** [comment]
I then have `"lint": "ionic-app-scripts lint",` inside `"scripts"` but I have tslint installed inside `package.json`

**Comment by glebec** [comment]
Ok… some observations:

* `defaultSeverity` applies to rules which do not themselves specify a severity level. Your rules (with `true`) will be affected, but it isn’t immediately obvious to me whether tslint’s recommended config (which you extend) specified severity levels or not.
* I would run `./node_modules/.bin/ionic-app-scripts lint` directly, with at least some rule failing, and test the exit code. It is conceivable (though unlikely) that `ionic-app-scripts` is wrapping around the TSLint output in some way which is breaking the error reporting. I am very skeptical that this is the case however.

I would have to test out this setup myself but I’m currently tapping all this out on my phone, so perhaps someone else will get to it before me. Now that we have all the details, other people can try to reproduce the error.

Good luck, —G.

**Comment by glebec** [comment]
I just set up a stock Ionic app as per https://ionicframework.com/getting-started. Husky's git hooks don't seem to be working with it, period. Debugging.

**Comment by ix-xerri** [comment]
If you look at the first example in https://github.com/typicode/husky, there is a different setup. Should I remove the husky hook and add everything in scripts?

**Comment by glebec** [comment]
@ix-xerri: The repo currently defaults to showing the `dev` branch, which is for an upcoming version of Husky. The `master` branch reflects what is currently available on npm. In the current version, hooks are placed in `scripts` and do not use a hyphen, e.g. `precommit` (not `pre-commit`).

**Comment by ix-xerri** [comment]
I'm using `0.15.0-rc.7` which is the latest tag on the dev branch

**Comment by ix-xerri** [comment]
In fact. That was the only thing left. Adding `--bailOnLintError true` did the trick! Thanks @glebec.

**Comment by tobiasbueschel** [comment]
Thanks everyone - I think we can close this issue. 🙏

**Comment by diegodesouza** [comment]
@glebec I have tried the `--bailOnLintError true` without avail, is there any other suggestion?

I tried this
```
  "husky": {
    "hooks": {
      "pre-commit": "npm run precommit --bailOnLintError true"
    }
  },
```

and this

```
scripts": {
   ...
    "lint": "lint --bailOnLintWarning true", << this or 
    "lint": "lint --bailOnLintError true", << this
    "precommit": "npm run lint",
  },
  "pre-commit": [
    "precommit"
  ],
  "husky": {
    "hooks": {
      "pre-commit": "npm run precommit"
    }
  },

```
