### ISSUE TITLE
Proposal: Unify the three README files

### ISSUE THREAD

**Issue by doublethefish** [typicode/husky#1166]
# Problem:
There are three README files

* `/docs/README.md` - seen on the docs site.
* `/README.md` - seen only in local checkouts.
* `/.github/README.md` - used as the _default_ readme on github, and only obvious there.

This leads to:
1. drift and subtle differences between the docs.
2. making contributions harder and more confusing.

# Proposal:

Move `./docs/README.md` to `/README.md`, and delete the others. Obviously, there would have to be consideration given to generating the docs site.

# Not relevant to this issue:
> 
> **Troubleshoot**
> - [x] Before creating an issue, please check:
> https://typicode.github.io/husky/#/?id=troubleshoot
> 
> If you're migrating from husky 4, see:
> https://typicode.github.io/husky/#/?id=migrate-from-v4-to-v7
> 
> **Context**
> Please describe your issue and provide some context:
> - Terminal or GUI client (PowerShell, Git Bash, GitHub Desktop, ...)
> - If applicable, content of the failing hook
> - If possible, minimal steps to reproduce the issue
> 
> Thank you!

**Comment by doublethefish** [comment]
This still needs consideration.

**Comment by FilipMaslovaric** [comment]
So which one is the correct README.md to follow, and most up to date???

**Comment by doublethefish** [comment]
> So which one is the correct README.md to follow, and most up to date???

Exactly! I’ve had PR #1167 open for a long time, but this project seems to be unsupported.

Basically, ‘./docs/README.md’ is mostly the most up to date.

**Comment by typicode** [comment]
Thanks for rising this issue. READMEs have been updated and should reflect the same usage instructions. I've answered as to why there are three READMEs in the PR.
