### ISSUE TITLE
Install or first-use instructions in readme.md fail

### ISSUE THREAD

**Issue by abelbraaksma** [typicode/husky#1169]
The `readme.md` for Husky has this line to be executed after you install Husky:

```
npm set-script prepare "husky install"
```

This `npm` command doesn't exist and just shows the npm help screen.

I found an alternative command in some PR here (#1154), which appears to be merged but doesn't show up in the `readme.md`, however, it fails just the same:

```
npm pkg set scripts.prepare="husky install"
```

And trying to run the `npm run prepare` command regardless leads to a bunch of errors, likely because the original commands don't work:

```
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path d:\Projects\Lula\billing\package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'd:\Projects\Lula\billing\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```

This is on Windows 10 with .NET 6 and npm 6.14.8, if it matters. I've no idea how to install Husky though I'd love to try it out. Anybody know how to install it properly and/or edit the `readme.md` to contain instructions that work?

**Comment by abelbraaksma** [comment]
Ok, I just realized that my `npm` wasn't up-to-date. The command from the main `readme.md` still isn't working, but the one from the PR #1154 now is.

And now, `npm run prepare` actually works.

**Comment by coolaj86** [comment]
Bump.

GitHub failed to re-render the `README.md` what's showing is out-of-sync from what's committed to the repo.

**Comment by abelbraaksma** [comment]
@coolaj86 that's weird!

**Comment by abelbraaksma** [comment]
The bot shouldn’t close this. @coolaj86, the readme still shows old instructions.

**Comment by abelbraaksma** [comment]
@coolaj86 meanwhile the change is visible. Not sure what’s changed since last time. Will close as fixed (I can’t change the label, but really, it is fixed!)
