### ISSUE TITLE
Hooks fail if user directory has apostrophe in it

### ISSUE THREAD

**Issue by luke-oneill** [typicode/husky#117]
My user directory has an apostrophe in it (I know... not a good idea, I've found similar bugs in many different scripts). This means that any hooks fail with the following message:

```
.git/hooks/pre-commit: line 39: syntax error near unexpected token `('
.git/hooks/pre-commit: line 39: `#  echo "> husky - pre-commit hook failed (add --no-verify to bypass)"'
```

The problem line in question is actually line 24 in `pre-commit`:
```
load_nvm NVM_DIR /Users/luke.o'neill/.nvm
```

I can fix manually but changing it to:
```
load_nvm NVM_DIR /Users/luke.o\'neill/.nvm
```

but I need to do this after each time I clear my node_modules and run npm install again.

**Comment by typicode** [comment]
Hi @luke-oneill,

I think husky `v0.14.2` should fix it, thanks to @yurasid's PR.
Let me know if not :)
