### ISSUE TITLE
How to use via npx?

### ISSUE THREAD

**Issue by coolaj86** [typicode/husky#1174]
How does `npm run prepare` run `package.json.scripts.prepare`, which runs `husky install`, yet husky has neither `node_modules/husky/bin/husky` nor `node_modules/.bin/husky`?

And how does `npx -p husky install` fail despite running `node_modules/husky/bin/install.js` as it should?

What black magics are afoot?

**Comment by River198** [comment]
Possibly -https://typicode.github.io/husky/getting-started.html
