### ISSUE TITLE
multi-`.husky`

### ISSUE THREAD

**Issue by abernier** [typicode/husky#1175]
In a multi-packages (aka monorepo) context, what about having one `.husky` folder per workspace (rather than a single one at root) ?

it would enable such structure:

```
.
|- .husky/
|  |- pre-push
|  `- pre-commit
|- appA/
|  |- .husky/
|  |  `- pre-commit
|  `- package.json
|- appB/
|  |- .husky/
|  |  |- commit-msg
|  |  `- pre-commit
|  `- package.json
|- ...
`- package.json
```

NB: we keep a global `.husky` root folder for global scripts

Husky should then execute each workspace's `.husky/*` scripts with workspace's path as `CWD`

**Comment by zoubingwu** [comment]
Any one tried with git workspace?

```sh
git workspace add temp
cd temp

# editing...
git add .
git commit -m "test"
```

this throws error 

```
.husky/pre-commit: line 2: .husky/_/husky.sh: No such file or directory
```

the pre-commit is like:

```sh
#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx lint-staged --config .lintstagedrc.js
```

**Comment by paescuj** [comment]
> Any one tried with git worktree?

When using git worktree with Node.js projects, I always recommend to run `npm|pnpm|yarn install` in the new tree. Ignored files/directories like `node_modules` aren't available in the new tree, so you certainly want to run this anyway, and this will also ensure that husky is installed & configured properly.

**Comment by typicode** [comment]
Closing as there's no plan to implement it inside husky. However I think it could be done with a shell script

```
<root>/.pre-commit/husky

. appA/.husky/pre-commit # sources and executes code in appA
. appB/.husky/pre-commit # sources and executes code in appB
```

This could be simplified with a function or loop
