### ISSUE TITLE
Migration to v8, issue with the directory structure

### ISSUE THREAD

**Issue by gamegee** [typicode/husky#1179]
**Context**
I want to migrate to husky v8, but I am not sure it will work with my current project directory.
I am working on a nxjs monorepo, and have such structure :

```tsx
/.git
/desktop-monorepo
  /package.json // Here is my main package.json
  /apps
  /libs
```

My package.json is not at the root level in the directory.
Is there a way to make it work ?

Thank you!

**Comment by riodw** [comment]
Is this the error that is thrown?
```
% npm set-script prepare "husky install"
npm WARN set-script set-script is deprecated, use `npm pkg set scripts.scriptname="cmd" instead.
```

**Comment by gamegee** [comment]
I have to run the script inside my folder `/desktop-monorepo`, and I have the following error :
```sh
husky-init updating package.json
  setting prepare script to command "husky install"
.git can't be found (see https://typicode.github.io/husky/#/?id=custom-directory)
```

If I run it at the root lvl I have the following error :
```sh
husky-init updating package.json
ENOENT: no such file or directory, open 'package.json'
```
