### ISSUE TITLE
Further improve experience around "node: command not found"

### ISSUE THREAD

**Issue by devinrhode2** [typicode/husky#1180]
**Context**
- GUI Client: VSCode's integrated git sidebar

Thankfully, there's a good section in the docs for this issue:
https://typicode.github.io/husky/#/?id=command-not-found

I recently tried introducing a git hook with a prettier auto-format with a new team, and some senior BE devs were really not interested in it :(

They didn't like that an npm lifecycle script was making changes to their home directory, or that it was an opt-out experience.

Anyway, I think it should be possible to avoid needing a `huskyrc` file most of the time.

Each git hook shell script starts with:
```
. "$(dirname "$0")/_/husky.sh"
```

This file _could_ detect if node is installed, although that may be a bloated.

I would imagine it's best to add a new script:
```
. "$(dirname "$0")/_/husky.sh"
. "$(dirname "$0")/_/husky-load-node.sh"
```

This `husky-load-node` script would attempt to define node for you, i.e., dynamically determine what should be in your `huskyrc` and run that code for you.

If node is not already loaded, we want to make sure we also load the right version.

We could radically simplify this by having a "recommended" version manager...

Here's outline of the logic (no code)
1. Node is undefined
  - Is there a `~/.huskyrc` file?
    A. If so, source it, continue on.
    B. If not, attempt to automatically load correct node version:
      - if `volta` is defined, do nothing, skip to after if/else
      - else if `$VOLTA_HOME` is defined, run: `export PATH="$VOLTA_HOME/bin:$PATH"`
      - else if `$HOME/.volta` directory exists, run `export VOLTA_HOME="$HOME/.volta"; export PATH="$VOLTA_HOME/bin:$PATH";`
      - else, throw error: can't find volta, can't find huskyrc, can't find node.
      - 
      - After large if/else: `volta` should be defined, run volta command to load correct node version.

Is it possible to have incorrect node version when using volta? If so, how frequently do people even run into this issue?

=====
I think nvm is too slow, but here a wip snippet to load nvm + verify node version:

```sh
export NVM_DIR="$HOME/.nvm"
GIT_ROOT="$(git rev-parse --show-toplevel)"

# Check node version when using nvm:
[[ "$(node --version)" == cat "$GIT_ROOT/.nvmrc" ]] || {
  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
  nvm use
}

```

snippet to load asdf-vm:
```sh
. "$(brew --prefix asdf)/libexec/asdf.sh"
```

**Comment by FilipMaslovaric** [comment]
>They didn't like that an npm lifecycle script was making changes to their home directory, or that it was an opt-out experience.

Good thinking.

That aside - you should also consider, if using `yarn` that you have `yarn exec` and `yarn node` at your disposal:
https://yarnpkg.com/cli/exec
https://yarnpkg.com/cli/node

**Comment by devinrhode2** [comment]
Interesting, yeah modern yarn has so many great things going for it, but they really need someone ironing out the small kinks that cost devs hours. `yarn node ./husky-script.js` could help solve this problem, but most likely, if `node` is not defined, `yarn` is also not defined. So seems like a catch-22.

I think corepack would solve this once it's available, but volta is available today...

**Comment by gpoole** [comment]
In theory it would be fine to just add the [two lines of `nvm` initialisation](https://github.com/nvm-sh/nvm#install--update-script) to your actual pre-commit hook. The script won't do anything if NVM is already available or not installed, so within a team you could assume NVM is the default use case and everyone else needs to add a `.huskyrc`, which seems reasonable to me. Unfortuantely NVM is not designed to work in a `set -e` environment though, which is how Husky runs the hook. I [had trouble with that on OSX, which is apparently expected](https://github.com/nvm-sh/nvm/issues/2080#issuecomment-515833450) and not going to be fixed in nvm. Removing the `-e` in husky.sh makes it work fine, but I assume it's being relied on by a lot of other users.
