### ISSUE TITLE
--no-install is not in the npm registry

### ISSUE THREAD

**Issue by Penggeor** [typicode/husky#1182]
This is comes from `pnpm` repository's issue: [https://github.com/pnpm/pnpm/issues/4790](https://github.com/pnpm/pnpm/issues/4790 ).

And the same problem occurs in my windows but not in my MacOS. I think this is associated with the platform. This is worthy to figure out.

**Comment by typicode** [comment]
Hi, this looks like an error related to older version of husky. I would suggest trying to upgrade.

**Comment by ehenon** [comment]
The problem still persists on my side

OS: Ubuntu 23.04
pnpm: v8.7.1
husky: v8.0.3
