### ISSUE TITLE
stale command output of npm set-script of README.md on npmjs.com and github.com

### ISSUE THREAD

**Issue by immayurpanchal** [typicode/husky#1183]
The actual File content is updated but npmjs.com and github.com show a stale value of the `npm set-script` command. 

Refer attached screenshots for better clarity.

### Path: typicode/husky/README.md 
<img width="951" alt="Screenshot 2022-08-27 at 10 09 41 AM" src="https://user-images.githubusercontent.com/17003525/187014652-51dcd1ff-6a19-4fe2-8ca9-c6a3c1caffc1.png">

### Path: https://github.com/typicode/husky/README.md
![image](https://user-images.githubusercontent.com/17003525/187014565-520b737c-f774-43db-bfd5-b3e973c8d2f4.png)

### Path: https://github.com/typicode/husky
![image](https://user-images.githubusercontent.com/17003525/187014594-21f4757f-e4e2-4a38-8941-85e82970ee27.png)

### Path: https://www.npmjs.com/package/husky
<img width="1226" alt="Screenshot 2022-08-27 at 10 04 43 AM" src="https://user-images.githubusercontent.com/17003525/187014605-a348be4a-6705-4c1b-baa0-a4e47e90d7ef.png">

**Comment by doublethefish** [comment]
The route-cause would be fixed by #1167

**Comment by typicode** [comment]
Fixed :+1: thanks for rising the issue!
