### ISSUE TITLE
Check if pushed branch is the checked out branch

### ISSUE THREAD

**Issue by voxpelli** [typicode/husky#12]
When pushing a branch it's not necessarily so that you have that branch checked out so eg. running some linting to check if the pushed code is okay will not be very accurate.

Would be nice with a simple check that matched the current checked out commit against the pushed commit and in the case of a mismatch aborted or warned about that mismatch.

Possible?

**Comment by rainboxx** [comment]
The script should have access to the STDIN that git is sending to the respective hook.

On the other side, the Bash hook could check the content itself and act on it. For for the `pre-push` hook, for example, this could just ignore the hook when deleting a remote branch:

```
read git_info;
git_local_ref=(${git_info// / });
if [ $git_local_ref = '(delete)' ]; then
  exit 0;
fi
```

This might not be what everyone wants, but the npm scripts could be more granular, have specific parameters or just pass the line along to the script as mentioned above:

```
read git_info;
npm run prepush --silent -- $git_info
```

**Comment by typicode** [comment]
Closing, thanks for the help @rainboxx. Also, for future reference, husky v1.0.0 provides now STDIN sent by Git via `HUSKY_GIT_STDIN`.
