### ISSUE TITLE
Git: nvm is not compatible with the "PREFIX" environment variable: currently set to "undefined"

### ISSUE THREAD

**Issue by bolamsydhom** [typicode/husky#1215]
**Troubleshoot**
- [ ] Before creating an issue, please check:
https://typicode.github.io/husky/#/?id=troubleshoot

If you're migrating from husky 4, see:
https://typicode.github.io/husky/#/?id=migrate-from-v4-to-v7

**Context**
Please describe your issue and provide some context:
- Terminal or GUI client (PowerShell, Git Bash, GitHub Desktop, ...)
- If applicable, content of the failing hook
- If possible, minimal steps to reproduce the issue

Thank you!

---
After using Husky to add pre-commit step in our repo, I am trying to commit using source control in vscode, and I am getting this error
![Screenshot 2022-11-13 at 1 32 19 PM](https://user-images.githubusercontent.com/45564999/201519922-a4b4157a-7fd7-4dfb-9e33-5e4e12db6ba9.png)

**Comment by typicode** [comment]
I'm not sure it's related to husky, since husky doesn't set or unset any PREFIX environment variable. I would try checking where this env variable is coming from.
