### ISSUE TITLE
The sourcetree error is garbled

### ISSUE THREAD

**Issue by liushuhui** [typicode/husky#1223]
![image](https://user-images.githubusercontent.com/26155477/206897429-8f3e7d4b-b5f6-4436-98f3-3e82e17cd8fb.png)

**Comment by paescuj** [comment]
This is more related to `lint-staged` itself... See also #968.

Which terminal do you use?

**Comment by GuoYingHAOG** [comment]
![image](https://user-images.githubusercontent.com/67637370/216225667-7ad75993-19d3-4758-a9c7-91ba2f6c35ed.png)
windows 系统，使用webstrom 自带得终端提交代码，git 效验报错，报错日志显示乱码
