### ISSUE TITLE
Permission issue with pnpm node-linker=hosited

### ISSUE THREAD

**Issue by Mister-Hope** [typicode/husky#1228]
**Troubleshoot**
- [x] Before creating an issue, please check:

**Context**

Github action log:

```
  . postinstall$ husky install
  . postinstall: sh: 1: husky: Permission denied
  . postinstall: Failed
```

Everything works fine in my project at [vuepress-theme-hope](https://github.com/vuepress-theme-hope/vuepress-theme-hope) untill I add `node-linker=hosited` to `.npmrc` for testing (I am using pnpm)

Since other packages which has postinstall (like esbuild) are not metting permission issues, I think that the fix may need to be applied here.

I did not look in through husky code yet, and I am not sure if the maintainer would like to check this first. I would be happy if you want more information, Thank you!

**Comment by Warkanlock** [comment]
Same for me, it's throwing permission denied out of nowhere inside a Github Action

**Comment by typicode** [comment]
It's weird. If you check husky's `package.json`. There's nothing fancy compared to other CLIs, so I'm not sure why it's failing.

**Comment by paescuj** [comment]
> Since other packages which has postinstall (like esbuild) are not metting permission issues, I think that the fix may need to be applied here.

Packages like `esbuild` are using `postinstall` scripts to modify the content inside their own package context while `husky` does modify outside of its context, which might be the reason why it fails here.

Out of curiosity: Why do you use the `postinstall` script instead of `prepare`?
