### ISSUE TITLE
Support git extras?

### ISSUE THREAD

**Issue by tomas-sereikis** [typicode/husky#123]
Currently husky only supports only native git hooks and this stops this possibility to be combined with git extras? Any ideas to combine them them in or to pass path to hooks.json?

**Comment by jhabdas** [comment]
@Tomas-Sereikis did `ghooks` have the same limitation?

**Comment by Tomas-Sereikis** [comment]
@jhabdas seems so

**Comment by jhabdas** [comment]
Thanks for checking @Tomas-Sereikis. Looking over TJs repo it looks like he's [trying to avoid](https://github.com/tj/git-extras/issues/150#issuecomment-10078902) anything Node-specific (solid idea IMO). Could you point to the hooks docs? I didn't see anything after a quick glance at TJs docs.

**Comment by Tomas-Sereikis** [comment]
it only has two more which are used for git release https://github.com/tj/git-extras/blob/master/Commands.md#git-release `pre-release.sh` and `post-release.sh` they take first argument as a tag if it is presented.

**Comment by hassankhan** [comment]
Similarly I'd love for Husky to support [Git Flow hooks](https://github.com/petervanderdoes/gitflow-avh/tree/develop/hooks) .

**Comment by schacki** [comment]
I would also like to see support for Git Flow hooks. Is this only a matter of extending hooks.json, or is this more complicated?

**Comment by griable** [comment]
Hi all,

I know this feed is now old but I think being able to add "custom hooks" would be convenient to some of us.

I did a [basic test](https://github.com/griable/husky/commit/e8862d9985af3710d392985a861ea8851f4a1ef8) adding [some git flow hooks](https://github.com/petervanderdoes/gitflow-avh/tree/develop/hooks) and it worked as expected.

Now I'm wondering how not to bloat this file with opinionated hook names, I'd be keen to open a PR on current / beta versions.

**Comment by typicode** [comment]
Closing as husky 5 may be more flexible in this regard and may support them (haven't tested but interested to know if someone confirms).

Thanks for the feedback :+1:
