### ISSUE TITLE
hooks aren't executable after husky install

### ISSUE THREAD

**Issue by CSchulz** [typicode/husky#1232]
After migrating from 4 to 8 we have noticed on some developer machines the hooks aren't executed.
Finally we found out that there is an issue with the executable flag of the hooks.

![image](https://user-images.githubusercontent.com/1520593/215059309-8f5f1bb6-d714-40ea-a811-24adf7937aa9.png)

Because of security reason our git repository aren't allowed to handle filemodes.

I am wondering why the scripts aren't checked by husky install because they are part of the repository now.

It would be a great addition if the scripts are automatically checked for the executable flag.

**Comment by typicode** [comment]
You mean showing warnings after `husky install`?

**Comment by CSchulz** [comment]
Yes something like that would be great. Furthermore I have found out you can disable the access flags in git (https://git-scm.com/docs/git-config#Documentation/git-config.txt-corefileMode).
Another check for this config would be good as well.

**Comment by yuntian001** [comment]
同样的问题

**Comment by typicode** [comment]
Fixed in v9. They don't need to be executable anymore.
