### ISSUE TITLE
Is this only available through NPM?

### ISSUE THREAD

**Issue by Akul2010** [typicode/husky#1235]
Is it possible to use this in a non-JS application?

**Comment by so1ve** [comment]
Yes because husky in written in JavaScript (Typescript actually, doesn't matter)

If you really want to use it in a non-js environment, try to implement it in a native language or bundle it into a executable file using pkg or nexe

**Comment by AlphaJuliettOmega** [comment]
`yarn` compatible too though right?

**Comment by so1ve** [comment]
> `yarn` compatible too though right?

yes. you can install husky via any package manager. (yarn classic, berry, npm, pnpm, bun etc.)
