### ISSUE TITLE
husky not work in  in the following circumstances

### ISSUE THREAD

**Issue by sunnywanggit** [typicode/husky#1237]
**Troubleshoot**
- [x] Before creating an issue, please check:
https://typicode.github.io/husky/#/?id=troubleshoot

If you're migrating from husky 4, see:
https://typicode.github.io/husky/#/?id=migrate-from-v4-to-v7

![image](https://user-images.githubusercontent.com/53786183/218034714-c4249eb0-e0ea-4266-adec-aa5724109306.png)

select E

![image](https://user-images.githubusercontent.com/53786183/218034781-2010e1c9-2954-4074-a816-aa18dc67a0f2.png)

edit commit message 

![image](https://user-images.githubusercontent.com/53786183/218034815-1464b7ff-40ee-4793-83e4-bee0cbde8b0a.png)

save and quit，husky not work

**Context**
Please describe your issue and provide some context:
- Terminal or GUI client (PowerShell, Git Bash, GitHub Desktop, ...)
![image](https://user-images.githubusercontent.com/53786183/218035356-5a08a556-f064-4ef0-ab43-cb2c16a7b96d.png)

- If applicable, content of the failing hook
- If possible, minimal steps to reproduce the issue

Thank you!

**Comment by sunnywanggit** [comment]
@spoike @azu @fearphage @ahutchings

**Comment by typicode** [comment]
Hi,

It's not something that can be fixed on husky's side. It's Git behavior which doesn't run the same hooks on Git revert. You can search Google for it, people are having the same kind of behavior.
