### ISSUE TITLE
Commit doesn't stop if warnings or errors found with ESLint

### ISSUE THREAD

**Issue by leonp5** [typicode/husky#1238]
I'm using [VSCodium](https://vscodium.com/) on a linux machine. The dev environment is dockerized.

VSCodium:

```
Version: 1.75.1
Release: 23040
Commit: c6a9727b801542499d2b59cb7db4224e060fc578
Date: 2023-02-09T22:41:50.017Z
Electron: 19.1.9
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.10.0-10-amd64
Sandboxed: No
```

Docker Node container:
```
Node: 18.14.0
NPM: 9.4.1
husky: 8.0.0
```

Thats the content of my `pre-commit` script.

```
docker exec dev_node npx eslint 'assets/js/**'
```

My expectaction is that the commit isn't executed if ESLint finds errors or warnings. Thats how it works when i use PHPStorm.
But when i commit via the terminal in VSCodium the errors & warnings are shown and the commit is executed.

When i use the toolbar of VSCodium to commit the changes it seems to me, that the pre-commit hook isn't executed, like it is described in [this stackoverflow post](https://stackoverflow.com/questions/71423089/vscode-issue-with-husky).

You can see my whole project here: [current feature branch](https://gitlab.com/leonp5/fws-theme/-/tree/add_blog_template)
If this link doesn't work any more, here is the [main branch](https://gitlab.com/leonp5/fws-theme/-/tree/main).

**Comment by typicode** [comment]
For commit to be stopped, command must return a non-zero exit code. Can you check if it's the case by adding `echo $?` after `docker ...` command (if it's `0` that's the reason why commit doesn't fail)

**Comment by leonp5** [comment]
Thanks for your answer :)
It's indeed `0`. Do you know, if i can change the settings in a way to change this?

**Comment by typicode** [comment]
I don't know sorry. I would search though if Docker, or something in between, doesn't hide the exit code of the command it's running. Maybe there's an option.

**Comment by leonp5** [comment]
Thanks for your support.
I would close the issue if you dont mind?

**Comment by typicode** [comment]
Sure
