### ISSUE TITLE
read -p exits with code 1 

### ISSUE THREAD

**Issue by shadowplay1** [typicode/husky#1239]
so i wrote a shell script in a `pre-commit` hook to automate some deploying things and im reading the input with `read -p "something" answer`, but whenever i do the commit, hook runs without any problems but when `read` runs, the hook is just exiting with code 1, everything before the `read` works, but nothing after it, no matter where the command is placed in the hook

terminal: termux
output: `husky - pre-commit hook exited with code 1 (error)`

steps to reproduce:
1. create a `pre-commit` hook with reading the user input:
```bash
#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

read -p "input: " test
echo "output: $test"
```
or run the command: `printf "#\!/usr/bin/env sh\n. \"\$(dirname -- "\$0")/_/husky.sh\"\n\nread -p \"input: \" test\necho \"output: \$test\"\n" > ./.husky/pre-commit.bak`
2. do a commit:
```bash
$ git commit -m "test: pre-commit input read test"
```
3. `pre-commit` hook will exit with code 1

expected the hook to run the `read` command and print the user input after but not erroring 

works fine if running this in a normal bash file:
```bash
~ $ bash test.sh
input: 12345
output: 12345
```
also, if changing `sh -e "$0 $@"` to `bash "$0 $@"` in `./.husky/_/husky.sh` file on line 24, the hook skips all the `read` commands in the script and all input variables are empty

any ideas? or there's something that i'm doing wrong?

**Comment by shadowplay1** [comment]
Uhhhh... I think this is abandoned repository and nothing will be answered here sadly

**Comment by typicode** [comment]
Search for `tty` in the issues. However reading input can be a cause of issues for GUI users.
