### ISSUE TITLE
How would you skip the hook?

### ISSUE THREAD

**Issue by kuncevic** [typicode/husky#124]
Say I did a `git commit` that triggered the `precommit` then on `git push` with `prepush`,  I realized I missed something really not introducing any issues like spelling, etc so then I do not want `precommit` and `prepush` to be run again as it time consuming and I know that everything just fine in that case. 

So how would I skip the hook to be running again ?

**Comment by onbjerg** [comment]
``git commit --no-verify`` and ``git push --no-verify`` should work?

>This option bypasses the pre-commit and commit-msg hooks. See also [githooks(5)](https://git-scm.com/docs/githooks).

**Comment by tony** [comment]
`--no-verify` only works for certain hooks: https://github.com/typicode/husky/pull/344#issuecomment-419885003

**Comment by a7madgamal** [comment]
yeah how does it work for checkout for example?

**Comment by harishekhar** [comment]
Try `git commit -n -m "your commit message"`

**Comment by chvenkat668** [comment]
Hi, All please share next steps of "git commit --no-verify" in git,

1) once I enter "git commit --no-verify" command, 
2) its asking me enter commit message after that, 
3) press "ESC" then type ":WQ" then enter, 
but its working fine my system, but its not working in other system

help me if any other alternative

**Comment by nahumzs** [comment]
@chvenkat668 do `git commit -m "your message" --no-verify` works?

**Comment by r2-d3** [comment]
This is not the best option. We use Gerrit which uses a hook to add Change-Id in the commit message. With --no-verify that is also skipped, unfortunately.

We want to keep husky but not all team members want to use it.
Would be nice to have a way to only skip husky hooks on git commit like the once introduced for git rebase HUSKY_SKIP_HOOKS=1.

**Comment by DesignByOnyx** [comment]
I'm spreading this information around as it's super useful:

As of `v2.4.0` you can now do `HUSKY_SKIP_HOOKS=1 git <command> ...`

**Comment by nick-vfip** [comment]
What about `git cherry-pick`?

**Comment by rbruelisauer** [comment]
Does not work. You'll receive an error "node: command not found" if node JS is not installed on your machine.
Installing NodeJS is not an option. The checks should be implemented in a way, so that you are not forced to install node JS if you want to skip the husky stuff.

**Comment by bivainis** [comment]
I'm usually using PhpStorm to merge conflicts, however, it doesn't have an option to disable commit hooks during merge.

Easiest solution for me:
1. Open `.git/hooks/pre-commit`
2. Comment out husky sh: `# . "$(dirname "$0")/husky.sh"`
3. Resolve merge conflicts and merge
4. Install packages: husky will overwrite pre-commit file again

Hope it helps somebody.

**Comment by antialias** [comment]
My preference is to ensure that whatever we are currently checking for in pre-commit hooks is reflected by any CI checks, and then disable pre-commit hooks altogether. There are many instances where one may make a commit that leaves the repo in an "bad" state, and this should be allowed, so long as the code does not land in master.

This is my preference of course, but from experience, pre-commit hooks have proven themselves to be too weak to be effective, and are at best a nuisance when getting a branch ready for review.

**Comment by DBullHDi** [comment]
> 
> 
> I'm usually using PhpStorm to merge conflicts, however, it doesn't have an option to disable commit hooks during merge.
> 
> Easiest solution for me:
> 
>     1. Open `.git/hooks/pre-commit`
> 
>     2. Comment out husky sh: `# . "$(dirname "$0")/husky.sh"`
> 
>     3. Resolve merge conflicts and merge
> 
>     4. Install packages: husky will overwrite pre-commit file again
> 
> 
> Hope it helps somebody.

I commented out `#. "$(dirname "$0")/husky.local.sh"`.

**Comment by Bartuz** [comment]
This is enough for me to cherry-pick without hooks:
`HUSKY_SKIP_HOOKS=true git cherry-pick --continue`
