### ISSUE TITLE
How do I make github hooks work on both windows and mac

### ISSUE THREAD

**Issue by laterdayi** [typicode/husky#1240]
**Troubleshoot**
- [√ ] Before creating an issue, please check:
https://typicode.github.io/husky/#/?id=troubleshoot

If you're migrating from husky 4, see:
https://typicode.github.io/husky/#/?id=migrate-from-v4-to-v7

I'm in the project root.husky > pre-commit

```
#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx lint-staged --no-stash
```

It works on windows, but it doesn't work on mac. How do you get windows and mac to work together

**Comment by typicode** [comment]
When creating hook on Windows, add it with `git add --chmod=+x` it will set the correct permission for macOS and Linux.
