### ISSUE TITLE
How do I automatically set chmod + x.husky /pre-commit for projects

### ISSUE THREAD

**Issue by laterdayi** [typicode/husky#1241]
**Troubleshoot**
- [√ ] Before creating an issue, please check:
https://typicode.github.io/husky/#/?id=troubleshoot

How do I automatically set chmod + x.husky /pre-commit for projects

**Comment by laterdayi** [comment]
Since it is a multi-person development, in mac environment, it is required to set chmod + x.usky /pre-commit for projects, but many people may deliberately leave it unset in an attempt to submit the wrong code to the repository

**Comment by typicode** [comment]
Scripts created with `husky add|set` are executable. If you create and commit them from macOS or Linux, there's no additional step. It'll work for everyone.

When it's created on Windows, you need to pass an additional option: `git add --chmod=+x .husky/pre-commit` for compatibility with other OS.

**Comment by laterdayi** [comment]
Many people may intentionally skip the validation commit code, so is there any way to verify or manually grant permissions on the system side

**Comment by yuntian001** [comment]
> 使用创建的脚本`husky add|set`是可执行的。如果您从 macOS 或 Linux 创建并提交它们，则没有额外的步骤。它会为每个人工作。
> 
> 在 Windows 上创建时，您需要传递一个附加选项：`git add --chmod=+x .husky/pre-commit`用于与其他操作系统的兼容性。

`husky install ` is not run `chmod`

**Comment by typicode** [comment]
Not needed anymore in v9 ;)
