### ISSUE TITLE
`git-flow` husky - pre-commit hook exited with code 1 (error)

### ISSUE THREAD

**Issue by zharinov-nikita** [typicode/husky#1242]
### Reproducing an error

1. I make a git clone from a remote repository in which husky already exists.
2. When initializing git-flow, a directory is used for hooks .husky.
3. Initialize git-flow with the command `git flow init`.
4. Executing `git add .` commands and `git -m "message"`.
5. I get an error - husky - pre-commit hook exited with code 1 (error).

### Package.json - scripts
![image](https://user-images.githubusercontent.com/101789452/222525895-51e304c9-1003-41f0-b67c-0f7abdca629e.png)

### Package.json - dependecies
![image](https://user-images.githubusercontent.com/101789452/222526403-788bc3cb-a878-418f-b292-aec119d23edf.png)

### Pre-commit
![image](https://user-images.githubusercontent.com/101789452/222526536-d151c403-3929-4969-bc94-a17391386434.png)

**Comment by typicode** [comment]
Hi,

Except if I'm missing something it's normal behavior.

One of the command in the pre-commit file exited with code 1, which made pre-commit hook fail.
For example, if `npm run lint` fails it will exit with a non-zero code and that will block the pre-commit.
