### ISSUE TITLE
fatal: not a git repository: '.git'

### ISSUE THREAD

**Issue by Omar-Radwan** [typicode/husky#1244]
I get the following error when I run `git commit`  inside a git repo
```
fatal: not a git repository: '.git'
husky - pre-commit hook exited with code 1 (error)
```
`.git` directory content
```
COMMIT_EDITMSG  HEAD  branches  config  description  hooks  index  info  logs  objects  packed-refs  refs
```
Husky version: 7.0.0 
OS: Ubuntu 18.04.6 LTS
Node version: v16.19.1

**Comment by typicode** [comment]
What's the content of `pre-commit`?

**Comment by Sgryts** [comment]
That looks like the path is incorrect or ".git" folder is missing
