### ISSUE TITLE
Conflicting git repos with Husky and WordPress

### ISSUE THREAD

**Issue by blachawk** [typicode/husky#1245]
Since Husky requires Git to be initialized in the given location where used, what do we do (in my case WordPress), when my entire WordPress site **is already** under Git repository management, and I want to use Husky in a plugin directory?  Would this not lead to a .git conflict?  Whats the technical solution in this case?

right now, within my plugin's directory at the terminal, if I run `npm run prepare`, the terminal spits back...

husky - .git can't be found (see https://typicode.github.io/husky/#/?id=custom-directory)

The issue does not appear to be lack of custom directory for .config settings, but my husky .git repo  (child), conflicting with my entire WordPress .git repo (parent).  Whats the remedy?

**Comment by typicode** [comment]
Hi, could you please share content of prepare and directory where your package.json is?

**Comment by blachawk** [comment]
This is my package.json file, that is associated to my plugin directory...

```json

{
	"name": "boilerplate",
	"version": "0.1.0",
	"description": "Example static block scaffolded with Create Block tool.",
	"author": "The WordPress Contributors",
	"license": "GPL-2.0-or-later",
	"main": "build/index.js",
	"scripts": {
		"build": "wp-scripts build",
		"format": "wp-scripts format && stylelint \"**/*.scss\" --fix",
		"lint:css": "wp-scripts lint-style",
		"lint:js": "wp-scripts lint-js",
		"packages-update": "wp-scripts packages-update",
		"plugin-zip": "wp-scripts plugin-zip",
		"start": "wp-scripts start",
		"prepare": "husky install"
	},
	"prettier": "@wordpress/prettier-config",
	"stylelint": {
		"extends": "@wordpress/stylelint-config/scss"
	},
	"devDependencies": {
		"@wordpress/eslint-plugin": "^14.1.0",
		"@wordpress/prettier-config": "^2.11.0",
		"@wordpress/scripts": "^25.5.1",
		"@wordpress/stylelint-config": "^21.11.0",
		"eslint-config-prettier": "^8.7.0",
		"husky": "^8.0.3",
		"stylelint": "^14.16.1"
	},
	"dependencies": {
		"@wordpress/block-editor": "^11.5.0",
		"@wordpress/blocks": "^12.5.0",
		"@wordpress/i18n": "^4.28.0"
	}
}
```

**Comment by typicode** [comment]
Could you try changing prepare script to `cd <path to git root from package.json dir> && husky install <path to package.json dir>/.husky`.
So if your package.json is in `plugin/` directory that would be `cd .. && husky install plugin/.husky`
