### ISSUE TITLE
Does husky not support setting by command in package scripts in v8?

### ISSUE THREAD

**Issue by laterdayi** [typicode/husky#1247]
```
  "scripts": {
    "post-merge": "npm run test"
  },
```

Does husky not support setting by command in package scripts in v8?

**Comment by laterdayi** [comment]
I don't really want to create a.husky foolder, but rather a command method, is that possible?

**Comment by laterdayi** [comment]
@typicode  Looking forward to your help

**Comment by typicode** [comment]
Hi, sorry, it's not possible. You can avoid the directory by running `husky install .` and `husky add ./post-merge "some cmd"` thought.

**Comment by laterdayi** [comment]
This means that currently husky v8 can only create hooks files from the project root directory, right?

**Comment by laterdayi** [comment]
```
.husky folder
      pre-commit
      post-merge
```

**Comment by typicode** [comment]
That's correct
