### ISSUE TITLE
Husky skipping hooks while commit from GIT GUI

### ISSUE THREAD

**Issue by krishna63** [typicode/husky#125]
Hi Everyone,

I have used husky with "validate-commit-msg" npm module, when i make the code changes and do the commits from the GIT CLI it is working, but when i try to commit from the GIT GUI, the commit-msg hook is being skipped.

Note:  nodejs is installed in my <<custom path>> , not in the "C:/Program Files/" directory

Any help would be appreciated

**Comment by onbjerg** [comment]
Possibly related to #105

**Comment by typicode** [comment]
Hi @krishna63,

Where is it installed? What installation method did you?

**Comment by krishna63** [comment]
Hi @typicode :
i intentionally installed my nodejs in a separate folder other than program files, as i will not  have admin right in office , i installed it my personal folder in  "C" drive it self where i have complete access for that folder. Doing that way i can install what ever node modules i need 

Is there any way like using of NVM or some thing that my hooks will be triggered when i try to commit the code from GIT GUI as well, Please let me know

**Comment by typicode** [comment]
Can you try adding the path to your Node installation directory in Windows PATH? Or is it restricted too?

**Comment by krishna63** [comment]
I already mentioned nodejs installation path in the PATH environment variable

**Comment by mnzaki** [comment]
I'm running into the same issue, but I think it's on the `git gui` side, seems like it commits with `--no-verify` (or at least as far as I can tell the `pre-commit` script is never even run)

**Comment by gvlekke** [comment]
same issue with sourcetree

**Comment by chrise86** [comment]
Same issue with Gitfox and Tower.

**Comment by typicode** [comment]
Cleaning old issues. Feel free to create a new one if needed.

**Comment by luanmuniz** [comment]
This is still an issue in v6

**Comment by danielmcormond** [comment]
FWIW, I found that [Gitfox](https://www.gitfox.app/) from the [App Store](https://www.apple.com/app-store/) cannot use hooks due to Apple's [sandbox restrictions](https://www.gitfox.app/support/gitfox/difference-appstore/).
