### ISSUE TITLE
Reduction of permissions in 8.0.3 bump

### ISSUE THREAD

**Issue by millsjoe** [typicode/husky#1251]
**Troubleshoot**
- [x] Before creating an issue, please check:
https://typicode.github.io/husky/#/?id=troubleshoot

**Context**
Updating from `8.0.2` to `8.0.3` causes the following in a github workflow
```
$ husky install && chmod ug+x .husky/*
sh: 1: husky: Permission denied
```
To mitigate I can revert to `8.0.2` or change the command to this
```
chmod ug+x ./node_modules/husky/lib/bin.js && husky install && chmod ug+x .husky/*
```

So although I have a way to mitigate, I can't see any reason this might have happened in a patch - do you have some insight why this might be?

**Comment by yuntian001** [comment]
I need this urgently.

**Comment by typicode** [comment]
As you said, it's probably not related to the patch (and there's probably not much that can be done on husky's side). What command do you use to install husky?

As for the permissions for hooks, you can use `git add chmod=+x ...`
