### ISSUE TITLE
Husky not displaying full error message from tsc command

### ISSUE THREAD

**Issue by hassanzohdy** [typicode/husky#1259]
**Troubleshoot**
- [x] Before creating an issue, please check:
https://typicode.github.io/husky/#/?id=troubleshoot

**Context**
When i run `npx tsc` command or even adding it in a script like:

```json
  "scripts": {
    "ts": "npx tsc --noEmit"
  }
```

Then `yarn ts`

It displays the entire error as expected like this:

![image](https://user-images.githubusercontent.com/13071138/235376722-94f5cbc0-5dd8-4e69-b151-5ad2c41fbc35.png)

But when adding that command to `.husky/pre-commit` the error is displayed like this:

![image](https://user-images.githubusercontent.com/13071138/235376747-4f1a5810-5622-4a5e-a574-3d175b302460.png)

Any idea how to fix tihs?

Thank you!

**Comment by typicode** [comment]
Sorry, I don't know. It's probably related to terminal capabilities detection (hooks run in a non interactive shell).
