### ISSUE TITLE
Cannot spawn .husky/commit-msg: No such file or directory

### ISSUE THREAD

**Issue by Bolu301** [typicode/husky#1267]
I got this error while executing git commit
I have the following .husky/commit-msg:

yarn husky add .husky/commit-msg 'npx --no-install commitlint --edit "$1"'

husky: 8.0.0
node: 18.14.0
OS: Windows 10

**Comment by typicode** [comment]
Replace it with `npx --no-install commitlint --edit "$1"` only. See https://github.com/typicode/husky/blob/main/.husky/commit-msg for reference

**Comment by Bolu301** [comment]
Thanks for this 
Don't know how I'm seeing this just now
It worked for me 
Issue resoved
