### ISSUE TITLE
Suddenly cannot commit with hook commit-msg failed Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by giangnh13579** [typicode/husky#1268]
**Troubleshoot**
- [x] Before creating an issue, please check:
https://typicode.github.io/husky/#/?id=troubleshoot

If you're migrating from husky 4, see:
https://typicode.github.io/husky/#/?id=migrate-from-v4-to-v7

**Context**
I'm using husky version `8.0.1` for checking syntax when commiting. This is my hook setting in `commit-msg`

```
#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx --no -- commitlint --edit "\${1}"
```

This worked perfectly, then suddenly I cannot commit anymore. The terminal show error:

```
/home/giangnh/access-control-system/node_modules/@commitlint/cli/lib/cli.js:114
        throw err;
        ^

[Error: ENOENT: no such file or directory, open '/home/giangnh/access-control-system/${1}'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/giangnh/access-control-system/${1}'
}
husky - commit-msg hook exited with code 1 (error)
```

The temporary fix is to remove the backslash character `\` in the hook `commit-msg`. The command became after changing: `npx --no -- commitlint --edit "${1}"`. Then I can commit again.

I wonder why this happen and there is any other way to fix solution above

**Comment by typicode** [comment]
Try removing `\` in commit-msg

**Comment by giangnh13579** [comment]
> Why do you need `\`?

@typicode It's already been in the code when I joined the project. It used to work until now.

**Comment by typicode** [comment]
I would suggest removing it. With `\$...`, `$` is escaped and the variable is not substituted with the correct path.

**Comment by giangnh13579** [comment]
> I would suggest removing it. With `\$...`, `$` is escaped and the variable is not substituted with the correct path.

Yeah, maybe this is the correct way
