### ISSUE TITLE
.husky/pre-commit: 4: pnpm: not found

### ISSUE THREAD

**Issue by VividLemon** [typicode/husky#1269]
**Troubleshoot**
- [x] Before creating an issue, please check:
https://typicode.github.io/husky/#/?id=troubleshoot

If you're migrating from husky 4, see:
https://typicode.github.io/husky/#/?id=migrate-from-v4-to-v7

**Context**
Please describe your issue and provide some context:
- Terminal or GUI client (PowerShell, Git Bash, GitHub Desktop, ...) bash
- If applicable, content of the failing hook 

```
> git -c user.useConfigOnly=true commit --quiet --allow-empty-message --file -
.husky/pre-commit: 4: pnpm: not found
husky - pre-commit hook exited with code 127 (error)
husky - command not found in PATH=/usr/lib/git-core:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
```

- If possible, minimal steps to reproduce the issue

Impossible

Thank you!

This is kind of a weird issue, one that isn't necessarily Husky's fault, but I can't gather any information on why exactly it's not working right. 

Here's the issue:
![image](https://github.com/typicode/husky/assets/31498096/94d3293a-15ca-48a3-b649-7d53c9466850)

If I use the github source control, and click commit, I then get the issue that is showed on the side of the image.

However, if I use my terminal directly it works fine.

Somewhere in between using the source control here and husky, the command is not found. 

pnpm lives at `/home/issayah/.local/share/pnpm/pnpm`
bash lives at `/usr/bin/bash`
vs code is a system package, not flatpak. 

It's a bit confusing of an issue, and I'm not sure where to look to find out how to fix the issue.

**Comment by typicode** [comment]
This is probably a PATH issue. If you run `echo $PATH` in the terminal it will contain path to pnpm.
If you start vscode from the terminal, I think it will inherit PATH from the terminal.
You can also check https://typicode.github.io/husky/troubleshooting.html#command-not-found it contains info to change PATH for GUI like vscode.

**Comment by VividLemon** [comment]
> This is probably a PATH issue. If you run `echo $PATH` in the terminal it will contain path to pnpm. If you start vscode from the terminal, I think it will inherit PATH from the terminal. You can also check https://typicode.github.io/husky/troubleshooting.html#command-not-found it contains info to change PATH for GUI like vscode.

Thank you for this information. Yes, I have tested your idea, and have found that it was because opening code through the terminal was the issue -- As I think I have only ever opened code through the terminal, now that I think about it. 

The question on my mind now is how would I go about fixing the path in this instance? Could you point me in the right direction?

**Comment by typicode** [comment]
Sure, in `~/.huskyrc` add this:

```sh
export PATH=$PATH:$HOME/.local/share/pnpm
```

It will append another directory to the PATH variable.

**Comment by VividLemon** [comment]
Thank you for your help

**Comment by typicode** [comment]
You're welcome

**Comment by JackMBurch** [comment]
> Sure, in `~/.huskyrc` add this:
> 
> export PATH=$PATH:$HOME/.local/share/pnpm
> 
> It will append another directory to the PATH variable.

.huskyrc is depreciated now, you'll have to add it to `~/.config/husky/init.sh`

**Comment by itzmail** [comment]
> > Sure, in `~/.huskyrc` add this:
> > export PATH=$PATH:$HOME/.local/share/pnpm
> > It will append another directory to the PATH variable.
> 
> .huskyrc is depreciated now, you'll have to add it to `~/.config/husky/init.sh`

thx u for your information, this work for me in this moment
