### ISSUE TITLE
husky not found when building docker image for prodction env

### ISSUE THREAD

**Issue by xulsup** [typicode/husky#1271]
package.json
```json
{
  "scripts": {
    "prepare": "husky install",
  },
  "devDependencies": {
    "husky": "^8.0.3",
  }
}
```

Dockerfile
```
FROM node:18.16.0-alpine

ENV NODE_ENV=production

COPY package.json package-lock.json ./
# Make npm install
RUN set -x \
  && apk add --update --no-cache --virtual build-deps alpine-sdk \
  && npm install --production --loglevel=warn \
  && apk del build-deps

COPY src/ ./src

CDM ["./src/entrypoint.sh"]
```
it will throw error like this:
![image](https://github.com/typicode/husky/assets/17876392/f9974bba-0b8e-49b8-8ba9-5c4973689dc7)

**Comment by typicode** [comment]
When you install with --production, devDependencies aren't installed. Since husky is a devDependency, it's not installed and so not found.

You have multiple ways to solve this error here: https://typicode.github.io/husky/guide.html#disable-husky-in-ci-docker-prod

**Comment by johanbook** [comment]
I also ran into this issue and wonder what the recommended approach is. The above mentioned link https://typicode.github.io/husky/guide.html#disable-husky-in-ci-docker-prod gives a 404.

EDIT: Found the docs at https://typicode.github.io/husky/how-to.html#ci-server-and-docker.
