### ISSUE TITLE
Husky not supporting typescript 5.1.3

### ISSUE THREAD

**Issue by jigmeloday** [typicode/husky#1273]
**Troubleshoot**
- [x] Before creating an issue, please check:
https://typicode.github.io/husky/#/?id=troubleshoot

If you're migrating from husky 4, see:
https://typicode.github.io/husky/#/?id=migrate-from-v4-to-v7

**Context**
i got issue saying ```Received malformed response from registry for ".". The registry may be down.``` after i removed yarn add . from husky pre-commit it started saying 
``` WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.
You may find that it works just fine, or you may not.
SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <5.1.0
YOUR TYPESCRIPT VERSION: 5.1.3
Please only submit bug reports when using the officially supported version.```

Thank you!

**Comment by typicode** [comment]
Probably not related to husky's code. It's probably the script called inside pre-commit that was outputting this.
