### ISSUE TITLE
Suggested update to documentation/readme

### ISSUE THREAD

**Issue by darcyparker** [typicode/husky#1275]
Please consider strengthening the recommended `prepare` script in the docs.

Sometimes the suggested `"prepare": "husky install"` script fails because it assumes the `$CWD` is a git repo.  There are edge cases where it is not... (some builds on docker don't clone the whole git repo).  And another edge case is that husky is a `devDependency` and only the `dependency` packages are installed...

I like `"prepare": "husky install || exit 0"` @Titan196 mentioned in https://github.com/typicode/husky/issues/1213#issuecomment-1307975812

Another possible solution: `"prepare": "git rev-parse &>/dev/null && husky install || echo 'Not git repo skipping husky install'"` which makes it clear we're testing for the `$CWD` being a git repo...  But perhaps not as good a solution if the user installed as husky as `devDependency` and didn't install the dev dependencies.

See https://github.com/typicode/husky/issues/1271
See https://github.com/typicode/husky/issues/1213

**Comment by typicode** [comment]
v9 doesn't fail anymore, it will just give a warning :+1: thanks for the feedback
