### ISSUE TITLE
.git/hooks/pre-commit: line 49: node_modules/run-node/run-node: No such file or directory

### ISSUE THREAD

**Issue by Tisiven** [typicode/husky#1280]
**Troubleshoot**
- [x] Before creating an issue, please check:
https://typicode.github.io/husky/troubleshooting.html

If you're migrating from husky 4, see:
https://typicode.github.io/husky/migrating-from-v4.html

**Context**
Terminal: zsh
OS: mac
IDE: vscode

```
    "husky": "^3.0.4",
    "lint-staged": "^9.2.3",
    "pnpm": "8.5.1",
    "node": "16.20.0",
    "nvm": "0.39.1",
```

After I used `pnpm i -D -w husky lint-staged`, this error occurred:
<img width="725" alt="image" src="https://github.com/typicode/husky/assets/23449533/98f28303-c0ec-4cbf-8964-74c521cb619f">

and then I checked .git/hooks/pre-commit and found this:
<img width="765" alt="image" src="https://github.com/typicode/husky/assets/23449533/a5c02f5b-a63c-4c40-a943-574f51d2fc99">

But I didn't find the run-node directory in node_modules
How to solve this problem?

Thank you!

**Comment by FriendsA** [comment]
fix path like node_modules/.pnpm/run-node@1.0.0/node_modules/run-node/run-node
