### ISSUE TITLE
Navigating to the custom directory page doesn't seem to work.

### ISSUE THREAD

**Issue by kaf-lamed-beyt** [typicode/husky#1284]
**Troubleshoot**
- [ ] Before creating an issue, please check:
https://typicode.github.io/husky/troubleshooting.html

If you're migrating from husky 4, see:
https://typicode.github.io/husky/migrating-from-v4.html

**Context**
Please describe your issue and provide some context:
- Terminal or GUI client (PowerShell, Git Bash, GitHub Desktop, ...)
- If applicable, content of the failing hook
- If possible, minimal steps to reproduce the issue

Thank you!

Navigating to this custom directory page (https://typicode.github.io/husky/#/?id=custom-directory) should redirect me to the appropriate one with the matching information.

| Where it takes me to | where it should go to correctly|
| --------------------------   | --------------------------------------- |
| ![image](https://github.com/typicode/husky/assets/48127194/f9078bd4-6ddc-43ba-aee4-6bfe2f245dcf) | ![image](https://github.com/typicode/husky/assets/48127194/e220fb77-675f-4f29-ad06-572459748712) |

**Comment by NomanGhiasy** [comment]
I'm having the same issue.

**Comment by AVor0n** [comment]
This has already been fixed (#1274)

**Comment by kaf-lamed-beyt** [comment]
I don't think so. I clicked the link just now and the issue still persists

**Comment by AVor0n** [comment]
> I don't think so. I clicked the link just now and the issue still persists

It's just that the last release was on January 3rd. Fix were added on June 8. So you just need to wait for the new release to make everything work

**Comment by kaf-lamed-beyt** [comment]
Oh! 

If that's the case then

**Comment by typicode** [comment]
Closing since this path doesn't exist anymore in the new doc.
