### ISSUE TITLE
Make sure the hooks work.

### ISSUE THREAD

**Issue by infacto** [typicode/husky#1291]
It seems that the hooks don't work from time to time. In this case you will not recognize it because there is no error. It's just skipped. The solution is to remove `node_modules` and `npm i` again. We currently use v4. I'll test v8. But that is not reproducible. Anyway... How to check if the hooks are present? If there is no way, we could implement it.

```json
{
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged"
    }
  },
  "lint-staged": {
    "*.{ts,js}": "eslint",
    "*.scss": "stylelint",
    "*.{ts,js,json,scss,css,html}": "prettier --write"
  }
}
```

**Comment by typicode** [comment]
husky v4 used `postinstall` to automatically install hooks. With modern package scripts, this gets cached so it runs only once.

This is solved with v8 so I'd suggest upgrading. There's a sections in the docs for migrating.
