### ISSUE TITLE
Unable to create commits when husky.sh variables are readonly

### ISSUE THREAD

**Issue by FarzamMohammadi** [typicode/husky#1294]
**Troubleshoot**
- [x] Before creating an issue, please check:
https://typicode.github.io/husky/troubleshooting.html

If you're migrating from husky 4, see:
https://typicode.github.io/husky/migrating-from-v4.html

**Context**
Please describe your issue and provide some context:
- Terminal or GUI client (PowerShell, Git Bash, GitHub Desktop, ...)
- If applicable, content of the failing hook
- If possible, minimal steps to reproduce the issue

Thank you!

**Issue Description**
After installing npm packages, a 'husky.sh' file is created containing two 'readonly' variables. These variables prevent both GitHub Desktop and VSCode from creating commits, resulting in the following error:

GitHub Desktop:
![image](https://github.com/typicode/husky/assets/72108716/b66e3308-b132-41e7-adca-83af2b5ea14d)

VSCode:
![image](https://github.com/typicode/husky/assets/72108716/f6f8b27d-399f-4905-89b7-ca869f864568)

**Solution**
The issue can be resolved by removing the 'readonly' declaration of the variables in the 'husky.sh' file.

**Steps to Reproduce**
0. Ensure you have VSCode / GitHub Desktop installed.
1. Install project packages using npm.
2. Make code changes.
3. Attempt to create a commit.

**Expected Behavior**
4. Commit is successfully created and can be pushed to the branch.

**Actual Behavior**
4. An error message is received, indicating an issue with readonly variables.

Thank you for your attention to this matter!

**Comment by typicode** [comment]
Thanks for the report :+1: . Next version will probably not have readonly variables so I'm closing this issue.
