### ISSUE TITLE
env: sh\r: No such file or directory

### ISSUE THREAD

**Issue by longmauriceproj** [typicode/husky#1295]
**Troubleshoot**
- [X] Before creating an issue, please check:
https://typicode.github.io/husky/troubleshooting.html

**Context**
I wanted to provide some clarification for Mac/Linux users experiencing the same issue as described in [What’s the point of husky.sh? #929](https://github.com/typicode/husky/issues/929) and [No such file or directory #944](https://github.com/typicode/husky/issues/944).

The issues listed above were closed without providing clarification as to why users may be experiencing the error. If you're having to run `husky-init` and overwrite the hooks every time you pull from a remote repo, the error is most likely related to line-ending issues.

Make sure your `git config` is set as follows:
```bash
git config --global core.autocrlf input
```
For reference, see the [git documentation on `core.autocrlf`](https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration)

**Comment by typicode** [comment]
Thanks for sharing :+1:
