### ISSUE TITLE
Mention explicitly that all client-side hooks are supported

### ISSUE THREAD

**Issue by jeritiana** [typicode/husky#1298]
**Context**
For newcomers, the first description of husky states _all Git hooks_ are supported, while actually _all **client-side** Git hooks_ are supported.

E.g. on [typicode.github.io/husky](https://typicode.github.io/husky/):
![image](https://github.com/typicode/husky/assets/5649605/990a8009-3eb4-4778-a45f-53f38ca91b3e)

A small update to the description and documentation would make nothing but clearer the scope of this great tool.

This has been suggested a couples of times:
#956
#329
#473
#1249

Thank you very much!

**Comment by typicode** [comment]
Fixed, thanks for the feedback
