### ISSUE TITLE
How to deal with global/system Git hook.

### ISSUE THREAD

**Issue by ethyde** [typicode/husky#130]
Hi,

For some reason i have some Git-Hook installed at global/system level, like this one [git-good-commit](https://github.com/tommarshall/git-good-commit) as commit-msg, this one [prepare-commit-msg](https://gist.github.com/bartoszmajsak/1396344) and a simple `.gitmessage` template. 

In my package.json i have : 
```
"precommit": "npm run eslint",
"eslint": "./node_modules/.bin/eslint -c .eslintrc ./src/ || true"
```
If i run `npm run precommit` everythings work well, but when i try to commit something, nothings happen, only normal commit.

I have commented my Global Githook from .gitconfig, try to commit something, but linting still does not start.

What do I do wrong ?

**Comment by nxmohamad** [comment]
try checking your .git/hooks/pre-commit file

**Comment by syropian** [comment]
@nxmohamad How do you run husky precommit scripts alongside an existing `.git/hooks/pre-commit` file? We have a ruby script doing some things in ours, but I'd also like to run an NPM task.

**Comment by Graham42** [comment]
This looks similar to https://github.com/typicode/husky/issues/171 ?

**Comment by typicode** [comment]
Closing to clean up the issues list but I'm keeping it in mind.
