### ISSUE TITLE
hook was ignored because it's not set as executable

### ISSUE THREAD

**Issue by wjw020206** [typicode/husky#1301]
### Environment
- husky: ^8.0.3
- macOS Monterey 12.6.1
- ubuntu 20.4
- Nodejs: 16.24
### Problem
```
hint: The '.husky/pre-commit' hook was ignored because it's not set as executable.
hint: You can disable this warning with git config advice.ignoredHook false.
```
I checked #1177, but the method there doesn't work for me. I use Windows system myself, and one of my colleagues uses Linux system and the other uses Mac system for development. Everything runs normally on Windows, but the above warning will appear on Linux and Mac.
### Related code
- package.json
``` json
"scripts": {
  "prepare": "husky install",
}
```
- .husky/pre-commit
```sh
#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
npx lint-staged --no-stash
```

**Comment by wjw020206** [comment]
I tried the following operations but it still doesn't work.
```json
"scripts": {
  "prepare": "husky install && chmod ug+x .husky/*",
}
```
as well as
```json
"scripts": {
  "prepare": "husky install && chmod 777 .husky/*",
}
```

**Comment by typicode** [comment]
Can you try this and commit?

```
git update-index --chmod=+x <file>
```

**Comment by wjw020206** [comment]
> Can you try this and commit?
> 
> ```
> git update-index --chmod=+x <file>
> ```

Thank you very much for your help, this method works very well for me, thank you again for your help

**Comment by NBHollas** [comment]
What file am i supposed to put there @wjw020206 ? :)

**Comment by wjw020206** [comment]
> What file am i supposed to put there @typicode ? :)

What file do you want to put?

**Comment by typicode** [comment]
Sorry, it was unclear. Git hooks, for example:

```
git update-index --chmod=+x .husky/pre-commit
```
