### ISSUE TITLE
docs request: using with git submodules

### ISSUE THREAD

**Issue by trusktr** [typicode/husky#1308]
Continuing from

- https://github.com/typicode/husky/issues/404

a docs section on using git submodules with Husky would be great.

F.e., what if we use a tool that hoists dependencies to the root of a supermodule on `npm install` at the root. Will this prevent husky hooks from being install in the submodules? etc?

**Comment by typicode** [comment]
Hi,

This issue concerns v4 which was very different from current version.
v8 uses Git's `core.hooksPath`  config, so there are chances that submodules work.

That being said an example of what you're trying to achieve would be helpful.
