### ISSUE TITLE
"fatal: cannot run .husky/pre-commit: No such file or directory"

### ISSUE THREAD

**Issue by erelsgl** [typicode/husky#1315]
**Troubleshoot**
- [ X ] Before creating an issue, please check:
https://typicode.github.io/husky/troubleshooting.html

If you're migrating from husky 4, see:
https://typicode.github.io/husky/migrating-from-v4.html

**Context**
Please describe your issue and provide some context:
- Terminal or GUI client: WSL
- If applicable, content of the failing hook: 

The file .husky/pre-commit exists and contains the following text:
```
#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

make lint-quick
```

- If possible, minimal steps to reproduce the issue

`git commit`

I get the following error: `"fatal: cannot run .husky/pre-commit: No such file or directory"`

**Comment by typicode** [comment]
Hi, could you run `HUSKY_DEBUG=1 git commit`?

**Comment by erelsgl** [comment]
Problem disappeared after re-installing WSL and re-booting Windows..
