### ISSUE TITLE
husky.sh file generated by husky-init contains error

### ISSUE THREAD

**Issue by Minozzzi** [typicode/husky#1319]
**Troubleshoot**
- [x] Before creating an issue, please check:
https://typicode.github.io/husky/troubleshooting.html

If you're migrating from husky 4, see:
https://typicode.github.io/husky/migrating-from-v4.html

**Context**
Please describe your issue and provide some context:
- Terminal or GUI client (PowerShell, Git Bash, GitHub Desktop, ...)
- - zsh terminal
- If applicable, content of the failing hook
- - ![image](https://github.com/typicode/husky/assets/61752597/51a42a8b-22bb-42e4-ae59-daa7e1ea0f82)

- If possible, minimal steps to reproduce the issue
- - Perform the initial configuration of the husky according to the documentation
- - - pnpm dlx husky-init && pnpm install
- - - pnpm dlx husky add .husky/commit-msg 'pnpm  commitlint --edit "$1"'

###### Husky version is 8.0.0

I would love to contribute to this task, but I will need to contextualize myself with the code, so it may take a while. And also check if this really is an error

Thank you!

**Comment by Minozzzi** [comment]
I think this would be the error, in ``husky-init` it is from version 8.0.0, this version has an error when comparing line 31 of file husky.sh , but in the latest version it is already correct

8.0.0 version
https://github.com/typicode/husky/blob/f5b5c33381c03d8e77970e58b9af4a641fc1f153/husky.sh#L31

Latest version:
https://github.com/typicode/husky/blob/6a5290c48cd148cc83f4ad1b07dd2d2cc4ce2a28/husky.sh#L39

PR: https://github.com/typicode/husky-init/pull/3

**Comment by typicode** [comment]
Thank you for the PR! `husky-init` will be deprecated soon, I'm closing this issue.
That being said it's strange that it doesn't pick the latest husky since the semver range is `^8.0.0` :thinking: . Maybe there's lock file with the exact version.
