### ISSUE TITLE
Is there a way to write a package for git hooks using husky?

### ISSUE THREAD

**Issue by fostimus** [typicode/husky#1321]
We have many projects that use husky. Instead of installing it and managing each one separately, I'd like to write a package using husky to manage all my git hooks in one place.

The closest I found to supporting this in the docs is https://typicode.github.io/husky/guide.html#custom-directory, but that doesn't seem like the solutions.

Any tips on how to have a parent package utilize a `git-hooks` package that implements husky?

**Comment by typicode** [comment]
It's in many different repos or it's a mono repo?

**Comment by fostimus** [comment]
Not a mono repo, the package will be used in many different repos

**Comment by typicode** [comment]
I see, in your package, you can `require('husky')` and run install, add, set commands... then in `package.json` have a `prepare` script with `my-hooks` which would be the `bin` that your package exposes.
