### ISSUE TITLE
error Command "dlx" not found.

### ISSUE THREAD

**Issue by KingAmo** [typicode/husky#1322]
**Context**

run  `yarn dlx husky-init --yarn2 && yarn ` as doc [says](https://typicode.github.io/husky/getting-started.html#automatic-recommended)

error 
```
➜ yarn dlx lint-staged
yarn run v1.22.19
error Command "dlx" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by sofiaborovskaia** [comment]
If you're using yarn version below v2, the command will look like this:
`npx husky-init && yarn`
