### ISSUE TITLE
PIPESTATUS env var always empty

### ISSUE THREAD

**Issue by damjan-anchorzero** [typicode/husky#1324]
**Context**
We're using `PIPESTATUS` `bash` env var in one of our pre commit hooks and we noticed that it's failing on linux with "Bad substitution" error. That is due to the `sh` (used by `husky.sh` script) not making that env var available. The problem appears to be that `husky.sh` switches script execution to `sh` instead of `bash` that is defined in our pre-commit hook.

**Terminal**
Bash 5.1.16(1)-release on Ubuntu 22.04.3 LTS

**Example to reproduce the issue**
```bash
#!/usr/bin/env bash
. "$(dirname "$0")/_/husky.sh"

ls -la | wc
echo "pipe status: $PIPESTATUS"
```
this will print
```bash
damjan@16p:~/workspace/test$ git commit -m "test"
     47     420    2925
pipe status: 
```
Running the script directly in the terminal gives the following output:
```bash
echo "pipe status: $PIPESTATUS"
    268    2409   18305
pipe status: 0
```

Interestingly, the following hook script:
```bash
#!/usr/bin/env bash
echo bash version: $BASH_VERSION
. "$(dirname "$0")/_/husky.sh"
echo bash_version: $BASH_VERSION
```
returns
```
bash version: 5.1.16(1)-release
bash version:
bash_version:
```

Looks like Husky runs scripts in `sh` and breaks the expected behavior (`PIPESTATUS` is not available in `sh`):
```bash
#!/usr/bin/env bash
ps
. "$(dirname "$0")/_/husky.sh"
```
outputs
```bash
    PID TTY          TIME CMD
  59098 pts/4    00:00:00 bash
  74778 pts/4    00:00:00 git
  74785 pts/4    00:00:00 bash
  74786 pts/4    00:00:00 ps
    PID TTY          TIME CMD
  59098 pts/4    00:00:00 bash
  74778 pts/4    00:00:00 git
  74785 pts/4    00:00:00 bash
  74789 pts/4    00:00:00 sh <-- started by husky.sh
  74790 pts/4    00:00:00 ps
     47     420    2925
```

**Comment by typicode** [comment]
Hi @damjan-anchorzero,

I understand the confusion. `sh` is used as common denominator across the different OS (macOS, Linux, Windows). This is the only shell that's guaranteed to work for everyone.

If you're in a controlled environment (i.e. company private repo), you can use `bash` this way. I haven't tested it but it should work (maybe add `set -e` so that it exits on the first failure).

```sh
# .husky/pre-commit
# ...

bash << EOF
ls -la | wc
echo "pipe status: $PIPESTATUS"
EOF
```
