### ISSUE TITLE
husky - command not found in PATH=/mingw64/libexec/git-core:/mingw64/

### ISSUE THREAD

**Issue by rttmoa** [typicode/husky#1327]
After I installed npm, I got an error when I started it. I deleted node_modules and reinstalled it and got an error.  
husky - command not found in PATH=/mingw64/libexec/git-core:/mingw64/

**Comment by rttmoa** [comment]
Solved Thanks！！！！

**Comment by zengqinglei** [comment]
@rttmoa How to solve it?
