### ISSUE TITLE
Husky should consider local .huskyrc files

### ISSUE THREAD

**Issue by SrBrahma** [typicode/husky#1330]
**Context**
Sometimes, we must create/edit a `$HOME/.huskyrc` file to add executables to the PATH so they can be run by husky git hooks. nvm, for example. I also have to do that with bun.

My solution to be applied team-wise is in the package json scripts:

```
    "setupHusky": "cd .. && bunx husky install public/config/.husky && echo PATH=\\\"${PATH}\\\" > ~/.huskyrc",
    "prepare": "bun setupHusky"
```

It works fine, but automatically changing a file outside the project's dir isn't the best practice.

I would appreciate it if husky also checked for a .huskyrc in its cwd. Currently, it only sources the .huskyrc in the $HOME:

![image](https://github.com/typicode/husky/assets/28177550/93223b70-5d94-4d6e-af94-c4f931ff196c)

Thank you!

**Comment by typicode** [comment]
You can do it already this way:

```sh
# pre-commit
# ...
. path_script

# rest of your hook
```

```sh
# commit-msg
# ...
. path_script

# rest of your hook
```

```
"prepare": "echo ... > path_script"
```

I don't think there will be support for a local .huskyrc since it can be done easily with shell scripting.

**Comment by SrBrahma** [comment]
Oh. True! Thanks for the quick answer. Closing this.

I don't know much about shell stuff: instead of creating this .huskyrc file mirroring the PATH, would it be possible to have a line in the git hook executable file that would do it as well?

**Comment by SrBrahma** [comment]
And uh... Maybe `husky install` could do the creation of the .huskyrc in the .husky dir automatically? With PATH on it.

**Comment by typicode** [comment]
In a team, where it's easy to have a controlled environment, I agree it could be sufficient.

But making it a default for bigger projects (OSS) where you have many people with different workflows or tools, if PATH is changed afterward this could create bugs or at least confusing situations. Like if you change your Node version but don't re-run `prepare`.

**Comment by SrBrahma** [comment]
I see, that's a good point. While I could say `husky install` could add it to .gitignore, it potentially would be a source of related issues.

Thanks for the answer and for Husky! 🤗
