### ISSUE TITLE
Install steps do not work for production installation (`husky: not found`)

### ISSUE THREAD

**Issue by mStirner** [typicode/husky#1331]
**Troubleshoot**
- [x] Before creating an issue, please check:
https://typicode.github.io/husky/troubleshooting.html

If you're migrating from husky 4, see:
https://typicode.github.io/husky/migrating-from-v4.html

**Context**
Followed the installation steps provided here: https://typicode.github.io/husky/getting-started.html which are working perfectly fine. But when installing a production environment without dev dependencies `NODE_ENV=production npm install --omit=dev`, npm fails with:

```
> backend@2.2.0 prepare
> husky install

sh: 1: husky: not found
npm ERR! code 127
npm ERR! path /home/marc/projects/OpenHaus/backend
npm ERR! command failed
npm ERR! command sh -c husky install
```

Which is just logical that its not found if its not installed...
But whats the "best practice" to use husky with prod installations?

**Comment by typicode** [comment]
See https://typicode.github.io/husky/guide.html#disable-husky-in-ci-docker-prod

There's no recommended best practice, just pick the one that makes the most sense for you or is the easiest to setup.

**Comment by mStirner** [comment]
Excuse me, i somehow over read that.
I came up with a post install script:

```sh
if [ "$NODE_ENV" = "production" ]; then

    # production installation
    # cp ../backend.service /usr/lib/systemd/system/
    # systemctl daemon-reload
    true

else

    # test/development installation
    npx husky install

fi
```

Do you see any downsites with this solution?
Just dont understand why you need the "prepare" hook in npm.

**Comment by typicode** [comment]
`prepare` is needed to automatically install Git hooks after `npm install`. This is what enables people cloning your project to have Git hooks set up when they run `npm install`. Unfortunately, there's no `devPostinstall` npm hook.

**Comment by typicode** [comment]
Regarding the script, it looks good to me.

The new link for this case:
https://typicode.github.io/husky/how-to.html#ci-server-and-docker

**Comment by ei-grad** [comment]
Got the same concern, that following instructions from husky docs, breaks `pnpm install -P`. Solved it changing `prepare` script to:
`if command -v husky; then husky install; fi`
