### ISSUE TITLE
How can I terminate a git hook if my build script fails?

### ISSUE THREAD

**Issue by GurdipS5** [typicode/husky#1332]
**Troubleshoot**
- [ ] Before creating an issue, please check:
https://typicode.github.io/husky/troubleshooting.html

If you're migrating from husky 4, see:
https://typicode.github.io/husky/migrating-from-v4.html

**Context**
I am using Nuke Build (https://nuke.build) on Windows Server 2022. This is a tool to write build scripts in C#. I have configured this to run in the pre-push commit hook like below:

`#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

while read local_ref local_sha remote_ref remote_sha; do
    # Iterate through commits in the range
    for commit in $(git rev-list --no-walk $local_sha^..$local_sha); do
        # Check commit message for your rules
        commit_message=$(git log --format=%B -n 1 $commit)
        if [[ $commit_message != *chore* ]]; then
          c:/Windows/System32/WindowsPowerShell/v1.0/powershell.exe -ExecutionPolicy RemoteSigned -File 'D:\Repositories\Kinderworx\API\Kinderworx.API.Trips\Kinderworx.API.Trips\build\build.ps1'
        fi
    done
done
`
However, is there a way to to prevent the push if the build fails? So the git hook (pre-push)terminates.
Thank you!

**Comment by typicode** [comment]
It should be aborted automatically if one of the command has an exit code != 0 or if you execute ˋexit 1ˋ yourself.
