### ISSUE TITLE
HUSKY: unbound variable

### ISSUE THREAD

**Issue by sdavids** [typicode/husky#1358]
```shell
.husky/_/h: line 13: HUSKY: unbound variable
```

**Context**

~/.config/husky/init.sh 
```shell
#!/usr/bin/env sh
set -eu

[ -e /etc/zshenv ] && . /etc/zshenv
[ -e "${ZDOTDIR:=${HOME}}/.zshenv" ] && . "${ZDOTDIR:=${HOME}}/.zshenv"
[ -e /etc/zprofile ] && . /etc/zprofile
[ -e "${ZDOTDIR:=${HOME}}/.zprofile" ] && . "${ZDOTDIR:=${HOME}}/.zprofile"
[ -e /etc/zlogin ] && . /etc/zlogin
[ -e "${ZDOTDIR:=${HOME}}/.zlogin" ] && . "${ZDOTDIR:=${HOME}}/.zlogin"
```

**Possible Solution**

Use

`${HUSKY:-}`

instead of

`$HUSKY`

in the `h` script.

**Background Info**

https://stackoverflow.com/a/44606194

**Comment by typicode** [comment]
Thank you for the report. PR ready.

**Comment by glensc** [comment]
no. the pr didn't fix anything:
- https://github.com/typicode/husky/pull/1359/files#r1469560235

**Comment by typicode** [comment]
Since `HUSKY` env variable is moved before `set -u` and `H` is declared, there should be no error or am I missing something?

**Comment by glensc** [comment]
Ahaa, I did not look at that angle. So yes. 

The only way to have `-u` is to do it externally from the script: `sh -u husky.sh` which does not need to be supported.
