### ISSUE TITLE
GitHub displays latest release as v9.0.1

### ISSUE THREAD

**Issue by intgr** [typicode/husky#1361]
On the GitHub project page https://github.com/typicode/husky, GitHub still lists v9.0.1 as the latest release.

As you seem to be releasing every few hours lately, this is quite confusing.

I was experiencing some bugs, went to check the project page, and thought I aready had the latest version (though there was already a release out that fixed my bug)

<img width="233" alt="image" src="https://github.com/typicode/husky/assets/137616/127430ec-f94e-4aa9-a550-dd5b2272bf13">

**Comment by typicode** [comment]
I agree it's not ideal. It's because it contains all the details about the new release (features, migration, ...) and I want to make it easy to be found.

I'll add a note to install using `husky@latest` to get the bug fixes that were released after.

**Comment by intgr** [comment]
Maybe instead every new 9.0.x release could have a link back to 9.0.1 release notes in big font?

**Comment by typicode** [comment]
That's a good idea. If there's a lot of feedback/confusion, I'll revisit.
For now, I'll keep it that way since it's all fresh :)
