### ISSUE TITLE
Export husky module in project defaulting to ESM requires the .default() property usage 

### ISSUE THREAD

**Issue by jerome-benoit** [typicode/husky#1362]
To reproduce: 

- Create node.js a project defaulting to ESM ("type": "module")
- Install husky as deps dev
- Import `husky` in a `prepare.js` ESM module and try to run it in the prepare step: `import('husky').then(husky => husky())`: 

TypeError: husky is not a function
    at file:///Users/I339261/SAPDevelop/e-mobility-charging-stations-simulator-git/prepare.js:7:33

- And doing `import('husky').then(husky => husky.default())` works

Using the default attribute on `husky` imported ESM module is not expected.

**Comment by typicode** [comment]
Why not do `import husky from 'husky'` and then `husky()`?

**Comment by jerome-benoit** [comment]
The issue remains the very same, however the import is done.

And husky is not installed at deployment on the cloud or CI, a full conditional control over its import is mandatory.

And whatever is the use case, an default ESM import of a function shall just works.

The root cause is that the exports fields miss types et import fields. And since seems to be ESM only now, properly unsupport commons.

**Comment by typicode** [comment]
Thank you I forgot the reason for the await. I'll have a look.

**Comment by jerome-benoit** [comment]
I think node.js has CLI arguments to enforce ESM module resolution to cook a unit test.

**Comment by typicode** [comment]
I've done some quick search and I think it's normal to have to use `default()` when using a dynamic import:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import#module_namespace_object
> with the default export available as a key called default

**Comment by jerome-benoit** [comment]
Fair enough. I guess it's then just a matter of updating the documentation and/or the release notes.
