### ISSUE TITLE
`.husky/_/husky.sh` empty on install

### ISSUE THREAD

**Issue by Fdawgs** [typicode/husky#1365]
**Context**

OS: Windows 11
Node version: v20.11.0
Husky version: v9.0.6

When running `npx husky`, the `.husky` directory is created, however `.husky/_/husky.sh` is an empty file:

![image](https://github.com/typicode/husky/assets/43814140/2036c267-a8a1-4a42-93ef-1a709e76f889)

Compared to when running `npx husky install` with husky v8.0.3:

![image](https://github.com/typicode/husky/assets/43814140/97a9c25b-2483-434c-8332-707d93f5ec6b)

Hooks do work but just curious if this is intended behaviour?

**Comment by typicode** [comment]
Hi, 

It's intended for backward compatibility. Otherwise v8 style hooks would fail. 

In the future, there will be a deprecation notice and it'll be removed.
