### ISSUE TITLE
Dead article links in Introduction docs page

### ISSUE THREAD

**Issue by MikeMcC399** [typicode/husky#1368]
The articles listed on [Husky > Introduction > Articles](https://typicode.github.io/husky/#articles) are no longer available and produce a `404` not found error:

---
## Articles

- [Why husky has dropped conventional JS config](https://blog.typicode.com/husky-git-hooks-javascript-config/)
- [Why husky doesn't autoinstall anymore](https://blog.typicode.com/husky-git-hooks-autoinstall/)
---

Probably this section should be deleted from [docs/index.md](https://github.com/typicode/husky/blob/main/docs/index.md).

**Comment by typicode** [comment]
Thanks for the heads, it's fixed 👍

**Comment by MikeMcC399** [comment]
Ah sorry, I see that the blog articles were restored. 

Thank you!
