### ISSUE TITLE
Hashbang support in V9?

### ISSUE THREAD

**Issue by henricook** [typicode/husky#1370]
Does V9 support hashbangs? For instance my post-checkout script starts:

```
#!/usr/bin/env bash
set -e

if [ -v HUSKY_SKIP_POST_CHECKOUT ]
then
 echo "Skipping post checkout as HUSKY_SKIP_POST_CHECKOUT is set..."
 exit 0
fi
```

and currently that gives me this error - like it's not using bash:

```
# gco foo-123            
M	.husky/pre-commit
M	package-lock.json
M	package.json
Already on 'foo-123'
.husky/post-checkout: 4: [: -v: unexpected operator
husky - post-checkout script failed (code 2)
```

Edit: This works fine on 8.0.3

**Comment by typicode** [comment]
It's not supported. Actually, it wasn't the intended behavior in v8.

If you need to run bash script use:

```sh
bash << EOF
# your script
EOF
```

But be aware that it'll fail for any contributor on Windows and systems without bash installed. POSIX and `sh`scripts are preferred for compatibility.

**Comment by henricook** [comment]
Thanks @typicode
