### ISSUE TITLE
 pre commit script failing 

### ISSUE THREAD

**Issue by akankshat05** [typicode/husky#1372]
**Troubleshoot**
- [x] Before creating an issue, please check:
https://typicode.github.io/husky/troubleshoot.html

I have followed the steps as mentioned in https://github.com/typicode/husky/releases/tag/v9.0.1.
- installed husky as dev dependency
-  Ran npx husky init 
- echo "npm run lint-staged" > .husky/pre-commit 
- After this when I commit im getting an error - .husky/pre-commit: .husky/pre-commit: cannot execute binary file
husky - pre-commit script failed (code 126) and unable to commit.
Node version - 20

**Comment by fuyachen** [comment]
Hi, I have the same issue. How did you solve this?

**Comment by akankshat05** [comment]
> Hi, I have the same issue. How did you solve this?

Hi, I did not solve this particular error. I think it was an issue with lint staged. After changing the script to npm run format (not use lint staged) it was working good

**Comment by east0422** [comment]
win10 huskyV9版本试试不**要在Visual Studio Code终端中使用echo创建钩子文件**，可以直接新建钩子commit-msg文件然后在文件中输入对应命令或者在cmd命令行切换到对应工程目录再使用 echo npm run lint-staged>.husky/pre-commit(cmd终端命令不要加引号)

**Comment by algoORgoal** [comment]
For someone who needs translation(I used a translator):
Try the win10 huskyV9 version. Do not use echo to create a hook file in the Visual Studio Code terminal. You can directly create a new hook commit-msg file and enter the corresponding command in the file or switch to the corresponding project directory on the cmd command line and then use echo npm run lint- staged>.husky/pre-commit (cmd terminal command without quotes)
