### ISSUE TITLE
Backwards compatibility with Husky 8.x

### ISSUE THREAD

**Issue by MikeMcC399** [typicode/husky#1374]
Thanks for releasing the Husky 9.x version! 👍🏻 

I have PRs in place to update 2 GitHub repos that I work on and there were two minor points that I noticed concerning backwards compatibility. It would possibly be worth adding some more detail to the release notes about them.

The [husky@9.0.1 release notes](https://github.com/typicode/husky/releases/tag/v9.0.1) say:

> `v9` is backward compatible with `v8`, allowing you to freely upgrade and migrate your hooks later.

1. If you were using `"prepare": "husky install"` in Husky `v8` and you don't change it to `"prepare": "husky"`, then Husky `v9` outputs a deprecation warning, so that wasn't 100% compatible, even if the warning can be ignored.
2. If you were using the how-to advice from [husky@8.0.3 > README > "Disable husky in CI/Docker/Prod" > "With a custom script"](https://github.com/typicode/husky/blob/v8.0.3/docs/README.md#with-a-custom-script) with `require('husky').install()` and you try to run this under Husky `v9` you will see the error `[ERR_REQUIRE_ESM]` when installing dependencies. You need to follow the new instructions in [Husky > CI server and Docker](https://typicode.github.io/husky/how-to.html#ci-server-and-docker) which recommend using `import('husky')` for Husky `v9` (instead of `require('husky')` for Husky `v8`). This usage is not backwards compatible (and it cannot be).

## Suggestion

You might like to review the backwards compatibility statement in [husky@9.0.1 release notes](https://github.com/typicode/husky/releases/tag/v9.0.1)

> `v9` is backward compatible with `v8`, allowing you to freely upgrade and migrate your hooks later.

and perhaps add something like:

It is recommended to make the following changes ...

above the sections for `package.json` and `.husky/pre-commit`

and in addition, draw attention for the need to change any use of `require('husky')` to `import('husky')` due to the transition from CommonJS to ESM.

**Comment by codethief** [comment]
If I may piggy-back on this ticket, since it is about documentation: Seeing that the [release notes](https://github.com/typicode/husky/releases/tag/v9.0.1) recommend the shebang be removed from pre-commit hooks, it would be great if the docs also mentioned what shell the pre-commit hooks now get executed in. (Do I, as a Husky user, have any control over this?)

**Comment by typicode** [comment]
Good point. I'll update.
Hooks are run with `sh` since it's available on all OSes. You can run  your python scripts as you would in a shell.

**Comment by codethief** [comment]
@typicode 
> Hooks are run with sh since it's available on all OSes.

1. What is "it", though? :D `sh` is merely a name whose exact meaning (bash, dash, ash, …) depends on the OS.
2. Does that mean the shell selected by the current user (`$SHELL`) is not respected?
3. Is there any way to tell Husky which shell to use?

**Comment by typicode** [comment]
1. `sh` command. I agree that behind other shells are running.
2. Yes
3. Yes, it needs to be explicit, see below:

```
# In .husky/pre-commit
bash << EOF
# your script
# ...
EOF
```
