### ISSUE TITLE
V9 Issue - Husky command not found in the PATH - with the hooks code in python 

### ISSUE THREAD

**Issue by RedGoldPhoenix** [typicode/husky#1381]
Hello,

I am currently using Visual Studio Code version 1.85.1, NodeJs version 20, and Husky version 9.

I've been using Husky since December, starting with the previous version, and my initial experience was excellent. I had no issues running the hooks coded in Python, and I easily shared them with other developers who executed the "npm install" command without any problems. The hooks I previously managed in the .git/hooks/ folder worked seamlessly in the .husky/ folder.

However, after installing the latest Husky version like below :

npm install --save-dev husky

and then:

npx husky init

I encountered a behavior change, and I received the following error message:
 
![image](https://github.com/typicode/husky/assets/6613155/608d3338-854a-4cb4-aae7-8a50be77bfa4)

I have read the tutorial at https://typicode.github.io/husky/how-to.html and found a relevant chapter: "Understanding PATH and Version Managers." According to my understanding, I need to create a folder in my repository, .config/husky/, and then create the file init.sh in it.

In the init.sh file, I added the line ~/python since Python on my laptop is installed in C:\Program File\python. Is this correct, or did I make a mistake? For your information, I followed these steps, but the issue persists.

I would greatly appreciate your assistance in resolving this problem, as I am currently stuck on this matter.

Best regards,

**Comment by typicode** [comment]
Hi,

You need two files.

`.husky/pre-commit`

```sh
python .husky/pre-commit.py
```

`.husky/pre-commit.py`

```python
# Your Python code
# ...
```

**Comment by gcko** [comment]
@typicode I added a PR to add documentation for this. It was something that I had to fix when migrating from v8 to v9

**Comment by RedGoldPhoenix** [comment]
@typicode @gcko 

Good Moning
I did the test and that work with the pre-commit.
I put an other one like  the commit-msg and I did the same and that stop working.. I know that is strange .. I believe I will uninstall and reinstall the tool and test again

![image](https://github.com/typicode/husky/assets/6613155/82dd7591-795b-47fd-886e-bc48e5f7da39)

![image](https://github.com/typicode/husky/assets/6613155/6672f36b-414b-4403-9da6-9adefbe93e2f)

Thanks for your support and you help

**Comment by RedGoldPhoenix** [comment]
Hello 
I did it suppressed Husky and I have installed it again 

Unistall ok 
![image](https://github.com/typicode/husky/assets/6613155/61d8c5db-3d55-46c2-9691-fe518b84a62c)

Install as you explain in the documentation
![image](https://github.com/typicode/husky/assets/6613155/21f55211-1386-4aed-a5b0-aeda7c26ae27)

![image](https://github.com/typicode/husky/assets/6613155/fc394c90-95ef-4708-b0ef-217d8e5b2473)

I launch a commit to run the precommit you give with the installation
![image](https://github.com/typicode/husky/assets/6613155/86179d8c-fd01-4a66-9c15-8cd8d9fd4d8e)

I copy the commit-msg from the folder _ to .kusky and I updated the pre-commit and commit message as below

![image](https://github.com/typicode/husky/assets/6613155/5aacffce-746a-436a-94f7-cca4b8da24e1)
![image](https://github.com/typicode/husky/assets/6613155/0e3bed18-e3d1-4289-a8b1-949d42e67a84)

but when I launch the commit the commit-msg don't run 
![image](https://github.com/typicode/husky/assets/6613155/f918e75c-8d54-4994-b1f3-147d8e0b765b)

**Comment by RedGoldPhoenix** [comment]
Hello 
I have a question 
What I must do to install and stay on the version 8.0.3  and be sure that the developers after a npm install will install the same version

**Comment by typicode** [comment]
`npm i husky@8 -D`, revert hooks and prepare script. Run prepare once on your machine and have other developers run `npm install` on theirs.

**Comment by RedGoldPhoenix** [comment]
@typicode 
Thanks a lot for your solution 
I'm happy to find again the same behavior I have previously 
Do you believe that with the next version, you can reintroduce some feature as we had with the version V8 ?

**Comment by RedGoldPhoenix** [comment]
1- I have uninstall the version V9 with `npm uninstall husky `
2- suppressed the .husky folder
3- I've launched the commands below in this order
`npm i husky@8 -D`
`npm install husky --save-dev`
`npm pkg set scripts.prepare="husky install"`
`npx husky install`
`echo 'node_modules' >> .gitignore`
`cat .git/config` (to check that the hooksPath=.husky)
`npx husky add .husky/pre-commit "echo ‘Test  pre-commit hook’"`
`npx husky add .husky/commit-msg "echo ‘Test  commit-msg hook’"`
`git add .`
`git commit -m'Update Husky V8'`

At the end I have copied and pasted my hook in Python and everything work fine

**Comment by typicode** [comment]
> Do you believe that with the next version, you can reintroduce some feature as we had with the version V8 ?

It's a bit early to say. As for the `commit-message` not working I just realized that your script was probably expecting a parameter. My bad, sorry.

It should have been `python .husky/commit-msg.py $1"

**Comment by RedGoldPhoenix** [comment]
@typicode 
Thanks for your last message
I will test it and will give you a return ;)
Thanks again for your support.

**Comment by ikapta** [comment]
Thanks. Based on this, I've discovered a working node version: 
```
node .husky/commit-msg.js "$1"
```
