### ISSUE TITLE
Yarn add husky failed due to node version is lower than 18, How can I skip installing in CI

### ISSUE THREAD

**Issue by cai-zhuo** [typicode/husky#1385]
**Troubleshoot**
- [x] Before creating an issue, please check:
https://typicode.github.io/husky/troubleshoot.html

If you're migrating from husky 4, see:
https://typicode.github.io/husky/migrate-from-v4.html

**Context**
Please describe your issue and provide some context:
- Terminal or GUI client (PowerShell, Git Bash, GitHub Desktop, ...)
- If applicable, content of the failing hook
- If possible, minimal steps to reproduce the issue

Thank you!
-----------

I wanna check my code with eslint + lint-staged, but my CI node image version is lower than 18, so should I find a way to avoid to install husky in CI ? Or just delete husky in package.json ?
Can I have better way than telling everyone to install husky in localhost to solve this ? 
Thanks to what you have done in this repo

--------
What I met : 
> error husky@9.0.10: The engine "node" is incompatible with this module. Expected version ">=18". Got "16.19.0"

**Comment by typicode** [comment]
You have some options here :)
https://typicode.github.io/husky/how-to.html#ci-server-and-docker

**Comment by cai-zhuo** [comment]
> You have some options here :) https://typicode.github.io/husky/how-to.html#ci-server-and-docker

Thank you for answering, but I tried to set HUSKEY = 0, I still met this error
May be I get wrong "husky" version ?
--------
<img width="781" alt="image" src="https://github.com/typicode/husky/assets/44321355/4db63bde-3049-4d8c-9fbf-7e0e40ae37ac">

**Comment by silentsakky** [comment]
We are bypassing husky install in circleci using below code, thought it might help you as well
`"prepare": "is-ci || husky install"`
is-ci is very simple npm module here https://www.npmjs.com/package/is-ci
