### ISSUE TITLE
Husky replaces my "prepare" script

### ISSUE THREAD

**Issue by ezeamin** [typicode/husky#1387]
**Context**
- Terminal: Powershell - Windows 11
- Node: 20.9.0
- pnpm: 8.14.0

Hi! Husky is working great so far, thanks for your time! But, when I run `pnpm exec husky init`, following the docs, it installs the hooks but also replaces my `prepare` script with `prepare: husky`. I understand the purpose of this behaviour, but if I have a `prepare` script already, it should't replace it with its own script.

It also replaces my repo pre-commit file inside of `/husky` with a default one that does `pnpm test`. This is undesired behavior, because I already had a configuration written for the pre-commit hook.

**Comment by typicode** [comment]
Hi!

For existing hooks, it's better to follow the 'How to migrate' section from https://github.com/typicode/husky/releases/tag/v9.0.1

I'll update docs to make that clearer.

**Comment by deleonio** [comment]
Hello @typicode and @ezeamin,

we use the script `prepare` for more than just `husky`. I think it is more comfortable to leave it as it is.

**Comment by zayne-wang** [comment]
@typicode
I created a pull request #1407  to fix this issue, please test and check.

**Comment by SH4LIN** [comment]
At least there should be a condition to check if prepare script has any commands in it or not If there is a command then this `husky` command should be appended.

Like this

```Diff
- 14 ;(o.scripts ||= {}).prepare = 'husky'
+ 14 ;(o.scripts ||= {}).prepare = '' === (o.scripts ||= {}).prepare ? 'husky' : (o.scripts ||= {}).prepare + ' && husky'
```

**Comment by zayne-wang** [comment]
> At least there should be a condition to check if prepare script has any commands in it or not If there is a command then this `husky` command should be appended.
> 
> Like this
> 
> ```diff
> - 14 ;(o.scripts ||= {}).prepare = 'husky'
> + 14 ;(o.scripts ||= {}).prepare = '' === (o.scripts ||= {}).prepare ? 'husky' : (o.scripts ||= {}).prepare + ' && husky'
> ```
> 
> Raised the PR for the mentioned solution please check it out.

Hi @SH4LIN,

Maybe we experienced the same mistake. According to typicode's reply in PR #1407, the custom scripts should be placed in `.husky/`, but not in `.husky/_/`. The `.husky/_/` directory is managed by husky it self.

Hope this could make sense for you.

**Comment by benwck** [comment]
> > At least there should be a condition to check if prepare script has any commands in it or not If there is a command then this `husky` command should be appended.
> > Like this
> > ```diff
> > - 14 ;(o.scripts ||= {}).prepare = 'husky'
> > + 14 ;(o.scripts ||= {}).prepare = '' === (o.scripts ||= {}).prepare ? 'husky' : (o.scripts ||= {}).prepare + ' && husky'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Raised the PR for the mentioned solution please check it out.
> 
> Hi @SH4LIN,
> 
> Maybe we experienced the same mistake. According to typicode's reply in PR #1407, the custom scripts should be placed in `.husky/`, but not in `.husky/_/`. The `.husky/_/` directory is managed by husky itself.
> 
> Hope this could make sense for you.

Hi,
The problem here is that you can't have a custom "prepare" script inside your package, Husky always replace it with "prepare: "husky"".
For automation purpose, it is a huge cons of using v9.

**Comment by ernilambar** [comment]
Why is this not prioritized? This issue has blocked me to upgrade Husky. 😔

**Comment by typicode** [comment]
`husky init` is a __one-time__ setup command.

It does only three things that can be done manually:
1. set `"prepare": "husky"` in `package.json`
2. run `husky` command (you can do it with `npx husky` or `npm run prepare`)
3. create an example `.husky/pre-commit` file (you can create it manually)

https://typicode.github.io/husky/how-to.html#manual-setup

Once these three steps are done, there's no need to run `husky init` or redo these steps ever again.

**Comment by ernilambar** [comment]
@typicode Thanks for the reply. I will go manual route then. I can live with running one extra command `npx husky` rather than not being able to use `"prepare"`. Thanks for the awesome tool. 😊

**Comment by typicode** [comment]
You're welcome, glad it's solved :)

**Comment by vedavrat-patwardhan** [comment]
> `husky init` is a **one-time** setup command.
> 
> It does only three things that can be done manually:
> 
> 1. set `"prepare": "husky"` in `package.json`
> 2. run `husky` command (you can do it with `npx husky` or `npm run prepare`)
> 3. create an example `.husky/pre-commit` file (you can create it manually)
> 
> https://typicode.github.io/husky/how-to.html#manual-setup
> 
> Once these three steps are done, there's no need to run `husky init` or redo these steps ever again.

But what about group projects? Someone might join first clone the repo run prepare to setup husky locally and then pushes some changes to the branch and now the prepare setup is gone for all other people who are going to join in future
