### ISSUE TITLE
How to run lint-staged and shell script together in precommit?

### ISSUE THREAD

**Issue by daiict218** [typicode/husky#139]
I have written a shell script which will run eslint on the staged file which I want to use in the precommit hook, but I also want to run lint-staged during precommit. How can I do that. My package.json looks something like this : 

```
 "scripts": {
    "precommit": "chmod +x tools/eslintscript.sh | ./tools/eslintscript.sh"
  },
  "lint-staged": {
    "*.js": [
      "prettier --write",
      "git add"
    ]
  },
```

I tried using 
```
"scripts": {
    "precommit": "npm-run-all --parallel --continue-on-error chmod +x tools/eslintscript.sh | ./tools/eslintscript.sh"
  },
```

but it didn't work. Can somebody help?

**Comment by okonet** [comment]
You should run `chmod +x tools/eslintscript.sh` once and commit the file into repository. It will persist its permissions.
