### ISSUE TITLE
`export HUSKY=0` in a config has no effect

### ISSUE THREAD

**Issue by alecmev** [typicode/husky#1393]
`$HUSKY` is evaluated before the configs are sourced, so its presence doesn't trigger `exit 0`:

https://github.com/typicode/husky/blob/095a4fefbb6b9e57f22bd96f3db0577f5ed427b3/husky#L2-L14

Are the docs out-ot-date and I'm expected to put `export H=0` in `init.sh`? Or something else is wrong?

**Comment by typicode** [comment]
Good catch. It's a bug. It was moved there to fix #1358. I'll publish a new version.

**Comment by typicode** [comment]
Should be good :+1:

**Comment by alecmev** [comment]
It is, thank you!
