### ISSUE TITLE
commitlint 18.6.1

### ISSUE THREAD

**Issue by stephenjason89** [typicode/husky#1394]
There is an ongoing discussion on the issue in commitlint pre commit hook which is also an issue here on husky.
https://github.com/alessandrojcm/commitlint-pre-commit-hook/issues/63

Basically what happens is commitlint can't find the config file.

tried commitlint.config.ts commitlint.config.js etc..
i downgraded for now to 18.6.0 which doesn't have the issue

it is also being discussed here
https://github.com/conventional-changelog/commitlint/issues/3909

Please feel free to close this issue if nothing has to be done here in husky.

**Comment by typicode** [comment]
Thanks for the heads up. Closing as I don't think it's related to husky.
Are you using the code provided here:
https://commitlint.js.org/#/guides-local-setup?id=using-a-git-hooks-manager

**Comment by stephenjason89** [comment]
> Thanks for the heads up. Closing as I don't think it's related to husky.
> 
> Are you using the code provided here:
> 
> https://commitlint.js.org/#/guides-local-setup?id=using-a-git-hooks-manager

Yes I am, it's working fine on lower versions of commitlint. Thank you for the link. And thank you for maintaining husky ☺️
