### ISSUE TITLE
yarn compatibility

### ISSUE THREAD

**Issue by rrsilaya** [typicode/husky#140]
I'm using `yarn v0.24.5` without npm and have been encountering this issue:
```
> husky - Can't find npm in PATH. Skipping precommit script in package.json
```

**Comment by typicode** [comment]
Hi @rrsilaya,

For the moment, it's an expectation/requirement to have `npm` installed. 
When you install Node it should be shipped with it, or do you use a particular install method?

**Comment by iRoachie** [comment]
@typicode When installing with yarn it doesn't set up the hooks

**Comment by typicode** [comment]
Hi @iRoachie what's your version of `yarn`? It was happening before `0.24` but recent versions of `yarn` seem to have fixed it.

**Comment by iRoachie** [comment]
@typicode 0.24.6

**Comment by typicode** [comment]
Thank you, I'll give it another try

**Comment by typicode** [comment]
I can't seem to be able to reproduce. If anyone else can confirm.
Here's how I've tested:

```sh
yarn --version
0.24.6

cd /tmp
mkdir A
cd A
git init
yarn init -y
yarn add husky --dev
cat .git/hooks/pre-commit # should be husky
cd ..
# retry with another directory to be sure that there's no issue with yarn caching
mkdir B
cd B
git init
yarn init -y
yarn add husky --dev
cat .git/hooks/pre-commit # should be husky
```

**Comment by iRoachie** [comment]
@typicode I'll try it again. Do you have to add both precommit and prepush for scripts to run?

**Comment by rrsilaya** [comment]
> @typicode When installing with yarn it doesn't set up the hooks

This is also happening to me, running on `v0.24.6`.

**Comment by GAumala** [comment]
I can also confirm that it is still happening on `v0.24.6`. Please don't asume that npm is bundled together with node.js in every system. That is not the case some Linux distros like Arch.

**Comment by typicode** [comment]
@GAumala good to know, thanks. Personally, on Linux, I'm always using [nvm](https://github.com/creationix/nvm), so it gets bundled.

Are you aware of other cases where `npm` isn't bundled?

**Comment by typicode** [comment]
> Do you have to add both precommit and prepush for scripts to run?

@iRoachie you can pick one or both, it'll work

> This is also happening to me, running on v0.24.6.

@rrsilaya would you have steps to reproduce the issue? May be obvious, but `--ignore-script` flag shouldn't be set or it will prevent husky's `install` to run.

BTW `yarn` `v0.27.5` has been published, would be worth rechecking with the latest release.

**Comment by hughryan** [comment]
Installing with `yarn v0.27.5` is not setting up the hooks.

**Comment by GAumala** [comment]
I don't know of other systems that don't bundle `npm` with now, but Arch is pretty big, and other distros like Antergos and Manjaro rely on Arch packages. Now that `yarn` is pretty popular I'd expect more distros to do this as well, Arch just did it first because of its rolling release model.

btw, I tested with `yarn v0.27.5` and it does setup the hooks. it just throws an error because I don't have npm installed.

**Comment by gaastonsr** [comment]
I just tested with the last version of yarn (`0.27.5`) and it works.

**Comment by MIGUELWAXX** [comment]
cheers

**Comment by JacopKane** [comment]
If `npm` is not installed (`brew install node --without-npm`) this issue still persists
