### ISSUE TITLE
.husky don't auto create

### ISSUE THREAD

**Issue by sunlianglife** [typicode/husky#1408]
"husky": "^9.0.11",
"node": "18.12.0" 

 "scripts": {
    "postinstall": "husky install",
  },

error:
$ husky install
install command is deprecated

**Comment by stephane-ruhlmann** [comment]
Hi @sunlianglife , v9.0 deprecated `install` command. Now you can just execute `husky`.

Check the changelog for further details: https://github.com/typicode/husky/releases/tag/v9.0.1
