### ISSUE TITLE
What replacement `husky install` and `husky uninstall` ?

### ISSUE THREAD

**Issue by dimaslanjaka** [typicode/husky#1415]
**Troubleshoot**
- [x] Before creating an issue, please check:
https://typicode.github.io/husky/troubleshoot.html

If you're migrating from husky 4, see:
https://typicode.github.io/husky/migrate-from-v4.html

**Context**

after updating husky to latest today, my `postinstall` script showing `deprecated`

![image](https://github.com/typicode/husky/assets/12471057/765d6292-aaed-4b54-979f-648001db9340)

because of no site search on https://typicode.github.io/husky/ and no document for replacement of this issue in https://typicode.github.io/husky/migrate-from-v4.html i write this.

**SOLVED**:

i just solved `husky install` replaced with `husky init`. But how `uninstall` replacement?

**Comment by Alec-Gillis** [comment]
I agree that the documentation is not clear on the `uninstall` replacement. For now I am using `git config --unset core.hooksPath` inside my project directory, which is exactly what the `v8` `uninstall` method was doing.
https://github.com/typicode/husky/blob/3c0e08d3ca4d01d04ebb92089e68c47e131ab6be/src/index.ts#L92

**Comment by typicode** [comment]
`husky` replaces `husky install` and as @Alec-Gillis suggested `git config --unset core.hooksPath` 👍
