### ISSUE TITLE
Reference non-existent version of git

### ISSUE THREAD

**Issue by wesleyschlenker** [typicode/husky#1419]
https://github.com/typicode/husky/blame/9f6e2123eaa002e0ad37a90645f71a25d1e0b2e9/docs/troubleshoot.md#L11

**Comment by typicode** [comment]
Hi, I'm not sure what you mean?
https://github.blog/2016-06-13-git-2-9-has-been-released/

**Comment by wesleyschlenker** [comment]
> Hi, I'm not sure what you mean?
> https://github.blog/2016-06-13-git-2-9-has-been-released/

Sorry, you were right. I misread the minor version of git latest.

**Comment by typicode** [comment]
No worries 👍
