### ISSUE TITLE
corepack - pnpm `command not found`

### ISSUE THREAD

**Issue by MartinX3** [typicode/husky#1425]
Arch Linux
IntelliJ IDE

I installed `pnpm` via `corepack enable`.
I restarted the system.

On commit it tells me `command not found` while using pnpm in `pre-commit` because it isn't in `PATH` used by husky,
But if I look in the terminal it's inside `PATH`.

I manually added the pnpm part of my .bashrc (added by corepack) to the husky bash script in the .husky folder to make it work.
I wonder why the `PATH` is different between husky and my system.
Does husky ignore my `.bashrc`?

**Comment by kaaax0815** [comment]
I have the same problem but on windows.
What did you add to your script?

**Comment by MartinX3** [comment]
@kaaax0815 it seems that problem is linux only and only dedicated to the IntelliJ IDEA.
They have now an open issue ticket about not using the .bashrc if started via the desktop ui.
Starting it via the terminal works fine.

https://youtrack.jetbrains.com/issue/WEB-66762/Command-not-found-if-pnpm-is-installed-via-corepack

https://youtrack.jetbrains.com/projects/IJPL/issues/IJPL-1055/Load-interactive-shell-environment-variables-on-Linux

https://youtrack.jetbrains.com/articles/SUPPORT-A-1727/Shell-Environment-Loading

**Comment by kaaax0815** [comment]
I have a similar problem on windows and vscode. Using it via terminal also fixes the problem

**Comment by MartinX3** [comment]
I think you need to open an issue ticket at vscode not using the user set path environmental changes if startet via the windows GUI.

**Comment by danggearment** [comment]
I still have this issue, any update bros

**Comment by pratik149** [comment]
I was facing the same issue in MacOS. I restarted my VSCode and it got resolved.

**Comment by Lordfirespeed** [comment]
Hey guys, on IntelliJ platform, you can copy the `nvm` and `pnpm` snippets from your `.bashrc` (or anlogous file for your shell) to one of Husky's [Startup Files](https://typicode.github.io/husky/how-to.html#startup-files) (probably `~/.config/husky/init.sh`) to resolve this issue.
