### ISSUE TITLE
Husky cannot execute git commands on Mac computers.

### ISSUE THREAD

**Issue by Autumn-one** [typicode/husky#1427]
I have a front-end project that uses husky to integrate git hooks to perform some automated operations. I execute some git commands in the Pre-commit and post-commit hooks, such as: git add . This works fine on windows, but on mac, the exact same configuration will fail when executing git commands.

**Comment by sankeyangshu** [comment]
Different operating systems handle file permissions differently. For example, file permissions may be lost when pulling from Windows to a Unix system such as Linux or macOS.
Set the file permissions to the executable:
`
chmod +x .husky/pre-commit
chmod +x .husky/commit-msg
`

**Comment by Autumn-one** [comment]
done
