### ISSUE TITLE
npx husky add  cannot be used ？

### ISSUE THREAD

**Issue by gitboyzcf** [typicode/husky#1428]
"husky": "^9.0.11"

`npx husky add .husky/pre-commit "npx --no-install -- lint-staged"`
👇
add command is deprecated ？？？

**Comment by typicode** [comment]
It's not needed anymore. It was doing changing permissions and setting up some things. You can simply create the file now.

**Comment by gitboyzcf** [comment]
May I ask if there are any alternatives?  What are they?

**Comment by typicode** [comment]
If you're on macOS or Linux, `echo "your command" > .husky/pre-commit` or using your code editor to create the file.

**Comment by ljsyyds** [comment]
What should I do if I'm on window?

**Comment by Junaid300** [comment]
Just wondering, Do we have to add commands to the `.husky/pre-commit` manually ? Like go to pre-commit file and add command .
for example 
```
// .husky/precommit
npm lint-staged
npm run build

```
Is there any way to add commands  using package script ?
```
preapare : `husky && <add command 1> && <add command 2>`
```
Because i am not getting why i need to  add command manually ? What if someone delete the .husky folder and forgot to add commands. 

May be i am on wrong track. Is there any option to do this in new version of husky ?

**Comment by typicode** [comment]
Husky folder should be versioned.

So when someone clones the repository they will get the hooks defined in it.

**Comment by Junaid300** [comment]
> So when someone clones the repository they will get the hooks defined in it.

For some reason husky hook is not working for me. May be i haven't implemented husky properly !!

```
{
  "name": "my-project",
  "private": true,
  "version": "0.0.1",
  "type": "module",
  "scripts": {
    "prepare": "husky | chmod ug+x .husky/*"
  },
  "dependencies": {
   ...
  },
  "devDependencies": {
    "@typescript-eslint/eslint-plugin": "^7.12.0",
    "@typescript-eslint/parser": "^7.12.0",
    "@vitejs/plugin-react": "^4.2.1",
    "eslint": "^8.55.0",
    "eslint-plugin-react-hooks": "^4.6.0",
    "eslint-plugin-react-refresh": "^0.4.5",
    "husky": "^9.0.11",
    "lint-staged": "^15.2.1"
  },

  "lint-staged": {
    "src/**/*.{js,jsx,ts,tsx,json,css,scss,md}": [
      "prettier --write ."
    ],
    "src/**/*.{js,jsx,ts,tsx,json}": [
      "eslint --max-warnings=0"
    ]
  }
}
```
// my pre-commit file

npx lint-staged
npx tsc
npm run build

```

**Comment by typicode** [comment]
`chmod` is unnecessary with v9. What kind of error do you get?

**Comment by Junaid300** [comment]
I wasn't familiar with the `chmod` in V9. I don't get any error, work fine and i was not familiar with the hook. Now i got it. thank you .

**Comment by typicode** [comment]
No worries, you're welcome :+1:
