### ISSUE TITLE
can't find .git dir on windows

### ISSUE THREAD

**Issue by AntonPuko** [typicode/husky#143]
Hi, when I'm trying to install husky on windows, I get an error:
`can't find .git directory, skipping Git hooks installation`
I noticed that the problem is in find-parent.js. It splits by `/` separator, but in windows, I have paths with `\`.

**Comment by typicode** [comment]
Thanks for the heads up, I'll have a look 👍

**Comment by rekateka** [comment]
Can confirm; I rolled back to 0.13.4 and it works fine there.

**Comment by typicode** [comment]
A fix has been merged to master, I'll test it more tomorrow before publishing.

**Comment by AntonPuko** [comment]
Thanks for the fast fix

**Comment by typicode** [comment]
Just published `v0.14.1`, it should fix it :)
