### ISSUE TITLE
Add `-v` as version checker, not folder creation command

### ISSUE THREAD

**Issue by ezeamin** [typicode/husky#1434]
Currently, when running `husky -v`, it runs `husky` command, inside of  `-v` folder, which is annoying. The desired behaviour is to output con console the current version husky is on.

**Comment by ignaciobockl** [comment]
![image](https://github.com/typicode/husky/assets/45101161/3812e1ec-9f44-4ae2-97fa-4b322b49063c)

As shown in the image, when you run the husky -v script it generates the '-v' folder and you would like to see the version installed globally on the computer.

**Comment by typicode** [comment]
No plans to add it or `-h`. But you can get the version with `npm show husky version`
