### ISSUE TITLE
Husky not running when .git is in another directory

### ISSUE THREAD

**Issue by cmaciasjimenez** [typicode/husky#1437]
Hi! I'm trying to use Husky v9 in a folder that has the `.git` folder in the parent folder. There is a [specific section](https://typicode.github.io/husky/how-to.html#project-not-in-git-root-directory) in the Husky website about this but I can't get it to work for some reason.

My folder structure is as follows
```
.
├── .git/
└── docs/ # package.json with husky
```

I've installed husky v9 in /docs and tried to run `npx husky init` which added the `prepare`script to the package.json but returned "_.git can't be found_". I went and did the [changes](https://typicode.github.io/husky/how-to.html#project-not-in-git-root-directory) specified in the website, but when I try to commit something to do the `npm test`, the commit goes through without husky running.

I don't know if maybe the guide isn't updated for v9 or am I installing it wrong or doing something in a different order as it should be.

Any help?

Thank you

**Comment by PiotrPulsate** [comment]
I have the same issue

**Comment by 127** [comment]
Same here it is nightmare to set it up.
Managed to set it up like 
`"prepare": "cd ../ && husky subproject/.husky"`
but it fails to run any hook as for example
`npm run lint` from subproject/package.json

**Comment by micalevisk** [comment]
since the binary itself is located at `docs/node_modules`, I don't think that this is something that Husky can resolve. I'd say this is a limitation.

You can solve this if your git repo was supposed to be using Husky globally
