### ISSUE TITLE
`.husky/_/commit-msg` not triggered with `git commit -m "test"`

### ISSUE THREAD

**Issue by ahmedelq** [typicode/husky#1440]
**Troubleshoot**
- [x] Before creating an issue, please check:
https://typicode.github.io/husky/troubleshoot.html

**Context**
Please describe your issue and provide some context:
-  env: `Ubuntu 22.04`, `Bash 5.1.16`, `git version 2.34.1`, `husky: 9.0.11`
- `git config core.hooksPath` gives: `.husky/_`

**Steps to reproduce**
1. Edit `.husky/_/commit-msg` with the below: 
```sh
#!/usr/bin/env sh
. "${0%/*}/h"
echo "test $1"
exit 1
```
2. `git commit -m "testing"`
3. Nothing gets printed out and commit message is accepted. 

Expected behavior: fail the git commit.

Thank you!

**Comment by typicode** [comment]
Commands should be put `.husky/commit-msg`

**Comment by irfan-nawaz** [comment]
what is _ folder then where can I read about it ?

**Comment by typicode** [comment]
It's a directory owned by husky to put necessary files for it to work. Consider it like node_modules.
In any case, files inside shouldn't be edited.
