### ISSUE TITLE
just clone my project repo on my new pc and got bad interpreter error.

### ISSUE THREAD

**Issue by Miguerfi** [typicode/husky#1444]
**Troubleshoot**
- [X] Before creating an issue, please check:
https://typicode.github.io/husky/troubleshoot.html

If you're migrating from husky 4, see:
https://typicode.github.io/husky/migrate-from-v4.html

**Context**
Please describe your issue and provide some context:
- Kitty - Archlinux
- pre-puush(?)
- pnpm install 

the output:
`sh: /home/**/work/1/**/node_modules/.bin/husky: /bin/sh: bad interpreter: Text file busy
`

**Comment by 3rd** [comment]
Hitting this as well on NixOS, seems like it's open for write at the time of execution.
For me it fails on `pnpm install`, with pnpm v8 and v9, and it used to work before.
With `npm install` it works fine.
It doesn't seem to come from husky/pnpn, what OS are you on @Miguerfi ?

```
✗ inotifywait -m node_modules/.bin/husky
Setting up watches.
Watches established.
node_modules/.bin/husky ATTRIB
node_modules/.bin/husky DELETE_SELF
```

**Comment by Miguerfi** [comment]
arch linux(btw).
im using bun now and is wokring fine.

**Comment by polyzen** [comment]
Can be worked around with `export UV_USE_IO_URING=0`:
https://github.com/nodejs/node/issues/48444
https://github.com/archlinux/aur/commit/fd50c6372e78fe518b35fd5afd0f9ba786a80d02

**Comment by miguelmota** [comment]
I also randomly experienced the error on node20 using arch linux (btw). 

The `export UV_USE_IO_URING=0` option did not work for me.

Upgrading to node22 solved it for me.
