### ISSUE TITLE
Husky initialization fails with TypeError in bun environment

### ISSUE THREAD

**Issue by NazCodeland** [typicode/husky#1457]
**Issue Type**: Bug

**Troubleshoot Checklist**:
- [x] I have checked the Husky Troubleshoot Guide

**Context**:
- Terminal: PowerShell 7.4.2
- Node.js version: v18.19.0
- Package Manager: bun
- Husky version: 9.0.11

**Description**:
When trying to initialize Husky in a new project using bun as the package manager, I encounter a TypeError. The error message suggests that the `npm_config_user_agent` environment variable is undefined, and the script is trying to call the `split` method on it.

**Steps to Reproduce**:
1. Create a new project directory
2. Initialize git with `git init`
3. Install husky with `bun add --dev husky`
4. Try to initialize husky with `bunx husky init`

**Expected Result**:
Husky initializes successfully and creates the necessary hooks.

**Actual Result**:
Initialization fails with the following error:

**Additional Context**:
This issue occurs even in a fresh project following the steps provided in the Husky Get Started Guide.

**Comment by CameronJThomas** [comment]
Just ran into this same issue. Even if you're using bun, you should still be able to do `npx husky init` to get set up, but agreed this shouldn't have a hard dependency on node.

**Comment by typicode** [comment]
Maybe it could be added to `bun` for parity with other package managers

**Comment by CameronJThomas** [comment]
Good shout, it actually looks like this was resolved in Bun 1.1.14, released a few weeks ago: https://bun.sh/blog/bun-v1.1.14#fixed-not-passing-npm-config-user-agent-on-windows

Have just updated Bun and no longer seeing this issue. Thanks!
