### ISSUE TITLE
husky runs ghooks twice

### ISSUE THREAD

**Issue by Sibiraj-S** [typicode/husky#146]
**package.json**

 ```
 "scripts": {
    "precommit": "npm test",
    "commit": "git-cz",
    "test": "grunt coffeelint"
  },
```

I run `npm run commit`. 

In this scenario, pre-commit happens before executing `git-cz` and again after while `git-cz` is making actual commit.

also this works well for standard git commit commands

**Comment by typicode** [comment]
Hi @Sibiraj-S,

Try to rename `commit` to `cz`. It happens because npm when you run `commit`, npm automatically runs `pre*` and `post*` scripts.

**Comment by Sibiraj-S** [comment]
Actually, I renamed it. then it when I got the error. Everything works fine. I posted the issue to let know of this condition. 
Is there thing that could be done on these scenarios

**Comment by Sibiraj-S** [comment]
If the behaviour is fine, Issue can be closed.
