### ISSUE TITLE
`Note: sh will be used to run hooks, even if a shebang is set.`

### ISSUE THREAD

**Issue by TheKnarf** [typicode/husky#1463]
**Troubleshoot**
- [x] Before creating an issue, please check:
https://typicode.github.io/husky/troubleshoot.html

**Context**

> `Note: sh will be used to run hooks, even if a shebang is set.`

This seems like an odd decision and a bit of a foot-gun?

I wanted to write my `pre-commit` hook as a Node script, now I solved that by having `node .husky/pre-commit.mjs` in my `.husky/pre-commit` file. But it still seems like an odd choice. Would it not be simpler if Husky respected the shebang (and maybe only used `sh` if there was no shebang).

If I were to take a guess it would be that people in the past either forgot to add an shebang or forgot to `chmod +x` their scripts, and maybe that was why this change came along? But that still seems like an odd decision.

**Comment by typicode** [comment]
> add an shebang or forgot to chmod +x their scripts

That's a good guess, it was a trade-off. The issue was mostly with people creating hooks on Windows (which doesn't have execute permissions) or people
