### ISSUE TITLE
v9.0.11 does not work with nvm

### ISSUE THREAD

**Issue by XingToYang** [typicode/husky#1466]
# dependencies
"husky": "^9.0.11",
"lint-staged": "^15.2.7"

# ~/.config/husky/init.sh
echo "Jackson4"
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
nvm use v20.10.0
node -v

# .husky/pre-commit
`node -v
npm run lint-staged`

# output
Jackson4
Now using node v20.10.0 (npm v10.2.3)
v20.10.0
v14.15.1

> demo@1.0.0 lint-staged /Users/lee/develop/projects/demo
> lint-staged --allow-empty

file:///Users/lee/develop/projects/demo/node_modules/listr2/dist/index.js:77
  static {
         ^

SyntaxError: Unexpected token '{'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:141:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! demo@1.0.0 lint-staged: `lint-staged --allow-empty`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the demo@1.0.0 lint-staged script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/lee/.npm/_logs/2024-07-16T09_36_24_751Z-debug.log
husky - pre-commit script failed (code 1)

I did above configurations follow https://typicode.github.io/husky/how-to.html#solution. I try to use node v20.10.0 at init.sh, but node version is v14.15.1 at .husky/pre-commit. Why it is v14.15.1, my default node version is v16.20.2

**Comment by XingToYang** [comment]
I have deleted /usr/local/bin/node, then my default node version became to v16.20.2

**Comment by Zackin-He** [comment]
I also encountered the same problem, git commit through the terminal works normally, but commit code through source control times error, may I ask you to solve this problem?  How was it resolved?

**Comment by samuelreichor** [comment]
Same here, looking forward for a solution
