### ISSUE TITLE
Husky 9.1.0 seems to change the pwd of the hooks

### ISSUE THREAD

**Issue by richardasymmetric** [typicode/husky#1468]
**Troubleshoot**
- [x] Before creating an issue, please check:
https://typicode.github.io/husky/troubleshoot.html

If you're migrating from husky 4, see:
https://typicode.github.io/husky/migrate-from-v4.html

**Context**
I just upgraded to 9.1.0 and made the documented changes to remove the shebangs from the hooks. We're also a cross platform repo, so we have the `.husky/common.sh` file to make it work for windows, and in all our hooks we have `. "$(dirname -- "$0")/common.sh"`

With 9.1.0 the sourcing of common.sh no longer works because `$(dirname -- "$0")` has changed from `.husky` to `.husky/_/` 

Here's the full debug output:

```
+ [  = 2 ]
+ basename .husky/_/pre-commit
+ n=pre-commit
+ dirname .husky/_/pre-commit
+ dirname .husky/_
+ s=.husky/pre-commit
+ [ ! -f .husky/pre-commit ]
+ [ -f _homedir_/.huskyrc ]
+ i=_homedir_/.config/husky/init.sh
+ [ -f _homedir_/.config/husky/init.sh ]
+ [  = 0 ]
+ c=0
+ trap c=$?; h EXIT
+ set -e
+ PATH=node_modules/.bin:/usr/lib/git-core:/usr/lib/git-core:/usr/bin:_homedir_/.cargo/bin::_homedir_/.local/bin:_homedir_/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin:~/.cache/.npm-global/bin:/usr/lib/dart/bin:node_modules/.bin:/usr/lib/dart/bin/:_homedir_/.local/bin:_homedir_/.cache/.npm-global/bin/bin
+ . .husky/pre-commit
+ set -x
+ dirname -- .husky/_/pre-commit
+ . .husky/_/common.sh
.husky/_/pre-commit: 4: .: cannot open .husky/_/common.sh: No such file
+ c=2
+ h
+ [ 2 = 0 ]
+ [ 2 != 0 ]
+ echo husky - pre-commit script failed (code 2)
husky - pre-commit script failed (code 2)
+ [ 2 = 127 ]
+ exit 1
```

**Comment by TheMikeyRoss** [comment]
For me removing `. "$(dirname "$0")/_/husky.sh"` from my .husky/commit-msg file fixed the issue.

**Comment by typicode** [comment]
Hi,

That's correct to fix this, remove `#!/usr/bin/env sh` and `. "$(dirname -- "$0")/_/husky.sh"` from your hooks. I'll fix that and publish a new version.

**Comment by typicode** [comment]
It should be automatically removed in v9.1.1 👍

**Comment by richardasymmetric** [comment]
> Hi,
> 
> That's correct to fix this, remove `#!/usr/bin/env sh` and `. "$(dirname -- "$0")/_/husky.sh"` from your hooks. I'll fix that and publish a new version.

What about common.sh as documented in https://typicode.github.io/husky/troubleshoot.html#yarn-on-windows

I still seem to having an issue with 9.1.1

**Comment by typicode** [comment]
Sorry, need to check this one but won't have time right now. You can add `pwd` or `echo $0` command s to see where you are and find the path to source `common.sh`.

Setting `HUSKY=2` lets you have debug info as well.

Feel free to share your findings.

**Comment by richardasymmetric** [comment]
> Sorry, need to check this one but won't have time right now.
> 
> Actually, I think `. .husky/common.sh` should do the trick.

That does look like it works, I'll have to wait until I'm at a windows machine again to try it, but at least it's not throwing errors on my ubuntu machine.
