### ISSUE TITLE
Misspelling in docs "Get Started" section

### ISSUE THREAD

**Issue by Tseku210** [typicode/husky#1470]
**Troubleshoot**
- [x] Before creating an issue, I checked the [troubleshoot guide](https://typicode.github.io/husky/troubleshoot.html)

**Context**
- **Issue description:** There is a misspelling on the "Get Started" page of the Husky documentation. The word "working" is misspelled as "workinkg" in the "Scripting" section.
- **Minimal steps to reproduce the issue:**
  1. Go to [Husky Get Started page](https://typicode.github.io/husky/get-started.html).
  2. Scroll down to the "Scripting" section.
  3. Observe the misspelling in the example script comments.

Thank you!

**Comment by typicode** [comment]
Thank you! It's fixed :)
