### ISSUE TITLE
.husky/_/husky.sh: line 1: .husky/_/_/husky.sh: No such file or directory

### ISSUE THREAD

**Issue by freezyh** [typicode/husky#1472]
**Troubleshoot**
- [ ] Before creating an issue, please check:
https://typicode.github.io/husky/troubleshoot.html

If you're migrating from husky 4, see:
https://typicode.github.io/husky/migrate-from-v4.html

**Context**
Please describe your issue and provide some context:
- Terminal or GUI client (PowerShell, Git Bash, GitHub Desktop, ...)
- If applicable, content of the failing hook
- If possible, minimal steps to reproduce the issue

Thank you!

**Comment by typicode** [comment]
Hi, to fix this, remove `#!/usr/bin/env sh` and `. "$(dirname -- "$0")/_/husky.sh"` from your hooks

**Comment by typicode** [comment]
It should be automatically removed in v9.1.1 👍

**Comment by frank-topel-dbi** [comment]
Please explain how this is "automatically" removed in 9.1.1. I'm using 9.1.1 and I am still getting this error, for this `pre-commit` hook:

```sh
#!/bin/sh

# This loads nvm.sh and sets the correct PATH before running hook
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

# Run the pre-commit hook
. "$(dirname "$0")/_/husky.sh"
npx lint-staged
npm run prettier:format-staged
```

**Comment by typicode** [comment]
Hi, automatic removal has been disabled due to issues. You need to do it manually now.

I would suggest updating to the latest version and remove `. "$(dirname "$0")/_/husky.sh"`, you can also call `lint-staged` directly.

**Comment by frank-topel-dbi** [comment]
Thanks for replying. Does this mean that the whole process of dynamically creating that `_/husky.sh` has been removed from husky? If not, when would that still be useful/necessary?
