### ISSUE TITLE
Deprecations in 9.1.1 are breaking changes

### ISSUE THREAD

**Issue by nimafallahian** [typicode/husky#1474]
Wanted to inform that the deprecations made in version 9.1.1 are breaking changes.

```
#!/bin/sh

# shellcheck source=.husky/_/husky.sh
. "$(dirname "$0")/_/husky.sh"
```

Is not only deprecated but it's not working as well and is breaking the automated pipelines. Also, I don't like the idea of removing code with running husky and without using a --write tag. As a developer I do need to have full control on what's happening. I do appreciate the work done here, although this makes debugging a bit harder. :D

**Comment by typicode** [comment]
Hey,

v9.1.0 added deprecation message without removing code but it wasn't actually possible to make it work with the shell script refactor. So instead, I went with an automatic removal of code in v9.1.1.

While I sometimes prefer to manually update like you, I guess with this approach more hooks will be ready for v10. Sometimes people tend to leave deprecation messages for a long time without taking actions, so here at least it will be done and prevent frictions later.

When updating husky, `prepare` should run and automatically update hooks so no breaking. Not sure why it broke for you in the CI, though.

Thanks for feedback and sorry for the issue.

**Comment by melink14** [comment]
This also broke for my project (causing release to fail since `git commit` of tag and changelog failed`).

I don't understand what you mean by it should be fixed automatically. `husky` was updated by dependabot so if it was supposed to run then, any updated hooks would be completely ignored and never committed back to the repo.

I guess after that all runs of `git commit` will fail.

To clarify, is the manual work around to delete the deprecated lines ourselves?

**Comment by iowillhoit** [comment]
Hey @typicode, the change in `9.1.1` is also affecting our builds in Github Actions. [Here is an example of it failing](https://github.com/oclif/plugin-version/actions/runs/10026010285/job/27709820238#step:8:68). 

It looks like [the regex](https://github.com/typicode/husky/compare/v9.1.0...v9.1.1#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346R6) that was written to clean this up is not quite flexible enough. 

Here is the [pre-commit file](https://github.com/oclif/plugin-version/blob/main/.husky/pre-commit) from the failing repo. You can see here (https://regex101.com/r/bZYGon/1) that the regex does not match what we have in our hook. Here is another [pre-commit example](https://github.com/salesforcecli/plugin-info/blob/main/.husky/pre-commit) that is slightly different but also does not match the regex.

This is going to break **a lot** of our repos' releases in the [oclif](https://github.com/oclif) and the [Salesforce CLI](https://github.com/salesforcecli) orgs as they start rolling over to `9.1.1`. 

Can this be reverted and released in a v10 or could you release a new version with a slightly more flexible regex? 
Thank you!

**Comment by iowillhoit** [comment]
Yea, the regex (and test) would work if our files had the same "headers". Our files are slightly different so the regex does not match.

Ours: `#!/bin/sh`
Regex: `#!/usr/bin/env sh`

Ours: `. "$(dirname $0)/_/husky.sh"`
Regex: `. "$(dirname -- "$0")/_/husky.sh"`

I took a stab at updating the regex. It might not be perfect, but it matches a few variations that we have: https://regex101.com/r/WuObfs/1

**Comment by melink14** [comment]
It looks like the regex in my files are the same as iowillhoit's examples.

I also thought it could be because of some deprecation lines I saw:
```
> rikaikun@2.5.59 prepare
> husky install

install command is DEPRECATED
```

but it looks like the regex is the actual cause!

**Comment by typicode** [comment]
I reverted it, so `v9.1.2` only displays a deprecation message and doesn't attempt to modify files.
Sorry for the trouble.
