### ISSUE TITLE
Restore set +x state

### ISSUE THREAD

**Issue by glensc** [typicode/husky#1475]
with previous version the hooks were ran as subshell, so `set -x` used in hooks didn't leak to main script.

previously it looked like this:
```
❯ git commit -am x
Running pre-commit hooks
⦿ node_modules/.bin/lint-staged -c .lintstagedrc.json
→ No staged files found.
```

this is how it looks now:

```
❯ git commit -am x
Running pre-commit hooks
⦿ node_modules/.bin/lint-staged -c .lintstagedrc.json
→ No staged files found.
⦿ c=0
⦿ h
⦿ '[' 0 = 0 ']'
⦿ return
```

I used `set -x` to let shell print executed commands:

```sh
❯ cat .husky/pre-commit
# Setup nice colorful prompt
# Use color "lime": https://tintin.mudhalla.net/info/256color/
c='\033[38;5;070m'
r='\033[0m'
PS4="${c}⦿${r} "

echo "Running pre-commit hooks"
set -x
node_modules/.bin/lint-staged -c .lintstagedrc.json
```

**Comment by typicode** [comment]
I see, thanks for the feedback. I would need a bit of time to think about it.

But you can refactor maybe to something like:

```
# Setup nice colorful prompt
# Use color "lime": https://tintin.mudhalla.net/info/256color/
c='\033[38;5;070m'
r='\033[0m'
PS4="${c}⦿${r} "

echo "Running pre-commit hooks"
echo "lint-staged -c .lintstagedrc.json"
lint-staged -c .lintstagedrc.json
```

`node_modules/.bin` is in the PATH now 👍 

Or you can wrap it in a shell:

```
sh << EOF
# your script
# ...
EOF
```

**Comment by typicode** [comment]
`v9.1.2` reverts this behavior

**Comment by glensc** [comment]
> 
> echo "lint-staged -c .lintstagedrc.json"
> lint-staged -c .lintstagedrc.json

no. i would not want to duplicate code lines :)

> 
> Or you can wrap it in a shell:
> 
> sh << EOF
> # your script
> # ...
> EOF

No. Hooks being fast is important to me. Slows down development the slower they are. Altho subshell invoke is likely minimal difference.

> node_modules/.bin is in the PATH now 👍

**Comment by glensc** [comment]
Reverted with https://github.com/typicode/husky/commit/20603175c10e35e58d1eadd20d08a491cfcc5b6a, so LGTM

**Comment by typicode** [comment]
Personally, I wouldn't worry about sub-shells. It's less than 1 ms diff on my machine.

```
time ls
time sh -c ls
```
