### ISSUE TITLE
File migrations should be conditional and/or optional

### ISSUE THREAD

**Issue by moltar** [typicode/husky#1477]
This line here tries to rewrite hook files:

https://github.com/typicode/husky/blob/f6cc4108837863bfbd31a861fdd8422637a492b1/index.js#L25

I have hook files managed by another idempotent tool that will reset the hooks back to their original state; therefore, the files are read-only.

I think the code that writes the file back should be also conditional:

```js
if (prev !== next) {
  console.log(`husky - removed deprecated code from ${hp}`)
  f.writeFileSync(hp, next)
}
```

Or there should be a way to turn off these migrations entirely.

Right now Husky install fails because of that with:

```
❯ pnpm husky
node:fs:596
  handleErrorFromBinding(ctx);
  ^

Error: EACCES: permission denied, open '.husky/post-rewrite'
    at Object.openSync (node:fs:596:3)
    at Object.writeFileSync (node:fs:2322:35)
    at file:///.../node_modules/.pnpm/husky@9.1.1/node_modules/husky/index.js:25:5
```

**Comment by typicode** [comment]
Hi,

It's fixed in v9.1.2. Only a message will be displayed.
