### ISSUE TITLE
Husky Installation Problem 

### ISSUE THREAD

**Issue by BonuV** [typicode/husky#148]
Below mentioned is the error message

npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn C:\WINDOWS\system32\cmd.exe;C:\WINDOWS\SysWOW64\cmd.exe
npm ERR! husky@0.14.1 install: `node ./bin/install.js`
npm ERR! spawn C:\WINDOWS\system32\cmd.exe;C:\WINDOWS\SysWOW64\cmd.exe ENOENT
npm ERR!
npm ERR! Failed at the husky@0.14.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above

**Comment by typicode** [comment]
sorry, didn't have the time to reply, closing as it's probably good now.
