### ISSUE TITLE
[docs] Please remove the following lines from your hook scripts

### ISSUE THREAD

**Issue by its-dibo** [typicode/husky#1480]
everytime I run `pnpm install` the file husky.sh updated with this content

```
echo "husky - DEPRECATED

Please remove the following lines from your hook scripts:

#!/usr/bin/env sh
. \"\$(dirname -- \"\$0\")/_/husky.sh\"

They WILL FAIL in v10.0.0
"
```

I searched for this warning in the docs, but it is not found anywhere

do you mean we have to replace

```
#!/usr/bin/env sh
. "$(dirname "$0")/_/husky.sh"
```

with

```
#!/usr/bin/env sh
. "$(dirname "$0")/h"
```

in every hook file, or totally remove those couple of lines?

**Comment by jljouannic** [comment]
The release notes of [v9.0.1](https://github.com/typicode/husky/releases/tag/v9.0.1) indicate those two lines have to be removed (see the "How to Migrate" section)

**Comment by tw3** [comment]
it looks like index.js will unconditionally add that "Please remove the following two lines..." message to husky.sh

![image](https://github.com/user-attachments/assets/50d9823e-1acf-4f70-a3a0-133b22823649)

is that true?

**Comment by 3h4x** [comment]
Why not add link in this console message to docs?
https://github.com/typicode/husky/releases/tag/v9.0.1
