### ISSUE TITLE
Not able to directly use package scripts (Zsh, Yarn zero-install)

### ISSUE THREAD

**Issue by Virakal** [typicode/husky#1485]
I have a simple `prepare-commit-msg` hook with the following contents:

```sh
yarn jira-prepare-commit-msg $1
```

If I'm understanding the 9.0.0 release notes correctly I should be able to change this to just `jira-prepare-commit-msg $1` but that fails.

```
.husky/prepare-commit-msg: 1: jira-prepare-commit-msg: not found
husky - prepare-commit-msg script failed (code 127)
```

Not sure if this is a bug or if I'm misunderstanding the feature? I'm using Yarn zero-install with Husky 9.1.4, Yarn 4.3.1, zsh 5.8.1, node 20.16.0. Node is shimmed in by mise and Yarn is installed through corepack. I'm on WSL 2.

Relevant parts of package.json:
```jsonc
{
  // ....
  "devDependencies": {
    "husky": "^9.1.4",
    "jira-prepare-commit-msg": "^1.7.2"
  },
  "packageManager": "yarn@4.3.1+sha512.af78262d7d125afbfeed740602ace8c5e4405cd7f4735c08feb327286b2fdb2390fbca01589bfd1f50b1240548b74806767f5a063c94b67e431aabd0d86f7774"
}
```

**Comment by typicode** [comment]
It works if your package manager creates `node_modules/.bin` directory. I think zero install works differently, so you have to use `yarn ...`.

**Comment by Virakal** [comment]
Fair enough, thanks.
