### ISSUE TITLE
Carriage return breaks scripts.

### ISSUE THREAD

**Issue by Mardoxx** [typicode/husky#1488]
```
yarn run typecheck
yarn run lint .
```

![image](https://github.com/user-attachments/assets/10486dbb-2a0e-4022-b3a9-165232ab7712)

Breaks with

```
error Command "typecheck\r" not found. Did you mean "typecheck"?
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
husky - pre-commit script failed (code 1)
```

**Comment by Mardoxx** [comment]
Removing the carriage return it works.

`Linux b4d87959f660 5.15.153.1-microsoft-standard-WSL2 #1 SMP Fri Mar 29 23:14:13 UTC 2024 x86_64 Linux`

**Comment by typicode** [comment]
Are you on Windows?
