### ISSUE TITLE
please update your docs

### ISSUE THREAD

**Issue by vipsunwei** [typicode/husky#1490]
**Troubleshoot**
- [ ] Before creating an issue, please check:
https://typicode.github.io/husky/troubleshoot.html

If you're migrating from husky 4, see:
https://typicode.github.io/husky/migrate-from-v4.html

**Context**
Please describe your issue and provide some context:
- Terminal or GUI client (PowerShell, Git Bash, GitHub Desktop, ...)
- If applicable, content of the failing hook
- If possible, minimal steps to reproduce the issue

Thank you!

**Comment by typicode** [comment]
What do you mean?

**Comment by vipsunwei** [comment]
文档版本不是9.1.4
也没有新版本的用法

发自我的iPhone


------------------ Original ------------------
From: typicode ***@***.***&gt;
Date: Wed,Aug 7,2024 9:29 PM
To: typicode/husky ***@***.***&gt;
Cc: vipsunwei ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [typicode/husky] please update your docs (Issue #1490)





 
What do you mean?

**Comment by typicode** [comment]
The english version is up to date.
A PR would be needed for the simplified chinese version.
