### ISSUE TITLE
How to control documentation translations versions?

### ISSUE THREAD

**Issue by Byron2016** [typicode/husky#1507]
**Troubleshoot**
- [ x ] Before creating an issue, please check:
https://typicode.github.io/husky/troubleshoot.html

**Context**
I would like to know what is the best way to control husky's documentation transltations, I made translations to Spanish based on English versions updated on these dates and with these last file commit numbers:

| English' doc file           | Commits on  | Commit number                                                  |
| ------------------------ | -------------- |----------------------------------------------------- |
| config.mts                   | Aug 24, 2024 | c5f4f483f8e02b1daac8b05041714809afb10c31  |
| get-started.md            | Jul 18, 2024   | 71e5dcbbd925f4b8d32bc02f8a008ccb9ccd63f3 |
| how-to.md                  | Mar 9, 2024   | e37252c5dbe762482ceedf57ac9c5c74517f0287 |
| index.md                     |Jul 18, 2024    | 902749b18f5ac6c592497eb1890b87930f5c250e |
| migrate-from-v4.md   | Jul 17, 2024   | e0994a4f600c3caf9e9a3561c231d048610784db |
| sponsorkit.config.js     | Jan 24, 2024  | ec13855c167bcead06523ae43ca1b5152d77810f |
| troubleshoot.md         | Jul 19, 2024   | f6cc4108837863bfbd31a861fdd8422637a492b1 |

- How to know if there are an update of English's doc file?
- How translators could have notice about the need of an update of its translations?
	

Thank you!

**Comment by typicode** [comment]
Honestly, I don't know. I'm not fond of translations as things can drift and become out of date.
So having them is mostly an experiment.

The good thing is that husky isn't a project that changes too much.
