### ISSUE TITLE
[enhancement] Custom npm binary/script

### ISSUE THREAD

**Issue by fcarreiro** [typicode/husky#151]
Hi all!

I have the following use case: I have a few projects where we use Docker in the development environment. Basically, I don't have node/npm installed in my computer. I do have git, but everything else is encapsulated in the docker containers.

The problem, as you can probably foresee, is that even though husky gets installed and the hooks are setup correctly, it fails when trying to find node/npm because, well, it doesn't exist outside the container.

This can be fixed, however, if I manually change the hooks to use "the npm inside the container". That is, instead of executing `npm run prepush` it would run something like `docker-compose api --rm run "npm run prepush"`. More elegantly, I can setup a script in my project (say `bin/dnpm`) which just redirects the npm arguments to the binary inside the container, then I can instruct husky (well, the hooks) to use this binary.

What I'm requesting/proposing here, is to create some way to explicitly tell the hooks where to find npm command (or better, something like the `dnpm` script). One possibility is to have a `.huskyrc` file which gets sourced from the hooks (`source .huskyrc` if existing) and which exports some kind of ENV var like `NPM_SCRIPT`. Then the hook checks whether `NPM_SCRIPT` is defined and uses that script, otherwise it goes on as usual.

I open the discussion of whether this implementation would make you happy. I could probably submit a PR for this when I have some more time.

Thanks!

**Comment by valorize** [comment]
https://github.com/typicode/husky/pull/190

**Comment by use-strict** [comment]
Same problem here. I'm unsure why `run-node` is needed at all. I'd expect what's written in the hook file to be the exact command that I have in `.huskyrc` hooks section.

**Comment by typicode** [comment]
Hi @fcarreiro,

It's maybe possible to do this now with the current version and `run-node`:
https://github.com/sindresorhus/run-node#customizable-cache-path-and-error-message

You can export a variable `RUN_NODE_CACHE_PATH` env which points to Node.

@use-strict as for why `run-node`, it's to be able to run husky in GUI clients, particularly when Node was installed using `nvm`.

**Comment by azz** [comment]
Hey @typicode, was just trying to do this (run `node` via `docker-compose`), and I'm not quite sure I'm following your suggestion. If there was a `bin/node` in `$PATH` it might work, but there's no way to guarantee that `bin/node` ends up in `$PATH` without first `source`ing a known file (like `.huskyrc` as suggested above.)

**Comment by azz** [comment]
Friendly bump. As far as I could surmise it's not currently possible to convince `run-node` to execute `docker run`/`docker-compose run` instead of `node`.

My suggestion is something like:

```json
{
  "hooks": {
    "pre-commit": "node my-script"
  },
  "config": {
    "node": "docker-compose run --rm --no-deps app node"
  }
}
```
