### ISSUE TITLE
Add husky label to warning for deprecated commands

### ISSUE THREAD

**Issue by smackfu** [typicode/husky#1537]
**Troubleshoot**
- [x] Before creating an issue, please check:
https://typicode.github.io/husky/troubleshoot.html

**Context**
There are some situations where npm commands are run but the commands themselves are shown.  In these cases, it may not be clear that the deprecation warning is coming from husky.

Here's an actual example:
```
$ npx npm-check-updates --interactive --format group
...
 husky                                     ^8.0.3  →   ^9.1.6

✔ Run npm install to install new versions? … yes
Installing dependencies...
install command is DEPRECATED
```

Suggestion is to change the message to `husky install command is DEPRECATED` or something similar.

**Comment by typicode** [comment]
Good point, do you want to make a PR?

**Comment by smackfu** [comment]
> Good point, do you want to make a PR?

Sure, will do it over the weekend.

**Comment by smackfu** [comment]
> Good point, do you want to make a PR?

Done! All the other DEPRECATED warnings already had it actually.
