### ISSUE TITLE
The same task works with 'precommit' but doesn't with  'prepush'

### ISSUE THREAD

**Issue by Alexintosh** [typicode/husky#154]
Hello, 

This is my package configuration in the package.json
```
{
"precommit": "npm run validate",
"validate": "npm run lint && npm run scss-lint && npm run test"
}
```

I'm now trying to switch the hook from precommit to prepush, when I do that the even if the tasks have no errors and exit with 0 the push doesn't go through.

Any help?

**Comment by jaufgang** [comment]
I am experiencing the same problem.  Also tested it out on `^0.15.0-beta.11`.
```json
"husky": {
        "hooks": {
            "pre-push": "npm  run tslint"
        }
    }
```
doesn't run the hook and allows code to be pushed when `tslint` fails, but changing it to `pre-commit` does cause the commit to fail.

**Comment by ix-xerri** [comment]
At the moment if I run `npm test` the commit is paused but if I run `npm run lint` on an ionic project it commits. Warning are generated but it still commits

**Comment by sneas** [comment]
Has anyone succeeded with it?

`"prepush": "npm run test"`, `"prepush": "npm test"`, `"prepush": "jest"` all run tests but do not push.

**Comment by etienne-bondot** [comment]
Same with `v1.0.0-rc.9` here. Any news ?

**Comment by fgcui1204** [comment]
any update for this issue???

**Comment by cc-xerri** [comment]
his was solved in an ionic project by adding:

`"scripts": {
    "lint": "ionic-app-scripts lint --bailOnError true"
}`

Note the `-bailOnError true`

**Comment by typicode** [comment]
Cleaning old issues and also it may have been solved since then. Feel free to create a new issue if needed.
