### ISSUE TITLE
[docs] Docs require local Git version > 2.9 but actual latest git version is 2.47.

### ISSUE THREAD

**Issue by WhereJuly** [typicode/husky#1540]
**Troubleshoot**
- [x] Before creating an issue, please check:
https://typicode.github.io/husky/troubleshoot.html

My installation is not a migration from husky 4

**Context**
Reading Husky Troubleshoot [Hooks not running](https://typicode.github.io/husky/troubleshoot.html#hooks-not-running) docs section I see
> 3. Confirm your Git version is above 2.9.

whereas Git [downloads](https://git-scm.com/downloads) page says the latest version 2.47.0 (2024-10-06).

Is it intentional? Can you clarify this?

Thanks.

**Comment by MarkusWahlman** [comment]
2.9 -> 2.20.0 .... -> 2.47.0

Version 2.47.0 is higher than 2.9

**Comment by WhereJuly** [comment]
@MarkusWahlman Thanks, just got that 9 < 47 :((
