### ISSUE TITLE
How to access $GIT_PARAMS in bash hook?

### ISSUE THREAD

**Issue by JohnAllen** [typicode/husky#156]
There are no extra params passed to a bash hook.  `$GIT_PARAMS` does not work.  (I have googled this extensively and not found any examples, same with the issues) 

The bas hook is properly called but the commit message that is normally available as `$1` in a normal prepare-commit-msg hook is not available, nor is `$2` or `$3`.  So how can I actually use an existing bash hook to prepare-commit-msg with husky?

**Comment by elyseholladay** [comment]
@JohnAllen GIT_PARAMS works for me when passed to .sh script file via `preparecommitmsg`. It won't work on `precommit`.

https://github.com/typicode/husky/issues/113 
https://github.com/typicode/husky/issues/92

**Comment by typicode** [comment]
Closing it, feel free to add a comment if you still experience the issue.
If that's the case I would be interested in knowing which tool/code editor/OS you're using to commit
