### ISSUE TITLE
git hook to run a command after `git pull` if a specified file was changed.In this example it's used to run `npm install` if package.json changed

### ISSUE THREAD

**Issue by jitendravyas** [typicode/husky#158]
How to to do the same with this husky https://gist.github.com/sindresorhus/7996717 ?

**Comment by xml** [comment]
Hmmm... I haven't tried this yet, but, is there any reason you can't just save sindre's post-merge.sh into your repo, then set the package.json's `post-merge` command to run that script via husky? Would the variables no longer be correct?
