### ISSUE TITLE
Documentation about behaviour on systems as husky is introduced

### ISSUE THREAD

**Issue by thedamon** [typicode/husky#159]
I'm just curious about how including this will affect other developers on our team, and I didn't see a note about this in the readme. 

We have a monorepo that uses a lot of different languages (with a java base). But my team is front end developers and we use js/css/all that good stuff in a subdirectory. If we add husky to our package.json subdirectory how will that affect:

1. people who haven't run the new `npm install`/`yarn` yet
2. people who have never run `npm install`
3. people who do not have node on their system.

etc etc

I'm trying to see what we need to have each developer do in order for the githooks to be applied, and how it will impact them if they don't do anything.

**Comment by typicode** [comment]
Good questions. I'll see how the README could be updated.

1. and 2. People who haven't run `npm install/yarn` won't have Git hooks installed, until they run it.
3. If Husky is installed and can't find `npm`, il will display a warning message and won't run scripts. In other words, it won't prevent people from committing, it'll just let them know it didn't succeed at running the hook.

Overall, Husky tries to not get in the way and provides information about skipping hook if necessary.

> I'm trying to see what we need to have each developer do in order for the githooks to be applied, and how it will impact them if they don't do anything.

Front-end will get it automatically but back-end won't unless they run `npm install`.

BTW, this kind of structure isn't supported

```
.git
A/package.json
B/package.json
```

If Husky is defined in both A and B, it will just run for 1 of the 2.
