### ISSUE TITLE
Different outputs when running `npm run precommit` vs `git commit`

### ISSUE THREAD

**Issue by mrmartineau** [typicode/husky#164]
I'm experiencing differences when I run these two commands:

```
npm run precommit
```
and
```
git commit ...
```
Running the `npm` command seems fine, but when I `git commit ..`, the tests fail. Are the two things not supposed to be the same or are there other differences? 

By the way, I am using lint-staged, which is running some tests on the staged files.

**Comment by typicode** [comment]
They are supposed to be, you may want to check that the right version of Node is picked by husky (it's displayed when you run `git commit ...`).

AFAICT that may be the only difference.

**Comment by mrmartineau** [comment]
@typicode thanks. I'll take a look today and get back to you.

**Comment by nxmohamad** [comment]
@mrmartineau I'm experiencing a similar issue. have you made progress with yours?

**Comment by mrmartineau** [comment]
@nxmohamad nope, I haven't been able to figure it out. I stopped using `lint-staged` and that seems to improve things. Will keep you posted if I find anything out

**Comment by nxmohamad** [comment]
so I made a mini break through in my case. tell me if this worked for you.

1. Did you use any other packages for git hooks before? If so there might be remnants of the old hook.

In  my case, the command in .git/hooks was different. Check out what yours is. 
I ended up ditching husky and just cutomising my own pre-commit.

**Comment by uhlryk** [comment]
I had same issue.
For me the reason was that git hooks desync with this library.
First check what you have in git hooks, for example for pre-commit:
```
cat .git/hooks/pre-commit
```
In my case there was hook created by different hook library (not sure how it happen, but never mind).

What helped me"
 * uninstall old hook library
 * uninstall husky
 * install husky

Check hooks.
