### ISSUE TITLE
Husky pre-commit checks the files of the filesystem, not the ones in the git index

### ISSUE THREAD

**Issue by MimoMoreno** [typicode/husky#165]
I don't know if in any of the closed issues this has been already discussed.
I'll put an example to reproduce the issue: 
Let's suppose that a file has a linter error, so that husky doesn't allow to commit. If I change the file, fixing the error, I can commit it **without** doing `git add fileName`; so I'll be committing and pushing a wrong file.

**Comment by typicode** [comment]
Hi @MimoMoreno,

It's on purpose, husky doesn't do more than running associated `npm` scripts. The benefit is that it won't do anything magical so it's simple to predict/debug.

For your case, maybe [lint-staged](https://github.com/okonet/lint-staged) could help :)
