### ISSUE TITLE
Disable prepush on remote branch deletes

### ISSUE THREAD

**Issue by craigryan** [typicode/husky#169]
I don't fancy running the prepush hook and a full lint + test run in my case just when deleting a remote branch either via command line or within Sourcetree. 

Ideally husky should handle either 

`git push origin :mybranch`
`git push origin --delete mybranch`

as deletions rather than push commands and not fire prepush.

**Comment by typicode** [comment]
I don't really know how it could be done, and may be out of scope for Husky as it just runs scripts associated to Git hooks, nothing more.

That said, if you run the command with the `-n/--no-verify` flag (`git push origin :mybranch -n`) maybe you can skip the hook :)

**Comment by elitwin** [comment]
The pre-push hook that Husky creates looks for an ENV variable to skip the hook (at least the latest version that I just installed).

$ HUSKY_SKIP_HOOKS=true git push origin :mybranch

**Comment by moshmage** [comment]
> The pre-push hook that Husky creates looks for an ENV variable to skip the hook (at least the latest version that I just installed).
> 
> $ HUSKY_SKIP_HOOKS=true git push origin :mybranch

While this works, it's a bit mad having to set a global variable to true, delete the branch, and then setting up the global variable again. 

@typicode aren't you looking at the command? can't you simply add a config value `shouldHuskyBeforeBranchDeletion: boolean` and then around `runner/index.ts:37` check if cmd has either --delete, -d or :branchname and if both are tru return 0 from husky? (honest question here, like I said: quick glance)

**Comment by kyle-mcknight** [comment]
> $ HUSKY_SKIP_HOOKS=true git push origin :mybranch

Is there a way to set up multiple reasons to skip the hook? Such as this one _and_ when rebasing?
