### ISSUE TITLE
Install task works incorrect if migrate from pre-commit

### ISSUE THREAD

**Issue by evgenizhuk** [typicode/husky#170]
Husky doesn't replace .git/hooks/pre-commit script when when it replaces [pre-commit](https://github.com/observing/pre-commit).
Now I'm using pre-commit package and when it installed it checks `.git/hooks/pre-commit file`. In case this file exists pre-commit beck-upped it and creates new one, old file gets extension .old.
When we uninstall pre-commit with `yarn remove pre-commit` old file restored from beck-up.
When we install husky it check `.git/hooks/pre-commit` file too, and do not replace it if file already exists, because husky suggests that file was created by 'ghook'.
So in case if you don't have `.git/hooks/pre-commit.old` file, yarn remove pre-commit && yarn add husky will work, otherwise .git/hooks/pre-commit: line 2: ./node_modules/pre-commit/hook: No such file or directory error will appear.

**Comment by typicode** [comment]
Hi @evgenizhuk,

I think a PR to automatically migrate pre-commit hooks would be great in order to avoid such issues. Husky already does this for ghooks, so it should be simple to add support for pre-commit :)

**Comment by typicode** [comment]
Automatic migration for `pre-commit` has been added in `v0.15 beta`
https://github.com/typicode/husky/tree/dev

Closing this issue :)
