### ISSUE TITLE
Not clear how to use Husky with existing hooks

### ISSUE THREAD

**Issue by Peeja** [typicode/husky#171]
I have a pre-commit hook already. Husky, kindly, does not overwrite it when it installs. However, I'd like to run Husky's pre-commit hook as well. There doesn't appear to be an easy way to do that. The best I can imagine is to create a new project entirely, install Husky into it, and copy that pre-commit hook into my own.

Is there an easier way to do this that could be documented? And if not, is it possible to create an easier way to do it? Ideally, I'd like to copy and paste a one-line invocation from the Readme into an appropriate place in my own hook.

**Comment by typicode** [comment]
If you move your hooks in `project/hooks` and have for example:

```json
{
  "precommit": "./hooks/pre-commit && npm test"
}
```

This way husky would run your pre-commit script and tests.

Would that work for you?

**Comment by Peeja** [comment]
This isn't a hook shared by the rest of my team, this is a personal hook that comes from my git template, so I can't change the codebase to accommodate it.

**Comment by typicode** [comment]
(wrong tag, wanted to put it on another issue)

I see.

As an alternative, you could make it so that `husky` doesn't overwrite the `pre-commit` hook by removing `#husky` line. This way, you could edit it to your liking and add your custom script.

The downside of it is obviously that you won't get updates, but that's maybe acceptable for your personal workflow.

Besides that, I can't think of another way :/

**Comment by Peeja** [comment]
Well, it would be nice if there were a single line I could add to my existing hook that would invoke the Husky hook. Is that not possible?

**Comment by cdeutsch** [comment]
I ended up renaming the existing hooks I was using by adding `-orig` to the name.

Ex. `pre-commit` -> `pre-commit-orig`

Then re-ran the husky install
```
node node_modules/husky/bin/install.js
```

Then added the following to the top of `pre-commit`, etc

```
# run the original hook
echo "`dirname $0`"/pre-commit-orig
"`dirname $0`"/pre-commit-orig || {
  echo
  echo "pre-commit-orig failed"
  exit 1
}

########################################################
# begin husky 0.14.3
########################################################

...
```

**Comment by jimmynotjim** [comment]
Running into this issue as well. As a library maintainer, I can't ask users to modify their existing hooks to ensure the hooks in my library are run, and I maintain a very small library compared to those listed in the Readme. 

Is it not possible to append existing hook files with the Husky script? It looks like cleanup would be more complicated but if there were a closing identifier you could eliminate the content between the two and leave the original content in place when uninstalling. 

I'm willing to explore this suggestion in a PR but want to check that it would be accepted and this isn't something you've already explored in the past before I do. Let me know and I'll try to find time this week or next.

**Comment by trusktr** [comment]
Appending to existing files, and wrapping the husky content between two well-named comment blocks (to make updates possible), seems like a good idea.

**Comment by jakewies** [comment]
I'm having an issue here as well. I've tried to find a viable solution and what I have right now is to:

```
git config --global init.templateDir '~/.git_template'
```

Then inside of `~/.git_template` I add a `/hooks` directory, and move all of my global hooks there. 

Now when running `git init` git will move my `/hooks` directory to the project's `.git` folder.

When I then install `husky` my custom hooks and the hooks installed by `husky` can live side by side. I've tested this and it seems to work out great. For reference I recently added an issue to this repository but have since closed https://github.com/typicode/husky/issues/391.

**Comment by sergiubologa** [comment]
I think the best approach would be to make husky append it's hooks to the existing ones. Are there any possible issues with this?

**Comment by chat-du-cheshire** [comment]
Hi, I'm trying to run custom hook from husky. I have package.json file and folder "custom-hooks" where I've my custom pre commit. But config like this 
"husky": {
    "hooks": {
      "pre-commit": "./custom-hooks/pre-commit"
    }
  }
Fail with error ". is not internal or external command"

**Comment by FullStackForger** [comment]
> I think the best approach would be to make husky append it's hooks to the existing ones. Are there any possible issues with this?

Appending seems straightforward but uninstalling with `git lfs uninstall` would require some extra work too.

**Comment by typicode** [comment]
Cleaning old issues. It may be possible to do something with `~/.huskyrc` though.

**Comment by josephShield** [comment]
I also advocate for reopening this issue.

I'm trying to add a new git pre-commit hook, and depending on whether I run my gradle build first or npm ci first, I get a different `.git/hooks/pre-commit` file... They're competing and I can't figure out how to make that stop. My research led me here, to this 4+ year old thread.

**Comment by edjchapman** [comment]
This is still an issue.  Pretty common for people to have other git hooks.  Husky just hijacks the git config.

The best I've come up with is to add `pre-commit run` to the husky file, but it's hacky.
