### ISSUE TITLE
env variable to prevent install

### ISSUE THREAD

**Issue by noamokman** [typicode/husky#172]
Hi,
Can we add an env variable to disable the install script?
something like the CI detection.

Let me know if I should open a PR.
Thanks

**Comment by typicode** [comment]
Hi @noamokman,

What's your use case? Or what issues are you facing?

Alternatively, depending on your use case one of these solutions may work:
- you can use `npm install --ignore-scripts` but it will ignore all `postinstall` scripts
- you can only install `dependencies` and not `devDependencies` which would prevent install

**Comment by noamokman** [comment]
Yeah,
I use husky on 2 generator project, 
A part of the test it to run `npm install` on an inner folder.
The generated folder then installs husky on a folder with out a .git directory, so it traverses up to the git folder of the generator, this breaks existing hooks.

Adding a new environment variable should be quit simple. 
Would be happy to do it for you. 

Maybe `SKIP_HUSKY_INSTALL`.

Thanks!

**Comment by typicode** [comment]
After giving some thoughts, PR welcome :)

Seems like there was something that was started to control installation:
https://github.com/typicode/husky/blob/master/bin/install.js#L10

`HUSKY_IGNORE_CI` could be refactored to `HUSKY_SKIP_INSTALL`
