### ISSUE TITLE
Error running commands in Windows

### ISSUE THREAD

**Issue by Sibiraj-S** [typicode/husky#175]
While running this

`"precommit": "SET NODE_ENV=production && node_modules/.bin/webpack",`

with husky, it is reporting that unable to find `node_modules` command not found. but when I execute the precommit without husky i.e., `npm run precommit` It is working fine.

**Comment by typicode** [comment]
Hi @Sibiraj-S,

You can probably change your code to this:

````
"precommit": "SET NODE_ENV=production && webpack",
````

`npm` automatically adds `node_modules/.bin` to `PATH`. This should solve the `node_modules` not found issue.

You may also want to check https://www.npmjs.com/package/cross-env for setting environment variable in a way that works on Windows, OS X and Linux.

**Comment by Sibiraj-S** [comment]
Yeah I currently use this
>You can probably change your code to this:
>"precommit": "SET NODE_ENV=production && webpack",

but what if we have to run anything that is not in `node_modules/.bin` and I am not referring particularly to `node_modules`. It is just a scenario.

**Comment by Sibiraj-S** [comment]
@typicode ?

**Comment by Sibiraj-S** [comment]
@typicode  is this fixed? I suppose it is working now?
