### ISSUE TITLE
error on OSX

### ISSUE THREAD

**Issue by syzer** [typicode/husky#177]
```.git/hooks/pre-push:407
  var ignoreBranch = prepushSection.ignoreBranch;
                                   ^
TypeError: Cannot read property 'ignoreBranch' of undefined```

**Comment by syzer** [comment]
after command:
```
git -c core.quotepath=false -c log.showSignature=false push --progress --porcelain origin refs/heads/feature/eslint-all-things:feature/eslint-all-things
```

**Comment by valorize** [comment]
Please be more spefic in your title and the exact problems your facing.

**Comment by typicode** [comment]
Hmm didn't really encounter something like that on OS X and not sure how to reproduce. Anyway I hope that you found a solution, feel free to open or comment on this issue if you encounter other problems with husky :)

**Comment by syzer** [comment]
@valorize `prepushSection` can be undefined , that was my problem :D
