### ISSUE TITLE
git add could be invoked at the end of pre-commit for files added before

### ISSUE THREAD

**Issue by wkwiatek** [typicode/husky#18]
Currently I have the case with [jsBeautify](https://github.com/beautify-web/js-beautify) which modifies some files during pre-commit. The problem is that after that modified files are not automatically added to commit so that I have to run `git add` again. 

It would be perfect if files that were added to commit before hook could be added automatically again at the end of the pre-commit.

**Comment by typicode** [comment]
What about something like this?

```javascript
"precommit": "js-beautify index.js && git add index.js"
```

You may want to extract this to a script if it's too long. For example with a Node script, it could be:

```javascript
// precommit.js
var execSync = require('child_process')
execSync('js-beautify index.js')
execSync('git add index.js')
```

```javascript
"precommit": "node precommit"
```

**Comment by wkwiatek** [comment]
I'm aware I can do it in my own script but for me it was kinda like expected behaviour after pre-commit script. I mean when one of files that were added and script makes change, it will be added again after pre-commit. I found it like nice-to-have general feature to your library.

**Comment by typicode** [comment]
Sorry, I misunderstood what you meant.

Yes it would be a nice feature, but personally for this project I prefer to avoid "magical" features. What's happening during a `pre-commit` hook is only what's defined in the `precommit` script.

Thanks for the feature suggestion :)

**Comment by wkwiatek** [comment]
That's fair enough :) I think that it closes the issue. Thanks for your reply!

**Comment by typicode** [comment]
You're welcome :)
