### ISSUE TITLE
Precommit file : should it be in .gitignore? relative path produces git changes

### ISSUE THREAD

**Issue by gkatsanos** [typicode/husky#184]
Hello, there was a file in our repo which was a pre-existing precommit script that was modified when we added husky.
`misc/pre-commit`

In it, there's
```bash
load_nvm () {
  # If nvm is not loaded, load it
  command_exists nvm || {
    export NVM_DIR=/Users/Georgios/.nvm
    [ -s "$1/nvm.sh" ] && . "$1/nvm.sh"
  }

  # If nvm has been loaded correctly, use project .nvmrc
  command_exists nvm && [ -f .nvmrc ] && nvm use
}
```

As you see there's a path that is modified someone else is running the script on his machine (its the home folder)

Should I include this file in .gitignore or did I do something wrong during the project setup.?

**Comment by typicode** [comment]
Hi @gkatsanos,

Sorry for the delay. Next version of husky (`v0.15`) won't have absolute paths in the generated script anymore (like home folder) so I guess it's fine to close this issue.

If you still have this issue with `husky@next`, feel free to update.
