### ISSUE TITLE
Apply husky git hook to specific branch only 

### ISSUE THREAD

**Issue by IAMtheIAM** [typicode/husky#186]
Is there a way to configure husky to apply a specific git hook, i.e. `prepush`  ONLY to a specific branch i.e. `master`?

I know I can modify the hooks in the package, but that makes it more complicated because husky installs its own hooks, then I have to go overwrite it with a modified version using some scripts. 

Mainly the purpose is to only run e2e or unit tests before pushing to master, but not every time I push to dev (which gets annoying waiting and seeing the browsers popup every time).

**Comment by IAMtheIAM** [comment]
I modified the pre-push hook like this and it works like a charm

```bash
#!/bin/sh
while read oldrev newrev refname
do
    branch=$(git rev-parse --symbolic --abbrev-ref $refname)
    if [ "master" == "$branch" ]; then

        # If we're on the Master branch, then Do something
        # Prepush script from husky 0.14.3

      command_exists () {
        command -v "$1" >/dev/null 2>&1
      }

      has_hook_script () {
        [ -f package.json ] && cat package.json | grep -q "\"$1\"[[:space:]]*:"
      }

      cd "frontend"

      # Check if prepush script is defined, skip if not
      has_hook_script prepush || exit 0

      # Node standard installation
      export PATH="$PATH:/c/Program Files/nodejs"

      # Check that npm exists
      command_exists npm || {
        echo >&2 "husky > can't find npm in PATH, skipping prepush script in package.json"
        exit 0
      }

      # Export Git hook params
      export GIT_PARAMS="$*"

      # Run npm script
      echo "husky > npm run -s prepush (node `node -v`)"
      echo

      npm run -s prepush || {
        echo
        echo "husky > pre-push hook failed (add --no-verify to bypass)"
        exit 1
      }
    fi
done

```

**Comment by Asuza** [comment]
Could you also accomplish this by checking what branch you're in within your _package.json_ file? Something along the lines of this pseudo-code:
```
"prepush": "if branch is master; then npm run master_prepush; fi"
```

**Comment by dgrusemann** [comment]
I ended up using https://github.com/kevinoid/git-branch-is.

`"prepush": "if git-branch-is master; then yarn test; fi"`

**Comment by budajeff** [comment]
When I try using `git-branch-is` i get the error "master was unexpected at this time." Any ideas?

`"pre-commit": "if git-branch-is master; then lint-staged && git-authors-cli && npm run gen-docs && node tools/add-size-badge.js && git add package.json README.md docs/*; else echo 0; fi"`

**Comment by giusnadd** [comment]
@budajeff try this:
"pre-commit": "(git-branch-is master && lint-staged && git-authors-cli && npm run gen-docs && node tools/add-size-badge.js && git add package.json README.md docs/*) || true"

**Comment by denisk20** [comment]
I ended up with this to limit the hooks to `dev` and `master`:

	"husky": {
		"hooks": {
			"pre-commit": "branch=`git branch | grep \\* | cut -d ' ' -f2`;branchesToCheck=(\"dev\" \"master\"); [[ \" ${branchesToCheck[@]} \" =~ \" ${branch} \" ]] &&  yarn check-flow-lint || exit 0",
			"pre-push": "branch=`git branch | grep \\* | cut -d ' ' -f2`;branchesToCheck=(\"dev\" \"master\"); [[ \" ${branchesToCheck[@]} \" =~ \" ${branch} \" ]] &&  yarn check-flow-lint-test || exit 0"
		}
	}

For some reason extracting into a variable didn't work for me (via `$npm_package_myVar`) so I had to duplicate large pieces of code.,

**Comment by cope** [comment]
> I ended up with this in order to limit the hooks to `dev` and `master`:
> 
> ```
> "husky": {
> 	"hooks": {
> 		"pre-commit": "branch=`git branch | grep \\* | cut -d ' ' -f2`;branchesToCheck=(\"dev\" \"master\"); [[ \" ${branchesToCheck[@]} \" =~ \" ${branch} \" ]] &&  yarn check-flow-lint || exit 0",
> 		"pre-push": "branch=`git branch | grep \\* | cut -d ' ' -f2`;branchesToCheck=(\"dev\" \"master\"); [[ \" ${branchesToCheck[@]} \" =~ \" ${branch} \" ]] &&  yarn check-flow-lint-test || exit 0"
> 	}
> }
> ```
> 
> For some reason extracting into a variable didn't work for me (via `$npm_package_myVar`) so I had to duplicate large pieces of code.

And this goes into package.json?

**Comment by cope** [comment]
This worked for me.

I added this into `.husky/pre-commit` and `.husky/pre-push` files:

```
branch="$(git rev-parse --abbrev-ref HEAD)"
if [ "$branch" = "whatever" ]; then
	echo "whatever branch is special, blabla..."
	...some package.json script calls, eg. pnpm format or pnpm test, etc...
fi

```
