### ISSUE TITLE
post-rewrite and pre-rebase hooks

### ISSUE THREAD

**Issue by kyriacos** [typicode/husky#19]
Hey! Thanks for building husky. It's a great idea :)

It would be great if those 2 hooks where added if possible. Can't fully switch to husky at the moment.

For now we are using a script to install the hooks. Just found husky and decided to give it a go.

Thanks

**Comment by typicode** [comment]
Hey! Thanks :)

Sure. What would be the use case for `post-rewrite` and `pre-rebase` (it's for giving examples in the README).

**Comment by kyriacos** [comment]
Thanks!

Well for both hooks and the `post-merge` we actually use it when the `package.json` file changes. We have a script that gets run on `post-merge`, `post-rewrite` and `pre-rebase` and if the `package.json` has changed then we just ask the user to run `npm install`

I would suggest not adding an example though, and just linking to the `git-scm` website.

Got this from https://git-scm.com/book/es/v2/Customizing-Git-Git-Hooks:
> The pre-rebase hook runs before you rebase anything and can halt the process by exiting non-zero. You can use this hook to disallow rebasing any commits that have already been pushed.

>The post-rewrite hook is run by commands that replace commits, such as git commit --amend and git rebase.

**Comment by typicode** [comment]
Added in `v0.8.1` ;)

**Comment by kyriacos** [comment]
Thanks! :)

**Comment by typicode** [comment]
You're welcome :)
Thanks for using the project.
