### ISSUE TITLE
0.8.1 breaks on a git submodule

### ISSUE THREAD

**Issue by avaly** [typicode/husky#20]
```
$ git commit -m "Test"
/src/web-dev/.git/modules/web-tools/hooks/pre-commit: 5: cd: can't cd to ../../web-tools
```

Where the project structure is:
- `/src/web-dev` - git repo with multiple git submodules
- `/src/web-dev/web-tools` - one of such git submodules which contains a `package.json` and where husky is installed in `node_modules`

**Comment by Shutnik** [comment]
Same problem, but works well without [this](https://github.com/typicode/husky/commit/62ca38fb0f51b2106ad2ba0bafe3ac4366ded0cc) changes.

**Comment by IcanDivideBy0** [comment]
any updates on this ? does someons found a fix / workaround ?
