### ISSUE TITLE
Can't have a hook running in Windows

### ISSUE THREAD

**Issue by voroshkov** [typicode/husky#201]
Can you please help me understand how installed hooks are supposed to run in Windows?
Here's a piece of installed hook, which, being run in a command prompt produces an error on each line:
```
#!/bin/sh
#husky 0.14.3

command_exists () {
  command -v "$1" >/dev/null 2>&1
}

has_hook_script () {
  [ -f package.json ] && cat package.json | grep -q "\"$1\"[[:space:]]*:"
}
...
```

**Comment by trent-boyd** [comment]
@voroshkov: I'm not a Windows user, but the first line (the location of the `sh` executable needed to run the hook) is the Mac/Unix location. Git ships with its own version of `sh`, so try replacing that with `#!C:/Program\ Files/Git/usr/bin/sh.exe` instead!

**Comment by voroshkov** [comment]
Sorry, guys, the problem is artificial. Googling gave me a lot of reasons why git hooks might not run. One of them was mine: wrong hooks folder in git config. There's no problem with executing husky's hooks in Windows and @trent-boyd really knows why ;)
