### ISSUE TITLE
Use with git-worktree

### ISSUE THREAD

**Issue by pietro909** [typicode/husky#202]
I'm using [git-worktree](https://git-scm.com/docs/git-worktree) and my folders are structured this way:

    project
    |-master
    |-develop

I've installed *husky* in `develop` and it doesn't run the hooks. I've found that the hooks are installed under `master/.git/worktrees/develop/hooks` while in `develop/.git` all I have is:

    gitdir: /Users/pietro909/workspace/app/master/.git/worktrees/develop

How can I tell *husky* to use the right folder? Thanks!

**Comment by alexeyten** [comment]
What version of husky do you use?
It should be fixed in #114 that was landed in version 0.14

**Comment by pietro909** [comment]
I'm using ` "husky": "^0.14.3"` which should be fine.

**Comment by atompkins** [comment]
I believe I am seeing the same problem

**Comment by jas99** [comment]
@typicode Was still not working for me facing it.
Sent PR @ https://github.com/typicode/husky/pull/407

@pietro909 @atompkins Feel free to use package @jas99/husky in meantime.

Thx

**Comment by jellytux** [comment]
Does not work on "husky": "^1.0.0" pre-commits are not being triggered with git worktree.

**Comment by jas99** [comment]
@jellytux do `npm install @jas99/husky` or `yarn add @jas99/husky` :wink:

**Comment by jas99** [comment]
My PR #407 still under consideration

**Comment by bbugh** [comment]
#407 was accepted and launched in 2.2.0. Worktree support is working great for me now. 🎉

**Comment by typicode** [comment]
Closing, thanks again for the PR 👍
