### ISSUE TITLE
Is there an option to bypass or opt out of the hooks?

### ISSUE THREAD

**Issue by robdodson** [typicode/husky#206]
Sometimes when I'm working on a project I might be experimenting in a branch and knowingly doing stuff that's wrong or might make my linter mad. Is there a way to tell husky to ignore my commit and not run a hook against it? I guess I could write this myself with an environment variable but it seems like a possibly useful husky option.

**Comment by AlaaAttyaMohamed** [comment]
yes you can just write `git commit -m "bla bla" -n` 
the `-n` will get you bypass the hooks

**Comment by AlaaAttya** [comment]
yes you can just write `git commit -m "bla bla" -n` 
the `-n` will get you bypass the hooks

**Comment by AlaaAttya** [comment]
also you can use `git commit --no-verify` and `git push --no-verify`
`-n` means no verify

**Comment by robdodson** [comment]
oh thanks! I just learned about the `--no-verify` flag 😄

**Comment by timotgl** [comment]
Another, although radical option is to move the files in `.git/hooks` out of this directory, if you never want to run them for the current repo and can't be bothered to add `--no-verify` to every git command. The hooks come back if husky is reinstalled though.

**Comment by pascalgn** [comment]
For anyone who arrives here from Google: You can also use the `core.hooksPath` git configuration option, so for example
```
git -c core.hooksPath=/dev/null checkout master
git -c core.hooksPath=/dev/null pull
git -c core.hooksPath=/dev/null commit ...
git -c core.hooksPath=/dev/null push
...
```

**Comment by DesignByOnyx** [comment]
I'm spreading this information around as it's super useful:

As of `v2.4.0` you can now do `HUSKY_SKIP_HOOKS=1 git <command> ...`

**Comment by yrammos** [comment]
@DesignByOnyx this does not seem to skip the `post-commit` hook, unfortunately.

**Comment by DesignByOnyx** [comment]
@yrammos - if what you say is true, you should report a bug. However, looking at the code, it appears that husky exits early if you use `HUSKY_SKIP_HOOKS=1` or `HUSKY_SKIP_HOOKS=true`. Can you try running your script with `HUSKY_DEBUG=1`?

https://github.com/typicode/husky/blob/1286e3beb39c6f4baed4ad1515c0bbd4730b11b1/src/installer/getScript.ts#L58

Also, if you are calling git commands from a child process (eg. through npm scripts in package.json), then you might need to forward any environment variables manually:

```
HUSKY_SKIP_HOOKS=1 npm run commit-my-code
```
... and in your package.json:
```json
{
  "scripts": {
    "commit-my-code": "HUSKY_SKIP_HOOKS=$HUSKY_SKIP_HOOKS git commit"
  }
}

**Comment by ghedsouza** [comment]
Current solution is add `HUSKY=0` environment variable to your command, like so:
```
HUSKY=0 git push # yolo!
```
(Documented at https://typicode.github.io/husky/#/?id=bypass-hooks).

The `HUSKY_SKIP_HOOKS` no longer works (as of at least 6.0.0).
