### ISSUE TITLE
Using husky programmatically

### ISSUE THREAD

**Issue by tjk** [typicode/husky#207]
I have a patch that supports something like `husky.on('precommit', ...)` so that a node module can install required git hooks. Part of this involves disabling the `install`, `uninstall` npm scripts (I was looking for ways to do this conditionally depending on whether husky is a dependency or sub-dependency). Is there a way to do something like this already? Is this something husky would like to support?

**Comment by typicode** [comment]
Hi @tjk,
 
What's your use case/need? You can disable scripts globally when installing with `npm install --ignore-scripts` but that may be too much.

**Comment by iamstarkov** [comment]
I need this as well

**Comment by typicode** [comment]
Closing as it's an old issue. That said, thanks for the feedback! :slightly_smiling_face:
