### ISSUE TITLE
post push

### ISSUE THREAD

**Issue by Chabane** [typicode/husky#208]
hello,

is it possible to have a postcommit/postpush? For example to tag your repository.

**Comment by alexeyten** [comment]
There is post-commit hook. 
There us no post-push becase git doesn’t provide one.

**Comment by Chabane** [comment]
Ok thanks!

**Comment by adntin** [comment]
I also need post push hook, because the code wants to add the commit message to jira after pushing to gitlab.

**Comment by alexeyten** [comment]
Still no `post-push` hook in git.
Probably what you need is `post-receive/post-update` hooks on server.
Also check [GitLab Jira integration ](https://docs.gitlab.com/ee/user/project/integrations/jira.html).
