### ISSUE TITLE
Pass custom path to the config file

### ISSUE THREAD

**Issue by max-mykhailenko** [typicode/husky#216]
I can't create `package.json` near `.git` folder. We use subfolders for all client side stuff. How I can put path to my `package.json` in config?

**Comment by kasparsd** [comment]
@max-mykhailenko Could you please provide some additional details on your setup? Are all project subfolders tracked in the same git repository? Does each project have its own `package.json` file?

**Comment by max-mykhailenko** [comment]
All folders in the same git repository. Only one subfolder have `package.json` file. 
My current folder structure looks like this
```
root 
- .git
- frontend
-- package.json
-- node_modules
-- etc
- backend
```

**Comment by max-mykhailenko** [comment]
I found another solution without using husky. From git version 2.9 we can set `core.hooksPath` and I move all hooks to the git repository without any problems. So you can close this issue.

**Comment by kasparsd** [comment]
Thanks for sharing @max-mykhailenko!

You could put another `package.json` file in the root just for that `precommit` hook, right? Or is there a reason it wouldn't work?

**Comment by typicode** [comment]
+1 thanks for sharing :)

Would be interested as well in the reasons why it's complicated to have `package.json` in the root just for `precommit` (even though I imagine that it's an organization issue).

**Comment by max-mykhailenko** [comment]
We try to keep `root` without environment specific files which used only in api or frontend. So changing `core.hooksPath` is more relevant for me. Thank you for participating 👍

**Comment by devilbags** [comment]
@max-mykhailenko  We have a similar project setup for our spring-boot + React web app. Can you elaborate as how do you configure your `git hooks`

**Comment by max-mykhailenko** [comment]
@devilbags `core.hooksPath ` new in Git version 2.9, run `git config core.hooksPath ./folder_with_hooks`.

We launch project from docker and just write additional command in docker `yaml` file.

Details https://git-scm.com/docs/githooks , examples https://github.com/git/git/blob/master/t/t1350-config-hooks-path.sh
