### ISSUE TITLE
Support generic script to run on all hooks

### ISSUE THREAD

**Issue by AndersDJohnson** [typicode/husky#220]
Support a generic `package.json` script name, e.g., `husky` or `githook` or `hook`, that runs on all hooks. The current hook name could be passed as an argument to this script. This will enable additional behaviors to be abstracted away and delegated to tools like [`react-scripts`](https://github.com/facebookincubator/create-react-app/tree/master/packages/react-scripts) from [`create-react-app`](https://github.com/facebookincubator/create-react-app), without requiring consumers define each hook individually in their own `package.json`.

This would also solve problems for tooling like https://github.com/kentcdodds/nps/issues/97.

**Comment by typicode** [comment]
Closing as it's an old issue. Thanks for the suggestion :+1:
