### ISSUE TITLE
windows `node is not a recognized command`

### ISSUE THREAD

**Issue by ryanbas21** [typicode/husky#222]
![f268ce5a4e22904b856e78e2971c7623](https://user-images.githubusercontent.com/18267769/34644659-34d25f9e-f300-11e7-8bfe-5683802cc058.png)

I have node installed. Couldn't find anything that really helped me in my searches. I read something about my path, but node works overall. Is there a way I can configure this to work on my windows box and my mac.

**Comment by xXValhallaCoderXx** [comment]
I also have been experiencing this issue at times on different systems

**Comment by typicode** [comment]
How was Node installed? Could you try with v0.15.0-rc.3?

```
npm install husky@next --save-dev
```

**Comment by ryanbas21** [comment]
@typicode node was installed via node installer. 

using husky@next worked. Thanks.

**Comment by typicode** [comment]
Great :) thanks for the update
