### ISSUE TITLE
Remove branch deletion triggers prepush hook

### ISSUE THREAD

**Issue by devlato** [typicode/husky#224]
Hi,

when I try to remove the remote branch with `git push --delete originname branchname`, husky triggers prepush hook. I think makes no sense to run prepush hook if the branch is being deleted anyway. 🤔

**Comment by seungha-kim** [comment]
This is an important issue for me!

**Comment by typicode** [comment]
It's a bit out of scope for husky. Some scripting or simply setting `HUSKY=0` to disable hooks may help.
Thanks for the suggestion :)
