### ISSUE TITLE
npm install 0.15.rc3 ENOENT: no such file or directory husky/lib/upgrader/bin.js

### ISSUE THREAD

**Issue by Falieson** [typicode/husky#229]
**STR**
```
$ rimraf node_modules
$ npm i -D git+https://git@github.com:typicode/husky.git#v0.15.0-rc.3

npm ERR! path ../node_modules/husky/lib/upgrader/bin.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '../node_modules/husky/lib/upgrader/bin.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```

**Comment by typicode** [comment]
Hi @Falieson,

Thanks for the report. Can you try installing the published version on https://npmjs.com instead?

```sh
npm i -D husky@next # or @0.15.0-rc.3
```

When husky is published to npm, `src` files get compiled to `lib`. If you install from GitHub, I don't think this step occurs, that's why `lib` directory can't be found.

**Comment by Falieson** [comment]
@typicode ah, that makes sense. thanks!
The reason I tried to pull it from gitlab is because I was trying `husky@beta` (per some suggestions) but that didn't exist!

**Comment by typicode** [comment]
Oh I see, `@beta` has actually been replaced by `@next` as it's closer to a `rc` than a `beta` now :)
