### ISSUE TITLE
Hooks not found in clean install

### ISSUE THREAD

**Issue by marcinlesek** [typicode/husky#234]
Hello,

after setting up by `vue-cli` `webpack template` I had a problem, that husky didn't get hooks and not working at all. I'm created test app by:
https://github.com/vuejs-templates/webpack

After that I added husky like in readme, so:

`npm install husky@next --save-dev`, gets:
```
> husky@0.15.0-rc.5 postinstall /home/marcinlesek/Projekty/husky-test/node_modules/husky
> node lib/installer/bin install

husky > setting up git hooks
husky > done
+ husky@0.15.0-rc.5
updated 1 package in 9.617s
```
and added to `package.json`:
```
"husky": {
    "hooks": {
      "pre-commit": "npm run test",
      "pre-push": "npm run test"
    }
  }
```
while in `scripts` section we have:
```
"scripts": {
    "dev": "webpack-dev-server --inline --progress --config build/webpack.dev.conf.js",
    "start": "npm run dev",
    "unit": "jest --config test/unit/jest.conf.js --coverage",
    "e2e": "node test/e2e/runner.js",
    "test": "npm run unit && npm run e2e",
    "lint": "eslint --ext .js,.vue src test/unit test/e2e/specs",
    "build": "node build/build.js"
  },
```
and finally want to `git commit` something, console says that:
```
.git/hooks/pre-commit: 10: .git/hooks/pre-commit: [[: not found
.git/hooks/prepare-commit-msg: 10: .git/hooks/prepare-commit-msg: [[: not found
.git/hooks/commit-msg: 10: .git/hooks/commit-msg: [[: not found
.git/hooks/post-commit: 10: .git/hooks/post-commit: [[: not found
[master 2f59f81] test
 1 file changed, 9 insertions(+)
```
Any tips what could be wrong? Thanks in advance.

Best regards,
Marcin

**Comment by Nxt3** [comment]
I'm having the same issue. I had pre-existing hooks setup like so:

```
"scripts": {
    "precommit": "lint-staged",
    "prepush": "yarn run test && yarn run component-test"
}
```

and then I moved them out manually like what is described in the `README`:

```
"husky": {
    "hooks": {
        "pre-commit": "lint-staged",
        "pre-push": "yarn run test && yarn run component-test"
    }
}
```

and they never get triggered.

**Comment by typicode** [comment]
Thanks for the heads up, my bad I've recently switch from `bash` to `sh` and forgot that `[[` isn't supported in `sh`.

I've published another version (`rc.6`), let me know if you still have the issue

**Comment by Nxt3** [comment]
@typicode I tried rc.6 and my hooks still aren't working after upgrading.

**Comment by typicode** [comment]
Hmm what's your OS? What do you have in `.git/hooks/pre-commit`? Do you use `.huskyrc`?

**Comment by marcinlesek** [comment]
For me `RC-6` fixed this bug and now husky works properly. Thanks @typicode :+1: 

@Nxt3 provide more details with your environment, I think it will help @typicode to resolve this issue for your specific case also. ;)

**Comment by typicode** [comment]
I suspect that if you have configured `husky` outside of `package.json` (using `.huskyrc` or `husky.config.js`) it may be ignored. I just discovered this case a few hours ago but I'm preparing a fix.

@marcinlesek great 👍

**Comment by Nxt3** [comment]
@typicode I'm on MacOS 10.12.6. I have the hooks defined in my `package.json`.

```
#!/bin/sh
#husky 0.14.3

command_exists () {
  command -v "$1" >/dev/null 2>&1
}

has_hook_script () {
  [ -f package.json ] && cat package.json | grep -q "\"$1\"[[:space:]]*:"
}

cd "."

# Check if precommit script is defined, skip if not
has_hook_script precommit || exit 0

load_nvm () {
  # If nvm is not loaded, load it
  command_exists nvm || {
    export NVM_DIR=/Users/ganttn/.nvm
    [ -s "$1/nvm.sh" ] && . "$1/nvm.sh"
  }

  # If nvm has been loaded correctly, use project .nvmrc
  command_exists nvm && [ -f .nvmrc ] && nvm use
}

# Add common path where Node can be found
# Brew standard installation path /usr/local/bin
# Node standard installation path /usr/local
export PATH="$PATH:/usr/local/bin:/usr/local"

# nvm path with standard installation
load_nvm /Users/ganttn/.nvm

# nvm path installed with Brew
load_nvm /usr/local/opt/nvm

# Check that npm exists
command_exists npm || {
  echo >&2 "husky > can't find npm in PATH, skipping precommit script in package.json"
  exit 0
}

# Export Git hook params
export GIT_PARAMS="$*"

# Run npm script
echo "husky > npm run -s precommit (node `node -v`)"
echo

npm run -s precommit || {
  echo
  echo "husky > pre-commit hook failed (add --no-verify to bypass)"
  exit 1
}
```

and it's obvious from looking at this what the issue is. The hooks aren't upgraded.

I upgraded like so:

`yarn add husky@next --dev`.

Uninstalling and re-installing isn't an option since this app is used on a large team and requiring everyone to re-install the hooks is going to be difficult to enforce.

**Comment by typicode** [comment]
@marcinlesek that's strange, when you run `yarn add husky@next --dev`, it should upgrade `.git/hooks/pre-commit` from `v0.14.3` to `v0.15` automatically. In any case, you shouldn't need to uninstall and reinstall husky.

It may be related to https://github.com/typicode/husky/issues/227. I've not yet been able to reproduce though. 

And in a normal scenario, when your team run `yarn` it should upgrade their hooks to `v0.15` without any particular action from them.

The only thing can be if they just run `git pull && yarn start`, they would miss the upgrade.

That said, maybe until https://github.com/typicode/husky/issues/227 is solved, it's better to stay with `v0.14.3`

**Comment by Nxt3** [comment]
@typicode (You're tagging the wrong person in your posts)

I think I'll wait for #227 to be resolved then. Thank you.

**Comment by typicode** [comment]
ahah thanks (edited) :)
What's your version of yarn?

**Comment by Nxt3** [comment]
v1.3.2.

**Comment by Zenser** [comment]
`node ./node_modules/husky/lib/installer/bin.js install` worked

**Comment by sonsor** [comment]
well i get this error 
Husky requires Git >= 2.13.0, please upgrade Git
husky > Failed to uninstall

after updating to git version 2.16.6
and"husky": "^4.2.3",
its works fine now

**Comment by chimurai** [comment]
Upgrading to 4.3.8 fixed it for me, if you're still on version 4.x

https://github.com/typicode/husky/issues/727
