### ISSUE TITLE
A weird problem about "node version manager: n" and husky

### ISSUE THREAD

**Issue by cos2004** [typicode/husky#235]
I have a precommit hook, when I run "git commit", the terminal output "husky > npm run -s precommit (node v0.12.13)", buy my node version is 8.9.3 , maybe 0.12.13 is a very old version I installed long time ago. Why is it so ? 

=======
os: mac 10.13.2
n: 2.1.7
node: 8.9.3
husky: 0.14.3

**Comment by typicode** [comment]
Hi @yuli,

That's strange. You don't have an old `nvm` installed? Husky may load it if it finds a `~/.nvm` or `/usr/local/opt/nvm` directory, if not it should just use the `node` version that you have in your terminal.

**Comment by cos2004** [comment]
@typicode  Thanks for reminding that I use "nvm" to manage node version long ago, but now I use "n"  instead of "nvm". The solution is to uninstall "nvm": rm -rf ~/.nvm
