### ISSUE TITLE
npm run lint does not stop the commit

### ISSUE THREAD

**Issue by ix-xerri** [typicode/husky#236]
Currently trying to implement a precommit hook to an Ionic project using `"husky": "^0.15.0-rc.6"`. If I run `npm test` on precommit, the commit stop. It did not stop when running `npm run lint` even though warning are generated. To make it stop, I had to edit the pre-commit hook to:

```
#!/bin/sh
# husky
# v0.15.0-rc.6 darwin

export GIT_PARAMS="$*"

hookname=`basename "$0"`

if [ -f package.json ] && cat package.json | grep -q "\"$hookname\"[[:space:]]*:"; then
  node_modules/run-node/run-node ./node_modules/husky/lib/runner/bin $hookname
  exit 1?
fi 
```

Notice that I changed the exit code from `exit $?` to `exit 1?`

**Comment by ix-xerri** [comment]
Tried it on `"husky": "^0.15.0-rc.7"` and adding `"severity": "error"` but the commit still happened even if you have tslint warnings.

**Comment by ecdeveloper** [comment]
+1

**Comment by ix-xerri** [comment]
Has to edit the lint script in package.json to result in `"ionic-app-scripts lint --bailOnLintError true"`

**Comment by diegodesouza** [comment]
This is happening to me also.

**Comment by typicode** [comment]
Cleaning old issues. Feel free to create a new one if needed.
Also FWIW husky's pre-commit works as expected during CI tests (i.e. aborting commit if scripts exit with non-zero code)  so it may be something else.

@diegodesouza I would check package.json to see if it's husky or pre-commit that is installed.
