### ISSUE TITLE
git add after webpack build

### ISSUE THREAD

**Issue by microcipcip** [typicode/husky#238]
Is there a way to `run build && run test` and then **add to the current commit the dist files** generated by webpack?
 For example with `git add -A ./ && git commit --amend --no-edit`? I can't manage to do this...

**Comment by tameroski** [comment]
Did you manage to do this (using husky or not) ?

**Comment by microcipcip** [comment]
No I couldn't, now I used `Lerna` with `simple-git` instead, not ideal but worked for my project.
