### ISSUE TITLE
Slow to execute

### ISSUE THREAD

**Issue by matthewmueller** [typicode/husky#24]
Really digging this repo, but there's a noticeable delay running through the hooks, even ones that you haven't specified (ex. git commit when you only have a prepush). Do you think this is something that could be sped up?

**Comment by typicode** [comment]
Hey,

Yes, currently it's not very optimal.
It creates all hooks, then each hook check if there's a corresponding script in `package.json` by running `npm run` each time. Must be the reason why it's slow.

I think of refactoring the project to create hooks based on scripts in `package.json` instead. This way, if there's no `precommit` there won't be a `pre-commit` hook.

The counterpart will be that if you add a hook to `package.json`, you'll have to reinstall `husky` to create the new hook.

**Comment by matthewmueller** [comment]
Personally I like just installing the hooks once. I'm not sure how many hooks are being run on a commit, but this `pre-commit` library doesn't really have a noticeable delay: https://github.com/iliakan/javascript-precommit/blob/master/bin/pre-commit.

Might be that `npm run` is slow.

**Comment by typicode** [comment]
I found the reason why it's slow. Basically with `v0.9.x` I've added all git hooks.

Husky's `pre-commit` alone is not that slow. But with a `git commit`, `prepare-commit-msg`, `commit-msg`, `post-commit` are now run also.

So it's like running `npm run` 4 times on every commit.
As a temporary solution, you can use `v0.8.x` or manually remove unused `.git/hooks`.

**Comment by typicode** [comment]
It should be much better now in `v0.9.2`.
I've switched to shell commands. So now instead of running `npm run`, it uses `cat` which is way faster.

**Comment by matthewmueller** [comment]
Awesomeeee. Thanks a lot!
