### ISSUE TITLE
I have error in VS Code

### ISSUE THREAD

**Issue by sh7dm** [typicode/husky#240]

**Comment by sh7dm** [comment]
This is my error:

> snyk test

"snyk" �� ���� ����७��� ��� ���譥�
��������, �ᯮ��塞�� �ணࠬ��� ��� ������ 䠩���.
npm ERR! Test failed.  See above for more details.
husky > pre-commit hook failed (add --no-verify to bypass)

This is my package.json:

...
"scripts": {
    "dev": "backpack",
    "build": "backpack build",
    "test": "snyk test"
  },
...

  "husky": {
    "hooks": {
      "pre-commit": "npm test"
    }
  },
...

**Comment by typicode** [comment]
Hi @sh7dm, I'd say it works as expected as the test seems to fail `npm ERR! Test failed` and husky displays the correct message and makes the commit fail.
