### ISSUE TITLE
Husky fails when .git/hooks directory is missing

### ISSUE THREAD

**Issue by jnv** [typicode/husky#242]
This was already reported in https://github.com/typicode/husky/issues/195#issuecomment-349750514. I am opening this issue since one of our developers ran into the same problem. In some cases (user action, modified repository template) folder `.git/hooks` may be missing, which causes hooks installation to fail with ENOENT error. Steps to reproduce:

```
# in empty folder:
$ git init
$ npm init -y
$ rm -rf .git/hooks
$ npm install husky@next --save-dev

> husky@0.15.0-rc.8 preuninstall .../node_modules/husky
> node lib/installer/bin uninstall

husky > uninstalling git hooks
husky > done

> husky@0.15.0-rc.8 install .../node_modules/husky
> node lib/installer/bin install

husky > setting up git hooks
husky > failed to install
ENOENT: no such file or directory, open '..../.git/hooks/applypatch-msg'
npm notice save husky is being moved from dependencies to devDependencies

+ husky@0.15.0-rc.8
updated 1 package in 3.83s
```

While this error is harmless, some devs may incorrectly assume the installation is broken. Husky should either create hooks directory, or skip hooks install with a warning message.

**Comment by typicode** [comment]
Hi @jnv,

Just published a new version (`v0.15.0-rc.9`) that doesn't fail and displays a warning message. Thanks for the suggestion :)

**Comment by versedi** [comment]
@typicode is this bug back? I'm on recent version and it happens again but for the directory inside node_modules:

```
npm install husky --save-dev

> husky@2.5.0 preuninstall /var/www/kfi/tantis/node_modules/husky
> node husky uninstall

husky > Uninstalling git hooks
husky > Done

> husky@2.5.0 install /var/www/kfi/tantis/node_modules/husky
> node husky install

husky > Setting up git hooks
ENOENT: no such file or directory, mkdir 'node_modules/husky/.git/hooks'
husky > Failed to install
```

**Comment by amenella** [comment]
Hi,

It seems the issue is appearing with husky@2.5.0 (released yesterday) but not with husky@2.4.1

Hope this helps,

@versedi @typicode

**Comment by ej14433** [comment]
As @amenella suggests, this is an issue with husky@2,5 and up. I resolve this with:

`npm install husky@2.4 --save-dev`

**Comment by jnv** [comment]
Sounds like a regression. Looking at recent commits, maybe there's something fishy in commit de75acb0a27bdab1ab3013cf0adda34b172cde2c?

**Comment by typicode** [comment]
Yes, `husky@2.5+` requires now a more recent version of Git. I've changed `latest` tag back to `husky@2.4` for the moment.

**Comment by amenella** [comment]
@typicode it seems like a breaking change, you should version to next major (v3.0.0)

**Comment by typicode** [comment]
Yes, it's planned :+1:

**Comment by typicode** [comment]
Next major available here https://github.com/typicode/husky/issues/520

**Comment by john-aws** [comment]
These symptoms also happen if you install husky on a machine that does not have git pre-installed. While this may be uncommon, it's certainly possible, especially on a VM or cloud instance. It would be good for the installation process to fail early with a clearer message than:

```
husky > Setting up git hooks
spawnSync git ENOENT
husky > Failed to install
```

**Comment by nicothin** [comment]
"husky": "^3.1.0",
osx

```
> node husky install

husky > Setting up git hooks
ENOENT: no such file or directory, mkdir '.git/hooks'
husky > Failed to install
```

```
ls .git/hooks/
applypatch-msg.sample
commit-msg.sample
post-update.sample
pre-applypatch.sample
pre-commit.sample
pre-push.sample
pre-rebase.sample
prepare-commit-msg.sample
update.sample
```

**Comment by ashishtilara** [comment]
+1
