### ISSUE TITLE
Problems with path when running scripts from hook

### ISSUE THREAD

**Issue by filipekiss** [typicode/husky#246]
Hey @typicode, first of all thank you for Husky! It's a great tool!

I'm having trouble with something and I've tried a few different solutions but wasn't able to pinpoint the culprit just yet. I've managed to work around the problem but the solution is far from optimal.

Here's the deal: I've added a few hooks in a legacy code base.

My current tree is as follows (reduced for brevity sake):

```
package.json
node_modules
new-project
├── node_modules
├── package.json
├── scripts
├── src
└── yarn.lock
```

Everything for the new project resides inside the `new-project` folder. My hooks are located in `new-project/scripts/tasks/precommit.js` for example.

Running `yarn run precommit` or `npm run -s precommit` works fine. Here's the output I want:

```
→ y precommit
yarn run v1.3.2
$ babel-node scripts/tasks/precommit.js
/Users/filipekiss/code/project/legacy
```

When I run the git hook directly from the root (running from the shell), it also works as expected:

```
→ .git/hooks/pre-commit
husky > npm run -s precommit (node v9.3.0)

/Users/filipekiss/code/project/legacy
```

But when the hook is ran when commiting, something odd happens:

```
→ gci -m ''
husky > npm run -s precommit (node v9.3.0)

/Users/filipekiss/code/project/legacy/new-project/node_modules/execa/index.js:347
                throw err;
                ^

Error: Command failed: git rev-parse --show-toplevel
fatal: Not a git repository: '.git'
```
(I'm commiting with an empty message so the hook can run but the commit can fail).

I tought [execa] was the problem, but using node's `child_proccess` yields the same result: `fatal: Not a git Repo`.

The command I'm using to get the git repo top level is `git rev-parse --show-toplevel`

I've hardcoded the path for the git root, but that's far from ideal. Do you have any idea why this happens?

Thank you for your time!

[execa]: https://github.com/sindresorhus/execa

**Comment by typicode** [comment]
Hi @filipekiss,

There seem to be 2 versions of husky running, `v0.14` and `v0.15` (which uses execa).

I would try using only [`v0.15`](https://github.com/typicode/husky) and have hooks defined just in the root `package.json`, see:
https://github.com/typicode/husky/blob/dev/docs.md#multi-package-repository-monorepo

Installing husky in multiple sub `package.json` creates conflicts as each will overwrite the previous Husky install.

**Comment by filipekiss** [comment]
Hey @typicode, I looked around my `package.json` and found just the `v0.14.3` listed as a dependency. I'll update it to `v.015` and see if that fixes my problem (the `execa` I mentioned in my post is actually the one I use to run a few tasks inside the hooks)

**Comment by filipekiss** [comment]
I guess it has something to do on how execa is run inside the hook.

Using `git rev-parse --git-dir` worked as expected, so I'm going with that for now, but I'll keep trying to figure out why this happens and I'll let you know if I ever find the culprit!

Thank you!
