### ISSUE TITLE
cd path incorrect on Windows systems 

### ISSUE THREAD

**Issue by 27percent** [typicode/husky#25]
When installing on Windows systems, husky creates hooks with cd paths as follows:
```bash
#!/bin/sh
# husky
cd directory\subdirectory\package_directory
[ -f package.json ] && cat package.json | grep -q '"precommit"\s*:'
[ $? -ne 0 ] && exit 0
npm run precommit --silent
if [ $? -ne 0 ]; then
  echo
  echo "husky - pre-commit hook failed (add --no-verify to bypass)"
  echo
  exit 1
fi
```

where the cd paths should be

```bash
#!/bin/sh
# husky
cd directory/subdirectory/package_directory
[ -f package.json ] && cat package.json | grep -q '"precommit"\s*:'
[ $? -ne 0 ] && exit 0
npm run precommit --silent
if [ $? -ne 0 ]; then
  echo
  echo "husky - pre-commit hook failed (add --no-verify to bypass)"
  echo
  exit 1
fi
```

Using back-slashes in the file path escapes characters instead of separating them with a slash, this stops husky from finding the package.json file which, in turn, stops husky working. I'm guessing this is a Windows vs. UNIX issue, the cd path needs to be sanitized and back-slashes replaced with forward-slashes on Windows

**Comment by typicode** [comment]
Good point, thanks for raising this issue :+1: I'll take care of it next week (don't have access to a computer right now)

**Comment by typicode** [comment]
Hi @27percent,

Thank you for your patience, it should be good now (`v0.9.3`).
Path will be normalized on Windows.
