### ISSUE TITLE
Can't run hooks

### ISSUE THREAD

**Issue by romariolopezc** [typicode/husky#252]
`.git/hooks/pre-commit: line 6: node_modules/run-node/run-node: No such file or directory`

I used `yarn` and `npm install`

I have node 8.5

I'm using the stable version

**Comment by typicode** [comment]
Hi @romariolopezc,

Hmm, that's strange, are your `package.json` and `.git` directory at the same level? Is `run-node` installed in `node_modules`? Is there a `node_modules/.bin/run-node` file? Are you using husky `v0.15.0-rc.8`?

If you try `rm -rf node_modules && npm install (or yarn)`, is itbetter?

**Comment by romariolopezc** [comment]
Yes, they are in the same level. And No there is no `run-node` in `node_modules` nor `node_modules/.bin`.

And I'm using `"husky": "^0.14.3",`

**Comment by typicode** [comment]
It seems `v0.15` hooks were installed at some point, as `v0.15` relies on `run-node` but `v0.14` doesn't (you can see the version in `.git/hooks/pre-commit).

I would suggest upgrading to `v0.15` if possible or delete existing hooks and reinstall them with `v0.14`.

**Comment by romariolopezc** [comment]
Did `rm -rf .git/hooks` then yarn. Everything working as expected!
