### ISSUE TITLE
[0.15.0-rc.12] Can't find .git/hooks directory.

### ISSUE THREAD

**Issue by ozum** [typicode/husky#255]
Hi,

Husky: `0.15.0-rc.12`
MacOS: `10.13.3`
Node: `9.8.0` (Standard installation)
NPM: `5.6.0`

Some freshly cloned repos are missing `.git/hooks` directory ([see here](https://stackoverflow.com/questions/33680880/why-is-git-hooks-sometimes-missing-in-cloned-repos)).

As a result when I clone a repo and `npm install` it, husky warns me:

`Can't find .git/hooks directory. You can try to fix this error by creating it manually. Skipping Git hooks installation.`

Is there a way to husky create it instead of warn? I think, it may be a better solution to create `.git/hooks` directory when directory cannot be found, if there isn't any reason to do otherwise.

**Comment by typicode** [comment]
Hi @ozum,

Thanks for the details. Personally, I've not experienced cloning a repo and not getting `.git/hooks`. Which Git client are you using?

My main concern with husky creating `hooks` dir is about rights, as sometimes people use `sudo npm install`. Maybe there wouldn't be any issue, and I'm too cautious here, but to avoid any problem, husky just outputs a warning message.

**Comment by ozum** [comment]
I didn't realize it until I encountered a broken code published. Part of my release workflow, I was assuming my tests are triggered via husky.

I'm using both git command line and GUI (source tree). To test this, I created an empty repo, assured it have `.git/hooks`,  then pushed it. Later I cloned it elsewhere and it does not have `.git/hooks`.

People may forget manually creating `.git/hooks` after cloning. I also forgot several times. Manually creating `.git/hooks` and setting husky later up is tiresome every time.

Maybe workflow below would be a good solution:
1. Look if `.git` presents.
1. Look if `.git/hooks` presents.
1. Look if `sudo` is used. ([is-root](https://www.npmjs.com/package/is-root) npm package can be used for this.)
1. `-e '.git' && ! -e '.git/hooks' && ! isRoot` -> create `.git/hooks` and emit info about it.
1. `-e '.git' && ! -e '.git/hooks' && isRoot` -> emit warning about lack of `.git/hooks` and `sudo`.

**Comment by travi** [comment]
i've missed this on several repos where i've started with one of the RCs. i usually realize fairly quickly that the hook scripts aren't running, but it surprises me every time that i need to manually add `.git/hooks/`

**Comment by travi** [comment]
i finally got a chance to investigate this. the hooks directory is normally created [as part of `git init`](https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks#_installing_a_hook). 

with a little digging, i found that the problem in my case was that my git config defined a template directory that didnt exist (i guess i hadn't cleaned that up from a previous machine). removing that config allowed `git init` to define `.git/hooks` as expected.

**Comment by ozum** [comment]
`git init` creates `.git/hooks` it. However problem in this case is `.git/hooks` is not created during clone.

**Comment by travi** [comment]
ah. i don't think i've noticed that issue, but may have overlooked since i was also seeing it as part of `git init`. i'll keep an eye out for it during clone, but at least part of what i was seeing is now resolved.

**Comment by ozum** [comment]
@travi, please note that, hooks are local and it is not stored in repo by default. So, when you clone a repo first time into an empty directory, `.git/hooks` is not created. ([See Here](https://stackoverflow.com/questions/33680880/why-is-git-hooks-sometimes-missing-in-cloned-repos))

**Comment by travi** [comment]
i am aware that the hooks are not versioned. thats a big part of why i use `husky` in the first place. however, `git clone` [should be doing a `git init` ](https://stackoverflow.com/questions/22724921/do-i-need-to-do-git-init-before-doing-git-clone-on-a-project#answer-22724997) as part of the clone, which would add the directory.

**Comment by bbakhrom** [comment]
faced same issue. On mac everything worked fine, however once another dev with windows machine pulled latest commits with husky and git hooks enabled he got this error.

**Comment by typicode** [comment]
Closing, in `v1.1.0+` `.git/hooks` gets automatically created.

Thanks for the feedbacks :)
