### ISSUE TITLE
Feature request: enabled option, with opt in/out

### ISSUE THREAD

**Issue by gerges-zz** [typicode/husky#258]
We've got quite a large dev team that's split on having/not having git hooks. I noticed the opt out env variable on install, but it's a large ask for someone to run that every time they install.

It would be awesome to have a model where we can still use `husky`, but require devs to opt-in or out via a git-ignored file, so it can be scoped to a given repo (imagine `echo true > .husky-enabled`).

In this case it may look like

```
//package.json
  "husky": {
    "enabled": "false",
    "hooks": {
      "pre-commit": "cd subproject && npm test"
    }
  }

//.husky-enabled
true
```

Let me know your thoughts, if there's a better way to do this, or if this doesn't line up with the goals of the project.

**Comment by typicode** [comment]
Hi @gerges 

Thanks for the feedback. That could make sense also for GUI clients, but no plans for this for the moment.

That said, currently you could take advantage of the fact that husky doesn't create `hooks` directory and if there's no `hooks` directory it skips installations.

So `rm -rf .git/hooks` or `mv .git/hooks .git/hooks-backup` would be equivalent to disabling husky locally (it's a workaround though, so not sure if your team would be satisfied with this).

**Comment by LeZuse** [comment]
Same here. We would like a way for our devs to opt-in rather than opt-out by deleting the `.git/hooks` dir.

We are thinking of going around this by creating a custom script that will check for git config:
```
if [[ `git config --get husky.hooks` == "true" ]]; then echo lint; else echo skip; fi
````

One caveat though: be careful about passing the correct exit code to prevent cancelling legitimate commits.

**Comment by typicode** [comment]
Opt-in/opt-out should now be possible with husky 5 as it doesn't automatically install Git hooks anymore.

Teams can decide to have a `postinstall` script to keep automatic install.
Or, alternatively `npx --no-install husky install` can be run only by devs who wish to install hooks.

Thanks for the feedbacks.
