### ISSUE TITLE
Allow relative path in husky generated script using package.json config param

### ISSUE THREAD

**Issue by jforjava1981** [typicode/husky#261]
We have a project structure where we host multiple angularjs projects modules with their own package.json files. All these sub projects are part of a maven module project. We cannot have package.json in main project and cannot have npm install modules in that folder.
Also every angular subproject will need to run husky precommit hook for it's own files. 
However when we install npm modules in each project one overwrites other script depending upon which one is run last and relative path refers to project where npm install was run last time.
Can't we have this relative path dynamic and picked up from package.json file configuration? So that at run time depending upon which project it is run on we can override it with our own path rather than hard coding it at build time to a project.

**Comment by typicode** [comment]
Hi @jforjava1981,

For monorepos, if possible, I would suggest having a root package.json that would act as the source of truth for husky and use lerna to handle sub projects.

https://github.com/typicode/husky/blob/dev/docs.md#multi-package-repository-monorepo

There's no plan to support husky dependency defined in multiple `package.json` file as I feel it would be complicated to get it right.

That said, with `v1.0.0-rc.3`, it's possible to have husky defined in a package.json that isn't at the same level as `.git` directory. So something like that could be possible with `v1.0.0-rc.3` :)

```sh
maven-project/
  front/
    package.json # add husky here
    angular-project-1/
      package.json
    angular-project-2/
      package.json
```
