### ISSUE TITLE
Husky verion (0.15.0-rc.13) doesn't work properly on Windows.

### ISSUE THREAD

**Issue by dimitardanailov** [typicode/husky#262]
Good Morning Guys, 

I've been working on Windows and git commit message doesn't work properly. 

My package.json
```
{
  "devDependencies": {
    "@commitlint/cli": "^6.1.3",
    "@commitlint/config-conventional": "^6.1.3",
    "husky": "^0.15.0-rc.13"
  },
  "husky": {
    "hooks": {
      "commit-msg": "./node_modules/.bin/commitlint -e $GIT_PARAMS"
    }
  }
}
```

Screenshot:
![husky](https://user-images.githubusercontent.com/2182018/38191183-5bd60f42-3670-11e8-9402-9850b390ab8b.PNG)

Node version is: 8.9.1

Information about my Windows:
![windows](https://user-images.githubusercontent.com/2182018/38191298-d9a9debc-3670-11e8-876a-a02799c555a6.PNG)

**Comment by Pokom** [comment]
While I'm not a contributor to Husky, this doesn't appear to be an issue with husky, but an issue inherent with running npm scripts on Windows. My recommendation(and verified on my end) is to alter your commit-msg script to:

```json
 "husky": {
    "hooks": {
      "commit-msg": "commitlint -e $GIT_PARAMS"
    }
  },
```

as long as commitlint is installed locally, it'll run with no problem.

**Comment by dimitardanailov** [comment]
@Pokom 

I prefer to use local packages for my scripts has a lot of advantages.

**Comment by typicode** [comment]
thanks @Pokom 

@dimitardanailov agree with you. In this case, if you just put `"commit-msg": "commitlint -e $GIT_PARAMS"` it will run the local package `./node_modules/.bin/commitlint` and not the global one. It's similar to npm behavior wich favors locally installed packages rather than global ones.

**Comment by XhmikosR** [comment]
@typicode: I'm having trouble on Windows too using v1.0.0-rc.13 win32, but not the exact error. I'm just using `npm test` for pre-commit and pre-push.

Precommit works but push fails for me with a `fatal: The remote end hung up unexpectedly` error.
