### ISSUE TITLE
Symlinked `husky` -- e.g. `npm link husky` -- does not run hooks

### ISSUE THREAD

**Issue by al-the-x** [typicode/husky#264]
I use `husky` to manage my git-hooks, but other developers on my team do not and prefer other methods of invoking and sharing hook scripts. I therefore install `husky` globally and use `npm link` to include it in projects. 

When I do so, the `install.js` script is not run, so I run it manually with `node node_modules/husky/bin/install.js`. It would be nice if `husky` had a `postlink` hook that would do the same thing as the `postinstall` hook. I can submit a PR for this.

The installed hook scripts contain a `cd` command that changes the working directory to the canonical `husky` installation folder, based on an assumption that `husky` is installed in the project-local `node_modules` that is adjacent to `package.json`. This prevents the scripts from executing and fails silently on the test `[ -f package.json ]`. I have commented out the `cd` line from all the scripts and everything works for me.

Is there a reason for this `cd` line, since none of the rest of the code seems to rely on being in the `husky` path...? The script even adjusts the `$PATH` to potentially include `node`... shouldn't that be sufficient? Is there a use case that I'm missing? Can I submit a PR to correct?

**Comment by harsh-tamr** [comment]
Do it!

**Comment by al-the-x** [comment]
The code has changed significant since I opened this issue and may have rendered this point moot. Closing.
