### ISSUE TITLE
error on 0.15.0-rc.13

### ISSUE THREAD

**Issue by sandangel** [typicode/husky#267]
```sh
Error: Cannot find any-observable implementation nor global.Observable. You must install polyfill or call require("any-observable/register") with your preferred implementation, e.g. require("any-observable/register")('rxjs') on application load prior to any require("any-observable").
```

package.json

```json
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged",
      "commit-msg": "commitlint -e $GIT_PARAMS"
    }
  }
```

node 8.11.1, yarn 1.5.1

**Comment by typicode** [comment]
Hi @sandangel,

Thanks for the report and help testing :) Except if I'm missing something, husky doesn't have a dependency to `any-observable` in [`package-lock.json`](https://github.com/typicode/husky/blob/dev/package-lock.json). Not sure if it relates to husky then.

Do you know if it's the pre-commit or commit-msg that fails?

Also do you have this error with husky v0.14 (you would need to move scripts from `husky.hooks` to `scripts.precommit` and `scripts.commitmsg` for it to work with v0.14)?

**Comment by sandangel** [comment]
@typicode HI, thanks for reply. I have this error when using husky 0.14

```json
{
 "scripts": {
    "precommit": "lint-staged",
    "commitmsg": "commitlint -e $GIT_PARAMS"
 }
}
```

```sh
git commit -m "chore: test husky hooks"
.git/hooks/pre-commit: line 6: node_modules/run-node/run-node: No such file or directory
```

Both throw error in precommit hook

**Comment by typicode** [comment]
Can you try manually removing `.git/hooks/pre-commit`, it seems to be still on `v0.15` and re-run `npm install husky --save-dev`?

**Comment by sandangel** [comment]
hi @typicode 
I have debug the process, it turns out that it's a lint-staged issue. 

```sh
npx lint-staged
Cannot find any-observable implementation nor global.Observable. You must install polyfill or call require("any-observable/register") with your preferred implementation, e.g. require("any-observable/register")('rxjs') on application load prior to any require("any-observable").
```

Thank you for your useful information
