### ISSUE TITLE
Husky 0.14.3 ignoring HUSKY_SKIP_INSTALL paramter

### ISSUE THREAD

**Issue by zastavnitskiy** [typicode/husky#269]
Hello, everyone!

I found an issue related to HUSKY_SKIP_INSTALL parameter – seems like the code that is checking for this is deleted at some point – some prepublishing optimisation scripts misbehaving?

### How to reproduce:
1. Install husky.
2. Remove node_modules
3. run `HUSKY_SKIP_INSTALL=true yarn install`
4. check .git/hooks – will have all husky hooks, while expected not to.

More to that, there are no mentions of `HUSKY_SKIP_INSTALL` variable in the source code of the module installed from npm:

```javascript
'use strict'

// Run when package is installed
const path = require('path')
const isCI = require('is-ci')
const installFrom = require('../src/install')

console.log('husky')

if (isCI && !process.env.HUSKY_IGNORE_CI) {
  console.log('CI detected, skipping Git hooks installation')
  process.exit(0)
}

console.log('setting up Git hooks')

const huskyDir = path.join(__dirname, '..')
installFrom(huskyDir)

```

**Comment by typicode** [comment]
Hello @zastavnitskiy!

`HUSKY_SKIP_INSTALL` feature has been added in `v0.15` https://github.com/typicode/husky/blob/dev/CHANGELOG.md#0150-rc1

So you may want to upgradre husky to `v1.0.0-rc.1` (it's behind `husky@next` tag) or trick `v0.14.3` to believe that it's in a CI :)

**Comment by zastavnitskiy** [comment]
Indeed, got confused by reading documentation on github :) I see that there is even a warning about it!
