### ISSUE TITLE
Ignore unstaged changes (precommit)

### ISSUE THREAD

**Issue by rodneyrehm** [typicode/husky#27]
I'm not submitting PRs for this because I wanted to talk about things first.

When running `git commit ./some-path` I don't necessarily commit all the changes in my working copy - but the scripts invoked on pre-commit don't know that. They will run on the current state my FS sees, not what I'm actually committing.

The common workaround is to save a diff, reset to head, run the tests and then re-apply the diff as can be seen [here](https://github.com/tarmolov/git-hooks-js/blob/master/examples/pre-commit/test). Maybe switching between the two behaviors could be made "configurable", simply by running "npm run precommit" on everything and "npm run precommit:staged" on what is really about to be committed?

While already meddling with this, how about providing a list of actually changed resources, so that a linter wouldn't have to check the entire source directory, if only one file got changed. [extracting](http://stackoverflow.com/a/2413151/515124) that info seems easy - but I have no idea how best to pipe it into a script.

I'm not sure if any of this applies to any hook but pre-commit (possibly post-commit).

**Comment by piranna** [comment]
> The common workaround is to save a diff, reset to head, run the tests and then re-apply the diff as can be seen here. Maybe switching between the two behaviors could be made "configurable", simply by running "npm run precommit" on everything and "npm run precommit:staged" on what is really about to be committed?

This can be easily done with `git stash` and `git stash pop`.

**Comment by glasserc** [comment]
See also https://github.com/okonet/lint-staged/issues/62 which is working on this issue.

**Comment by janek** [comment]
I've been running into this problem quite a bit - the stashing workaround works, but I think it would be very helpful if there was a fix

**Comment by dlsso** [comment]
@piranna Do you have an example of doing this with `git stash` and `git stash pop`?

We need to make sure we don't `pop` unless a stash is created, but it seems the post-commit does not have access to variables set in the pre-commit file, and I'm wondering if there's a cleaner way than making a temporary file.
