### ISSUE TITLE
Empty error message?

### ISSUE THREAD

**Issue by FezVrasta** [typicode/husky#273]
I'm trying to configure Husky and CommitLint to work together. This is my config:

```
"scripts": {
  "commitmsg": "commitlint -e $GIT_PARAMS"
},
"commitlint": {
  "extends": [
    "@commitlint/config-conventional",
    "@commitlint/config-lerna-scopes"
  ]
}
```

The problem is that whenever I commit something where I expect commitlint to throw an error, I just get:

```
husky > npm run -s commitmsg (node v9.11.1)


husky > commit-msg hook failed (add --no-verify to bypass)
```

If I run `commitlint` from command line it returns the correct error message so I think the problem is in Husky, but what's wrong with it?

I'm on Husky 0.14.3

**edit**:

I added an `echo $GIT_PARAMS` in the git hook file and it just prints `.git/COMMIT_EDITMSG`, it doesn't seem right, right?

**Comment by FezVrasta** [comment]
Sorry, found the problem. I had an invalid `version` in my package.json and so npm was failing silently when it ran the script.

**Comment by dawidnawrot** [comment]
@FezVrasta I have similar problem. Invalid version of what?

**Comment by FezVrasta** [comment]
I don't remember correctly but it was probably something like a `"version": "xxx"` (some invalid semver version)

```json
{
  "version": "invalid"
  [...]
}
```
