### ISSUE TITLE
how to let server hook work.

### ISSUE THREAD

**Issue by MiYogurt** [typicode/husky#276]
in the server i use `git init --bare` init git repo.

client configuration
![image](https://user-images.githubusercontent.com/10082395/39174894-77428554-47db-11e8-98c2-d4c5d8f43284.png)

how to let they work，i did't see echo hello run。

if i writing some bash in server computer repo hooks/post-recevice ，it working , husky not support server hooks？

**Comment by typicode** [comment]
Hi @MiYogurt,

Good question and sorry for the delay. Husky only focuses on client hooks, not even sure how to support server hooks.
