### ISSUE TITLE
Issue with git checkout in worktree

### ISSUE THREAD

**Issue by NicolasPelletier** [typicode/husky#279]
Good morning,

I have husky 0.15.0-rc.8.

The following sequence of commands fail when run in a repo
```
$ git worktree add gh-pages origin/gh-pages
Preparing gh-pages (identifier gh-pages)
HEAD is now at 3f215d8 <Some comment>

$ cd gh-pages/
$ git checkout -b nicolas
Switched to a new branch 'nicolas'
/Users/pelletn/src/<my main repo folder>/.git/hooks/post-checkout: line 6: node_modules/run-node/run-node: No such file or directory
$
```

This sequence work with version 0.14.3.

I tried adding `--no-verify`, but git does not like it:
```
$ git checkout --no-verify -b nicolas2
error: unknown option `no-verify'
```

**Comment by typicode** [comment]
Good morning, thanks for the heads up. It's just that worktree support hasn't been reintroduced in `@next`, but it will be :)

I'll update this issue, when it will be available again.

**Comment by NicolasPelletier** [comment]
Thanks, I just wanted to notify you against a regression in case you were not aware.

Thanks for the good work you do here. This is a very nice library.

**Comment by typicode** [comment]
It's back in ` v1.0.0-rc.4` ;)
