### ISSUE TITLE
Support .sh files as hooks

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typicode/husky#281]
I used to have something like this in `package.json`:

```json
  "husky": {
    "hooks": {
      "post-merge": "./hooks/post-merge"
    }
  }
```

where `./hooks/post-merge` was a `#!/bin/sh`-prefixed file.

At some point in time, this was found to not be working (IIRC it used to?), so now I have something like:

```json
  "husky": {
    "hooks": {
      "post-merge": "node -e \"process.exit(!require('is-windows')())\" && powershell ./hooks/post-merge.ps1 || sh ./hooks/post-merge.sh"
    }
  }
```

where the `.ps1` and `.sh` files do roughly the same thing. That duplication is suboptimal 😌.

Husky's `README.md` only shows `npm test` and `docs.md` only shows `lerna run test`. Can Husky be changed to also allow running these sh scripts?

It should be trivial on most non-Windows systems. On Windows, if Git is installed then in theory the Git shell should exist and be able to run them: either with Git for Windows' Git Bash or (maybe?) Git natively? I'm not familiar.

**Comment by typicode** [comment]
Hi @JoshuaKGoldberg,

I think it's possible already. I've tried this on Windows:

```sh
# hello.sh
echo hello
```

```json
"husky": {
  "hooks": {
    "pre-commit": "sh hello.sh"
  }
}
```

```sh
$ git commit -m test
husky > pre-commit (node v10.6.0)
hello
```

**Comment by JoshuaKGoldberg** [comment]
@typicode `sh` doesn't natively exist on Windows, so either you're using something like Cmder that adds an equivalent of `sh` or your `hello.sh` is using commands that _happen_ to be similar in both systems. `echo hello`, from your code snippet, does.
