### ISSUE TITLE
Does v1.0 still use nvm when `.nvmrc` exists?

### ISSUE THREAD

**Issue by forabi** [typicode/husky#282]
When I commit to a git repo via VS Code, pre-commit hooks use the system-wide version of Node.js. Looks like husky no longer uses nvm?

**Comment by forabi** [comment]
> Instead v1.0.0 uses run-node, but it can be configured to use a particular Node version:
sindresorhus/run-node#customizable-cache-path-and-error-message

I'm not sure that's what `$RUN_NODE_CACHE_PATH` does. I just tried this:

```
❯ export RUN_NODE_CACHE_PATH=/home/f/.nvm/versions/node/v8.10.0/bin

❯ npx run-node
npx: installed 1 in 4.896s
> process.version
'v9.11.1'
> .exit

❯ yarn global add run-node
❯ run-node
> process.version
'v9.11.1'
> 

```

**Comment by forabi** [comment]
@macklinu Neat! But I wonder if this has any unintended consequences?

**Comment by macklinu** [comment]
In my case, it ensures that `npm start` starts my Node.js server with the node version listed in `devDependencies.node`, but I'm not sure how this would work with executing installed modules (via `npm install`) in a husky pre-commit hook, for example. I wanted to bring this up in case it can help resolve this issue or if others have experience with this setup when using husky.

**Comment by forabi** [comment]
Any updates on this? Can we have nvm support as an optional flag (e.g. `--use-nvm`)?

**Comment by typicode** [comment]
Maybe not a flag, as it would mean having specific code for `nvm` inside husky (which is a bit too magical for some users) but I'm considering creating a third-party tool to allow adding `nvm` support again.

**Comment by forabi** [comment]
That would be great. I'd be happy to help!

**Comment by jensfranke** [comment]
I run in the same issue with the tower app (external git client):
``` 
Can't find node in PATH, trying to find a node binary on your system
husky > pre-commit (node v6.2.0)
```

it works via terminal with `nvm use` and `git commit -m'test'`.

version log of `nvm ls`:
```
         v6.7.0
        v6.11.3
        v10.3.0
->      v10.8.0
         system
default -> node (-> v10.8.0)
stable -> 10.8.0 (-> v10.8.0)
system -> 10.8.0 (-> v10.8.0)
node -> stable (-> v10.8.0) (default)
```

if i use `nvm use system` the version is:
```
Now using system version of node: v6.2.0 (npm v3.8.9)
```

husky is using the same version.

what is the best way to fix this issue?

**Comment by zhaozhe0831** [comment]
> I run in the same issue with the tower app (external git client):
> 
> ```
> Can't find node in PATH, trying to find a node binary on your system
> husky > pre-commit (node v6.2.0)
> ```
> it works via terminal with `nvm use` and `git commit -m'test'`.
> 
> version log of `nvm ls`:
> 
> ```
>          v6.7.0
>         v6.11.3
>         v10.3.0
> ->      v10.8.0
>          system
> default -> node (-> v10.8.0)
> stable -> 10.8.0 (-> v10.8.0)
> system -> 10.8.0 (-> v10.8.0)
> node -> stable (-> v10.8.0) (default)
> ```
> if i use `nvm use system` the version is:
> 
> ```
> Now using system version of node: v6.2.0 (npm v3.8.9)
> ```
> husky is using the same version.
> 
> what is the best way to fix this issue?

I have a same problem, too.

**Comment by phifa** [comment]
So is there a way to make this work in VS Code with proper output?

**Comment by typicode** [comment]
Husky doesn't automatically use `.nvmrc`, but you can achieve the same behavior with `~/.huskyrc`
See https://github.com/typicode/husky/blob/master/DOCS.md#huskyrc

You can even use other Node version manager with it.

**Comment by shannonmoeller** [comment]
Thanks, @typicode !
