### ISSUE TITLE
v0.10.0: gulp is trying to use “origin” as a task

### ISSUE THREAD

**Issue by mistadikay** [typicode/husky#29]
Hi,

after updating to v0.10.0, I have a weird behavior in my prepush hook which is the following:

```json
{
  "scripts": {
    "prepush": "gulp --gulpfile gulpfile.js test:build"
  }
}
```

Where `test:build` is the name of gulp task. When I run it as `npm run prepush`, everything is fine. But when husky is running it on `git push origin master`, I have the following error:

```sh
[10:34:31] Using gulpfile ~/*PROJECT_DIRECTORY*/gulpfile.js
[10:34:31] Task never defined: origin
[10:34:31] Please check the documentation for proper gulpfile formatting

husky - pre-push hook failed (add --no-verify to bypass)
```

Which means that for some reason I have `origin` parameter leaked into npm script and it's trying to find gulp task named `origin`. Probably it's because of [this commit](https://github.com/typicode/husky/commit/c7ae4e070811451ecda3f586222ee04ad889dc33)?

**Comment by typicode** [comment]
My bad, you're right. Since pre-commit takes no parameter, I just thought it would be the same with pre-push.

I'll fix that.

**Comment by mistadikay** [comment]
@typicode `v0.10.1` works well, thanks!
