### ISSUE TITLE
Expected Behaviour of Merge

### ISSUE THREAD

**Issue by byronmejia** [typicode/husky#290]
Hey there,

I was wondering what the expected behaviour is of husky. Should pre-commit hooks run if the commit is due to a merge conflict being resolved?

IE:
```
git merge master
# An Merge Conflict must be resolved
# User resolves Conflicts
git commit # To finalize the merge
> Pre Commit hook runs now
```

My script currently checks if it's in the middle of a merge, and terminates the script early in that situation, but what is the expected behaviour of husky?

**Comment by typicode** [comment]
Hey @byronmejia,

I guess it's normal, as Git seems to run `pre-commit`  hook and then husky runs associated script. 

In fact, husky don't "add" any particular behaviours to Git hooks and isn't opiniated. It just runs corresponding scripts if they exist in `package.json`.

Regarding `pre-commit` maybe you can find useful informations here:
https://git-scm.com/docs/githooks#_pre_commit

Hope it helps

**Comment by byronmejia** [comment]
Awesome! Yes, this helps a lot @typicode :)

I'll close the issue just to avoid polluting the open issues :)
