### ISSUE TITLE
hooks not work if husky installed before git init

### ISSUE THREAD

**Issue by CodeLittlePrince** [typicode/husky#296]
Hooks not work if husky installed before git init, and I uninstalled husky, then reinstall it, it works.
### version
`"husky": "^1.0.0-rc.8"`

**Comment by alexeyten** [comment]
Not sure what we could do about it. Husky can't install git hook if there is no git. May be there should be big when husky is installed without git

**Comment by typicode** [comment]
Hi @CodeLittlePrince,

Thanks for the feedback.

Unfortunatly, as @alexeyten summed it up, there's not much Husky can do about it.
Maybe the message will be refined.

**Comment by zhenyulin** [comment]
would it be possible to provide a .bin cli to init husky for this situation?

**Comment by andres-rivera** [comment]
Solution: save your work by pushing your changes to remote repo then delete .git folder and node_modules folder locally. Next run git init followed  by npm install.

**Comment by andres-rivera** [comment]
If you installed husky before you initialized .git then husky will not trigger. Husky can't integrate into git hooks if there is not a .git folder. 

The solution is to reverse the process. Delete .git folder and node_modules folder locally. Run git init first followed by npm install.
