### ISSUE TITLE
Run pre-push only on files committed but not pushed to remote

### ISSUE THREAD

**Issue by alexanto** [typicode/husky#297]
Can I run pre-push hook only on files that are committed but not yet push to remote? Something like I can do when combining pre-commit hook with lint-staged, only run a script for the latest modified files, not entire repo.

**Comment by PombeirP** [comment]
Any comment on this? Can the arguments passed to the hook by Git be accessed when using Husky?

**Comment by udayrajMT** [comment]
Just sharing a relevant link for those interested: 
https://stackoverflow.com/questions/3636914/how-can-i-see-what-i-am-about-to-push-with-git
