### ISSUE TITLE
NPM Install issue 

### ISSUE THREAD

**Issue by jimmynotjim** [typicode/husky#299]
I wanted to take a stab at my suggestion in https://github.com/typicode/husky/issues/171#issuecomment-390796547 but when trying to install the repo dependencies I get an error because the file [referenced in the package.json install script](https://github.com/typicode/husky/blob/dev/package.json#L13) does not exist.

```
Cannot find module '/Users/wilsong/repos/jw/husky/lib/installer/bin'
```

**Comment by typicode** [comment]
Hi @jimmynotjim,

This should be fixed now as `install` script is disabled in development with [pinst](https://github.com/typicode/pinst).

PS: As for having user hooks in addition to project hooks, TBH not sure yet how or if I'd like to support it.

**Comment by jimmynotjim** [comment]
Thanks @typicode. Are you open to a PR to help you decide? If not, no worries, but figured I'd try and lend a hand to ensure everyone on my team can utilize husky (we have mandatory hooks installed on our work machines).
