### ISSUE TITLE
git commit fork error

### ISSUE THREAD

**Issue by sasrar** [typicode/husky#309]
I am trying to install husky and add precommit scripts to my Angular 5 project. After I've installed husky, however, I get this error when I do `git commit` which is perplexing.

```
fork: child 528 - died waiting for dll loading, errno 11
.git/hooks/pre-commit: fork: retry: Resource temporarily unavailable
```

package.json:
```
scripts:{
...
precommit : "ng lint"

}
```

OS: Windows 10
I'm running the terminal in Visual Studio Code in admin mode.

Any ideas on how to fix this?

**Comment by typicode** [comment]
Hi @sasrar,

Sorry, I don't really know. Personally, I'm using Code on Windows, but not in admin mode, and haven't experienced such issue.

I don't think it's related to husky code directly though. Some people are mentioning issues with the antivirus https://stackoverflow.com/questions/37263702/cant-start-git-bash
