### ISSUE TITLE
[QUESTION] - preparecommitmsg prepend branch name to commit message.

### ISSUE THREAD

**Issue by mintuz** [typicode/husky#311]
Hello I'm looking at using husky to prepend branch name to every commit message and I am seeing the following error `prepare-commit-msg hook failed (cannot be bypassed with --no-verify due to Git specs)` 

version of Husky I am using is **0.14.3** is this something I am doing wrong or is it a bug within husky.

I have this as my husky config, any help would be appreciated.

```
  "husky": {
    "hooks": {
      "preparecommitmsg": "./tools/commit-message.sh"
    }
  },
```

and the script I want to run is as follows.

```
#!/bin/sh
#
# Automatically adds branch name and branch description to every commit message.
# Modified from the stackoverflow answer here: http://stackoverflow.com/a/11524807/151445
#

# Succeed on all merge messages, as evidenced by MERGE_MSG existing
[ -f $GIT_DIR/MERGE_MSG ] && exit 0

# Get branch name and description
NAME=$(git branch | grep '*' | sed 's/* //')

# Don't apply this logic if we are in a 'detached head' state (rebasing, read-only history, etc)
# newlines below may need echo -e "\n\n: (etc.)"
if [ "$NAME" != "(no branch)" ]; then
	# Append branch name and optional description to COMMIT_MSG
	# For info on parameters to githooks, run: man githooks
	echo "\n\n: $NAME" >> "$1"
fi
```

**Comment by typicode** [comment]
Hi @mintuz,

I think you're close to make it work :+1: 

A few things:
* I'd suggest using `husky@next` (which translates to `v1.0.0-rc.10` right now) instead of `v0.14.3`
* `v1.0.0` uses raw git hooks names, so `preparecommitmsg` would need to be renamed to `prepare-commit-msg`
* `$1` won't contain Git hook params because Husky is passing them using `HUSKY_GIT_PARAMS` env variable, so you should `HUSKY_GIT_PARAMS` instead in your code

Hope this will help :)

**Comment by mintuz** [comment]
Hey @typicode 

Thanks for getting back to me, your suggestions are working apart from point 3, the HUSKY_GIT_PARAMS come back as `.git/COMMIT_EDITMSG message`, not sure what the message bit of the PARAMS is but all I need is the COMMIT_EDITMSG location so i've hard coded it to `"$GIT_DIR/COMMIT_EDITMSG"`, I imagine it's something I am doing rather than husky so I am happy to close issue if you agree?

i've also included the updated script incase anyone else finds it useful.

## Updated script

```
#!/bin/bash
#
# Automatically adds branch name and branch description to every commit message.
# Modified from the gist here https://gist.github.com/bartoszmajsak/1396344
#

# This way you can customize which branches should be skipped when
# prepending commit message. 
if [ -z "$BRANCHES_TO_SKIP" ]; then
  BRANCHES_TO_SKIP=(master develop)
fi

# Get branch name and description
BRANCH_NAME=$(git branch | grep '*' | sed 's/* //')

# Branch name should be excluded from the prepend
BRANCH_EXCLUDED=$(printf "%s\n" "${BRANCHES_TO_SKIP[@]}" | grep -c "^$BRANCH_NAME$")

# A developer has already prepended the commit in the format [BRANCH_NAME]
BRANCH_IN_COMMIT=$(grep -c "\[$BRANCH_NAME\]" $1)

if [ -n "$BRANCH_NAME" ] && ! [[ $BRANCH_EXCLUDED -eq 1 ]] && ! [[ $BRANCH_IN_COMMIT -ge 1 ]]; then 
  sed -i.bak -e "1s/^/[$BRANCH_NAME] /" "$GIT_DIR/COMMIT_EDITMSG"
fi
```

**Comment by typicode** [comment]
Thanks for sharing :) glad it works.
https://git-scm.com/docs/githooks#_prepare_commit_msg `message` seems to be when `-m/-F` is passed.

**Comment by tolribeiro** [comment]
> Hey @typicode
> 
> Thanks for getting back to me, your suggestions are working apart from point 3, the HUSKY_GIT_PARAMS come back as `.git/COMMIT_EDITMSG message`, not sure what the message bit of the PARAMS is but all I need is the COMMIT_EDITMSG location so i've hard coded it to `"$GIT_DIR/COMMIT_EDITMSG"`, I imagine it's something I am doing rather than husky so I am happy to close issue if you agree?
> 
> i've also included the updated script incase anyone else finds it useful.
> 
> ## Updated Config
> ```
> "husky": {
>     "hooks": {
>       "prepare-commit-msg": "./tools/git-commit-message.sh"
>     }
>   },
> ```
> 
> ## Updated script
> ```
> #!/bin/bash
> #
> # Automatically adds branch name and branch description to every commit message.
> # Modified from the gist here https://gist.github.com/bartoszmajsak/1396344
> #
> 
> # This way you can customize which branches should be skipped when
> # prepending commit message. 
> if [ -z "$BRANCHES_TO_SKIP" ]; then
>   BRANCHES_TO_SKIP=(master develop)
> fi
> 
> # Get branch name and description
> BRANCH_NAME=$(git branch | grep '*' | sed 's/* //')
> 
> # Branch name should be excluded from the prepend
> BRANCH_EXCLUDED=$(printf "%s\n" "${BRANCHES_TO_SKIP[@]}" | grep -c "^$BRANCH_NAME$")
> 
> # A developer has already prepended the commit in the format [BRANCH_NAME]
> BRANCH_IN_COMMIT=$(grep -c "\[$BRANCH_NAME\]" $1)
> 
> if [ -n "$BRANCH_NAME" ] && ! [[ $BRANCH_EXCLUDED -eq 1 ]] && ! [[ $BRANCH_IN_COMMIT -ge 1 ]]; then 
>   sed -i.bak -e "1s/^/[$BRANCH_NAME] /" "$GIT_DIR/COMMIT_EDITMSG"
> fi
> ```
I am also getting the same error message regarding the `sed: can't read /COMMIT_EDITMSG`. Any updates on that?

**Comment by dennerkrans** [comment]
Got it working with this setup @tolribeiro :)

### Config
```
"husky": {
  "hooks": {
    "prepare-commit-msg": "./git-commit-message.sh $HUSKY_GIT_PARAMS"
  }
},
```
### Script
```
#!/bin/bash
#
# Automatically adds branch name and branch description to every commit message.
# Modified from the gist here https://gist.github.com/bartoszmajsak/1396344
#

# This way you can customize which branches should be skipped when
# prepending commit message. 
if [ -z "$BRANCHES_TO_SKIP" ]; then
  BRANCHES_TO_SKIP=(master develop)
fi

# Get branch name and description
BRANCH_NAME=$(git branch | grep '*' | sed 's/* //')

# Branch name should be excluded from the prepend
BRANCH_EXCLUDED=$(printf "%s\n" "${BRANCHES_TO_SKIP[@]}" | grep -c "^$BRANCH_NAME$")

# A developer has already prepended the commit in the format [BRANCH_NAME]
BRANCH_IN_COMMIT=$(grep -c "\[$BRANCH_NAME\]" $1)


if [ -n "$BRANCH_NAME" ] && ! [[ $BRANCH_EXCLUDED -eq 1 ]] && ! [[ $BRANCH_IN_COMMIT -ge 1 ]]; then 
  sed -i.bak -e "1s~^~[$BRANCH_NAME] ~" $1
fi
```

**Comment by johncmunson** [comment]
This might be a more robust solution for a lot of people...
https://gist.github.com/johncmunson/ca02a8027a923a7f4b2f662c67d6528c
It looks for a pattern in the branch name (such as a Jira ticket number) and uses that to prepend commit messages with instead of the entire branch name.
