### ISSUE TITLE
When multiple args from git then HUSKY_GIT_PARAMS only gets first one

### ISSUE THREAD

**Issue by damonmaria** [typicode/husky#312]
In [index.ts](https://github.com/typicode/husky/blob/dev/src/runner/index.ts) `process.argv` is passed into `[, scriptPath, hookName = '', HUSKY_GIT_PARAMS]`.

So if the hook script passes multiple args then only the first is captured. 

To test I echoed out the arguments at different points. 

For a `post-checkout` in the hook script when I `echo gitParams $gitParams` it results in:
`gitParams 6bc99f135cdb87fbc614b90bdccda84b09732fce 6bc99f135cdb87fbc614b90bdccda84b09732fce 1` 
which is correct.

However, when I `echo HUSKY_GIT_PARAMS $HUSKY_GIT_PARAMS` in my script I get just 
`HUSKY_GIT_PARAMS 6bc99f135cdb87fbc614b90bdccda84b09732fce`.

**Comment by typicode** [comment]
Hi @damonmaria, 

Thanks for the heads up.
It should be good with `1.0.0-rc.10`
