### ISSUE TITLE
Hide console.log information behind a DEBUG variable

### ISSUE THREAD

**Issue by Aghassi** [typicode/husky#314]
https://github.com/typicode/husky/blob/41be7d87497399e8ffec7a1b2d54123b4ca84a70/src/runner/index.ts#L45

Currently, this outputs no matter what. However, it seems a bit messy in my opion. Since this just logs information about the runtime environement, can it be hidden behind a flag like `process.env.DEBUG` or something so it doesn't show for everything?

Alternatively, if it was a little prettier (which I don't mind contrib'ing) it would be less annoying 😄

**Comment by typicode** [comment]
Thanks for the feedback. This line is removed in v5 ;)
