### ISSUE TITLE
post-commit didn't work

### ISSUE THREAD

**Issue by zzzgit** [typicode/husky#316]
![image](https://user-images.githubusercontent.com/1060733/42428436-37a293a0-8366-11e8-9b47-867ac2a69261.png)

by this config, `post-commit` totally doesn't work for me
but if I change `post `to `pre`, everything is okay
why?

**Comment by typicode** [comment]
Hi @zzzgit,

I would check maybe that `.git/hooks/pre-commit` and `.git/hooks/post-commit` are the same and contains husky code.

Personally, I've just tried locally but not reproducing.
