### ISSUE TITLE
Husky failing to create hooks on install

### ISSUE THREAD

**Issue by cideM** [typicode/husky#318]
At work we ran into some issues when upgrading from husky to the latest version. Not sure if the problems are on our side, but when looking at the source I noticed that the husky identifier used by [older versions](https://github.com/typicode/husky/blob/10ee88e191cb17407ca03b9ee55879d1a7ecf39c/src/installer/getScript.ts#L14) is `# husky`, but the [current `is.ts`](https://github.com/typicode/husky/blob/dev/src/installer/is.ts#L7) looks for `#husky`. Could it be that because of that husky fails to identify existing hooks?

**Comment by typicode** [comment]
Hi @cideM,

It should look for both `# husky` (`huskyIdentifier`)  and ` #husky` (`previousHuskyIdentifier`) in [`is.ts`](https://github.com/typicode/husky/blob/dev/src/installer/is.ts#L9-L10)
What's the issue exactly?

**Comment by cideM** [comment]
Ah I see now. The git hooks were from version `0.13` and contained a valid identifier. It now appears that the `postinstall` script wasn't running. Could be related to us using `lerna`. Ultimately this issue was probably on our side.

**Comment by typicode** [comment]
Thanks for the update :+1: 
You may be already doing that with `lerna`, but I'd recommend also having husky in the root `package.json` ([doc](https://github.com/typicode/husky/blob/dev/DOCS.md#multi-package-repository-monorepo))
