### ISSUE TITLE
Support for multiple scripts per hook?

### ISSUE THREAD

**Issue by cviebrock** [typicode/husky#319]
I was hoping something like this was supported:

```json
{
  "husky": {
    "hooks": {
      "commit-msg": [
        "some-script.sh",
        "some-other-script.sh",
        "one-more-script.sh",
      ]
    }
  }
}
```

And Husky would run those 3 scripts in order, allowing git to stop at the first failure.

I realize this _could_ be done with one script (that itself runs all 3 parts), or by doing something like:

```json
"commit-msg": "some-script.sh && some-other-script.sh && one-more-script.sh"
```

But I thought the json array might be a bit cleaner syntax.

Any thought to implementing something like this?

**Comment by typicode** [comment]
Hi @cviebrock,

No plan to support this for the moment in Husky.

Maybe there are existing tools or task runners that would allow defining scripts this way and could be used with Husky.

**Comment by cviebrock** [comment]
Thanks for the answers. I might try my hand at a PR to add this, but in the meantime https://github.com/okonet/lint-staged seems to do what I need.

**Comment by dianasaurio** [comment]
I think this would be a nice feature for husky.

**Comment by typicode** [comment]
> Thanks for the answers. I might try my hand at a PR to add this, but in the meantime https://github.com/okonet/lint-staged seems to do what I need.

Glad to read it :)

> I think this would be a nice feature for husky.

Realized recently that you can do it somehow with a `.huskyrc.js` file:

```js
const tasks = t => t.join(' && ') 

module.exports = {
  hooks: {
    'pre-commit': tasks([
      'echo 1',
      'echo 2',
      'echo 3'
    ])
  }
}
```

**Comment by kalpeshsingh** [comment]
> > Thanks for the answers. I might try my hand at a PR to add this, but in the meantime https://github.com/okonet/lint-staged seems to do what I need.
> 
> Glad to read it :)
> 
> > I think this would be a nice feature for husky.
> 
> Realized recently that you can do it somehow with a `.huskyrc.js` file:
> 
> ```js
> const tasks = t => t.join(' && ') 
> 
> module.exports = {
>   hooks: {
>     'pre-commit': tasks([
>       'echo 1',
>       'echo 2',
>       'echo 3'
>     ])
>   }
> }
> ```

For `.huskyrc` file - 

```
"hooks": {
    "pre-commit": "npm run format && npm run test"
}
```
