### ISSUE TITLE
Using most recent config script should emit warning about versions

### ISSUE THREAD

**Issue by Vitao18** [typicode/husky#320]
Trying to use `husky@next` scripts in `0.14.3` should emit some warning. Or maybe we should try to make it more explicit in docs, whatever works.
I spent a lot of time trying to get what was wrong with my scripts and the issue was that I was using new script configuration with `0.14.3`.

I can work on this issue if necessary :)

**Comment by typicode** [comment]
Hi @Vitao18,

Thanks for the help and feedback :)

`husky@next` emits warning if you're using `0.14.3` config, but it's true that `0.14` doesn't emit warning if you use new config.

I'm sorry for the confusion and time spent, but I'm not feeling confident touching `0.14.3` code as it's widely used and stable. I prefer to avoid risk of regression (even if it's low) and focus on releasing `1.0.0`.

That said, feel free if you want to add a warning about the incompatibility in the `0.14.3` README on `master` branch.
