### ISSUE TITLE
Suggest add use yarn run precommit script

### ISSUE THREAD

**Issue by nodece** [typicode/husky#321]
PS:  Node.js has two dependency management tools, npm and yarn.
So I suggest add use yarn run precommit script.
```
npm run -s precommit 
//or 
yarn precommit
```

**Comment by typicode** [comment]
Hi @nodece,

`v1.0.0`  won't have such message and there's also no plan to modify `v0.14.3` so I'm closing this.
But that's a good point :+1: :slightly_smiling_face: thanks
