### ISSUE TITLE
pre-push not work

### ISSUE THREAD

**Issue by wfsovereign** [typicode/husky#322]
"husky": "^0.14.3"
system: osx 10.13.6
node version: v8.11.3

```javascript
 "husky": {
    "hooks": {
      "pre-push": "npm run lint"
    }
  },
```

don't work

**Comment by Ubiquitous23** [comment]
I'm also experiencing the same thing, however if I use **version: 1.0.0-rc.13** everything works fine.

**Comment by aguynamedben** [comment]
Same thing, pre-push hooks didn't work until I specified that specific version.

Install command
```
$ yarn add --dev husky@v1.0.0-rc.13
```
package.json
```json
  "husky": {
    "hooks": {
      "pre-push": "npm run test"
    }
  },
```

**Comment by typicode** [comment]
Hi @wfsovereign,

`husky` field in `package.json` is actually only supported by `v1`.

Thanks for the help @Ubiquitous23, @aguynamedben 👍

**Comment by wfsovereign** [comment]
thanks everybody

**Comment by cassianomon** [comment]
Works with this:

> Same thing, pre-push hooks didn't work until I specified that specific version.
> 
> Install command
> 
> ```
> $ yarn add --dev husky@v1.0.0-rc.13
> ```
> 
> package.json
> 
> ```json
>   "husky": {
>     "hooks": {
>       "pre-push": "npm run test"
>     }
>   },
> ```

Don't work with latest version.

**Comment by brettz9** [comment]
Should this be reopened per the last comment? (In my case, we had preexisting hooks, but running `npm rebuild` still didn't help.)

**Comment by JClackett** [comment]
Im having the same issues, pre-push is not working, neither is commit-msg.

```
"husky": {
    "hooks": {
      "commit-msg": "commitlint -E HUSKY_GIT_PARAMS",
      "pre-commit": "lerna run  --concurrency 1 --stream  pre-commit",
      "pre-push": "yarn typecheck"
    }
  },
```

**Comment by swesleylokiandthor** [comment]
Another vote for reopening this please

**Comment by atul161** [comment]
Hii @swesleylokiandthor ,

Documentation of husky is telling that you automatic configure husky but that is not working correctly. 

I have figured it out. You neeed   unisntall the husky first using  command **_`npm uninstall husky`_** and after that again install it using command `npm install husky --save-dev`  . Now run the listed command 

- `npx husky install`
- npm set-script prepare "husky install"
- npx husky add .husky/pre-commit "Add your coomand here ie lint staged , npm run type-check , npm test etc" 
- Now add the following thing into package.json
   -  ```
 "husky": {
    "hooks": {
      "pre-commit": "lint-staged",
      "pre-push": "npm run type-check"
    }
```

- If you are using husky for linter then add this also in package.json
 `  "lint-staged": {
    "*.@(ts|tsx)": [
      "npm run lint",
      "npm run  format"
    ]
  },`

**Comment by rajjaiswalsaumya** [comment]
`husky` is not working for me too. I am on `windows 10`, and have `prepare` command in my `package.json`, and have latest `husky 7.0.4` installed as of now. I have `git version 2.32.0.windows.2`. I have `pretty-quick` installed. I have package.json having script `"husky": {
    "hooks": {
      "pre-commit": "pretty-quick --staged"
    }
  }`

My husky does not seem to be running at all automatically. When i ran pretty-quick manually, it runs fine. What am i missing here ?

**Comment by alexeyten** [comment]
https://typicode.github.io/husky/#/?id=migrate-from-v4-to-v7
