### ISSUE TITLE
git hooks not auto install

### ISSUE THREAD

**Issue by Neil20170223** [typicode/husky#324]
i install the latest version (1.0.0-rc.13)
had try uninstall and install
had try remove direcory .git/hooks and creat it

**Comment by typicode** [comment]
@Neil20170223, @maartenth what OS and package manager are you using? also the version of the package manager would be helpful.

Do you get any logs from husky when installing it?

**Comment by Neil20170223** [comment]
@typicode  Mac os, npm, 6.2.0

**Comment by typicode** [comment]
Thanks for the details, and congrats on solving it 👍 
I'll try to document the cases where husky doesn't install and how to fix.
