### ISSUE TITLE
Support for spaces in user directory?

### ISSUE THREAD

**Issue by luismasg** [typicode/husky#325]
I use this to hooks scripts in my package.json 
```
    "precommit": "pretty-quick --staged && npm run lint ",
    "postcommit": "git update-index -g"
```
every time I make a commit I get an warning message about the space in my username.
however it runs prettier and lint without problems. not sure what issues this might cause. or if it's corrupting the git index or something. can/should I ignore the warning?

```git commit -m "test husky"
.git/hooks/pre-commit: line 20: export: `suarez/.nvm': not a valid identifier
.git/hooks/pre-commit: line 20: export: `suarez/.nvm': not a valid identifier
husky > npm run -s precommit (node v6.11.5)

🔍  Finding changed files since git revision 8b4181d.
🎯  Found 0 changed files.
✅  Everything is awesome!
.git/hooks/post-commit: line 20: export: `suarez/.nvm': not a valid identifier
.git/hooks/post-commit: line 20: export: `suarez/.nvm': not a valid identifier
husky > npm run -s postcommit (node v6.11.5)

[test-changelog b11a1ae] test husky
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 test.txt
```

in my ` .git/pre-commit` file  I see 

```
... 
load_nvm () {
  # If nvm is not loaded, load it
  command_exists nvm || {
    export NVM_DIR=/Users/luis suarez/.nvm
    [ -s "$1/nvm.sh" ] && . "$1/nvm.sh"
  }

  # If nvm has been loaded correctly, use project .nvmrc
  command_exists nvm && [ -f .nvmrc ] && nvm use
}
...
```

 I'd glady make a PR to wrap the username with double quotes but after skimming husky's source code and I can't find where it's getting the username path.

what is the best option  here?  please advise. and  thank you for reading this.
as a side comment, I have `export HOME=/Users/'luis suarez'`in my .zshrc file

**Comment by luismasg** [comment]
update:
I've located the file that I would change on a PR:

line 30 of `husky/src/utils/get-hook-script.js`  to    `export NVM_DIR="${home}"/.nvm`

I'm not really sure where it's getting the value for 'home'  (sorry ☹️ )

anyways.
I'm on `"husky": "^0.14.3"`
I don't know if it makes sense to make a pr for version 0.14.x or if even if I *can*.
is this something that will go away in husky@next  ?

**Comment by typicode** [comment]
Hi @luismasg,

Thanks for the issue and help with a PR :)

> I don't know if it makes sense to make a pr for version 0.14.x 

Personally, I'd prefer not to release a new version for `0.14.x` as it'll be replaced with `1.0`. 

> is this something that will go away in `husky@next` ?

Yes, it should be fixed in `husky@next` :)
It's quite stable too if you want to switch to it already.
