### ISSUE TITLE
Hooks not working

### ISSUE THREAD

**Issue by standayweb** [typicode/husky#326]
I have set up husky commit hooks to run on commit and push, it works for me and another dev, but for one dev the commit hooks do not get run. Not sure what the issue is here

**Comment by andrea11** [comment]
I have the same issue... I don't know why but it seems that husky don't install correctly git hooks

**Comment by aguynamedben** [comment]
Same here

**Comment by aguynamedben** [comment]
I was experiencing this with a pre-push hook until I saw [this other ticket](https://github.com/typicode/husky/issues/322#issuecomment-413023082) in which somebody mentioned needing to use version 1.0.0-rc.13, then it worked.

**Comment by standayweb** [comment]
Unfortunately, we are already using `1.0.0-rc.13` but thanks for the suggestion

**Comment by ramakrishnasomepalli** [comment]
I have the same issue i tried both the versions (1.0.0-rc.13 and the stable 0.14.3 ) but no hook (pre-commit,post-push ..etc) is triggering . I verified the hooks folder and all the respective scripts are available and husk is also installed as expected. I also verified the " npm config get ignore-scripts" and the flag is set to false.
Any suggestion how to make it work.

**Comment by nikolay-borzov** [comment]
I know that hooks don't work on WebStorm IDE because of the way how WebStorm uses Git

**Comment by yiuyiu** [comment]
@ramakrishnasomepalli 
hello i met the same problem.And i find that the husky must install after git init . When installed it will show setting up git hooks ~

**Comment by typicode** [comment]
Have you fixed your issue?
Are you getting any output from husky when running `npm install husky@next -D` or when commiting/pushing with Git? Also which Git client or IDE are you using?

@ramakrishnasomepalli you've checked the right things... maybe I would check the value of `git config core.hooksPath`

**Comment by ramakrishnasomepalli** [comment]
I am still facing the error but the same configurations are working fine in another machine.

**Comment by ramakrishnasomepalli** [comment]
@typicode  When i am committing i am not getting any logs related to husk.

**Comment by typicode** [comment]
@ramakrishnasomepalli when running `git config core.hooksPath` what do you get? When checking `.git/hooks/pre-commit` (or the failing hook)  does it start with:

```sh
#!/bin/sh
# husky
# v1.0.0...
```

**Comment by Undistraction** [comment]
I have the same problem. Hooks do not run. `git config core.hooksPath` returns nothing.

**Comment by typicode** [comment]
@Undistraction you can simply re-run `npm install husky@next --save-dev`

If it shows:

```
husky > setting up git hooks
husky > done
```

Then everything went fine. Otherwise, if you get something different, could you copy/paste the output here?

**Comment by Undistraction** [comment]
@typicode I found the problem. Husky is a dependency of another package. It seems that even though it is installed when I install that package, it doesn't set up the git hooks.

**Comment by typicode** [comment]
@Undistraction thanks for the update, I was running out of ideas 😅

**Comment by ramakrishnasomepalli** [comment]
@typicode  Please find the below log.
$ npm i husky@next -D

> husky@1.0.0-rc.13 preuninstall D:\workspace\TW-Workspace\Q2A\svc-q2a-quote-pricecheck\node_modules\husky
> node husky uninstall

husky > uninstalling git hooks
husky > done

> husky@1.0.0-rc.14 install D:\workspace\TW-Workspace\Q2A\svc-q2a-quote-pricecheck\node_modules\husky
> node husky install

husky > setting up git hooks
husky > done
npm WARN svc-q2a-quote-pricecheck@1.0.9 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ husky@1.0.0-rc.14
added 2 packages and updated 1 package in 203.131s.

And it is still not working also as suggested by @Undistraction  I have noticed the below packages are missing from being installed under nodule modules of husky but the same are available under my project node modules. 
 "cosmiconfig": "^5.0.6","get-stdin": "^6.0.0","please-upgrade-node": "^3.1.1","run-node": "^1.0.0",

**Comment by MincheolC** [comment]
Hi, I encounter with similar issue. I'm using `husky v1.0.0-rc.14` and `package.json` as follow.
```
"husky": {
    "hooks": {
      "pre-push": "npm test"
    }
  }
```
`pre-push` hook doesn't not working, but `pre-commit` work fine as follow
```
"husky": {
    "hooks": {
      "pre-commit": "npm test"
    }
  }
```
Is there anyone here who can help me with this problem?? Thanks

**Comment by typicode** [comment]
Hi @MincheolC, can you check that `.git/hooks/pre-commit` and `.git/hooks/pre-push` have the same content?

**Comment by jakewies** [comment]
I seem to be having the same issue when upgrading from `0.14` to `1.0.1`. I am using `husky` in conjunction with `lint-staged`:

```
// package.json

"husky": {
    "hooks": {
      "pre-commit": "lint-staged"
    }
  },
  "lint-staged": {
    "src/**/*.{js,jsx,json,css}": [
      ...
    ]
  }
```

I noticed that I am no longer getting any `husky` related output when committing.

My `/.git/hooks/pre-commit` contents begin with:

```
// .git/hooks/pre-commit

#!/bin/sh
# husky
# v1.0.1 darwin

...
```

Not sure what's going on, but I hope this info helps narrow the issue a bit. 😄

**Comment by typicode** [comment]
Hi @jakewies,

To confirm that `pre-commit` is running, I'd try to edit `.git/hooks/pre-commit` and add something like:

```sh
#!/bin/sh
# husky
# v1.0.1 darwin
echo "pre-commit" # should be visible in the console when doing a git commit

...
```

**Comment by jakewies** [comment]
@typicode I'll update that file and see what happens 👍

**Comment by jakewies** [comment]
@typicode I updated `.git/hooks/pre-commit` with the line below:

```bash
 #!/bin/sh
 # husky
 # v1.0.1 darwin

echo "pre-commit"

...
```

I added a test file and committed to source. Unfortunately "pre-commit" was not logged to the console when running `git commit`. 😞

**Comment by typicode** [comment]
@standayweb AFAICT it doesn't seem to be related to husky. Do you have a ` GIT_DIR` env variable set?

**Comment by standayweb** [comment]
@typicode The developer who was having this issue is no longer at the company and has reset his laptop

**Comment by HardcoreParkore** [comment]
For those who come after me - I was having this issue because my git config hooksPath was set to a different directory.

**Comment by jorgemarrero** [comment]
As @HardcoreParkore says, checks you git config, in your folder project: `cat .git/config`

You must remove `hooksPath`, husky will handle this for you.

**Comment by zlydenko** [comment]
> As @HardcoreParkore says, checks you git config, in your folder project: `cat .git/config`
> 
> You must remove `hooksPath`, husky will handle this for you.

what if you dont have config file?

**Comment by codelegant** [comment]
I meet this issue, the reason is I install husky before I init git。

**Comment by JuanmaMenendez** [comment]
Guys my problem is that committing with WebStorm Dialog fails and show me this error: "**cannot spawn .git/hooks/pre-commit: No such file or directory**"

However, when I commit manually in the console, everything works as expected (pre-commit hook is called, the lints executed and the files committed)

I am using Windows and lint-staged.

I tried without _hooksPath_ and setting _hooksPath = .git/hooks_  but the same results it works in the console but not in WebStorm Dialog.

Any ideas?

**Comment by HardcoreParkore** [comment]
@JuanmaMenendez I've seen some people say that adding a shebang to the beginning of the file helps

https://github.com/conventional-changelog/standard-version/issues/254

**Comment by JuanmaMenendez** [comment]
> @JuanmaMenendez I've seen some people say that adding a shebang to the beginning of the file helps
> 
@HardcoreParkore  I had the shebang to the beginning  :(

**Comment by JuanmaMenendez** [comment]
I solved the problem, just in case somebody in the future need it the solution was:

In  "Webstorm Settings > Version Control > Git > Path to Git executable"  to change  “C:\Program Files\Git\mingw64\bin\git.exe” by “C:\Program Files\Git\cmd\git.exe”

**Comment by eiji03aero** [comment]
i kind of had similar case, and found out it was git version.
as part of installation code says, husky requiried git to be some version. maybe this thing should be put on README.md as well?
`Husky requires Git >= 2.13.2`

somehow, when i ran `yarn add -D husky` did not show the error in log supposedly thrown from `src/installer/gitRebParse.ts`

**Comment by hansiemithun** [comment]
I am sorry to be late here, i am facing similar challenges. Can someone please answer this for me: https://stackoverflow.com/questions/57314400/precommit-hook-not-triggering-even-after-failures. I don't want to install lot more libraries and keep it simple in advance is my request.

**Comment by N0xFF** [comment]
> maybe this thing should be put on README.md as well?
> Husky requires Git >= 2.13.2

It should be at the top of README https://github.com/typicode/husky/blob/master/CHANGELOG.md#270

**Comment by timscott** [comment]
I was getting this until I noticed that I was using a version of node that was too old.

**Comment by andres-rivera** [comment]
If you installed husky before you initialized .git then husky will not trigger. Husky can't integrate into git hooks if there is not a .git folder. 

The solution is to reverse the process. Delete .git folder and node_modules folder locally. Run git init first followed by npm install.

**Comment by josmithua** [comment]
@ghost No need to remove .git/node_modules folder, just do `yarn remove husky && yarn add -D husky`

**Comment by 0xc0d3r** [comment]
Let me write my investigation. My `.git/hooks` contains `*.sample` files. I understood that `.git/hooks` are not set up but they are supposed to be set up while installing the `husky`. 

```
$ node -v
v12.8.0
$ npm -v
6.10.2
$yarn -v
1.3.2
```
I removed the current existing hooks in `.git` folder and tried to install again `yarn add --dev husky@next` and expecting for a message `husky > Setting up git hooks` but no luck. Next, I updated my `yarn` version to `1.17.3` and repeated the above steps but no change in result.

Out of nowhere, I tried the same steps with `npm` and everything worked as expected. I could see  the below output
```
$ npm i -D husky@4.2.3
> husky@4.2.3 install ----husky-node-modules-path-------
> node husky install

husky > Setting up git hooks
husky > Done

> husky@4.2.3 postinstall ----husky-node-modules-path-------
> opencollective-postinstall || exit 0

Thank you for using husky!
If you rely on this package, please consider supporting our open collective:
> https://opencollective.com/husky/donate

npm notice created a lockfile as package-lock.json. You should commit this file.

+ husky@4.2.3
added 40 packages from 31 contributors, removed 28 packages, updated 452 packages and audited 1192 packages in 48.427s
found 0 vulnerabilities
```

@typicode Any reasons behind this weird behavior?

**Comment by ivanji** [comment]
I went through the same issue - no hooks were being added to .git hooks - there were just a bunch .sample files. After following most of the solutions specified here - what worked for me was upgrading yarn to the latest version - and reinstalling husky. After that I immediately noticed husky under .git/hooks and everything started working. Thanks!

**Comment by pke** [comment]
Took me forever today. `yarn add -D husky` does *not* run the installation of the hooks.
Only `npm i -D husky` does that.

**Comment by tyust512** [comment]
@pke yes, i also meet this using yarn@latest. Is there any solutions, thanks.

**Comment by anuja8275** [comment]
i m still facing an issue i have install husky added in package.json and script as pre-push "num run doc" but when push from git or source-tree but its not creating doc  after push could some one help me to know.

**Comment by akashagarwal7** [comment]
Using `git version 2.20.1 (Apple Git-117)`, I had to move the husky config from .huskyrc to package.json for hooks to work.

**Comment by ZeeshanTamboli** [comment]
@0xc0d3r This maybe due to the node version being old. Husky requires `Node >= 10`.
I had faced the same issue and switching node version using nvm worked for me.

**Comment by ZeeshanTamboli** [comment]
> Let me write my investigation. My `.git/hooks` contains `*.sample` files. I understood that `.git/hooks` are not set up but they are supposed to be set up while installing the `husky`.
> 
> ```
> $ node -v
> v12.8.0
> $ npm -v
> 6.10.2
> $yarn -v
> 1.3.2
> ```
> 
> I removed the current existing hooks in `.git` folder and tried to install again `yarn add --dev husky@next` and expecting for a message `husky > Setting up git hooks` but no luck. Next, I updated my `yarn` version to `1.17.3` and repeated the above steps but no change in result.
> 
> Out of nowhere, I tried the same steps with `npm` and everything worked as expected. I could see the below output
> 
> ```
> $ npm i -D husky@4.2.3
> > husky@4.2.3 install ----redacted-husky-node-modules-path-------
> > node husky install
> 
> husky > Setting up git hooks
> husky > Done
> 
> > husky@4.2.3 postinstall ----redacted-husky-node-modules-path-------
> > opencollective-postinstall || exit 0
> 
> Thank you for using husky!
> If you rely on this package, please consider supporting our open collective:
> > https://opencollective.com/husky/donate
> 
> npm notice created a lockfile as package-lock.json. You should commit this file.
> 
> + husky@4.2.3
> added 40 packages from 31 contributors, removed 28 packages, updated 452 packages and audited 1192 packages in 48.427s
> found 0 vulnerabilities
> ```
> 
> @typicode Any reasons behind this weird behavior?

@0xc0d3r This maybe due to the node version being old. Husky requires Node >= 10.
I had faced the same issue and switching node version using nvm worked for me.

**Comment by pygeek** [comment]
I'm on Node 14.6.0, using npm with husky@4.2.5 and experiencing this issue.

**Comment by jlug331221** [comment]
> > > As @HardcoreParkore says, checks you git config, in your folder project: `cat .git/config`
> > > You must remove `hooksPath`, husky will handle this for you.
> > 
> > 
> > what if you dont have config file?
> 
> In order, do the following
> 
> * Run `git config --list` and ensure there is no 'hooksPath'
> * If there was a `hooksPath`, remove/comment it
> * Delete the hooks in .git/hooks^1
> * `npm install`
> * You can check that this worked by reading the hook and ensuring that there's a comment from Husky inside it
> 
> ^1: This is required because husky takes over the hooks in .git/hooks at installation time and won't override a pre-existing hook.

This was my problem for anyone that is still having this issue. I just commented the `hooksPath` as @HeyParkerJ suggested and my Husky hooks started working in my project. Thanks for the help!

**Comment by mwanago** [comment]
I had this issue when using Node Version Manager.
If you are using Linux or Mac, creating the `~/.huskyrc` file with a following code might help you:
`# ~/.huskyrc
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"`

**Comment by zzzachzzz** [comment]
This worked for me (using yarn workspaces, with husky installed at the workspace root):
```
rm -r .git/hooks/
yarn remove husky
yarn add husky -D -W
```

**Comment by xenoterracide** [comment]
in yarn 2 I did this, and it worked, but had to have husky in the package.json, having it in .huskyrc.json didn't work

```
yarn husky-upgrade
```

**Comment by steelx** [comment]
> I had this issue when using Node Version Manager.
> If you are using Linux or Mac, creating the `~/.huskyrc` file with a following code might help you:
> 
> ```
> export NVM_DIR="$HOME/.nvm"
> [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"```
> ```

still doesnt work for me. I tried everything mentioned above.
1. no hooks path in git config
2. did `npm i -D husky`
3. deleted hooks folder

still I never see any of these lines
```
husky > Setting up git hooks
husky > Done
```

**Comment by cenda** [comment]
> still doesnt work for me. I tried everything mentioned above.

@steelx  Hi, did you pasted whole mentioned code to `~/.huskyrc` file? I tried it, but I ignored ` ``` ` at the end and it worked for me...

**Comment by steelx** [comment]
> > still doesnt work for me. I tried everything mentioned above.
> 
> @steelx  Hi, did you pasted whole mentioned code to `~/.huskyrc` file? I tried it, but I ignored ` ``` ` at the end and it worked for me...

Thanks for comment. 
Yes, the tripple Tilda are not present in rc file.

**Comment by filipemeneses** [comment]
In case someone come across this, `ignore-scripts` was active in `.npmrc`, so it wouldn't trigger husky scripts.
Removing it, worked.

```
; ignore-scripts=true
```

**Comment by everttrollip** [comment]
I previously tried using `git-lfs` in my repository, which I later removed. However, it still seemed that my pre-push hooks were being overwritten by `git-lfs`. Running an uninstall removed the hooks and the global git lfs configuration. A re-build of npm `node_modules` right after that worked for me and re-configured my pre-push hook to start with: 

```
#!/bin/sh
# husky
# v1.0.0...
```
as mentioned by @typicode here: https://github.com/typicode/husky/issues/326#issuecomment-420264343

Here again the commands I executed,

```
git-lfs uninstall
npm rebuild
```

**Comment by postbird** [comment]
> > > As @HardcoreParkore says, checks you git config, in your folder project: `cat .git/config`
> > > You must remove `hooksPath`, husky will handle this for you.
> > 
> > 
> > what if you dont have config file?
> 
> In order, do the following
> 
> * Run `git config --list` and ensure there is no 'hooksPath'
> * If there was a `hooksPath`, remove/comment it
> * Delete the hooks in .git/hooks^1
> * `npm install`
> * You can check that this worked by reading the hook and ensuring that there's a comment from Husky inside it
> 
> ^1: This is required because husky takes over the hooks in .git/hooks at installation time and won't override a pre-existing hook.
> 
> EDIT: Since this is still somewhat active over 2 years later, I want to mention that I changed my github name from @HardcoreParkore to @HeyParkerJ, since there are some comments with references to both aliases.

that works for me, thanks so much! 
add another point:
if run `git commit -m "feat:xxx"` , and  it shows `husky-run not found`, u can reinstall `husky` to try again.

**Comment by mezentsv** [comment]
Had the same issue. After installing husky my `.git/hooks` contained only `*.sample` files. 
Tried all solutions up here, none of them worked. 
Then I upgraded `npm 15.4.0 -> 15.5.1` and it solved the issue.

**Comment by mezentsv** [comment]
Had the same issue. After installing husky my `.git/hooks` folder contained only `*.sample` files.
Tried all the suggestions up here, none of them worked.
Then I upgraded `node 15.4.0 -> 15.5.1` and it solved the issue.

**Comment by charles-cit** [comment]
I did it using the husky@4.2.3 version

First I uninstalled the installed version> npm uninstall husky
I deleted the hooks folder inside the .git folder

then I installed the version mentioned above> npm i -D husky@4.2.3

With that I could see the messages:
husky> Setting up git hooks
husky> Done

The hooks folder in .git were created correctly and this time with the husky.sh file
And it worked for me.

**Comment by larry-dalmeida** [comment]
> I did it using the husky@4.2.3 version
> 
> First I uninstalled the installed version> npm uninstall husky
> I deleted the hooks folder inside the .git folder
> 
> then I installed the version mentioned above> npm i -D husky@4.2.3
> 
> With that I could see the messages:
> husky> Setting up git hooks
> husky> Done
> 
> The hooks folder in .git were created correctly and this time with the husky.sh file
> And it worked for me.

Only solution that worked for me. Thank you @charles-cit !

**Comment by guvarallo** [comment]
> I did it using the husky@4.2.3 version
> 
> First I uninstalled the installed version> npm uninstall husky
> I deleted the hooks folder inside the .git folder
> 
> then I installed the version mentioned above> npm i -D husky@4.2.3
> 
> With that I could see the messages:
> husky> Setting up git hooks
> husky> Done
> 
> The hooks folder in .git were created correctly and this time with the husky.sh file
> And it worked for me.

After trying every possible solution, this is the only one that worked, thanks @charles-cit!

**Comment by DouglasDev** [comment]
I can confirm there is a serious bug in version 5. I tried all the methods and the only one that worked was installing husky@4.2.3.

**Comment by typicode** [comment]
Since this issue was created, I think many different bugs/solutions were mixed together. Could you create a new issue specifically for husky 5?

**Comment by luisFebro** [comment]
> I did it using the husky@4.2.3 version
> 
> First I uninstalled the installed version> npm uninstall husky
> I deleted the hooks folder inside the .git folder
> 
> then I installed the version mentioned above> npm i -D husky@4.2.3
> 
> With that I could see the messages:
> husky> Setting up git hooks
> husky> Done
> 
> The hooks folder in .git were created correctly and this time with the husky.sh file
> And it worked for me.

This was the solution to me after a battle of tries.

**Comment by AbnerPS** [comment]
> @typicode Eu encontrei o problema. Husky é uma dependência de outro pacote. Parece que, embora seja instalado quando instalo o pacote, ele não configura os ganchos do git. Isso só acontece quando eu instalo explicitamente usando `npm i husky@next -D`.

If you have trouble installing husky@next, try installing version 4 directly: npm install husky@4 --save-dev

**Comment by aymkin** [comment]
```cd .git && rm -rf hooks```
```npm i -D husky@4.2.3```
```npm i -D husky```

**Comment by antoniojps** [comment]
Version `4.2.3` fixed my issue. Works with yarn aswell.

**Comment by tarunbhartiya7** [comment]
> Version `4.2.3` fixed my issue. Works with yarn aswell.

4.3.8 should also work.

**Comment by MeganRook18** [comment]
To get husky to work for me, I had to uninstall version 5 of husky and run `npm install husky@4 --save-dev`, then run `npm rebuild`.

**Comment by samer-nowrx** [comment]
Yes! Apparently version 5 is only available to use in open-source projects! Version 4 is free to use for everyone!

**Comment by num8er** [comment]
I solved it simply calling install from husky binary
```
 ./node_modules/.bin/husky install
```

**Comment by adrianolangaro1** [comment]
I had to remove husky and then add it again on version 4.3.8 and worked just fine

**Comment by callum-bennett** [comment]
It looks like from Husky version 5 onwards you no longer add the husky pre-commit command to the package.json file.

I removed the following from package.json
```
"husky": {
   "hooks": {
      "pre-commit": "lint-staged"
   }
 }
```

Then ran the following
```
yarn remove husky
yarn add -D husky
husky install
husky add .husky/pre-commit "lint-staged" 
chmod a+x .husky/pre-commit
```

Hope this helps

**Comment by dreadwail** [comment]
If you've tried everything listed in this issue and still can't get the damn hooks to install while using older versions of husky (I was using `3.0.8`), just bypass all the cruft and run this:

```
$ node ./node_modules/husky/lib/installer/bin.js install
```

No idea why it wouldn't run for me during installation of the husky package, but that did the trick for me.

```
husky > Setting up git hooks
husky > Done
```

Seems pretty brittle, but I guess `3.0.8` is a pretty old version at this point so maybe the newer versions are a bit better.

**Comment by Dinika** [comment]
> It looks like from Husky version 5 onwards you no longer add the husky pre-commit command to the package.json file.
> 
> I removed the following from package.json
> 
> ```
> "husky": {
>    "hooks": {
>       "pre-commit": "lint-staged"
>    }
>  }
> ```
> 
> Then ran the following
> 
> ```
> yarn remove husky
> yarn add -D husky
> husky install
> husky add .husky/pre-commit "lint-staged" 
> chmod a+x .husky/pre-commit
> ```
> 
> Hope this helps

This works for me with the expectation that I had to use yarn to run the lint-staged command for me in pre-commit (since I have not installed lint-staged globally in my laptop):

```
husky add .husky/pre-commit "yarn add lint-staged" 
```
 I also did not have to make the .huskypre-commit executable. In the husky version I installed, it's executable by default.

**Comment by hosseinmd** [comment]
I solved that by close VS Code and reopen that and run git push in terminal, husky works.

**Comment by jhinter** [comment]
None of the above answers were working for me!

But something finally solved the problem: 
**I just checked out my repo again**, and husky is finally working again! (4.3.6) 

There has to be something messed up in .git, but I don't know what it is. Removing .git/hooks was not resolving the problems for me.

**Comment by MatteoInfi** [comment]
```
npm uninstall husky
```

```
npm install -D husky
```

This is bug on the husky side

**Comment by JanithaR** [comment]
> None of the above answers were working for me!
> 
> But something finally solved the problem:
> **I just checked out my repo again**, and husky is finally working again! (4.3.6) 🎉
> 
> There has to be something messed up in .git, but I don't know what it is. Removing .git/hooks was not resolving the problems for me.

Well, I'll be damned. Busted my brain for hours and finally came down this thread enough to read this comment and tried. Everything started working as expected. v4.3.8

**Comment by DanielRuf** [comment]
If you downgrade from a newer version to v4, ensure to run `git config --unset core.hooksPath`. Because `git config core.hooksPath` will probably display `.husky` but should be `.git`.

**Comment by tomatobybike** [comment]
`yarn remove husky`

`yarn add -D husky@4.3.8
`

and then you can do it success

**Comment by vocoWone** [comment]
Delete project and re-pull remotely

**Comment by javed7891** [comment]
> I can confirm there is a serious bug in version 5. I spent hours trying all the methods and the only one that worked was installing husky@4.2.3. I'm on mac with git version 2.20.1, node v14.15.4, and npm v6.14.10. This issue should be reopened.

Thanks for sharing the fix, this is the only version that worked for macos.

**Comment by atul161** [comment]
Hii  @xenoterracide  @aguynamedben @Undistraction  @pke  @samer-nowrx  @sapegin @pke  @samer-nowrx 

Documentation of husky is telling that you automatic configure husky but that is not working correctly. 

I have figured it out. You neeed   unisntall the husky first using  command **_`npm uninstall husky`_** and after that again install it using command `npm install husky --save-dev`  . Now run the listed command 

- `npx husky install`
- npm set-script prepare "husky install"
- npx husky add .husky/pre-commit "Add your coomand here ie lint staged , npm run type-check , npm test etc" 
- Now add the following thing into package.json
```json

 "husky": {
    "hooks": {
      "pre-commit": "lint-staged",
      "pre-push": "npm run type-check"
    }

```

- If you are using husky for linter then add this also in package.json
```json

  "lint-staged": {
    "*.@(ts|tsx)": [
      "npm run lint",
      "npm run  format"
    ]
  }
  
```

-  Now try to commit . **_Note that dont add .husky into gitignore because sometimes husky will not work for other developer and if .husky folder is present same for every developer then it will work correctly._**

**Comment by Marceloasf** [comment]
What worked for me was: 

- Make sure Husky v4 is installed (v7 was not working).
- Check the output of `git config core.hooksPath`. This should not return anything. If it does run the command:

`git config --unset core.hookspath`

**Comment by kostyanp95** [comment]
> What worked for me was:
> 
> * Make sure Husky v4 is installed (v7 was not working).
> * Check the output of `git config core.hooksPath`. This should not return anything. If it does run the command:
> 
> `git config --unset core.hookspath`

The only thing that helped me out of all the above options! Thanks!

**Comment by xiaoyao316** [comment]
I found that when `git pull` is executed, if there is no updatable content, the `post merge` hook will not be triggered, but if there is updatable content, it will be triggered.

**Comment by jdeblasse** [comment]
@kostyanp95  and others in this thread. The problem is likely due to file permissions of your hooks. Please check.

`File mode changed from 100644 (Regular) to 100775 (Executable)`

**Comment by typicode** [comment]
I'm going to lock this issue, since it goes back to 2018 and solutions provided at the beginning may not be relevant anymore. I think it can create more confusion and harder to debug to leave multiples issues/versions in a single thread.

Feel free to create new issues if needed.

Thanks.
