### ISSUE TITLE
pre-receive or update hook  not work

### ISSUE THREAD

**Issue by fancyboynet** [typicode/husky#329]
Ex, I want do something after the `git push` complete, and I have tried `pre-receive` or `update`, neither of them worked, but the `pre-push` is ok.
```
"husky": "^1.0.0-rc.13"
```
```
"husky": {
    "hooks": {
      "pre-push": "echo 111" // work
    }
  }
```
```
"husky": {
    "hooks": {
      "pre-receive": "echo 111" // not work
    }
  }
```

**Comment by squelix** [comment]
The hook `post-receive` doesn't work either...

**Comment by Aqours** [comment]
It's Server-Side Hooks. You can find more information in [here](https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks)

**Comment by typicode** [comment]
Hi @fancyboynet,

As @Aqours pointed out, only client-side hooks are supported. You can find the full list here: https://git-scm.com/docs/githooks
