### ISSUE TITLE
thoughts on ignoring certain filetypes?

### ISSUE THREAD

**Issue by moimikey** [typicode/husky#33]
I'm not one for flooding features, but... it would be quite nice if `husky` had the ability to filter out glob patterns. my particular use case is that our repository has multiple languages committing which don't require our push hook, which enforces `eslint` to run.

food for thought!

**Comment by typicode** [comment]
Hi @moimikey,

Interesting case. I think that you can create a `prepush.js` script for that:

```js
// prepush.js
var cp = require('child_process')

// Same as git diff --name-only origin/master | grep .js && npm run eslint
if (cp.execSync('git diff --name-only origin/master').indexOf('.js') !== -1) {
  // Run eslint if there's a .js file and redirect child process output to parent
  cp.exec('npm run eslint', { stdio: 'inherit' }, function (err) {
    if (err) throw err
  })
}
```

`package.json`

```json
"prepush": "node prepush.js"
```

**Comment by iamstarkov** [comment]
I also prefer @typicode’s solution, because it will keep husky clean and easy to maintain

**Comment by moimikey** [comment]
i love how it didn't cross my mind to do this. thanks! :+1:
