### ISSUE TITLE
Running multiple command on a hook

### ISSUE THREAD

**Issue by Quadriphobs1** [typicode/husky#330]
I want to run more than one command on a hook. For example running `npm run lint and npm run test` in a `pre-push`.

**Comment by Keramet** [comment]
in package.json:
```
...
"scripts": {
    "precommit": "npm test && npm run lint",
    "start": ...,
    "lint": ... 
  },
```

**Comment by Quadriphobs1** [comment]
Ohhh I was actually not using the `&&` for it and I hope it would work way

**Comment by djErock** [comment]
How can I run these (npm run lint && npm test) concurrently?

**Comment by Thomaash** [comment]
Try `run-p lint test` from https://www.npmjs.com/package/npm-run-all.
