### ISSUE TITLE
hook is running script but git command not running after completion

### ISSUE THREAD

**Issue by ramesh-yadav** [typicode/husky#332]
I am using pre-push hook with 1.0.0-rc.13 version. From last 3 days it is not pushing code to GIT repo after completions of scripts commands. Earlier it was working fine

This has become a blocker for me.

**Comment by alexeyten** [comment]
Husky (and git hooks) has nothing to do with you SSH connection.

**Comment by garrettH3S** [comment]
Same issue here with husky@3.0.9 pre-push hook, 
- running a jest testing suite `npm run test`. 
- issue only happens when it takes over 60s to complete.
- there are no errors thrown. just no push.

**Comment by lhguerra** [comment]
I don't quite understand much about hooks, but it looks to me that they're opening the connection before running the scripts, and that's the reason prepush fails sometimes. Isn't it possible to run the commands before that? Or am I missing something?

Look at the output of this push:

```
husky > pre-push (node v11.9.0)
./scripts/sniff.sh

------------------------------------------------
--------- Running on a stale container ---------
------------------------------------------------


------------------------------------------------
--------- Running on a stale container ---------
------------------------------------------------

yarn run v1.19.0
$ eslint src
Done in 9.32s.
yarn run v1.19.0                                                                                                                           
$ react-scripts test                                                                                                                       
Connection to bitbucket.org closed by remote host.
PASS src/modules/user/lib/__tests__/roles.js (6.383s)

.... a lot more lines of test output ....
```

As you can see, my devtoolsl container took some time to start and the connection to Bitbucket was closed even before the tests started to running, which means it was open before needed.

**Comment by Aure77** [comment]
Same issue... (husky 4.2.5)

**Comment by typicode** [comment]
Closing as I'm cleaning old issues.
