### ISSUE TITLE
QQ: Async scripts?

### ISSUE THREAD

**Issue by clintandrewhall** [typicode/husky#335]
I'm using [HackMyResume](https://github.com/hacksalot/HackMyResume) to build a set of files, and it appears the PDF generation is asynchronous, so [my precommit hook](https://github.com/clintandrewhall/clintandrewhall.com/blob/master/package.json#L84) finishes before the PDF is generated... so it doesn't get added.

Curious if there's a way to support async jobs out of the box, or if I should hack this to be synchronous?  Thanks in advance!

**Comment by typicode** [comment]
Hi @clintandrewhall,

I've never personally used HackMyResume, but what if you change your `precommit` script to something like this?

```json
"precommit": "lint-staged && yarn generate && git add <file(s) that were generated by HackMyResume>" 
```

**Comment by xmsz** [comment]
Is there another solution ?
