### ISSUE TITLE
Propose: make husky-install configurable when git-hooks have already exists

### ISSUE THREAD

**Issue by imcuttle** [typicode/husky#336]
In my scene:
I already have `commit-msg` hook, so running `npm i husky -D` fails to inject husky's `commit-msg` hook.

so I consider that I could make husky-install configurable. For example:

- `package.json`
```json
{
  "husky": {
     "installType": "overwrite"
  }
}
```

And husky could read `install` field which is one of `overwrite`, `append`, `skip(by default for compatibility)`.

- `overwrite`: overwriting the previous hook
- `append`: appending to the previous hook
- `skip`: skipping husky

**Comment by imcuttle** [comment]
I had release the temporary package `@moyuyc/husky` which implemented.

[@moyuyc/husky - Allow user's existing hooks](https://github.com/imcuttle/husky/blob/tmp-release/DOCS.md#allow-users-existing-hooks)

**Comment by jsumners** [comment]
At the very least an environment variable `HUSKY_OVERWRITE=true` should be supported. I am migrating from `pre-commit` on some widely developed OSS projects and the `isPreCommit` check does not actually figure out the current hook script is a `pre-commit` script for whatever reason. Ultimately, I just want to be able to force the overwrite so that when other contributors install new dependencies the hook will be updated.

**Comment by imcuttle** [comment]
Hi, @jsumners  
Use environment variable like `HUSKY_OVERWRITE=true` is just taking effects in your computer **excluding other contributors**. But `"appendType": "overwrite"` in `package.json` works with everyone.

And `husky` overwrites `pre-commit` correctly on mac os.

**Comment by jsumners** [comment]
I agree that the `package.json` approach is the right one. Just stating that the env var is a minimal approach.

I am on macOS and a fresh install of `husky` in a project skipped updating the installed git pre-commit hook, which was added by the `pre-commit` package.

**Comment by typicode** [comment]
> isPreCommit check does not actually figure out the current hook script is a pre-commit script for whatever reason

I would be interested to know why. What's the content of the `pre-commit` generated script? Does it contain `./node_modules/pre-commit/hook` string?

**Comment by hugomrdias** [comment]
i'm trying to migrate to husky from git-validate and would also need a way to force git hooks overwrite

**Comment by jsumners** [comment]
https://asciinema.org/a/uHh4ulQ7jqc8RSgGNXMzuLWsQ

```sh
#!/usr/bin/env bash
./node_modules/.registry.npmjs.org/@jsumners/pre-commit/1.2.2-fork.1/node_modules/@jsumners/pre-commit/hook
RESULT=$?
[ $RESULT -ne 0 ] && exit 1
exit 0
```

Regardless, the feature requested in this issue is a good solution for explicitness. @imcuttle have you not submitted a PR to add this feature?

**Comment by hugomrdias** [comment]
@typicode overwrite existing hooks is really important when migrating users would you consider this ?

**Comment by hugomrdias** [comment]
Ping @typicode please take a look at this problem 
would you consider this ?

**Comment by jsumners** [comment]
@imcuttle please rebase your fork onto the current source and submit a PR.

**Comment by imcuttle** [comment]
@jsumners  I had submit a [PR](https://github.com/typicode/husky/pull/337) long long ago.

**Comment by tomasbjerre** [comment]
I also implemented a proposal: https://github.com/typicode/husky/pull/535
