### ISSUE TITLE
add hook when husky return with 'failed'

### ISSUE THREAD

**Issue by heavybeard** [typicode/husky#338]
I need to run a script if git-husky hook return with `husky > pre-commit hook failed (add --no-verify to bypass)`, but I didn't find it.

I used the workaround [here](https://github.com/typicode/husky/issues/115#issuecomment-290175590), it seemed sufficient but it doesn't work how it expected

If it's not implemented yet, I think it could be a useful feature

**Comment by heavybeard** [comment]
I'm working in a private repo, I cannot share code, but `@angular/material` has the same approach so you can use that repo to check the following steps to setup a similar config:

1. clone [`@angular/material`](https://github.com/angular/material2) repo
2. run `npm install -D husky`
3. add the following object in json
    ```json
    "husky": {
      "hooks": {
        "pre-commit": "gulp lint"
      }
    }
    ```
4. create a new component in `<root>/src/lib` (you can duplicate the `button` and renamed it `new-button` o what you want)

Now, you have a codebase with a CODEOWNER lint error a you can't push you `new-component` in remote repo thanks to `husky`:

1. add `new-component` to `staged` files and commit
2. `pre-commit` hook run linting with in all codebase and it does not pass because of the missing owner in `<root>/.github/CODEOWNERS` file

As a developer you want to push my code, so you'll fix the lint error adding the owner on the file and you re-run the `git commit` phase

1. add the owner in `<root>/.github/CODEOWNERS` file
2. re-run the commit

Now, you have a codebase without lint errors, but you push a lint-error codebase because your CODEOWNERS file was not in `staged` files.

This is wrong for my project, so I found a early solution in order to prevent these hacks: I want to stash modified files and run the lint only on `staged` codebase.
In this phase, if hook return with a fail I want to `stash pop`, I want to `stash pop` file in order to make modified files available again to dev.

#### Best solution, IMHO

1. change `"pre-commit"` hook with `"git stash save --keep-index && gulp lint"`
2. add `"husky-fail"` hook with `"git stash pop"` <- this is what I would like ❤️  😄 

#### Fix that doesn't work

1. change `"pre-commit" hook with "git stash save --keep-index && gulp lint || git stash pop"

PS: Sorry for the long description, but I want to describe all. Let me know if you want more

**Comment by typicode** [comment]
Thanks for the detailed instruction, it's really helpful. I can reproduce and I see the kind of issue.
Not sure yet why `|| git stash pop` doesn't work as expected.

**Comment by Tangelo1** [comment]
Bump. Would love to see this implemented

**Comment by osdiab** [comment]
@typicode the problem is that `husky.sh` runs the script with the `-e` flag, making it immediately abort if any command in the hook errors. So if you want to pop the stash after a command fails - you can't, unless you remove that flag.

So what you can do as a user is to just run `set +e` in your hook. Here's an example from my project:

<details>
<summary>Example</summary>

```
#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

set +e  # dont fail immediately after error

[[ -z $(git status --short) ]]
UNTRACKED_CHANGES=$?
if [[ $UNTRACKED_CHANGES != 0 ]]; then
  echo "🧐 There are uncommitted changes, stashing them before running checks."
  git stash --include-untracked
fi

echo "😎 Checking lint errors before you push..."
yarn lint
LINT_STATUS=$?

if [[ $LINT_STATUS != 0 ]]; then
  echo "🚨 Lint errors were present! Please run yarn:lint:fix to autofix them (and fix by hand any that couldn't be fixed automatically)."
fi

if [[ $UNTRACKED_CHANGES != 0 ]]; then
  echo "📦 Unstashing your previous uncommitted changes!"
  git stash pop --quiet
fi

exit $LINT_STATUS

```
</details>
