### ISSUE TITLE
Not able to access process.env in integrated git

### ISSUE THREAD

**Issue by IvanMiIosevic** [typicode/husky#339]
Hi,

For my `npm test` script, i use some process.env variables to connect to a database.

When i commit or push from the terminal, my tests are passing because husky seems to be able to access these environment variables but when i commit or push from Atom's integrated git, Husky isn't able to access these env variables so all my tests are failing and i can't push or commit.

```
FAIL tests/models/apartmentCondition.test.js
  ● Test suite failed to run
    Dialect needs to be explicitly supplied as of v4.0.0
      13 | let sequelize;
      14 | if (config.use_env_variable) {
    > 15 |   sequelize = new Sequelize(process.env[config.use_env_variable]);
```
[screenshot](https://imgur.com/a/nMQKduJ)

Is this a Husky bug or is it on Atom's side ?

**Comment by typicode** [comment]
Hi @IvanMiIosevic,

I'd say it's on Atom's side.

When opening Atom, I suppose shell's env variable aren't inherited. It's often the case with GUI Git clients, they don't have the same env variable as the terminal.

Maybe https://atom.io/packages/env-from-shell can help.

**Comment by IvanMiIosevic** [comment]
Thank you !
