### ISSUE TITLE
feature request: check an environment variable to bypass hooks

### ISSUE THREAD

**Issue by SKalt** [typicode/husky#346]
Git only passes a `--no-verify` option to the commit-msg, pre-commit, pre-push, and pre-rebase hooks.  To allow skipping other hooks, I'd propose checking the truthiness of an environment variable with a prefix like  HUSKY or GIT and a suffix like _NO_VERIFY or _BYPASS.  
Raised in response to #344 .

**Comment by SKalt** [comment]
(1) use on windows: I'm proposing a modification to the js or git bash scripts, both of which will be able to detect environment variables cross-platform. 
```{typescript}
// in src/runner, either index.ts or bin.ts
if (require('process').env.HUSKY_NO_VERIFY) // skip all hooks
```
```{sh}
# in all hook scripts
if [ -n $HUSKY_NO_VERIFY ]; then echo "skipping hook etc" && exit 0; fi 
```
 This would not require any modification of hooks written in package.json / .huskyrc.  
(2) use cases boil down to needing to use `--no-verify`:
- you need to push a hotfix to prod now, are sure it works, and will lint it later.
- you are working on a legacy codebase, and would rather pause your lint/test pipeline until you're done.
-  you're debugging your tests, but can't effectively make your changes until your tests pass

All of these are edge cases that run counter to the idea of using git hooks. Still, I think leaving a consistent escape mechanism adds value.

**Comment by philihp** [comment]
Shouldn't lint/test be done on pre-commit or pre-push?

IMO`--no-verify` _is_ the consistent escape mechanism.

**Comment by gajus** [comment]
Seems like now I need to use something along the lines of this to by-pass a hook:

https://github.com/gajus/gitdown/commit/42609720a7122be6c0c45cf84af7ce8a26f53ce6

**Comment by nicosampler** [comment]
The Environment variable proposal seems very useful for me, any news on this request?

**Comment by SKalt** [comment]
Nothing other than what you see here, as far as I know. Might be worth tossing up a PR. Worst case is it pushes the discussion forward.

**Comment by typicode** [comment]
Closing, it's possible to do it now with `HUSKY_SKIP_HOOKS=1`

**Comment by bokub** [comment]
@jjangga0214 Looks like the new syntax is now `HUSKY=0`
