### ISSUE TITLE
What blocks the v1.0.0 release?

### ISSUE THREAD

**Issue by chenrui333** [typicode/husky#347]
Just curious what prevents from releasing v1.0.0 and what are the features in v1.0.0.

Thanks!

**Comment by navarroaxel** [comment]
The changes are on the CHANGELOG.md but could be a cool thing consolidate all the changes on the release of the v1.0.0, and highlighting what are the **breaking changes**.

The bad thing is that the version 1.0.0-rc.15 was released with the tag **latest** on npm, instead of using **next**

**Comment by chenrui333** [comment]
I see, thanks for the update. Would that be good to create a [milestone](https://help.github.com/articles/creating-and-editing-milestones-for-issues-and-pull-requests/) to track the progress?

**Comment by typicode** [comment]
@chenrui333 not much but I wanted to wait until I'm satisfied and enough people have tested it.

But I'm happy to say that the release is in progress. `1.0.0-rc.15` is the new `@latest` version and isn't behind a `@next` tag anymore :tada:.

> The changes are on the CHANGELOG.md but could be a cool thing consolidate all the changes on the release of the v1.0.0, and highlighting what are the breaking changes.

:+1: it's on my todo list :slightly_smiling_face:

**Comment by typicode** [comment]
> The bad thing is that the version 1.0.0-rc.15 was released with the tag latest on npm, instead of using next

It's on purpose (https://github.com/typicode/husky/issues/354)
