### ISSUE TITLE
Specifying path to .git directory?

### ISSUE THREAD

**Issue by affanshahid** [typicode/husky#348]
We have a mono-repo for an enterprise application. A particular component of this app is built with Node.js and uses husky. The folder structure is similar to:

ROOT
  - .git
  - compA
  - compB
  - compC
    - subCompA
      - package.json (husky configuration)

Currently it tells me `.git` not found so it is unable to set up hooks. Is there some way I can specify the `.git` directory, which is a few folders up?

**Comment by lvl99** [comment]
I'm unable to do the same. Have a folder structure like so:
```
  project/
    .git/
    # server files and folders...
    frontend/
      # frontend files and folders...
      package.json
```

When running `git commit ...` in `project/frontend` the husky pre-commit hook outputs:
```bash
  fatal: Not a git repository: '.git'
  husky > post-commit hook failed (cannot be bypassed with --no-verify due to Git specs)
```

**Comment by fleboulch** [comment]
Same issue for me (get the current branch name always fails)

Folder structure
```
project/
    .git/
    frontend/
      package.json
    scripts/
        husky.sh
    .huskyrc
```

.huskyrc
```
{
  "hooks": {
     "pre-push": "../scripts/husky.sh",
  }
}
```

frontend/husky.sh

```
#!/bin/bash
...
currentBranchName=$(git rev-parse --abbrev-ref HEAD) # fails (see error message below)
...
git add ../app.json # success
git commit --amend --no-edit # success
```

Error message
`fatal not a git repository (or any of the parent directories) .git
`

This is quite weird because when I run my script directly from my terminal it works perfectly.

**Environment**: Ubuntu 16.04

**Comment by fatso83** [comment]
@fleboulch I am not certain what happens, as I can run the exact same script with success in any folder in the terminal with success, but you can fix this in two ways:
1. Manually go to the root folder using `cd`, as in `cd .. && git add app.json`, etc
1. Specify the git and workdir on the git cli. Example
```javascript
const gitcmd = 'git --git-dir ../.git --work-tree ..';
async.parallel(
  {
    branch: exec(gitcmd + ' rev-parse --abbrev-ref HEAD'),
    commit: exec(gitcmd + ' rev-parse HEAD'),
    changeDate: exec(gitcmd + ' show -s --format=%ci HEAD') // iso-like string. %cI (strict iso) is only supported in newer git versions (2.6+?), and the server has git 2.1
  },
  (err, results) => {
    if (err) {
      console.error(err);
      process.exit(1);
    }
```

**Comment by fatso83** [comment]
@affanshahid Are you actually experiencing this bug anymore. You talked about the install step, but I suspect the install step is actually ok, and you get these errors on commit - like the rest of us.

With regards to that, both @lvl99, @fleboulch and me are actually talking about a different issue. This issue purports to be about the install step of husky, whereas the three of us talk about issues post-install, where `package.json` lies in a subfolder of the root git folder. That's issue  #98.

**Comment by typicode** [comment]
Cleaning old issues. Feel free to re-open if needed.

**Comment by Ronsku** [comment]
This is an issue in v5 for me. When .git folder isn't in the same folder as package.json and it runs:
`"postinstall": "husky install",`
husky it says
`Error: .git can't be found`

**Comment by Ronsku** [comment]
@typicode 
Checkout this when running latest 5.1.3. This comes from package.json `"postinstall": "husky install", or `"husky": "husky",` by running `yarn husky install` manually:
![image](https://user-images.githubusercontent.com/7983358/109805917-b14dc000-7c2c-11eb-9b73-6371fc05f01b.png)

My project structure:
Root
- .git
- Server
- Client
  - package.json

What to do?

**Comment by mattpfeffer** [comment]
Same problem as @Ronsku but looking at the below in **husky/install.ts** it seems that's intentional.
```javascript
  // Ensure that we're not trying to install outside cwd
  const absoluteHooksDir = path.resolve(process.cwd(), dir)
  if (!absoluteHooksDir.startsWith(process.cwd())) {
    throw new Error('.. not allowed')
  }

  // Ensure that cwd is git top level
  if (!fs.existsSync('.git')) {
    throw new Error(".git can't be found")
  }
```

If you absolutely need to get this working in a pinch, the dirty solution is to temporarily modify `!fs.existsSync('.git')` to a relative path to your root to allow the install. Keep in mind, afterwards you'll also need to point `hooksPath` in `.git/config`  to your `.husky` folder which will be in your subdirectory. That shouldn't be taken as a recommendation though.

**Comment by Maxim-Mazurok** [comment]
See https://typicode.github.io/husky/#/?id=custom-directory

**Comment by aleksandervalle** [comment]
> See https://typicode.github.io/husky/#/?id=custom-directory

@Maxim-Mazurok this worked superbly!

Given repo structure:
```
.git
micro-frontends
    layout
        .husky
            pre-commit
        ...
        package.json
```

Then  changing directory in `pre-commit`
```
#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

cd micro-frontends/layout
yarn pretty-quick --staged && yarn concurrently yarn:test yarn:lint
```

and same in  `package.json`
```
"scripts": {
    ...
    "prepare": "cd ../.. && husky install micro-frontends/layout/.husky"
  }
```

did the trick for me.

**Comment by Ronsku** [comment]
Thanks @Maxim-Mazurok and @aleksandervalle!

**Comment by agneym** [comment]
Is this possible with multiple custom directories? 

Repository structure:

```
.git
package-a
    package.json
package-b
    package.json
package-c
```
I need husky and lint-staged to work on `package-a` and `package-b` but not `package-c` and the `package.json` is inside these directories. 

Following the documentation for [custom directory](https://typicode.github.io/husky/#/?id=custom-directory) in both `package-a` and `package-b`, it seems to rewrite each other hooks.

**Comment by induratized** [comment]
@agneym what approach did you found for your case? Did you went for installing husky individually for each package ?

**Comment by agneym** [comment]
@induratized yes, that's what I ended up doing. Even though that would not have been my first preference

**Comment by induratized** [comment]
@agneym I found a solution on github comments to this so that you only have to husky install in the root folder of your monorepo once

Install and setup ([instructions to setup](https://typicode.github.io/husky/#/?id=install)) husky in your root folder and in root package.json script block add prepare script as below:

```json
"script": {
    "prepare": "cd .. && husky install <**root_dir_name**>/.husky"
}
```

`cd..` is to let husky know that the `.git` folder is a directory up .

My project folder struct is below
**ROOT**
    .git
    projectA
    projectB
        app1
            src
            package.json
        app2
            src
            package.json
        package.json   <----- husky installed here and monitors app1 and app2 etc.

**Comment by ababakanian** [comment]
> https://typicode.github.io/husky/#/?id=custom-directory

This worked for me

**Comment by el-f** [comment]
Can also add this to the pre-commit script, this will continue to go up one folder until it detects a git repo or reaches the fs root in which case it will terminate with error.

```sh
while [ ! -d .git ] && [ "$PWD" != "/" ]; do
  cd ..
done

if [ ! -d .git ]; then
  echo ">> Cannot find .git directory"
  exit 1
fi
```

**Comment by MartinMuzatko** [comment]
> > [typicode.github.io/husky/#/?id=custom-directory](https://typicode.github.io/husky/#/?id=custom-directory)
> 
> This worked for me

This link doesn't exist anymore.

**Comment by induratized** [comment]
> > > [typicode.github.io/husky/#/?id=custom-directory](https://typicode.github.io/husky/#/?id=custom-directory)
> > 
> > 
> > This worked for me
> 
> This link doesn't exist anymore.

try this updated link under Guide section :
https://typicode.github.io/husky/guide.html#custom-directory

**Comment by Yona-Appletree** [comment]
That link doesn't exist any more, either :(
