### ISSUE TITLE
Rebasing performance issues?

### ISSUE THREAD

**Issue by tony** [typicode/husky#351]
In our configuration, we only have a `pre-push`. Despite that, rebasing that usually would take <10 seconds now takes >3 minutes. 

(I don't think `pre-push` triggers in an interactive rebase / any rebase, does it?)

Using v1.0.0-rc13. This is happening on mac and linux.

Is there any way possible hooks not specified in the config could not be installed (#204)?

Is lieu of that, how about an environmental variable to skip all hooks (#346). Though, I guess that wouldn't skip the hooks triggered on rebase?

Is there a way I could provide better debug info? Is anyone else experiencing this as of v1.0.0-rc.13?

**Comment by typicode** [comment]
Hi @tony,

Not sure why it's happening. Maybe you've already found the reason or a workaround.

Anyway, a little more debug info was added (thanks to @wsmd PR) in v1.1.2. Set `HUSKY_DEBUG=true` and you should see a debug message for each hook.

Hope it'll help.
