### ISSUE TITLE
Was v1 intentionally released as `latest` on npm?

### ISSUE THREAD

**Issue by Timer** [typicode/husky#354]
```
joes-mbp:create-react-app joe$ npm dist-tag ls husky
latest: 1.0.0-rc.15
next: 1.0.0-rc.14
```

Was v1 intentionally released as stable under a beta version? Or was this an accident?

If this was an accident, please re-tag the old version for `latest` (`0.14.3`). 😄

**Comment by typicode** [comment]
Hi @Timer,

Yes, it was intentional :)

I released the ` rc` Friday, so that if something goes wrong I can rollback or fix it during the week-end to reduce the impact on users.

The `rc` will be removed soon :+1:

**Comment by Timer** [comment]
Awesome, thanks!
