### ISSUE TITLE
runs twice with multiple pushurls

### ISSUE THREAD

**Issue by netpoetica** [typicode/husky#355]
FYI, if you have configured multiple pushurl in your .gitconfig, the pre-push task will run twice

**Comment by typicode** [comment]
Good to know, thanks :)

Not sure Husky should do something about it, as Husky's role is just to call corresponding script when Git runs the hook. Maybe third-party, or some scripting to prevent this.

**Comment by netpoetica** [comment]
@typicode Are you under the impression that a the hooks can check what the current remote is, and bypass for certain remotes? I do not think that we have access to current rename name in the scripts, but I could be wrong for sure
