### ISSUE TITLE
Any plan to release it as CLI app and Library too?

### ISSUE THREAD

**Issue by DrSensor** [typicode/husky#356]
Hi, thanks for the husky (:dog: woof!). I found out that I can put the config in `.huskyrc.json` and it's really nice that husky use git-hooks natively by injecting wrapper script in `.git/hooks`.

I wonder if in the future I can use it in a non-JS/npm base project :thinking: (e.g `$ husky setup` will setup the git-hooks base on `.huskyrc.json`).

Also having husky can be used as a library could be a good idea in case someone wants to create a feature for setup git hooks (e.g vscode extension for applying git-hooks)

**Comment by typicode** [comment]
I can see the advantages but no plan for that for the moment. Thanks for the feedback.
