### ISSUE TITLE
If "hooks" folder do not exists, install seems to fail

### ISSUE THREAD

**Issue by DavidBabel** [typicode/husky#358]
I guess the title get the issue.

Tested with husky 1.0 and yarn 1.9.4

**Comment by mattbailey** [comment]
Ran into this today too setting up a new project, pretty annoying. Can be overcome with this in package.json:

```json
  "scripts": {
    "preinstall": "mkdir -p .git/hooks 2> /dev/null"
  }
```

but obviously, that's not cross-platform and kinda hacky.

**Comment by DavidBabel** [comment]
Here is a fix: https://github.com/typicode/husky/pull/366, hope @typicode will consider it.

**Comment by typicode** [comment]
Should be good in `v1.1.0`, thanks for the feedback and PR :)

**Comment by DavidBabel** [comment]
thanks
