### ISSUE TITLE
Error "Not a git repository" when trying to execute git command inside of bash script

### ISSUE THREAD

**Issue by dcurletti** [typicode/husky#364]
I have a bash script: 
```bash
#ts-precommit.sh

SRC_PATTERN=".*\.(ts|tsx)$"
if git diff --cached --name-only | grep --quiet -E "$SRC_PATTERN"
```
That I am running like so:
```json
"husky": {
    "hooks": {
      "pre-commit": "sh ./ts-precommit.sh"
    }
  }
```
And I get the following output:
```
Not a git repository
To compare two paths outside a working tree:
usage: git diff [--no-index] <path> <path>
```

Any reasons why I wouldn't be able to call `git` from the script?

**Comment by typicode** [comment]
Hi @dcurletti,

Hmm I don't really know why it doesn't work :/
What do you get if you `echo $PWD` and `echo $GIT_DIR` in your `ts-precommit.sh`?

**Comment by dcurletti** [comment]
Hi @typicode -
The working directory is correct, but the GIT_DIR was wrong. 
I fixed it by doing `unset $(git rev-parse --local-env-vars)`
You can also append `env -i` to any of your git commands if you don't want to unset the vars for the entire script.

Found with the help of:
https://stackoverflow.com/questions/3542854/calling-git-pull-from-a-git-post-update-hook
https://serverfault.com/questions/107608/git-post-receive-hook-with-git-pull-failed-to-find-a-valid-git-directory

**Comment by typicode** [comment]
Thanks for sharing :+1:
