### ISSUE TITLE
Easy to misunderstand readme instructions

### ISSUE THREAD

**Issue by Val-istar-Guo** [typicode/husky#367]
> Starting with 1.0.0, you can also use any of the files/formats that are supported by cosmiconfig. This means that you can place your husky hooks config in a .huskyrc file or export them from a husky.config.js file as well. Cosmiconfig supports .js, .json, and .yaml file formats.

when I am trying to use yml as a configuration file. i don't know it should be named with `husky.yml`, `.husky.yml`, `husky.config.yml`, `huskyrc.yml` or `.huskyrc.yml`.

After a few tries, I found `.huskyrc.yml` to be correct. English is not my mother tongue, Clear instructions make it easier to understand.

Description like config section in the [marionebl/commitlint](https://github.com/marionebl/commitlint) is well：
>Configuration is picked up from commitlint.config.js, .commitlintrc.js, .commitlintrc.json, or .commitlintrc.yml file or a commitlint field in package.json

**Comment by typicode** [comment]
Thanks for the feedback :+1: and example from commitlint. I'll update this part :)

**Comment by typicode** [comment]
Updated

**Comment by Val-istar-Guo** [comment]
> Starting with 1.0.0, you can also configure hooks using .huskyrc, .huskyrc.json or .huskyrc.js file.

Will the yml format be no longer supported? 😱

**Comment by typicode** [comment]
It was just to simplify docs, but yml will be supported :) (actually as long as cosmiconfig supports it ouf the box)
