### ISSUE TITLE
Add support for nodenv

### ISSUE THREAD

**Issue by jantimon** [typicode/husky#369]
Would you be open to support nodenv (a quite common node version manager)?  
https://github.com/nodenv/nodenv

We would have to add the following three lines to all hook files:
```
if command -v nodenv >/dev/null 2>&1; then
  eval "$(nodenv init -)"
fi
```

Should I create a merge request?

**Comment by jantimon** [comment]
@typicode - should I create a merge request to add support for nodenv?

**Comment by typicode** [comment]
Hi @jantimon,

Thanks for your patience. 

Yes, it's an undocumented feature for the moment, but I'm experimenting with sourcing `~/.huskyrc` (if it exists) to allow different version managers.

It's available since `1.1.4`

```sh
# ~/.huskyrc
# Note: it will run in /bin/sh shell
if command -v nodenv >/dev/null 2>&1; then
  eval "$(nodenv init -)"
fi
```

**Comment by jantimon** [comment]
Wow that's amazing - so I can basically just drop in that file and it will be executed just before any hook?

**Comment by typicode** [comment]
Does it work as expected?

**Comment by jantimon** [comment]
Yes thanks.
