### ISSUE TITLE
EISDIR: illegal operation on a directory, read on yarn/npm install

### ISSUE THREAD

**Issue by davidlivingrooms** [typicode/husky#376]
Hello, 
    Just wanted to share an issue that was causing me some headache. Husky is throwing

`EISDIR: illegal operation on a directory, read`

on yarn or npm install for me. The git hooks then fail to install. I was attempting to use husky v1.1.1.

I tried reinstalling, tweaking .npmrc, yarn cache clean but nothing worked. The only thing that worked for me was downgrading the version of husky I was trying to use. In this case, I went down to 0.14.3 and then it worked. Thanks.

Mac OSX Version: 10.13.3
yarn: 1.10.1
npm 5.6.0

**Comment by typicode** [comment]
Hello @davidlivingrooms,

What rights do you have for `.git/hooks` directory or files? Is it consistent with the rest?

**Comment by DylanMerigaudShapr** [comment]
I had a dependencies that was named package.json which makes husky thinks it's the actual package.json, removed this dependencies and it now works ! (reinstall husky in order to create hooks)
