### ISSUE TITLE
Merge conflict in json file results in JSONError

### ISSUE THREAD

**Issue by brandondoran** [typicode/husky#378]
Hello,
Whenever I rebase and there's a conflict in a package.json, husky crashes when parsing the json. There is no way to get around it, that I have found, other than deleting husky, re-doing the rebase and fixing any conflicts.  It's because of the `<<<<<<< HEAD ...` lines that the rebase adds due to the conflict. 

The error is:
```
Husky > unexpected error { JSONError: Unexpected token < in JSON at position 7409 while parsing near '...****************,<<<<<<< HEAD    "**********.'
```

coming from `/node_modules/husky/node_modules/read-pkg/index.js:35:15`

Any ideas on how to fix or workaround?

**Comment by typicode** [comment]
Hi @brandondoran,

Hmm that's an "interesting" case. Can you try adding `--no-verify` to your git command?

As a workaround, you can also put your hooks in a `.huskyrc` file:

```json
{
  "hooks": {
    "pre-commit": "npm test"
  }
}
```

But I suppose that you'll have the same issue if there's a conflict in `.huskyrc`.

To help working on a fix, could you provide steps to reproduce?

**Comment by brandondoran** [comment]
@typicode thanks for the quick reply. The `.huskyrc` suggestion sounds like it might solve it, at least for my use case. We would rarely, if ever run into a situation where there'd be a conflict in `hooks` but I suppose it could happen.

I ran into the problem on internal projects. But I'll put together a repo to reproduce this issue. Thanks!

**Comment by typicode** [comment]
> But I'll put together a repo to reproduce this issue.

Thanks that would be awesome. But if it's too much, just a few steps or failing git command would be helpful.

**Comment by brandondoran** [comment]
I have not been able to reproduce this again since creating the issue. If I run into it again, I can reopen with an example to reproduce.
