### ISSUE TITLE
How about support plugins?

### ISSUE THREAD

**Issue by poppinlp** [typicode/husky#379]
Hi. Thanks for a pretty nice tool!

I've used this in my work for some days. I find there is something that i need to do in diff projects or repos. So the plugin idea came to me that i could write a plugin and use it in diff projects. But seems husky not support it right now.

In my opinion, the plugin should have ability to register action in any hook and receive arguments like HUSKY_GIT_STDIN, HUSKY_GIT_PARAMS, e.t.c.

Although we could write a CLI bin to do it, but it's a little bit weird when handle arguments. I have made one [husky-plugin-filter-push](https://github.com/poppinlp/husky-plugin-filter-push) which is used in this way:

```json
{
  "hooks": {
    "pre-push": "husky-plugin-filter-push --git $HUSKY_GIT_STDIN --command npm test"
  }
}
```

I think it's better to do it as register a plugin and the config may like this:

```json
{
  "plugins": [
    "filter-push"
  ],
  "hooks": {
    "pre-push": "npm test"
  }
}
```

This is just a preliminary idea. I'm interested in your opinion about this. :)

**Comment by typicode** [comment]
Hi,

Thanks for the suggestion/comment :+1:  and sorry for the lack of reply at the time. I think it's an interesting idea.
That said, with the recent v5, the current direction is more toward scripts and CLI working together.
