### ISSUE TITLE
PR available: add HUSKY_GIT_HOOK environment variable so multi-hook scripts can be used again

### ISSUE THREAD

**Issue by bartvanandel** [typicode/husky#380]
We are using one script for multiple git hooks. Previously we were able to distinguish which hook was being called by looking at `process.env.npm_lifecycle_event`, however since Husky 1.0 doesn't use the script section anymore, this value is no longer present. Husky for sure knows which hook is being called, I suggest this to be added to the environment as `HUSKY_GIT_HOOK` so we can again use multi-purpose hook scripts.

**Comment by bartvanandel** [comment]
@typicode I'm hoping you can look into this within a short time frame. We had to upgrade Husky for a different reason but now our hooks are actually broken :(

**Comment by bartvanandel** [comment]
It would be nice if the maintainer could take a look at this?

**Comment by bartvanandel** [comment]
We are currently using something like the latter. The former isn't portable across platforms without something like crossenv. Having this built-in would be nice but at this moment we can live without it.

Thanks for your reply.

**Comment by typicode** [comment]
Cleaning old issues. 

That said, it should be possible to have a generic way to get hook name with v5 using `basename "$0"`:

```
echo "hook name is $(basename "$0")"
```
