### ISSUE TITLE
Default shell

### ISSUE THREAD

**Issue by Christilut** [typicode/husky#382]
I'm running a Linux command in my `pre-commit` and this works fine on my Linux machine but on my Windows machine it tries to execute the command in cmd/powershell which obviously doesn't work.
I've set my default VSCode shell to WSL (Linux subsystem) but Husky seems to always use CMD.

What determines which shell Husky uses? Or should it be using the VSCode default shell?

**Comment by typicode** [comment]
Sorry, I don't really know :/

Closing as it may have been fixed by newer versions or may not be relevant anymore. Feel free to create another issue if needed.
