### ISSUE TITLE
Errors when no package.json is present (e.g. in a gh-pages branch)

### ISSUE THREAD

**Issue by matatk** [typicode/husky#387]
I've been using Husky for a while; it's very helpful, thanks.

Recently I upgraded to 1.1 and have found that when I want to switch to my "gh-pages" branch (which does not contain a "package.json" file) Husky complains that it can't find "package.json". This stops me from being able to run some scripts that I need to on my gh-pages branch, as they check out the latest README changes from "master" and apply them to "gh-pages", but the Husky errors are interrupting the script. On "master" I have only a "precommit" hook specified in "package.json".

The error message is of the form

    Husky > unexpected error { Error: ENOENT: no such file or directory, open '/path/to/package.json'

Is this behaviour by design? If so, is it possible to opt out, at least for certain branches?

**Comment by typicode** [comment]
Thanks for the report. It's a bug, I'll see what can be done.

**Comment by typicode** [comment]
@bk201- Thanks for the PR. I went with the try/catch approach instead as it was easier to add a test for.
@matatk `1.1.3` should fix this issue
