### ISSUE TITLE
How do I use husky globally?

### ISSUE THREAD

**Issue by harsh-tamr** [typicode/husky#388]
I want to use husky in a shared repo where other's don't want to use husky. How do I enable husky as a feature flag. I tried linking husky@1 and it didn't work.

**Comment by orta** [comment]
Husky has a [disable](https://github.com/typicode/husky/blob/6fd89e8fccf6ca7590743cd8b4ce9643de7091e5/DOCS.md#disable-auto-install) env var. But maybe what you want to to add a feature where this behavior could be the opposite?

**Comment by bm-stschneider** [comment]
I share the same problem. I have husky globally installed but the hook can't find it.
`Can't find Husky, skipping pre-commit hook
You can reinstall it using 'npm install husky --save-dev' or delete this hook`

**Comment by typicode** [comment]
Husky 5 doesn't automatically install Git hooks anymore. So it should now be possible to have it installed on a per-developer basis.
Thanks for the feedback.
