### ISSUE TITLE
husky with sourcetree : Can't find node in PATH, trying to find a node binary on your system

### ISSUE THREAD

**Issue by zhaozhe0831** [typicode/husky#390]
I'm trying to use husky precommit with sourcetree. The precommit command is run but i get the following error:

![image](https://user-images.githubusercontent.com/12945873/47774142-22ac9980-dd27-11e8-9a62-d236d928f9b4.png)

Does anybody know what's wrong? I'm using n.

OS: macOS Mojave 10.14
Node: 10.13
`$ which node`: /usr/local/bin/node
npm: 6.4.1
`$ whick npm`: /usr/local/bin/npm

![image](https://user-images.githubusercontent.com/12945873/47775421-943a1700-dd2a-11e8-8ff7-0f487979fb6e.png)

**Comment by zhaozhe0831** [comment]
@zhaozhe0831 I have same problem when I switch 8.12.0 with `n`.

**Comment by typicode** [comment]
It's actually not an error, just an information message. But it may sound like an error, especially as the output is red.

Node version managers works by modifying the PATH when the terminal is started. GUI clients usually don't work well with version managers as they don't source .bashrc or .zshrc where version managers are usually initialized.

So this message is just to let you know that husky will go into a mode where it'll try to find a Node binary (it uses [run-node](https://github.com/sindresorhus/run-node) for that).

Here's more documentation
https://github.com/typicode/husky/blob/master/DOCS.md#node-version-management

**Comment by AdeOpe** [comment]
me too

![image](https://user-images.githubusercontent.com/5416277/50173000-39ff1080-02ee-11e9-8521-cde4419a5d04.png)

**Comment by mdversion01** [comment]
This is an error. If I get this:
![image](https://user-images.githubusercontent.com/3177287/54857075-e7116c80-4cd3-11e9-906d-9e043c465ff1.png)
in Sourcetree, it's doesn't commit. 
Has anyone figured out a solution?

**Comment by fabb** [comment]
You need to set your system-wide node version to 8 or higher:
```
nvm alias default 8
```

**Comment by mdversion01** [comment]
my default is 
```
default -> 8 (-> v8.11.3)
```
But I still get the same thing above when trying to commit with Sourcetree.

**Comment by mdversion01** [comment]
I found somewhat of a reason/solution for the issue with Sourcetree. All of my dependencies are current, node, husky, lint-staged and no solution works but this,

https://stackoverflow.com/questions/52754063/git-push-failed-due-to-husky-pre-push-on-sourcetree

**Comment by thoqbk** [comment]
In my MAC, I fixed this by:
1. Check Node path:
```shell
which node
/usr/local/bin/node
```
2. Update `~/.bash_profile`:
```shell
# ...
export PATH="/usr/local/bin:$PATH"
```

**Comment by bitclaw** [comment]
I had the same issue with Webstorm. If anyone is using fnm, then the command to fix it would be:

`fnm default 12.10.0`

**Comment by spacecakes** [comment]
This happens to me in Visual Studio Code if there's an linting error in the code, which we take care of in the pre-commit hook. vscode will display 
>`Info: can't find node in PATH, trying to find a node binary on your system` 
in a pop up, even though it isn't the actual error, making it confusing for people to see what the real problem is (unless they check the output log).

If the commit goes through, there's no popup. Does anyone have an idea how I can get vscode to display the actual error instead of this?

**Comment by sainnr** [comment]
I was experiencing this error with NVM & WebStorm (while everything was fine from the Ubuntu terminal). 

In a nutshell, it's just a path problem with NPM & GUI vs terminal as @typicode [suggests](https://github.com/typicode/husky/issues/390#issuecomment-436966021). In my case, I ended up configuring `~/.huskyrc` as suggested in [docs](https://github.com/typicode/husky#local-commands-huskyrc), to make sure it effectively uses NVM:

```
# ~/.huskyrc
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
```

**Comment by zkrige** [comment]
@sainnr solution worked for me on Catalina/zsh

**Comment by valeriopisapia** [comment]
The last one works for me as well

**Comment by crgeee** [comment]
thank you @sainnr

**Comment by mohammadalipak** [comment]
on my mac Mojave, I fixed this by:

Check Node path:
```
which node
/usr/local/bin/node
```

Add this path to the globals PATHs:
```
sudo vi /etc/paths.d/local_bin
```
enter edit mode by typing `i` then type this into the file:
```
/usr/local/bin
```
and save it `esc wq enter`

**Comment by crespowang** [comment]
I have the same problem, then I launched SourceTree from terminal, then it worked! First you need to make sure you have **stree** cli installed.
![image](https://user-images.githubusercontent.com/25573589/72866614-1481d900-3d30-11ea-9d17-952db5e1bf1d.png)
Then from your terminal run **stree** it works for me!

**Comment by alexilyaev** [comment]
I opened a related issue on the SourceTree Jira:
https://jira.atlassian.com/browse/SRCTREE-7184

Basically the same issue with the PATH not including `/usr/local/bin`.
Please up vote.

**Comment by claudioviola** [comment]
```
export NVM_DIR="$HOME/.nvm"
source ~/.nvm/nvm.sh
```

I simply added this in my bash_profile and it works

**Comment by ogelacinyc** [comment]
It works for me. My machine is macOS mojave 10.14.6(18G2022)
I use bash shell.
```
# ~/.huskyrc
export PATH="/usr/local/bin/:$PATH"
```

```
$ which node
/usr/local/bin/node

$ which yarn
/usr/local/bin/yarn
```

**Comment by bobrosoft** [comment]
If you're using macOS and NVM, then that's the proper solution: just create `.huskyrc` in your `~` home directory with next content:
```
#!/usr/bin/env bash

source ~/.bash_profile

if test -f ".nvmrc"; then
    nvm use
fi
```
NOTE: it using your .bash_profile where NVM initialization should be already defined earlier when you installed NVM. I.e. next
```
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
```

**Comment by tenadolanter** [comment]
> Switching to husky 3.1.0 (which uses run-node) also worked for me

https://github.com/typicode/husky/issues/639

**Comment by doup** [comment]
In my case @sainnr solution (https://github.com/typicode/husky/issues/390#issuecomment-545855628) was almost there, I was missing `nvm use` after initializing NVM, like so:

```sh
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
nvm use
```

**Comment by thelpbogeyman** [comment]
This worked for me (and other Git apps that were having issues). This is on a Mac.
`# HUSKY_SKIP_HOOKS=1 open -a "SourceTree"`

**Comment by tr1stan** [comment]
> This worked for me (and other Git apps that were having issues). This is on a Mac.
> `# HUSKY_SKIP_HOOKS=1 open -a "SourceTree"`

This doesn't solve the issue though, it just stops the hooks from firing altogether.

+1 for downgrading to `3.1.0` so that team members who might use a GUI don't need extra setup.

**Comment by ShoshoWang** [comment]
Hi, guys, I met the same issue, here is how I fix it.

1.firstly, this is about the Node path problem, I try to change my .bash_profile, but it does still not work, so I installed "nvm"

Two ways to install 
`curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash
`
or
`wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash`

2. as mentioned above, if you can not install nvm, you can download the` install.sh` file and execute it  to install

3.after finished step 3 you can input 'nvm ls' in your terminal if you can successfully use this command, you can skip stepping 5, if you still can not use 'nvm command', skip stepping 4

4. add to your  .bash_profile  
```
export NVM_DIR="/Users/magicdawn/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
```
then update 
` source .bash_profile`
 
5. in your terminal, then fix this issue
nvm install v12

**Comment by bypatryk** [comment]
I've spent some time figuring it out. Here's a fix that should work in any situation, though I tested it only on MacOS Big Sur with node installed via `nvm`. But it should work no matter how you installed your node.

## Issue
The thing is that SourceTree git hooks run within "clean" context and we need to add our node directory into that context. Husky enables that to us, as [it runs `~/.huskyrc`](https://github.com/typicode/husky/blob/next/scripts/husky.sh#L15-L18) before executing any node-related commands. But we need to create this file first.

## Solution
Run:
```
echo "export PATH=\"$(dirname $(which node)):\$PATH\"" > ~/.huskyrc
```
This will create `~/.huskyrc` file, which will add your node directory to `PATH`. Some explanation to this command (as bash scripts usually look like black magic to front-end devs):

- `which node` yields path from which `node` is being fired, in my case `/Users/myusername/.nvm/versions/node/v15.4.0/bin/node`
- `dirname $(which node)` yields directory from that path, in my case `/Users/myusername/.nvm/versions/node/v15.4.0/bin`
- `echo "export PATH=\"$(dirname $(which node)):\$PATH\""` just prints out:
```
export PATH="/Users/myusername/.nvm/versions/node/v15.4.0/bin:$PATH"
```
- `> ~/.huskyrc` that part takes what has been printed out and saves it into a file `~/.huskyrc`

**Comment by typicode** [comment]
Closing as many solutions have been provided (thank you! :+1: )

See also https://typicode.github.io/husky/#/?id=command-not-found (works for v4 and v5)

**Comment by Legys** [comment]
None of the solutions worked for me.
Open `.git/hooks/pre-commit`,

**Comment by chuyik** [comment]
Hey folks, I've forked husky v4 to fix this problem, please give it a try if needed.
Repo: https://github.com/chuyik/husky
Package: @chuyik/husky

**Comment by tiagosiebler** [comment]
> If you're using macOS and NVM, then that's the proper solution: just create `.huskyrc` in your `~` home directory with next content:
> 
> ```
> #!/usr/bin/env bash
> 
> source ~/.bash_profile
> 
> if test -f ".nvmrc"; then
>     nvm use
> fi
> ```
> 
> NOTE: it using your .bash_profile where NVM initialization should be already defined earlier when you installed NVM. I.e. next should be there already:
> 
> ```
> export NVM_DIR="$HOME/.nvm"
> [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
> ```

Thank you! This worked to resolve this with sourcetree on Mac!

**Comment by appsparkler** [comment]
After executing `npx husky install .config/husky` from the terminal; the errors resolved for me.

**Comment by kirillgroshkov** [comment]
This comment made it work for me! https://github.com/typicode/husky/issues/390#issuecomment-577008221

**Comment by daviddunndiscovery** [comment]
> After executing `npx husky install .config/husky` from the terminal; the errors resolved for me.

this worked for me 🕺

**Comment by Aisen60** [comment]
work for me https://github.com/typicode/husky/issues/390#issuecomment-762213421

**Comment by kirillgroshkov** [comment]
BTW, SourceTree just released a new version on 2021-08-23 that fixes this issue for me! Now it works regardless if I open SourceTree via command line or via Application icon.

**Comment by wvddrss** [comment]
@daviddunndiscovery I love you!! Searched for this issue for ages.

**Comment by wvddrss** [comment]
> > After executing `npx husky install .config/husky` from the terminal; the errors resolved for me.
> 
> this worked for me 🕺

When I do that it bypasses the precommit. and it couldnt find node in terminal..

**Comment by Kaicha** [comment]
> After executing `npx husky install .config/husky` from the terminal; the errors resolved for me.

This worked for me too.

**Comment by alexventuraio** [comment]
In my case:

- Mac with Apple M1 chip
- `yarn` installed with homebrew
- Using NVM loaded as a [Oh My Zsh plugin](https://github.com/lukechilds/zsh-nvm#as-an-oh-my-zsh-custom-plugin)

This was the error I was getting and this is the way I fixed and make it work:

![Screen Shot 2022-03-29 at 14 16 48](https://user-images.githubusercontent.com/13169164/160699392-6d53d287-2518-411d-ba92-6ac8e12ee1cf.png)


### Solution

- Create `~/.huskyrc` file in my home directory
- With this content:
```sh
# Load Yarn command coming from homebrew
export PATH="/opt/homebrew/bin/:$PATH"

# This loads nvm.sh and sets the correct PATH before running hook
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

nvm use default
```

**Comment by craigwheeler** [comment]
The problem appears to be related to using nvm and changing node versions since after I switched versions I was unable to commit anything, however, opening Sourcetree from the terminal works for me...

`open /Applications/SourceTree.app/Contents/MacOS/SourceTree`

**Comment by ladytellur** [comment]
I faced the similar issue.
Mac + Sourcetree + husky stuck with using an old node version installed via nvm ignoring the new nvm default node version
Once I deleted that old node version I get `npx` not found error (because PATH contained the path to an old node version still)

The problem was that another program had added PATH changes to ~/.zshrc (.bashrc if you use it)
The solution was to move the nvm setup to the bottom of .zshrc (.bashrc)

Problem
```
# NVM initialisation
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm

# Some other program adding to the PATH:
export PATH="$ANT_ROOT:$PATH"
```
Solution
```
# Some other program adding to the PATH:
export PATH="$ANT_ROOT:$PATH"

# NVM initialisation
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
```
[stackoverflow](https://stackoverflow.com/a/47883587/2330836)
