### ISSUE TITLE
How are devinstall and devuninstall scripts being used?

### ISSUE THREAD

**Issue by dv29** [typicode/husky#392]
I am trying to reuse husky for other projects (not just config file), building a lib of sorts that will be used by all other projects.
I cannot understand how and when devinstall and devuninstall scripts are executed during installs. Cannot find any documentation either on npmjs.com.
Can someone help understand when this are getting executed please?

**Comment by typicode** [comment]
Hi @dv29,

devinstall and devuninstall are just internal commands used to install git hooks in the CI and when developing husky.

It's not possible to reuse husky this way, sorry about that. What would be your use case/ what do you try to solve?

**Comment by dv29** [comment]
Hi @typicode,
So I am trying to build a reusable library across our node stack that has all liniting, bundling, testing and everthing that dev's require to build the project and work effectively.
What I wanted to do was use husky and add the hooks when this library that I created is installed and use the config from this library and not the per project.

Can you explain when and how are the hooks being added to .git, at what npm lifecycle event please?

**Comment by dv29** [comment]
I have an idea how to do that with husky, I mean I know what husky would require to make that possible, but I dont get at what point is husky adding the hooks during install

**Comment by dv29** [comment]
Nevermin, found it. there is `install` script in the packaged/published version of the package.
