### ISSUE TITLE
Husky didn't cancel commit

### ISSUE THREAD

**Issue by Thisman** [typicode/husky#394]
Try to install precommit hook by husky.

.haskyrc:
```
{
  "hooks": {
    "pre-commit": "npm run lint"
  }
}
```

package.json:
```
"lint": "tslint -c tslint.json src/**/*.ts"`
```

`tslint` failed with status code 2, i see message:
```
husky > pre-commit hook failed (add --no-verify to bypass)
```
but commit didn't canceled

**Comment by fleboulch** [comment]
You can use `lint-staged` npm package. I think it could fix your issue.

In package.json
```
"lint-staged": "8.0.4"
```
In .huskyrc
```
{
  "hooks": {
     "pre-commit": "lint-staged"
  }
}
```

**Comment by Thisman** [comment]
@fleboulch thanks for answer. I will try!

**Comment by typicode** [comment]
@Thisman closing, feel free to re-open if you still have the issue

@fleboulch thanks for the help :)
