### ISSUE TITLE
Case-sensitivity issue on install (Windows / Git)

### ISSUE THREAD

**Issue by JoshSchreuder** [typicode/husky#401]
This is a weird, I think specifically Windows issue, so bear with me.

Depending on how I run `npm install` two slightly different hooks get installed, specifically related to `scriptPath`. This causes subtle failures when doing git operations like `git add`.

For example, if I have a directory called `myDir`, on Windows, this can also be accessed at `mydir` as Windows dirs are case-insensitive.

Depending on which one is my working directory when `npm install` is called, I may get:

`scriptPath="myDir/node_modules/husky/run.js"`
or
`scriptPath="mydir/node_modules/husky/run.js"`

Then when the hook runs, my file paths end up being, for example:

`myDir/myfile.js`
or
`mydir/myfile.js`

Neither Prettier nor ESLint for example care about these paths being different, they will happily work both ways. However, git paths are case-sensitive, so `git add mydir/myfile.js` when my directory is actually called `myDir` will cause `git add` to add nothing.

I don't know if this is specifically a problem you wish to solve with Husky, or whether it's more of a me problem :)

**Comment by typicode** [comment]
Hi @JoshSchreuder,

Not sure how to test it. Also using mostly Node `path` API to abstract OS.
Would you have some minimal steps I could do to reproduce on Windows?

**Comment by typicode** [comment]
Closing but feel free to reopen the issue if needed.
