### ISSUE TITLE
Gets stuck on jest watch usage options

### ISSUE THREAD

**Issue by biancajemsten** [typicode/husky#402]
I'm using husky to run jest tests in a create react app. The tests work fine using npm test but when run in a pre-commit hook the terminal gets stuck on the "Watch" options. Nothing happens when clicking any of the keys for the options.  Subsequently no code gets committed. What could the issue be? 

<img width="1014" alt="screen shot 2018-11-20 at 11 14 34" src="https://user-images.githubusercontent.com/37228766/48770230-88040280-ecb5-11e8-8c68-5a7fe188b7d3.png">

This is the package.json content: 

```json
{
  "name": "my-app",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@material-ui/core": "^3.2.2",
    "@material-ui/icons": "^3.0.1",
    "@types/jest": "^23.3.9",
    "@types/node": "^10.12.2",
    "@types/react": "^16.4.18",
    "@types/react-dom": "^16.0.9",
    "@types/react-router-dom": "^4.3.1",
    "@types/react-select": "^2.0.6",
    "enzyme-to-json": "^3.3.4",
    "lodash": "^4.17.11",
    "react": "^16.6.3",
    "react-dom": "^16.6.3",
    "react-ga": "^2.5.3",
    "react-router-dom": "^4.3.1",
    "react-scripts": "2.1.1",
    "ts-loader": "^5.3.0"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --watchAll",
    "eject": "react-scripts eject"
  },
  "devDependencies": {
    "enzyme": "^3.7.0",
    "enzyme-adapter-react-16": "^1.7.0",
    "husky": "^1.1.4",
    "prettier": "1.13.6",
    "react-test-renderer": "^16.4.2",
    "tslint": "^5.11.0",
    "tslint-config-prettier": "^1.16.0",
    "tslint-react": "^3.6.0",
    "typescript": "^3.1.6"
  },
  "tslintConfig": {
    "extends": "react-app"
  },
  "browserslist": [
    ">0.2%",
    "not dead",
    "not ie <= 11",
    "not op_mini all"
  ],
  "jest": {
    "snapshotSerializers": [
      "enzyme-to-json/serializer"
    ]
  },
  "husky": {
    "hooks": {
      "pre-commit": "npm test",
      "pre-push": "npm test",
      "...": "..."
    }
  }
}
```

**Comment by typicode** [comment]
Hi @biancajemsten,

Scripts run by husky need to exit so that the hook fails or succeeds. The issue here is that in watch mode `test` script never exits.

Personally, I would change `scripts`  field to something like this:

```
"test": "react-scripts test",
"test:watch": "react-scripts test --watchAll"
```

And run tests in development with `npm run test:watch`

`"...": "..."`  can also be removed, it was just to show that other hooks can be added.

**Comment by uxitten** [comment]
@typicode hi, with your way is not solve problem

**Comment by HugoLiconV** [comment]
I'm having the same issue

**Comment by sanchezcarlos1986** [comment]
Try this:

`"husky": {
    "hooks": {
      "pre-commit": "CI=true react-scripts test"
    }
  }`

**Comment by uxitten** [comment]
@sanchezcarlos1986 it's great, worked

**Comment by gmbwa** [comment]
I reckon this needs to be in the readme

**Comment by komarovalexander** [comment]
> Try this:
> 
> `"husky": { "hooks": { "pre-commit": "CI=true react-scripts test" } }`

In case of pre-push this solution does not work:

_husky > pre-push (node v12.5.0)
'CI' is not recognized as an internal or external command,
operable program or batch file.
_husky > pre-push hook failed (add --no-verify to bypass)__

Is there any way to fix it?

**Comment by diglopes** [comment]
> Hi @biancajemsten,
> 
> Scripts run by husky need to exit so that the hook fails or succeeds. The issue here is that in watch mode `test` script never exits.
> 
> Personally, I would change `scripts` field to something like this:
> 
> ```
> "test": "react-scripts test",
> "test:watch": "react-scripts test --watchAll"
> ```
> 
> And run tests in development with `npm run test:watch`
> 
> `"...": "..."` can also be removed, it was just to show that other hooks can be added.

You can add the flag --forceExit on your script
