### ISSUE TITLE
submodule commit not work

### ISSUE THREAD

**Issue by yoyo837** [typicode/husky#404]
root package.json:
```
  "husky": {
    "hooks": {
      "pre-commit": "npm run lint"
    }
  }
```

**Comment by typicode** [comment]
Hi @yoyo837,

Thanks for the report. Actually Husky should support submodule. There's a test here, you can check the directory layout and expectations:
https://github.com/typicode/husky/blob/master/DOCS.md#access-git-params-and-stdin

Can you provide the logs when running `git commit`?
Would you have some minimal reproduction steps for your issue?

**Comment by yoyo837** [comment]
> Can you provide the logs when running git commit?
```
> git add -A -- .
> git commit --quiet --allow-empty-message --file - --all
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse 新课程
> git rev-parse --symbolic-full-name 新课程@{u}
> git rev-list --left-right 新课程...refs/remotes/origin/新课程
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse 新课程
> git rev-parse --symbolic-full-name 新课程@{u}
> git rev-list --left-right 新课程...refs/remotes/origin/新课程
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git show :course/_dataId/study.vue
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse 新课程
> git rev-parse --symbolic-full-name 新课程@{u}
> git rev-list --left-right 新课程...refs/remotes/origin/新课程
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose

```

> Would you have some minimal reproduction steps for your issue?

Of course, if you really need that, I will prepare one.

**Comment by typicode** [comment]
Thanks for the logs.

Just the commands would be sufficient something like:

```
git init
mkdir ...
# commands to create the submodule...
npm init -y
npm install husky --save-dev
# anything else before testing the pre-commit hook...
git commit -m test 
```

Or alternatively, the layout of your project. Where is your package.json? Where is the `.git` file from your submodule and what's it's content?

Sorry, I didn't put the correct link for the test (going to update the previous comment) here it is:
https://github.com/typicode/husky/blob/master/src/installer/__tests__/index.ts#L165-L168

**Comment by yoyo837** [comment]
directory:
```
.
+-- .git
+-- pages(submodule)
|   +-- .git
|   +-- package.json
+-- package.json (pre-commit hook)
```

```json
  "husky": {
    "hooks": {
      "pre-commit": "npm run lint"
    }
  }
```

**Comment by yoyo837** [comment]
submodule .git:

```
tanghuideMacBook-Pro:.git tanghui$ ls -ls
total 104
 8 -rw-r--r--    1 tanghui  staff     16 12  4 09:43 COMMIT_EDITMSG
 8 -rw-r--r--    1 tanghui  staff   1635 12  4 09:57 FETCH_HEAD
 8 -rw-r--r--    1 tanghui  staff     26 12  3 09:49 HEAD
 8 -rw-r--r--    1 tanghui  staff     41 11 29 15:51 ORIG_HEAD
 0 drwxr-xr-x    2 tanghui  staff     64  8  1 19:55 branches
 8 -rw-r--r--    1 tanghui  staff    996 11 28 18:08 config
 8 -rw-r--r--    1 tanghui  staff     73  8  1 19:55 description
 0 drwxr-xr-x   13 tanghui  staff    416  8  1 19:55 hooks
40 -rw-r--r--    1 tanghui  staff  20030 12  4 09:43 index
 0 drwxr-xr-x    3 tanghui  staff     96  8  1 19:55 info
 0 drwxr-xr-x    4 tanghui  staff    128  8  1 19:55 logs
 0 drwxr-xr-x  259 tanghui  staff   8288 11 30 17:56 objects
 8 -rw-r--r--    1 tanghui  staff    831  8  1 19:55 packed-refs
 0 drwxr-xr-x    5 tanghui  staff    160  8  1 19:55 refs
 8 -rw-r--r--@   1 tanghui  staff    174 12  4 09:31 sourcetreeconfig
```

**Comment by yoyo837** [comment]
My case: git commit is executed under submodule repo, not root repo.

**Comment by mrbone** [comment]
your case should not work, because you only add husky at the root level,  if you wanna husky works in every submouldes.
you should run `yarn add husky --dev` or `npm i husky --save-dev` in every submodule manually.

**Comment by skateborden** [comment]
@yoyo837 Did you get this to work?

In my case the submodule is a build of the main repo, so I want to run the tests on the main repo source before allowing a commit in the build submodule.

**Comment by waterplea** [comment]
I have this config in my `package.json`:
```
    "husky": {
        "hooks": {
            "pre-commit": "lint-staged"
        }
    },
    "lint-staged": {
        "linters": {
            "*.{js,ts,html,md,less,json}": [
                "prettier --write",
                "git add"
            ],
            "*.ts": "tslint --fix",
            "*.less": "stylelint"
        }
    },
```
I have this config in both submodule and main module. I work in root project. If I commit something to submodule only — husky does not run the hook. Neither of the hooks. Is there something I can do? Tried it on husky 4.3.8

**Comment by sdqyang** [comment]
use husky 3.1.0 can solve，6.0.0 the .git like this 
![image](https://user-images.githubusercontent.com/5997041/115875920-4e341900-a478-11eb-9ce0-011bd68a18e7.png)
and 3.10
![image](https://user-images.githubusercontent.com/5997041/115875959-58eeae00-a478-11eb-9548-8043cf009eb9.png)

**Comment by pengliheng** [comment]
> I have this config in my `package.json`:
> 
> ```
>     "husky": {
>         "hooks": {
>             "pre-commit": "lint-staged"
>         }
>     },
>     "lint-staged": {
>         "linters": {
>             "*.{js,ts,html,md,less,json}": [
>                 "prettier --write",
>                 "git add"
>             ],
>             "*.ts": "tslint --fix",
>             "*.less": "stylelint"
>         }
>     },
> ```
> 
> I have this config in both submodule and main module. I work in root project. If I commit something to submodule only — husky does not run the hook. Neither of the hooks. Is there something I can do? Tried it on husky 4.3.8

run it `"postinstall": "(export GIT_DIR=$(cd react_native/cimb_src && git rev-parse --git-dir) ; test -f $GIT_DIR/hooks/pre-commit || node node_modules/husky/husky.js install)"`
