### ISSUE TITLE
Clean out GIT_ variables before running hook commands

### ISSUE THREAD

**Issue by docwhat** [typicode/husky#405]
Story:

I couldn't make my tests pass via husky because a bunch of `GIT_` variables are set (by `git` itself, not husky).

It was driving me nuts because it wasn't obvious what was going on and I could only reproduce it via the pre-commit hook & husky.

Suggestion:

Remove all the `GIT_` variables _before_ running the hook(s).  Or possibly rename them to `HUSKY_HOOK_GIT_...` instead.

At the very least, hopefully this issue will help someone in the future.

**Comment by typicode** [comment]
Hi @docwhat,

Thanks for the feedback. Do you remember which `GIT_` variables were causing issues?

**Comment by docwhat** [comment]
All of them?  The author and committor ones in particular were messing up my tests; but others could have too

I create Git repositories to test my Git repo analytics library. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
