### ISSUE TITLE
No hooks running with version 1.2.0

### ISSUE THREAD

**Issue by madcapper2** [typicode/husky#408]
I have 2 issues that might be really just 1 issue.  The first is that if I run .git/hook/pre-commit, nothing appears to happen.  If I then go run that same command by double clicking on it in Finder, then it runs a process but I'm told that it can't find Husky.
```
Can't find Husky, skipping pre-commit hook
You can reinstall it using 'npm install husky --save-dev' or delete this hook
```
This might have something to do with my directory structure:
       Main directory where git lives
           -subA
           -subB: where Husky is installed and the package.json lives

My pre-commit hook looks like:
```
#!/bin/sh
# husky

# Hook created by Husky
#   Version: 1.2.0
#   At: 2018-11-26 20:01:31
#   See: https://github.com/typicode/husky#readme

# From npm package
#   Name: husky
#   Directory: /Users/me/workspaces/mainDirectory/subB/node_modules/husky
#   Homepage: https://github.com/typicode/husky#readme

scriptPath="subB/node_modules/husky/run.js"
hookName=`basename "$0"`
gitParams="$*"

debug() {
  [ "${HUSKY_DEBUG}" = "true" ] && echo "husky:debug $1"
}

debug "$hookName hook started..."

if ! command -v node >/dev/null 2>&1; then
  echo "Can't find node in PATH, trying to find a node binary on your system"
fi

if [ -f $scriptPath ]; then
  if [ -f ~/.huskyrc ]; then
    debug "source ~/.huskyrc"
    source ~/.huskyrc
  fi
  subB/node_modules/run-node/run-node $scriptPath $hookName "$gitParams"
else
  echo "Can't find Husky, skipping $hookName hook"
  echo "You can reinstall it using 'npm install husky --save-dev' or delete this hook"
fi
```

Any help would be greatly appreciated.

**Comment by typicode** [comment]
Hi @madcapper2,

> If I then go run that same command by double clicking on it in Finder, then it runs a process but I'm told that it can't find Husky.

I suppose that the current working directory in this case is `.git/hooks`, and so when it looks for `scriptPath`, it's actually `.git/hooks/subB/node_modules/husky/run.js` in this context.

> The first is that if I run .git/hook/pre-commit, nothing appears to happen. 

If you run `HUSKY_DEBUG=true git commit ...` do you get `pre-commit hook started...` message?
If yes, then I would check the associated hook script in `package.json` or `.huskyrc`?

**Comment by madcapper2** [comment]
@typicode, 
  Thanks for the quick reply.  I ran with the `HUSKY_DEBUG=true` on the commit and I see the following output:
```
husky:debug pre-commit hook started...
husky:debug prepare-commit-msg hook started...
husky:debug commit-msg hook started...
husky:debug post-commit hook started...
```

I added some additional echos out and the command that it calls to do `subB/node_modules/run-node/run-node $scriptPath $hookName "$gitParams"`  looks like `subB/node_modules/run-node/run-node subB/node_modules/husky/run.js pre-commit `.   

My package.json looks like:
```
"scripts": {
       "test-check": "ng test --watch=false --browsers=ChromeHeadless --reporters=mocha --sourceMap=false",
        "husky": {
            "hooks": {
                "post-commit": "git update-index -g",
                "pre-commit": "lint-staged && npm run test-check"
            }
        },
        "lint-staged": {
            "*.{js,ts,scss,json}": [
                "prettier --write",
                "git add"
            ]
        },
}
```

I'm not sure if this is a setup problem or a directory issue.  Thanks again for helping.

**Comment by vnnnt** [comment]
Probably a bad copy-paste. Husky and lint-staged shouldn’t be in “scripts” field.

**Comment by madcapper2** [comment]
This was a setup issue in the package.json.  The husky and lint-staged should NOT be in the scripts section of the file.
