### ISSUE TITLE
Remove hard dependency on NPM and allow for other package managers

### ISSUE THREAD

**Issue by cozuya** [typicode/husky#409]
I'm somehow running a node app with only Yarn - NPM is not installed.  I'm not quite sure how I pulled that off.. 🤔 Anyways, husky does not work without NPM, gives a cryptic message, and skips all hooks.

**Comment by typicode** [comment]
Hi @cozuya, you should give a try to Husky `v1`. The dependency has been removed and you can use it with npm, yarn or pnpm.

Check https://github.com/typicode/husky#upgrading-from-014 for upgrading.

**Comment by cozuya** [comment]
😑 Sorry about that, realized that I was using Husky v1 at work and Husky less than v1 at home on a different project.  Thanks for the great package!

**Comment by typicode** [comment]
No worries, thanks :)
