### ISSUE TITLE
problem with hoosk when add new page

### ISSUE THREAD

**Issue by DevRMahdi** [typicode/husky#410]
Hi ,
I have a problem with Hoosk CMS
when i added a **new page** it give me **that error**

> A Database Error Occurred
> Error Number: 1364
> 
> Field 'pageParent' doesn't have a default value
> 
> INSERT INTO `hoosk_page_attributes` (`pagePublished`, `pageTemplate`, `pageURL`) VALUES ('1', 'page', 'thisisalopage')
> 
> Filename: C:/wamp/www/Hoosk/hoosk/hoosk0/models/Hoosk_model.php
> 
> Line Number: 228
>

**Comment by typicode** [comment]
Hi @DevRMahdi,

Doesn't seem related to Husky, I think you created the issue in the wrong project :)

**Comment by DevRMahdi** [comment]
Hi @typicode 
 Ahhh Yes Sorry 
Thank you

**Comment by DevRMahdi** [comment]
> Hi @typicode
> Ahhh Yes Sorry
> Thank you

Yes sorry
