### ISSUE TITLE
environment $HUSKY_GIT_PARAMS not displaying values

### ISSUE THREAD

**Issue by latel** [typicode/husky#411]
here for me, husky kept displaying the raw string rather than execute the command

.huskyrc.js
```
module.exports = {
  "hooks": {
    "pre-commit": "echo $HUSKY_GIT_PARAMS && exit 1"
  }
}
```

shell
```
$ git commit -m test --allow-empty
husky > pre-commit (node v11.3.0)
$HUSKY_GIT_PARAMS 
husky > pre-commit hook failed (add --no-verify to bypass)
```

**Comment by tanhauhau** [comment]
which version of husky are you using?

**Comment by latel** [comment]
> which version of husky are you using?

$ npm ls|grep husky
+-- husky@1.2.0

**Comment by Fandekasp** [comment]
I downgraded husky, testing all versions up to v0.15.0-rc.13 , and none could output anything with the command above. Doesn't seem to be a problem related to the version, or that's a bug that's been going on for a long time..

**Comment by Fandekasp** [comment]
oh. seems like pre-commit doesn't return anything, but commit-msg returns `.git/COMMIT_EDITMSG`

**Comment by typicode** [comment]
Closing as it's an old issue and the problem may have been fixed with most recent v4 or v5.
