### ISSUE TITLE
Warnings are not considering for Angular TSLint 

### ISSUE THREAD

**Issue by rajeeshivam** [typicode/husky#416]
Hi,

Problem:
I have configured precommit hook for my Angular application with TSLint static analysis tool. But this catch and block only the Errors and not blocking my commit if any Warning are found by TSLint

Expected Behavior:
Pre commit should be able to block Warnings also, If find any

Current Behavior:
Developers are able to commit their code if Warnings are also found by TSLint

Thanks,
Rajeesh

**Comment by typicode** [comment]
Hi Rajeesh,

I think this behavior is normal. Warnings don’t make tslint fail and exit with a code different than 0 (hooks are stopped when command exits with code >0).

See Exit Code section https://palantir.github.io/tslint/usage/cli/

Personally I would change the severity of the rules to error if they need to make the hook fail. You can also apply a global severity I think.
