### ISSUE TITLE
Husky fails to install hooks in sub-repositories with Yarn workspaces

### ISSUE THREAD

**Issue by ma2ciek** [typicode/husky#417]
With the given structure of projects:

```
main-project/
	.git/
	node_modules/
	packages/
		project-a/
			.git/
			node_modules/
			src/
			package.json
		project-b/
			.git/
			node_modules/
			src/
			package.json
	src/
	package.json
```

and 

```js
// main-project/package.json
{
	workspaces: [ 'packages/*' ],
	"dependencies": {
		"project-a": "*",
		"project-b": "*",
		"husky": "^1.2.0"
	}
}
```

and 

```js
// project-a/package.json, project-b/package.json
{
	"dependencies": {
		"husky": "^1.2.0"
	}
}
```

...it's impossible to install husky hooks in the sub-repositories. Husky is being installed only once in the main project's `node_modules` and since every sub-repository contains own `.git` directory commits from sub-repositories don't trigger Husky's hooks.

I'm actually don't know how to solve it and whether it's a `yarn` workspaces' bug, `husky`'s bug or if that combination actually just won't work.

The simple workaround I've found is to add a different version of `husky` to the root package and a different to the sub-packages. But that feels like a hack and it can accidentally break after bumping up deps.

**Comment by AJIh** [comment]
`husky` doesn't adapt monorepo environment. You will have to add `husky` into [nohoist](https://yarnpkg.com/blog/2018/02/15/nohoist/) array of yarn's workspace config.

**Comment by ma2ciek** [comment]
Your solution works, thanks!

**Comment by dgesteves** [comment]
hey @ajihyf how can i do that?

**Comment by cinan** [comment]
> `husky` doesn't adapt monorepo environment. You will have to add `husky` into [nohoist](https://yarnpkg.com/blog/2018/02/15/nohoist/) array of yarn's workspace config.

this should be mentioned in readme, big thank-you!



> hey @ajihyf how can i do that?

example is here https://classic.yarnpkg.com/blog/2018/02/15/nohoist/
