### ISSUE TITLE
Husky log nothing when pre-push fail with commitlint

### ISSUE THREAD

**Issue by riderx** [typicode/husky#418]
Since i added commitlint, husky hide the log of it in the git debug console of vscode when using git push function of VSCODE.
<img width="1248" alt="screenshot 2018-12-07 at 15 06 19" src="https://user-images.githubusercontent.com/4084527/49652307-0260b080-fa32-11e8-9cca-809fd04dc360.png">
and if i do `git push` in terminal i get the good one
<img width="1263" alt="screenshot 2018-12-07 at 15 05 38" src="https://user-images.githubusercontent.com/4084527/49652364-2e7c3180-fa32-11e8-9c1c-136fcb9bc3f2.png">

The problem appear only with **husky**, **commitlint** and **vscode**, if i get error in typescript lint ,the next scrip in my pre-push hooks, the logs are well write in the git console.

**Comment by typicode** [comment]
thanks for the report, not sure what can be done on husky's side :/
