### ISSUE TITLE
Add JSON Schema for .huskyrc & .huskyrc.json

### ISSUE THREAD

**Issue by demensky** [typicode/husky#420]
After adding `husky` in project I use `pre-commit` & `pre-push` hooks. But `pre-commit` did not work.

The problem was that it was sealed up in `pro-commit`:

<img src="https://user-images.githubusercontent.com/10235949/49794993-8fad4900-fd41-11e8-9bf3-62687f2e2a51.png" width="332" height="79" />

I propose to add JSON Schema. That allow you to validate `.huskyrc` file and autocomplete.

<img src="https://user-images.githubusercontent.com/10235949/49795458-af913c80-fd42-11e8-82e0-eac2f83c71e4.png" width="486" height="131" />

<img src="https://user-images.githubusercontent.com/10235949/49795617-20d0ef80-fd43-11e8-961b-0e546d51f615.png" width="337" height="209" />

<img src="https://user-images.githubusercontent.com/10235949/49795712-5d9ce680-fd43-11e8-8a51-418bac682de7.png" width="337" height="115" />

**Comment by tohjg** [comment]
If available, please have it upload to http://schemastore.org/json/ where VSCode validate husky config file. Explicitly pointing schema to `node_modules` folder is not available if you are using monorepo.

**Comment by demensky** [comment]
angular.json using json schema in `node_modules`. What is the problem with monorepo? @tohjg do you have an example repository where it will not work?

**Comment by demensky** [comment]
@tohjg SchemaStore/schemastore#690
