### ISSUE TITLE
Husky uninstalls after first run

### ISSUE THREAD

**Issue by rumkin** [typicode/husky#426]
Husky version is `1.2.1`.

## Error

Husky runs once and then removes itself.

## Steps

1. Install husky.
2. Add husky to `package.json` as follows:
  ```json
  "husky": {
    "hooks": {
      "pre-commit": "./test.sh"
    }
  }
  ```
3. Run `git commit -m "Commit message"`.

Result output contains this:

```bash
husky > pre-commit (node v10.10.0)

> husky@1.2.1 preuninstall /project/path/node_modules/husky
> node husky uninstall

husky > uninstalling git hooks
husky > done

# My test output goes here
```

## Details
Package file content:

```json
{
  "name": "@plant",
  "private": true,
  "devDependencies": {
    "husky": "^1.2.1"
  },
  "husky": {
    "hooks": {
      "pre-commit": "./test.sh"
    }
  }
}
```

Test file `test.sh` switch directory to subpackage, installs missed packages and run tests:

```
#!/bin/bash

set -e

cd packages/plant
npm i .
npm test
```

**Comment by typicode** [comment]
Hi @rumkin,

What's the content of `./test.sh`?

**Comment by typicode** [comment]
Sorry didn't have time to look at the update :/
Closing as the issue may have been solved by new versions.
