### ISSUE TITLE
Pre-push fail from stdin for windows git-bash

### ISSUE THREAD

**Issue by jmfadeley** [typicode/husky#429]
For version 1.3.0 of Husky, I am using Git and GitBash for Windows 10 (we tried both version 2.10.1 and 20.20.1, the latest) with Yarn version 1.7.0. When I attempt to run `git push --set-upstream origin XXX/branch` it hangs indefinitely and if I cancel it, I see:

`error: failed to push some refs to 'https://github.com/BLAHBLAH.git'`

I am using tokens, and we believe stdin is hanging because it's expecting input. We tried using `<&-` to forcefully close the stdin, but it failed to work. For the time being we've locked ourselves to version 1.2.1 to workaround this.

**Comment by typicode** [comment]
Thanks for the report. You're using this token https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/ ?

Do you also have the error with `git push`? Or is the `--set-upstream origin XXX/branch` flag important to reproduce the error?

**Comment by jmfadeley** [comment]
We definitely used `--set-upstream`. Don't remember if we ever tried just `push` but I'll verify this afternoon.

And yes, we're telling on access tokens. Thanks!
