### ISSUE TITLE
`git push` freezes unslees it is run from .git/hooks

### ISSUE THREAD

**Issue by kyrrelm** [typicode/husky#430]
Running windows 7 with cygwin. My package.json looks like this:

```
{
  "husky": {
    "hooks": {
      "pre-commit": "yarn prettier:check"
    }
  },
...
 "devDependencies": {
    "husky": "^1.3.0",
    ...
}
```
As you can see I have no pre-push hooks setup. If I run `git push` from `.git/hooks` everything works fine, and I get the following:

```
Can't find Husky, skipping pre-push hook
You can reinstall it using 'npm install husky --save-dev' or delete this hook
Counting objects: 3, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 282 bytes | 282.00 KiB/s, done.
Total 3 (delta 2), reused 0 (delta 0)
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
...
```
If I run `git push` from the root of the project, the terminal freezes. The terminal is still responsive, but nothing is printed, and the process does not finish.

If I delete `/hooks` pushing from any directory works again.

**Comment by typicode** [comment]
Could you try with v1.2.1 ?

```
npm install husky@1.2.1 --save-dev
```

**Comment by justinhp** [comment]
@typicode yes, that works for me.  downgrading it.  otherwise, it's as @kyrrelm mentioned.
