### ISSUE TITLE
pre-commit hangs indefinitely on git bash

### ISSUE THREAD

**Issue by nerdchacha** [typicode/husky#431]
I am using trying to use `husky` on a windows machine using `git-bash`.
This is how my `.huskyrc` looks like
```
{
  "hooks": {
    "pre-commit": "npm run precommit"
  }
}
```
The pre commit hook runs perfectly fine when running `git commit -m "..."` but when i try to run `git commit --amend --no-edit`, the shell hangs indefinitely when using `git bash` but runs perfectly fine when firing the same command from `powershell`

**Comment by typicode** [comment]
Thanks for the report. Interesting that it works in `powershell` though.

I would suggest downgrading to `1.2.1`. I've changed the `@latest` tag to point to this version as well.

It's related to https://github.com/typicode/husky/blob/master/CHANGELOG.md#130

**Comment by nerdchacha** [comment]
Hi @typicode,
Thanks for the quick update.
v1.2.1 seems to be working fine.
