### ISSUE TITLE
Pre-commit hook not executing

### ISSUE THREAD

**Issue by AfroDevGirl** [typicode/husky#435]
I've read as many issues as possible trying to fix my problem with no luck. I'm working in a lerna repo with the root folder containing husky as a dev dependency. I have a single pre-commit hook that i'd like to run that delegates the same `lint-staged` task to each package. The command that should be run on pre-commit itself works perfectly, but I'm unable to get any Husky output/execution while running any `git commit` command, even with `HUSKY_DEBUG=true git commit ...`. My team has multiple repos and the pre-commit hooks (for ruby) are working just fine so I don't think I have an overall git hook issue. I've tried using `.huskyrc` instead of `package.json` as well. I've uninstalled and re-installed husky a number of times with no change. Any potential insight is welcome, i'm officially stumped!

Husky version `1.3.0`
MacOS version `Mojave 10.14`
Yarn version `1.9.4`
Node version `8.10.0`
Lerna version `2.11.0`
Lint Staged version `^8.1.0`
zsh version `5.4.2`

package.json:
```
"husky": {
    "hooks": {
      "pre-commit": "lerna run --concurrency 1 --stream precommit"
    }
}
```
.huskyrc:
```
{
    "hooks": {
      "pre-commit": "lerna run --concurrency 1 --stream precommit"
    }
}
```
^ I did not execute with both configurations at the same time, but it's the same result with both types of configuration.

sub-packages package.json:
```
"scripts": {
    ...,
    "precommit": "lint-staged"
},
...,
"lint-staged": {
    "*.{js, jsx}": [
      "eslint --fix",
      "git add"
    ],
    "*.{tx, tsx}": [
      "tslint --fix",
      "git add"
    ]
  }
```

All commit output:
```
$git status
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   root/to/changed/file.js

no changes added to commit (use "git add" and/or "git commit -a")
$git add .
$git commit -m 'Added some changes'
[git-branch-name sha123456] Added some changes
1 files changed, 6 insertions(+), 6 deletions(-)
```

running the command that should be executed by the husky config:
```
$lerna run --concurrency 1 --stream precommit
lerna info version 2.11.0
package-1: yarn run v1.9.4
package-1: $ lint-staged
package-1: Stashing changes... [started]
package-1: Stashing changes... [skipped]
package-1: → No partially staged files found...
package-1: Running linters... [started]
package-1: Running tasks for *.{js, jsx} [started]
package-1: Running tasks for *.{tx, tsx} [started]
package-1: Running tasks for *.{tx, tsx} [skipped]
package-1: → No staged files match *.{tx, tsx}
package-1: eslint --fix [started]
package-1: eslint --fix [completed]
package-1: git add [started]
package-1: git add [completed]
package-1: Running tasks for *.{js, jsx} [completed]
package-1: Running linters... [completed]
package-1: Done in 2.96s.
package-2: yarn run v1.9.4
package-2: $ lint-staged
package-2: Stashing changes... [started]
package-2: Stashing changes... [skipped]
package-2: → No partially staged files found...
package-2: Running linters... [started]
package-2: Running tasks for *.{js, jsx} [started]
package-2: Running tasks for *.{tx, tsx} [started]
package-2: Running tasks for *.{js, jsx} [skipped]
package-2: → No staged files match *.{js, jsx}
package-2: Running tasks for *.{tx, tsx} [skipped]
package-2: → No staged files match *.{tx, tsx}
package-2: Running linters... [completed]
package-2: Done in 0.99s.
lerna success run Ran npm script 'precommit' in packages:
lerna success - package-2
lerna success - package-1
```

pre-commit hook:
```
#!/bin/sh
# husky

# Hook created by Husky
#   Version: 1.3.0
#   At: 2018-12-27 10:49:14
#   See: https://github.com/typicode/husky#readme

# From npm package
#   Name: husky
#   Directory: /hidden/path/to/repo/node_modules/husky
#   Homepage: https://github.com/typicode/husky#readme

scriptPath="node_modules/husky/run.js"
hookName=`basename "$0"`
gitParams="$*"

debug() {
  [ "${HUSKY_DEBUG}" = "true" ] && echo "husky:debug $1"
}

debug "$hookName hook started..."

if ! command -v node >/dev/null 2>&1; then
  echo "Can't find node in PATH, trying to find a node binary on your system"
fi

if [ -f "$scriptPath" ]; then
  if [ -t 1 ]; then
    exec < /dev/tty
  fi
  if [ -f ~/.huskyrc ]; then
    debug "source ~/.huskyrc"
    source ~/.huskyrc
  fi
  node_modules/run-node/run-node "$scriptPath" $hookName "$gitParams"
else
  echo "Can't find Husky, skipping $hookName hook"
  echo "You can reinstall it using 'npm install husky --save-dev' or delete this hook"
fi

```

git config
```
$git config core.hooksPath
.githooks
```

executing the husky run.js script in terminal
```
$node_modules/run-node/run-node node_modules/husky/run.js pre-commit
husky > pre-commit (node v8.10.0)
lerna info version 2.11.0
package-1: yarn run v1.9.4
package-1: $ lint-staged
package-1: Stashing changes... [started]
package-1: Stashing changes... [skipped]
package-1: → No partially staged files found...
package-1: Running linters... [started]
package-1: Running tasks for *.{js, jsx} [started]
package-1: Running tasks for *.{tx, tsx} [started]
package-1: Running tasks for *.{tx, tsx} [skipped]
package-1: → No staged files match *.{tx, tsx}
package-1: eslint --fix [started]
package-1: eslint --fix [completed]
package-1: git add [started]
package-1: git add [completed]
package-1: Running tasks for *.{js, jsx} [completed]
package-1: Running linters... [completed]
package-1: Done in 2.96s.
package-2: yarn run v1.9.4
package-2: $ lint-staged
package-2: Stashing changes... [started]
package-2: Stashing changes... [skipped]
package-2: → No partially staged files found...
package-2: Running linters... [started]
package-2: Running tasks for *.{js, jsx} [started]
package-2: Running tasks for *.{tx, tsx} [started]
package-2: Running tasks for *.{js, jsx} [skipped]
package-2: → No staged files match *.{js, jsx}
package-2: Running tasks for *.{tx, tsx} [skipped]
package-2: → No staged files match *.{tx, tsx}
package-2: Running linters... [completed]
package-2: Done in 0.99s.
lerna success run Ran npm script 'precommit' in packages:
lerna success - package-2
lerna success - package-1
```

**Comment by AfroDevGirl** [comment]
[INSERT GIF OF HEAD HITTING DESK] 

`git core.hookspath` was wrong due to previous githooks configuration in our repo, unsetting it via `git config --unset core.hookspath` worked perfectly.

**Comment by gandhirahul** [comment]
Well I am having the same issue. 
But unsetting the `git core.hookspath` doesn't seem to work.

**Comment by gandhirahul** [comment]
The issue was with the git version as `core.hookspath` was introduced in v2.9. ( https://github.com/git/git/blob/master/Documentation/RelNotes/2.9.0.txt#L127-L128)

`brew upgrade git`

Upgrading git to latest version solved the problem.

https://tenor.com/4cCH.gif

**Comment by romellem** [comment]
For anyone else having this problem, mine was related to my **global** git config, setting the `core.hooksPath` key.

In my `~/.gitconfig` file, I had the following lines:

    [core]
	hooksPath = /Users/my.username/.git_hooks

Looking in this folder, I didn't have any real hooks setup, so I just deleted the `hooksPath` line altogether.

Opening a new terminal window, the husky pre-commit hooks set up in the current git repo now run correctly.

**Comment by dfquicazanr** [comment]
> [INSERT GIF OF HEAD HITTING DESK]
> 
> `git core.hookspath` was wrong due to previous githooks configuration in our repo, unsetting it via `git config --unset core.hookspath` worked perfectly.

You sir saved my life from a concussion from banging my head to the desk too, thank you very much

**Comment by hrk15** [comment]
@AfroDevGirl Thank you!

**Comment by HectorMG02** [comment]
> [INSERT GIF OF HEAD HITTING DESK]
> 
> `git core.hookspath` was wrong due to previous githooks configuration in our repo, unsetting it via `git config --unset core.hookspath` worked perfectly.



> The issue was with the git version as `core.hookspath` was introduced in v2.9. ( https://github.com/git/git/blob/master/Documentation/RelNotes/2.9.0.txt#L127-L128)
> 
> `brew upgrade git`
> 
> Upgrading git to latest version solved the problem.
> 
> https://tenor.com/4cCH.gif

it works for me!! Thanks (2022)
