### ISSUE TITLE
husky执行需要什么环境么

### ISSUE THREAD

**Issue by yizhengfeng-jj** [typicode/husky#439]
## 问题
husky执行不了
## 描述
我在windows上面配置了husky，是可以执行的，但是到了我的虚拟桌面就不行了，我的虚拟桌面node 都已经全局配置了
![image](https://user-images.githubusercontent.com/20452750/50754522-f8300d00-1290-11e9-9d1c-c52cdaf3f054.png)
## 异常结果
我git commit 直接帮我提交了，并且没有输出123

![image](https://user-images.githubusercontent.com/20452750/50754598-388f8b00-1291-11e9-8c08-5a51a45ceb45.png)

## 期待结果
![image](https://user-images.githubusercontent.com/20452750/50754641-578e1d00-1291-11e9-872e-dc300f72e306.png)

## 猜想
是不是husky要配合node 使用，可是我本地的和虚拟环境node都已经设置全局变量了，为什么本地的windows可以，虚拟桌面的不行了。！！！我们的虚拟桌面只能访问内网，不能访问外网，这会是原因么

**Comment by 403studio** [comment]
有可能是git版本的问题，当我使用`npm uninstall husky`时，出现了一下错误
`Husky requires Git >= 2.13.2, please update Git`。所有我更新了电脑上的git，重新安装husky就可以正常使用了
