### ISSUE TITLE
Code changes on precommit

### ISSUE THREAD

**Issue by flesler** [typicode/husky#44]
Hi, not sure this is an issue with this module or maybe it's just how git works.
I'm trying to automate package.json version bumping before every commit.

I installed `uver-cli` in devDependencies, it's just a module that bumps the version.
Then:
```json
{
  "scripts": {
    "precommit":"uver"
  }
}
```

It was effectively called but the version bump was left as an uncommited change.

Shouldn't precommit be able to change code? Is there another hook that should? Maybe it's something wrong with my code?

Thanks

**Comment by flesler** [comment]
Ok, found the solution, will explain here in case someone else gets here.

Problem was I wasn't git adding the change to the index. This is how the script should be instead:
```json
{
  "scripts": {
    "precommit":"uver && git add -A"
  }
}
```

**Comment by typicode** [comment]
Hi @flesler,
That's right, thank you for sharing the solution :+1: 
You can go to https://git-scm.com/docs/githooks if you need documentation about a particular git hook.
