### ISSUE TITLE
`git commit` fails, ultimately causing lost work

### ISSUE THREAD

**Issue by papiro** [typicode/husky#444]
This exact issue has happened twice to me, and while I'm not sure what the cause of it is, we reasoned it was related to husky so uninstalled it. I'm on a Windows, using MINGW64 git version 2.19.1.windows.1. Here is the flow of events, including the error:
```
PPirault@Dev38 MINGW64 ~/Desktop/proj (feature/transfers-description)
$ git status
On branch feature/transfers-description
Your branch is up to date with 'origin/feature/transfers-description'.

Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        modified:   app/components/account-selector/account-selector.spec.js
        modified:   app/components/checkbox/checkbox.spec.js
        new file:   app/components/input-field/input-field.spec.js
        modified:   app/components/selector/select.js
        renamed:    app/components/transfers-screen/transfers-screen.spec.js -> app/components/transfers-form/transfers-form.spec.js

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   app/components/checkbox/checkbox.spec.js
        modified:   app/components/input-field/input-field.js
        modified:   app/components/transfers-screen/transfers-screen.js
        modified:   bin/scaffold-component-test.js


PPirault@Dev38 MINGW64 ~/Desktop/proj (feature/transfers-description)
$ git commit
husky > pre-commit (node v8.12.0)
Stashing changes... [started]
Stashing changes... [failed]
→ Error: Command failed: git checkout-index -af
error: unable to create file README.md: Permission denied


Error: Command failed: git checkout-index -af
error: unable to create file README.md: Permission denied


husky > pre-commit hook failed (add --no-verify to bypass)

PPirault@Dev38 MINGW64 ~/Desktop/proj (feature/transfers-description)
$ git status
On branch feature/transfers-description
Your branch is up to date with 'origin/feature/transfers-description'.

Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        modified:   app/components/account-selector/account-selector.spec.js
        modified:   app/components/checkbox/checkbox.spec.js
        new file:   app/components/input-field/input-field.spec.js
        modified:   app/components/selector/select.js
        renamed:    app/components/transfers-screen/transfers-screen.spec.js -> app/components/transfers-form/transfers-form.spec.js

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        deleted:    README.md

```
As you can see, there is a `git checkout-index -af` (happening under husky's hood?), which is ditching the unstaged changes. At that point, the only way (that I know of) to recover the lost work is to comb through `git fsck --unreachable` and inspect each blob to find the changes.  This happened intermittently and we have been using husky in our project without issues for the last 2 months, with an average of 5 git commits per weekday. The two occurrences happened only within the last week.

**Comment by typicode** [comment]
Hi @papiro,

Sorry for the lost work :/

> happening under husky's hood?

Probably not. Husky doesn't run `git checkout-index -af`.
I would suggest checking commands that are defined in your `pre-commit` script.

**Comment by papiro** [comment]
Interesting! You just opened my eyes a bit. To be honest, I was blurring husky's responsibilities into other tools. It's not clear to me exactly what husky does from the README, so I thought husky was somehow in cahoots with our xo setup and linting our files, out-of-the-box! I think I need to post on a different repo...

Thanks!

**Comment by tasos-ch** [comment]
@typicode You were right.

It isn't Husky that stashes the changes. It is [lint-staged](https://github.com/okonet/lint-staged). I have configured it with `git add` and `lint-staged` explicitly mentions it in its [documentation ](https://github.com/okonet/lint-staged#reformatting-the-code) that this will stash unstaged files and restore them later.

I am sorry for the confusion!
