### ISSUE TITLE
Husky cannot execute hooks

### ISSUE THREAD

**Issue by Brolly0204** [typicode/husky#445]
## version
husky: "^1.3.1",
os: Mac
node: v10.7.0

## .huskyrc
```
{
  "hooks": {
    "pre-commit": "npm run lint"
  }
}
```

**Comment by shamatov** [comment]
Same here.

husky: "^1.3.1"
os: Windows 10
node: v10.15.0

There is no custom hooks that prevents Husky.

**Comment by danielhdz56** [comment]
same here, this is a recurring issue with husky. previous version of husky you could fix this by doing 
rm -rf .git/hooks 
and then installing husky 
npm install -D husky

this doesn't work for me, but maybe it does for y'all.

**Comment by tuananh** [comment]
@danielhdz56 this does fix it for me. thank you!

**Comment by vitalii** [comment]
doesn't work for me

**Comment by vitalii** [comment]
check .git/hooks
if it's empty try to uninstall husky and install again. my sh history

```sh
 ls .git/hooks
 npm uninstall husky
 npm i husky -D
 ls .git/hooks
```
it helped me

**Comment by SammyIsra** [comment]
Yup, deleting `.git/hooks` directory and reinstalling husky did it for me.

Is there any reason why this runs this way? Is there no command that we can run within husky to check and create the hooks? 

Do you also have to do the same thing every time you change your hooks? It seems a bit inconvenient if that's the case.

Maybe we can submit an MR to get around the issue?

**Comment by radiocity** [comment]
Changing `#!/bin/sh` to `#!/bin/bash` helps with `cannot spawn` error, but leads to new one `.git/hooks/pre-commit: line 32: node: command not found` on Windows.

**Comment by zhixuanziben** [comment]
@vitalii It does work for me, Thanks!

**Comment by hejkerooo** [comment]
Check `git` version
https://stackoverflow.com/questions/39332407/git-hooks-applying-git-config-core-hookspath

It may cause an issue.
My git version is currently `2.17.2`, I will update it and post results there, if this worked.

**Comment by chat-du-cheshire** [comment]
Hi, I'm trying to run custom hook from husky. I have package.json file and folder "custom-hooks" where I've my custom pre commit. But config like this

**Comment by wataruoguchi** [comment]
Hi, I had the same issue. The hooks didn't work. Here's what I did.

**Make sure you understand it changes the valid location of hook files. If you're not familiar with this, talk to your peer before you run the commands.**

1. Check where your git hooks are: `$ git rev-parse --git-path hooks`
1. Then if it's not `.git/hooks`, run `git config core.hooksPath .git/hooks/` to solve the problem.

It seems like the hooks files are created in `.git/hooks/` no matter what the `core.hooksPath` is.

**Comment by 403studio** [comment]
first,you shoule check the `.git/hooks` if there are some hooks,such as `pre-commit` ,and check its content,if husky is corrected configed,you can see some content
second,if the `.git/hook` does not has hooks,that means `husky` isnt take place.you shoule reinstall husky.for me at this moment i find the problem

when i uninstall husky,the terminal show:
**`Husky requires Git >= 2.13.2, please update Git`**
so i update my git and reinstall husky, everything is ok

**Comment by championchap** [comment]
I was installing husky via the official node docker image for 10.16. These are based on Debian, which does not have access to a version of Git as high as is required for Husky to work.

It's also worth noting that while running `npm install` does give the "please update git" message, it doesn't appear to show when using Yarn to install your dependencies. This left me scratching my head for a while.

**Comment by typicode** [comment]
Closing it some fixes have been suggested. Also it's related to a pretty old husky version.

As for Debian, it seems that Debian Buster has now a version of Git without the issue. Even though not ideal for the moment and for people stuck with older versions of Debian, it should hopefully be fixed with time.

Yarn seems to hide `console.log` messages during install. I don't really know what could be done about that, but I would be scratching my head too.

**Comment by dboscanv** [comment]
In my case, it was my Node version (should be >=10)

**Comment by batouche-dev** [comment]
add your script into package.json like this for instance:
{
  "scripts": {
-   "precommit": "npm test",
-   "commitmsg": "commitlint -E GIT_PARAMS"
  },
and then run this command line:

npx --no-install husky-upgrade

to automatically upgrade your configuration, then try again, it works for me.

**Comment by BoMiddleton** [comment]
> Yup, deleting `.git/hooks` directory and reinstalling husky did it for me.
> 
> Is there any reason why this runs this way? Is there no command that we can run within husky to check and create the hooks?
> 
> Do you also have to do the same thing every time you change your hooks? It seems a bit inconvenient if that's the case.
> 
> Maybe we can submit an MR to get around the issue?

Good lord -

**Comment by baleksandr48** [comment]
Hej everyone, I tried all above and it hasn't helped me. But I solved the problem by upgrading node&npm.
```
sudo npm cache clean -f
sudo npm install -g n
sudo n stable
--open new terminal--
rm -rf ./node_modules/
npm i husky
```
I am not sure but maybe first command (sudo npm cache clean -f) would be enough.

**Comment by BoMiddleton** [comment]
THIS WORKED!!!! 

in the package.json file"

  "husky": {
       "hooks": {
         "pre-commit": "npm test",
         "commit-msg": "commitlint -E HUSKY_GIT_PARAMS"
       }
  },

**Comment by Arslanmajeed270** [comment]
> Hi, I had the same issue. The hooks didn't work. Here's what I did.
> 
> **Make sure you understand it changes the valid location of hook files. If you're not familiar with this, talk to your peer before you run the commands.**
> 
>     1. Check where your git hooks are: `$ git rev-parse --git-path hooks`
> 
>     2. Then if it's not `.git/hooks`, run `git config core.hooksPath .git/hooks/` to solve the problem.
> 
> 
> It seems like the hooks files are created in `.git/hooks/` no matter what the `core.hooksPath` is.

Thanks it's worked for me.

**Comment by MarkoCen** [comment]
The issue happened with latest node version `15.14.0`
By switching to older node version `14.15.1`, the issue resolved

**Comment by dayvsonsales** [comment]
This problem still occurred with node version v15.3.0

**Comment by Naimdasb** [comment]
Yes I have issues with husky with node v15.3.0

**Comment by 5bsh** [comment]
There is also issue with Node v12.16.0. After lots of config changes multiple installation, I decided to update node version and then it works.

**Comment by lukemovement** [comment]
Still getting the above issue with Windows 10 / Husky 6.0.0

**Comment by simo54** [comment]
I am having the same issue but this is how it worked for me without specifying the custom hook inside package.json on React 

**OS: Windows 10
Node: v14.16.1
husky: ^6.0.0**

1. `npm install husky --save-dev`
2. `npx husky install`
3. `npx husky add .husky/pre-commit "npm run test"` 
4. `git commit -m"custom message"`

**Comment by rathod-sahaab** [comment]
[Official Docs](https://typicode.github.io/husky/#/?id=manual) supporting @simo54 's [answer](https://github.com/typicode/husky/issues/445#issuecomment-821869101)

**Comment by jeafgilbert** [comment]
For me that is using yarn and typescript, after doing `yarn husky install`, it generates _.husky_ folder and if we check `git rev-parse --git-path hooks` will show _.husky_, no need to change that. What I did was creating new file named _pre-push_ (without any file extension) in _.husky_ folder. I only added the execution of the test in the file, but you can add your linting rules, formatting, or whatever you like.

<img width="352" alt="Screenshot 2023-03-04 at 12 36 58 PM" src="https://user-images.githubusercontent.com/1263134/222878117-2a615da9-f811-4b32-9f98-f0a421af88a7.png">

```
yarn test -u
```
