### ISSUE TITLE
Testing Hooks

### ISSUE THREAD

**Issue by stalinkay** [typicode/husky#446]
Is there a way to test the hooks that are set up in `.huskyrc`? It was previously possible to use `npm run pre-commit` to test a hook. Find my specific use case here.

.huskyrc

```
{
  "hooks": {
    "pre-commit": "npm install && npm run lint && npm run test",
    "commit-msg": "echo $HUSKY_GIT_PARAMS; commitlint -E HUSKY_GIT_PARAMS && (proselint $HUSKY_GIT_PARAMS || true) && ./spellcheck.sh $HUSKY_GIT_PARAMS && npm run spellcheck -- $HUSKY_GIT_PARAMS",
    "postcommit": "if ! git diff --exit-code *Info.plist &> /dev/null; then npm run commitamend; fi",
    "post-rewrite": "npm run postcommit"
  }
}
```

**Comment by zachlysobey** [comment]
Trying to answer this myself @stalinkay.

So far my best idea is to just create *new* npm scripts for each of these in package.json and update the `.huskyrc` to point at those.

```json
{
  "hooks": {
    "pre-commit": "npm run husky:pre-commit",
    "commit-msg": "npm run husky:commit-msg",
    "postcommit": "npm run husky:postcommit",
    "post-rewrite": "npm run husky:post-rewrite"
  }
}
```

**Comment by stalinkay** [comment]
@zachlysobey Thanks, this is exactly what I was looking for but for some reason, it didn't cross my mind.
