### ISSUE TITLE
Deleted Project That Used Husky From Repo - Husky Hooks Still Attempting To Run

### ISSUE THREAD

**Issue by ideoclickVanessa** [typicode/husky#448]
I had a project that was using husky in gitrepoA. The project has since moved to gitrepoB; however, I'm still getting the following kind of errors in gitrepoA:
`Can't find Husky, skipping post-checkout hook`

I'm confused as to why the Husky hooks are still being attempted even after the only project that referenced the husky package has been removed from gitrepoA. How do I get gitrepoA to stop attempting to call the husky hooks?

**Comment by Nolanus** [comment]
Take a look at the files in `.git/hooks` folder and remove everything that you didn't put there. You may also delete all non `*.sample` files all together if you do not use any git hooks any longer.

**Comment by ideoclickVanessa** [comment]
Deleting all of the non `*.sample` files seems to have done the trick.

Did I need to perform this manual step because I didn't perform an `npm uninstall husky` or would I always need to perform this manual step?

**Comment by Nolanus** [comment]
Running `npm uninstall husky` should delete all the git hook files as well (https://github.com/typicode/husky/blob/89efe65f1848d312988880f2a5f754e2d0b32c1b/src/installer/index.ts#L192)
