### ISSUE TITLE
Unix commands whilst using windows git bash.

### ISSUE THREAD

**Issue by GeoffThorpeFT** [typicode/husky#449]
We have a husk hook pre-push hook defined in our javascript environment as follows:
```
module.exports = {
	hooks: {
		'pre-commit': 'secret-squirrel && lint-staged',
		'pre-push': 'CI=true make test',
	},
};
```
Unfortunately when a push is triggered from a git bash session on windows we get 
```'CI' is not recognized as an internal or external command,```

It appears the command is running in a pure windows sessions instead of a git bash session. Is this expected behaviour?

**Comment by ankri** [comment]
Hi, 
have a look at [cross-env](https://github.com/kentcdodds/cross-env) 

>cross-env makes it so you can have a single command without worrying about setting or using the environment variable properly for the platform. Just set it like you would if it's running on a POSIX system, and cross-env will take care of setting it properly.

And the usage example from their readme:
```json
{
  "scripts": {
    "build": "cross-env NODE_ENV=production webpack --config build/webpack.config.js"
  }
}
```

**Comment by typicode** [comment]
Hi @GeoffThorpeFT 

> It appears the command is running in a pure windows sessions instead of a git bash session. Is this expected behaviour?

Shouldn't be. At least, I've always observed the opposite when testing on Windows.

How did you install Git? Which tools do you use?

As @ankri suggested, `cross-env` should fix that.

**Comment by avidrucker** [comment]
@GeoffThorpeFT How did it go in resolving your issue? I am experiencing a similar `'CI' is not recognized as an internal or external command,
operable program or batch file.` on pre-push while working in Windows (Gitbash & Powershell), and not clear as to how to utilize cross-env in resolving the issue.

**Comment by typicode** [comment]
@avidrucker Not sure if that's the issue but `cross-env CI=true your-command` should fix your error message.

Closing to clean up. Feel free to re-open if needed.
