### ISSUE TITLE
Cannot find git directory due to `package.json` npm package

### ISSUE THREAD

**Issue by sgronblo** [typicode/husky#450]
I had to manually regenerate my husky hooks and found (by inspecting package.json) that one way of doing it would be to run `node node_modules/husky/husky.js install`. However the command was mysteriously failing because it could not find the .git directory.

After some debugging I noticed that we have a transitive dependency that is actually named `package.json` https://www.npmjs.com/package/package.json which causes husky to think that node_modules is the project root and therefore causes the .git folder lookup to fail.

I worked around it for now by temporarily renaming the `package.json` package and then re-running the husky install command and then restoring the name.

I recommend adding a fix that checks whether package.json is a file before returning that directory as the project root.

**Comment by typicode** [comment]
Thanks for the report! Interesting case, wasn't expecting that 😅
It'll be fixed.

**Comment by typicode** [comment]
> I recommend adding a fix that checks whether package.json is a file before returning that directory as the project root.

I agree, at least as a temporary fix.

**Comment by typicode** [comment]
Should be fixed by husky `2.5.0` (would need some testing)

**Comment by leonardovillela** [comment]
This issue is corrected? Or can i take this?
