### ISSUE TITLE
Question: Append keyword if `--no-verify` was used.

### ISSUE THREAD

**Issue by manojchandrashekar** [typicode/husky#456]
Can I add append a keyword to the commit message if the `--no-verify` flag was used to skip the hook?

Usually when the hooks are skipped, it is because of lint errors or code coverage thresholds, which usually means we are accruing tech debt. I was wondering if this can be tracked.

**Comment by karltaylor** [comment]
I am also looking to do this functionality but I am unsure how to integrate?

**Comment by rickvandermey** [comment]
I would like to see if my commit message starts with `WIP` or if i could set this variable,  it would skip the hook completely,
