### ISSUE TITLE
Make hookName available to scripts through environment var

### ISSUE THREAD

**Issue by damonmaria** [typicode/husky#457]
If I try and keep things simple and just call the same script from each Husky hook I'm using (since what I'm trying to do from each hook is similar) then there's no way (without passing a argument to the script) to determine what git hook is running. e.g. `post-checkout`, `post-merge`, etc... 

Can this be made available through an environment var? Something like `HUSKY_HOOK_NAME`?

**Comment by typicode** [comment]
It may not fit exactly the initial need. But with v5, it should be more straightforward to get hook name in a generic way. For example with `basename $0`.
