### ISSUE TITLE
Doesn't work when installed via 'npm link husky'

### ISSUE THREAD

**Issue by medikoo** [typicode/husky#458]
Currently `husky` depends on side-effect of `run-node` package being installed as top dependency of given project, if it's not the case then hooks crash with:

```
line 36: node_modules/run-node/run-node: No such file or directory
```

It looks as source of an issue is here: https://github.com/typicode/husky/blob/f8f1172b4794d28b681b2dfe6ac0473cbeba56a8/src/installer/getScript.ts#L91

**Comment by typicode** [comment]
Hi @medikoo, to better understand the issue, why do you need to install it using `npm link`?

**Comment by medikoo** [comment]
> Hi @medikoo, to better understand the issue, why do you need to install it using `npm link`

I maintain tens of packages, and prefer to have one physical installation of `husky` which is linked into all packages I maintain.

Generally fact that `husky` relies on flat installs qualifies as a bug imo, as flat installs are not considered to be a standard that has to be followed to ensure correct node modules resolution (npm from v3 started to imply flat installs only to avoid too long path names on windows).

Additionally also in case of normal `npm install` it's immune to bugs (at least theoretically), as if there are some other project dependencies that rely on other `run-node` version which for some reason is not compatible with one used by `husky`, then `npm` may install `run-node` that's dedicated for `husky` in husky's `node_modules`, leaving incompatible one in top level `node_modules`.

If `run_node` has to be addressed by direct path, then some fix might be to follow logic as below (in free notation):
```javascript
if (exists('node_modules/husky/node_modules/run_node')) {
  use('node_modules/husky/node_modules/run_node');
} else {
 use('node_modules/run_node');
}

**Comment by medikoo** [comment]
It might be also related to fact that `husky` resolves that path on _install_, while it'll be better if it's resolved with node resolution rules at _run_ moment (if possible)

I first installed normally, and then linked. I guess `husky` won't install properly just with `npm link husky` (and I guess it's hard to workaround it)

**Comment by typicode** [comment]
Thanks for the detailed explanations! :+1: 

Going to close the issue as husky 5 doesn't use `run-node` or auto-installs anymore. It's also quite different from v4.
