### ISSUE TITLE
Add description to readme about what's going on under the hood

### ISSUE THREAD

**Issue by adius** [typicode/husky#46]

**Comment by typicode** [comment]
Thank you for the feedback, what do you think would need clarification?

**Comment by adius** [comment]
Well … if you check out the code of the generated hooks,
it all makes sense.
But I think this feeling should already settle in after reading the readme =D

**Comment by adius** [comment]
I guess a short explanation that husky generates the hook files in the .git/hooks directory
which check the package.json for the corresponding script and execute it
(and use the nvm specified version) would already be an improvement.

**Comment by iamstarkov** [comment]
@adius would you mind to suggest a pull-request with relevant explanation?
