### ISSUE TITLE
Husky can not find NPM in path

### ISSUE THREAD

**Issue by CristoAMH** [typicode/husky#460]
I installed node and npm with nvm. Trying to fix another error that husky give me before( I still don't know what it is: 
```
husky > npm run -s precommit (node )
env: node: No such file or directory
husky > pre-commit hook failed (add --no-verify to bypass)
```

But I reinstalled node and npm and now give me this error
**Main error:**
```> activity-drag-drop@1.0.6-59 test:husky /Users/cristoamh/MEGAsync/insendi/repositories/activities/activity-drag-drop
> git add . && git commit -m 'updating version'  && git push

nvm is not compatible with the "npm_config_prefix" environment variable: currently set to "/Users/cristoamh/.nvm/versions/node/v8.15.0"
Run `unset npm_config_prefix` to unset it.
**husky > can't find npm in PATH**, skipping precommit script in package.json
On branch test
nothing to commit, working tree clean
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! activity-drag-drop@1.0.6-59 test:husky: `git add . && git commit -m 'updating version'  && git push `
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the activity-drag-drop@1.0.6-59 test:husky script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/cristoamh/.npm/_logs/2019-02-26T22_56_27_023Z-debug.log```

 
Does anyone know what is happening? Thanks.

**Comment by bm-stschneider** [comment]
`sed -i '26i\ exit 0' .git/hooks/pre-commit` would fix this.
In general, husky throws and exit code 1 if it can't find node/npm.

**Comment by CristoAMH** [comment]
@bm-stschneider Can you explain to me what does the command that you wrote?

**Comment by bm-stschneider** [comment]
This would insert exit 0 for the case that node is not found. If node is actually there but not found, that would be a different problem though.

**Comment by CristoAMH** [comment]
@bm-stschneider Thanks for answer so fast. Your solution is good but I just see one problem. For the project that I am working on, there are at least  ~40 folders where I use husky. And I should do this in every folder.

I think I have to figured out why is not finding npm or node when have been installed with NVM.

**Comment by typicode** [comment]
This looks like some old husky version. I'd recommend updating to latest version.
