### ISSUE TITLE
How do I recover the commit message for another try?

### ISSUE THREAD

**Issue by docwhat** [typicode/husky#461]
How do I recover the commit message to try again when (for example) lint is found?

If my message is detailed it is irritating to re-enter the whole thing again just because I forgot to fix a bit of lint.

This should probably be in the README.

**Comment by callamwilliams** [comment]
Usually press the up arrow key in your terminal window?

`git push origin develop -f` will run the task again if it's a pre-push task

**Comment by docwhat** [comment]
> Usually press the up arrow key in your terminal window?

😝 

The order of things is:

1. `git commit`
2. Type in commit message.
3. lint-staged runs
4. It fails.

I then have to fix the problem, and then start over again.

If I spent a bunch of time on 2, I've lost all my work. 😢

**Comment by LarsWalter** [comment]
If your hook is a `pre-commit` you shouldn't be prompted to type your commit message until after your hook has run successfully.

1. `git commit`
2. pre-commit hook runs.
3. if pre-commit passes, editor for typing commit message is opened.

If you inline your commit message with `git commit -m "..."` it's in your command history.

**Comment by docwhat** [comment]
Are you sure? Because that isn't my experience with [my `package.json`](https://github.com/docwhat/docwhat/blob/ba52c5dfd270042ea59152652826a88ad4bc337a/package.json#L44-L48):

```sh
$ git cz
cz-cli@3.0.7, cz-conventional-changelog@2.1.0


Line 1 will be cropped at 100 characters. All other lines will be wrapped after 100 characters.

? Select the type of change that you're committing: chore:    Other changes that don't modify src or test files
? What is the scope of this change (e.g. component or file name)? (press enter to skip)

? Write a short, imperative tense description of the change:
 use gatsby's clean instead of just rm
? Provide a longer description of the change: (press enter to skip)

? Are there any breaking changes? No
? Does this change affect any open issues? No
husky > pre-commit (node v11.10.1)
  ↓ Stashing changes... [skipped]
    → No partially staged files found...
  ✔ Running linters...
[master ec1a96a] chore: use gatsby's clean instead of just rm
 1 file changed, 1 insertion(+), 1 deletion(-)
```

If the tests failed then I'd have to re-enter the commit message.

FYI: `git cz` is part of [commitizen](http://commitizen.github.io/cz-cli/).  It asks you questions and then creates a changelog compatible commit message.

**Comment by docwhat** [comment]
Ah... I think the problem is that `git cz` asks the questions _before_ it runs `git commit --message=...`.

Yup. Buried _way down_ in the docs is a [_Retrying failed commits_](https://github.com/commitizen/cz-cli#retrying-failed-commits) section.

Sorry for bothering y'all.

**Comment by mohamed-ahmed** [comment]
I see this issue is closed but I don't quite understand @docwhat 's answer. What's the significance if it runs `git cz` before or after `git commit --message=...` ?
Also how should the git commit message be formatted to not require the interactive input?
