### ISSUE TITLE
Unable to run hooks from Git-Bash or Babun

### ISSUE THREAD

**Issue by cmccormack** [typicode/husky#462]
Hello,

I've been testing with a few different shells and even asked a few others to test - for some reason I cannot seem to get my hooks to work from git-bash or Babun (running ZSH) on Windows 10, while they work fine in WSL, powershell, and cmd.  

I asked a few others to test and it worked fine for them, so I suspect it's an environment variable issue but I'm just not sure.

I'm attempting to run a pre-commit with pretty-quick:
```json
  "husky": {
    "hooks": {
      "pre-commit": "pretty-quick --staged"
    }
  }
```

I also tested using an echo and that seems to work fine:
```json
  "husky": {
    "hooks": {
      "pre-commit": "echo 'test'"
    }
  }
```
```sh
husky > pre-commit (node v11.11.0)
'test'
```

I added a log statement in `node_modules/husky/lib/runner/index.js` catch statement and I get the following error thrown:
```sh
$ git commit
husky > pre-commit (node v11.11.0)
'pretty-quick' is not recognized as an internal or external command,
operable program or batch file.
{
  "code": 1,
  "stdout": null,
  "stderr": null,
  "failed": true,
  "signal": null,
  "cmd": "C:\\WINDOWS\\system32\\cmd.exe /q /s /c \"pretty-quick --staged\"",
  "timedOut": false
}
```

Seems odd it's trying to run it with cmd instead of bash/zsh.

Again, I suspect environment variables but I'm not sure how to test this so I'm hoping someone with more experience with Husky may be able to help.

**Comment by vonwao** [comment]
I'm having a similar issue with same error ('pretty-quick' is not recognized as an internal or external command).  Strangely, it was working for me for a while, and then it stopped working.

**Comment by pppdns** [comment]
I have the same issue but strangely enough, only recently

**Comment by Tragedian** [comment]
I also have this issue, but only on one machine. Not clear exactly what's special about this environment, but the symptoms are the same.

In our setup, the `pretty-quick` module is installed locally, so it makes sense that cmd.exe cannot resolve it. What's not clear is why it works in most environments.

**Comment by ddaversa** [comment]
I am trying to fix a similar issue.  Some details on my side:
husky hook set as:
```
      "post-merge": "./git/hooks/post-merge $@",
```

I'm running Git Bash on Windows 10.  The error I get on commit is:

```
husky > pre-commit (node v10.15.1)                                                                                                                                                   '.' is not recognized as an internal or external command,                                                                                                                            operable program or batch file.
```

I noticed that's a Windows error. If I run the prehook script manually in git bash, it runs quietly. If I run it in cmd.exe, I get the same error.  A bit of investigation showed me that a possibly fix for this would be to run

```
npm config set script-shell "C:\\Program Files\\Git\\bin\\bash.exe"
```

While that seems to fix similar issues for other people, I tried it both in cmd & git bash, but no success there.  I'm running out of ideas.

Anyone found anything else ?

**Comment by Tragedian** [comment]
It looks like it's something to do with the `Path` environment variable for the cmd.exe process. 

@ddaversa Could you try to use this as a hook to see if your symptoms are the same?
```
"pre-commit":` "echo %Path%"
```

I've managed to capture a process start event using ProcMon, and I can see the `Path` variable used to launch the process includes the local `node_modules\.bin` directory, which _should_ make the local tools resolve correctly. The output from the echo should match, but is instead my default environment value.

**Comment by ddaversa** [comment]
If I do that, it just echoes the Path correctly.

It seems the error comes from the fact that Husky is using cmd.exe to execute the hooks instead of Git Bash (where I call it from); and because of that, it doesn't support the forward slashes "/" in the path.  A simple fix would be to use backslashes "\" instead, but then I'll break it for the rest of my team, so that's not a possibility. I'm wondering if I can get husky to execute the hooks from Git Bash instead.

**Comment by Tragedian** [comment]
Got to the bottom of my issue today and the problem seems to be related to an old install of `nvmw`.

There's a little-known feature of CMD on Windows that allows you to automatically run a script whenever a new CMD terminal is established: [Hidden gotcha: The command processor's AutoRun setting](https://devblogs.microsoft.com/oldnewthing/20071121-00/?p=24433).

One of these AutoRun scripts had been configured for my profile. The script itself overwrites the `Path` variable with its own value (seemingly based on my default environment variables). Once the associated registry key was removed, the normal value flowed into the process and everything worked as expected.

**Comment by pmarshall** [comment]
I just had this issue crop up on Windows after I did a "git clean" to force a clean slate. The solution was to re-run "npm install" as administrator. (Not my proudest moment, but I'm not going to worry my pretty little head about it.)

**Comment by shakthifuture** [comment]
I followed this temporary solution and works charm: https://stackoverflow.com/questions/63943401/husky-pre-commit-hook-failed-add-no-verify-to-bypass/63948896#63948896

**Comment by MatthewPorter31** [comment]
@shakthifuture that works, but eliminates the purpose of Husky. --no-verify bypasses husky checks

**Comment by typicode** [comment]
Cleaning old issues, so I'm going to close this one as some workarounds seem to have been found.
Also husky 5 may be exempt from this issue.
