### ISSUE TITLE
Easier support for multiple commands in non-js config files

### ISSUE THREAD

**Issue by ericcornelissen** [typicode/husky#464]
As specified [in the docs](https://github.com/typicode/husky/blob/master/DOCS.md#multiple-commands) one can run multiple command using `&&`, the example given is:

```json
{
  "pre-commit": "cmd && cmd && cmd"
}
```

The docs then go on to describe how one can use JavaScript to write this in a more readable fashion

```javascript
const tasks = arr => arr.join(' && ')

module.exports = {
  'hooks': {
    'pre-commit': tasks([
      'cmd',
      'cmd',
      'cmd'
    ])
  }
}
```

I wonder if there is any plans or desire to automatically support a syntax like this for non-javascript formats (e.g. JSON or YAML), where Husky will automatically concatenate commands for you when you provide it with an array of commands? So one could just use ⬇️ and have all the commands run in sequence.

```yaml
hooks:
  pre-commit:
    - cmd
    - cmd
    - cmd
```

I haven't looked at the code of the project yet, but if this is a desired feature I would be interested in trying to implement it 😃

**Comment by jantimon** [comment]
👍 that would be way cleaner than `&&`

**Comment by ericcornelissen** [comment]
Close this as per [this comment](https://github.com/typicode/husky/pull/638#issuecomment-725443116).
