### ISSUE TITLE
There ought to be a way to instruct husky to exclude certain hooks

### ISSUE THREAD

**Issue by kylebebak** [typicode/husky#467]
E.g., a `.huskyrc.json` file, with an array of hooks are aren't created in `.git/hooks` when husky is installed.

Use case: I don't want the `prepare-commit-msg` and `commit-msg` hooks putting commented out stuff into my commit messages. It's opt-in behavior for devs that know they'll never add certain hooks to their project.

I'm sure there are plenty of other valid use cases. I figure this change would be fairly easy to implement.

It could work like this:

`.huskyrc.json`

~~~json
{
  "excludedHooks": [
    "prepare-commit-msg",
    "commit-msg",
    "applypatch-msg"
  ]
}
~~~

**Comment by typicode** [comment]
To be honest, there are no plans to support this for the moment. But you can empty these hooks locally and husky won't reinstall them:

```
: > .git/hooks/prepare-commit-msg # disabled and husky won't reinstall it
```

**Comment by kylebebak** [comment]
Ah, neat trick... Thanks!
