### ISSUE TITLE
Works only in terminal

### ISSUE THREAD

**Issue by DonikaV** [typicode/husky#470]
root folder 
```
"lerna": "3.11.0",
"husky": "^1.3.1"
```
lerna.json 

```
"packages": [
    "pack1",
    "pack2"
  ],
```

pack 1 and pack2 have this in package.json in scripts

"precommit": "lint-staged"

With .lintstagedrc.yml 
```

linters:
  "src/main/js/**/*.{js,jsx,mjs}":
    - "eslint src/main/js --fix"            # Run Eslint
    - "prettier --print-width 120 --tab-width 4 --trailing-comma none --write src/main/js/**/*.{js,jsx,mjs}"
    - "git add"
```

After commit nothing.  I mean no any messages/output

It works only from terminal. 
I mean i need run 
git add -A
npm run -s precommit

But if i do normal flow for commit - nothing happens

**Comment by typicode** [comment]
In root folder, I think you also need to have a husky config that will run the corresponding `precommit` in each packages.

See https://github.com/typicode/husky/blob/master/DOCS.md#multi-package-repository-monorepo

**Comment by DonikaV** [comment]
I have, but it not works...
