### ISSUE TITLE
Husky cannot execute hooks for post-receive or post-update

### ISSUE THREAD

**Issue by sallypanda** [typicode/husky#473]
version
husky: "^1.3.1",
os: Window 10
node: v8.11.3

.huskyrc
``` 
 {
    "husky": {
        "hooks": {
            "pre-commit": "npm run eslint",
            "post-receive":"node test.js",
            "post-update":"node test.js"
        }
    }
  }
```

`git push ` ，There's no way to trigger the post-receive and post-update hook。
But `pre-commit` is worked! 
Please take a look.

**Comment by sbalay** [comment]
@sallypanda Those hooks that you mention are server side hooks, not client side. 
Server side hooks are not supported.
