### ISSUE TITLE
Commit through VSCode problem

### ISSUE THREAD

**Issue by jpgmiranda** [typicode/husky#474]
Hi folks,

Just for documentation, I will post that problem I have had because I didn't find anything on the web about it.

**Problem**
When I try to commit through the VSCode I received this popup problem: 

![image](https://user-images.githubusercontent.com/3392236/56165992-e0aca280-5faa-11e9-9156-deeadae34aa4.png)

**Solution**
After some struggle trying searching on the web, I found out what happened. My default node version was out of date, see: `default -> v4.1.1`.

![image](https://user-images.githubusercontent.com/3392236/56166239-747e6e80-5fab-11e9-9f2c-edcf0070e99a.png)

Then to solve it I just changed the default node version to more up to date:
```sh
nvm alias default 8.10.0
```
And restart the VSCode :D

**Comment by BlindDespair** [comment]
@jpgmiranda thank you man, you saved my day! My nvm default was set to none, lol
