### ISSUE TITLE
Q: Is it possible to have personal, global husky rules?

### ISSUE THREAD

**Issue by michahell** [typicode/husky#478]
On top of husky rules used per repo (shared in git), is it possible to additionally have a personal set of hooks that are always applied for each and every git repository on your machine?

It is possible to do this without Husky: https://stackoverflow.com/questions/2293498/applying-a-git-post-commit-hook-to-all-current-and-future-repos

**Comment by Roms1383** [comment]
That would actually cool to have them as presets maybe, in the way it works for `semantic-release` and `commitlint`?

**Comment by typicode** [comment]
Not with the current release but it's something interesting. Maybe in future versions.
