### ISSUE TITLE
Any breaking changes with 2.0?

### ISSUE THREAD

**Issue by danielmartinprieto** [typicode/husky#481]
Hello, I'd love to know if there is any breaking change after the last major release. I also think it'd be a good idea to include a little changelog for each release, or at least a list of breaking changes (if any) and a migration path for those when applicable.

Thanks.

**Comment by tobiasbueschel** [comment]
Hey @danielmartinprieto,

You can find the changelog here: https://github.com/typicode/husky/blob/master/CHANGELOG.md

I agree with you though, it would be great if we could include the changes in the [Github Release](https://help.github.com/en/articles/creating-releases) section as well.

@typicode could we retrospectively add all the changes to the release section? GitHub allows to edit the description for each release: https://help.github.com/en/articles/editing-and-deleting-releases

**Comment by danielmartinprieto** [comment]
Sorry, my bad! Didn't see the changelog! Thanks, @tobiasbueschel <3

**Comment by typicode** [comment]
No worries, I've updated the CHANGELOG to make it more visible what is the 2.0 breaking change is.

For the moment, I think I'll stick to a file because it's easy to maintain. Maybe in the future I'll switch to GitHub Release, thanks for the feedback.

By the way, are there any particular benefits having the CHANGELOG in GitHub Release?

**Comment by danielmartinprieto** [comment]
@typicode I think people usually go to that GitHub tab looking for the releases, and most "well documented" libraries use it to share the changelog at the same time. But if you already keep a CHANGELOG file I think that's more than ok, just make sure its existence is well communicated in the readme or somewhere else.
