### ISSUE TITLE
feature: add HUSKY_SKIP_HOOKS support

### ISSUE THREAD

**Issue by typicode** [typicode/husky#487]
When rebasing, it may be useful to be able to temporarily disable hooks. Unfortunately, it's not possible to do it with `git rebase --no-verify`, `pre-commit` hook is still run.

A test should be added in https://github.com/typicode/husky/blob/master/src/installer/getScript.ts#L54 to verify if `HUSKY_SKIP_HOOKS` is set to `1` or `true`, if that's the case the hook should display some message and exit. 

```sh
$ HUSKY_SKIP_HOOKS=1 git rebase -i ...
```

Ideally a test could be added in https://github.com/typicode/husky/blob/master/.travis.yml to verify that hooks are skipped. Something like:

```yaml
- HUSKY_SKIP_HOOK=1 time git checkout
# Check that no ci-post-checkout file was created via a ci-husky-skip-hooks.js script
# For example, see:
# https://github.com/typicode/husky/blob/master/scripts/ci-post-checkout-check.js
```

Related issues:
https://github.com/typicode/husky/issues/468
https://github.com/typicode/husky/issues/447

**Comment by asaf050** [comment]
+1
Facing the same issue , unable to skip post-commit hook.

**Comment by ozzywalsh** [comment]
Hi Guys,
I have created a pull request for this.
Feedback appreciated.

**Comment by typicode** [comment]
Thanks again @ozzywalsh for the PR, it'll be released soon.

**Comment by davinanaya** [comment]
Is there a way to run `HUSKY_SKIP_HOOKS=1`  in background when i run rebase ? is kind of tricky because if some one comes to a project and wants to make a rebase he dont know he needs to use HUSKY_SKIP_HOOKS. thanks

**Comment by qpxtWhite** [comment]
@davinanaya I add some script to pre-commit hook
```shell
BRANCH_NAME=$(git branch | grep '*' | sed 's/* //')
if [[ $BRANCH_NAME =~ "no branch" ]]; then
  echo "You are rebasing, skipping hook"
  exit 0
fi
```

**Comment by thoran** [comment]
In case you got here like I did and you're looking for what to do currently, then instead use `HUSKY=0` if you want to skip the hooks.
