### ISSUE TITLE
test screen freezes when there is no test 

### ISSUE THREAD

**Issue by MilanRgm** [typicode/husky#489]
I am using `pre-commit` and `pre-push` hooks. `pre-push` hooks for running the tests. However, if there is no test file, then the screen freezes saying `No tests found` and I cannot push the code.

Here is the configuration

```javascript
"scripts": {
     "test": "react-scripts test",
     "precommit": "lint-staged",
 },
"husky": {
    "hooks": {
      "pre-commit": "yarn precommit",
      "pre-push": "yarn test"
    }
  },
```
<img width="791" alt="Screen Shot 2019-05-10 at 1 04 56 PM" src="https://user-images.githubusercontent.com/17469150/57742724-0c25c880-76e2-11e9-9152-26ba139f877a.png">

**Comment by typicode** [comment]
Hi @MilanRgm,

Sorry I'm not familiar enough `react-scripts`, from the screenshot it seems to be running in watch mode and not exiting. That's the reason why push is blocked, it's waiting for `yarn test` to finish.

Closing as there's not much that can be done on husky's side.

**Comment by helena-charles** [comment]
I am having this same issue but the issue does not replicate when running without husky.

@typicode

**Comment by s-pic** [comment]
@helena-charles 
I had the same problem, the following solution fixed it for me:
```diff
-    "test": "react-scripts test",
+    "test": "react-scripts test --watchAll=false",
+    "test:watch": "react-scripts test",
```

I am running `test:watch` locally and `test` pre-push.
