### ISSUE TITLE
I understand this works with GUI's but what about Github's Desktop Client?

### ISSUE THREAD

**Issue by lasergoat** [typicode/husky#49]
I have installed node with the standard installer.

I have husky working in the CLI but Github Desktop Client acts like there are no scripts to run.

**Comment by iamstarkov** [comment]
maybe it is the problem with github desktop?

**Comment by typicode** [comment]
Hi,

What's the output of `which node`? You're on OS X?

**Comment by lasergoat** [comment]
`/usr/local/bin/node`

**Comment by typicode** [comment]
> I believe that something within the husky generated script skips the entire hook if node isn't found.

It checks if `npm` is available in `$PATH` and fails otherwise. I suspect that `$PATH` may not be the same when the git hook script is run from GitHub Desktop.

If you want verify it, you can run:

```sh
my-project$ echo $PATH

# echo $PATH in some file when pre-commit is called
my-project$ mv .git/hooks/pre-commit .git/hooks/pre-commit.bak
my-project$ echo 'echo $PATH > ../../precommit-path' > .git/hooks/pre-commit

# try to make a commit from GitHub Desktop and check the output
my-project$ cat precommit-path
```

Sorry I'm on Linux right now, so I can't test it.
There may be a setting in GitHub Desktop to edit `PATH`.

**Comment by typicode** [comment]
Quick update, works with `nvm` + `GitHub Desktop`.
Need to test with Node installed differently.

**Comment by skhilko** [comment]
I confirm, husky hooks don't work for GUI clients with Node installed without use of `nvm`. When I use SourceTree to commit something, I see the following error:
`husky - can't find npm in PATH. Skipping precommit script in package.json`
I'm pretty sure it fails the same in GitHub Desktop.

@typicode, you're exactly right:
> I suspect that $PATH may not be the same when the git hook script is run from GitHub Desktop.

After some research I found that GUI apps on mac didn't respect `$PATH` value set for terminal environment.

I've installed node via homebrew. Both `node` and `npm` are installed under `/usr/local/bin`. (as you'd installed them with a standard installer)

`/usr/bin:/bin:/usr/sbin:/sbin` is the `$PATH` value when committing from SourceTree.

I know that this is not really a husky issue, that is simply how mac GUI apps work. However, if we could include `/usr/local/bin` when husky generates the hooks, that would've resolved the issue for many people without the need of finding [the unreliable solution and tinkering with the system](http://apple.stackexchange.com/questions/51677/how-to-set-path-for-finder-launched-applications).

**Comment by typicode** [comment]
> I know that this is not really a husky issue, that is simply how mac GUI apps work. However, if we could include /usr/local/bin when husky generates the hooks

I agree :), do you want to make a PR?

**Comment by typicode** [comment]
Should be good with `v0.11.8`.
Thank you @skhilko

**Comment by nick-woodward** [comment]
Still seeing the original issue of the `pre-commit` hook running from the CLI, but getting skipped in GUIs.

OS: Windows 7
GUI: GitHub Desktop

**Comment by iamstarkov** [comment]
@nick-woodward is it with latest husky?

**Comment by nick-woodward** [comment]
@iamstarkov Sorry forgot to mention that. Yes I'm using 0.11.8.

**Comment by damusnet** [comment]
Hi, somehow I still that exact same issue as well:

**OS:** macOS Sierra 10.12.4
**GUI:** GitHub Desktop
`which node = /usr/local/bin/node`
`node --version = v7.9.0` installed with Homebrew
`"husky": "^0.13.3"` with `yarn add husky --dev --force`

Am I missing something? Thanks in advance!

**Comment by damusnet** [comment]
Nevermind! I just had removed another precommit lib (`precommit-hook`) and had to remove all hooks `rm -f .git/hooks/*` and run `yarn add husky --dev --force` again. Now all works fine!

**Comment by jbcpollak** [comment]
I'm having this problem with nodenv installed, since `/usr/local/bin/nvm` doesn't exist. I don't have a solution yet.

**Comment by lasergoat** [comment]
@jbcpollak did you figure it out?

**Comment by jantimon** [comment]
@jbcpollak @lasergoat my work a round for nodenv is the following:
Create a new file: `~/.nvm/nvm.sh` with the following content:

```
#!/bin/bash
eval "$(nodenv init -)"
```

As husky executes the nvm.sh it will also initialize nodenv.

**Comment by jbcpollak** [comment]
@jantimon that's a great idea - I'll try it. I had been installing a copy of node directly through homebrew, but I'll try this solution instead.

**Comment by jonaskkristensen** [comment]
How did you solve this issue? I'm now getting the error `Commit failed - exit code 1 received, with output: 'Husky requires Node 8.6.0, can't run Git hook.'` - guess its the same issue? Using github desktop 2.2.4

**Comment by lasergoat** [comment]
@jonaskkristensen  I never did solve this, it just started working after their PR and me switching to the newer github client when it came out. What node version are you? 

```node --v```

or if using nvm, do `nvm list` and see which is your default version.

Make sure it's higher than 8.6.0
