### ISSUE TITLE
cannot install husky

### ISSUE THREAD

**Issue by zhe2chen** [typicode/husky#496]
npm ERR! Linux 4.15.0-50-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! yorkie@2.0.0 install: `node bin/install.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the yorkie@2.0.0 install script 'node bin/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the yorkie package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node bin/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs yorkie
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls yorkie
npm ERR! There is likely additional logging output above.

**Comment by typicode** [comment]
Hi @zhe2chen,

It seems to be related to yorkie, which is a fork of husky.

I don't really know why you're getting this error. Apparently, `bin/install.js` can't be found.
I would try maybe to remove `node_modules`  and reinstall.
