### ISSUE TITLE
Does husky respect a  .huskyrc in the git root directory?

### ISSUE THREAD

**Issue by helt** [typicode/husky#499]
I have a multi-language monorepo project with multiple build systems (i.e. maven for java and yarn/lerna for javascript).

The directory setup is somewhat complicated. Multiple unrelated javascript projects live side-by-side. I want to start centralizing configuration. And the husky hooks are one of them. 

Now i wonder if it is possible to place the `.huskyrc` into the root directory (next to README.md) just like my root `.gitignore`. To my knowledge, only a `~/.huskyrc` is used, and that one is individual per user...

**Comment by G-Rath** [comment]
I think a good solution to this could be a property in `.huskyrc.json` - something like `root` or `monorepo` maybe?

Either way, to me that's a nice simple solution: when installing, once you've found a `.git`, before actually installing check if theres a husky config, and if it has `"root/monorepo/whatever": true` bail out, maybe w/ a log along the lines of "config asked us not to install, as they're already installed".

Better yet: you could actually check for a `package.json` w/ `husky` as a dependency.

@typicode let me know if you'd be interested in this, as I'm happy to attempt a PR 🙂

**Comment by arcanis** [comment]
I think I'd also be interested in a per-repo `.huskyrc` file in the context of https://github.com/yarnpkg/berry/issues/102 - but JSON likely wouldn't work, as in my use case I'd need this file to be run as part of the Husky shellscript, not Husky itself.

**Comment by bradleyayers** [comment]
Yes at the moment only `~/.huskyrc` is checked https://github.com/typicode/husky/blob/8b9989f0696e0f0c330991ebe46e93181d2f9ad8/src/installer/getScript.ts#L21

**Comment by G-Rath** [comment]
Interesting; so are you saying this functionality already exists, but it's based on the existence of  `~./huskyrc`?

Right now my use of husky is working fine w/ `.huskyrc.json` in my projects root.

I've not explored the `husky` code base yet to know how it does its installs, but if you're happy to help me understand & find a starting point, I'm more than happy to try and implement this feature :)

(I do slightly worry about what'll it be like when it comes time to implement the tests however :joy:)

**Comment by typicode** [comment]
Thanks for the feedback, interesting idea. No plan to support that directly as it's a bit of an edge case.
That said, hooks could be configured manually to load a file in git root.
