### ISSUE TITLE
Question: Why does husky findUp git?

### ISSUE THREAD

**Issue by G-Rath** [typicode/husky#502]
I'm breaking this out from #499

I've got a project whose nature requires having multiple mini-projects ("templates") in a directory of the project, all of which are committed to git.

When husky installs, it uses `find-up` to look up recursively until it finds a parent folder w/ a `.git` file or folder:

https://github.com/typicode/husky/blob/8b9989f0696e0f0c330991ebe46e93181d2f9ad8/src/installer/index.ts#L138

This means that if you install husky in `root/a/b/c`, it'll set `root/.git` to call husky in `root/a/b/c`.

My question is: Why?

Personally, I'd think you'd want to just check if the `package.json` root had a `.git` file or folder (so `/c` in this example); otherwise you're running scripts that are hidden away in nested folders, and also need to make sure the packages are actually installed if they're critical to your project (or it's flow).

It could be I've completely missed a valid use case, hence the question :)

**Comment by typicode** [comment]
Hi @G-Rath,

It's because some users have their package.json in nested directory and can't move it to Git root. That seems to happen mostly with enterprise projects. 

```sh
.git
front/package.json
back/ # May not be in Node but in some other tech
```

**Comment by G-Rath** [comment]
Hi @typicode - thanks for the response.

That seems a bit weird to me, as why would not be able to move `husky` to the git root?

As I've said, IMO if you're going to use `husky` to manage your git hooks, theres no reason why you can' stick it at the same level as the `.git`, since it'll override any other hooks anyway?

So in your example:
```
.git
front/package.json # this is fine - contains things for front
back/ # also fine
package.json # this is where husky should be IMO
```

Of course, this is my opinion, and I'm sure there are some valid reasons for why that won't work. Either way; nothing I can do :) 

In saying that, it does make me a little uncomfortable as there's no bail out condition - if I install husky by mistake in a folder w/o git, it'll just keep going up until it reaches the top of the drive (or of course finds a `git` repo).

(Ironically, I found the other day I had actually managed to create a git repo of my C:\ drive by mistake, w/o realising it, which is part of the reason why this makes me a little paranoid)

----
Originally, I was going to suggest passing a [predicate](https://github.com/sindresorhus/find-up#matcher) function to `find-up`, but then after looking at the code some more, I realised you actually get the config *before* searching for the nearest `.git`, and bail out if you can't find it in the same directory as the `node_modules` the `husky` package is installed in.

That makes the whole thing a lot simpler: would you be open to having a `root` config property, like [`eslint`s `root`](https://eslint.org/docs/user-guide/configuring#using-configuration-files-1), that if `true` means `husky` only looks for `.git` in the same directory as it's `package.json`?

It should just be a matter of the following:
```
const gitDirOrFile = conf.root
    ? fs.existsSync(path.join(userPkgDir, '.git'))
    : findUp.sync('.git', { cwd: userPkgDir })
```

Let me know if you'd be interested in supporting that, and I'll break it out into a new issue + PR (w/ tests 😬). I think this might solve #499, but suspect I might be not be understanding what the issue is actually about 🙂

**Comment by abbottdev** [comment]
Just for reference - I am here trying to find a config setting to specify the `.git` dir because my org does have a front/back type scenario. (We also are using NPM utilities within different language repos, as the tooling for NPM is better 🙉) As I've now discovered, if husky walks up that actually is exactly what I need! ❤️

**Comment by typicode** [comment]
Behavior has been changed in v5. Git dir needs to be specified if it's at a different level than `.package.json`. Thanks for the feedbacks :+1:
