### ISSUE TITLE
Install script failing on older versions of node

### ISSUE THREAD

**Issue by nlucero** [typicode/husky#503]
`husky@2.4.1` install script is failing using `node` `v8.1.3`:

```
$ node -v
v8.1.3

$ npm i husky@latest

> husky@2.4.1 install /Users/nlucero/repos/personal/husky-node-8.1.3/node_modules/husky
> node husky install

/Users/nlucero/repos/personal/husky-node-8.1.3/node_modules/pkg-dir/node_modules/find-up/index.js:28
		const foundPath = await runMatcher({...options, cwd: directory});
		                                    ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/nlucero/repos/personal/husky-node-8.1.3/node_modules/pkg-dir/index.js:3:16)
npm WARN husky-node-8.1.3@1.0.0 No description
npm WARN husky-node-8.1.3@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! husky@2.4.1 install: `node husky install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the husky@2.4.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/nlucero/.npm/_logs/2019-06-13T17_12_19_441Z-debug.log
```

Since I couldn't find anything on the `README` about which versions of `node` are supported, I'm assuming this is a bug. It was working before using the same `node` version (at least for `"husky": "^1.3.1"`)

**Comment by alvincrespo** [comment]
This is happening to us as well. Just hit the above using the CircleCI docker image `circleci/node:chakracore-8.10.0-browsers`.

**Comment by typicode** [comment]
Hi,

@nlucero can you try upgrading your version of Node, I've tried with 8.16.0 but fails with 8.1.3.

@alvincrespo I'm not sure that Node ChakraCore support the spread operator. I'd suggest switching to Node 8 if possible.

Alternatively, you can use HUSKY_SKIP_INSTALL=1 if you're CI is not detected and husky tries to install itself.

**Comment by typicode** [comment]
https://github.com/typicode/husky/pull/512 I've updated `package.json` engines. This way next version of husky will display a message if used with something lower than 8.6.0.

**Comment by alvincrespo** [comment]
@typicode Thanks for the update. We moved to node:8-10.0-browsers on CI and it worked.
