### ISSUE TITLE
Wrong CWD on `git push . ref:branch`

### ISSUE THREAD

**Issue by Vovan-VE** [typicode/husky#505]
I did search similar issues, but did not find same. Sorry if it is duplicate.

Sometimes I'm too lazy and do fast-forward merge with one command `git push . topic:master` when HEAD is `topic`. Usually we do `git checkout master` and `git merge topic` for this.

So, when I do `git push . topic:master`, husky shows errors (debug on):

```
husky:debug pre-push hook started
Total 0 (delta 0), reused 0 (delta 0)
remote: husky:debug pre-receive hook started
remote: Can't find Husky, skipping pre-receive hook
remote: You can reinstall it using 'npm install husky --save-dev' or delete this hook
remote: husky:debug update hook started
remote: Can't find Husky, skipping update hook
remote: You can reinstall it using 'npm install husky --save-dev' or delete this hook
remote: husky:debug post-receive hook started
remote: Can't find Husky, skipping post-receive hook
remote: You can reinstall it using 'npm install husky --save-dev' or delete this hook
remote: husky:debug post-update hook started
remote: Can't find Husky, skipping post-update hook
remote: You can reinstall it using 'npm install husky --save-dev' or delete this hook
```

I did check CWD from `pre-receive` hook : it was `/path/to/repo/.git` .

Husky: 2.4.1
Git: 2.17.1

**Comment by typicode** [comment]
Closing as it may have been fixed by Husky v4 changes. Feel free to re-open if that's not the case :+1:
