### ISSUE TITLE
Support $npm_execpath

### ISSUE THREAD

**Issue by edwardgalligan** [typicode/husky#506]
This feature request is a bit of an extension of #102 but should be simpler to implement than actively supporting multiple package managers.

[`$npm_execpath`](https://github.com/npm/npm-lifecycle/blob/dbbfe27804b385a482b1dc369be6b6ce34e97c80/index.js#L82) is a variable supported by NPM in NPM scripts to refer to itself. It's purpose is that it can then be used by alternative package-managers to refer to themselves if they support running npm scripts (e.g. yarn supports this variable).

Example code:

```json
{
  "scripts": {
    "a": "echo 'hi'",
    "b": "$npm_execpath a"
  },
  "husky": {
    "hooks": {
      "pre-push": "$npm_execpath a"
    }
  }
}
```

With the above config, `yarn run b` will work, but the husky hook won't.

**Comment by typicode** [comment]
Hi @edwardgalligan 

Interesting, thanks for sharing. Not sure yet how it could be supported by husky.

**Comment by edwardgalligan** [comment]
> *Not sure yet how it could be supported by husky.*

I'm curious: do you mean you haven't decided how it would be implemented best, or that you don't understand the feature request? I can elaborate if it's the latter.

**Comment by typicode** [comment]
I can see the benefit but don't know how it would be implemented. I'm keeping it in mind though.

**Comment by h0ru5** [comment]
Interestingly, we had it working like this, but it stopped working with Node version 14.11.0
