### ISSUE TITLE
Can we use node script instead? (argv is empty)

### ISSUE THREAD

**Issue by mk0y** [typicode/husky#514]
Hi all,

I'm working on a commit-msg hook, but I'm writing it in Node.

Problem is that then process.argv is empty in such scripts.

My file begins with:
```
#!/usr/bin/env node
```

And it only contains `console.log(process.argv)`.

Husky hook in package.json is `"commit-msg": "scripts/commit-msg.js -E HUSKY_GIT_PARAMS"`. (file has been chmod +x)

Console.log only has array of:
```
[ '/usr/local/Cellar/node/11.12.0/bin/node', '/path/to/scripts/commit-msg.js', '-E', 'HUSKY_GIT_PARAMS']
```

So my question is how to pass git params (a commit message) to node scripts?

**Comment by mk0y** [comment]
I'm reading commit message from 
```
const msg = fs.readFileSync(path.join(__dirname, '../.git/COMMIT_EDITMSG'), { encoding: 'utf8' })
```

**Comment by rheaditi** [comment]
If anyone finds this issue, here's how I got it to work in a node script:
`"commit-msg": "scripts/commit-msg.js -E HUSKY_GIT_PARAMS"`

scripts/commit-msg.js: 
```js
#!/usr/bin/env node
const fs = require('fs');
const {
  HUSKY_GIT_PARAMS: gitMessagePath,
} = process.env;

const message = fs.readFileSync(gitMessagePath, { encoding: 'utf8' });

```
