### ISSUE TITLE
npm registry shows 2.4.1 as the latest instead of 2.6.0

### ISSUE THREAD

**Issue by cherukumilli** [typicode/husky#517]
```
$ npm outdated
Package  Current  Wanted  Latest  Location
husky      2.6.0   2.6.0   2.4.1  my-app
```

is this deliberate?

![Screen Shot 2019-06-27 at 8 29 02 AM](https://user-images.githubusercontent.com/5217007/60270478-1ed11700-98b6-11e9-82d8-82413fc41a1b.png)

**Comment by langpavel** [comment]
Confirmed. `latest` tag is outdated on `npm`.

**Comment by typicode** [comment]
Hi @cherukumilli,

Yes, it's deliberate, husky `2.6.0` appears to not work with older versions of Git so I've changed back `latest` to `2.4.1`. I'll probably release a `3.0.0` with the breaking changes from `2.6.0` instead.

**Comment by typicode** [comment]
I've just republished `2.4.1` as `2.7.0`

**Comment by langpavel** [comment]
Yep, it's there
