### ISSUE TITLE
Tag release 2.7.0

### ISSUE THREAD

**Issue by Arcanemagus** [typicode/husky#519]
Could the 2.7.0 release be tagged on the repository so we have a reference point and the changelog can be determined by tools that check version updates? Thanks!

**Comment by typicode** [comment]
Hmm not sure how to do it. I republished from v2.4.1 commit as a temporary fix and I'm not sure if it's possible to tag twice the same commit.

A v3.0.0 is on its way so v2.7.0 should stay long. Sorry I guess it's not ideal.

**Comment by typicode** [comment]
https://github.com/typicode/husky/issues/520

**Comment by Arcanemagus** [comment]
Btw, you can tag an older commit [like this](https://git-scm.com/book/en/v2/Git-Basics-Tagging#_tagging_later), but looking at how things were done that wouldn't work very well either since the changelog is still on `master`, I'll go ahead and just close this issue.
