### ISSUE TITLE
Pre-push hook not preventing git push

### ISSUE THREAD

**Issue by niniveLC** [typicode/husky#524]
I added a husky git hook on pre-push to enforce unit testing code-coverage using the command below, but even though the tests returns errors during git push, my code is still being pushed to github. Am I missing some configuration?

![image](https://user-images.githubusercontent.com/49163477/60375242-19aabf80-99bd-11e9-953b-60a14eab3c5c.png)

OS: Windows 10

package.json:
 "husky": {
    "hooks": {
      "pre-push": "ng test --code-coverage --watch=false",
      "...": "..."
    }
  },

Karma.conf.js:
 coverageIstanbulReporter: {
      dir: require('path').join(__dirname, '../coverage'),
      reports: ['html', 'lcovonly'],
      fixWebpackSourcePaths: true,
      thresholds: {
        statements: 90,
        lines: 90,
        branches: 90,
        functions: 90
      }
    },

**Comment by typicode** [comment]
Hi @niniveLC,

It's usually because the `pre-push` script defined in `package.json` exits with a 0 status code (it needs to be different than 0 to block `git push`).

**Comment by niniveLC** [comment]
got it, thank you
