### ISSUE TITLE
How to define shell command in a .huskyrc.js file ?

### ISSUE THREAD

**Issue by ethyde** [typicode/husky#525]
Hi,

I try to configure my huskyrc.js file with something like the [loading for NVM](https://github.com/typicode/husky/blob/master/DOCS.md#huskyrc), but i don't know how to do that ?
I have to add a package for shell commands ?

Thanks.

**Comment by typicode** [comment]
Hi,

Shell commands should work, no package necessary.

**Comment by ethyde** [comment]
Hi,

Thanks for your quick answer, but how to write shell command in a js file ? I found no examples with shell and JS commands in the same file

**Comment by typicode** [comment]
Maybe I'm misunderstanding but what about:

```js
// huskyrc.js
module.exports = {
  hooks: {
    'pre-commit': 'export NVM_DIR="$HOME/.nvm" && [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh",
    'pre-push': 'sh some_script.sh'
  }
}
```

That said it's not recommended to load `nvm`  this way as not everyone uses `nvm`  (Windows users for example).

**Comment by ethyde** [comment]
Oh yes, thanks, it's exactly what i need !

Thanks for the point about nvm, at this moment all my environnement use it so it's not a problem.
