### ISSUE TITLE
Detect the package.json in the subdirectory

### ISSUE THREAD

**Issue by luka107** [typicode/husky#526]
I introduced husky(^3.0.0) to my package.json with these following configuration:
"husky": {
"hooks": {
"pre-commit": "cd ../../.. && gradle npmLint"
}
}
Unfortunately, I can't get anything even an error message from the husky, it looks like a normal commit without any hook.
The package.json is under the directory src/main/npm/, not in the root dir.

I thought I got a similar issue with #452

Another found is one of my dependencies use husky(^0.13.4) as the required lib, not for sure this is the root reason.

Thanks.

**Comment by luka107** [comment]
I introduced husky(^3.0.0) to my package.json with these following configuration:
"husky": {
    "hooks": {
      "pre-commit": "cd ../../.. && gradle npmLint"
    }
  }
Unfortunately, I can't get anything even an error message from the husky, it looks like a normal commit without any hook.
The package.json is under the directory `src/main/npm/`, not in the root dir.

I thought I got a similar issue with https://github.com/typicode/husky/issues/452

Another found is one of my dependencies use husky(^0.13.4) as the required lib, not for sure this is the root reason.

**Comment by typicode** [comment]
Hi,

What do you get if you set `HUSKY_DEBUG=1`

```
$ HUSKY_DEBUG=1 git commit ...
```

There should only be one husky dependency.

**Comment by luka107** [comment]
Thanks for quick response,

Unfortunately, even if I set HUSKY_DEBUG=1 but still don't get anything related to husky. Here is my output on the console:

[linqing@linqing mbtst (linqing/test-husky)]$ HUSKY_DEBUG=1 git commit -m "afaf"
[linqing/test-husky 4b574d67ae] afaf
 2 files changed, 4 insertions(+), 1 deletion(-)


I'm wondering what do I miss some configuration which caused the husky module to never be called?

I certainly added the husky dependency to package.json.
[linqing@linqing mbtst (linqing/test-husky)]$ ls src/main/npm/node_modules/husky/
CHANGELOG.md  DOCS.md  husky.js  lib  LICENSE  node_modules  package.json  README.md  run.js

**Comment by luka107** [comment]
Oops, I found something really interesting.

I first uninstall husky
and run `HUSKY_DEBUG=1 npm install husky@3.0.0 --save-dev`

Then I got this:

[linqing@linqing mbtst (linqing/test-husky)]$ HUSKY_DEBUG=1 npm install husky@3.0.0 --save-dev

> husky@3.0.0 install /home/linqing/node_modules/husky
> node husky install

husky:debug cwd: /home/linqing/node_modules/husky
husky:debug INIT_CWD: /home/linqing/ccname/ccgroup/mbtst
husky > Setting up git hooks
fatal: not a git repository (or any of the parent directories): .git
husky > Failed to install

> husky@3.0.0 postinstall /home/linqing/node_modules/husky
> opencollective-postinstall || true

Thank you for using husky!
If you rely on this package, please consider supporting our open collective:
> https://opencollective.com/husky/donate

npm WARN saveError ENOENT: no such file or directory, open '/home/linqing/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/linqing/package.json'
npm WARN linqing No description
npm WARN linqing No repository field.
npm WARN linqing No README data
npm WARN linqing No license field.

I think there should be a bug when I install the husky module.
The right package.json path should be: `/home/linqing/ccname/ccgroup/mbtst/src/main/npm/package.json` instead of `/home/linqing/package.json`

**Comment by luka107** [comment]
After using "HUSKY_DEBUG=1" to reinstall the husky module, I found the reason why I didn't start any hooks is I installed failed in my last time.

I run the install command in the root directory instead of `src/main/npm`(the correct path).

Overall, thanks for the quick response, I closed this issue.

**Comment by typicode** [comment]
Glad I could help
