### ISSUE TITLE
I can't get $param in husky script?

### ISSUE THREAD

**Issue by zzzgit** [typicode/husky#527]
![image](https://user-images.githubusercontent.com/1060733/60637793-632c5c00-9e4e-11e9-887f-028d925639e1.png)

I wrote this like above, and then I got: 

![image](https://user-images.githubusercontent.com/1060733/60637820-8820cf00-9e4e-11e9-8e5e-8a41a2f86fcc.png)

Why the variable could not be interpreted?

**Comment by mrfelton** [comment]
Also not working for me

**Comment by zzzgit** [comment]
no solution yet?

**Comment by typicode** [comment]
I can't seem to be able to reproduce the issue:

```
$ cat .huskyrc.js
module.exports = {
  hooks: {
    'prepare-commit-msg': 'echo $HUSKY_GIT_PARAMS && exit 1',
  }
}

$ git commit -m test
husky > prepare-commit-msg (node v12.8.1)
.git/COMMIT_EDITMSG message
...
```

What's your OS/Terminal/Git client?
Can you try changing `prepare-commit-msg` to this:

```sh
'prepare-commit-msg': 'node index.js'
```

```js
// index.js
console.log('HUSKY_GIT_PARAMS', process.env.HUSKY_GIT_PARAMS)
```

**Comment by zzzgit** [comment]
> ```shell
> node index.js
> ```

win7, git bash

> Can you try changing prepare-commit-msg to this:

![image](https://user-images.githubusercontent.com/1060733/64851375-d837c100-d649-11e9-94e8-1ed135a83cf9.png)

**Comment by MartinYounghoonKim** [comment]
I have same issue. any update ?

**Comment by typicode** [comment]
Closing as HUSKY_GIT_PARAMS has been removed in v5. Also the most recent v4 has received a fix regarding `prepare-commit-msg` on Windows https://github.com/typicode/husky/pull/737
