### ISSUE TITLE
Is it possible to run git commands within hooks?

### ISSUE THREAD

**Issue by dmitrizzle** [typicode/husky#530]
I'd like to create build files, add them to commit and create commit before pushing:

```
    "husky": {
        "hooks": {
            "pre-push": "yarn prettier && yarn lint:fix && yarn test && yarn build:staging && git add ./dist && git commit -m \"[husky auto] Add build files for Staging environment.\""
        }
    },
```

However, I get ejected with the first git command, from CLI:
```
nothing to commit, working tree clean
husky > pre-push hook failed (add --no-verify to bypass)
error: failed to push some refs to 'https://github.com/qxmd/calculate.git'
```

Is it at all possible to run git commands from Husky?

Thank you.

**Comment by fivethreeo** [comment]
I think the other commands are forked and not done before add and commit
Try

‘’’bash
    "husky": {
        "hooks": {
            "pre-push": "yarn prettier; yarn lint:fix; yarn test; yarn build:staging; git add ./dist ;git commit -m \"[husky auto] Add build files for Staging environment.\""
        }
    },
‘’’

**Comment by typicode** [comment]
Closing as it's an old issue.
