### ISSUE TITLE
Husky 3.0.0 does not create .git/hooks

### ISSUE THREAD

**Issue by dilumdarshana** [typicode/husky#532]
Version 3.0.0 does not create pre and post hooks inside .git/hooks directory. Anyone came a cross this problem ?

**Comment by typicode** [comment]
Hi,

Could you post the install logs please?
Also could you run install with HUSKY_DEBUG=1

**Comment by dilumdarshana** [comment]
Hi...

Looks like here is the problem,

```
husky > Setting up git hooks
Husky requires Git >= 2.13.2, please update Git
husky > Failed to install
```
I am using git 2.11.0. By the way, Husky 2.7.0 working fine with git 2.11.0. I see there is additional git version check on gitRevParse.ts

**Comment by typicode** [comment]
Yes, I'd suggest upgrading Git if possible or staying with Husky  2.7.0 until then.

**Comment by danburzo** [comment]
I just wanted to mention that in my case, husky@3.0.0 did _not_ throw an error upon installation. It was just that the hooks were not triggering...
