### ISSUE TITLE
husky failed with 2.22.0

### ISSUE THREAD

**Issue by evilebottnawi** [typicode/husky#533]
From install:
```
> husky@3.0.0 install /home/itgalaxy/web/dev0.cms.dev.itgalaxy.company/public_html/wp-content/themes/insteria/node_modules/husky
> node husky install

husky > Setting up git hooks
Husky requires Git >= 2.13.2, please update Git
husky > Failed to install
```

```
$ git --version
git version 2.22.0
```

**Comment by evilebottnawi** [comment]
my mistake - two git was installed (first from system, second from source)

**Comment by Anjing1993** [comment]
> my mistake - two git was installed (first from system, second from source)
How do you solve it ?

**Comment by Anjing1993** [comment]
@evilebottnawi Hi，how do you solve it ?

**Comment by evilebottnawi** [comment]
@Anjing1993 yep, i have two git installed version (one was compiled other was installed using `apt-get`)
