### ISSUE TITLE
Can I use husky only with yarn?

### ISSUE THREAD

**Issue by zverexe** [typicode/husky#536]
I installed latest husky and wanted to use it just with yarn.

I added that config to my package.json file:
```
"husky": {
    "hooks": {
      "pre-commit": "yarn jest",
      "pre-push": "yarn jest"
    }
  }
```
but when I do commit or push code, nothing happens, tests don't run.

**Comment by typicode** [comment]
Try to commit with `HUSKY_DEBUG=1 git commit ...`, you should see some logs.
Also can you paste the output of husky installation? Hooks may not have been set up.

**Comment by dilumdarshana** [comment]
You can do two things,
1. Check husky hooks are created inside .git/hooks folder
2. Try with "yarn run test" instead of "yarn test"

**Comment by zverexe** [comment]
@dilumdarshana I do not have such folder.

**Comment by zverexe** [comment]
@typicode this is what I have while rugnning comming with husky debug:
[husky-config 4819f970b] tets
 1 file changed, 1 insertion(+)

**Comment by zverexe** [comment]
this is what I have in console after installed husky:

info Direct dependencies
└─ husky@3.0.0
info All dependencies
├─ @types/normalize-package-data@2.4.0
├─ caller-callsite@2.0.0
├─ caller-path@2.0.0
├─ cosmiconfig@5.2.1
├─ execa@1.0.0
├─ get-stream@4.1.0
├─ husky@3.0.0
├─ import-fresh@2.0.0
├─ lines-and-columns@1.1.6
├─ nice-try@1.0.5
├─ opencollective-postinstall@2.0.2
├─ please-upgrade-node@3.1.1
├─ run-node@1.0.0
├─ semver-compare@1.0.0
└─ type-fest@0.6.0

**Comment by dilumdarshana** [comment]
What is your git version?

**Comment by zverexe** [comment]
git version 2.17.2

**Comment by dilumdarshana** [comment]
> @dilumdarshana I do not have such folder.

Your git version should be works fine with husky 3.0.0

Since you don't have this folder, something should be happening when setting up git hooks while package installation. Have you tried with this to debug the installation? 

``yarn add -D husky --verbose``

There should be some texts in the result 'husky > Setting up git hooks'.....

**Comment by zverexe** [comment]
[4/5] ⠄ husky
verbose 77.068 pre-commit:
pre-commit: Detected an existing git pre-commit hook
pre-commit: Old pre-commit hook backuped to pre-commit.old
pre-commit:
only this

**Comment by zverexe** [comment]
okay now I have this when I commit something:
pre-commit:
pre-commit: We have nothing pre-commit hooks to run. Either you're missing the `scripts`
pre-commit: in your `package.json` or have configured pre-commit to run nothing.
pre-commit: Skipping the pre-commit hook.
pre-commit:

**Comment by zverexe** [comment]
I fixed the bug, I reinstalled npm according to https://gist.github.com/DanHerbert/9520689 
but I cannot run pre commit hook when commit changes through webstorm
