### ISSUE TITLE
Look forward to the support of gerrit

### ISSUE THREAD

**Issue by repairearth** [typicode/husky#538]
Any plan or any workarounds?

**Comment by typicode** [comment]
Hi @repairearth,

What's the issue with gerrit?

**Comment by repairearth** [comment]
Hi @typicode 

The main problem is gerrit need to append/prepend some scripts into the hooks created by husky.
For example, generate a `Change-Id` in the end of message in `commit-msg` hook. 
So the requirement is to append extra scripts to hooks when husky is installed.
Maybe we can put these extra scripts into `.huskyrc.js` like this:
```json
{
  extraScripts: {
    'commit-msg': `add_ChangeId() ...`
  }
}
```

**Comment by typicode** [comment]
I've checked Gerrit docs and it seems like Change-id is just shell script.
I have't tested it, but theorically I suppose it should be possible to call it like this?

`.huskyrc`

```json
{
  "hooks": {
    "commit-msg": "<other commands> && ./scripts/change-id.sh"
  }
}
```

**Comment by luisxiaomai** [comment]
@typicode @repairearth , above approach did not work for me. Do you have any other workaround to let gerrit and husky commit-msg both works? 

https://github.com/HaitianLiu/husky-gerrit this repo seems to solve this problem, but it seems be out of date.

**Comment by bharatpatil** [comment]
I’m also looking for the solution.

**Comment by avakin** [comment]
@typicode @bharatpatil @luisxiaomai Hi, guys! Any support or solution for Gerrit? 

Have added the pre-commit hook, but now I'm getting the problem with Change-id.

**Comment by W-ChenAMG** [comment]
Is there a solution to this problem?

**Comment by SarahLyu** [comment]
+1

**Comment by l-hammer** [comment]
+1

**Comment by W-ChenAMG** [comment]
可以暂时将 .git下面的hooks文件中要用的钩子  复制出来，放在husky文件下方 ，这样使用

**Comment by ewawadr** [comment]
Issue might be related to husky behavior change in v4 -> v7, https://blog.typicode.com/husky-git-hooks-javascript-config/
Gerrit hook exists in `.git/hooks/commit-msg` , however it's not executed.
One way for workaround is to run script provided by Gerrit and copy hook from `.git/hooks/commit-msg` to `.husky/commit-msg` and finally run `husky install`.

**Comment by yanhaijing** [comment]
> Issue might be related to husky behavior change in v4 -> v7, https://blog.typicode.com/husky-git-hooks-javascript-config/ Gerrit hook exists in `.git/hooks/commit-msg` , however it's not executed. One way for workaround is to run script provided by Gerrit and copy hook from `.git/hooks/commit-msg` to `.husky/commit-msg` and finally run `husky install`.

That's a good idea. Any examples

**Comment by avakin** [comment]
Have resolved the issue, but using `lint-staged` library, but the approach is the same. Have tried to made this one common.

So, have resolved the issue by creating custom .sh script. 

For gerrit we need change-id that is installed via .sh script. Also I needed to add my custom .pre-commit hook for running linters, formatters, etc. 
So. Creating custom folder near **.git** folder like **.githooks**, into this one you can create .pre-commit bash script where you can add commands to choose staged files and run npm scripts:


`#!/bin/sh`
`FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')`
`reactDir='./$react-app-folder/'`

`[ -z "$FILES" ] && exit 0`

`cd $reactDir`
`echo "$FILES" | npm run $npm_scipt_name`
`echo "$FILES" | xargs git add`

`exit 0`

Then, create into your `src` folder `.init_git_hooks.sh` script with: 

`rootDir=$(git rev-parse --show-toplevel);
hooksDir=${rootDir}/.githooks;
git config core.hooksPath $hooksDir;
$ curl -Lo ${hooksDir}/commit-msg http://review.example.com/tools/hooks/commit-msg
chmod +x ${hooksDir}/commit-msg`

Into the package.json you can add script for your and  your team comfort like 

`"scripts": {
    "init-hooks": "./init_git_hooks.sh"
  },`

**Comment by felipecrs** [comment]
My suggested workaround is

```diff
- "prepare": "husky install"
+ "prepare": "curl -fsSL https://review.gerrithub.io/tools/hooks/commit-msg -o .husky/commit-msg && chmod +x .husky/commit-msg && husky install"
```

And, ofc, add the `commit-msg` to the `.husky/.gitignore`.

**Comment by daxiongz** [comment]
> My suggested workaround is
> 
> ```diff
> - "prepare": "husky install"
> + "prepare": "curl -fsSL https://review.gerrithub.io/tools/hooks/commit-msg -o .husky/commit-msg && chmod +x .husky/commit-msg && husky install"
> ```
> 
> And, ofc, add the `commit-msg` to the `.husky/.gitignore`.

It's fine!

**Comment by gitrampal** [comment]
> Issue might be related to husky behavior change in v4 -> v7, https://blog.typicode.com/husky-git-hooks-javascript-config/ Gerrit hook exists in `.git/hooks/commit-msg` , however it's not executed. One way for workaround is to run script provided by Gerrit and copy hook from `.git/hooks/commit-msg` to `.husky/commit-msg` and finally run `husky install`.



> Issue might be related to husky behavior change in v4 -> v7, https://blog.typicode.com/husky-git-hooks-javascript-config/ Gerrit hook exists in `.git/hooks/commit-msg` , however it's not executed. One way for workaround is to run script provided by Gerrit and copy hook from `.git/hooks/commit-msg` to `.husky/commit-msg` and finally run `husky install`.

It worked !! thanks.
