### ISSUE TITLE
How to run husky pre-commit when commiting through Webstorm or other IDE?

### ISSUE THREAD

**Issue by zverexe** [typicode/husky#540]
Hi, I have such configs of husky:

"scripts": {
    "test": "jest"
  },
  "husky": {
    "hooks": {
      "pre-commit": "yarn jest"
    }
  }

node vv8.11.3

I use docker too.
Everything works fine when committing in the terminal, tests run, but when I use webstorm for commit, tests won't run, nothing happened basically. What do I need to do to run precommit script when committing in webstorm?

**Comment by fsarachu** [comment]
I had similar problems because husky was using a different node version than the current (using nvm with `.nvmrc`).
If you're using nvm, you can try [this](https://github.com/typicode/husky/blob/master/DOCS.md#huskyrc), it worked  for me.

**Comment by zverexe** [comment]
I added this 
```
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
```
to my .huskyrc and now after each commit through webstorm I see this message in the console:
```
pre-commit: 
pre-commit: Failed to locate the `npm` binary, make sure it's installed in your $PATH.
pre-commit: Skipping the pre-commit hook.
pre-commit: 
```

**Comment by zverexe** [comment]
I created .huskyrc in the project directory, is it right?

**Comment by zverexe** [comment]
any updates on this?

**Comment by typicode** [comment]
It seems like you have another git hooks manager conflicting with Husky. Check if you're `package.json` have a `pre-commit` as a dependency?

**Comment by redreceipt** [comment]
Same question, but for the Github merge button. I want it to fail if it doesn't pass my `pre-commit` hook. Is this possible?

<img width="243" alt="Screen Shot 2019-09-29 at 5 49 41 PM" src="https://user-images.githubusercontent.com/2659478/65840024-89448980-e2e1-11e9-8a9d-9fd13d6464a6.png">

**Comment by typicode** [comment]
@redreceipt AFAIK not possible.

**Comment by avshyz** [comment]
Same issue :\
(Precommit's not referenced in my requirements. Tried deleting .git/hooks/ and reinstalling husky)

**Comment by johannesjo** [comment]
@fsarachu the link is down. Could you maybe summarize what it contained?

**Comment by LogansUA** [comment]
Hey, I'm having the same issue

**Comment by thorne51** [comment]
> I added this
> 
> ```
> export NVM_DIR="$HOME/.nvm"
> [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
> ```

@zverexe Thanks for this. I was digging into why my PHPStorm kept failing on pre-commit hooks with the error "Yarn requires Node.js 4.0 or higher to be installed." This is after many iterations of fixing/breaking cycle. I had a look at the actual pre-commit hook file that was setup at `.git/hooks/pre-commit` in my project directory which only had the following (apart from some comments):
```
. "$(dirname "$0")/husky.sh"
```
In the same folder, looking at `husky.sh`'s contents, I noticed the following:
```
# Source user ~/.huskyrc
if [ -f ~/.huskyrc ]; then
  debug "source ~/.huskyrc"
  . ~/.huskyrc
fi
```

Since the issue seemed to be my local setup, I moved my `.huskyrc` file to my user home directory and updated my PATH with NVM in it:
```
# ~/.huskyrc
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
```

PHPStorm's commits seem to fire the git hooks correctly after this change.

**Comment by ErikCupal** [comment]
I had to adjust `.huskyrc` content like this:

```sh
# ~/.huskyrc
export NVM_DIR=~/.nvm
source $(brew --prefix nvm)/nvm.sh
```

because I installed nvm via homebrew.

After adding `.huskyrc` to `~`, git hooks in Webstorm work!

**Comment by meowto16** [comment]
If you use NVM, it's helped me (write in terminal):
`
n=$(which node); \
n=${n%/bin/node}; \
chmod -R 755 $n/bin/*; \
sudo cp -r $n/{bin,lib,share} /usr/local
`

from this answer https://stackoverflow.com/questions/21215059/cant-use-nvm-from-root-or-sudo

**Comment by milklim** [comment]
[This answer](https://stackoverflow.com/a/40078875) helps to resolve the issue
```
sudo ln -s "$NVM_DIR/versions/node/$(nvm version)/bin/node" "/usr/local/bin/node"
sudo ln -s "$NVM_DIR/versions/node/$(nvm version)/bin/npm" "/usr/local/bin/npm"
sudo ln -s "$NVM_DIR/versions/node/$(nvm version)/bin/npx" "/usr/local/bin/npx"
```

**Comment by sliminas** [comment]
For me this resolved the issue:
```sh
# in ~/.huskyrc
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
```

**Comment by ramaralo** [comment]
If using a `/.husky/pre-commit file, adding this also works:

```
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
```
