### ISSUE TITLE
Abort if commit ends up being empty

### ISSUE THREAD

**Issue by ThiefMaster** [typicode/husky#542]
This is easy to reproduce: Run some code formatter with husky's pre-commit hook, then edit a committed file that only introduces fixable code style violations, then commit it again. The hook will fix all the violations and in the end the commit is empty.

I think it would be nicer if committing was aborted in this case.

**Comment by Andreeh** [comment]
Any update on this?

**Comment by typicode** [comment]
Thanks for the suggestion, I can see the benefit.
That said, personally, I think it's a bit out of scope to be fixed on husky's side.
