### ISSUE TITLE
How to run a pre commit test that avoids the debug lines in the code?

### ISSUE THREAD

**Issue by dancalderon** [typicode/husky#546]
Hello.

I'm trying to use husky to check before every commit if my code contains any console.log or any debug line.

I'm using eslint and prettier with the wesbos configuration.

I'm trying to do it in a Next.js app

**Comment by typicode** [comment]
Hi @dancalderon,

Sorry for the late reply, you can do it this way in your `package.json`:

```json
{
  "scripts": {
    "test": "<your test runner>",
    "lint": "eslint <options fitting your project>"
  },
  "husky": {
    "hooks": {
      "pre-commit": "npm test && npm run lint"
    }
  }
}
```

For the particular `eslint` rule/config that would allow that, I don't know.

But you can manually run `npm run lint` to test if it catches debug lines. Husky will prevent commits when `npm run lint` fails.
