### ISSUE TITLE
Pre-push fail : unable to import Django in pre-push after husky upgrade

### ISSUE THREAD

**Issue by ymouscaz** [typicode/husky#547]
Hi,

I upgraded on my macOS 10.13.6 my node to v10.16.0 and husky to v3.0.0 and since this moment the pre-push for my Django project fails with this error : 

> husky > pre-push (node v10.16.0)
yarn run v1.5.1
$ python manage.py test --settings=MyDjangoProject.settings.dev MyDjangoProject/unit_tests/ --parallel 8 --noinput
Traceback (most recent call last):
  File "manage.py", line 17, in <module>
    "Couldn't import Django. Are you sure it's installed and "
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: sh
Arguments: -c python manage.py test --settings=MyDjangoProject.settings.dev MyDjangoProject/unit_tests/ --parallel 8 --noinput
Directory: /Users/Yoann/Pro/git_projects/MyDjangoProject
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "/Users/Yoann/Pro/git_projects/MyDjangoProject/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
husky > pre-push hook failed (add --no-verify to bypass)
error: failed to push some refs to 'git@gitlab.fr:myComp/MyDjangoProject.git'

I work with pyenv and virtualenv and it was ok before the upgrade.
I tried to : 

> rm -rf .git/hooks/ 
> npm i -D husky@3.0.0

but the error is still here...
I can run` python manage.py test --settings=MyDjangoProject.settings.dev MyDjangoProject/unit_tests/ --parallel 8 --noinput`without any problems in my env.

I printed `which python` in the .git/hooks/pre-push file to check if it's ok and it is (the same as in my env).

Now, I'm lost and I'm wondering if my best solution is to remove all this mess and reinstall it from scratch ...

To conclude, the error in yarn-error.log is : 

> Trace: 
  Error: Command failed.
  Exit code: 1
  Command: sh
  Arguments: -c python manage.py test --settings=MyDjangoProject.settings.dev MyDjangoProject/unit_tests/ --parallel 8 --noinput
  Directory: /Users/Yoann/Pro/git_projects/MyDjangoProject
  Output:
  
      at ProcessTermError.MessageError (/usr/local/lib/node_modules/yarn/lib/cli.js:186:110)
      at new ProcessTermError (/usr/local/lib/node_modules/yarn/lib/cli.js:226:113)
      at ChildProcess.<anonymous> (/usr/local/lib/node_modules/yarn/lib/cli.js:30281:17)
      at ChildProcess.emit (events.js:198:13)
      at maybeClose (internal/child_process.js:982:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)

Thanks a lot for your help.

**Comment by ymouscaz** [comment]
Hi,

A point after a month of multi tries : still the same pb and I really don't understand it ><
I upgraded macOS to 10.14.6 but not any magical effect on my issue with husky...
Does anyone here can help me please ?

Thanks a lot.

**Comment by typicode** [comment]
Hi @ymouscaz,

Not sure if that will help, but if you run `printenv` in the terminal and add it to `pre-push`:

```sh
"pre-push": "printenv && ..."
```

Do you see any notable differences between outputs? Especially in `PATH` related envs or envs used by Django?

**Comment by ymouscaz** [comment]
Hi @typicode,

Thanks for your answer !

This is the result of printenv directly in my virtualenv : 
`PATH=/Users/Yoann/.pyenv/shims:/usr/local/bin:/usr/local/sbin:/usr/local/Cellar/pyenv-virtualenv/1.1.1/shims:/Users/Yoann/.pyenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/opt/X11/bin`

And the one from "pre-push": "printenv && ..."

`PATH=/Users/Yoann/Pro/git_projects/MyDjangoProject/node_modules/.bin:/Users/Yoann/Pro/git_projects/node_modules/.bin:/Users/Yoann/Pro/node_modules/.bin:/Users/Yoann/node_modules/.bin:/Users/node_modules/.bin:/node_modules/.bin:/usr/local/bin:/usr/local/Cellar/git/2.17.1/libexec/git-core:/Users/Yoann/.pyenv/shims:/usr/local/bin:/usr/local/sbin:/usr/local/Cellar/pyenv-virtualenv/1.1.1/shims:/Users/Yoann/.pyenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/opt/X11/bin`

The difference is several paths in addition with the pre-push instructions : /Users/Yoann/Pro/git_projects/MyDjangoProject/node_modules/.bin:/Users/Yoann/Pro/git_projects/node_modules/.bin:/Users/Yoann/Pro/node_modules/.bin:/Users/Yoann/node_modules/.bin:/Users/node_modules/.bin:/node_modules/.bin:/usr/local/bin:/usr/local/Cellar/git/2.17.1/libexec/git-core

Do you know how can I remove them to test if they are the guilty guys ?

**Comment by ymouscaz** [comment]
In addition to my previous comment :
I tried to put "pre-push": "which python && ..." and I got : 
`/usr/local/bin/python` (my OS default Python v2.7.15), so it's not the one from my pyenv/virtualenv.

NB : if I tried directly "which python" in my pyenv/virtualenv I get : 
`/Users/Yoann/.pyenv/shims/python`

Not a big discover because the inital error (couldn't import Django) means that husky is not launched in my pyenv/virtualenv, but if it can be informative clue for you...

**Comment by ymouscaz** [comment]
Hi @typicode ,

I found a "dirty" way : if I set `"pre-push": "source ~/.profile && ..."` it works.
But : I'm not alone on the project and all the others dev are not on macOS... So, it's not an acceptable solution. 
Maybe it could help you to better understand the pb...

Nb : I tried to remove and reinstall the `node_modules/` of the project (with `yarn.lock` and `package-lock.json`), but it was the same stuff at the end

**Comment by typicode** [comment]
Hi @ymouscaz,

If you need to run specific commands only on your computer, you can add them in `~/.huskyrc`:
https://github.com/typicode/husky/blob/master/DOCS.md#huskyrc

Depending on what you have in `.profile`, it can make husky slow so you may want to only have `pyenv/virtualenv` related code.

**Comment by ymouscaz** [comment]
Hi @typicode ,

My `.profile` is not a big one to load.
But I tried with ~/.huskyrc on your advice and got no more success with it :'(

**Comment by typicode** [comment]
In theory, if `"pre-push": "source ~/.profile && ..."` fixes it, moving `source ~/.profile` to `~/.huskyrc` should produce the same result.

If you commit with `HUSKY_DEBUG=1 git commit ...`, do you see somewhere in the output:

```
# ...
husky:debug source ~/.huskyrc
# ...
```

If it doesn't appear, it means that it didn't find a `.huskyrc` in `~`.

**Comment by ymouscaz** [comment]
I'm agree with you : in theory it fixes it (Theory, what a nice country...! :) ). But it's not the case...
I moved `source ~/.profile` to `~/.huskyrc` as you mentioned it and commited with `HUSKY_DEBUG=1`, this is the output : 
```
(MyDjangoProject) 08:41ymouscaz@BA00087:~/Pro/git_projects/MyDjangoProject(test-branch) HUSKY_DEBUG=1 git commit -am"test"
husky:debug pre-commit hook started
husky:debug source ~/.huskyrc
husky:debug cwd: /Users/Yoann/Pro/git_projects/MyDjangoProject
husky:debug cwd: /Users/Yoann/Pro/git_projects/MyDjangoProject (updated)
husky:debug prepare-commit-msg hook started
husky:debug source ~/.huskyrc
husky:debug cwd: /Users/Yoann/Pro/git_projects/MyDjangoProject
husky:debug cwd: /Users/Yoann/Pro/git_projects/MyDjangoProject (updated)
husky:debug commit-msg hook started
husky:debug source ~/.huskyrc
husky:debug cwd: /Users/Yoann/Pro/git_projects/MyDjangoProject
husky:debug cwd: /Users/Yoann/Pro/git_projects/MyDjangoProject (updated)
husky:debug post-commit hook started
husky:debug source ~/.huskyrc
husky:debug cwd: /Users/Yoann/Pro/git_projects/MyDjangoProject
husky:debug cwd: /Users/Yoann/Pro/git_projects/MyDjangoProject (updated)
[test-branch a4b35793] test
 1 file changed, 3 insertions(+)
```

Then when I try to `git push`, the error message is still here :'(

**Comment by tacoto12** [comment]
Don't send me any more of the bullshit about Rosa's whoring skank ass. YOU can have her sorry ass because she is incapable of having a relationship above the level of a 10th grader in high school.  She is a liar,  thief, junkie, whore and two faces back stabbing piece of shit disloyal rat and I could not care less about whether or not she survives or doesn't 


Sent from my MetroPCS 4G LTE Android Device
-------- Original message --------From: Yoann Mouscaz <notifications@github.com> Date: 8/29/19  1:49 AM  (GMT-06:00) To: typicode/husky <husky@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: Re: [typicode/husky] Pre-push fail : unable to import Django in
  pre-push after husky upgrade (#547) 
I'm agree with you : in theory it fixes it (Theory, what a nice country...! :) ). But it's not the case...

I moved source ~/.profile to ~/.huskyrc as you mentioned it and commited with HUSKY_DEBUG=1, this is the output :
(MyDjangoProject) 08:41ymouscaz@BA00087:~/Pro/git_projects/MyDjangoProject(test-branch) HUSKY_DEBUG=1 git commit -am"test"
husky:debug pre-commit hook started
husky:debug source ~/.huskyrc
husky:debug cwd: /Users/Yoann/Pro/git_projects/MyDjangoProject
husky:debug cwd: /Users/Yoann/Pro/git_projects/MyDjangoProject (updated)
husky:debug prepare-commit-msg hook started
husky:debug source ~/.huskyrc
husky:debug cwd: /Users/Yoann/Pro/git_projects/MyDjangoProject
husky:debug cwd: /Users/Yoann/Pro/git_projects/MyDjangoProject (updated)
husky:debug commit-msg hook started
husky:debug source ~/.huskyrc
husky:debug cwd: /Users/Yoann/Pro/git_projects/MyDjangoProject
husky:debug cwd: /Users/Yoann/Pro/git_projects/MyDjangoProject (updated)
husky:debug post-commit hook started
husky:debug source ~/.huskyrc
husky:debug cwd: /Users/Yoann/Pro/git_projects/MyDjangoProject
husky:debug cwd: /Users/Yoann/Pro/git_projects/MyDjangoProject (updated)
[test-branch a4b35793] test
 1 file changed, 3 insertions(+)

Then when I try to git push, the error message is still here :'(

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/typicode/husky/issues/547?email_source=notifications\u0026email_token=AMATDU2FEDJ576QKUUHCO3DQG5WQPA5CNFSM4IFEK5O2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD5NOEJI#issuecomment-526049829",
"url": "https://github.com/typicode/husky/issues/547?email_source=notifications\u0026email_token=AMATDU2FEDJ576QKUUHCO3DQG5WQPA5CNFSM4IFEK5O2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD5NOEJI#issuecomment-526049829",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by typicode** [comment]
I'm running out of ideas here, sorry :/
I don't really understand why `source ~/.profile` would behave one way when called from "pre-commit" and a different way when called from `~/.huskyrc`.

Also I don't know `pyenv/virtualenv` enough.

Maybe this could help you figure out:

```
"pre-commit": "source ~/.profile && echo \"PATH from pre-commit $PATH\" && exit 1"
```

`exit 1` should let you iterate faster as every commit would fail.

In `~/.huskyrc`, you can try to add this:

```
source ~/.profile && echo "PATH from huskyrc $PATH"
```
 
PATH should be the same.

**Comment by ymouscaz** [comment]
Hi @typicode and thanks a lot again for your help.

These are the results of the two different echo $PATH (spoiler alert : they are not the same...) : 

`PATH from pre-commit /Users/Yoann/.yarn/bin:/Users/Yoann/.config/yarn/global/node_modules/.bin:/Users/Yoann/.pyenv/shims:/usr/local/bin:/usr/local/sbin:/usr/local/Cellar/pyenv-virtualenv/1.1.1/shims:/Users/Yoann/.pyenv/shims:/Users/Yoann/Pro/git_projects/MyDjangoProject/node_modules/.bin:/Users/Yoann/Pro/git_projects/node_modules/.bin:/Users/Yoann/Pro/node_modules/.bin:/Users/Yoann/node_modules/.bin:/Users/node_modules/.bin:/node_modules/.bin:/usr/local/bin:/Users/Yoann/.yarn/bin:/Users/Yoann/.config/yarn/global/node_modules/.bin:/Users/Yoann/.pyenv/shims:/usr/local/bin:/usr/local/sbin:/usr/local/Cellar/pyenv-virtualenv/1.1.1/shims:/Users/Yoann/.pyenv/shims:/usr/local/Cellar/git/2.17.1/libexec/git-core:/Users/Yoann/.yarn/bin:/Users/Yoann/.config/yarn/global/node_modules/.bin:/Users/Yoann/.pyenv/shims:/usr/local/bin:/usr/local/sbin:/usr/local/Cellar/pyenv-virtualenv/1.1.1/shims:/Users/Yoann/.pyenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/opt/X11/bin`

`PATH from huskyrc /Users/Yoann/.yarn/bin:/Users/Yoann/.config/yarn/global/node_modules/.bin:/Users/Yoann/.pyenv/shims:/usr/local/bin:/usr/local/sbin:/usr/local/Cellar/pyenv-virtualenv/1.1.1/shims:/Users/Yoann/.pyenv/shims:/usr/local/Cellar/git/2.17.1/libexec/git-core:/Users/Yoann/.yarn/bin:/Users/Yoann/.config/yarn/global/node_modules/.bin:/Users/Yoann/.pyenv/shims:/usr/local/bin:/usr/local/sbin:/usr/local/Cellar/pyenv-virtualenv/1.1.1/shims:/Users/Yoann/.pyenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/opt/X11/bin`

**Comment by typicode** [comment]
😅 ... Are you using a GUI Git client? Maybe try doing a `cat ~/.profile` in both `~/.huskyrc` and `package.json`, just to ensure that the same code is being sourced.

**Comment by ymouscaz** [comment]
Hi @typicode ,

I'm not using a GUI Git client, CLI only.
I made your verification : it's the same code which is being sourced. :/

**Comment by ymouscaz** [comment]
Another unsuccessful try : I remove my pyenv & virtualenv on my local and rebuilt them --> still the same result T_T

**Comment by fivethreeo** [comment]
I think this is because husky or git runs the command in another shell so it’s not picking up the active pyenv/virtualenv. Try ‘pyenv init; python manage.py test’.

**Comment by ymouscaz** [comment]
Hi @fivethreeo ,

Thanks for your help.
I tried your idea (but I've to say that I was a lil bit pessimistic about it because I set auto-activation of the pyenv environment) and this is the result : 
```
husky > pre-push (node v10.16.0)
# Load pyenv automatically by appending
# the following to your profile:

eval "$(pyenv init -)"

husky > pre-push hook failed (add --no-verify to bypass)
error: failed to push some refs to 'git@gitlab.fr:myComp/MyDjangoProject.git'
```

**Comment by fivethreeo** [comment]
Auto activation only affects current shell.

So maybe:

eval "$(pyenv init -)"; python manage.py test

or

echo 'eval "$(pyenv init -)"' > runtest.sh
echo 'python manage.py test' >> runtest.sh
chmod u=x runtest.sh

./runtest.sh

If that does not work I'm out of ideas ;)

**Comment by ymouscaz** [comment]
Hi @fivethreeo,

Great news : eval "$(pyenv init -)" solved the pb !!!
A big big thanks to you and to @typicode for your help and your time !

**Comment by typicode** [comment]
🎉 🙂

**Comment by kiruh** [comment]
I've got the same issue.
I don't use pyenv. I use virtualenv and virtualenvwrapper.

**package.json**
```json
// ...
"husky": {
    "hooks": {
        "pre-push": "python manage.py test --settings=cs.settings.test --failfast --parallel"
    }
},
// ...
```

**Environment:**
```bash
$ printenv
```

```bash
CLUTTER_IM_MODULE=xim
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
LC_MEASUREMENT=bg_BG.UTF-8
VIRTUALENVWRAPPER_WORKON_CD=1
LESSCLOSE=/usr/bin/lesspipe %s %s
LC_PAPER=bg_BG.UTF-8
LC_MONETARY=bg_BG.UTF-8
XDG_MENU_PREFIX=gnome-
VIRTUALENVWRAPPER_HOOK_DIR=/home/kiril/.virtualenvs
DJANGO_SETTINGS_MODULE=cs.settings.swimcloud.dev
LANG=en_US.UTF-8
_VIRTUALENVWRAPPER_API= mkvirtualenv rmvirtualenv lsvirtualenv showvirtualenv workon add2virtualenv cdsitepackages cdvirtualenv lssitepackages toggleglobalsitepackages cpvirtualenv setvirtualenvproject mkproject cdproject mktmpenv
DISPLAY=:0
OLDPWD=/home/kiril/projects/cs
WORKON_HOME=/home/kiril/.virtualenvs
GNOME_SHELL_SESSION_MODE=ubuntu
VIRTUALENV_PYTHON=/usr/bin/python3
COLORTERM=truecolor
USERNAME=kiril
XDG_VTNR=2
SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
VIRTUAL_ENV=/home/kiril/.virtualenvs/cs
LC_NAME=bg_BG.UTF-8
XDG_SESSION_ID=2
USER=kiril
DESKTOP_SESSION=ubuntu
QT4_IM_MODULE=xim
TEXTDOMAINDIR=/usr/share/locale/
GNOME_TERMINAL_SCREEN=/org/gnome/Terminal/screen/c0e31243_3c25_4944_9c25_a8bacb12e520
PWD=/usr/games
HOME=/home/kiril
TEXTDOMAIN=im-config
SSH_AGENT_PID=2489
QT_ACCESSIBILITY=1
XDG_SESSION_TYPE=x11
XDG_DATA_DIRS=/usr/share/ubuntu:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop
XDG_SESSION_DESKTOP=ubuntu
LC_ADDRESS=bg_BG.UTF-8
GJS_DEBUG_OUTPUT=stderr
LC_NUMERIC=bg_BG.UTF-8
PROJECT_HOME=/home/kiril/projects
GTK_MODULES=gail:atk-bridge
PAPERSIZE=a4
WINDOWPATH=2
VIRTUALENVWRAPPER_SCRIPT=/usr/share/virtualenvwrapper/virtualenvwrapper.sh
TERM=xterm-256color
SHELL=/bin/bash
VTE_VERSION=5202
QT_IM_MODULE=ibus
XMODIFIERS=@im=ibus
IM_CONFIG_PHASE=2
XDG_CURRENT_DESKTOP=ubuntu:GNOME
GPG_AGENT_INFO=/run/user/1000/gnupg/S.gpg-agent:0:1
GNOME_TERMINAL_SERVICE=:1.75
XDG_SEAT=seat0
SHLVL=1
LC_TELEPHONE=bg_BG.UTF-8
GDMSESSION=ubuntu
GNOME_DESKTOP_SESSION_ID=this-is-deprecated
LOGNAME=kiril
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
XDG_RUNTIME_DIR=/run/user/1000
XAUTHORITY=/run/user/1000/gdm/Xauthority
VIRTUALENVWRAPPER_PROJECT_FILENAME=.project
XDG_CONFIG_DIRS=/etc/xdg/xdg-ubuntu:/etc/xdg
PATH=/home/kiril/.virtualenvs/cs/bin:/home/kiril/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
LC_IDENTIFICATION=bg_BG.UTF-8
PS1=(cs) \[\e]0;\u@\h: \w\a\]${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ 
GJS_DEBUG_TOPICS=JS ERROR;JS LOG
SESSION_MANAGER=local/kiril-ThinkPad-W540:@/tmp/.ICE-unix/2394,unix/kiril-ThinkPad-W540:/tmp/.ICE-unix/2394
LESSOPEN=| /usr/bin/lesspipe %s
GTK_IM_MODULE=ibus
LC_TIME=bg_BG.UTF-8
_=/usr/bin/printenv
```

**Environment when git push is executed:**
```json
"husky": {
    "hooks": {
        "pre-push": "printenv"
    }
}
```
```bash
$ git push
```
```bash
VIRTUALENVWRAPPER_WORKON_CD=1
GJS_DEBUG_TOPICS=JS ERROR;JS LOG
LESSOPEN=| /usr/bin/lesspipe %s
WORKON_HOME=/home/kiril/.virtualenvs
USER=kiril
LC_TIME=bg_BG.UTF-8
TEXTDOMAIN=im-config
XDG_SEAT=seat0
SSH_AGENT_PID=2489
XDG_SESSION_TYPE=x11
SHLVL=2
OLDPWD=/usr/games
QT4_IM_MODULE=xim
HOME=/home/kiril
VIRTUALENV_PYTHON=/usr/bin/python3
DESKTOP_SESSION=ubuntu
HUSKY_GIT_PARAMS=origin git@bitbucket.org:swimcloud/cs.git
GNOME_SHELL_SESSION_MODE=ubuntu
GTK_MODULES=gail:atk-bridge
LC_MONETARY=bg_BG.UTF-8
GIT_PREFIX=
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
COLORTERM=truecolor
IM_CONFIG_PHASE=2
LOGNAME=kiril
GTK_IM_MODULE=ibus
_=/usr/bin/node
USERNAME=kiril
XDG_SESSION_ID=2
TERM=xterm-256color
GNOME_DESKTOP_SESSION_ID=this-is-deprecated
_VIRTUALENVWRAPPER_API= mkvirtualenv rmvirtualenv lsvirtualenv showvirtualenv workon add2virtualenv cdsitepackages cdvirtualenv lssitepackages toggleglobalsitepackages cpvirtualenv setvirtualenvproject mkproject cdproject mktmpenv
WINDOWPATH=2
HUSKY_GIT_STDIN=
PATH=/home/kiril/projects/cs/node_modules/.bin:/home/kiril/projects/node_modules/.bin:/home/kiril/node_modules/.bin:/home/node_modules/.bin:/node_modules/.bin:/usr/bin:/usr/lib/git-core:/home/kiril/.virtualenvs/cs/bin:/home/kiril/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
PAPERSIZE=a4
SESSION_MANAGER=local/kiril-ThinkPad-W540:@/tmp/.ICE-unix/2394,unix/kiril-ThinkPad-W540:/tmp/.ICE-unix/2394
XDG_MENU_PREFIX=gnome-
GNOME_TERMINAL_SCREEN=/org/gnome/Terminal/screen/c0e31243_3c25_4944_9c25_a8bacb12e520
LC_ADDRESS=bg_BG.UTF-8
XDG_RUNTIME_DIR=/run/user/1000
DJANGO_SETTINGS_MODULE=cs.settings.swimcloud.dev
DISPLAY=:0
PROJECT_HOME=/home/kiril/projects
LANG=en_US.UTF-8
XDG_CURRENT_DESKTOP=ubuntu:GNOME
LC_TELEPHONE=bg_BG.UTF-8
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
XDG_SESSION_DESKTOP=ubuntu
XMODIFIERS=@im=ibus
GNOME_TERMINAL_SERVICE=:1.75
XAUTHORITY=/run/user/1000/gdm/Xauthority
SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
LC_NAME=bg_BG.UTF-8
SHELL=/bin/bash
QT_ACCESSIBILITY=1
GDMSESSION=ubuntu
LESSCLOSE=/usr/bin/lesspipe %s %s
VIRTUALENVWRAPPER_PROJECT_FILENAME=.project
LC_MEASUREMENT=bg_BG.UTF-8
VIRTUALENVWRAPPER_HOOK_DIR=/home/kiril/.virtualenvs
TEXTDOMAINDIR=/usr/share/locale/
GJS_DEBUG_OUTPUT=stderr
GPG_AGENT_INFO=/run/user/1000/gnupg/S.gpg-agent:0:1
LC_IDENTIFICATION=bg_BG.UTF-8
XDG_VTNR=2
VIRTUAL_ENV=/home/kiril/.virtualenvs/cs
VIRTUALENVWRAPPER_SCRIPT=/usr/share/virtualenvwrapper/virtualenvwrapper.sh
QT_IM_MODULE=ibus
PWD=/home/kiril/projects/cs
CLUTTER_IM_MODULE=xim
XDG_DATA_DIRS=/usr/share/ubuntu:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop
XDG_CONFIG_DIRS=/etc/xdg/xdg-ubuntu:/etc/xdg
LC_NUMERIC=bg_BG.UTF-8
LC_PAPER=bg_BG.UTF-8
VTE_VERSION=5202
```

**Comment by kiruh** [comment]
I have found that PATH variable differs in environment printed from package.json.
Overriding it solves the problem. But this is not a final solution.
```json
// ...
"husky": {
    "hooks": {
        "pre-push": "PATH='/home/kiril/.virtualenvs/cs/bin'; python manage.py test --settings=cs.settings.test --failfast --parallel"
    }
},
// ...
```

**Comment by kiruh** [comment]
After a research I found that PATH variable in tests called from husky differs from PATH variable in  tests called from bash. The main difference is that some middleware appends `/usr/bin/` before `/home/kiril/.virtualenvs/cs/bin`. Since python is found at `/usr/bin/`, python from virtual environment is never executed.
```
[
  "/home/kiril/projects/cs/node_modules/.bin",
  "/home/kiril/projects/node_modules/.bin",
  "/home/kiril/node_modules/.bin",
  "/home/node_modules/.bin",
  "/node_modules/.bin",
> "/usr/bin",
  "/usr/lib/git-core",
> "/home/kiril/.virtualenvs/cs/bin",
  "/home/kiril/.local/bin",
  "/usr/local/sbin",
  "/usr/local/bin",
  "/usr/sbin",
> "/usr/bin",
  "/sbin",
  "/bin",
  "/usr/games",
  "/usr/local/games",
  "/snap/bin"
];
```
I found that installing [nvm](https://github.com/nvm-sh/nvm) fixes that problem. I suppose that node binary is located at `/usr/bin/` and nvm node binary is located at `/home/kiril/.nvm/versions/node/v13.5.0/bin` and that affects the PATH.
```
[
  "/home/kiril/projects/cs/node_modules/.bin",
  "/home/kiril/projects/node_modules/.bin",
  "/home/kiril/node_modules/.bin",
  "/home/node_modules/.bin",
  "/node_modules/.bin",
> "/home/kiril/.nvm/versions/node/v13.5.0/bin",
  "/usr/lib/git-core",
  "/home/kiril/.nvm/versions/node/v13.5.0/bin",
> "/home/kiril/.virtualenvs/cs/bin",
  "/home/kiril/.local/bin",
  "/usr/local/sbin",
  "/usr/local/bin",
  "/usr/sbin",
> "/usr/bin",
  "/sbin",
  "/bin",
  "/usr/games",
  "/usr/local/games",
  "/snap/bin"
];
```
