### ISSUE TITLE
Failing with weird message on Windows 10

### ISSUE THREAD

**Issue by belousnikita** [typicode/husky#549]
I have an weird error in any git gui, and VSCode git. 

I get this error when i am commiting from git bash, any git gui, or VSCode git output console on Windows 10:
> "lint-staged" �� ���� ����७��� ��� ���譥�
>��������, �ᯮ��塞�� �ணࠬ��� ��� ������ 䠩���.
>npm ERR! code ELIFECYCLE
>npm ERR! errno 1
>npm ERR! app@1.0.0 lint-staged: `lint-staged -x`
>npm ERR! Exit status 1
>npm ERR! 
>npm ERR! Failed at the app-setting-api@1.0.0 lint-staged script.
>npm ERR! This is probably not a problem with npm. There is likely additional logging output >above.

Configs: 
```json
"devDependencies": {
    "eslint": "^6.0.1",
    "husky": "^3.0.0",
    "lint-staged": "^9.0.2"
  },
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged -x"
    }
  },
  "lint-staged": {
    "*.js": [
      "eslint --quiet",
      "git add"
    ]
  },
```

- OS: Windows 10
- Node: v10.16.0
- GIT: v2.22.0.windows.1

It works fine in WSL with git version 2.17.1, using git-cli commands.

**Comment by belousnikita** [comment]
Ok, i find out that this problem is caused by WSL bash executable. After i've uninstalled windows subsystem for linux it works fine.

**Comment by addamove** [comment]
You can reinstall node_modules from windows shell(powershell from example)
