### ISSUE TITLE
Pre-commit fails with error when npm script calls "read with prompt"

### ISSUE THREAD

**Issue by cherryshoe** [typicode/husky#552]
Hello,

I want to incorporate a pause (read -p) with a manual step (to run Cypress) in the pre-commit hook, but it causes an error.

npm script in package.json:
`  
"scripts": {
    "clientlint": "cd client && npm run lint",
    "clientcypress": "read -p Run Cypress and then press any key to continue",
    "lint": "node_modules/.bin/eslint -c .eslintrc .; exit 0"
  }
`

.huskyrc file:
`
{
  "hooks": {
    "pre-commit": "npm run clientcypress && npm run lint && npm run clientlint"
  }
}
`

The error on git commit is:
$ vim /git commit -m "Add pause in pre-commit hook for Cypress"
husky > pre-commit (node v8.16.0)

> cherryshoe@0.2.0 clientcypress /opt/cherryshoe
> read -p Run Cypress and then press any key to continue

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cherryshoe@0.2.0 clientcypress: `read -p Run Cypress and then press any key to continue`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cherryshoe@0.2.0 clientcypress script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/cherryshoe/.npm/_logs/2019-07-19T20_18_29_663Z-debug.log
husky > pre-commit hook failed (add --no-verify to bypass)

Running the npm script by itself works:
$ npm run clientcypress

> cherryshoe@0.2.0 clientcypress /opt/cherryshoe
> read -p Run Cypress and then press any key to continue

Run
$

Reading the read man pages, it is because running through husky doesn't allow manual input from a terminal?
`              -p prompt
                     Display prompt on standard error, without a trailing newline, before  attempting  to  read  any  input.   The
                     prompt is displayed only if input is coming from a terminal.`

Environment:
CentOS Linux release 7.3.1611 (Core)
husky 2.7.0
npm 6.4.1
node v8.16.0
git version 1.8.3.1

**Comment by typicode** [comment]
> husky doesn't allow manual input from a terminal?

There were bugs at some point with reading terminal's input. Also it can make it complicated/impossible to commit from GUI as users can't enter text usually.
That said husky 5 works differently and it should be possible to read input during commit.
