### ISSUE TITLE
Unable to make husky work with yarn pnp on windows

### ISSUE THREAD

**Issue by HusamIbrahim** [typicode/husky#553]
I set the `HUSKY_USE_YARN` option but I'm still getting the following error on Windows 10 ..

> error Command "husky-run" not found.

**Comment by typicode** [comment]
Hi @HusamIbrahim,

Can you try with the latest version of husky? Also if you run `yarn husky-run` in your terminal does it fail too?

**Comment by HusamIbrahim** [comment]
@typicode Tried with v3.0.2. It fails with the same error message if I run `yarn husky-run`.

**Comment by typicode** [comment]
Thanks for the feedback!

I don't know why it's failing for the moment.

`HUSKY_USE_YARN` is an undocumented feature but better `yarn pnp` support is definitely in the v4.0 roadmap.

**Comment by HusamIbrahim** [comment]
> `HUSKY_USE_YARN` is an undocumented feature but better `yarn pnp` support is definitely in the v4.0 roadmap.

That's good to know. It'd be great though if basic support can be managed before the next major release 🙂

Btw what's the status on [this PR](https://github.com/typicode/husky/pull/491)?

**Comment by typicode** [comment]
> Btw what's the status on this PR?

Another approach is currently being taken (the one with `yarn husky-run`).

**Comment by arcanis** [comment]
Cf https://github.com/typicode/husky/issues/560#issuecomment-520827817 - tl;dr there's a bug in Yarn 1 which is fixed in Yarn 2 (which is the generally recommended version to use when using PnP).

**Comment by HusamIbrahim** [comment]
@arcanis Is there a way to make Yarn 2 use my global Yarn cache?

**Comment by arcanis** [comment]
For a global cache, you'll be looking for [`enableGlobalCache`](https://yarnpkg.github.io/berry/configuration/yarnrc#enableGlobalCache) (it's similar to setting a custom `cacheFolder`, except that you won't have to remember which path it should be when configuring other projects).

**Comment by typicode** [comment]
I've published a new version, which is a very early `v4.0.0` version. It should support Yarn PnP out of the box.

You can give it a try using `yarn add husky@next --dev`.

Feedback is welcome.

**Comment by HusamIbrahim** [comment]
@typicode Thanks for pushing forward PnP support. I'm encountering issues on Windows 10. I get this when I try to commit after setting up a pre-commit hook ..

> yarn install v1.17.3
> error `install` has been replaced with `add` to add new dependencies. Run "yarn add husky-run pre-commit " instead.
> info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by arcanis** [comment]
It'll be fixed with #562 🙂

**Comment by HusamIbrahim** [comment]
@arcanis Great! Waiting on this PR to get merged so I can give it a whirl.

**Comment by typicode** [comment]
#562 was merged and husky `v4.0.0-beta.1`  was published

**Comment by HusamIbrahim** [comment]
> #562 was merged and husky `v4.0.0-beta.1` was published

This version produces the same old error

`error Command "husky-run" not found.`

**Comment by arcanis** [comment]
Can you confirm you use Yarn 2? The issue I mentioned is still in the v1.

**Comment by HusamIbrahim** [comment]
> Can you confirm you use Yarn 2? The issue I mentioned is still in the v1.

My bad. Was mistakenly using Yarn 1 in another repo when I tried this. I can confirm it works flawlessly with Yarn 2 👌
