### ISSUE TITLE
README.md examples not working

### ISSUE THREAD

**Issue by krutoo** [typicode/husky#554]
Hi. Examples in README.md not working on unix systems. I mean:

```js
// package.json
{
  "husky": {
    "hooks": {
      "pre-commit": "npm test", // there are no "run" option after npm
      "pre-push": "npm test", // and there
      "...": "..."
    }
  }
}
```

Please, correct me if I am wrong. Thanks.

**Comment by typicode** [comment]
Hi @krutoo,

`npm test` is an exception and a shortcut for `npm run test`.
You can get more info with `npm help test`:
> This runs a package's "test" script, if one was provided.

So in theory, this example should work, if it doesn't it may be related to another issue. Feel free to paste your output or describe the issue you're having.

**Comment by krutoo** [comment]
Yes, sorry for useless issue, its work with npm test
