### ISSUE TITLE
[windows] husky is not working with commitlint 

### ISSUE THREAD

**Issue by indraraj26** [typicode/husky#557]
I used below commands to install husky and commitlint
npm install --save-dev @commitlint/config-conventional @commitlint/cli
echo "module.exports = {extends: ['@commitlint/config-conventional']}" > commitlint.config.js
npm install husky --save-dev

**Expected Behavior**
I shouldnt be able to commit without adding feat: chore: etc

**Current Behavior**
I am able to commit without feat: chore: i have configured husky for commit-msg

**Steps to Reproduce (for bugs)**
https://github.com/indraraj26/github-test

**Version**
```
"husky": "^3.0.2",
```

Link to commitlint opened issue : https://github.com/conventional-changelog/commitlint/issues/770

**Output**:
```
PS C:\indraraj\github-test> echo "foo" | ./node_modules/.bin/commitlint
⧗   input: foo
✖   subject may not be empty [subject-empty]
✖   type may not be empty [type-empty]

✖   found 2 problems, 0 warnings
ⓘ   Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint
```

**Comment by typicode** [comment]
Hi @indraraj26,

Thanks for the repo!

I can't seem to be able to reproduce on Windows. I tried with your repo and the commit failed as expected.

![screenshot-husky](https://user-images.githubusercontent.com/5502029/62705836-89658e80-b9ee-11e9-94a6-b4991d32927e.jpg)

Can you retry to commit with `HUSKY_DEBUG=1` and paste the output?

```
$env:HUSKY_DEBUG=1; git commit -m foo
```

**Comment by indraraj26** [comment]
Hi, 

I am getting this error

![image](https://user-images.githubusercontent.com/23274631/62767385-2b01e400-bab2-11e9-8079-fd12a4a0a703.png)

**Comment by typicode** [comment]
Hi,

My bad, the syntax was for PowerShell (which comes with Windows). For `cmd`, I'm not sure but I think it's something like:

```
set HUSKY_DEBUG=1
git commit -m foo
```

**Comment by keverw** [comment]
I'm using Mac and recently started using both of these tools.

I noticed it didn't seem to fail either as I expected so searched on Google and found this issue.

I downloaded their repo to see if it does the same with someone else's setup and indeed it didn't error

```
Kevins-MacBook-Pro-2012:github-test-master kevinwhitman$ git init
Initialized empty Git repository in /Users/kevinwhitman/Downloads/github-test-master/.git/
Kevins-MacBook-Pro-2012:github-test-master kevinwhitman$ git add .
Kevins-MacBook-Pro-2012:github-test-master kevinwhitman$ git commit -m "foo"
[master (root-commit) db2826b] foo
 7 files changed, 3437 insertions(+)
 create mode 100755 .gitignore
 create mode 100755 commitlint.config.js
 create mode 100755 index.html
 create mode 100755 index.js
 create mode 100755 package-lock.json
 create mode 100755 package.json
 create mode 100644 yarn.lock
```


I'm using git version 2.20.1 (Apple Git-117). 

So looks like same issue on Windows is causing this on Mac.

**Comment by typicode** [comment]
@keverw could you try with `HUSKY_DEBUG=1 git commit ...` please and post the output?

**Comment by keverw** [comment]
Just did this but it didn't seem to give any different output.

```
Kevins-MacBook-Pro-2012:kevinwhitman kevinwhitman$ cd /Users/kevinwhitman/Downloads/github-test-master
Kevins-MacBook-Pro-2012:github-test-master kevinwhitman$ git add .
Kevins-MacBook-Pro-2012:github-test-master kevinwhitman$ HUSKY_DEBUG=1 git commit -m "foobar"
[master 284b6ea] foobar
 1 file changed, 1 insertion(+), 1 deletion(-)
Kevins-MacBook-Pro-2012:github-test-master kevinwhitman$
```

**Comment by przemyslawzalewski** [comment]
Please see if you have a  `CI=true` environmental variable defined somewhere in the system settings or during packages install.

![SystemPropertiesAdvanced_2019-08-14_17-08-36](https://user-images.githubusercontent.com/30114244/63032588-63d8f900-beb6-11e9-89cc-9937c9e10292.png)

I had it enabled and it caused the git hooks to be skipped during husky install:

```sh
> node husky install

husky > Setting up git hooks
CI detected, skipping Git hooks installation.
```

`HUSKY_DEBUG=1 git commit` didn't show anything for me as well. Please inspect your `npm install` logs.

**Comment by keverw** [comment]
@przemyslawzalewski No CI for me. but I reran `yarn add husky --dev` and it worked. Maybe part of the issue would of been I installed husky before I init the Git repo.

So it works for me now.

**Comment by indraraj26** [comment]
Hi @typicode ,

Still it is same. 

![image](https://user-images.githubusercontent.com/23274631/63404306-595fb780-c400-11e9-882c-2226f3ff8e8e.png)

**Comment by typicode** [comment]
When setting `HUSKY_DEBUG=1`, you should at least some messages from husky like:

```sh
$ HUSKY_DEBUG=1 git commit -m test
husky:debug pre-commit hook started
...
```

It seems like hooks weren't installed. Can you check `.git/hooks/pre-commit`? Does it start with:

```sh
#!/bin/sh
# husky

# Hook created by Husky
#   Version: 3.0.4
# ...
```

**Comment by indraraj26** [comment]
Hi, 

This is what i see 

![image](https://user-images.githubusercontent.com/23274631/63688771-e1412980-c825-11e9-8aa1-d71d15cce72b.png)

![image](https://user-images.githubusercontent.com/23274631/63688848-177ea900-c826-11e9-9870-25e74441dba4.png)

**Comment by indraraj26** [comment]
I just re-setup the commitlint and husky in different project it is working now. No idea what was causing the above issue.
Thank you for response.
#closing

**Comment by typicode** [comment]
Glad it works now, thanks for the update :)

**Comment by cyrixmorten** [comment]
Unsure if I should open a new issue but have exactly same problem on Windows.

Tried to re-setup commitlint and husky, upgrade node from 10 to 12.

![image](https://user-images.githubusercontent.com/6650168/67012119-1add3500-f0f1-11e9-9bc2-9567f39868fd.png)

Might be commitlint that does not fire a non-zero exit code?

![image](https://user-images.githubusercontent.com/6650168/67012275-65f74800-f0f1-11e9-844d-de98a600f168.png)

![image](https://user-images.githubusercontent.com/6650168/67012235-5546d200-f0f1-11e9-95ba-64fb8a8333b6.png)

**Comment by a631807682** [comment]
@typicode I have same problem on Windows like @cyrixmorten , check commit message fail but not fire non-zero exit.

**Comment by JsonMa** [comment]
> Glad it works now, thanks for the update :)

Me too, this problem appear under windows. Husky does not work for me, and no git hook files under .git folder. My node version is v12.13.1.

**Comment by Kaliph** [comment]
I have the same  issue. I am working with Windows 10. My node version is 12.14.1 and git version 2.25.0.windows.1

This is the output when trying to commit with git commandline

`λ git commit -m deletebutton
husky > commit-msg (node v12.14.1)
⧗   input: deletebutton
✖   subject may not be empty [subject-empty]
✖   type may not be empty [type-empty]

✖   found 2 problems, 0 warnings
ⓘ   Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint

husky > commit-msg hook failed (add --no-verify to bypass)`

**Comment by rlam3** [comment]
Can we reopen this issue? This is still happening.

**Comment by isaacrajaei** [comment]
If anyone still have problem with this I would advise to read this article.
[https://dev.to/talohana/husky-and-commitlint-for-clean-git-log-44be](https://dev.to/talohana/husky-and-commitlint-for-clean-git-log-44be)

To suppress the error you may add `--no-verify` at the end of your commit line.
`git commit -m "your-msg" --no-verify`

**Comment by kaminskypavel** [comment]
`echo "feat(scope): test" | yarn commitlint`


`⧗   input: "FEAT(scope): test" 
✖   subject may not be empty [subject-empty]
✖   type may not be empty [type-empty]
`

**Comment by Hacaw** [comment]
I have the same issue like @kaminskypavel.

**Comment by nibilly7** [comment]
The subject of a commit must respect a template <type>: <subject>. Type can be:
  'build',
  'chore',
  'ci',
  'docs',
  'feat',
  'fix',
  'perf',
  'refactor',
  'revert',
  'style',
  'test'
The subject must be write in lower case.

See the documentation of the conventional config of commitlint. 
https://github.com/conventional-changelog/commitlint/tree/master/%40commitlint/config-conventional

**Comment by JoniRinta-Kahila** [comment]
I had a similar problem. The problem started when the husky installation failed due to reason X.
This is how i fixed the problem: 
from `config` file in `.git folder`, I removed `hooksPath = .husky`  row.

So the problem was that the husky could not find the hooks because the hooks were written to the package.json file and husky searches hooks in the .husky folder.
