### ISSUE TITLE
Optionally overwrite existing hooks

### ISSUE THREAD

**Issue by tomasbjerre** [typicode/husky#558]
# Problem

I'm working within an organization where we get Git Bash pre packaged with hooks. We cannot change that and every developer will get these hooks, from the installation of Git Bash, installed when cloning repositories. The pre packaged hooks will make Husky ignore any hooks configured in `package.json`.

Developers must do something like:
```shell
git clone whatever.git
rm ./git/hooks/*
npm install
```

# Proposed solution

Make it possible to optionally always overwrite any existing hook.

**Comment by tomasbjerre** [comment]
A workaround might be to put this in `package.json`:
```json
scripts: {
 "preinstall": "rm -f .git/hooks/pre-commit"
}
```

**Comment by ckarlbe** [comment]
Wouldn't it be great if husky runs the pre-existing hook before it runs the now existing husky hook? In that way husky preserve the old hook and tries to execute both?

**Comment by brother** [comment]
See also 336.

**Comment by statm** [comment]
> A workaround might be to put this in `package.json`:
> 
> ```json
> scripts: {
>  "preinstall": "grep -q husky .git/hooks/pre-commit || rm -f .git/hooks/pre-commit"
> }
> ```

This wouldn't work on Windows due to the lack of `grep` and `rm`. Worse, you can't even use rimraf because it's preinstall. We ended up creating a custom script to `fs.readdir` and `fs.unlink` all git hooks.

**Comment by typicode** [comment]
Closing as it shouldn't be an issue with husky 5. Thanks for the issue, PR and workaround :+1:
