### ISSUE TITLE
husky package post install hook fails on windows

### ISSUE THREAD

**Issue by capaj** [typicode/husky#565]
```
> husky@3.0.3 postinstall C:\Users\jspac001\repos\ProductivityHubUI\node_modules\husky
> opencollective-postinstall || true

'opencollective-postinstall' is not recognized as an internal or external command,
operable program or batch file.
'true' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! husky@3.0.3 postinstall: `opencollective-postinstall || true`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the husky@3.0.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```
is what happens on a windows machine.

**Comment by typicode** [comment]
Thanks for the report. I'm not sure why it can't find `open-collective`. It's defined as a dependency and I've just tried on Windows.

Could you try with a freshly created repo?

```sh
git init
npm init -y
npm install husky --save-dev
```

**Comment by capaj** [comment]
I confirm that clean installs run fine.

**Comment by typicode** [comment]
@emily-curry thanks a lot for checking the other projects, do you want to make a PR with `|| exit 0`?

**Comment by naingaungphyo** [comment]
Now latest(master) core-js code changed from 
> || operator

 to 
> "postinstall": "node -e \"try{require('./postinstall')}catch(e){}\"".

Husky postinstall script should be changed into the same way, because it is causing error in powershell. 
The error is the same as this [core-js issue](https://github.com/zloirock/core-js/issues/582)
