### ISSUE TITLE
Check failed: U_SUCCESS(status). and show FailureMessage Object: 0000001E3C6FD400

### ISSUE THREAD

**Issue by wind4gis** [typicode/husky#567]
my computer is win10, when I install husky, it shows errors like this:
![image](https://user-images.githubusercontent.com/3963291/63659880-6ad10700-c7e6-11e9-9be3-ec7ce74ffbb2.png)

**Comment by typicode** [comment]
Hi @wind4gis,

This error doesn't ring a bell to me and I don't know what may cause it. I'm testing on Windows 10 as well.

Maybe you can try in a clean repo https://github.com/typicode/husky#testing-husky-in-a-new-repo or reinstall Node or try with npm instead of yarn.
