### ISSUE TITLE
Not a Husky!

### ISSUE THREAD

**Issue by muscaiu** [typicode/husky#578]
**Is this a known issue ???**

![2019-09-05_16-18-42](https://user-images.githubusercontent.com/11426309/64345592-4f8da500-cff9-11e9-9ff1-7389531669c3.png)

**Comment by jaller94** [comment]
Unicode specifies this character as "DOG FACE", meaning it may or may not be a husky. The visual appearance depends on the viewer's system (OS, installed fonts, etc.).

https://unicode-table.com/en/1F436/

To have certainty about the visual appearance, one will have to upload an image and display it in the ReadMe.

**Comment by typicode** [comment]
🤔 now that you say it...

**Comment by kokushkin** [comment]
ok, then if unicode says it's a dog face, how could you be sure that someone will see a husky on their system? You should call your package "dog" then😅
