### ISSUE TITLE
v3 won't install or work from a git worktree directory

### ISSUE THREAD

**Issue by zfeher** [typicode/husky#580]
Hi' Thank you for working on this project. 

Today we wanted to upgrade from 0.14.x to the latest 3.0.5 version. But it didn't work. The hooks didn't run. Checking the hooks directory seemed just fine. Removing husky, and the hooks manually an reinstalling husky did not install the hooks.

However downgrading to 2.6.0 version worked flawlessly. 

Then I became suspicious about git worktrees and it seems that is the problem. If we want to install the latest husky from a git worktree it won't install/remove/run the hooks. 

As it seems versions ranging from 0.14-2.6.0 are able to handle this.

**Comment by typicode** [comment]
Hi @zfeher,

Thanks for the report.

Husky v3 uses `git rev-parse ...` to figure out where hooks should be installed. Before, it was some JS code that was doing this.

You can get some debug info during install using `HUSKY_DEBUG=1 npm install husky --save-dev`. Can you post the output?

Would you also have some commands I can run to reproduce the issue locally?

**Comment by zfeher** [comment]
The requested debug output:
```
$ HUSKY_DEBUG=1 npm install -D husky

> husky@3.0.5 preuninstall C:\Users\zfeher\dev\projects\acme\acme-green\node_modules\husky
> node husky uninstall

husky:debug cwd: C:\Users\zfeher\dev\projects\acme\acme-green\node_modules\husky
husky:debug INIT_CWD: C:\Users\zfeher\dev\projects\acme\acme-green
husky > Uninstalling git hooks
husky:debug topLevel: C:/Users/zfeher/dev/projects/acme/acme-green
husky:debug gitDir: C:/Users/zfeher/dev/projects/acme/acme-main/.git/worktrees/acme-green
husky > Done
```

`acme-green` is a git worktree here whereas the `acme-main` is the main repo dir where the actual `.git` folder lives.

I noticed something new: If I installed husky in the main folder it worked. Then I uninstalled it, opened the worktree folder, installed husky there which didn't created hooks under `acme-main/.git/hooks` (like 2.6.0 did) instead it created hooks in the worktree under `main/.git/worktrees/acme-green/hooks`. 
This sounds reasonable. But the hooks didn't work this way for some reason, maybe it is a git problem. But after installing husky in the main repo folder as well (installed hooks in `acme-main/.git/hooks`), the hooks started to work when I commited in the worktree.

You can repro this by making git worktrees in a cloned git repository. To do this:
```
1, clone or open a repository
2, cd to the repo folder
3, remove husky: npm r husky
4, create a worktree: git worktree add --detach ../repo-worktree
4, cd ../repo-worktree
5, npm i -D husky
```

Hope this helps.

**Comment by typicode** [comment]
Hi @zfeher,

It helped a lot, thanks! I've just published a new version which should fix the issue (`v3.0.8`).

**Comment by forivall** [comment]
I'm having similar issues, and whenever i switch from one worktree directory to the other, i have to run `npm rebuild husky` in order for hooks to work.

The `.git` directory is at `~owl2-env/packages/chat/.git` (`~owl2-env` and `~owl` are [zsh named](http://zsh.sourceforge.net/Doc/Release/Expansion.html#Static-named-directories) [directories](https://github.com/forivall/dotfiles/blob/93725ac/plugins/jump/jump.plugin.zsh#L18))
```
~owl2-env/packages/chat master
» HUSKY_DEBUG=1 git commit
husky:debug husky v3.0.8 (created at 10/4/2019, 8:03:20 PM)
husky:debug pre-commit hook started
husky:debug Current working directory is '/Users/emily/code/owl/owl2-env/packages/chat'
husky:debug Changed current working directory to '/Users/emily/code/owl/owl2-env/packages/chat'
husky > pre-commit (node v10.16.2)
🔍  Finding changed files since git revision 5b4ae5d.
🎯  Found 0 changed files.
✅  Everything is awesome!
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean

~owl2-env/packages/chat master
» cd -
~owl/repos/chat

~owl/repos/chat chore/yarn-dedupe
» HUSKY_DEBUG=1 git commit
husky:debug husky v3.0.8 (created at 10/4/2019, 8:03:20 PM)
husky:debug pre-commit hook started
/Users/emily/code/owl/owl2-env/packages/chat/.git/hooks/pre-commit: line 48: ../../node_modules/run-node/run-node: No such file or directory

~owl/repos/chat chore/yarn-dedupe
» HUSKY_DEBUG=1 npm rebuild husky

> husky@3.0.8 install /Users/emily/code/owl/repos/chat/node_modules/husky
> node husky install

husky:debug Current working directory is '/Users/emily/code/owl/repos/chat/node_modules/husky'
husky:debug INIT_CWD environment variable is set to '/Users/emily/code/owl/repos/chat'
husky > Setting up git hooks
husky:debug Git rev-parse command returned:
husky:debug   --show-top-level: /Users/emily/code/owl/repos/chat
husky:debug   --git-common-dir: /Users/emily/code/owl/owl2-env/packages/chat/.git
husky:debug Installing hooks in '/Users/emily/code/owl/owl2-env/packages/chat/.git/hooks'
husky > Done

> husky@3.0.8 postinstall /Users/emily/code/owl/repos/chat/node_modules/husky
> opencollective-postinstall || exit 0

Thank you for using husky!
If you rely on this package, please consider supporting our open collective:
> https://opencollective.com/husky/donate

husky@3.0.8 /Users/emily/code/owl/repos/chat/node_modules/husky

~owl/repos/chat chore/yarn-dedupe
» HUSKY_DEBUG=1 git commit
husky:debug husky v3.0.8 (created at 10/4/2019, 8:05:55 PM)
husky:debug pre-commit hook started
husky:debug Current working directory is '/Users/emily/code/owl/repos/chat'
husky:debug GIT_DIR environment variable is set to '/Users/emily/code/owl/owl2-env/packages/chat/.git/worktrees/chat'
husky:debug If you're getting "fatal: not a git repository" errors, you may want to unset GIT_DIR
husky:debug Changed current working directory to '/Users/emily/code/owl/repos/chat'
husky > pre-commit (node v10.16.2)
🔍  Finding changed files since git revision 5b4ae5d.
🎯  Found 0 changed files.
✅  Everything is awesome!
On branch chore/yarn-dedupe
nothing to commit, working tree clean

~owl/repos/chat chore/yarn-dedupe
» cd -
~owl2-env/packages/chat

~owl2-env/packages/chat master
» HUSKY_DEBUG=1 git commit
husky:debug husky v3.0.8 (created at 10/4/2019, 8:05:55 PM)
husky:debug pre-commit hook started
.git/hooks/pre-commit: line 48: node_modules/run-node/run-node: No such file or directory
```

**Comment by typicode** [comment]
@forivall when you change directory it seems like the path to husky is different.
 
As the layout/bug is a bit complex, could you provide steps to recreate the issue locally?

I don't know if it applies, but you may want to check https://github.com/typicode/husky#monorepos, husky needs to be defined once in a project with multiple `package.json`.

**Comment by zfeher** [comment]
@typicode thank you for the fix, tried it and works for us flawlessly

**Comment by forivall** [comment]
@typicode yeah, it seems like it has to do with our multi-repo setup, where there is a root repo to setup various utilities to work on multiple repositories in sync, & a yarn workspace to share deps, similar to https://github.com/ckeditor/ckeditor5. (although, we're currently using pre-commit for most repositories, and I decided to start the switch to husky for a new project). In the case where the error happens, the repo is in the workspace, and the worktree is outside of it.

I have a (non reproducing) repro set up at https://github.com/typicode/husky/compare/master...forivall:forivall/workdir-and-multi-repo#diff-d3e594e28e18ed2d5b3dc8a3e04b1d1bR29 , and I'll add a parent repository to show the error in action.

**Comment by forivall** [comment]
Ah, I figured out the workaround / fix. After adding this to the `workspaces` section of the _root_ repo's package.json (for the yarn workspace), and re-running `yarn` it works perfectly!
```diff
diff --git a/package.json b/package.json
index 7ae7807..e389194 100644
--- a/package.json
+++ b/package.json
@@ -20,7 +20,8 @@
       "."
     ],
     "nohoist": [
-      "**/husky"
+      "**/husky",
+      "**/run-node"
     ]
   },
   "scripts": {
```
