### ISSUE TITLE
Question: are there any caveats to using husky/git hooks?

### ISSUE THREAD

**Issue by Grandclosing** [typicode/husky#583]
Hi all,

I was warned against using husky, and by extention, git hooks in general, on my project. Are there any caveats when using such? Are there any known security issues? 

Thanks!

**Comment by typicode** [comment]
Hi @Grandclosing,

Not that I know. Husky simply creates shell scripts (hooks) that run associated commands defined in `package.json` or `.huskyrc`.

What were the concerns about? I could give you a more detailed answered :)
