### ISSUE TITLE
Help test Husky v4 (pre-release)

### ISSUE THREAD

**Issue by typicode** [typicode/husky#586]
__To give it a try, simply install `husky@next`:__

```sh
npm install husky@next --save-dev
yarn add husky@next --dev
```

Please report any issues related to this version (or add a :+1: if everything is working fine).

__To go back to Husky v3:__

```sh
npm install husky@latest --save-dev
yarn add husky@latest --dev
```

Thank you! :pray:

**Comment by bm-stschneider** [comment]
Finally, its working with a global install

**Comment by StephanBijzitter** [comment]
I saw that v4 still contains support for the deprecated hooks in package.json scripts. Will that be removed?

I've got a [pull request](https://github.com/typicode/husky/pull/623) for v3 to disable the backward compatibility using an option and I'd be more than willing to adapt it for v4 or create an additional pull request for the `next` branch.

**Comment by typicode** [comment]
Thank you for the help and feedback! Husky 4 has just been released.

@bm-stschneider not really intended or recommended as it can create side effects. For example, having version Y installed globally and in project B, but still having some code from version X in project A that will call version Y.

@StephanBijzitter yes, I hope so :) I just didn't have the time to review the PR yet.

**Comment by bm-stschneider** [comment]
The thing is, if you have people in a multilanguage project who do not have node installed, husky will break tries to commit. By having a working global install this can be circumvented.

**Comment by typicode** [comment]
I see thanks for sharing. If they don't have Node, they shouldn't be able to install Husky/Git hooks or am I missing something?

**Comment by bm-stschneider** [comment]
That is correct, BUT, with a volume mount into the docker container they have the git hooks as well unfortunately.
