### ISSUE TITLE
ENOENT: no such file or directory, mkdir 'node_modules/husky/.git/hooks'

### ISSUE THREAD

**Issue by AniaMakes** [typicode/husky#587]
I'm trying to get lint-staged to work and I believe Husky is the failure point. I would appreciate any suggestions on how to proceed, especially given that the same issue occurs in the husky-only testing repo. If you have any further questions, I'll do my best to answer them. Many thanks in advance :)

Ubuntu 16.04 LTS
git version 2.7.4
node version 10.16.3
npm version 6.9.0

When installing lint-staged, I kept getting the following error.
``` husky > Setting up git hooks
ENOENT: no such file or directory, mkdir 'node_modules/husky/.git/hooks'
husky > Failed to install
```

Followed the instructions at https://github.com/typicode/husky#hooks-arent-running - there doesn't appear to be any husky code there, just a bunch of *.sample which I believe are git's own hook samples.

Followed the instructions at https://github.com/typicode/husky#testing-husky-in-a-new-repo - same issue. Removed husky and run the install with DEBUG:
```
ania@computer:~/code/foo$ HUSKY_DEBUG=1 npm install husky 

> husky@3.0.8 install /home/ania/code/foo/node_modules/husky
> node husky install

husky:debug Current working directory is '/home/ania/code/foo/node_modules/husky'
husky:debug INIT_CWD environment variable is set to '/home/ania/code/foo'
husky > Setting up git hooks
husky:debug Git rev-parse command returned:
husky:debug   --show-top-level: /home/ania/code/foo
husky:debug   --git-common-dir: node_modules/husky/.git
ENOENT: no such file or directory, mkdir 'node_modules/husky/.git/hooks'
husky > Failed to install

> husky@3.0.8 postinstall /home/ania/code/foo/node_modules/husky
> opencollective-postinstall || exit 0

Thank you for using husky!
If you rely on this package, please consider supporting our open collective:
> https://opencollective.com/husky/donate

npm WARN foo@1.0.0 No description
npm WARN foo@1.0.0 No repository field.

+ husky@3.0.8
added 75 packages from 48 contributors and audited 93 packages in 3s
found 0 vulnerabilities
```

**Comment by AniaMakes** [comment]
Quick update to this - when I tried installing husky-test-directory and forced version 2.4.1 it installed just fine!

```
ania@computer:~/code/foo2$ npm install husky@2.4.1 --save-dev

> husky@2.4.1 install /home/ania/code/foo2/node_modules/husky
> node husky install

husky > Setting up git hooks
husky > Done
husky > Like husky? You can support the project on Patreon:
husky > https://www.patreon.com/typicode 🐕
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN foo2@1.0.0 No description
npm WARN foo2@1.0.0 No repository field.

+ husky@2.4.1
added 78 packages from 47 contributors and audited 91 packages in 2.837s
found 0 vulnerabilities
```

**Comment by CHBresser** [comment]
I also came across this issue, forced to 2.4.1 and it installed fine.

**Comment by typicode** [comment]
Hi @AniaMakes, @CHBresser,

Thanks for the report and detailed logs. What's your version of Git?
@AniaMakes not sure why `git rev-parse --git-common-dir` returns `node_modules/husky/.git`.

**Comment by CHBresser** [comment]
`git --version`: `git 2.11.0`

default gcp git version.

**Comment by typicode** [comment]
For some reasons, it seems like `git rev-parse --common-git-dir` behaves differently before Git v2.13.

```sh
project $ git init
project $ mkdir foo && cd foo
project/foo $ git rev-parse --common-git-dir 
# will return foo/.git before 2.13 and ../.git after
```

If possible, I would suggest upgrading Git to v2.13+

**Comment by stianlik** [comment]
Looks like this is a regression caused by #585. I get the the same error when installing husky in to a subdirectory of a git repository using git version 2.9.3 on Redhat 7.6.

```sh
HUSKY_DEBUG=1 npm install husky@3.0.9 --save-dev
ENOENT: no such file or directory, mkdir 'auw-web-client-react/node_modules/husky/.git/hooks'
```

I was able to make it work by pointing `GIT_DIR` to the root directory of my repository using the following command:

```sh
GIT_DIR="$PWD/../.git" HUSKY_DEBUG=1 npm install husky@3.0.9 --save-dev
```

As I'm running git v2.13+, I think we can conclude that an upgrade won't solve the problem. Using `git rev-parse --git-dir` instead of `--common-git-dir` will report the correct directory and should work with and without worktrees.

Called from subdirectory of repository:

```
git rev-parse --git-dir
/...path/my-repo/.git
```

Called from worktree

```
git rev-parse --git-dir
/...path/my-repo/.git/worktrees/my-worktree
```

To support worktrees, all you need to do is to strip away the part after `.git`.

**Comment by MartinMuzatko** [comment]
Since you only allow having husky installed only once per git project, it wouldn't make that much sense to differ here and just use the package.json as root. Makes sense?

**Comment by 100001** [comment]
upgrade your git version to 2.24.0

**Comment by VladKovalevsky** [comment]
> For some reasons, it seems like `git rev-parse --common-git-dir` behaves differently before Git v2.13.
> 
> ```shell
> project $ git init
> project $ mkdir foo && cd foo
> project/foo $ git rev-parse --common-git-dir 
> # will return foo/.git before 2.13 and ../.git after
> ```
> 
> If possible, I would suggest upgrading Git to v2.13+

Works for me. Awesome, Thanks!
