### ISSUE TITLE
How can I use the commitmsg?

### ISSUE THREAD

**Issue by ximendatie** [typicode/husky#589]
I want to use my own regex to limit the commit msg .
For example, I want all the commits have a special word which I prepared, so I want to check the commit by my regex.

Now, I don't know how to get the commit msg.

// package.json
```js
  "husky": {
    "hooks": {
      "commit-msg": " sh myshell.sh && commitlint -E HUSKY_GIT_PARAMS"
    }
  },
 ```
The myshell.sh didn't get the commit msg, who can help me?

**Comment by typicode** [comment]
Hi @ximendatie,

Have you tried something like this?

```sh
/tmp/test master*
→ cat .huskyrc
{
  "hooks": {
    "commit-msg": "sh script.sh"
  }
}

/tmp/test master*
→ cat script.sh
echo $HUSKY_GIT_PARAMS

/tmp/test master*
→ git commit -m test
husky > commit-msg (node v12.10.0)
.git/COMMIT_EDITMSG
[master 607ad23] test
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 bar
```

**Comment by ximendatie** [comment]
Thank you typicode, I think you are right.
I finally use a node script and get the commit msg file by `process.env.HUSKY_GIT_PARAMS`

```js
#!/usr/bin/env node
const path = process.env.PWD+'/'+process.env.HUSKY_GIT_PARAMS //Here I get the commit msg filepath, then I can get the msg
```
