### ISSUE TITLE
Option to not install git hooks on npm install

### ISSUE THREAD

**Issue by w33ble** [typicode/husky#59]
When a user runs `npm install husky`, all of the git hooks get installed automatically. This is usually great, but it would be handy to optionally be able to skip that install step and run it manually later. 

[ghooks](https://github.com/gtramontina/ghooks/blob/master/bin/module-install#L4-L6) offers this via `opt-cli` (it's broken in my testing though), which would allow a user to prevent the hook installations if they'd like to via a settings file or some configuration in the `package.json` file. It would be great if husky had the same, so that automatic installation could be optionally disabled.

This is something I'd like to create a PR for, but I wanted to have a discussion about it here before building the feature.

**Comment by iamstarkov** [comment]
there will be no point in husky with this feature enabled

**Comment by w33ble** [comment]
I disagree. The repo I want to use this on spans multiple projects and languages, each with their own set of hooks and requirements. The issue we have now is that building the node parts requires an npm install, which automatically installs our hooks and gets in everyone else's way. There are some other options, and we could roll something by hand, but husky is everything we want, sans the option to opt-in.

**Comment by w33ble** [comment]
I just realized that adding an opt-in option to husky isn't actually a requirement. We can just set up all the husky rules, and the someone would opt in would be to `npm install husky`. We don't need it in the package.json file at all.

Sorry for the noise.
