### ISSUE TITLE
Stdin is commented out?

### ISSUE THREAD

**Issue by ReekenX** [typicode/husky#597]
Good day! Been using `Husky` for half a year now, great work!

I ran into the issue where on `pre-commit` hook I need to ask some input from developer. Running script manually - works, but when it's called from `husky` - it does not listen for the input.

Github Issues list shows lots of closed and opened questions around `stdin`. Unfortunately, I could not understand how it should be fixed. After debugging, found that

https://github.com/typicode/husky/blob/master/src/installer/getScript.ts#L79

is commented out. Uncommenting these few lines in `.git/hooks/post-receive` makes it all working.

Is there is something about commented lines?

**Comment by typicode** [comment]
Hi @ReekenX,

Yes, it caused issues for some Git clients. I can't remember exactly which but it should be mentioned in issues.

AFAIK some graphical Git clients can't get user input in hooks (GitHub Desktop, VS Code, ...). 

Alternatively, you could have a script getting the user input and a hook validating it:

```js
// package.json
{
  "scripts": {
    "commit": "<get user input>"
  },
  "husky": {
    "hooks": {
      "pre-commit": "<validate user input>"
    }
  }
}
```

This is what commitlint is doing with their prompt:
https://commitlint.js.org/#/guides-use-prompt

**Comment by ReekenX** [comment]
@typicode Clear and thanks for quick reply.

Would it be possible to tweak those [mentioned lines](https://github.com/typicode/husky/blob/master/src/installer/getScript.ts#L79) so if it finds env variable, they end up uncommented?

Like:

```
export HUSKY_GIT_STDIN=1
npm install # installs husky and git hooks
```

Looks like easy fix, no?

**Comment by jagu-sayan** [comment]
This work with GitKraken, SourceTree, Atom, VisualStudio Code :
````bash
# Used to fix GitKraken bug that launch git hook in terminal
PARENT_COMMAND="$(basename "$(ps -o comm= $PPID)")"

# Check if stdout is a terminal and parent command is `git`
if [ -t 1 ] && [ "$PARENT_COMMAND" == "git" ]; then
  # Exec node binary with /dev/tty (current terminal) as stdin
  exec < /dev/tty
else
```

And maybe we can add the `HUSKY_GIT_STDIN=1` option
