### ISSUE TITLE
Hooks are occasionally corrupt

### ISSUE THREAD

**Issue by Livven** [typicode/husky#599]
So this is a very weird issue, but sometimes the hooks written by Husky (3.0.9 on Windows) after running `npm install` or `yarn install` are corrupt. There will be this additional section at the end of the file which causes errors with the shell script:

```
his hook"
  fi
fi
```
<details>
<summary>Full file contents</summary>

```
#!/bin/sh
# husky

# Hook created by Husky
#   Version: 3.0.9
#   At: 10/24/2019, 2:30:18 PM
#   See: https://github.com/typicode/husky#readme

# From
#   Directory: undefined
#   Homepage: https://github.com/typicode/husky#readme

scriptPath="node_modules/husky/run.js"
hookName=`basename "$0"`
gitParams="$*"

debug() {
  if [ "${HUSKY_DEBUG}" = "true" ] || [ "${HUSKY_DEBUG}" = "1" ]; then
    echo "husky:debug $1"
  fi
}

debug "husky v3.0.9 (created at 10/24/2019, 2:30:18 PM)"
debug "$hookName hook started"
debug "Current working directory is '`pwd`'"

if [ "${HUSKY_SKIP_HOOKS}" = "true" ] || [ "${HUSKY_SKIP_HOOKS}" = "1" ]; then
  debug "HUSKY_SKIP_HOOKS is set to ${HUSKY_SKIP_HOOKS}, skipping hook"
  exit 0
fi

if [ "${HUSKY_USE_YARN}" = "true" ] || [ "${HUSKY_USE_YARN}" = "1" ]; then
  debug "Calling husky through Yarn"
  yarn husky-run $hookName "$gitParams"
else

  if [ -f "$scriptPath" ]; then
    # if [ -t 1 ]; then
    #   exec < /dev/tty
    # fi
    if [ -f ~/.huskyrc ]; then
      debug "Sourcing '~/.huskyrc'"
      . ~/.huskyrc
    fi
    node "$scriptPath" $hookName "$gitParams"
  else
    echo "Can't find Husky, skipping $hookName hook"
    echo "You can reinstall it using 'npm install husky --save-dev' or delete this hook"
  fi
fi
his hook"
  fi
fi
```    
</details>

This happens very rarely, but it does not seem to be a one-off. I've had it happen maybe two or three times now over the last few months and a few colleagues have experienced it as well.

For what it's worth, it does not seem affect all hooks. Right now 5 out of 19 are corrupt (with identical file contents) and the rest are fine. Modification time for all files is identical/close.

Seems like it must be caused by [this `fs.writeFileSync` call](https://github.com/typicode/husky/blob/3336d84cc1af605769d0a447b8af8e108b800939/src/installer/index.ts#L32) somehow.

**Comment by typicode** [comment]
Hi @Livven,

That's strange, not sure what's causing it. Unfortunately, I don't know what could be done on husky's side to fix that, sorry.
