### ISSUE TITLE
how to write husky hooks in various environment

### ISSUE THREAD

**Issue by schuman66** [typicode/husky#601]
`{
  "hooks": {
    "pre-commit": "npm test"
  }
}`
For example, I just want to husky work in test and master, not in dev environment.
How to solve the problem?

**Comment by typicode** [comment]
You would need to write some custom code or use a third-party tool. If you're looking for per NODE_ENV script, you can have a look at https://www.npmjs.com/package/per-env. For particular branches, you can use https://www.npmjs.com/package/git-branch-is (see also this thread https://github.com/typicode/husky/issues/186)
