### ISSUE TITLE
Configure Husky to use a different command than "node"?

### ISSUE THREAD

**Issue by gCardinal** [typicode/husky#604]
I'm trying to setup husky in a project using Docker for everything (local dev and deployment). 

Since I don't have node on my local machine, all my scripts in my project are configured to run a little shell script I committed to my project; `bin/node`. I can get husky to install fine, since I'm running `bin/node yarn`. The only step missing is, how could I tell husky it won't find node and should instead try to run `bin/node` in my local repository?

Is there such an option?

**Comment by typicode** [comment]
Hi @gCardinal,

Not really. Also husky v4 will call `yarn/npm` instead of `node`.
That said, husky sources `~/.huskyrc`. Maybe you could try to alias `node` to `bin/node` in this file.

**Comment by gCardinal** [comment]
That would only work on my local machine though. To me, the appeal of Husky is how it makes it so git hooks are shared. We're also using Docker here to 100% isolate external dependencies of a project from the system, so that would break that.

It's possible to put a `.huskyrc` file within the project, but that file doesn't seem to support doing aliases within that local `.huskyrc`. Would that be a possible enhancement you would consider?

**Comment by typicode** [comment]
Cleaning old issues, but husky 5 should be more flexible and doesn't use node, npm or yarn automatically.
Thanks for the feedback.
