### ISSUE TITLE
Install hooks for sub-repos without package(s).json

### ISSUE THREAD

**Issue by dcorvasce** [typicode/husky#609]
I have a worktree directory like the following:

```
mainproject/
    .git
    package.json
    submodule-a/
        .git
    submodule-b
        .git
```

Both `submodule-a` and `submodule-b` have no `package.json`. Instead, they use the `package.json` defined within `mainproject`.

Currently, **Husky** only installs hooks at the root-level. Is there a way to recursively install hooks for each sub-repo w/o a package.json?

We are using **npm**, so Yarn workspaces can't help us.

### Setup

**Git version:** 2.20.1
**OS:** Ubuntu Linux 19.04
**Shell:** zsh 5.5.1

#### `HUSKY_DEBUG=1 npm install husky --save-dev`

```
> husky@3.1.0 preuninstall /home/dom/projects/xyzcorp/mainproject/node_modules/husky
> node husky uninstall

husky:debug Current working directory is '/home/dom/projects/xyzcorp/mainproject/node_modules/husky'
husky:debug INIT_CWD environment variable is set to '/home/dom/projects/xyzcorp/mainproject'
husky > Uninstalling git hooks
husky:debug Git rev-parse command returned:
husky:debug   --show-top-level: /home/dom/projects/xyzcorp/mainproject
husky:debug   --git-common-dir: ../../.git
husky > Done

> husky@3.1.0 install /home/dom/projects/xyzcorp/mainproject/node_modules/husky
> node husky install

husky:debug Current working directory is '/home/dom/projects/xyzcorp/mainproject/node_modules/husky'
husky:debug INIT_CWD environment variable is set to '/home/dom/projects/xyzcorp/mainproject'
husky > Setting up git hooks
husky:debug Git rev-parse command returned:
husky:debug   --show-top-level: /home/dom/projects/xyzcorp/mainproject
husky:debug   --git-common-dir: ../../.git
husky:debug Installing hooks in '../../.git/hooks'
skipping existing user hook: post-merge
husky > Done

> husky@3.1.0 postinstall /home/dom/projects/xyzcorp/mainproject/node_modules/husky
> opencollective-postinstall || exit 0
```

**Comment by ThaFog** [comment]
+1, submodules should be supported by husky as for now hooks are called only for root.

@domcorvasce found out the workaround for this case:
```
GIT_DIR=$(cd <path_to_submodule> && git rev-parse --git-dir) node node_modules/husky/husky.js install
```
This actually worked for me - it just made husky think submodule is a root git repo and installed it's hooks again there

(if you're on Windows - just set GIT_DIR env var to the result of `git rev-parse --git-dir` command ran in submodule directory)

**Comment by typicode** [comment]
Closing as a workaround has been provided (thanks @ThaFog) and also because husky 5 works differently.
