### ISSUE TITLE
Confused about huskyrc options

### ISSUE THREAD

**Issue by callumlocke** [typicode/husky#611]
The readme says I can use:

- `.huskyrc` as a shell script that will be sourced before running *any* hook command.
- `.huskyrc` as a JSON file that defines your actual hook commands.

These seem like very separate features, but they share a filename. So I can't use these two features together. Why?

(I want to be able to define some custom multi-line shell functions in a shell script that I can then reuse in my hook commands. And I want to define the actual hook commands, i.e. what to run on pre-commit etc, in a JSON file separate from my package.json.)

**Comment by typicode** [comment]
Thanks for the feedback! I agree it's poorly named. This should be improved in future releases. You can use `.huskyrc.json` to avoid confusion.

Regarding multiline, you can use `.huskyrc.js` (see README for multiline example). That said it may be too simple for your case.
