### ISSUE TITLE
Can't find Husky, skipping post-commit hook — husky keeps randomly dying

### ISSUE THREAD

**Issue by waterplea** [typicode/husky#612]
I have husky in my package.json inside devDependencies of my project:

`"husky": "^3.0.9",`

When I run `npm i` or `ci` — I see that it got installed, I see `Thank you for using husky!` message. However every once in a while it randomly dies. When I commit I see `Can't find Husky, skipping post-commit hook` message. It happens for me on Windows 7, Windows 10 and Ubuntu. I have no idea how can that happen or what am I doing wrong :(

**Comment by typicode** [comment]
Hi @waterplea,

That's strange. On Windows hook scripts shouldn't contain this message (https://github.com/typicode/husky/blob/master/src/installer/getScript.ts#L69-L74)

It means that `node` command can't be found in `PATH`  env variable.

What terminal are you using on Windows and Ubuntu? Are you comitting using a GUI?
On Windows, how did you install Node?

**Comment by waterplea** [comment]
I use WebStorm on Windows 7/10 and my colleague uses VSCode on Ubuntu, here's the message: 
![image](https://user-images.githubusercontent.com/11832552/69346566-107c0100-0c84-11ea-85c5-2776a5e5d34d.png)

**Comment by typicode** [comment]
My bad, I misread the issue.

This error message means that the path to husky script doesn't exist. It's usually `node_modules/husky/husky.js`, you can check the exact value in `.git/hooks/pre-commit` (`scriptPath="..."`). 

It can happen if `node_modules` is deleted or `node_modules/husky` doesn't exist anymore.

**Comment by waterplea** [comment]
The thing is the path does exist and nothing was done to node_modules that I know of. It just stops working for be apparent reason. I'll try to find more info when this happen again.

**Comment by waterplea** [comment]
So it happened to me again today, the very next time I tried to commit something. I see that `node_modules/husky` is intact. I even installed it globally just in case, and it still told me Can't find Husky, skipping pre-commit hook.

**Comment by sveg-pl** [comment]
Hey @waterplea - I've just downgraded husky to 3.0.8 and it works. Maybe it will help you temporarily?

**Comment by aprilandjan** [comment]
I'm using husky `^3.0.9` in my monorepo proejct and facing the exact same problem. I thought it was because I sometimes do git operations in non-git-root-directory`. But even after clear `node_modules` and re-installation, the problem still exists.

**Comment by manuelbieh** [comment]
I suddenly get `Can't find Husky, skipping [...] hook`  in all my repos after I upgraded my system to Node 13 and the most recent Yarn. Will investigate on that.

**Comment by manuelbieh** [comment]
Okay, now without hurry: I upgraded my system (Windows 10, latest non-insider build) to Node 13.3.0 from 10.15.3) and Yarn from 1.17.3 to 1.21.0 and suddenly(?) in every repo in which I _freshly_ install Husky I get the `Can't find Husky, skipping [...] hook` error. I had a look at the `.git/hooks` folder and compared hook from an old, working version of Husky (from Nov 6th, 2019) with a newly installed one and the only notable difference I see is:
```
scriptPath="../../../../../htdocs/_git/react-ssr-setup/node_modules/husky/run.js"
```
(which is broken) vs.
```
scriptPath="node_modules/husky/run.js"
```
which is working.

I downgraded everything back to the last working version (incl. Husky 3.0.9) and I keep getting a broken version 🤔 

```
$ npx envinfo

  System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
    Memory: 5.76 GB / 15.85 GB
  Binaries:
    Node: 10.15.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.17.3 - C:\Program Files\nodejs\yarn.CMD
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  Managers:
    RubyGems: 2.7.6 - C:\Ruby25-x64\bin\gem.CMD
  Utilities:
    Git: 2.21.0 - C:\cygwin64\bin\git.EXE
  Virtualization:
    Docker: 19.03.2 - C:\Program Files\Docker\Docker\Resources\bin\docker.EXE
  IDEs:
    VSCode: 1.41.1 - C:\Program Files\Microsoft VS Code\bin\code.CMD
  Languages:
    Bash: 4.4.12 - C:\cygwin64\bin\bash.EXE
    Perl: 5.26.3 - C:\cygwin64\bin\perl.EXE
    Python: 2.7.15 - C:\Users\manuel\.windows-build-tools\python27\python.EXE
    Ruby: 2.6.4 - C:\cygwin64\bin\ruby.EXE
  Browsers:
    Edge: 44.18362.449.0
    Internet Explorer: 11.0.18362.1
```
Diff of a broken hook (left) and a working (right):
![image](https://user-images.githubusercontent.com/239546/71494125-f3b78800-2844-11ea-8708-fdcf09122eb4.png)

Does anybody here have an idea what's suddenly wrong?! Everything worked fine until … I don't know. Before christmas and even after reverting everything back to the old versions I keep getting a broken setup on `yarn add --dev husky` 🤷‍♂

**Comment by alexmww** [comment]
Make sure you can run `node` from the terminal you are committing from. Then, if not, check your node installation. 
For me, that was the issue.

**Comment by typicode** [comment]
Cleaning old issues also seems like workarounds/fixes have been found.
Feel free to create a new issue if it still happens.

**Comment by chovyprognos** [comment]
`scriptPath="node_modules/husky/run.js"` doesn't appear to be a valid path anymore. Does anyone know a fix?

**Comment by Eitz** [comment]
The file `run.js` doesn't exist anymore in the husky directory. I am not sure why it sets tat as the scriptPath. I am having this exact issue, not sure why this was completed.
