### ISSUE TITLE
Drop node 8 support in v4

### ISSUE THREAD

**Issue by XaveScor** [typicode/husky#616]
Hello. https://nodejs.org/en/about/releases/ Node 8 End-of-life will be in 1 month. I think you can drop node 8 support in v4.

**Comment by typicode** [comment]
Good idea, thanks :)

**Comment by typicode** [comment]
Dropped ;)

**Comment by polRk** [comment]
Firebase cloud functions on node 8 is crying.....

**Comment by typicode** [comment]
@polRk If you're not using Yarn 2, you can stay on Husky 3 for the moment ;)
I suppose Firebase will drop it as well at some point as Node 8 has reached end of life.

**Comment by polRk** [comment]
> I suppose Firebase will drop it as well at some point as Node 8 has reached end of life.

Node 10 in Beta and works with lots of bugs. I'm not sure they will turn off support node 8 until a stable release of node 10 on firebase comes out
