### ISSUE TITLE
silence husky's default messages?

### ISSUE THREAD

**Issue by heavyk** [typicode/husky#617]
possibly related to #115 and maybe #128

I was looking into customising the error messages today and the stderr message output works perfectly. however, is there a way to silence the first and last messages?

```
husky > pre-commit (node v13.2.0)
hello world
husky > pre-commit hook failed (add --no-verify to bypass)
```

I looked at the source and they're just console.logs, so there's no simple way to do it. could there be some sort of env variable, that if set skips those messages?

**Comment by typicode** [comment]
Thanks for feedback. No plan to implement that for the moment, but I'm keeping it in mind.
That said, FWIW, husky 5 is less verbose.
