### ISSUE TITLE
lint-staged command is not found

### ISSUE THREAD

**Issue by fayfang** [typicode/husky#618]
when I use package.json below, the output is 'lint-staged command is not found'
```json
{
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged"
    }
  },
  ...
}
```

when I use the npm command like this, It work
```json
{
  "scripts": {
    "lint": "lint-staged"
  },
  "husky": {
    "hooks": {
      "pre-commit": "npm run lint"
    }
  },
  ...
}
```

How can I fix it up?

OS: windows
terminal: git bash
git version: 2.17

```sh
$ HUSKY_DEBUG=1 git commit
PS D:\Users\fangyy001\Desktop\project\veb-third-web\cmbwp> git commit
husky > pre-commit (node v12.13.0)
'lint-staged' 不是内部或外部命令，也不是可运行的程序
```

**Comment by Ryuno-Ki** [comment]
Hi fayfang,

[`lint-staged`](https://www.npmjs.com/package/lint-staged) is another package. Run `npm install lint-staged --save-dev` to install it.

**Comment by fayfang** [comment]
> Hi fayfang,
> 
> [`lint-staged`](https://www.npmjs.com/package/lint-staged) is another package. Run `npm install lint-staged --save-dev` to install it.

yeah, but I am confused that why the cmd in ./node_module/.bin can not be used when git commit. not only the lint-staged ,but also all the cmd in ./node_module/.bin can not be used.

**Comment by Ryuno-Ki** [comment]
Can you show the error message?
(In case you're using macOS or a GNU/Linux distribution, force an English message via `LC_ALL=C ./node_modules/.bin/husky` resp. with the `git` command).

**Comment by typicode** [comment]
It may be worth testing with Husky v4.

As the reason why `npm run lint` works but not calling `lint-staged` directly, I suspect it's because `npm run` modifies `PATH` to include `node_modules/.bin`. On the other side, when hook commands are run `PATH` isn't modified.

**Comment by barretron** [comment]
> On the other side, when hook commands are run `PATH` isn't modified.

Is this an intentional change in behavior from v3? I'm running into the same issue.

**Comment by Manubi** [comment]
`.husky/pre-commit: line 4: lint-staged: command not found` 
I get now this error message with husky v5.0.4 and lint-staged v10.5.1

**Comment by typicode** [comment]
> Update: Adding yarn lint-staged to the pre-commit husky file fixed it.

That's the right fix, for husky v5 and v4, locally installed commands need to be run via the package manager.
So `yarn lint-staged` or `npx --no-install lint-staged` will work.

Alternatively, this will work too:

```js
// .husky/pre-commit (v5) or .huskyrc (v4)
npm run pre-commit
```

```js
// package.json
{
  "scripts": {
    "pre-commit": "lint-staged"
  }
}
```

**Comment by AbnerPS** [comment]
If the husky hook is not being called, try to install version 4: npm install husky@4 --save-dev

**Comment by scoobster17** [comment]
To follow @typicode's message:

**Comment by scoobster17** [comment]
To follow @typicode's message:

> I suspect it's because npm run modifies PATH to include node_modules/.bin. On the other side, when hook commands are run PATH isn't modified.

If you change your `.husky/pre-commit` to include this path, it works with husky@latest:

```
#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

node_modules/.bin/lint-staged
```

**Comment by michelmany** [comment]
Adding `npx lint-staged` to the pre-commit husky file fixed it for me.

**Comment by kevinbrian-cortex** [comment]
> Adding `npx lint-staged` to the pre-commit husky file fixed it for me.

Also this worked for me.

**Comment by SercanSercan** [comment]
> Adding `npx lint-staged` to the pre-commit husky file fixed it for me.

I should've read your comment earlier :D
