### ISSUE TITLE
Avoid Husky from being triggered for changes on every unrelated directory in monorepo project

### ISSUE THREAD

**Issue by khanhtc1202** [typicode/husky#619]
Hey guys, thanks for the wonderful tool. I'm using husky in a subdirectory of my monorepo project which has more than one directory that contains package.json file as below

```
sample
├── .git
├── module_A
│   └── package.json  // contains husky as its dependency
└── module_B
    └── package.json  // not contain husky
```

When I try to commit changes on module_B (not contain husky), it's triggered and run check pre-commit for module_A itself even I do not change anything in that directory. Is is possible to make husky just being triggered when has changes in its local directory (module_A in this case) only? And how can I config husky that way.

Thanks for your time.

**Comment by typicode** [comment]
If you're working with a monorepo, I would suggest using [lerna](https://github.com/lerna/lerna) and `lerna run` command with `--since` flag. 

See also https://github.com/typicode/husky/issues/624#issuecomment-571421881

**Comment by khanhtc1202** [comment]
I just found out that `--no-verify` flag ignores triggered husky run in specific cases as well. Thank you for your help!

**Comment by castroCrea** [comment]
I found a way to run husky only on the folder where change are happening, but you need husky at the root of your repo

https://stackoverflow.com/a/68118548/6253167

```
// ~/.husky/pre-push

#!/bin/sh
. "$(dirname $0)/_/husky.sh"

declare IS_APP_FOLDER_CHANGE=$(git show --name-only -r --stat --oneline HEAD^^..HEAD | grep 'app/')

echo "IS_APP_FOLDER_CHANGE  --> + $IS_APP_FOLDER_CHANGE"

if [[ $IS_APP_FOLDER_CHANGE ]]; then cd app && yarn test --watchAll=false && cd ..; fi
```
