### ISSUE TITLE
Use husky without package.json?

### ISSUE THREAD

**Issue by tommyalatalo** [typicode/husky#620]
Since I can't find any mention of an online support forum, slack channel or similar, I have to ask here.

Is it possible to use husky on a per-repo basis without having a package.json file?
I would like to use husky in non-node repositories and be able to use some file like "myrepo/.husky" from where husky would load my hooks. Currently it specifically has to be a package.json file, right?

**Comment by hummal** [comment]
It is mentioned in the documentation in the README that you can also use .huskyrc and more. Also there is a .huskyrc file in the repo itself where you can see how to use.

**Comment by typicode** [comment]
Yes. Currently husky needs to be defined in `package.json` as a `devDependency` but configuration can be defined in `.huskyrc`.

**Comment by felipecassiors** [comment]
Using husky as a global package and `.huskyrc` doesn't currently work. 

```json
// .huskyrc
{
  "hooks": {
    "commit-msg": "commitlint -E HUSKY_GIT_PARAMS"
  }
}
```

```bash
$ gitpod /workspace/semantic-release-vagrant-test $ npm install -g husky
> husky@4.2.1 preuninstall /home/gitpod/.nvm/versions/node/v10.18.0/lib/node_modules/husky
> node husky uninstall
husky > Uninstalling git hooks
Can't find package.json in /workspace/semantic-release-vagrant-test directory or parents
Please check that your project has a package.json or create one and reinstall husky.
husky > Failed to uninstall
/home/gitpod/.nvm/versions/node/v10.18.0/bin/husky-run -> /home/gitpod/.nvm/versions/node/v10.18.0/lib/node_modules/husky/bin/run.js
/home/gitpod/.nvm/versions/node/v10.18.0/bin/husky-upgrade -> /home/gitpod/.nvm/versions/node/v10.18.0/lib/node_modules/husky/lib/upgrader/bin.js
> husky@4.2.1 install /home/gitpod/.nvm/versions/node/v10.18.0/lib/node_modules/husky
> node husky install
husky > Setting up git hooks
Can't find package.json in /workspace/semantic-release-vagrant-test directory or parents
please check that your project has a package.json or create one and reinstall husky.
husky > Failed to install
> husky@4.2.1 postinstall /home/gitpod/.nvm/versions/node/v10.18.0/lib/node_modules/husky
> opencollective-postinstall || exit 0
Thank you for using husky!
If you rely on this package, please consider supporting our open collective:
> https://opencollective.com/husky/donate
+ husky@4.2.1
updated 1 package in 2.033s
```

**Comment by hummal** [comment]
I guess that comes from the term, that installing husky in the project also installs the git hooks. Without this project wide install it won't install and execute the hooks by git, because there is no code that refers to husky itself I guess.

**Comment by felipecassiors** [comment]
@hummal I didn't get it. As you can see in the log, the `husky` install resolves the current folder as the project folder (so it would be able to inject the hooks), but says that there is no `package.json`, despite it already have a `.huskyrc`.

**Comment by hummal** [comment]
if you do the same with `npm i husky -D` in the project folder, does it correctly install the git hooks?
