### ISSUE TITLE
Follow config.js files convention for a `husky.config.js`

### ISSUE THREAD

**Issue by vabatta** [typicode/husky#621]
As the title says, would be great to be able to setup the configuration inside a file named `husky.config.js` and follow the convention that most of the tools is now adapting.

**Comment by typicode** [comment]
You can. Actually, you can define config in any file supported by [cosmiconfig](https://github.com/davidtheclark/cosmiconfig). But for the sake of brevity, not all of them are mentioned. 

That said, I know that Jest and Webpack use `*.config.js` in their docs. Which other tools are you thinking about?

**Comment by vabatta** [comment]
Well, tons of them. Just to mention a few that I use across different projects: `babel-plugin-macros.config.js`, `babel.config.js`, `commitlint.config.js`, `lint-staged.config.js`, `next.config.js`, `postcss.config.js`, `prettier.config.js`, `stylelint.config.js`, `tailwind.config.js`, ...

**Comment by typicode** [comment]
Thanks for the list!

**Comment by typicode** [comment]
I've updated the README :+1:
