### ISSUE TITLE
Add option to ignore npm/yarn script "precommit"

### ISSUE THREAD

**Issue by StephanBijzitter** [typicode/husky#622]
Using Husky 3.1.0

This issue is about this message:
```
Warning: Setting pre-commit script in package.json > scripts will be deprecated
Please move it to husky.hooks in package.json, a .huskyrc file, or a husky.config.js file
Or run ./node_modules/.bin/husky-upgrade for automatic update
```

My `package.json` currently looks like this:
```json
  "scripts": {
    "precommit": "yarn lint-staged && yarn unit",
    "commit": "git-cz",
    "unit": "jest --config=./scripts/jest/config.js --no-cache",
  },
  "lint-staged": {
    "**/*.ts": [
      "yarn eslint --quiet"
    ]
  },
  "husky": {
    "hooks": {
      "commit-msg": "commitlint -E HUSKY_GIT_PARAMS"
    }
  }
```

When running `yarn commit`, I expect the following to happen:
```
run linting
run unit tests
open git-cz to type commit message
lint commit message
```
But instead, this happens:
```
run linting
run unit tests
open git-cz to type commit message
run linting
run unit tests
lint commit message
```

I've arranged my scripts this way to run the unit tests before being able to write a commit message, as the unit tests contain a lot of in-browser tests, that are quite slow. It's very annoying to write a detailed commit message only to find out the tests are failing, and then having to write the message again.

Could an option be added to _never_ treat anything in the `scripts` dictionary  as a hook?

**Comment by typicode** [comment]
Since husky 4 is in maintenance and husky 5 doesn't have this issue, I'm going to close it.
That said, good suggestion and thanks for the PR :+1:
