### ISSUE TITLE
[4.0.5]: break on CI system without git installed

### ISSUE THREAD

**Issue by ggascoigne** [typicode/husky#636]
The recent change to have husky exit with a real error code is causing my CI build to fail.  For a variety of historical reasons we don't have git available during our CI builds, the old behavior of having husky fail to install silently was quite beneficial to us in this situation.

I can see that generally the error code is a good thing, but would you be open to allowing a silent failure if for example a CI specific environment variable was set?

**Comment by Gyunikuchan** [comment]
This is causing grief for us as well when attempting to build docker images from an intermediary clean artifact

**Comment by duongdev** [comment]
Getting (maybe) the same issue on Heroku.

```
...yarn install log...

       [4/4] Building fresh packages...
       error /tmp/build_21a0d1a4fbaaf18063cb8d3ef91e86e8/node_modules/husky: Command failed.
       Exit code: 1
       Command: node husky install
       Arguments: 
       Directory: /tmp/build_21a0d1a4fbaaf18063cb8d3ef91e86e8/node_modules/husky
       Output:
       husky > Setting up git hooks
       fatal: not a git repository (or any parent up to mount point /)
       Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
       husky > Failed to install
       info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       Some possible problems:
       
       - Node version not specified in package.json
         https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version
       
       Love,
       Heroku
       
 !     Push rejected, failed to compile Node.js app.
 !     Push failed
```

**Comment by tonyjeffrey** [comment]
the same problem 
<img width="794" alt="MacHi 2020-01-10 14-29-57" src="https://user-images.githubusercontent.com/21188025/72130984-f7571d00-33b5-11ea-8d15-01d9c3b44d8f.png">

**Comment by tonyjeffrey** [comment]
`const a = '111';
const b = '222';`

**Comment by yoyo837** [comment]
Same here.

**Comment by duongdev** [comment]
Seems we have several releases since yesterday but the issue wasn't completely fixed.

![image](https://user-images.githubusercontent.com/9253690/72132239-06879c00-33b1-11ea-8b35-4ee69b5a84e3.png)

**Comment by typicode** [comment]
It has been reverted in v4.0.6. Sorry about the issue.

**Comment by fullstackzach** [comment]
We ran into this too and found it could be fixed by specifying the env variable following in the Dockerfile to skip the install.

Before `npm install` `npm ci` or `yarn` 
add `ENV HUSKY_SKIP_INSTALL=1` in your Dockerfile.

I just noticed this github issue now and saw it was reverted in 4.0.6, but thought I'd still share this option
