### ISSUE TITLE
Seems not respecting `--silent`

### ISSUE THREAD

**Issue by tunnckoCore** [typicode/husky#64]
It seems it not respects the `alias npm="npm --silent"`.

**Comment by iamstarkov** [comment]
what do you mean by that?

**Comment by tunnckoCore** [comment]
i have this alias, and when fails for example the commit-msg hook it outputs npm's 20 lines error, which i dont like and that's silent flag for

**Comment by tunnckoCore** [comment]
i believe, it's because you use bash's `command npm ...`.

i have an idea, why not just call `node path/to/jsfile.js` instead of creating and workin on bash file. i'll show what i mean, im on phone now.

**Comment by iamstarkov** [comment]
husky is separated from npm, so how npm silent flag will help you with husky?

**Comment by tunnckoCore** [comment]
What about if we just create simple Bash file for in the hook dir, then just call node from it.

**example .git/hooks/commit-msg**

```bash
#!/usr/bin/env bash
node path/to/file.js
```

And actually the hook will be plain javascript file which will allow cool things. Idea is more advanced and I'm going to implement it in https://github.com/tunnckoCore/npm-hooks

**Comment by iamstarkov** [comment]
npm hooks' environment is different from plain node environment

**Comment by mrmckeb** [comment]
It would be great to resolve this, having large NPM errors logged out makes the actual error harder to see.

**Comment by marvinhagemeister** [comment]
PR #73 is a different config based approach which would satisfy both positions. At work there are some of us who prefer to suppress npm's verbose error output and some who prefer the verbose version.

**Comment by marvinhagemeister** [comment]
We'll my coworkers were bugging me a lot with this the past week, so I finally gave in and created a minimal fork with my PR applied. It is published on npm under the package name: [husky-dontbark](https://github.com/marvinhagemeister/husky/tree/husky-dontbark).

Obviously a fork is not an optimal solution and I'd love to bring some sort of silence mode into core (either via my PR or something else). We basically have two different opinions in this thread: The first group who expects errors to be explicit and the second one who trusts the actual scripts that get called to output anything useful.

In either case husky itself prints a sweet error message upon a failing hook:

```bash
husky - pre-commit hook failed (add --no-verify to bypass)
```

**Comment by davidhund** [comment]
@typicode: any plans on merging this PR #73?

**Comment by tunnckoCore** [comment]
:+1:

**Comment by nerdgore** [comment]
Has anyone tried an npmrc file? It works wonderfully for me. IMO there is no need to add a config option to the package.json.
![screen shot 2017-01-04 at 09 50 33](https://cloud.githubusercontent.com/assets/1582533/21636675/db19de72-d263-11e6-977e-e9678ec46616.png)

**Comment by tunnckoCore** [comment]
Don't know. I was using `pre-commit` last year or so and last days I switched to husky for a bit, but back switched to pre-commit. Reasons were that it outputs yellow output with NPM ERR, but exits with no errors so the task is run successfully (the task is `git-cz`) and the second one is that I had `prepush: npm test` but it seemed that it does not run the tests.
