### ISSUE TITLE
Double confirmation for a specific push

### ISSUE THREAD

**Issue by multivoltage** [typicode/husky#641]
Hi guys. I already used husky. Unfortunatly now I work for a project where if user push on master, the push will trigger a production release. It is possible to catch the push with husky and print some red text color whit "are you sure? yes/no". And if User tap yes it will push

**Comment by EmmanuelDemey** [comment]
have you tried writing your own node script ?

**Comment by multivoltage** [comment]
Hello. Unfortunately my company has switched me to other projects even though I haven't solved my problem. So I think you can quit :(
