### ISSUE TITLE
version 4 throws bad variable name error

### ISSUE THREAD

**Issue by whimzyLive** [typicode/husky#649]
Upgrading from 3.x to 4.x throws bad variable name error.

## Received error:
```sh 
Received error `.git/hooks/pre-push: 70: export: refs/heads/improvement/15-add-json-schema-validator: bad variable name`.```

Sorry for short description.

**Comment by hovancik** [comment]
Same here: 

```
.git/hooks/pre-push: 70: export: 158cde09f524a38a403430302a69f64b1d8d264b: bad variable name
```

**Comment by hovancik** [comment]
More info: 

`Hook created by Husky v4.0.9`

not sure if 70 is line number, but: 

```
case $hookName in
  "pre-push"|"pre-receive"|"post-receive"|"post-rewrite")
    export HUSKY_GIT_STDIN=`cat`;; //LINE 70
esac
```

**Comment by whimzyLive** [comment]
yes, it was line 70 for me too. I will have a look at this tomorrow, see if I can fish out something more useful, or even pick up what is causing this errors

**Comment by typicode** [comment]
Thanks for the report, could you try with Husky `v4.0.10`?

**Comment by dcaillibaud** [comment]
I had this pb, upgrading to v4.0.10 solve the export pb but since I have a failure without info  (and without running test, because of immediate response)

```
git push
husky > pre-push (node v10.18.1)
husky > pre-push hook failed (add --no-verify to bypass)
error: failed to push some refs to 'git@framagit.org:Sesamath/…'
```
pre-commit hook is fine, with the config :

```
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged",
      "pre-push": "test"
    }
  },
  "lint-staged": {
    "*.js": [
      "eslint --fix",
      "git add"
    ]
  }
```

I'm using `pnpm`, and running `pnpm test` is fine.

**Comment by typicode** [comment]
Closing since the original issue `bad variable name error` is fixed. @dcaillibaud could you open another issue and try running with `HUSKY_DEBUG=1`?

**Comment by whimzyLive** [comment]
Thanks @typicode.
