### ISSUE TITLE
Husky pre commit for directory parallel to node_modules

### ISSUE THREAD

**Issue by aakashwt** [typicode/husky#660]
Before creating an issue, see [troubleshoot](https://github.com/typicode/husky#troubleshoot) section in the README and verify that you're using Git `>= 2.13.0`.

Please provide your OS, terminal and the following commands output:

```sh
$ HUSKY_DEBUG=1 npm install husky --save-dev
$ HUSKY_DEBUG=1 git commit # ...
```

My directory structure is something like this

my-app
   -node_modules
  - src
     - package.json
     - app
  - projects
     - src
        - package.json
        -lib

How can we format directory by tslint in pre-commit?

// package.json
{
  "husky": {
    "hooks": {
      "pre-commit": "npm test", // HERE need to format directory (both src and project) by tslint
      "pre-push": "npm test",
      "...": "..."
    }
  }
}

**Comment by typicode** [comment]
If you want to format both directory, you can either have a `pre-commit` in one of the directory (either `src/.huskyrc` or `projects/src/.huskyrc`) and run lint command in both directories with something like: `tslint && cd <some other dir> && tslint` for example.

But if you have a monorepo, a more elegant and recommended solution would be to use lerna:
https://github.com/typicode/husky#monorepos
