### ISSUE TITLE
[FEATURE-REQUEST] Concurrent mode

### ISSUE THREAD

**Issue by VincentLanglet** [typicode/husky#663]
When using pre-commit hooks, `lint-staged` give a great silent/concurrent mode.

With
```
"lint-staged": {
        "*.js": "eslint",
        "*.less": "stylelint"
    },
"husky": {
        "hooks": {
            "pre-commit": "lint-staged",
        }
    },
```
The two scripts will be executed at the same time and the hook fail as soon as one script fail.

But I don't see a way to do the same for prepush hooks.
```
"husky": {
        "hooks": {
            "pre-push": ["eslint", "stylelint"]
        }
    },
```

I know the syntax `eslint && stylelint` can do the job, but I don't want to wait for the whole execution of `eslint` if `stylelint` could fail before.

**Comment by typicode** [comment]
Hi @VincentLanglet,

I would suggest using Husky with a third-party tool. For example, https://www.npmjs.com/package/npm-run-all

**Comment by shiftgeist** [comment]
@VincentLanglet have you tried 
```diff
- "pre-push": "eslint && stylelint"
+ "pre-push": "eslint & stylelint"
`
this should execute eslint and stylelint at the same time, but i don't know it the other stops when one fails.

**Comment by VincentLanglet** [comment]
> Single `&` should execute eslint and stylelint at the same time

I didn't know the syntax `&`.

> but i don't know it the other stops when one fails.

Just tried, it runs concurrently but one failure doesn't stop other processes.

**Comment by shiftgeist** [comment]
Imo `&&` runs things sequencial while `&` runs concurrent.
