### ISSUE TITLE
[Documentation] Yarn 2 Berry PnP setup instructions

### ISSUE THREAD

**Issue by dzintars** [typicode/husky#664]
Is there any place to read about "edge" setup with Yarn 2 and pure PnP project?
It seems like everything in my side is installed as recommended in various places, still, hooks are not triggered and no any errors provided.
I would be grateful for a clean and precise section in the documentation on how to set up Husky in pure Berry PnP project.

**Comment by typicode** [comment]
Hi @dzintars,

I think it's because of Yarn's cache and Husky install script is run once. Could you try running `yarn rebuild`?

**Comment by hallettj** [comment]
In case it helps I can confirm that Husky's hooks *are* set up correctly with Yarn 2 in my test. (I thought that I had the same problem as @dzintars until I remembered that I forgot to run `git init` before installing Husky 🤦‍♂️.)

These are the steps that I ran in an empty directory, with yarn 1.21.1 as my global yarn executable (I switched to Yarn 2 with the `yarn policies set-version berry` step):

    $ git init
    $ yarn init # accept all defaults
    $ yarn policies set-version berry
    $ yarn add --dev husky # console output includes lines, "husky@npm:4.2.1 must be built because it never did before or the last one failed\nCompleted in 0.39s"
    $ ls -l .git/hooks # hooks are present as well as `husky.sh` and `husky.local.sh`

**Comment by dzintars** [comment]
Tnx @hallettj and @typicode 
I made a quick test as suggested above by @hallettj  and there is what I got. Most likely it's somewhat related to my Fedora environment, but I will document it there. Mby it will help for somebody else.

```sh
cd husky-test && git init
Initialized empty Git repository in husky-test/.git/
```

```sh
 yarn init -y
{
  name: 'husky-test'
}
```

```sh
 yarn policies set-version berry
Internal Error: husky-test@workspace:.: This package doesn't seem to be present in your lockfile; try to make an install to update your resolutions
    at t.RunInstallPleaseResolver.getCandidates (/usr/local/lib/node_modules/yarn/bin/yarn.js:36:863677)
    at t.MultiResolver.getCandidates (/usr/local/lib/node_modules/yarn/bin/yarn.js:24:41320)
    at /usr/local/lib/node_modules/yarn/bin/yarn.js:36:581640
    at /usr/local/lib/node_modules/yarn/bin/yarn.js:36:857805
    at new Promise (<anonymous>)
    at e.exports (/usr/local/lib/node_modules/yarn/bin/yarn.js:36:857787)
    at i (/usr/local/lib/node_modules/yarn/bin/yarn.js:24:91764)
    at /usr/local/lib/node_modules/yarn/bin/yarn.js:24:91837
    at /usr/local/lib/node_modules/yarn/bin/yarn.js:24:91880
    at new Promise (<anonymous>)
```

```sh
yarn --version
2.0.0-rc.27
uname -r
5.4.15-200.fc31.x86_64
node --version
v12.14.1
```
I will continue tomorrow.

**Comment by hallettj** [comment]
@dzintars Unfortunately the command for setting the yarn version for your project is different depending on whether your globally-installed `yarn` executable is version 1 or 2. (See https://github.com/yarnpkg/berry/issues/773)

if your global `yarn` is version 1 the command is:

    $ yarn policies set-version berry

if your global `yarn` is version 2 (as in your case) the command is:

    $ yarn set version berry

As I understand it the best practice right now is to keep your global install on version 1 (per the [install instructions](https://next.yarnpkg.com/getting-started/install)). If your project is using yarn 2 you are going to want to run the command to set the version to `berry` regardless, which creates something like lockfiles in your repo (`.yarnrc` and `.yarn/releases/yarn-berry.js`). A global yarn 1 executable works with both yarn 1 projects, and with yarn 2 projects that have those files checked in.

**Comment by caassandra** [comment]
Bumping to say that I'm running into this same problem. I did a little digging, but couldn't find a solution. I'm not really invested enough to pursue this further because this is a new project and I'd rather just use Yarn v1, but in case someone wants to pick up the trail where I left off, here's what I found.

```
$ HUSKY_DEBUG=1 git commit 
husky:debug husky v4.2.5 - pre-commit
husky:debug Current working directory is [...]
husky:debug yarn run --silent husky-run exited with 0 exit code
```
So according to the debug logs, husky successfully ran the hook, but according to me, it didn't. This seems to be a problem with actually calling yarn, so I added a hook that would just fail.

```json
{
"scripts": {
    "fail": "exit 1"
  },
  "husky": {
    "scripts": {
      "pre-commit": "fail",
    }
  },
}
```

Nothing, still. Weirdly, using the deprecated `"precommit"` script works when you also include the new configuration and prefix the command with `yarn`:

```json
{
  "scripts": {
    "fail": "exit 1",
    "precommit": "echo \"this works\" && yarn fail"
  },
  "husky": {
    "scripts": {
      "pre-commit": "fail"
    }
  }
}
```

```
$ git add . && HUSKY_DEBUG=1 git commit
husky:debug husky v4.2.5 - pre-commit
husky:debug Current working directory is [...]

Warning: Setting pre-commit script in package.json > scripts will be deprecated.
Please move it to husky.hooks in package.json or .huskyrc file.

For an automatic update you can also run:
npx --no-install husky-upgrade
yarn husky-upgrade

See https://github.com/typicode/husky for more information.

husky > pre-commit (node v14.3.0)
this works
husky > pre-commit hook failed (add --no-verify to bypass)
husky:debug yarn run --silent husky-run exited with 1 exit code
```

Looking through [the source code](https://github.com/typicode/husky/blob/master/src/runner/index.ts), it seems like the only difference is how the commands are collected. It seems like the only difference in how the process works for [the deprecated format](https://github.com/typicode/husky/blob/master/src/runner/index.ts#L11-L25) and the [current format](https://github.com/typicode/husky/blob/master/src/runner/index.ts#L27-L32) is how the commands are found, not in how they're run. Which makes sense, I guess.

```
$ yarn --version
2.1.1
$ node --version
v14.3.0
$ ls .git/hooks | grep husky
husky.local.sh
husky.sh
$ yarn why husky
yarn why husky
└─ project@workspace:.
   └─ husky@npm:4.2.5 (via npm:^4.2.5)
```

I hope this helps someone someday! Otherwise I just wasted my morning 😅

**Comment by dzintars** [comment]
@caassandra Yarn v`2.1.1`? Looks like i am missing something. :) Mine is just v`2.0.0-rc.36.git.20200706.0d45e383`.

**Comment by caassandra** [comment]
@dzintars i _just_ started trying out yarn v2, so i probably downloaded a newer version 🙃 but as far as I'm aware it should be basically the same.

**Comment by kirill-konshin** [comment]
Somehow it does work for me with no extra configuration...

**Comment by caassandra** [comment]
@kirill-konshin the hooks run and everything? and you're using pnp? can u post the output of the commands i wrote above (`yarn --version` etc)?

**Comment by kirill-konshin** [comment]
@caassandra 

```
% yarn --version
2.1.1
% node --version
v14.4.0
% ls .git/hooks | grep husky
husky.local.sh
husky.sh
% yarn why husky
└─ project@workspace:.
   └─ husky@npm:4.2.5 (via npm:4.2.5)
```

I can tell that hooks are working because commit takes long time, we're doing type checks.

**Comment by caassandra** [comment]
Ok, since the only difference between our outputs is the node version, I upgraded from `v14.3.0` to `v14.6.0` and created a new repo, and everything seemed to work... I guess we can close this issue with the workaround of "upgrade node to v14.4.0"?

For reference, these were the steps I took:

1. Created a new yarn project

```zsh
❯ mkdir husky-test && cd husky-test && git init && yarn init -y
Initialized empty Git repository in /Users/[...]/husky-test/.git/
yarn init v1.22.4
success Saved package.json
✨  Done in 0.05s.
```

2. Set the version to berry and add husky as a devDependency.

```zsh
❯ yarn set version berry
Resolving berry to a url...
Downloading https://github.com/yarnpkg/berry/raw/master/packages/berry-cli/bin/berry.js...
Saving it into /Users/[...]/husky-test/.yarn/releases/yarn-berry.js...
Updating /Users/[...]/husky-test/.yarnrc.yml...
Done!

❯ yarn add -D husky
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed in 1.6s
➤ YN0000: ┌ Fetch step
➤ YN0013: │ [... fetching dependencies ...]
➤ YN0000: └ Completed in 0.3s
➤ YN0000: ┌ Link step
➤ YN0007: │ husky@npm:4.2.5 must be built because it never did before or the last one failed
➤ YN0000: └ Completed in 1.1s
➤ YN0000: Done in 3.01s
```

3. Add a few different types of hooks to make sure everything worked. I wanted a shell hook, a JS hook, and a yarn command hook.

`package.json`:
```jsonc
{
  "name": "husky-test",
  "version": "1.0.0",
  "main": "index.js",
  "author": "caassandra <cass@swag.lgbt>",
  "license": "MIT",
  "devDependencies": {
    "commitizen": "^4.1.2",
    "cz-emoji": "^1.2.1",
    "husky": "^4.2.5"
  },
  "scripts": {
    // test.js contains: console.log("Hello from JS!")
    "js-test": "node test.js"
  },
  "husky": {
    "hooks": {
      // husky should be able to execute shell commands and yarn commands
      "pre-commit": "echo \"Hello from shell!\" && yarn js-test",
      // husky should work with yarn PnP dependencies as well
      "prepare-commit-msg": "exec < /dev/tty && git cz --hook || true"
    }
  },
  "config": {
    "commitizen": {
      // gotta have my emoji
      "path": "cz-emoji"
    }
  }
}
```

4. Add files and commit

```zsh

❯ git add . && git commit
husky > pre-commit (node v14.6.0)
Hello from shell!
Hello from JS!
husky > prepare-commit-msg (node v14.6.0)
(node:98198) [MODULE_NOT_FOUND] [...] # Yarn complaining about undeclared dependencies
cz-cli@4.1.2, cz-emoji@1.2.1

? Select the type of change you're committing: (Use arrow keys or type to search)
[...]
```

I guess something changed somehow? Looking through the changelog, [there's not anything immediately obvious](https://nodejs.org/en/blog/release/v14.4.0/#commits) that would have impacted things, but literally nothing else has changed?

```zsh
❯ yarn --version
2.1.1

❯ node --version
v14.6.0

❯ ls .git/hooks | grep husky
husky.local.sh
husky.sh

❯ yarn why husky
└─ husky-test@workspace:.
   └─ husky@npm:4.2.5 (via npm:^4.2.5)
```

@dzintars Try upgrading yarn and node to `2.1.1` and `v14.4.0` respectively, and see if it works for you.

**Comment by dzintars** [comment]
@caassandra Thank You! Quick and dirty test in existing project seems to work for me now. Seems it was fixed somewhere upstream. Late there. I will test tomorrow and will close this.

**Comment by dzintars** [comment]
Yeah.. it's working now like a charm! :) Yaayyy! :) Happy husky! :)

**Comment by Necroskillz** [comment]
Also wasn't working for me, the issue was old `git` version. Problem is yarn 2 does not show output from install scripts. I had to add `process.exit(1)` to `run()` method and `yarn rebuild` to force it to show me a link to file (!) with a log,

```
husky > Setting up git hooks
husky:debug Current working directory is C:\Devel\tns\client\.yarn\unplugged\husky-npm-4.2.5-30d80a2ef8\node_modules\husky
Husky requires Git >=2.13.0. Got v2.10.2.
husky:debug Error: Husky requires Git >=2.13.0. Got v2.10.2.
    at Object.checkGitVersion (C:\Devel\tns\client\.yarn\unplugged\husky-npm-4.2.5-30d80a2ef8\node_modules\husky\lib\installer\checkGitVersion.js:16:15)
    at run (C:\Devel\tns\client\.yarn\unplugged\husky-npm-4.2.5-30d80a2ef8\node_modules\husky\lib\installer\bin.js:61:31)
    at Object.<anonymous> (C:\Devel\tns\client\.yarn\unplugged\husky-npm-4.2.5-30d80a2ef8\node_modules\husky\lib\installer\bin.js:91:1)
    at Module._compile (internal/modules/cjs/loader.js:1236:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1257:10)
    at Module.load (internal/modules/cjs/loader.js:1085:32)
    at Function.external_module_.Module._load (C:\Devel\tns\client\.pnp.js:14441:14)
    at Module.require (internal/modules/cjs/loader.js:1125:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (C:\Devel\tns\client\.yarn\unplugged\husky-npm-4.2.5-30d80a2ef8\node_modules\husky\husky.js:21:3)
husky > Failed to install
```
