### ISSUE TITLE
Precommit hook fails inside Visual Studio 2019

### ISSUE THREAD

**Issue by lucipacurar** [typicode/husky#673]
Hi,

I have `git version 2.24.1.windows.2`, `husky 4.2.3`, `VS2019 16.4.5`,  `pretty-quick 2.0.1` and `husky` fails to run inside `VS2019` only with the following message:

```
 husky > pre-commit (node v12.14.0)
/c/[my_project_path_here]/ClientApp/node_modules/.bin/pretty-quick: line 5: cygpath: command not found
internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module 'C:\pretty-quick\bin\pretty-quick.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
husky > pre-commit hook failed (add --no-verify to bypass)
```

But it works perfectly fine from `git bash` and other git clients like SourceTree and Tortoise. I'm not sure how can I run `husky` in debug mode from VS so I can provide you with the debug log. With `husky 3.1.0` it works just fine. Please let me know if you need more info. Thank you :)

**Comment by longcui** [comment]
same issue here

**Comment by volser** [comment]
same issue but for GitHub Desktop for Windows

**Comment by dwilliams1994** [comment]
I also have this issue. As suggested, downgrading Husky to 3.1.0 appears to fix it_

**Comment by vmo-mgosling** [comment]
Also having this issue with GitHub Desktop.

**Comment by barisusakli** [comment]
This seems similar to https://stackoverflow.com/questions/61196309/husky-4-x-not-working-with-visual-studio-git, maybe try the solution from that link.

**Comment by Slettan** [comment]
> This seems similar to https://stackoverflow.com/questions/61196309/husky-4-x-not-working-with-visual-studio-git, maybe try the solution from that link.

Thanks for the link, this worked for me:

```json
"scripts": {
  "format-staged": "pretty-quick --staged"
},
"husky": {
  "hooks": {
    "pre-commit": "npm run format-staged"
  }
}
```

**Comment by nycgavin** [comment]
> > This seems similar to https://stackoverflow.com/questions/61196309/husky-4-x-not-working-with-visual-studio-git, maybe try the solution from that link.
> 
> Thanks for the link, this worked for me:
> 
> ```json
> "scripts": {
>   "format-staged": "pretty-quick --staged"
> },
> "husky": {
>   "hooks": {
>     "pre-commit": "npm run format-staged"
>   }
> }
> ```

Try
"husky": {
  "hooks": {
    "pre-commit": "npx pretty-quick --staged"
  }
}

**Comment by aminya** [comment]
This is not specific to Visual Studio. 
I have the same error with commit lint on GitHub desktop or Atom.
https://github.com/conventional-changelog/commitlint/issues/1665

**Comment by LloydTao** [comment]
i have this issue on GitHub Desktop. 

it appears to be specific to `commitlint` (https://github.com/conventional-changelog/commitlint/issues/1665).

removing this from my `package.json` instantly fixes the problem:

```
  "husky": {
    "hooks": {
      "commit-msg": "commitlint -E HUSKY_GIT_PARAMS",
      "pre-commit": "lint-staged"
    }
  },
```



the error log gives a small indication of what's happening.

it incorrectly looks in: 

- `C:\Users\Lewis\AppData\Local\GitHubDesktop\app-2.5.5\resources\app\git\node_modules\yarn\bin\yarn.js`

where the real path is:

- `C:\Users\Lewis\AppData\Roaming\npm\node_modules\yarn\bin\yarn.js`

---

error log:

```
Commit failed - exit code 1 received, with output: '/c/Users/Lewis/AppData/Roaming/npm/yarn: line 5: cygpath: command not found
internal/modules/cjs/loader.js:1032
  throw err;
  ^

Error: Cannot find module 'C:\Users\Lewis\AppData\Local\GitHubDesktop\app-2.5.5\resources\app\git\node_modules\yarn\bin\yarn.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1029:15)
    at Function.Module._load (internal/modules/cjs/loader.js:898:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}'
```

**Comment by rlam3** [comment]
@LloydTao Were you able to find a workaround solution?

**Comment by jmejiaxdev** [comment]
Hi! A brute solution is removing whatever hook (e.g. `husky`) folder located inside your `.git` folder

**Comment by aminya** [comment]
> Hi! A brute solution is removing whatever hook (e.g. `husky`) folder located inside your `.git` folder

Well, I actually do this. Other people use Husky in their projects, and when I want to contribute to their projects, I get rid of the hooks first so I can commit a change! 🙄

**Comment by typicode** [comment]
Not sure but it seems to be a PATH issue. Could you try logging PATH?

In `~/.huskyrc`:

```sh
echo "$PATH" > PATH.txt
```

**Comment by BarakMaozCIQ** [comment]
I have an issue here, some know how to solve it? 
![image](https://user-images.githubusercontent.com/71022764/106167038-77a11980-6195-11eb-8033-e36ca96b1095.png)

**Comment by lucipacurar** [comment]
@BarakMaozCIQ you have some workarounds posted above. You can change the script to be run on precommit with `npx pretty-quick --staged`

**Comment by viceice** [comment]
It's a visual studio issue, in the included git version the cygpath.exe is missing.

https://developercommunity.visualstudio.com/t/Missing-cygpathexe-in-git/1393876

**Comment by aminya** [comment]
It is actually a Husky problem. I had the issue with GitHub Desktop, not Visual Studio. Husky v1 works fine for example.

**Comment by viceice** [comment]
Nope, it's a problem of the used git distribution. cygpath seems also be missing in github desktop.

**Comment by lucksp** [comment]
committing on my terminal works fine.  Committing on GitHub Desktop results in Error:

> .husky/pre-commit: line 4: npx: command not found
husky - pre-commit hook exited with code 127 (error)

Followed the guide here: https://github.com/okonet/lint-staged#installation-and-setup

**Comment by aminya** [comment]
@viceice Microsoft has closed your issue meaning this is a Husky issue and it should be fixed independently of its environment.

https://developercommunity.visualstudio.com/t/Missing-cygpathexe-in-git/1393876#T-N1414158

> Hi Michael,

> We only use the version of Git that we ship with Visual Studio because we want to make sure that our Git features within Visual Studio function as designed. > Different versions of git.exe can break us in three different ways:

> If git.exe changes the command line parameters that its operations expected (unlikely), or
> If git.exe changes the output that it writes to stdout and/or stderr (surprisingly likely), or
> If git.exe changes the exit codes that its operations return (also, surprisingly likely).
> Because git.exe can break us so easily, we don’t support versions of git.exe other than the one that ships with the version of Visual Studio that you have installed.

> That being said, it’s your computer, and you can do what you want with it. You could try replacing the folder that contains the version of Git that we ship with Visual Studio with a version of Git for Windows that you download from https://gitforwindows.org/. I can’t state enough that this is NOT a supported scenario and some parts of Visual Studio’s Git integration may not work after you do this, but it might work for you. Something you should know, however, is that if you go this route, the next time your Visual Studio installation is updated, it will most likely replace the version of Git for Windows that you copy/install into the Visual Studio Git folder with the latest supported version of Git. This will most likely break your scenario again because the latest support version of Git that we ship won’t include cygpath.exe.

> I really wish I could give you better news than this, but unfortunately, I think this is your best option at this point. You’re welcome to go to Git for Windows GitHub issues page and request cygpath.exe be added back to the tools that ship with MinGit, though.

> Sorry and good luck.

**Comment by viceice** [comment]
@aminya i know 😕 for me it looks like a npm issue too, because the generated shell wrapper scripts are not checking the existence of cygpath.

**Comment by aminya** [comment]
Husky directly spawns `git` command without checking it the exe will work with Husky. I think the solution would be to first use [which](https://www.npmjs.com/package/which) package to see where the `git` exe is and use the one which is guaranteed to work.  

https://github.com/typicode/husky/blob/a66271d21fdf798b291d009c213ed48737dae227/packages/husky/src/index.ts#L11

**Comment by xavierfoucrier** [comment]
Hello everyone,

I had the same error in Github Desktop and **fix it by downgrading to a lower version of Git for Windows**:
now using `git version 2.30.1.windows.1` on Windows 7 Pro x64.

> Still have the issue on Atom `1.57.0`, but could probably fix it by reinstalling the software.

**Comment by mcaden** [comment]
I had this issue on an Angular project. It happened running `yarn lint` or just going straight to angular and using `ng lint`. However, `npm run lint` ran just fine.

I'm using **nvm-for-windows** using Nodejs **14.17.0** and npm **6.14.13**.

**Comment by aminya** [comment]
Those who still have this issue. I migrated to [`Lefthook`](https://github.com/evilmartians/lefthook/blob/master/docs/node.md), and I am pretty happy with it.

**Comment by JBoothUA** [comment]
https://stackoverflow.com/questions/61196309/husky-4-x-not-working-with-visual-studio-git

**Comment by pajuka** [comment]
Look here, this fixed these issue for me: https://github.com/yarnpkg/berry/issues/4095
