### ISSUE TITLE
Commands don't run in a predictable shell

### ISSUE THREAD

**Issue by ThomWright** [typicode/husky#674]
- Ubuntu 18.04
- Fish shell

We have our husky config in package.json like so:

```json
{
  "husky": {
    "hooks": {
      "pre-commit": "npm run a-thing && npm run another-thing",
    }
  }
}
```

This assumes that the command is run in `bash` (or `sh` I guess), which I think it used to pre-v4. At least, this worked in v3.

Now there are failures because it runs in whatever default shell a developer happens to use. For me that's fish, so I get:

`fish: Unsupported use of '&&'. In fish, please use 'COMMAND; and COMMAND'.`

If this runs in whatever shell a developer likes as their default, there are inevitable portability problems. Is there a reason this doesn't run in a predictable shell like (I think) it used to?

**Comment by ollar** [comment]
@ThomWright did you managed to find a solution?

**Comment by ThomWright** [comment]
Our only solution is to downgrade to husky v3 for now.

**Comment by Maistho** [comment]
It's also possible to change the script to `bash -c 'npm run a-thing && npm run another-thing'`, but it's a bit cumbersome.

**Comment by typicode** [comment]
It should be fixed in the last version
