### ISSUE TITLE
Why are my changes gone after a cancelled git commit and how do I recover them?

### ISSUE THREAD

**Issue by lolmaus** [typicode/husky#679]
Here's what I did:

 1. Coded 8 hours worth of changes.
 2. `git status` displays all my changes.
 3. `git add -A`
 4. `git commit -m "Foo"`. A pre-commit git hook fires with `husky` and `lint-staged`.
 5. I remember that there's a TypeScript typing error I failed to fix, so I press Ctrl+C to cancel.
 6. Absentmindedly, I run `git commit -m "Foo"` again and immediately cancel.
 7. Changes are gone! The files are reverted, `git status` is clean, `git log` and `git reflog` do not show a new commit.

WHAT. THE. HELL?!?!

Questions:

1. Why did my changes get reverted?
2. How do I recover them?

PS Using VS Code with the GitLens extension on Windows.

git version 2.25.1.windows.1
husky 4.2.3

[![step 1][1]][1] [![step 2][2]][2]

  [1]: https://i.stack.imgur.com/s5FKO.png
  [2]: https://i.stack.imgur.com/GbxCm.png

**Comment by lolmaus** [comment]
OK, it was `lint-staged` to blame. It stashed my changes.

So running `git stash apply` recovered them!

**Comment by iamqingmei** [comment]
OMG I got the exactly same question!!!!! Thanks you saved my life!!!!
