### ISSUE TITLE
Husky running tests instead of lint-staged

### ISSUE THREAD

**Issue by tonyjmartinez** [typicode/husky#684]
Please provide your OS, terminal and the following commands output:
macOS 10.15.3
iTerm2

I've run into a problem where husky runs tests instead of `lint-staged` in my repo. The problem goes away when I reinstall husky, but eventually it comes back. I've seen it happen in both the VS code terminal and iTerm2. I don't have a pre-commit script in `package.json`, and my `.huskyrc` and `.lintstagedrc` don't specify that tests should be run.

My `.huskyrc`.

```
{
  "hooks": {
    "pre-commit": "lint-staged"
  }
}
```

My `.lintstagedrc`.
```
{
  "*.js": [
    "eslint"
  ],
  "*.+(js|json)": [
    "prettier --write",
    "git add"
  ]
}
```

**Comment by typicode** [comment]
Hi,

Husky doesn't run test automatically. There's no such behavior in Husky. When it happens again, I would suggest checking `.git/hooks/pre-commit` to see if something has overwritten Husky's pre-commit hook (it should contain `husky` string)

**Comment by Spencer17x** [comment]
I encountered the same problem.

**Comment by shreyas-sriram** [comment]
Had the same issue.

Check if your `husky.sh` has the following

```
#!/bin/sh
# husky
# Created by Husky v4.3.0 (https://github.com/typicode/husky#readme)
#   At: 08/11/2020, 15:14:37
#   From: /Users/shreyas/Desktop/BookXchange/bookxchange-server/node_modules/husky (https://github.com/typicode/husky#readme)
. "$(dirname "$0")/husky.sh"
```

**Comment by creativogee** [comment]
Experiencing the same issue. This is what my pre-commit file looks like 
`#!/bin/bash
./node_modules/pre-commit/hook
RESULT=$?
[ $RESULT -ne 0 ] && exit 1
exit 0`

How do I resolve this?
