### ISSUE TITLE
husky package post install hook fails on windows

### ISSUE THREAD

**Issue by naingaungphyo** [typicode/husky#690]
I'm reopening [this old issue](https://github.com/typicode/husky/issues/565) because I got this identical error. 

```
opencollective-postinstall || exit 0
The token '||' is not a valid statement separator in this version.
+ CategoryInfo : ParserError: (:) [], ParentContainsErrorRecordException
+ FullyQualifiedErrorId : InvalidEndOfLine

```

As I mentioned in the old issue, the core-js postinstall script is also changed from 

> || operator

 to this [error catch code.](https://github.com/zloirock/core-js/blob/4546ffeca298cbccf0843e31e8af6403693ab8ae/packages/core-js-bundle/package.json#L55)

> "postinstall": "node -e \"try{require('./postinstall')}catch(e){}\""

you can reference [this](https://github.com/zloirock/core-js/issues/582) core-js issue to know why the above changes is needed.

**Comment by naingaungphyo** [comment]
The above error is due to wrong npm script-shell config setting.
To fix this error, change npm script-shell config like this.

> npm config set script-shell "C:\\WINDOWS\\System32\\cmd.exe"

**Comment by MiKr13** [comment]
@typicode Please remove opencollective based on Windows environment

**Comment by typicode** [comment]
`postinstall` has been removed, it should be good now.

**Comment by typicode** [comment]
Sorry for the issue on Windows.

**Comment by MehmetSunguralp** [comment]
> The above error is due to npm script-shell config setting being set as powershell.exe. The workaround is to change npm script-shell config to default setting null.
> 
> > npm config set script-shell null

Worked for me on windows
