### ISSUE TITLE
Remove ads or support OPEN_SOURCE_CONTRIBUTOR=true

### ISSUE THREAD

**Issue by mikemaccana** [typicode/husky#691]
```
Thank you for using husky!
If you rely on this package, please consider supporting our open collective:
> https://opencollective.com/husky/donate
```

[Ads are banned per npm policy](https://www.infoq.com/news/2019/08/npm-bans-package-ads/) so these shouldn't appear, but even if they do, the package should support `OPEN_SOURCE_CONTRIBUTOR` (which I am) to suppress this output.

About to file a bug on two other projects with ads in console output.

**Comment by typicode** [comment]
Hi @mikemaccana,

You can disable this message with `DISABLE_OPENCOLLECTIVE=true`. It should disable the Open Collective message for other projects using `opencollective-postinstall` package as well.

```sh
DISABLE_OPENCOLLECTIVE=true npm install husky -D
```

**Comment by mikemaccana** [comment]
Any chance you could support both? That way we wouldn't need to have a number of different environemnt variables which all mean the same thing. Thanks!

**Comment by mikemaccana** [comment]
I deleted my previous comment, the best place to fix this is in `opencollective-postinstall` so I'm doing that https://github.com/opencollective/opencollective-postinstall/issues/23
