### ISSUE TITLE
No evident error or warning when no compatible git version is available

### ISSUE THREAD

**Issue by eduard-malakhov** [typicode/husky#693]
Not sure if this needs to be addressed as an issue, but maybe it would be useful to document this behaviour explicitly (at least as an issue).

When husky is being installed on a host with git < 2.13.0 via `yarn` or `npm`, the installation succeeds and the user sees no warning indicating that hook haven't been installed. Although `checkGitVersion` fails and an error message is printed, the error is later suppressed in `installer/bin.ts` and hence, the package manager treats installation as successful. As both package managers hide output from package scripts by default, unless the user runs installation in verbose mode, he/she has no clue of the problem.

I've run into this in a Docker container `mcr.microsoft.com/vscode/devcontainers/typescript-node:0-12` which is currently the default [devcontainer](https://code.visualstudio.com/remote-tutorials/containers/how-it-works) for VS Code for TypeScript development. Since it is based on the current stable release of Debian (stretch) which includes git version 2.11.0, husky hooks won't be installed there correctly.

Once again, I am not sure if this behaviour needs to be changed, but I think at least initiating a discussion won't hurt. I would personally prefer to have the installation fail if no compatible git version is available, but I am not sure if that would be generally acceptable.

At the very least, we could add a notice in the docs saying that in case of incompatible version of git, installation does not fail. Here's what yarn output looks for example:

```sh
root@32f76451ac19:/workspace# git --version
git version 2.11.0
root@32f76451ac19:/workspace# yarn add -W husky
yarn add v1.22.4
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.1.2: The platform "linux" is incompatible with this module.
info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "workspace-aggregator-2f8f7064-46d7-43c3-a394-a524aa693953 > @uniqi/cli > ts-mocha@6.0.0" has incorrect peer dependency "mocha@^3.X.X || ^4.X.X || ^5.X.X || ^6.X.X".
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 15 new dependencies.
info Direct dependencies
└─ husky@4.2.3
info All dependencies
├─ @babel/runtime@7.9.2
├─ @types/parse-json@4.0.0
├─ compare-versions@3.6.0
├─ cosmiconfig@6.0.0
├─ find-versions@3.2.0
├─ husky@4.2.3
├─ lines-and-columns@1.1.6
├─ opencollective-postinstall@2.0.2
├─ pkg-dir@4.2.0
├─ please-upgrade-node@3.2.0
├─ regenerator-runtime@0.13.5
├─ semver-compare@1.0.0
├─ semver-regex@2.0.0
├─ which-pm-runs@1.0.0
└─ yaml@1.8.3
Done in 30.11s.
```

**Comment by typicode** [comment]
Hi @eduard-malakhov,

Thanks for the feedback. I agree that the error should be more visible.
I tried to change the behavior in 4.3.4 and it broke things for people (https://github.com/typicode/husky/issues/822) so rolled it back in 4.3.5.

While not ideal, I'll leave it as it is.

That's also one of the reasons that in husky 5 install is explicit. It makes it easier to see errors.
