### ISSUE TITLE
Bad error message if node_modules doesn't exist

### ISSUE THREAD

**Issue by fo-fo** [typicode/husky#694]
OS: macOS 10.15.3 (also happens on Linux)
Git: 2.26.0
Husky: 4.2.3
Yarn: 1.22.1

Husky hooks don't provide a good error message if `node_modules` doesn't exist. When the hook is executed, `yarn` run by `husky.sh` in `.git/hooks` prints `error Command "husky-run" not found.`

What should happen:
It should print the `Can't find Husky, skipping $hookName hook` message and skip the hook, without failing. Probably the reason for this issue is that yarn's run command returns `1` as its exit code in this situation, and not `127` that `husky.sh` checks against.

**Comment by typicode** [comment]
Thanks for the heads up, should be good in next patch :+1:
