### ISSUE TITLE
yaml config

### ISSUE THREAD

**Issue by JanNemcik** [typicode/husky#695]
Hello, I just want to ask if .huskyrc can be also in yaml format

**Comment by iliyanyotov** [comment]
Yes, the config can be in YAML format by looking at the loading script and trying it out myself by creating a **.huskyrc.yaml** file. Example usage bellow with a pre-commit hook.

```yaml
hooks:
  pre-commit: lint-staged
```

Will make sure to create a PR for adding this to the documentation.
