### ISSUE TITLE
Feature Request: Custom config path

### ISSUE THREAD

**Issue by mrAl-x** [typicode/husky#699]
Is there any way to override the default path for a `husky.config.js` file? It'd be great to be able to change it's default path, say, to a `/config` folder instead of the root directory for example

**Comment by tymonx** [comment]
I have the same issue. I want to have a global `~/.huskyrc.json` configuration file in my home directory. Currently only the `~/.huskyrc` file is used that simple source it and it is not usable for configuration.

**Comment by xeho91** [comment]
Hi!

Can we please get an official response to this feature request?

I also would love to have it, to keep our project root directory less polluted _(without having to use `package.json`)_.

**Comment by typicode** [comment]
Thanks for the suggestion, not opposed to the `config` folder as some tools like Rome seem to use it. Maybe later (sorry to not be able to give a date right now).

**Comment by waynevanson** [comment]
Thank you for your response, I'll be looking forward to the addition :)

**Comment by typicode** [comment]
This should do the trick :) https://typicode.github.io/husky/#/?id=custom-directory
