### ISSUE TITLE
Husky hooks not working tried both v4.2.5 and v3.0.8

### ISSUE THREAD

**Issue by PranjalAgni** [typicode/husky#712]
### Description
I am using Husky version (4.2.5) to lint my commit messages on `commit-msg` hook, but the hooks returns me this error: `.git/hooks/pre-commit: line 8: /husky.sh: No such file or directory`.

### Details 
I want to use `husky` with `commit-lint`, but unable to get it working. Below are description of few **unsuccessful** attempts:

1. Installed husky **v4.2.5** using yarn + npm:   
While doing a git commit it throws the error `.git/hooks/pre-commit: line 8: /husky.sh: No such file or directory`.

2. Installed husky **v3.0.8** using yarn + npm:
While doing a git commit the hooks are not running but all the hooks are created inside `.git/hooks`. I tried to run `pre-commit` and `commit-msg` but the hooks didn't execute and its like husky is not present in project.

### Installation
I installed husky using both **yarn** and **npm** as with yarn the installation process didn't showed me the post-install process of husky but all the hooks were present inside `.git/hooks` so I used npm and it shown me the post-install process and all the hooks were present same as above.

### Code
.huskyrc
```
{
  "hooks": {
    "pre-commit": "echo hello_world",
    "commit-msg": "commitlint -E HUSKY_GIT_PARAMS"
  }
}
```
[**Link to repo**](https://github.com/PranjalAgni/quiz-trivia-game) where I used husky

### Version
Husky v4.2.5
Windows 10 Pro
NodeJS v10.16.0
Npm v6.9.0
Yarn v1.17.3
Git v2.26.0

**Comment by iliyanyotov** [comment]
@PranjalAgni Just cloned your repository to give it a try and the hooks work fine on my machine (macOS 10.14.6), so your configuration is all correct.

Can you try to remove the `node_modules` directory and do a clean install of all the dependencies (including husky@4.2.5.) using yarn?

**Comment by PranjalAgni** [comment]
@iliyanyotov  I removed `node_modules` from root and did a clean install - it did not worked. 

Then I cloned back my repo at a different location ran `yarn install` to install all the deps but while commiting its throwing the errror. 

**Screenshot**
![image](https://user-images.githubusercontent.com/26196076/79133512-c7ab1d00-7dc9-11ea-9fcc-0b9f7a0a9406.png)

**Comment by PranjalAgni** [comment]
@typicode Can you please help. Is it some problem with Windows WSL?

**Comment by typicode** [comment]
Hi @PranjalAgni can you edit `.git/hooks/pre-commit`, add the following echo command and run again? Also can you verify that `.git/hooks/husky.sh` exists?

```sh
# ...
echo "$(dirname "$0")/husky.sh"
. "$(dirname "$0")/husky.sh"
```

**Comment by PranjalAgni** [comment]
Here it is: 

![image](https://user-images.githubusercontent.com/26196076/79721409-e6487100-82ff-11ea-94c9-d88d83b9e50b.png)

![image](https://user-images.githubusercontent.com/26196076/79721575-36273800-8300-11ea-99dd-2e175ab69d02.png)

**Comment by krasingneves** [comment]
FWIW, my teams are having similar issues with v4.2.5 + just npm, in a windows environment, regardless of client (command line, fork, sourcetree, gitkraken). 

We found that reverting to 3.1.0 has stopped having the `.git/hooks/pre-commit: line 8: /husky.sh: No such file or directory.` error.

**Comment by typicode** [comment]
Thanks for the screens! Seems like `dirname $0` is empty string in your case, not sure why.

**Comment by krasingneves** [comment]
@typicode - One thing I notice between the versions that work for me and the versions that don't is that the version that work uses `basename` instead of `dirname`.

When I locally change my hook from `dirname` to `basename`, it starts working again.

**Comment by brettz9** [comment]
Could this be related to #103 ? i.e., nvm issues

**Comment by Ronkiro** [comment]
> Could this be related to #103 ? i.e., nvm issues

It seems to not be related. I suffer the same issue with 4.2.5, but without nvm

**Comment by kerasing** [comment]
@brettz9  - We do not use nvm for windows (or operate in WSL).

**Comment by timtnleeProject** [comment]
Same issue with `4.3.0`
![image](https://user-images.githubusercontent.com/33143314/95316470-6f5f5e80-08c6-11eb-81a0-9fd20bdb31e8.png)

**Comment by zaneclaes** [comment]
Yarn workspaces may also be related. I have 3 projects in my workspace. The first 2 already used Husky. The third I just tried to add it to. I first did the `yarn install -D pretty-quick husky` from the child project, and then tried the `yarn install` from the workspace root. Neither worked. However, I was able to correct it by simply copying the relevant scripts from the git directory.

**Comment by chopfitzroy** [comment]
Seeing this with `npm` [version 7](https://blog.npmjs.org/post/631877012766785536/release-v700) as well.

**Comment by kimixu717** [comment]
same issue

**Comment by typicode** [comment]
Error message reminds me of https://github.com/typicode/husky/issues/732 

Could you try updating Git?

As for npm 7, older versions were missing an env variable needed by husky 4. It's fixed in most recent versions.
