### ISSUE TITLE
[Windows] Entering a terminal session in a git hook

### ISSUE THREAD

**Issue by GitGangGuy** [typicode/husky#713]
Husky has been working great for me until now, and I'm really grateful of what a team of open source developers can accomplish for essentially nothing; I hate to add on to the pile of other issues that are to be adressed, which is why I'm keeping it short.  
When attempting to enter an interactive terminal session on a *NIX-based system from a git hook, the general recommendation is to do a `exec < /dev/tty` before executing the command. For example, in combination with commitizen, this would look like so:
```
exec < /dev/tty && git cz --hook || true
```
The problem: On Windows, neither the `exec` command nor the `dev/tty` path exist.
In a small number of edge cases calling commitizen like so even works, but any output from a prompt like the ones created by Inquirer.js don't overwrite the previous prompt frame on key input, which might be caused by the non-Windows-compatible tty session call.
What is the  equivalent Windows (PowerShell) command for the above?
Ideally, how could I turn this into a `package.json` script I can call from my git hook?
Are there any cross-platform packages (like cross-env) that do this automatically (I wasn't able to find any)?

**Comment by typicode** [comment]
Appreciate the concerns :) Not aware of any package or equivalent for Windows.

I realize this doesn't answer your question. But personally, if you're not the only developer, I'd avoid entering an interactive terminal session during a Git hook. 

It will be broken for Git GUI clients (like VSCode or GitHub Desktop) as they don't provide a way to enter text during in an interactive terminal.

Instead, you can maybe have a npm script for commitizen and a hook with commitlint to ensure that the commit respects some format.

**Comment by GitGangGuy** [comment]
@typicode Alright, thanks for taking your time answering this! 💯  I guess I'll just do as you suggested.
