### ISSUE TITLE
npx husky-ugrade reports 404

### ISSUE THREAD

**Issue by danielo515** [typicode/husky#718]
I was very pleased to see that I can upgrade from my old husky to the newest automatically, however the command doesn't seem to exist on npm:

```sh
➜  npx --no-install husky-upgrade
not found: husky-upgrade
```
If I remove the flag:

```
➜  npx husky-upgrade 
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/husky-upgrade - Not found
npm ERR! 404 
npm ERR! 404  'husky-upgrade@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/danielo/.npm/_logs/2020-04-22T14_30_27_038Z-debug.log
Install for husky-upgrade@latest failed with code 1
```

**Comment by danielo515** [comment]
Ok, thanks to #353 I see that the proper command to use is

```
npx husky husky-upgrade
```

**Comment by danielo515** [comment]
Nope, I spoke too soon. That command does nothing

**Comment by typicode** [comment]
Hi @danielo515 

`husky-upgrade` is part of husky (https://github.com/typicode/husky/blob/master/package.json#L7). Recent version of husky needs to be installed first.

This should work:

```sh
npm i husky@latest -D
npx --no-install husky-upgrade
```

**Comment by danielo515** [comment]
Thanks for the answer.
Then upgrade the docs accordingly? In any case, I had husky installed, but previous version, so the `@latest` part is key.
