### ISSUE TITLE
Smart monorepo

### ISSUE THREAD

**Issue by nathanredblur** [typicode/husky#719]
this is a suggestion / feature:

I have a a repo with 4 micro-services each with his own package.json. I wanted to run some lints rules before do a commit in `/app` micro-services, but I have the problem that if some of my workmates works in other micro-service, the the hook was triggered when is not required.

so i did this small script and change my package.json configuration to run it.

```json
"husky": {
    "hooks": {
      "pre-push": "sh husky.sh"
    }
  },
```

```sh
#!/bin/bash

SRC_PATTERN="app/"

if git diff @{push} --cached --name-only | grep --quiet "$SRC_PATTERN"
then
  npm run lint && npm run type-check
else
  exit 0
fi
```

this will check if the changes to be pushed is part of the folder that this hook belong. 
that would be the ideal solution. 
1. If you have a monoRepo, the hook would check where the `husky` was installed or where you have packages.json with a valid `husky` configuration and save this locations for later use.
2. `husky` will then check which paths changes happen and trigger the task in each package.json where the files where modify.
e.g.
this is your repo structure
```
-app
  |- app.js
  |- package.json // pre-push: "npm lint"
- api
  |- api.js
  |- package.json  // pre-push: "npm test"
- utils
  |- index.js
  |- package.json  // no hook

```
- if you modify `api.js` only `npm test` is execute,
- if you modify any file inside `/app` then `npm lint` is execute
- if you change any file in `/utils`  nothing happen
- if you modify `app.js`, `api.js` and `utils/index.js`, then `npm lint` and `npm lint` is executed

thanks

**Comment by bnbarak** [comment]
First, cool `sh` script, but you can use https://github.com/okonet/lint-staged - and this is proven to work with monorepos. Example of package.json:

```json
"husky": {
    "hooks": {
      "pre-push": "lint-staged"
    }
  },
  "lint-staged": {
    "*.+(ts|tsx|js|jsx)": [
      "eslint --fix"
    ]
  }
```
