### ISSUE TITLE
Error on (re)install 

### ISSUE THREAD

**Issue by pixelass** [typicode/husky#72]
When running `npm install` the git hooks are set up.

After removing node_modules and running `npm install` I get the following error

``` shell
setting up hooks in .git/hooks
fs.js:922
  return binding.mkdir(pathModule._makeLong(path),
                 ^

Error: EEXIST: file already exists, mkdir '/<MY_PROJECT>/.git/hooks'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:922:18)
    at Object.create (/<MY_PROJECT>/node_modules/husky/src/index.js:123:33)
    at /<MY_PROJECT>/node_modules/husky/bin/install.js:22:13
    at Array.forEach (native)
    at /<MY_PROJECT>/node_modules/husky/bin/install.js:20:11
    at /<MY_PROJECT>/node_modules/husky/src/index.js:17:9
    at ChildProcess.exithandler (child_process.js:197:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)

# ... install tree

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "i"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! husky@0.11.9 install: `node ./bin/install.js`
npm ERR! Exit status 1
```

**Comment by typicode** [comment]
Hi @pixelass,

Thank you for the report. Hmm, I don't really know why it doesn't work the second time. Also, I'm not able to reproduce the issue:

```sh
test$ git init
test$ npm init
test$ npm install husky -D # OK
test$ rm -rf node_modules
test$ npm install husky -D # OK
```

Am I missing something? Also there's a test to prevent that here:
https://github.com/typicode/husky/blob/master/src/index.js#L123

PS: I'm using Node stable instead of `iojs`, don't know if it's related

**Comment by pixelass** [comment]
thx for the fast reply.
I'll test it in a MVP. This is a big project so maybe we're doing something else wrong.

**Comment by iamstarkov** [comment]
@typicode i think you couldnt reproduce it because you didnt specify any git hooks in npm scripts

**Comment by iamstarkov** [comment]
and @pixelass is also using `nodejs`, not `iojs`

**Comment by iamstarkov** [comment]
@typicode that said you are right and tests are covering this case

**Comment by pixelass** [comment]
In my case hooks is not a folder but a symlink.

`hooks -> ../node_modules/git-scripts/bin/hooks`

It seems that a previously installed module "git-scripts" added the symlink so your test does not recognise it as a directory.

Not sure if you want to add this to the test.

Cheers.

**Comment by iamstarkov** [comment]
i think the problem here is that your project is using two different packages to orchestrate git hooks at the same time

**Comment by pixelass** [comment]
it was the previous package. it has been exchanged by husky. 
We don't use multiple packages. the symlink was dirt from the old pkg. your check does not detect symlinks

**Comment by pixelass** [comment]
as mentioned the issue is resolved after deleting the symlink.
