### ISSUE TITLE
pre-push not pushing with exit code 0

### ISSUE THREAD

**Issue by kennethbigler** [typicode/husky#723]
I am exiting with code 0 in my `pre-push` hook, but the push never happens.
Any idea why my hooks ends successfully but the push does not happen?

here is my `husky.config.js`:
```js
module.exports = {
  hooks: {
    'post-checkout': 'post-checkout',
    'pre-commit': 'lint-staged',
    'commit-msg': 'commit-msg && commitlint -E HUSKY_GIT_PARAMS',
    'pre-push':
      'yarn && yarn lint && yarn build && yarn test && echo $? && exit 0'
  }
};
```

> [troubleshoot](https://github.com/typicode/husky#troubleshoot) ✅
> Git: `git version 2.24.2 (Apple Git-127)`
> OS: `macOS Catalina 10.15.3`
> Terminal: `VSCode 1.44.2`

Command:
```sh
HUSKY_DEBUG=1 yarn add husky --save-dev -W
```
Output: 
```sh
[4/4] 🔨  Building fresh packages...
success Saved 1 new dependency.
info Direct dependencies
└─ husky@4.2.5
info All dependencies
└─ husky@4.2.5
$ patch-package
patch-package 6.2.0
Applying patches...
No patch files found
✨  Done in 27.15s.
```

Command:
```sh
HUSKY_DEBUG=1 git push
```
Output:
```sh
...
Test Suites: 8 passed, 8 total
Tests:       113 passed, 113 total
Snapshots:   7 passed, 7 total
Time:        16.087s
Ran all test suites in 8 projects.
0
husky:debug yarn run --silent husky-run exited with 0 exit code
```

**Comment by XiaoPa** [comment]
hi @kennethbigler, how did you solve the problem ?

**Comment by kennethbigler** [comment]
@XiaoPa I did end up resolving the problem.
At some point during the execution, husky lost internet connectivity (I had choppy wifi at the time), and so it did not push (even if it had re-gained internet connectivity).
The solution was to just bypass husky. I ran the pre-push code locally then did a `git push --no-verify` to bypass husky from doing its check.
