### ISSUE TITLE
Pre-commit/pre-push hooks hang

### ISSUE THREAD

**Issue by struct78** [typicode/husky#724]
I recently upgraded from Husky v3.1.0 to v4.2.5, and my pre-push hook now hangs. I am using macOS 10.14.6 & terminal in VS Code.

I have narrowed it down to this line in `.git/husky.sh`:

```
case $hookName in
  "pre-push"|"post-rewrite")
    export HUSKY_GIT_STDIN="$(cat)"; # <--- cat is hanging
esac
```

Executing the cat command in the terminal by itself also hangs, I am not sure if this is expected behaviour or not?

**Comment by hanayashiki** [comment]
removing that line works for me )

**Comment by hanayashiki** [comment]
any idea on how to patch this?

**Comment by hanayashiki** [comment]
I resolved this by removing this package from my project!

**Comment by typicode** [comment]
Hmm not sure why it hangs, sorry. That said, husky 5 shouldn't have this issue since this environment variable/line of code has been removed.
