### ISSUE TITLE
Additional command if hook fails

### ISSUE THREAD

**Issue by vitorboccio** [typicode/husky#725]
Hello, I am trying to run an additional command ONLY if one of my hooks fail.

So I am not sure how to implement this and actually don't know if it's supported currently.

```
"hooks": {
      "commit-msg": "commitlint -E HUSKY_GIT_PARAMS",
      "pre-commit": "lint-staged",
}
```

For example this "commit-msg" hook is using commitLint to check messages format and IF it fails I wanna run a second command (npx whatever-package-here). 
Note: This second command shouldn't run the next hook ('pre-commit') as it is a cli to help the user to format his commit message. 
Is it currently supported ? if so, how to implement such thing ? 

I tried things like `"commitlint -E HUSKY_GIT_PARAMS &> /dev/null || npx package-here"` but didnt work.

Thanks.

**Comment by typicode** [comment]
Hmm, not sure why it didn't work. Would have tried the same code.
Closing as I'm cleaning old issues.
