### ISSUE TITLE
Local docker support?

### ISSUE THREAD

**Issue by ellioseven** [typicode/husky#730]
I'm using a local docker environment to run git hooks with husky. I've set up a hook to run on pre-push. The hook triggers, however I get:

```
husky:debug husky v4.2.5 - pre-push
husky:debug Current working directory is /home/elliot/Development/prosple/frontend
Can't find yarn in PATH: /usr/lib/git-core:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
Skipping pre-push hook
```

My husky file looks like so:

```
const tasks = arr => arr.join(" && ")
const run = "docker-compose run --rm platform "

module.exports = {
  "hooks": {
    "pre-push": tasks([
      run + "yarn test"
    ])
  }
}
```

I'd like to have husky run in my local docker environment. It seems to defeat the purpose of using a docker environment by requiring these hooks to run on the host. Is there some way to get this working WITHOUT performing git operations inside the docker container itself?

**Comment by zimmicz** [comment]
@ellioseven could you share your dockerfile/docker-compose.yml? I can't get past `husky-run` not installed error.

**Comment by ellioseven** [comment]
@zimmicz 

```
FROM node:lts-alpine
RUN apk add --no-cache bash git
```

**Comment by ellioseven** [comment]
**Solved.** I didn't have an up to date git installation in the image.
