### ISSUE TITLE
Segmentation fault error after fresh husky installation

### ISSUE THREAD

**Issue by Drecu** [typicode/husky#731]
Hi,

i just installed husky and wanted to use it with lint-staged.
Unfortunately the pre commit hook just crashes with a really weird error seen below:
![image](https://user-images.githubusercontent.com/60739293/83745005-39cb1000-a65d-11ea-9967-c708820f7e01.png)
In the .git/hooks/pre-commit looks everything fine with husky. 

Any idea what's causing this problem?

kind regards Michel

**Comment by Drecu** [comment]
im currently doing a fresh install in a demo project, as suggested to check if husky even runs and it fails already there im opening a different issue and closing this one.

**Comment by bennycode** [comment]
I am also getting this error with husky v4.3.8 on a MacBook Air with Silicon CPU and Node v16.

**Comment by ydmitry** [comment]
Same for me, node 16, apple m1

**Comment by sureshHARDIYA** [comment]
I am facing same issue, node 16, windows. I am not sure how to fix this. Any lead?

**Comment by lisandrascruz** [comment]
Did anyone get this solution?

**Comment by ramyzhang** [comment]
Same issue here! Node 18.12.1, Apple M2!
I've tried reinstalling husky a couple times to no avail.
Here is the behaviour:
```
MY_NAME@MY_MACHINE MY_REPO % git push
Fixing any lint errors...
.husky/pre-push: line 5: 86374 Segmentation fault: 11  yarn run lint:fix
husky - pre-push hook exited with code 139 (error)
error: failed to push some refs to 'https://github.com/MY_REPO'
```
I don't think it's a problem with the lint command as it runs fine by itself.

**Comment by juancho1123** [comment]
@ramyzhang Friend, I have the same problem with m2, do you have a solution for this problem?

**Comment by ramyzhang** [comment]
> @ramyzhang Friend, I have the same problem with m2, do you have a solution for this problem?

I was never able to get it to work for the project I was working on, but it seems there's some solutions you could try in this thread: https://github.com/typicode/husky/issues/1246
