### ISSUE TITLE
husky.sh no such file or directory, when I use git v2.27.0

### ISSUE THREAD

**Issue by bluehymn** [typicode/husky#732]
when I use Git v2.27.0 cause this error but is well in Git v2.26.2 

<img width="556" alt="企业微信截图_15912625312537" src="https://user-images.githubusercontent.com/15361704/83845181-f0e98900-a73a-11ea-9a32-cc594e6d2067.png">

**Comment by typicode** [comment]
Thanks for the report. Not sure what's causing this :thinking: or what could be done on husky's side to fix that. Sorry :/
FWIW husky 5 is tested on Windows against Git 2.29.2 and it seems to work.
