### ISSUE TITLE
Husky commit-msg no longer working when using Sourcetree

### ISSUE THREAD

**Issue by cutterbl** [typicode/husky#734]
I realize this one might be a little odd, but...

We have multiple husky hooks setup. We use Sourcetree, from Atlassian, as a GUI interface to git. This has worked fine for us in the past, and suddenly does not. Not sure why, but none of our hooks are firing, when doing commits _in Sourcetree_. I have verified that everything still works fine if I'm working strictly in terminal.

Husky 4.2.5
Git 2.20.1 (Apple Git-117)
Node 10.18.0 (nvm default, for some time now)
NPM 6.13.4 (nvm default, for some time now)
Sourcetree 4.0.1 (234)
git-branch-is 3.1.0

We have a simple setup
```js
"husky": {
    "hooks": {
      "pre-push": "if git-branch-is master; then npm lint; fi",
      "commit-msg": "if git-branch-is master; then commitlint -E HUSKY_GIT_PARAMS; fi"
    }
  },
```
Neither hooks, when driving with Sourcetree. Both work fine, when driving directly in the Terminal.

**Comment by tenadolanter** [comment]
> Switching to husky 3.1.0 (which uses run-node) also worked for me
https://github.com/typicode/husky/issues/639

**Comment by andorfermichael** [comment]
#820 worked for me
