### ISSUE TITLE
Print commit message in output

### ISSUE THREAD

**Issue by magistr4815** [typicode/husky#738]
Hey. I use Husky, lint-stage and Vs Code.
I write the commit message in the visual interface of Vs Code, and not in the terminal (bash), and therefore my commit message may be lost.

More details:
1) I made changes to the repository.
2) I wrote a commit message and pressed enter.
![msg](https://user-images.githubusercontent.com/8629826/85410555-4c5ba980-b578-11ea-9c72-f90683405205.png)
3) Husky starts to process files and stops because it finds errors.
4) I get error output in the output panel in Vs Code.

Can I somehow **display in the panel my commit message** that did not pass the test?
![msg1](https://user-images.githubusercontent.com/8629826/85410981-d3108680-b578-11ea-8f65-a781cbfdd1e9.png)

I feel lazy if I constantly re-enter the message (sometimes it has to be done several times due to carelessness)

**Comment by typicode** [comment]
Hi,

Not sure that it's possible. You could access it in `commit-msg` hook but it happens after `pre-commit` hook, so it wouldn't work in your case.
