### ISSUE TITLE
Support run on change

### ISSUE THREAD

**Issue by stephenh** [typicode/husky#741]
It'd be cool if husky natively supported "run on change" functionality, i.e.

https://gist.github.com/sindresorhus/7996717

With a syntax like:

```json
  "husky": {
    "hooks": {
      "post-checkout": {
        "package-lock.json": "npm i",
        "**/*.graphql": "npm run graphql-codegen",
        "Dockerfile,docker-compose.yml": "docker-compose build",
       }
    }
  },
```

(This can be done today with a `runOnChange.sh` script that husky invokes, but it'd be great to have somewhat-non-trivial-to-do-in-bash things like the `**/*.graphql` blob be executed on the JS/node/husky side of things.)

**Comment by typicode** [comment]
Hi @stephenh,

Thanks for the feedback and sharing this script :) I can see the benefit.
That said I prefer to keep husky small and unopiniated.

**Comment by stephenh** [comment]
@typicode cool, np!

If anyone else comes across this issue, I've got a fork that implements this: 

https://github.com/typicode/husky/compare/next...stephenh:run-on-change

It's not super-polished (we have it setup to do auto-run `npm i` on package-lock change and I think technically it runs more often than it needs to) but we're using it on our main repository and it's generally working well.
