### ISSUE TITLE
.git/hooks/husky.sh Permission denied

### ISSUE THREAD

**Issue by lzuliuyun** [typicode/husky#742]
when I execute 'git pull' command, I get error:
```.git/hooks/husky.sh: line 47: /usr/bin/basename: Permission denied```

execute 'git commit' command, I get similar error:
```
.git/hooks/husky.sh: line 47: /usr/bin/basename: Permission denied .git/hooks/husky.sh: line 37: /usr/bin/grep: Permission denied
.git/hooks/husky.sh: line 58: /usr/bin/dirname: Permission denied .git/hooks/husky.sh: line 58: /husky.local.sh: No such file or directory
```

os:  Microsoft Windows [版本 10.0.18362.900]
git: git version 2.26.2.windows.1

it's ok about four days ago, it's not work recently。

**Comment by castarco** [comment]
@lzuliuyun you can try removing the file in `.git/hooks/husky.sh`, and repeating the command `npm install` (without admin permissions).
