### ISSUE TITLE
commit-msg hook is skipped on Windows 10 if husky is installed by Yarn

### ISSUE THREAD

**Issue by SachinShekhar** [typicode/husky#749]
There's no problem if husky is installed by `npm`. But, if it's installed by Yarn, the `commit-msg` hook is skipped. Here's the relevant error when husky's debug mode is ON:

```bash
/usr/bin/bash: X:projectnamenode_modules.binhusky-run: command not found
husky:debug yarn run --silent husky-run exited with 127 exit code
Can't find Husky, skipping commit-msg hook
You can reinstall it using 'npm install husky --save-dev' or delete this hook
```

It seems the problem is with path. `X:projectnamenode_modules.binhusky-run` should be `X:\projectname\node_modules\.bin\husky-run`.

Please, fix it.

**Comment by SachinShekhar** [comment]
I found the cause of the issue. This line is causing issue: https://github.com/typicode/husky/blob/master/sh/husky.sh#L88

```bash
run_command () {
  if command_exists "$1"; then
    "$@" husky-run $hookName "$gitParams"

    exitCode="$?"
    debug "$* husky-run exited with $exitCode exit code"

    if [ $exitCode -eq 127 ]; then
      echo "Can't find Husky, skipping $hookName hook"
      echo "You can reinstall it using 'npm install husky --save-dev' or delete this hook"
    else
      exit $exitCode
    fi

  else
    echo "Can't find $1 in PATH: $PATH"
    echo "Skipping $hookName hook"
    exit 0
  fi
}

# Run husky-run with the package manager used to install Husky
case $packageManager in
  "npm") run_command npx --no-install;;
  "npminstall") run_command npx --no-install;;
  "pnpm") run_command pnpx --no-install;;
  "yarn") run_command yarn run --silent;;
  *) echo "Unknown package manager: $packageManager"; exit 0;;
esac
```

The culprit is: `"yarn") run_command yarn run --silent;;`. The script tries to run `husky-run` using `yarn run` and I tested that `yarn run` fails to execute locally installed CLIs on Windows.

I've also verified that this Husky issue goes away if I edit `.git/hooks/husky.sh` file to replace ` "yarn") run_command yarn run --silent;;` with ` "yarn") run_command npx --no-install;;`

**Comment by SachinShekhar** [comment]
I am closing this issue because this isn't an issue of husky's code. I've already notified Yarn team about it: https://github.com/yarnpkg/yarn/issues/8340

Until they fix this, you can use do this if you are facing the same issue:

1.  Create `fix-husky.js` file in project's root with following content:

```javascript
const fs = require('fs');

// If Operating System is Windows, fix Husky for Yarn
if (process.platform === 'win32') {
  const huskyScript = fs.readFileSync('.git/hooks/husky.sh', {
    encoding: 'utf-8',
  });
  const fixedHuskyScript = huskyScript.replace(
    'run_command yarn run --silent;;',
    'run_command npx --no-install;;'
  );
  fs.writeFileSync('.git/hooks/husky.sh', fixedHuskyScript);
}
```
2. Run it once after installing husky with `node fix-husky.js` (you can even save it as `package.json` script).

**Comment by alexturpin** [comment]
Out of curiosity, is there an appetite for a PR that always uses `npx` on Windows in husky.sh? I don't think that Yarn fix is coming anytime soon...

**Comment by SachinShekhar** [comment]
Possibly. That'd fix large number of broken husky repo.
