### ISSUE TITLE
Why are dashes stripped from the hook names?

### ISSUE THREAD

**Issue by radfahrer** [typicode/husky#75]
as seen here https://github.com/typicode/husky/blob/master/bin/install.js#L21, when the hooks are installed, dashes get stripped out of the hook names. Why is this being done?

**Comment by typicode** [comment]
Hi @radfahrer,

For consistency with npm script hooks https://docs.npmjs.com/misc/scripts and to avoid having this in `package.json`:

```
{
  "scripts": {
    "prepublish": "npm test",
    "pre-commit": "npm test"
  }
}
```

It's hard to say what's the best approach, but the idea was that for Node devs it would be less surprising to have this convention.
