### ISSUE TITLE
Monorepo using black code formatter git hook (for python) clashing with husky git hook

### ISSUE THREAD

**Issue by alexolivas** [typicode/husky#750]
I'm not quite sure there is a proper solution to this, but the project I am working on is a monorepo consisting of mostly python modules and a lone react project which serves as the web interface for the entire thing. It has the following directory structure:
```
/top
    .git // contains all the hooks including husky and black
    /some-python-module
    /another-python-module
    /react-js-app
        package.json // contains husky config
```
For the longest time, I had the husky pre-commit and pre-push hooks working just fine on that react module. However, we recently introduced black code formatter to format all our python code to follow PEP8 convention in a pre-commit hook. Since the installation of black on our monorepo it has taken over my husky hooks which are now completely ignored.

I am not sure if there is something I can configure in husky, pre-commit, or black to get these to work together. I am opening up this issue in the black open source project as well, just to see if I can get any insight by the either community to see if anyone has encountered a similar issue and what has been done to solve it?

**Comment by ammarnajjar** [comment]
hello @alexolivas, I would give [pre-commit](https://github.com/pre-commit/pre-commit) a try, kudos to @asottile!

**Comment by typicode** [comment]
Hi @alexolivas,

Unfortunately, I don't think there's anything that can be done. Or at least not in a simple way. I would pick either one of them to manage git hooks.

**Comment by asottile** [comment]
fwiw I just answered [a stackoverflow question about this](https://stackoverflow.com/a/64002300/812183)

**Comment by typicode** [comment]
@asottile thanks for the update, the migration feature looks very cool

**Comment by alexolivas** [comment]
@asottile thanks for that
