### ISSUE TITLE
Stuck at pre-commit or post-checkoust

### ISSUE THREAD

**Issue by MatthD** [typicode/husky#752]
Since today our team and I got stucked many times of `git commit` or `git checkout` (for pre-commit & post-checkout)

- OS : macOS Catalina 10.15.5
- Git version 2.25.0
- Node: 12.16.1 or 14.8.0
- Husky: 4.2.3

![Capture d’écran 2020-08-26 à 18 09 26](https://user-images.githubusercontent.com/7901366/91329003-ef72ae80-e7c7-11ea-9fbc-bc726179ad6e.png)

![image](https://user-images.githubusercontent.com/7901366/91329394-660fac00-e7c8-11ea-9463-f4f857e7a877.png)

**Comment by typicode** [comment]
Hmm, besides a command waiting for stdin or in watch mode, I don't know what could be the reason. But I suppose that since then, you've found a solution/workaround.

Feel free to create a new issue if needed.
