### ISSUE TITLE
Feature: Disable hooks on merge commits

### ISSUE THREAD

**Issue by kylemh** [typicode/husky#753]
I'm leveraging `commitizen` with `husky` and it works like a dream... Except when dealing with merge commits.

I'm prompted to go through `cz-cli` for those, when I never really want to. 

I found these two potential workarounds, but neither seem to work:

https://stackoverflow.com/questions/56379208/ignoring-merge-commits-for-prepare-commit-msg-git-hook
https://stackoverflow.com/questions/61234845/how-to-bypass-pre-commit-hooks-after-fixing-merge-conflicts

I would love the solution to be an aspect of husky

**Comment by typicode** [comment]
Hi,

You can disable husky with environment variables: `$ HUSKY_SKIP_HOOKS=1 git ...` (v4) or `$ HUSKY=0 git ...` (v5)
