### ISSUE TITLE
Direnv integration

### ISSUE THREAD

**Issue by cdfa** [typicode/husky#755]
Hi, would you consider adding [direnv](direnv.net) integration to Husky? I depend on it to add my package manager to my `PATH` when I'm in the project directory (using Nix), so my hooks fail when I'm using Git from somewhere else than the project directory (like a git GUI).

Integration could also be implemented on the GUI side, but implementing in husky would make it work for any GUI.

Please provide your OS, terminal and the following commands output:
OS: 5.4.60-2-MANJARO GNU/Linux
Terminal: not relevant (GUI is Gitkraken)
Command output: not relevant either, but Husky version is `4.2.5`

**Comment by jasonk** [comment]
You can get husky to load your direnv configs by adding `eval "$(direnv export bash)"` to your `~/.huskyrc` file

**Comment by cdfa** [comment]
Ah thanks! Missed that section in the README. Apologies :sweat_smile:
