### ISSUE TITLE
Suggestion: Documentation Site

### ISSUE THREAD

**Issue by tderflinger** [typicode/husky#756]
Hi there,

I think there is a need for a separate documentation site for Husky. In that I could help out and design and write a simple documentation website using Docusaurus (https://docusaurus.io/).

Do you also think there is a need for that? If yes, what content should I include?

-Tommy

**Comment by typicode** [comment]
Hi @tderflinger ,

Thanks for the suggestion, I've been thinking about it too and went with docute for husky v5.
