### ISSUE TITLE
Is there a way to get remote  ref, local ref etc. in husky 'pre-push' hook script ?

### ISSUE THREAD

**Issue by koiralakiran1** [typicode/husky#757]
Hi,
I'm trying to make branches protected (sort of) locally on a repository which doesn't allow protected branches on the remote.

It was easily achievable to fail a `pre-commit` hook if someone is trying to commit on protected branches that I've listed. Just checking the current branch against the protected branches list would work.

However, in `pre-push` similar check wouldn't completely work. Someone can push to a protected remote branch while being in an unprotected branch.
This is what I mean. if `master` is a protected branch, then
```sh
(branch: abc) $ git push origin abc:master # push abc branch to master which will be successful
```
So, is there a way that I can check what is the exact branch that is being pushed to? Something like [this](https://github.com/git/git/blob/87c86dd14abe8db7d00b0df5661ef8cf147a72a3/templates/hooks--pre-push.sample) that is possible on git's custom `pre-push` script?

I've already tried passing `$HUSKY_GIT_STDIN` but couldn't get this to work.

Husky version: `4.3.0`
Git version: `2.28.0`

My husky config:
![image](https://user-images.githubusercontent.com/11130898/92426971-f7a8f180-f1aa-11ea-92f3-f6cee90023ff.png)

On my `pre-push` script, I'm doing something like this, but the loop never gets executed. Am I missing something or doing something wrong?
![image](https://user-images.githubusercontent.com/11130898/92426781-7f423080-f1aa-11ea-92ea-1f28cf334613.png)

I've already looked into:
https://stackoverflow.com/questions/24223811/getting-last-executed-command-from-script
https://github.com/talenavi/husky-precommit-prepush-githooks
https://stackoverflow.com/questions/4196148/git-pre-push-hooks
https://stackoverflow.com/questions/42455506/in-pre-push-hook-get-git-push-command-full-content

Thanks

**Comment by SiddarthaAdusumalli** [comment]
I ran into the same problem today. After reading [this answer](https://askubuntu.com/a/604631/1151980), I ended up changing the `while read ...` line as below and it did the job for me:

```sh
echo "$HUSKY_GIT_STDIN" | while read local_ref local_sha remote_ref remote_sha
```

Please note that I'm no bash expert. A better solution solution might be possible.

**Comment by typicode** [comment]
Closing as `$HUSKY_GIT_STDIN` has been removed. It may be easier to do also with v5.
