### ISSUE TITLE
[Monorepo][enhancement] Single husky installation for multiple sub projects

### ISSUE THREAD

**Issue by blelump** [typicode/husky#758]
Hi! First of all, thanks for this tool.

Now to the problem:  I am aware of https://github.com/typicode/husky#monorepos and the suggestions stated there, but I'd like to avoid using additional tool to solve this particular problem. I've digged a bit into it and it seems Husky installs `husky.sh` and `husky.local.sh` into the `.git/hooks` dir. So adding:

```
echo `pwd`
set | egrep GIT
```
to `husky.local.sh` prints:
```
/absolute/path/to/repo/root
GIT_EDITOR='...'
GIT_PREFIX='relative_to_.git_root_path'
```

Is there any caveat of using `"${pwd}/${GIT_PREFIX}"` to execute the `cd` command within `husky.local.sh` comparing to the current `cd "hardcoded/relative/path`?

In particular:
```
# husky.local.sh
packageManager=yarn
SUBPROJECT_DIR="`pwd`/${GIT_PREFIX}"
cd $SUBPROJECT_DIR
```

**Comment by typicode** [comment]
Hi, 

Interesting, thanks for sharing :) Will need to find some time for testing.

**Comment by bnbarak** [comment]
There is a discussion about the issue here https://github.com/typicode/husky/issues/677. And I have a PR ready to merge here https://github.com/typicode/husky/pull/728.

But, I like your idea of being able to explicitly set the project root.
