### ISSUE TITLE
Husky doesn't always respond to sigint

### ISSUE THREAD

**Issue by CluEleSsUK** [typicode/husky#763]
Not 100% sure how to consistently replicate this or if it's even _strictly_ with Husky, but thought I'd drop it here in case anyone had insight!

Sometimes when a precommit hook runs, hitting ^C is ignored completely, e.g.
```
$ git commit 
husky > pre-commit (node v14.3.0)
^C
✔ Preparing...
✔ Preparing...
✔ Preparing...
✔ Preparing...
✔ Preparing...
✔ Preparing...
✔ Preparing...
✔ Preparing...
✔ Preparing...
✔ Preparing...
✔ Preparing...
✔ Preparing...
✔ Preparing...
✔ Preparing...
✔ Preparing...
✔ Preparing...
✔ Preparing...
✔ Preparing...
✔ Preparing...
✔ Running tasks...
✔ Applying modifications...
✔ Cleaning up... 
^C
```
While only two `^C` characters are shown above, there is in fact a `✔ Preparing...` for each ^C press.

It also doesn't happen every time - perhaps a timing issue with when the sigint is received?

**Comment by typicode** [comment]
Hmm :thinking: not sure why it didn't respond or if something can be changed in husky's code to fix that. That said, there are good chances that husky 5 doesn't have this issue since it's working differently that v4.
