### ISSUE TITLE
[feature request] Ability to ignore a specific hook

### ISSUE THREAD

**Issue by caleb15** [typicode/husky#764]
It would be nice if a user could configure husky to skip a specific hook. For example, VSCode can automatically blackify files on save so there is no need to run the black hook. However, I still might want to run other hooks.

**Comment by typicode** [comment]
Thanks for the suggestion :)
Not sure how it could be implemented and actually I prefer to keep husky not too opinionated about that.

With the CLI you can however use `HUSKY=0` to disable all hooks, or `git commit --no-verify` to disable commit hooks, etc... With VSCode, I don't know.

**Comment by caleb15** [comment]
I don't understand how it would make husky more opinionated - isn't opionated when you just have one certain style of thinking? This would allow more flexibility.

**Comment by typicode** [comment]
Opinionated may not have been the best word. Actually, it's more that I don't see how it could be done or what the workflow would look like.
