### ISSUE TITLE
Trouble executing bash script from hook

### ISSUE THREAD

**Issue by qapla47** [typicode/husky#765]
Hi,
Having a bit of difficulty executing a bash script from the pre-commit hook. I can see that the file is being run, but it always exits from the else clause when running with Husky. If I run the file manually, it does the validation correctly every time. I have attempted to incorporate lint-staged and prepush-if-changed, but there are issues with lint-staged and PyCharm. 

OS: Ubuntu 18.04 | Node: 10.16.3 | Git: 2.17.1 | Husky: 4.2.5 | IDE: VSCode and PyCharm

.huskyrc
```json
{
  "hooks": {
    "pre-commit": "bash skip-validation.sh"
  }
}
```
skip-validation.sh
```bash
#!/bin/bash

CHECK_LOCATION='<project_root>/apps/ui'
if git diff --name-only | grep -q $CHECK_LOCATION; then
  # next line is a placeholder
  echo 'found match'  
  yarn run validate:src
  exit 0
else
  echo 'no match'
  exit 0
fi
```
If I make a change in the location I'm watching for, and run the hook with debug on I get the following. It does finally commit, but without running the validation script (local is an alias for add and commit).
```
~$ HUSKY_DEBUG=1 git local "check"
husky:debug husky v4.2.5 - pre-commit
husky:debug Current working directory is <project_root>
husky:debug GIT_DIR environment variable is set to .git
husky:debug If you're getting "fatal: not a git repository" errors, check GIT_DIR value
husky > pre-commit (node v10.16.3)
no match
husky:debug yarn run --silent husky-run exited with 0 exit code
husky:debug husky v4.2.5 - prepare-commit-msg
husky:debug Current working directory is <project_root>
husky:debug prepare-commit-msg config not found, skipping hook
husky:debug husky v4.2.5 - commit-msg
husky:debug Current working directory is <project_root>
husky:debug commit-msg config not found, skipping hook
[branch_name] check
1 file changed, 1 insertion(+)
```
If I run the command run in the middle of that debug, it runs the bash file correctly, but doesn't actually execute the commit.
```
~$ yarn run --silent husky-run pre-commit
husky > pre-commit (node v 10.16.3)
found match 
$ yarn run npm-run-all test:related validate:files dev
[ ... additional script output... ]
```
ideas?

**Comment by qapla47** [comment]
Here is a minimal [repo](https://github.com/qapla47/testRepo.git), not fully functional, but representative of my project structure. 
If you run the skipValidation script manually, you'll see that changes made in the webui directory are caught. However, if you commit and allow Husky to run the validation script, you'll see it fails to detect the changes.

**Comment by typicode** [comment]
> ideas?
:thinking: I would try logging `git diff --name-only`, `git diff --name-only | grep $CHECK_LOCATION`, etc... but to be honest, I don't really know why it's working differently or where it's failing.

Maybe you've found a solution since then, if so can this issue be closed?

**Comment by qapla47** [comment]
I did, today, find a method to make this work, and for posterity, I'll post what we did in case others run into similar situations:
In the hook, reference a yarn script
```
{
  "hooks": {
    "pre-commit": "yarn run need:validation"
  }
}
```
The script calls the bash file
```
"need:validation": "bash ./skip-validation.sh",
"validate": "does lots of things"
```
In the bash file use:
```
#!/bin/bash
CHECK_LOCATION="path/to/your/code"
if [[ $(git status --porcelain | grep $CHECK_LOCATION) ]]; then
  yarn run validate
  git add .
  exit 0
else
  exit 0
fi
```
We have, in the intervening time, upgraded our node and node_modules, and this solution only worked with v4.3.8, it did not work with v5 due to an error in finding git-lfs.
