### ISSUE TITLE
Executing Script No Responding with v4.3.0

### ISSUE THREAD

**Issue by libterty** [typicode/husky#766]
# Description

I'm using Husky version (4.3.0) to check my commit and push. But the hooks did not trigger husky without any error message pop up.

# Details
I used husky for my commit and push check, but couldn't get it work. Below are description of few unsuccessful and successful attempts:

1. Installed husky v4.3.0 with npm: While doing commit and push there's no error pop up but it didn't trigger husky somehow

2. Installed husky v4.2.5 with npm: When I downgrade to v4.2.5 with same set up it can works.

# code
```json=
"husky": {
    "hooks": {
      "pre-commit": "sh scripts/precommit.sh",
      "pre-push": "sh scripts/prepublish.sh"
    }
  }
```

[Repo Link and Downgrade commit Link](https://github.com/libterty/lib_quorum/commit/710aaa27f733012af5e1151b5f2c4080f056adda)

Version: 
Husky 4.3.0
Node 10.15.0

**Comment by typicode** [comment]
Thanks for the repo link and report, not sure what may be causing this. Sorry :/

**Comment by libterty** [comment]
@typicode 

I found out the reason why it fails. It's not because of the version 4.3.0. It's I forget to run `git init ` when i copy my old code to  the new branch. Husky install requires git to be initialized first.

![Screen Shot 2021-01-08 at 12 08 01 AM (2)](https://user-images.githubusercontent.com/38395851/103915595-5f198280-5146-11eb-8aa7-97a3fd263445.png)

**Comment by typicode** [comment]
I see, thanks for the update :slightly_smiling_face: I guess it can be closed now.
