### ISSUE TITLE
need to run npm rebuild everytime for precommit

### ISSUE THREAD

**Issue by tonystaark** [typicode/husky#767]
```
 "husky": {
    "hooks": {
      "pre-commit": "lint-staged"
    }
  }

 "lint-staged": {
    "*!(node_modules|build)/**/*.{js,ts,tsx,json}": [
      "prettier --write",
      "eslint --fix"
    ],
    "*!(node_modules|build)/**/*.{css,scss}": [
      "prettier --write"
    ]
  }
```
Hi recently I have an issue where I run git commit, it will throw error saying 
```
$ git commit -m "updated somefiles"
husky > pre-commit (node v12.18.0)
i No staged files match any configured task.
[master 5b8734c] updated somefiles
 1 file changed, 15 insertions(+), 3 deletions(-)

```
The fact is I made changes to the file specified in lint-staged above. After going through crazy search, I tried `npm rebuild` and it works. 
What is the issue behind this? My node version on local never changes, using v12.18.0 as always.

**Comment by typicode** [comment]
Hmm, I don't know what may cause this :/
