### ISSUE TITLE
the pre-commit and pre-push hooks are not executed when I make a new commit

### ISSUE THREAD

**Issue by slim-hmidi** [typicode/husky#768]
I installed husky v4.3.0 and prettier v2.1.2 and I add this scripts to package.json:
```
 "lint-fix": "eslint ./src/**/*.ts{,x} --fix",
  "format": "prettier --write ./src/**/*.ts{,x}",
"husky": {
    "hooks": {
      "pre-commit": "npm run lint-fix",
      "pre-push": "npm run format"
    }
  }
```
Whenever I do a new commit neither the pre-commit nor the pre-push executed. I reinstalled husky many times and I delete node_modules and reinstall husky but does not work.
**Node:** 12.18.4
**Git:** 2.28.0.windows.1
**OS:** windows 10

**Comment by typicode** [comment]
Looks good to me. I would try maybe updating npm to latest.
Closing as I'm cleaning old issues. Feel free to re-open if you still have the problem.
