### ISSUE TITLE
[Feature Request] API for installing husky when it's a transitive dependency

### ISSUE THREAD

**Issue by jedwards1211** [typicode/husky#769]
Note: I'm on 4.3.0.

Since I maintain a lot of packages I'm working on putting all of my build deps, including husky, and configs into a single dev dependency `@jedwards1211/js-toolchain`.  I'd like to make my `postinstall` script install the husky hooks.  I can sort of accomplish this with `node node_modules/husky/husky.js install`, but this is a brittle approach since I can't rely on husky winding up in `<project root>/node_modules/husky` (it may end up in `<project root>/node_modules/@jedwards1211/js-toolchain/node_modules/husky`).

There's not currently a better way to do this, is there?  Right now the best I've managed is to make my postinstall script do `yarn add --dev husky@${version}` but that's not as clean.

**Comment by typicode** [comment]
Hi @jedwards1211,

Husky 6 exposes now its API :) (I'll document it later)

**Comment by jedwards1211** [comment]
Cool, thanks!  My work has stalled on my dev deps package since I've been so busy 😅 but I'm looking forward to it!
