### ISSUE TITLE
Pre-commit gets pushed even if no file is changed

### ISSUE THREAD

**Issue by nautatva** [typicode/husky#772]
This is just a simple reproducible example. A lot of variation in this also has the same bug.
I have an basic HTML file as an existing commit. The Pre-commit hook attached just uses prettier to format the file. [Steps for setting up pre-commit](https://prettier.io/docs/en/precommit.html#option-2-pretty-quickhttpsgithubcomazzpretty-quick)
```
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>

</body>

</html>
```

Now I just remove the extra lines, which prettier will fix as run by pre-commit hook.
The problem is as soon as the file is prettified, the file will be the same as previous commit. When seen in `git logs`, we see a git with "zero file changes".

Ideally, this shouldn't have been committed. One way I saw this is achieved in [pre-commit](https://github.com/pre-commit/pre-commit) is not pushing directly if files are changed by hooks.

**Comment by typicode** [comment]
This would be a bit out of scope for husky. But I think https://github.com/okonet/lint-staged will abort commit if linter reverts all changes.
