### ISSUE TITLE
Which version to install

### ISSUE THREAD

**Issue by z31fbras** [typicode/husky#773]
Hi,

I already use husky on one project and this tool is great!
I wanted to install husky on another project.

I found when installing that the version I was installing was a beta version.
This repo leads by default to version 5.

Is it intended?
I'd love to install v5 but I would like to know if it's safe enough before installing it on my company's project.

I'm afraid that installing v4 right now might be a bad idea.
Is there a approximate date for the stable release of v5?

Thanks for your advice!

**Comment by typicode** [comment]
Hi @z31fbras

Personally if I had to start a new project, I would use v5. I'm also using it on this repo to run hooks.

That said, v5 is free for Open Source and in early access for Sponsors. So unless your company is developing an Open Source project, you or your company may need to become a sponsor to use it (everything's explained in the docs :) ).

v4 will be receive maintenance updates meanwhile.

> Is there a approximate date for the stable release of v5?
No date for the moment.

Feel free if you have any other questions.

**Comment by z31fbras** [comment]
Hi @typicode,

Thanks for your reply!

I'm not developing an open source project for my company.
I'll use v4 for the moment and maybe migrate to v5 one day.

However, on my personal projects, I'll be happy to discover the new features of v5 👍
Thanks for the hard work on this repo,

Have a nice day 👋
