### ISSUE TITLE
Output customization

### ISSUE THREAD

**Issue by ImanMh** [typicode/husky#777]
Hi there, Thanks for the nice tools you folks provide for the community of opensource.

Are there any ways I can customize my output during the commit process? It's OK for most of the commits but when you are doing merges that have conflicts there are a lot of files that have to be processed and when their number is high it gets out of the screen so most of the terminal tools (Mac terminal, Webstorm terminal, iTerm and ...) keep scrolling the page and husky prints a huge output which makes a very bad experience. My suggestion is that if we could see a progress bar or even a simple "pending... (12/345)" message that would make a very good difference in Husky UX.

**Comment by typicode** [comment]
Hi @ImanMh,

Thanks :) 

Regarding output customization, that's a good idea but out of scope for husky. That said, you can temporarily disable hooks with `HUSKY=0 git ...` (v5) or `HUSKY_SKIP_HOOKS=1 git ...` (v4).

**Comment by ImanMh** [comment]
Thank, does `HUSKY=0 git ...` disables output or completely bypasses the process?

**Comment by typicode** [comment]
It bypasses the process.

**Comment by ImanMh** [comment]
@typicode can you help me with where can I can find files related to output methods? I would like to work on a proposal for output customization or fix the issue for my self at least. I would appreciate if you can help me out.
