### ISSUE TITLE
Hard-coded yarn install command breaks on commit

### ISSUE THREAD

**Issue by hannahwood** [typicode/husky#778]
I am unable to upgrade to v4 because this version introduced these hardcoded package manager commands install here:
https://github.com/typicode/husky/blob/master/sh/husky.sh#L88
```# Run husky-run with the package manager used to install Husky
case $packageManager in
  "npm") run_command npx --no-install;;
  "npminstall") run_command npx --no-install;;
  "pnpm") run_command pnpx --no-install;;
  "yarn") run_command yarn run --silent;;
  *) echo "Unknown package manager: $packageManager"; exit 0;;
esac
```

The reason this is a problem is that I use `yarnpkg` instead of `yarn` as I have `hadoop-yarn` installed as `yarn`.
So when I try to commit, I get the error `Error: Could not find or load main class run`

If there is any way of getting around hardcoding these, that would be great for me and my team!

**Comment by typicode** [comment]
Hi @hannahwood,

Hmm with v4, I don't see a way, except in `~/.huskyrc`.
That said v5 is more flexible and doesn't have package managers hard-coded.
