### ISSUE TITLE
Husky 5.x HUSKY_GIT_PARAMS

### ISSUE THREAD

**Issue by Oreku2608** [typicode/husky#779]
I am setting up a monorepo project with husky 5.x using commitlint.js, however I can't get it to work properly. I have tried to save the hook in the following ways

npx husky add commit-msg "npx --no-install commitlint --env $ {HUSKY_GIT_PARAMS}"
npx husky add commit-msg "npx --no-install commitlint --env $ HUSKY_GIT_PARAMS"

When performing a git commit -m "blah blah blah"

I can't retrieve the HUSKY_GIT_PARAMS :( 

In the new documentation HUSKY_GIT_PARAMS is removed. Instead Git parameters should be used directly in scripts (eg). $ 1 However, I can't find the way to pass the argument to commitlint

**Comment by typicode** [comment]
Hi @Oreku2608,

Can you try:

```sh
npx --no-install commitlint --edit $1
```

You can find a working example [here](https://github.com/typicode/husky/blob/07f3fedd7ac2872aa8203ac32c9ed539a792ec30/.husky/commit-msg)

**Comment by Oreku2608** [comment]
@typicode Many thanks. Works !!! 😄

**Comment by nicgordon** [comment]
This is great, could this example be made more public?

**Comment by typicode** [comment]
> This is great, could this example be made more public?

Yes, good idea, I've added a migration section to the docs :)
