### ISSUE TITLE
Doesn't work when installed with --no-bin-links flag

### ISSUE THREAD

**Issue by emmajam** [typicode/husky#781]
We are facing an issue when yarn install is invoked with `--no-bin-links` to enable with gradle caching.

Any ideas on a work around for this? Can we update the symlink tin the .git/hooks/pre-commit file?

**Comment by typicode** [comment]
Closing as it may have been solved since then.

**Comment by emmajam** [comment]
Are you sure?

**Comment by emmajam** [comment]
I'll check out the latest version and test today

**Comment by typicode** [comment]
My bad, my response wasn't clear. Closed it as it's an old issue and a solution may have been found on your side.

That said, besides calling directly `node node_modules/husky/lib/bin.js install`, personally I don't know what else could be done. It's a bit of an edge case.
