### ISSUE TITLE
Not working with yarn on Catalina 10.15.7

### ISSUE THREAD

**Issue by webcoderkz** [typicode/husky#782]
yarn: '1.22.4',
node: '14.3.0',
husky: '5.0.0-beta.0'

added to package.json:

```
  "husky": {
    "hooks": {
      "pre-commit": "echo \"\\x1b[104m\\x1b[97m\n[ Cleaning build directories ]\n\\x1b[0m\"",
    }
  },
```

It doesn't fire. I've checked ".git/hooks" it had default hooks, i deleted them. Then i ran:

`node node_modules/husky/lib/bin.js install`, i got the message about successful hook installation, but ".git/hooks" was empty. The only way i got this working is by using it in cli:

`node node_modules/husky/lib/bin.js add pre-commit "npm test"` - it creates a file under ".husky/pre-commit" and now, when i use `git commit` it does fire as intended. What's wrong?

**Comment by typicode** [comment]
Hi @webcoderkz,

The way to configure Husky has changed in v5, please see the new install instructions.
https://typicode.github.io/husky/#/?id=install
