### ISSUE TITLE
Support Backwards Compatability for git < v2.13.2?

### ISSUE THREAD

**Issue by rrrix** [typicode/husky#783]
### Background
So, long story short, I was pulling my hair out trying to figure out why Husky in my monorepo wasn't invoking hooks on ANYONE else's machine on my team (8 people!) while it works for me. Everything was setup perfectly.

Turns out, husky requires **git >= v2.13.2**, and that's hidden in a little comment within the _old_ CHANGELOG.md.

Upon digging into the code, it appears this change is related to how husky uses `git rev-parse --show-toplevel --absolute-git-dir` to find the project `.git` directory so it can install hooks in the correct place.

The change can be found here: https://github.com/typicode/husky/compare/v2.6.0...v3.0.0-0 

### The Reality

Having an unsupported git version is essentially the same as using `git commit --no-verify`! 

This is quite unfortunate, as I was really expecting everything to "just work" without having to force everyone on my team to check and upgrade their git versions. 

### Can Husky support git versions older than v2.13.2?

* Why was this change made to switch from `--git-common-dir` to `--absolute-git-dir`? 
* If git older than `v2.13.2` is found, can the "old" behavior be used with the relative dir (instead of just silently failing)? 
* What is the downside of using `--git-dir` if `--absolute-git-dir` is not supported? 

----

I'm happy to submit a PR for this work, if this idea is supported.

If not, I will probably unfortunately have to fork the project.

**Comment by typicode** [comment]
Hi @rrrix,

Husky `v5` supports Git down to `2.9` so I don't think it'll be changed in `v4`.
I don't remember exactly why it was changed though, maybe some issues in edge cases.
