### ISSUE TITLE
Selectively enable/disable optional hooks?

### ISSUE THREAD

**Issue by JulianLaval** [typicode/husky#784]
I wasn't able to find this in the v4 or v5 documentation - apologies if I've missed it.

Does Husky support selectively enabling / disabling hooks?

As an example, I'd love to specify a `pre-push` hook that is automatically installed on `postinstall`, but also specify a `pre-commit` hook that isn't automatically installed but can be enabled on a case by case basis (e.g. via `husky enable pre-commit`).

What would be the best way to achieve this? Thanks in advance!

**Comment by typicode** [comment]
Hi,

It's not possible via a command, but you could have disabled hooks with some prefix/suffix and rename them to enable them.
For example, `.husky/pre-commit.disabled` or `.husky/pre-commit.sample` for v5 and `_pre-commit` field in v4.

**Comment by JulianLaval** [comment]
Got it, thanks!

We've settled on the following approach using Husky v5:
- Add `pre-push` hook to package.json
- `husky install` on `postinstall` to ensure the hook is set up for everyone
- Specify in Code Guidelines that additional user hooks can be set up via `husky install hook-name "cmd"`
- Add `.husky/` to `.gitignore` so that these user hooks aren't committed

**Comment by typicode** [comment]
Thanks for sharing :+1:
