### ISSUE TITLE
How i can rest the hook directory after switching branches

### ISSUE THREAD

**Issue by ingoziemann** [typicode/husky#785]
I have 2 local future branches. On one I have added a husky pre-commit hook. On the other one, there should be no hook.  If I switch to the branch that should have no hook, I can't commit anymore, because the hook stuff will be not reset. Is there a way to reset the hook stuff?

**Comment by kirkoman** [comment]
Did you get this working?  It is definitely possible to run different hooks on different branches.  There is no "reset" needed beyond just configuring the hooks on the branch.

More detail about how you are setting up the hook could be helpful.  As a point of reference, I just ran through the following and it worked as expected:
```
C:\dev\foo>git init . && npm init -y && npm i -D husky
C:\dev\foo>REM -- Now edit package.json to add "husky": { "hooks": { "pre-commit": "echo ~~hello~~" } }
C:\dev\foo>git add package.json && git commit -m "say hello on commit"
husky > pre-commit (node v12.13.1)
~~hello~~
[master (root-commit) 150e3bf] say hello on commit
 1 file changed, 16 insertions(+)
 create mode 100644 package.json
C:\dev\foo>git checkout -b feat_nohello
Switched to a new branch 'feat_nohello'
C:\dev\foo>REM -- Remove the hook from package.json ("husky": { "hooks": { } })
C:\dev\foo>git commit -m "feature: quieter commits" package.json
[feat_nohello 85bc3b3] feature: quieter commits
 1 file changed, 1 insertion(+), 1 deletion(-)
C:\dev\foo>
```
