### ISSUE TITLE
npm install trigger husky@4.0.3 uninstall，node_modules empty!! why????

### ISSUE THREAD

**Issue by airwaycai** [typicode/husky#786]
$ npm install 

> husky@2.0.0 uninstall /Users/bjhl/mywork/flight/node_modules/husky
> node bin/uninstall.js

husky
uninstalling Git hooks
done

npm WARN @umijs/plugin-layout@0.12.4 requires a peer of @ant-design/pro-layout@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN babel-plugin-dva-hmr@0.4.2 requires a peer of redbox-react@1.x but none is installed. You must install peer dependencies yourself.
npm WARN dva-immer@0.5.0 requires a peer of dva@^2.5.0-0 but none is installed. You must install peer dependencies yourself.
npm WARN dva-loading@3.0.21 requires a peer of dva-core@^1.1.0 | ^1.5.0-0 | ^1.6.0-0 but none is installed. You must install peer dependencies yourself.
npm WARN jsdom@15.2.1 requires a peer of canvas@^2.5.0 but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.3.1 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.3.1 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.

removed 2816 packages and audited 3021 packages in 37.09s
found 11 vulnerabilities (9 low, 2 high)
  run `npm audit fix` to fix them, or `npm audit` for details

**Comment by typicode** [comment]
Don't know what happened, but I don't think it's related. You can check `uninstall.js`, it only removes Git hooks.
I would simply re-run `npm install` to ensure that everything is back in `node_modules`.

**Comment by paradox010** [comment]
i have same problems, and i guess that we used same framework.

**Comment by paradox010** [comment]
maybe u can change node version . i used v10.14.0。(this error occurred when i use v12.18.3)
