### ISSUE TITLE
Husky 4.3.0 does not work with worktree folders

### ISSUE THREAD

**Issue by KnisterPeter** [typicode/husky#787]
When running `git commit` in a repo with husky enabled it fails with this:

```sh
error Command "husky-run" not found.
```

**Comment by typicode** [comment]
Thanks for the report :+1: (and sorry for the late reply).
Worktree support in v4 is a bit tricky. That said, husky v5 works quite differently so it may not have this issue.

**Comment by jpribyl** [comment]
I seem to be getting the same error for husky 5.1.3 - are you aware of some workaround?
