### ISSUE TITLE
Unstage files on hook error

### ISSUE THREAD

**Issue by Thomazella** [typicode/husky#789]
I find myself doing
- stage files, commit, have error, fix, commit, see same error

that happens because the correct way is
- stage files, commit, have error, fix, stage changes, commit

Just wondering if husky _could_ reset the index on error. That would allow me to reuse the first user flow after a hook error

**Comment by typicode** [comment]
Husky isn't opinionated, it just runs hooks with the provided commands, nothing more.  Maybe a script could do that.
