### ISSUE TITLE
Install issue on non-git environments

### ISSUE THREAD

**Issue by alisabzevari** [typicode/husky#79]
Husky couldn't detect our Jenkins CD environment because the `BUILD_NUMBER` env variable was not present and failed to install. Why not just checking if the `.git` directory exists?

**Comment by typicode** [comment]
Good point, I'll update husky.

**Comment by alisabzevari** [comment]
@typicode Cool, I can make a PR.

**Comment by typicode** [comment]
Thank you for the offer. Already added the feature in the `next` branch ;) and published it using `beta` tag, to give it a try:

```
npm install husky@beta --save-dev
```

I'll publish `v0.12.0` stable soon.
