### ISSUE TITLE
[Bug] Reinstall hooks command

### ISSUE THREAD

**Issue by xenoterracide** [typicode/husky#790]
Sometimes husky hooks break, and reinstall doesn't work (seems true of yarn2  (with PnP?)), I ran this, and it worked

```
yarn husky-upgrade
```

but it would seem like a better idea to add a command to just reinstall the hooks

```
yarn husky-install-hooks
```

**Comment by typicode** [comment]
Not sure, but I think `yarn rebuild` will trigger husky's postinstall. That said v5 has `husky install` which does what you suggest :+1:
