### ISSUE TITLE
postcheckout hook never exits during interactive rebase

### ISSUE THREAD

**Issue by christianacca** [typicode/husky#80]
I've been struggling to resolve a problem with a `postcheckout` hook that is running during an git interactive rebase.

The symptoms of the problem are very obvious:

* `git rebase somesha -i`
* select that you want to reword one of the commit messages
* confirm your answers (in my case I'm rewording one of the commit messages)
* ... wait, wait, wait... give up waiting for the text editor to appear to prompt me to edit the commit message

This happens even for the simplest of `postcheckout` hooks. 

For testing purposes I wrote the following hook which fails as described above:

*package.json*:
```json
  "postcheckout": "node scripts/clean.js"
```

*scripts/clean.js*:
```js
  process.exitCode = 0;
```

My setup is as follows:

* Windows 10
* node 6.2.2
* husky@0.11.9

Any pointers as to what I need to do to get the postcheckout hook to exit so that the interactive rebase can continue?

Thanks
Christian

**Comment by pgosset** [comment]
Any news?

**Comment by tony** [comment]
Also having this issue making `git rebase -i` pretty slow.

**Comment by typicode** [comment]
Closing as husky 5 may not have this issue.
