### ISSUE TITLE
husky@5 license on npm is incorrect

### ISSUE THREAD

**Issue by anthony-telljohann** [typicode/husky#807]
According to the `LICENSE` file, `husky >= 5` is now `License Zero Parity 7.0.0 and MIT with exception License Zero Patron 1.0.0` however on the [husky npm registry](https://www.npmjs.com/package/husky/v/5.0.0) the license is MIT.

I would recommend updating your licenses to match otherwise consumers may not be aware of the changes.

**Comment by typicode** [comment]
Thanks for catching that :+1: not sure why it was considered MIT, I've updated package.json. I hope it'll fix the issue for the next release.

**Comment by typicode** [comment]
I've updated the license, but it doesn't seem to have any effect.

**Comment by anthony-telljohann** [comment]
That is very odd. I thought the package.json was the source of truth for the registry. Appreciate you updating it regardless.

**Comment by typicode** [comment]
No worries, I've sent a mail to npm support too :+1:
