### ISSUE TITLE
Husky on Node 15

### ISSUE THREAD

**Issue by Dacker15** [typicode/husky#809]
I'm using Husky with Node `v15.1.0` and it's not working.
I use the exact configuration in a project with Node 12 and it works.

Does Husky work on Node 15?

OS: `Windows 10`
Husky version: `4.3.0`

**Comment by typicode** [comment]
What's your version of npm?

**Comment by Dacker15** [comment]
Providing more information:

OS: `Windows 10`
NodeJS: `15.1.0`
npm: `7.0.8`
Git:  `2.29.2 for Windows`

**Comment by typicode** [comment]
Thanks for the details, It may be related to https://github.com/typicode/husky/issues/776
Npm 6 should work with Husky v4.
Alternatively, Husky v5 is known to work with npm 7 but is currently free for Open Source and in early access for Sponsors.

Closing as there's already another issue to track this.
