### ISSUE TITLE
how to setting up?

### ISSUE THREAD

**Issue by jt3k** [typicode/husky#81]
By using readme.md i install husky `npm install husky --save-dev`
then i add precommit and prepush hooks to npm.
![](https://i.imgur.com/yHDsM2R.png)

Now I try to do commits
![](https://i.imgur.com/RAlgbg9.png)
but hooks not works.

what am I doing wrong?

**Comment by typicode** [comment]
Hi @jt3k,

Normally running `npm install husky --save-dev` should automatically trigger installation script for you (`node_modules/husky/bin/install.js`).

So, just by setting `precommit` in `package.json` you should be good.

That said, one reason that could explain why hooks weren't installed is if `ignore-scripts` is set to `true`. To verify could you run:

```sh
npm config get ignore-scripts # should be false
```

**Comment by jt3k** [comment]
![2016-12-09 10 23 56](https://cloud.githubusercontent.com/assets/1261240/21041056/b4b1b6ac-bdf9-11e6-9ecb-f5c123bfdea5.png)

it seems the problem is installing via add yarn husky --dev

thanx for help!

**Comment by buildAll** [comment]
if you have your own precommit in .git/hooks before npm install husky, than precommit scripts could not be triggered. so just delete your own precommit first.

**Comment by dpikt** [comment]
For some reason the install script didn't trigger for me, so I just ran it manually and it solved the issue:
`node node_modules/husky/bin/install.js`

**Comment by GuillaumeHumbert** [comment]
The same thing happened to me, I installed husky _via_ Yarn and the install script did not trigger. I spent way too much time narrowing down the problem and finding this topic.

Maybe consider changing the title to a more representative one, and reopening to fix the installation with Yarn? Or is it more on Yarn's side that a fix must be made?

**Comment by lcoder** [comment]
It takes me so much time.This help me . wowowoo

**Comment by philwolstenholme** [comment]
I had this issue because a fork of Husky had been installed from one of my dependencies (Yorkie, from vue-cli), and had written to my `.git/hooks` directory, so Husky hadn't been able to set itself up.

**Comment by kartiklad** [comment]
For people who venture here in the future looking for a quick fix:

yarn add -D husky was the problem for me. Removing node modules and installing everything again fixed it for me.

**Comment by Gpia** [comment]
I have this problem too.  husky does not run.
so, i installed it manuly, but still failed. because i had own .git/hooks.
![image](https://user-images.githubusercontent.com/13506519/39870250-3ced2c8c-5493-11e8-9bea-727fc513949b.png)

**Comment by divyanshu013** [comment]
Still happens in yarn 1.7, need to run the install script manually

**Comment by typicode** [comment]
@philwolstenholme husky `v1.0.0-rc.8` should fix that, it'll overwrite hooks generated by the fork.

You can always run `rm -rf .git/hooks && mkdir .git/hooks`, if you don't have personal hooks in it.

@divyanshu013 is it with husky `v1.0.0-rc.8`?

**Comment by divyanshu013** [comment]
@typicode this is with 0.14.3, didn't realize there was a RC available

**Comment by seanWLawrence** [comment]
> You can always run `rm -rf .git/hooks && mkdir .git/hooks`, if you don't have personal hooks in it.

This worked for me, thank you so much!

**Comment by webuniverseio** [comment]
For version 1.3.1 I had to use `node node_modules/husky/husky.js install`.
