### ISSUE TITLE
ENOENT: no such file or directory, open '/home/karl/dev/basickarl/energy-estimator/.husky/pre-commit'

### ISSUE THREAD

**Issue by basickarl** [typicode/husky#810]
Pieces of my `package.json`:

```
    "private": true,
    ...
    "scripts": {
        "postinstall": "npx husky install",
        ...
        "husky": "5.0.1",
```

I run then `npm install` then I run:
```
npx husky install
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
        modified:   package-lock.json
        modified:   package.json

no changes added to commit
```

`npx husky add pre-commit "npm test"` and I get:

`ENOENT: no such file or directory, open '/home/karl/dev/basickarl/energy-estimator/.husky/pre-commit'`

**Comment by typicode** [comment]
Was `.husky` directory created when you've run `npx husky install`?

**Comment by basickarl** [comment]
@typicode Oddly enough no it wasn't :/ I'm running Ubuntu 16.04, bash and Node v14 if that helps at all.

**Comment by typicode** [comment]
I think I know what happened. You need to run `npx --no-install husky install` so that it runs the version installed locally and not load `@latest` version on npmjs.com (which is v4).

I would suggest changing `postinstall` to `husky install`, `npx husky install` is unnecessary here.
