### ISSUE TITLE
Husky from node inside a docker container

### ISSUE THREAD

**Issue by devsnek** [typicode/husky#813]
For a project, we have a bunch of build tools inside a docker container (including node itself) and all that is needed is docker. for example if you wanted to invoke node directly, you would do `./scripts/dev-env/run.sh node`

![](https://gc.gy/87492826-0fbc-40c9-a512-616781113ef0.png)

To this end, I need to figure out a way to tell husky to prefix the `npx` command with `./scripts/dev-env/run.sh`. Any help is appreciated.

**Comment by typicode** [comment]
Would a shell alias or function named `npx` do the job?
In Husky v5, `npx` isn't hard coded so it may be more flexible.

**Comment by devsnek** [comment]
@typicode where would i put said shell alias? i was reading the docs for v4 and v5 and all i could find was `~/.huskyrc`, but that's not specific to the project.

**Comment by devsnek** [comment]
I see now that husky v5 doesn't invoke node to run hooks, so I guess that solves my problem. Thanks.
