### ISSUE TITLE
[Feature] enable Sourcetree & nvm for mac

### ISSUE THREAD

**Issue by sleepq123** [typicode/husky#815]
### when i use husky by sourceTree, it didn't working.
then, i have see  error in commit historys, as below:
> **because of which node path didn't find!**

![image](https://user-images.githubusercontent.com/31381291/100198018-32aefb80-2f36-11eb-9469-727a2ae6097b.png)

> **then i changed `.git/hooks/pre-commit`, it look likes good,as below:**

![image](https://user-images.githubusercontent.com/31381291/100198647-0f388080-2f37-11eb-98de-1cbd1eafbbdf.png)

### hopping
maybe we can change when writing `pre-commit` such file, add current node path

**Comment by sleepq123** [comment]
it seems like this
![image](https://user-images.githubusercontent.com/31381291/100201589-32652f00-2f3b-11eb-8bc7-24065f04fa9b.png)

**Comment by sleepq123** [comment]
**something like yorkie i find!**
[yorkie github](https://github.com/yyx990803/yorkie)

**Comment by typicode** [comment]
Good idea. That was the behavior in Husky 0.14. It worked but Node path was hard-coded. If Node was updated, you could have the Git GUI client still use the older version. Or if the version was removed, Node wouldn't be found in the GUI Client, and husky would need to be reinstalled to update.

Personally, I'd recommend adding `. ~/.nvm/nvm.sh` to `~/.huskyrc`
https://typicode.github.io/husky/#/?id=command-not-found

This way, your GUI Client would use the version defined by nvm, even if it's updated.
