### ISSUE TITLE
v5: hooks not working for custom directory setup

### ISSUE THREAD

**Issue by vertic4l** [typicode/husky#816]
Following the instructions for v5:

> Another case you may be in is if your package.json file and .git directory are not at the same level. For example, project/.git > and project/front/.package.json.

So i added:
> "postinstall": "cd .. && husky install ./src"

then run:

> npx husky add pre-commit "npm run eslint; npm run stylelint-fix; npm run ts-check"

and when trying to commit:

> npm ERR! code ENOENT
> npm ERR! syscall open
> npm ERR! path /Sites/frontend-portal/package.json
> npm ERR! errno -2
> npm ERR! enoent ENOENT: no such file or directory, open '/Sites/frontend-portal/package.json'
> npm ERR! enoent This is related to npm not being able to find a file.
> npm ERR! enoent 
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /.npm/_logs/2020-11-27T10_08_45_180Z-debug.log
> husky - pre-commit hook exited with code 254 (error)

path should be `/Sites/frontend-portal/src/package.json` then

**Comment by typicode** [comment]
Thanks for the heads up. I've updated docs (https://typicode.github.io/husky/#/?id=custom-directory), you'd need to change directory before running commands (`cd src`).

**Comment by bharti2022** [comment]
> 

where we have to specify the path I am not able to implement as .git and package.json are present in diff directories. can you help

**Comment by uKiJo** [comment]
> > 
> 
> where we have to specify the path I am not able to implement as .git and package.json are present in diff directories. can you help

you have to specify it inside the pre-commit hook `cd front
npm test`
