### ISSUE TITLE
v4 to v5 installation disparity 

### ISSUE THREAD

**Issue by jcohenho** [typicode/husky#817]
When upgrading to v5, are we no longer allowed to just add the package and use the previous configuration in package.json? :

```
{
  "husky": {
    "hooks": {
      "pre-commit": "npm test",
      "pre-push": "npm test",
      "...": "..."
    }
  }
}
```

Is running  `yarn husky install` and adding hooks via `husky add <hookname>` a new requirement?

**Comment by typicode** [comment]
Hi,

Yes, you need to follow the new install instructions. There's a section about caveats when migrating from v4 to v5 https://typicode.github.io/husky/#/?id=migrate-from-v4-to-v5

**Comment by typicode** [comment]
that said, if you still want to configure hooks from `package.json`, you could do `husky add pre-commit "npm run pre-commit"` and define a `pre-commit` script in `package.json > scripts`
