### ISSUE TITLE
Call pre-push hook conditionally

### ISSUE THREAD

**Issue by ym-project** [typicode/husky#818]
Hi!
Could you help me? I expect next behavior:
* `git push remote branch` or `git push` - call hook
* `git push --tags` or `git push remote tag` - ignore hook
* `git push -d remote tag` - ignore hook

That is, I want call a hook when I try to transfer code only. When I work with branches or tags this hook should't be called. Is it possible?

**Comment by douglascayers** [comment]
You can use git's `--no-verify` argument to not run hooks.

https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---no-verify

**Comment by ym-project** [comment]
> You can use git's `--no-verify` argument when committing or pushing to not run hooks.
> 
> https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---no-verify
> 
> https://git-scm.com/docs/git-push#Documentation/git-push.txt---no-verify
> 
> You can also set environment variable `HUSKY=0` then run your git command to disable hooks as described [here](https://typicode.github.io/husky/#/?id=bypass-hooks).

It's a workaround. If husky provides an opportunity to control hook behavior it'll be great.
Something like this:
`huskyrc.js`
```js
module.exports = {
    'pre-push': 'npm run test',
    extend: {
        ['pre-push'](command) {
            if (/--tags/.test(command)) {
                // skip hook
                return false
            }
            // call hook
            return true
        }
    }
}
```

**Comment by typicode** [comment]
While the suggestion is interesting, husky's scope is just to install and run hooks, so no plans to go further than that.

That said, maybe you can use these values in a shell script to decide if some commands should be run:

https://git-scm.com/docs/githooks#_pre_push
> The hook is called with two parameters which provide the name and location of the destination remote

**Comment by ym-project** [comment]
> While the suggestion is interesting, husky's scope is just to install and run hooks, so no plans to go further than that.
> 
> That said, maybe you can use these values in a shell script to decide if some commands should be run:
> 
> https://git-scm.com/docs/githooks#_pre_push
> 
> > The hook is called with two parameters which provide the name and location of the destination remote

Ok. Thank you. I will try sh scripts.
