### ISSUE TITLE
Git hooks are not setup after postinstall

### ISSUE THREAD

**Issue by theolavaux** [typicode/husky#819]
In my package.json, I've got this script.

```
"postinstall": "husky install"
```

Inside .husky/pre-commit, I have the following.

```sh
#!/bin/sh
[ -z "$CI" ] && exit 0

. "$(dirname $0)/_/husky.sh"

lint-staged
```

After I run npx husky install or yarn husky install, I get

```
husky - installing git hooks...
husky - done
```
However, cat .git/hooks/pre-commit returns no file.

Indeed, no hook is ran when committing and my files are commited without running lint-staged. However, if I do yarn lint-staged, my files are linted correctly.

Using either npm or yarn, my git hooks aren't configured under the .git folder and I only have the pre-commit.sample.

**Comment by douglascayers** [comment]
Same experience using `"husky": "4.3.0"`
```json
    ...
    "husky": {
        "hooks": {
            "pre-commit": "lint-staged",
            "commit-msg": "commitlint -E HUSKY_GIT_PARAMS"
        }
    },
    "lint-staged": {
        "*.{js,ts}": [
            "prettier --write",
            "eslint --fix",
            "git add"
        ]
    },
    "devDependencies": {
        "husky": "4.3.0",
        "lint-staged": "10.5.2",
        "prettier": "2.2.1",
    },
    ...
```

```
$ node --version
v15.1.0

$ npm --version
7.0.8

$ git --version
git version 2.29.2
```

**Comment by douglascayers** [comment]
Possible related to https://github.com/typicode/husky/issues/776

**Comment by theolavaux** [comment]
Here are the versions that I'm using.

$ npm -v
6.14.8

$ node -v
12.20.0

$ git --version
git version 2.17.1

**Comment by typicode** [comment]
Hi, what do you get when running:

```
ls -la .husky/
```

**Comment by theolavaux** [comment]
$ ls -la .husky
total 20
drwxrwxr-x 2 tlavaux tlavaux 4096 Nov 30 11:03 _
drwxrwxr-x 3 tlavaux tlavaux 4096 Nov 30 11:14 .
drwxrwxr-x 7 tlavaux tlavaux 4096 Nov 30 12:31 ..
-rw-rw-r-- 1 tlavaux tlavaux    2 Nov 30 14:01 .gitignore
-rwxr-xr-x 1 tlavaux tlavaux   76 Nov 30 12:59 pre-commit

**Comment by typicode** [comment]
And `git config core.hooksPath`?

**Comment by theolavaux** [comment]
```
$ git config core.hooksPath

.husky
```

**Comment by typicode** [comment]
Hmm weird, everything looks good. Could you try adding some kind of echo message at the top of your `.husky/pre-commit` script:

```sh
#!/bin/sh
echo "hello" && exit 1
...
```

```sh
$ git commit -m test
```

**Comment by theolavaux** [comment]
Ok, I found the problem, it lies in here.

```
[ -z "$CI" ] && exit 0
```

 `$ git commit -m test` was printing echo as expected. After removing the CI check line, my command ran as expected.

**Comment by theolavaux** [comment]
Thanks for help! By the way, isn't this assertion supposed to be this instead ?

```sh
! [ -z "$CI" ] && exit 0
```
