### ISSUE TITLE
Disabling hooks on CI doesn't work anymore with Husky 4.3.4 on Jenkins

### ISSUE THREAD

**Issue by bartw** [typicode/husky#821]
Even when setting the env var `HUSKY=0` in the CI, Husky still tries to set up git hooks.

```
Step 4/17 : ENV HUSKY=0
```
...
```
> husky@4.3.4 install /app/node_modules/husky
> node husky install

husky > Setting up git hooks
fatal: not a git repository (or any of the parent directories): .git
husky > Failed to install
```

**Comment by Divlo** [comment]
Same problem when I run `npm install` inside a docker container with the image `node:14.15.1-alpine3.12`.

**Comment by Divlo** [comment]
Maybe related to this issue : #655

**Comment by typicode** [comment]
`HUSKY=0` is for v5.
Please try `HUSKY_SKIP_INSTALL=1` for husky v4.

**Comment by bartw** [comment]
Thank you @typicode that worked like a charm.

**Comment by Divlo** [comment]
`HUSKY_SKIP_INSTALL=1` solves the issue but I don't think it's a great solution.
We could instead try/catch the installation of `husky`, what do you think ? @typicode

**Comment by Cherry** [comment]
From what I can tell, https://github.com/typicode/husky/commit/033a2ae8e6c7f62205f8499c5c575483fd6b2357 introduced a breaking change here.

Adding `HUSKY_SKIP_INSTALL=1` does of course resolve this, but according to the v4 docs, Husky installs are skipped by default in CI: https://github.com/typicode/husky/tree/master#ci-servers. If this wasn't the case and people were just unknowingly experiencing a "failed" install that previously didn't exit with an error, I'd expect to see a lot more builds fail over the next few weeks when `^4.3.0` resolves to `4.3.4` for people on their rebuilds.

I'd suggest the change at https://github.com/typicode/husky/commit/033a2ae8e6c7f62205f8499c5c575483fd6b2357 be reverted for v4, and introduced as a breaking change in v5, though perhaps with some documentation updates regarding how this works in CI servers that are meant to be skipped.

**Comment by wojtekKrol** [comment]
I  built docker image without any problem   over 15 days ago and everything works fine. Today I had to rebuild it and got the same error but with    "husky": "^4.3.0". 
Why earlier it worked and now it didn't?
 (I had same version of husky back then and now)

`ENV HUSKY_SKIP_INSTALL=1` in `Dockerfile` solved problem

**Comment by Cherry** [comment]
@wojtekKrol See https://github.com/typicode/husky/issues/822. `4.3.5` should resolve this.

**Comment by mittalyashu** [comment]
I am using v6 and `HUSKY=0` doesn't work.

Did the env name got changed again?

**Comment by aleksblendwerk** [comment]
Is the `HUSKY` variable even considered when it comes to installing hooks (as opposed to running hooks)?

I am on v6.

**Comment by mittalyashu** [comment]
According to these lines of code https://github.com/typicode/husky/blob/main/packages/husky/src/husky.sh#L10-L13

It seems it only disable the use of husky instead of disable the installation.

**Comment by mittalyashu** [comment]
`HUSKY=0` doesn't disable the installation of husky itself, instead we can use it while running git commands to disable husky from executing.

**For example:** `HUSKY=0 git commit -m "make commit without running husky"`

**Comment by RyanClementsHax** [comment]
I too am seeing this problem in my CI system with version `6.0.0`

**Comment by binarymist** [comment]
I'm seeing this in version 7.0.4.

```
> husky install

fatal: not a git repository (or any of the parent directories): .git
```

**Comment by typicode** [comment]
> What's the fix for this?

It depends on what you can do on your CI/how you prefer to handle such case. But here are some examples:
https://typicode.github.io/husky/#/?id=disable-husky-in-cidockerprod

**Comment by binarymist** [comment]
Resolved with the following:

```
  "scripts": {
   ...
    "prepare": "if [ -z \"$AN_ENV_VAR\" ]; then husky install ; fi"
  },
```
`AN_ENV_VAR` is an `ENV`in our Dockerfile that always has a value assigned

Thanks.
