### ISSUE TITLE
npm install fails on husky installation

### ISSUE THREAD

**Issue by Moshem123** [typicode/husky#822]
We're running `npm install` on docker with the image [node:dubnium](https://github.com/nodejs/docker-node/blob/c2604466d06ba562fd9040d18c57af16545c6a5b/10/stretch/Dockerfile) and the build fails:
```
12:21:13  > node husky install
12:21:13  
12:21:13  husky > Setting up git hooks
12:21:13  Husky requires Git >=2.13.0. Got v2.11.0.
12:21:13  husky > Failed to install
```

it fails multiple pipelines we have, and of course we don't maintain `node:dubnium` image so upgrading git is not possible.
The only solution is to add `export HUSKY_SKIP_INSTALL=true` to the npm install cmd but it's not realistic as we have many pipelines in many different repos, and adding this seems to be not the best practice.

Please offer a solution so our many builds won't fail,
Thanks!

**Comment by yossisp** [comment]
another temporary fix is to lock the version of husky version in package.json to `"husky": "^4.3.0"`

**Comment by sverweij** [comment]
> another temporary fix is to lock the version of husky version in package.json to `"husky": "^4.3.0"`

@yossisp you probably mean to lock it with `"husky": "4.3.0"` so without the `^`? With the `^` it'll still install husky 4.3.4 (which I found to have the problem).

**Comment by Moshem123** [comment]
> another temporary fix is to lock the version of husky version in package.json to `"husky": "^4.3.0"`

Thanks but I'm looking for a permanent fix (:

**Comment by kopach** [comment]
Hi there. In my case the issue seems similar but error is slightly different 
```bash
> husky@4.3.4 install /home/travis/build/kopach/karma-sabarivka-reporter/node_modules/husky
> node husky install
husky > Setting up git hooks
Cannot destructure property `name` of 'undefined' or 'null'.
husky > Failed to install
```

Also, worth noticing, install fails only on node v11 in my case. More details can be found directly in PR https://github.com/kopach/karma-sabarivka-reporter/pull/309

**Comment by vis97c** [comment]
Yup husky@4.3.4 is throwing me the same error in circleci and heroku.

**Comment by Cherry** [comment]
From what I can tell, https://github.com/typicode/husky/commit/033a2ae8e6c7f62205f8499c5c575483fd6b2357 introduced a breaking change here.

Adding `HUSKY_SKIP_INSTALL=1` does of course resolve this, but according to the v4 docs, Husky installs are skipped by default in CI: https://github.com/typicode/husky/tree/master#ci-servers. If this wasn't the case and people were just unknowingly experiencing a "failed" install that previously didn't exit with an error, I'd expect to see a lot more builds fail over the next few weeks when `^4.3.0` resolves to `4.3.4` for people on their rebuilds.

I'd suggest the change at https://github.com/typicode/husky/commit/033a2ae8e6c7f62205f8499c5c575483fd6b2357 be reverted for v4, and introduced as a breaking change in v5, though perhaps with some documentation updates regarding how this works in CI servers that are meant to be skipped.

**Comment by typicode** [comment]
I've rolled it back. Sorry for the bad release.
It was to make the logs visible with  npm 7 since currently husky fails silently https://github.com/typicode/husky/issues/776

**Comment by PeiLiao** [comment]
Same issue. But installed successfully by using node V10.
