### ISSUE TITLE
npm ERR! INIT_CWD is not set, please check that your package manager supports it

### ISSUE THREAD

**Issue by remarkablemark** [typicode/husky#823]
For remarkablemark/html-react-parser#186, I'm seeing the [Travis CI](https://travis-ci.org/github/remarkablemark/html-react-parser/builds/748021059) error when installing husky v4.3.4:

```sh
$ node --version
v15.3.0
$ npm --version
7.0.14
$ nvm --version
0.37.0

$ npm install
npm ERR! code 1
npm ERR! path /home/travis/build/remarkablemark/html-react-parser/node_modules/husky
npm ERR! command failed
npm ERR! command sh -c node husky install
npm ERR! husky > Setting up git hooks
npm ERR! INIT_CWD is not set, please check that your package manager supports it (npm 7.0.14)
npm ERR! 
npm ERR! Alternatively, you could set it manually:
npm ERR! INIT_CWD="$(pwd)" npm install husky --save-dev
npm ERR! 
npm ERR! Or upgrade to husky v5
npm ERR! husky > Failed to install

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2020-12-07T00_35_40_858Z-debug.log
The command "npm install" failed and exited with 1 during .
```

Not sure if this is related to #822 and #640.

**Comment by typicode** [comment]
It's actually related to https://github.com/typicode/husky/issues/776

npm 7 only show logs if the script fails. It was an attempt to make logs visible, let people know that husky didn't install with ways to fix that. But it also created some issues there https://github.com/typicode/husky/issues/822

So all in all, it wasn't a good release. I've rolled it back with `v4.3.5`.

Personally, if you have an OSS project, I'd recommend using `v5` which doesn't have this issue with npm 7. I'm using it on my projects.

Let me know if you have any other questions.

**Comment by remarkablemark** [comment]
Thanks for the clarification and the quick release! I'll look into upgrading to `husky@5` as my next task.
