### ISSUE TITLE
Clarification on latest version

### ISSUE THREAD

**Issue by rarkins** [typicode/husky#825]
Is the latest version on npm intended to be `4.3.5` or `5.0.4`? It looks like `5.0.4` was temporarily published as latest but now `4.3.5` is. This has resulted in [a lot of autoclosed upgrade pull requests](https://github.com/search?q=renovate+update+husky+v5+autoclosed+is%3Apr&type=Issues)

**Comment by typicode** [comment]
My bad, it was a mistake. Sorry for the confusion.

For the moment, the latest on npm is intended to be `4.3.5` but `5.0.4` is ready to be used and should be preferred if you have an OSS project (or if you're a sponsor).

At some point `5` will be the latest on npm.

**Comment by rarkins** [comment]
BTW I manage the Renovate Bot tool which provides people with automated Pull Requests for updates. I see that there's a licensing implication for updating to version 5 however it is not mentioned in the [GitHub release notes for v5](https://github.com/typicode/husky/releases/tag/v5.0.0) and only quite far down in the page that they link to. I assume it would be undesirable that quite a few private projects may update to this library *without* being aware of the implications? Assuming that's not intentional, would you consider editing the release notes so that there is some mention and people do not accept the upgrade without being aware?

**Comment by typicode** [comment]
> would you consider editing the release notes so that there is some mention and people do not accept the upgrade without being aware?

Sure, so I guess I'll need to add the mention on other releases as well (5.0.1, 5.0.2, ...) until it's MIT again?

**Comment by rarkins** [comment]
I think only a need for 5.0.0 as that's what people check for breaking changes

**Comment by typicode** [comment]
https://github.com/typicode/husky/releases/tag/v5.0.0 updated :)

That said, there's a green banner at the top of https://typicode.github.io/husky/ but maybe the message is not clear enough?

**Comment by rarkins** [comment]
v5 release notes look great - thanks for updating those. Now once v5 gets tagged as latest again and Renovate raises all those PRs that message will be embedded within the PR so much harder to miss. And yes I actually did miss that green banner and scrolled until I saw "Free for Open Source, early access for Sponsors" further down.

**Comment by typicode** [comment]
Thanks for all the feedback :)
