### ISSUE TITLE
v5: why does a custom directory require package.json?

### ISSUE THREAD

**Issue by ericcornelissen** [typicode/husky#827]
The [v5 documentation says](https://typicode.github.io/husky/#/?id=custom-directory) you can install Husky into a custom directory with the install command by specifying a custom path. However, the source requires this custom directory to have a `package.json` file (see below), but that doesn't seem necessary to me. I did some manual testing (commenting out the snippet below in `node_modules/husky`) and installed into a subdirectory and as far as I can tell everything works fine (including running NPM scripts, but even if that wasn't possible I don't know why that must be supported), but maybe I'm missing something...

https://github.com/typicode/husky/blob/aaf1beed46962a2d9ea01e7d9a7ca06324ccb3f3/src/commands/install.ts#L32-L34

Relatedly, the first example in the ["Custom directory" documentation](https://typicode.github.io/husky/#/?id=custom-directory) suggests to me that I can install the hooks into a directory called `.config` instead of `.husky`, but the result of the example would be that the hooks are installed into `.config/.husky`. Not sure if that is just me reading it wrong or if it is a mistake in the documentation.

In any case, I would like to see the option to change the name of the `.husky` folder in addition to changing the directory, would you be open to such a feature @typicode? My initial suggestion for this would be to have a separate option+argument for that, e.g. `husky install custom/dir -dirname .config`.

**Comment by typicode** [comment]
The fact that the custom dir requires `package.json` is likely a bug I think.
Overall this part is a bit rough around the edges, I do plan to improve that this week.
Thanks for the feedback :+1:

**Comment by typicode** [comment]
Should be good with `v5.0.6`, I've updated documentation.

**Comment by ericcornelissen** [comment]
Works as expected now, awesome 👍 Thank you very much!
