### ISSUE TITLE
Pre commit hook checks for source lint (not stagged)

### ISSUE THREAD

**Issue by vahidvdn** [typicode/husky#828]
The idea of git hooks is for preventing the wrong source code from being committed. I use `husky` for this purpose. Here is my setting:

```json
"husky": {
  "hooks": {
    "pre-commit": "ng lint --fix=true"
  }
}
```

If there is a lint error, it prevents from being committed. Here is the scenario:

 1. Developer writes wrong code (e.g. `x==y` which should be `x===y` from lint point of view)
 2. He uses these commands: `git add .` and `git commit -m "msg here"` which fails. Because lint fails.
 3. He corrects the source code. But instead of doing `git add .` again, he uses this command: `git commit -m "msg here"`. This time lint doesn't fail, because in source code everything is fine, and `ng lint` succeeds. But actually, he is committing the previous version which has been added before.

Any idea how to prevent this?

**Comment by typicode** [comment]
Hmm, I'm not sure, but I'd try https://github.com/okonet/lint-staged

**Comment by vahidvdn** [comment]
@typicode Thanks. For now, I'm going to close the issue.
