### ISSUE TITLE
_postinstall

### ISSUE THREAD

**Issue by ozum** [typicode/husky#829]
Hi,

Trying husky v5, I added `"postinstall": "is-ci || husky install"` to my scripts. When I execute `npm install`, husky renames script to `_postinstall`.

As a result, when I push my project, it does not have `postinstall` script anymore.

Is it expected behaviour?

**Comment by typicode** [comment]
Hi,

I'd check if https://github.com/typicode/pinst isn't running at some point.
Husky alone can't rename `postinstall`.

**Comment by ozum** [comment]
Thanks.
