### ISSUE TITLE
is there documentation on just how to write a custom hook?

### ISSUE THREAD

**Issue by mxtetrachord** [typicode/husky#831]
i need to generate a shell file or similar, to be checked into VC, for my whole team to use as a precommit step. we have old tests that need to get run manually, and so i've written a shell script that just asks the user for a `Y/n` and blocks the commit if no.

i've been trying to find docs as to where this file should live, how i can make it available to the rest of my team, and even what it should do—currently i'm exiting with either 0 or 1 based on the user's response, but i'm not sure that's correct.

any guidance and docs would be appreciated!

**Comment by mxtetrachord** [comment]
i should note we're on v4 at the moment, with few plans to upgrade, if that makes this easier.

**Comment by typicode** [comment]
> currently i'm exiting with either 0 or 1 based on the user's response, but i'm not sure that's correct.

That's correct.

No docs in particular but with v4, you may want to try the following config:

```
{
  "hooks": {
    "pre-commit": "sh path/to/script.sh"
  }
}
```

That said, a script asking the user can cause trouble with GUI clients. For example GitHub Desktop users may not have a terminal where they can answer the question.

**Comment by mxtetrachord** [comment]
thanks for your help! i think i'm able to stick this together from here.
