### ISSUE TITLE
Installing post-commit hook with "commit --amend" causes havoc in package.json

### ISSUE THREAD

**Issue by Vadorequest** [typicode/husky#834]
I'm trying to simplify a workflow by using Husky.

Basically, I want to store the git commit hash/branch in the package.json, so that it's easy to know from which commit hash and branch each commit was made from. (to be used in the source code) 

I'm trying to do it using [`git-hash-package`](https://github.com/Metnew/git-hash-package), and run it  after a commit has been made (using post-commit hook), by amending the previous commit and adding whatever changed in package.json into the previous commit. (that might not be really elegant, but it seemed simple enough for a first try)

Here is how my `.husky.post-commit` file looks like:
```bash
#!/bin/sh
. "$(dirname $0)/_/husky.sh"

npx git-hash-package && git add package.json && HUSKY=0 git commit --amend --no-edit

```

It seems to work fine at first glance, but when I edit anything in the package.json, there seems to be something running that make the memory and filesystem out of sync. Also, upon commit, the commit kinda seem to enter an infinite loop.

Here is a video that shows what happens.
https://youtu.be/UwUJm76yPQQ

Maybe what I'm trying to do is completely dumb and can't work, but I thought it might be possible.

**Comment by red2678** [comment]
If you check the idea `git log` window do you see any errors? Also, if you break the command into 3 separate lines does it work? Breaking up the command into 3 lines could potentially help trace the error better.

**Comment by JohnPangalos** [comment]
I had this problem as well, I fixed this by moving the post-commit hook to a pre-push hook. This stopped the infinite loop anyway.

**Comment by moevasya** [comment]
@johnpangalos but im running into another issue where i have 1 commit ahead and 1 commit behind, any thoughts ?

**Comment by johnpangalos** [comment]
I am unsure, it sounds like there are new commits upstream that you need to pull. Have you tried got pull?

**Comment by johnpangalos** [comment]
Were you trying to implement the above @moevasya? If so, what can you provide a bit more information.
