### ISSUE TITLE
Cannot spawn .husky/pre-commit: No such file or directory

### ISSUE THREAD

**Issue by oceandrama** [typicode/husky#835]
I got this error after migration to v5 while executing `git commit`

I have the following .husky/pre-commit:
```
yarn lint-staged
```

husky: 5.0.6
node: 14.5.0
OS: Windows 10

**Comment by oceandrama** [comment]
Oh, I've added file manually, not using `hasky add` command. That's my mistake

**Comment by InSuperposition** [comment]
Anyone with this issue using Git for Windows should check their line endings

https://github.com/typicode/husky/issues/1010#issuecomment-898606055

**Comment by Mandra-dev** [comment]
Had the same problem, found my answer [here](https://github.com/conventional-changelog/standard-version/issues/254#issuecomment-424669323)
