### ISSUE TITLE
View husky progress in VSCode as it's available

### ISSUE THREAD

**Issue by cupidchan** [typicode/husky#838]
I found out that the result of Husky will be shown in the OUTPUT windows AFTER the progress is completed. Is there anyway we can configure husky so that the output will be shown as it's available, instead of wait after all progresses are done? If no, can we make it as an enhancement request? Thanks!

**Comment by typicode** [comment]
Hi @cupidchan,

Good suggestion, however I don't think it's something that can be done on husky's side. Husky runs commands passed by the user and the commands can show progress (like Jest for example) but, AFAIK, there's no way to force VSCode to display that.

**Comment by cupidchan** [comment]
@typicode , sorry to bring this up again. But may I ask if there is any setting in VSCode that you are aware of to see what is happening in the pre-commit process? Right now, I can only see a progress bar running across repeatedly at the top of the Source Control section after I commit the change. However, everything is like working inside a black box that I don't even know if it's getting hung in the process or it's just simply taking a long time to execute.

**Comment by jonnytest1** [comment]
I would recommend a vscode extension that registers a new husky output panel - doing the integration might require work on husky as well though

**Comment by mackelito** [comment]
> I would recommend a vscode extension that registers a new husky output panel - doing the integration might require work on husky as well though

Do you have a suggestion?
I would also like a similar setup but not sure how to do it
