### ISSUE TITLE
Environment variable 'HUSKY_GIT_PARAMS' is not available globally

### ISSUE THREAD

**Issue by NorthDecoder** [typicode/husky#840]
I realize the husky 4.x.x version is not the latest and maybe ending LTS, however
this comment may help someone with the same problem.  My problem is most likely
a documentation misunderstanding.

Following the documentation I tried:
```bash
λ HUSKY_DEBUG=1 git commit -m "xxx"


husky:debug husky v4.3.0 - pre-commit
husky:debug Current working directory is /home/northdecoder/workspace/projectnamehere/test
husky > pre-commit (node v14.15.1)
/home/northdecoder/workspace/projectnamehere/test/node_modules/@commitlint/cli/lib/cli.js:100
        throw err;
        ^

Error: Recieved 'HUSKY_GIT_PARAMS' as value for -E | 
--env, but environment variable 'HUSKY_GIT_PARAMS' is not available globally
```

in `package.json` with what documentation currently recommends
```javascript
 "husky": {
  "hooks": {
   "commit-msg": "commitlint -E HUSKY_GIT_PARAMS",
   "pre-commit": "commitlint -E HUSKY_GIT_PARAMS "
  }
 }
 ```

----

__tried__   EDIT: (❌ antipattern)

reference the commitlint help:
```bash
commitlint -h
@commitlint/cli@11.0.0 - Lint your commit messages
...
--edit, -e           read last commit message from the specified file or
                       fallbacks to ./.git/COMMIT_EDITMSG
...
```

in `package.json` change the commitlint switch from -E to -e
```javascript
 "husky": {
  "hooks": {
   "commit-msg": "commitlint -e",
   "pre-commit": "commitlint -e "
  }
 }
 ```
but this does not work, because the file contains the previous commit message.
I _can_ manually clear the previous message before making the next commit.

```bash
#manually clear the previous message
echo > ../.git/COMMIT_EDITMSG
# make some changes
vim deleteme.md
#...
# write a non compliant message
git commit -m "added header in deleteme.md"
# commitlint provides accurate error message

# notice old message is still there
cat ../.git/COMMIT_EDITMSG

#manually clear the previous message
echo > ../.git/COMMIT_EDITMSG
# make some changes
vim deleteme.md

#...
# write a compliant message
git commit -m "test(deleteme.md): added header"
# commitlint accepts the commit message
```
The caveat is remembering to clear the previous message.

**Comment by typicode** [comment]
Hi,

I think you're getting an error because `pre-commit` takes no parameter (https://git-scm.com/docs/githooks#_pre_commit) and so `HUSKY_GIT_PARAMS` is empty.

I would try using `commitlint` only in the `commit-msg` hook and delete `pre-commit` config.

**Comment by NorthDecoder** [comment]
Thank you for getting me going in the right direction. Sorry for the trouble.  Looking back, I am not sure where I copied that extra command from.

**Comment by typicode** [comment]
No worries, glad it's working now :)
