### ISSUE TITLE
`postinstall` script leads to unnecessary runs in client

### ISSUE THREAD

**Issue by brandonpittman** [typicode/husky#843]
Just a thought about changing the docs.

We have a frontend package that the backend app installs. The frontend app was installing husky in the `postinstall` script, but that means the backend app's install triggers husky. Putting the `is-ci || husky install` script in `prepare` instead, gets around this problem.

Am I doing something wrong, or is this the intended behavior?

I am using `pinst` as indicated in the docs but that seemed to have no effect on how the backend app's install of the frontend package happened.

**Comment by typicode** [comment]
Is your frontend package published somewhere?

**Comment by brandonpittman** [comment]
No, it's pushed to GitHub, and then the backend PHP app installs it from the GitHub repository directly.

**Comment by abhijit945** [comment]
This is pretty beneficial when you have script for Angular `ngcc` in `postinstall`.
