### ISSUE TITLE
v5 fails to find git-lfs

### ISSUE THREAD

**Issue by qapla47** [typicode/husky#848]
Upgraded to test v5 and see if we wanted to go that route while we were updating all our packages, and found the following four errors:
This repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/[post-checkout][post-commit][post-merge][pre-push]

Files were also created in the .husky directory with those four filenames, with the matching error message.
These errors prevented me from being able to make PRs, and I had to uninstall v5 in order to move on.

We are absolutely using git-lfs in our project, it has been working for years, and this issue does _not_ happen with v4.3.8.

**Comment by typicode** [comment]
Hmm not sure what would be the difference that would cause this issue.
I tried with v4 and the same files are installed in .git/hooks (instead of .husky).

Are you using a GUI? Does it fail if you try to commit in the terminal? If you run `git-lfs` in the terminal, do you have an error?
