### ISSUE TITLE
Uninstalling Husky 5 leaves local git config in an invalid state

### ISSUE THREAD

**Issue by Robin-Hoodie** [typicode/husky#849]
So I just tried using Husky 5 `husky@next` by doing the following:

- `yarn add husky@next` => Installs Husky 5
- `yarn husky install` 
- I then realised I instead wanted to work with Husky 4
- `yarn remove husky`
- `yarn add husky` => Installs Husky 4

This led to none of my git hooks being called anymore

After a few hours of debugging I figured out that running `yarn husky install` actually sets `core.hooksPath` in your local git config to `.husky`. This does not seem to be documented anywhere and that would be reasonable if removing `husky@next` from your repo would actually also clean up after itself and unset `core.hooksPath` again (or even better, save the value of `core.hooksPath` if it was set, and set it back to whatever it was)

My suggestion is thus one of the following:

1. (Preferred) - Removing `husky@next` from your repo will unset `core.hooksPath` - I'm not familiar enough with `package.json#scripts` to know whether or not this is a viable solution
2. Add uninstall instructions to the docs, telling people they need to run `git config --unset core.hooksPath` if removing `husky@next`

Regardless of the solution, I would document that running `yarn husky install` will set the `core.hooksPath` property in your local git config.

I'm happy to help out with a PR that implements whatever solution is deemed best

**Comment by typicode** [comment]
Hi,

Thanks for the report.

Regarding 1, there's a `preuninstall` script that should execute `git config  --unset core.hooksPath` automatically. It seems like it's not called though, not sure why.

https://github.com/typicode/husky/blob/next/package.json#L39

**Comment by Robin-Hoodie** [comment]
Yarn 2 does not seem to support the `preuninstall` lifecycle script: https://yarnpkg.com/advanced/lifecycle-scripts

Perhaps best to update the documentation for now?

**Comment by typicode** [comment]
Closed by #853 :)
