### ISSUE TITLE
using husky without a local install of node

### ISSUE THREAD

**Issue by tim-millar** [typicode/husky#852]
Hi 

I'm trying to use husky in a dockerised application. At the moment I sync node_modules on the container and the host, which gives us access to husky locally and so we can use it to run eslint and prettier on commit, etc.

However this workflow falls apart for those devs who do not have local installs of node. Ideally we would configure husky to use `docker-compose run web node` (for e.g.) when it runs, rather than searching the path for the executable and failing. Is this possible?

Another idea I had was to sync the node executable between host and container (and maybe rely on `run-node` to access it), but then we would running be node built for ubuntu from mostly macOS dev machines.

Is there a good solution for this, that you know of (other than simply getting everyone to install node locally)?

Many thanks

**Comment by vansergen** [comment]
@tim-millar You can use the [`node:14-buster` ](https://hub.docker.com/layers/node/library/node/14-buster/images/sha256-32362e2ea89c62d77c86c8f26ad936dbbdc170cd6c06c4d7ff7a809012bb0c32?context=explore)container.

**Comment by tim-millar** [comment]
@vansergen how is that configured?

**Comment by vansergen** [comment]
@tim-millar Something like this should work

```dockerfile
FROM node:14-buster

WORKDIR /app

# Copy your app (where you want to use husky with the config)
COPY . .

# Install dependencies (including husky)
# https://typicode.github.io/husky/#/?id=install 
RUN npm install

# Do something else
# RUN <cmd>

# Use husky as usual
RUN git commit -m "bad commit"

# app
CMD ["npm", "start"]

```

**Comment by tim-millar** [comment]
Thanks @vansergen. The issue is that git is running locally. A developer will make changes to the application and commit files using the local install of git. Ideally we would run the whole process via the container. At present git runs the hook, which calls out to husky (present locally), which calls out to node (not necessarily present), which ultimately runs a command in the container (from this point on it works fine). 

What would help is if we could tell husky where to find node (e.g., to use `docker-compose run web node`, rather than searching the path for the executable).

**Comment by vansergen** [comment]
@tim-millar  Did you try [`.devcontainer`](https://code.visualstudio.com/docs/remote/containers#_create-a-devcontainerjson-file) for developing inside a container where you could have all necessary tools?

**Comment by tim-millar** [comment]
unfortunately not everyone is using vs code so we would like a solution where developer tooling can be run locally

**Comment by sashaaKr** [comment]
@tim-millar did you find any workaround for that?

**Comment by tim-millar** [comment]
@sashaaKr we made a local install of node a prerequisite for development.

**Comment by andreighh** [comment]
How about this?

```
docker-compose exec -T web node
```

I use something similar and I also don't have node locally, works fine.

**Comment by sashaaKr** [comment]
@andreighh yes, this is exactly how we did it.
Only one thing in this approach that I don't like is that you need to make sure that you already have running container.
