### ISSUE TITLE
Command "husky-run" not found.

### ISSUE THREAD

**Issue by budarin** [typicode/husky#854]
Just have upgraded from v4.3.8 to v5.0.9 and got the error

have tried to uninstall/install husky, remove `npde_modules` - nothing helped

```bash
> git -c user.useConfigOnly=true commit --quiet --allow-empty-message --file -
error Command "husky-run" not found.
```

**Comment by Milo123459** [comment]
Can confirm. This is so ridiculously annoying.

**Comment by typicode** [comment]
Hi @budarin,

Could you provide steps to reproduce the issue? Also are you using Git 2.9+?

**Comment by Milo123459** [comment]
^ I'm using latest git version.

**Comment by budarin** [comment]
git version 2.30.0

steps to reproduce - upgrade husky to the latest ver.

**Comment by Milo123459** [comment]
Git version: 2.30.0.windows.2, if this is required for git 2.9+ then there needs to be support for older versions

**Comment by typicode** [comment]
Hmm, can't try right now on Windows. But here are the steps I've done and it seems to work. Let me know if I'm missing something.

```sh
/tmp/foo main*
❯ git init
Initialized empty Git repository in /tmp/foo/.git/

/tmp/foo main*
❯ npm init -y
Wrote to /tmp/foo/package.json:

{
  "name": "foo",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "husky": "^4.3.8"
  },
  "dependencies": {},
  "description": ""
}



/tmp/foo main*
❯ npm install husky@4 -D

> husky@4.3.8 preuninstall /tmp/foo/node_modules/husky
> node husky uninstall

husky > Uninstalling git hooks
husky > Done

> husky@4.3.8 install /tmp/foo/node_modules/husky
> node husky install

husky > Setting up git hooks
husky > Done

> husky@4.3.8 postinstall /tmp/foo/node_modules/husky
> opencollective-postinstall || exit 0

Thank you for using husky!
If you rely on this package, please consider supporting our open collective:
> https://opencollective.com/husky/donate

npm WARN foo@1.0.0 No description
npm WARN foo@1.0.0 No repository field.

+ husky@4.3.8
updated 1 package and audited 47 packages in 1.883s

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities


/tmp/foo main*
❯ npm install husky@5 -D

> husky@4.3.8 preuninstall /tmp/foo/node_modules/husky
> node husky uninstall

husky > Uninstalling git hooks
husky > Done
npm WARN foo@1.0.0 No description
npm WARN foo@1.0.0 No repository field.

+ husky@5.0.9
removed 46 packages, updated 1 package and audited 1 package in 0.67s

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities


/tmp/foo main*
❯ npx husky install
husky - Git hooks installed

/tmp/foo main*
❯ npx husky add .husky/pre-commit "echo hello && exit 1"
created .husky/pre-commit

/tmp/foo main*
❯ git add package.json

/tmp/foo main*
❯ git -c user.useConfigOnly=true commit --quiet --allow-empty-message --file -
hello
husky - pre-commit hook exited with code 1 (error)
```

**Comment by Milo123459** [comment]
Let me try uninstalling the hooks

**Comment by Milo123459** [comment]
I mean, it uninstalled them and I ran it to install again but didn't install them.. Odd.

**Comment by Milo123459** [comment]
^ After downgrading and building again, it just, doesn't work. I've got an idea but a faint one.

**Comment by Milo123459** [comment]
Alright, figured out how to fix it.

Firstly, we need to remove .git/hooks.

For me, I ran typicodes [husky-4-to-5](https://github.com/typicode/husky-4-to-5), which worked like a charm.

Then, run yarn / npx husky install.

Viola, should work. You can check out my [repo](https://github.com/Milo123459/Spencer/tree/v1) to check out how I did it. 

Have a great day. 👋

**Comment by mo-sharif** [comment]
Thanks, @Milo123459 your suggestion works like a charm 🙌

**Comment by Milo123459** [comment]
Glad it does 😉

**Comment by budarin** [comment]
> Alright, figured out how to fix it.
> 
> Firstly, we need to remove .git/hooks.
> 
> For me, I ran typicodes [husky-4-to-5](https://github.com/typicode/husky-4-to-5), which worked like a charm.
> 
> Then, run yarn / npx husky install.
> 
> Viola, should work. You can check out my [repo](https://github.com/Milo123459/Spencer/tree/v1) to check out how I did it.
> 
> Have a great day. 👋
> 
> Leave me a comment if this helped you out!

it did not help me :(

**Comment by Milo123459** [comment]
What's happened meaning it didn't work?
Can you send me if it erodes?

**Comment by budarin** [comment]
> What's happened meaning it didn't work?
> Can you send me if it errors?

there were no error - hooks folder had not been created with husky

**Comment by Milo123459** [comment]
Try, npx husky install.

**Comment by budarin** [comment]
> Try, npx husky install.

![image](https://user-images.githubusercontent.com/8055157/107414454-12e5a780-6b23-11eb-9996-bbf186c5194e.png)

![image](https://user-images.githubusercontent.com/8055157/107414478-1aa54c00-6b23-11eb-9fad-839beb3e1e89.png)

You could see that husky does not recreate `hooks` folder during installation

**Comment by Milo123459** [comment]
Try `yarn husky install`

**Comment by budarin** [comment]
but my previous hooks are lost!!! :(

**Comment by Milo123459** [comment]
Firstly, don't close this issue, it'll be helpful for other users.
Secondly, they should still be in your package.json

**Comment by Milo123459** [comment]
Did you run husky 4 to 5?

**Comment by budarin** [comment]
> Firstly, don't close this issue, it'll be helpful for other users.
> Secondly, they should still be in your package.json

they are in package.json but not useb with husky in commit process

**Comment by Milo123459** [comment]
yarn husky add .husky/hook-name "script to run"

**Comment by budarin** [comment]
> Did you run husky 4 to 5?

```bash
23 verbose stack Error: could not determine executable to run
23 verbose stack     at getBinFromManifest (C:\Program Files\nodejs\node_modules\npm\lib\exec.js:264:23)
23 verbose stack     at exec (C:\Program Files\nodejs\node_modules\npm\lib\exec.js:178:15)
24 verbose cwd C:\Users\Мастер\AppData\Local\npm-cache\_cacache\tmp\git-clone-bc12e66d
```

**Comment by budarin** [comment]
> yarn husky add .husky/hook-name "script to run"

I used to use huskyrc.js - now it's useless?

**Comment by Milo123459** [comment]
Yes.

**Comment by Milo123459** [comment]
> > Did you run husky 4 to 5?
> 
> 
> 
> ```bash
> 
> 23 verbose stack Error: could not determine executable to run
> 
> 23 verbose stack     at getBinFromManifest (C:\Program Files\nodejs\node_modules\npm\lib\exec.js:264:23)
> 
> 23 verbose stack     at exec (C:\Program Files\nodejs\node_modules\npm\lib\exec.js:178:15)
> 
> 24 verbose cwd C:\Users\Мастер\AppData\Local\npm-cache\_cacache\tmp\git-clone-bc12e66d
> 
> ```

I node version?

**Comment by budarin** [comment]
> > > Did you run husky 4 to 5?
> > 
> > 
> > ```shell
> > 23 verbose stack Error: could not determine executable to run
> > 
> > 23 verbose stack     at getBinFromManifest (C:\Program Files\nodejs\node_modules\npm\lib\exec.js:264:23)
> > 
> > 23 verbose stack     at exec (C:\Program Files\nodejs\node_modules\npm\lib\exec.js:178:15)
> > 
> > 24 verbose cwd C:\Users\Мастер\AppData\Local\npm-cache\_cacache\tmp\git-clone-bc12e66d
> > ```
> 
> I node version?

v15.8.0

**Comment by Milo123459** [comment]
Never mind on that, just convert everything to .husky/hook

**Comment by budarin** [comment]
do
`yarn husky add .husky/pre-commit "lint-staged"`

then try to commit - got the error:
```bash
> git -c user.useConfigOnly=true commit --quiet --allow-empty-message --file -
.husky/pre-commit: line 4: lint-staged: command not found
husky - pre-commit hook exited with code 127 (error)
```

**Comment by Milo123459** [comment]
Replace lint-staged with yarn lint-staged

**Comment by budarin** [comment]
> Replace lint-staged with yarn lint-staged

what about other command like `commitlint` in scripts?

`.husky/commit-msg: line 4: commitlint: command not found`

**Comment by Milo123459** [comment]
Yup, yarn commitlint, take a look at my repo Milo123459/Spencer and the branch v1 to see how I do it.

**Comment by budarin** [comment]
cann not convert my prev post-checkout

`if [[ $HUSKY_GIT_PARAMS =~ 1$ ]]; then ${'yarn install --frozen-lockfile'}; fi`

**Comment by Milo123459** [comment]
Husky git paeans was used. Replace it with $1

**Comment by budarin** [comment]
> Husky git paeans was used. Replace it with $1

could you fix the code, please

**Comment by budarin** [comment]
try to do the same steps on Mac - there is no any effect - changes are committed without hooks

**Comment by Milo123459** [comment]
No. I'm on my phone, just replace $HUSKY_GIT_PARAMS with $1

**Comment by budarin** [comment]
> No. I'm on my phone, just replace $HUSKY_GIT_PARAMS with $1

is there any sense `$1 =~ $1`?

**Comment by Milo123459** [comment]
No clue. Just always run it? 🙃

**Comment by budarin** [comment]
do on Mac
```
yarn add husky
yarn husky install
yarn husky add .husky/hook1 "..."
. . . 
yarn husky add .husky/hookN "..."
```
it does not take an effect when I commit the changes

**Comment by Milo123459** [comment]
What does .husky/pre-commit look like?

**Comment by budarin** [comment]
> What does .husky/pre-commit look like?

sorry, it works if I use it when clone a project with hooks on Mac at first time - I should manually recreate hook to proper set access rights to them :(

**Comment by Milo123459** [comment]
Well you'll need to run the install husky thing every time you install so run it on a post install script

**Comment by budarin** [comment]
> Well you'll need to run the install husky thing every time you install so run it on a post install script

not only husky install but fix access rights to hooks on linux based OS's

**Comment by inhaq** [comment]
Initially, followed @Milo123459 and `deleted .git/hooks` and then was getting an error in following the next steps and git was committing code without hooks. Then tried `yarn husky install` and `yarn husky add .husky/pre-commit "lint-staged"` it worked. btw node is v15.8.0

**Comment by Milo123459** [comment]
> Initially, followed @Milo123459 and `deleted .git/hooks` and then was getting an error in following the next steps and git was committing code without hooks. Then tried `yarn husky install` and `yarn husky add .husky/pre-commit "lint-staged"` it worked. btw node is v15.8.0 

Glad it worked!

**Comment by PaulMEdwards** [comment]
> Initially, followed @Milo123459 and `deleted .git/hooks` and then was getting an error in following the next steps and git was committing code without hooks. Then tried `yarn husky install` and `yarn husky add .husky/pre-commit "lint-staged"` it worked. btw node is v15.8.0

Should you use `yarn lint-staged` in your pre-commit [as @Milo123459 suggests in the comment here](https://github.com/typicode/husky/issues/854#issuecomment-776259276)?

I'm doing the same and neither command errors on commit, but when run manually, only the command run as a `yarn` argument works.

**Comment by Milo123459** [comment]
Are you using yarn?

**Comment by PaulMEdwards** [comment]
Yeah, the point is that the `lint-staged` command needs to be prefixed with either `yarn` or `npx` and can't just be run on its own.

I had the same issue as the OP and the 4-to-5 script doesn't work for me due to https://github.com/typicode/husky-4-to-5/issues/1. I had to manually perform the 4-to-5 migration process and what resolved the error was removing the `husky` configuration section from the `package.json` file after creating the new v5 `.husky` hooks hidden folder & populating the pre-commit config file.

**Comment by Milo123459** [comment]
Package.json scripts are isolated which gives access to all binaries installed. The SH file is not. That's why you have to prefix it.

**Comment by inhaq** [comment]
@PaulMEdwards yup, using `yarn` but you can use `npx` as well mentioned above by @Milo123459

**Comment by Milo123459** [comment]
There probably is a way to isolate the sh files like package.json scripts, but it'll have to work for pnpm and yarn v2 which is a pain.

**Comment by shellscape** [comment]
Can confirm that the latest version of 5.x is broken again with `pnpm`. Looking at issues between pnpm and husky repos, this seems to pop up as an issue at least once a year. Can't help but wonder if something can be done to prevent these regressions.

**Comment by Milo123459** [comment]
pnpx. Use pnpx.

**Comment by shellscape** [comment]
@Milo123459 that's a workaround, not a solution. I'd expect husky to behave the same on install between  4.x and 5.x. As it is, it's broken.

**Comment by Milo123459** [comment]
It's not pnpms fault. It's husky's. The script just has to be isolated like the npm scripts are. I'm sure there is a way to do that.

Also, at least it works, better then nothing! 😅

**Comment by shellscape** [comment]
We're on the same page there, saying the same thing in different ways 👍

**Comment by SalahAdDin** [comment]
> Initially, followed @Milo123459 and `deleted .git/hooks` and then was getting an error in following the next steps and git was committing code without hooks. Then tried `yarn husky install` and `yarn husky add .husky/pre-commit "lint-staged"` it worked. btw node is v15.8.0

Well, this does not work for me, hooks are not working now.

**Comment by Milo123459** [comment]
@SalahAdDin try `yarn lint-staged` as seen in my example.

**Comment by SalahAdDin** [comment]
I solved it by the **GitKraken** related issue.

**Comment by kevinschaffter** [comment]
@SalahAdDin Can you post that issue here and your fix?

**Comment by typicode** [comment]
To fix `husky-run` not found, install husky 5 and run `husky init` script:

With yarn:

```
yarn add husky -D && yarn husky init
```

With pnpm:

```
pnpm add husky -D && pnpx husky install
```

It will set up hooks and create a pre-commit hook that you can edit in `.husky/pre-commit`. If you want to add another hook, __it's highly recommended__ to use `husky add ...` command.

Optionally, you can delete `.git/hooks` to remove artifacts from husky 4 (it's automatically done if you upgrade with `npm`).

There's also section for migrating from husky 4 to 5 in the docs:
https://typicode.github.io/husky/#/

Hope this helps :)

**Comment by SalahAdDin** [comment]
> @SalahAdDin Can you post that issue here and your fix?

Issue and fix: https://github.com/typicode/husky/issues/875

**Comment by shellscape** [comment]
@typicode running `yarn husky init` results in the following:

```
Usage
  husky install [dir] (default: .husky)
  husky uninstall
  husky set|add <file> [cmd]
```

You closed this issue with bad info.

**Comment by Milo123459** [comment]
That looks like husky6, this issue covered husky 5..

**Comment by SalahAdDin** [comment]
> That looks like husky6, this issue covered husky 5..

No way, **Husky 6**?

**Comment by guaizi149** [comment]
package.json
add `"prepare": "npx husky install",`

**Comment by sourceful-julian** [comment]
I found this very helpful for mac osX - https://dev.to/studiospindle/using-husky-s-pre-commit-hook-with-a-gui-21ch
adding the path to your local/user npm files (`PATH="/usr/local/bin:/Users/julian/.npm/bin:$PATH"`) fixed the problems I had with husky not being able to find yarn despite having the npm/bin path in my global PATH

**Comment by asvetlenko** [comment]
I have the same issue:
<img width="1724" alt="image" src="https://user-images.githubusercontent.com/9693052/154281660-186c8579-0b3d-4e9c-a0b8-8206d2e62ac5.png">
