### ISSUE TITLE
Allow hooks to display colors.

### ISSUE THREAD

**Issue by Milo123459** [typicode/husky#858]
Hooks right now can't display colors, for example using chalk won't display the colors correctly. 

**This is probably a git hook issue** but I don't know. 

If it is a git hook issue, then a contribution "fixing" it would be cool.

**Comment by typicode** [comment]
I would check maybe in another terminal. I think chalk checks for terminal capabilities before using color.

```sh
/tmp/bar main*
❯ cat index.js
const chalk = require('chalk');
console.log(chalk.green('hello'));

/tmp/bar main*
❯ cat .husky/pre-commit
#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

node index.js && exit 1

/tmp/bar main*
❯ git commit --allow-empty
hello # <- it's green
husky - pre-commit hook exited with code 1 (error)
```

**Comment by Milo123459** [comment]
I'm using powershell with starship.rs

**Comment by typicode** [comment]
I wonder if setting an env variable would help:
https://github.com/chalk/supports-color#info

**Comment by lebron112** [comment]
> I wonder if setting an env variable would help:
> https://github.com/chalk/supports-color#info

how to use?
