### ISSUE TITLE
npm package has postinstall in package.json and failed in project

### ISSUE THREAD

**Issue by itstueben** [typicode/husky#860]
I have a problem in my npm package. I update dit to husky v5 to the following packages.json
```
 "scripts": {
    ....
    "postinstall": "husky install",
    "prepublishOnly": "pinst --disable",
    "postpublish": "pinst --enable"
  },
```

If i tried to install my npm package in myRealWorld App i get an error for postinstall.
On WIndows:
```
> mypackage@1.7.46 postinstall ...package
> husky install
        throw new Error(".git can't be found");
```
In CI: 
```
husky install
sh: 1: husky: not found
```

What do i wrong in my npm package repo? I dont want to postinstall in other project that consume my package but on local development in the package repo it should run the postinstall on npm i

edit: formatting

**Comment by typicode** [comment]
Hi,

There seems to be 2 issues.

In CI, husky isn't found. I would check if only production dependencies are installed.
If you don't want to install husky in CI, see https://typicode.github.io/husky/#/?id=disable-hooks-in-ci

In your App, did you publish your package on npm?

**Comment by nenadfilipovic** [comment]
@typicode I don't think is-ci is needed in CI environment, this is from my CI

> ***@0.0.1 postinstall /usr/app/integration
| > husky install
| 
| husky - not a Git repository, skipping hooks installation

Husky is now correctly seeing that there is no git and skips installation.

**Comment by typicode** [comment]
@nenadfilipovic you're right, thanks.

**Comment by typicode** [comment]
By the way, `prepare` seems to be actually a better hook than `postinstall` when using npm, pnpm or yarn v1. Docs have been updated since this issue.
