### ISSUE TITLE
commitlint does not work with 5.0.9

### ISSUE THREAD

**Issue by ethanneff** [typicode/husky#861]
Following this guide, https://typicode.github.io/husky/#/?id=husky_git_params-ie-commitlint- does not run the command.

**Comment by Milo123459** [comment]
Hi. I use commitlint with 5.0.9 and I'll send how I do it.
```bash
#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '$ commit-msg' 
echo '$ yarn commitlint -e $1'
yarn commitlint -e $1```

**Comment by PizzaPete** [comment]
I've got problems too. I'm getting: `yarn: command not found`. Although I'm using yarn (v1.22.5), I've got the same result when I use npx instead of yarn.

**Comment by Milo123459** [comment]
Is @commitlint/cli installed?

**Comment by PizzaPete** [comment]
Thanks for your quick response @Milo123459.

When I'm running: `git commit -m 'my commit message'` it does work. Strangely it doesn't seem to work with my Git GUI which is Git-Fork.

**Comment by typicode** [comment]
@PizzaPete are you using `nvm` or equivalent. It might be a PATH issue:
https://typicode.github.io/husky/#/?id=command-not-found

@Milo123459  thanks for the help :+1:

**Comment by Milo123459** [comment]
No problemo. Glad we could figure it out!

**Comment by PizzaPete** [comment]
@typicode thanks, that dit the trick. Missed it while reading the documentation.

**Comment by leepowelldev** [comment]
I was having problems getting commitlint to work using `npx` as per the docs ... I kept getting commitlint's help output.

In the end I created a npm script in my `package.json` file and called that instead which seemed to work.

Any ideas why the npx approach wasn't working?

**Comment by BePo65** [comment]
In the husky documentation about [HUSKY_GIT_PARAMS](https://typicode.github.io/husky/#/?id=husky_git_params-ie-commitlint-) the example is `npx --no commitlint --edit $1`.

I didn't find a `--no` option in npx documentation [(https://github.com/npm/npx#readme)](https://github.com/npm/npx#readme) only `--no-install`.

Did they miss the `--no` option in the npx docu or is this just a typo in the husky docu (and the reason why @ethanneff has problems?

**Comment by typicode** [comment]
@BePo65 you can find it on npmjs.com

https://docs.npmjs.com/cli/v7/commands/npm-exec#compatibility-with-older-npx-versions

> The --no-install option is deprecated, and will be converted to --no

@leepowelldev are you on Windows?

**Comment by leepowelldev** [comment]
@typicode - Mac 11.2.1

**Comment by BePo65** [comment]
ok, I see. I am on npm V6 as Angular (according to their development team) only supports node LTS (by now this means V14) and I had problems with node V15 (not related to husky :-).

**Comment by lgaticaq** [comment]
I fix error using this in `.husky/commit-msg`:
```sh
#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npx --no -- commitlint --edit $1
```

**Comment by chalkygames123** [comment]
Hi @typicode.

The `--no` option doesn't seem to be implemented yet (I was confused too 😅).

Note that they say it "**will** be converted to `--no`".

So the `--no` in the @lgaticaq's example doesn't do anything because npm just ignores unknown options, and thus npx prompts if you attempt to run an uncached package.

For example, running `npx serve` will output:

```
% npx serve
Need to install the following packages:
 serve
Ok to proceed? (y)
```

and `npx --no-install serve` will output:

```
% npx --no-install serve
npm ERR! canceled
```

So we should revert to `--no-install`.

**Comment by chalkygames123** [comment]
Alternatively, we can also use a `-c` or `--call` options like `npx -c 'commitlint --edit "$1"'`. It just fails if the package is not installed locally.

**Comment by chalkygames123** [comment]
BTW, about the cache location of npx: https://stackoverflow.com/questions/63510325/how-can-i-clear-the-central-cache-for-npx

**Comment by typicode** [comment]
Thanks all for the feedback! :+1: Docs have been reverted to `--no-install` :)
