### ISSUE TITLE
commitizen does not work with 5.0.9

### ISSUE THREAD

**Issue by paulmboyce** [typicode/husky#862]
Hi guys, 

Husky Version 5 breaks the pre-commit-message hook for Commitizen.

I think this is a common problem for Husky V5 migration. 

(If like me you are used to simply adding husky and commitizen to a project without knowing of the changes in new Husky 5, then this may save you time.)

## SOLUTION (1) - Husky v4:

**STEP 1:** Roll back to Husky 4.3.8 

## SOLUTION (2) - Husky v5:

**STEP 1:** Replace the following hook in package.json:

( This is the Husky Version 4 hook specified by commitizen, see:  [https://github.com/commitizen/cz-cli](https://github.com/commitizen/cz-cli) )
```
"husky": {
		"hooks": {
			"prepare-commit-msg": "exec < /dev/tty && git cz --hook || true"
		}
	},
```

**STEP 2:** With a external hook by executing the following (which create a Husky V5 hook in a separate file):
```
npx husky add .husky/prepare-commit-msg "exec < /dev/tty && git cz --hook || true"
```

You hook will not be located here:

```
.husky/prepare-commit-msg
```

**Comment by typicode** [comment]
Hi @paulmboyce,

Thanks for the report and sharing solutions :+1: 
With the solutions provided can this issue be closed?

**Comment by paulmboyce** [comment]
Hi @typicode - 
Thanks for your kind words 👍
YES, with the solution provided, this can be closed.

**Comment by kylemh** [comment]
> You hook will not be located here:

@paulmboyce did you mean will "NOW" be located?

**Comment by paulmboyce** [comment]
Hi @kylemh ,

Oops, yes! It was a typo,   I meant "will NOW be located".   (I have updated my entry above).

As to your problem, I believe "cz" is commitizen  CLI tool, so it looks like you do not have commitizen installed correctly. 

To install:
```
$ npm install -g commitizen
```

SEE commitizen instructions here for more info: 
https://www.npmjs.com/package/commitizen

Hope that helps you Kyle!

**Comment by kylemh** [comment]
I had commitizen installed. My only workaround was to locally install `git-cz` despite [documentation](https://github.com/commitizen/cz-cli#if-your-repo-is-not-commitizen-friendly) suggesting it wasn't necessary and it was working for me fine before this update.

**Comment by Jack-Barry** [comment]
I was able to resolve this by running the [`husky-4-to-5`](https://github.com/typicode/husky-4-to-5) migration tool in an existing project (encouraged by the [husky migration docs](https://typicode.github.io/husky/#/?id=migrate-from-v4-to-v5)), which basically performs the steps described by @paulmboyce . It copied over my hooks from the `husky` section of `package.json` into applicable files in `.husky`, so the section in `package.json` is no longer needed.

I avoided the global install and got this working by switching `git cz` to `npx cz` in the `prepare-commit-msg` hook:

```
exec < /dev/tty && npx cz --hook || true
```

### Specs

| Module | Version(s) |
|:-:|:-:|
| `husky` | `4.3.8` -> `5.1.1` |
| `commitizen` | `4.2.3` |
| `cz-emoji` | `1.3.1` |

Working on Windows 10 and WSL Ubuntu `20.04`

**Comment by kylemh** [comment]
Just wanna point out that `npx cz` is a similar workaround to installing `git-cz` locally for a project. Neither of which should need to happen.

**Comment by daviddelusenet** [comment]
@kylemh I completely followed your step-by-step guide and I'm still running into issues. When I run `git commit` I get the following error:

```
error: unknown option `hook'
```

**Comment by ricovilela** [comment]
In my case I use Yarn and had some occasional difficulties using Husky with 'commit-msg', 'pre-commit' and 'prepare-commit'.

Guidance in official documentation is not effective.

After hours I discovered that in most of the commands used in Husky scripts and I have to add "Yarn" to execute the commands.

It looked like this:
**[.husky / pre-commit]**
#! / bin / sh
. "$ (dirname" $ 0 ") / _ / husky.sh"

yarn lint-staged

**[.husky / commit-msg]**
#! / bin / sh
. "$ (dirname" $ 0 ") / _ / husky.sh"

yarn commitlint --edit $ 1

**[.husky / prepare-commit-msg]**
#! / bin / sh
. "$ (dirname" $ 0 ") / _ / husky.sh"

exec </ dev / tty && yarn cz --hook || true

As soon as I run "git commit" it runs Husky perfectly.

**Comment by lucaslamar** [comment]
I need to migrate from version 4 to 6, I ran the commands and put
```
#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

exec < /dev/tty && git cz --hook || true
```
but when executing the command  `git commit`  it happened
![image](https://user-images.githubusercontent.com/37666623/120342154-e5895900-c2cd-11eb-9a93-0dad56b1ae05.png)

**Comment by zorgick** [comment]
@lucaslamar you won't be able to surpress default behavior of `git commit` with the comand of yours (if no message is provided, git will open a default editor to let you type a message - in your case it is vim)

Use the answer above by @ricovilela to trigger commitizen on git commit

**Comment by miguelsmuller** [comment]
someone has version 7.0.1?
I'm having the same problem with @lucaslamar 
My interactive terminal opens. ask the questions. but instead of committing at the end it opens the text editor.
my hook file is the same as what @zorgick put above.

**Comment by ricovilela** [comment]
@miguelsmuller - I had the same problem in another pc and the solution consist in not resuming commit command but create simple text for example
`git commit -m 'a'`
This method dont open the editor and show the options of Husky on next step.

> someone has version 7.0.1?
> I'm having the same problem with @lucaslamar
> My interactive terminal opens. ask the questions. but instead of committing at the end it opens the text editor.
> my hook file is the same as what @zorgick put above.

**Comment by miguelsmuller** [comment]
do you have any repo for me to take a look at?
can you tell me how your **prepare-commit-msg** file looks like ?

**Comment by miguelsmuller** [comment]
really @ricovilela. it worked that way.
But now the problem arises.
I can't create an alias in my **.gitconfig** file for the **git commit** command to omit the parameter (like **_commit = -m "a"_**) because not every project I have has husky and commitzen.

@paulmboyce it is possible to reopen the issue since it is not working properly in this version 7.0.0 ??

Does anyone have any suggestions for a palliative measure to get around this problem???

I was even in doubt whether the solution should come from this project or from the commitizen (commitizen/cz-cli#839)

**Comment by miguelsmuller** [comment]
Hello everybody. Can anyone give feedback if there is an intention to present a solution to this situation?
@typicode

**Comment by zorgick** [comment]
@miguelsmuller It is unclear what you want to achieve. If you want to add an alias  for `git commit -m 'a'~ per single repo, execute this command in your repo:
```sh
git config --local alias.cm "commit -m 'a'"
# use it 
git cm
```

This will create an alias in ./.git/config, that will work only in this repo

**Comment by ZxBing0066** [comment]
I have the same problem 🥲, is there any solution better then `alias commit with a default message`, I think it's a hack.

And after add the hook, run `npx cz` will call cz twice.
