### ISSUE TITLE
Invalid package file from stdin

### ISSUE THREAD

**Issue by be-cosmin-neculau** [typicode/husky#863]
Hi, 

I've upgraded Husky to version 5 on a couple of projects and I'm getting the following error when trying to push: 

![image](https://user-images.githubusercontent.com/78748223/107526077-23982b00-6bc0-11eb-9fac-99f91bf95d7f.png)

What am I doing wrong? Thanks in advance!

**Comment by typicode** [comment]
Hi @be-cosmin-neculau,

What does your pre-push hook do? Can you share some code to reproduce?

**Comment by be-cosmin-neculau** [comment]
Hi @typicode,

I'm trying to run ncu. It appears I'm getting this only on ncu.

**Comment by typicode** [comment]
Git `pre-push` receives `refs` through `stdin` which seems to confuse `ncu`. I would check `ncu` options, maybe try to use `ncu --packageFile <path to package.json>`?

**Comment by be-cosmin-neculau** [comment]
Yep, this fixed the issue, thanks!
