### ISSUE TITLE
Downgrade from version 5.x to version 4.x

### ISSUE THREAD

**Issue by roberto-sobachi-cko** [typicode/husky#865]
I tried husky version 5.x on one of my projects, then I decided to downgrade to version 4.x. I removed all new files created by husky 5.x (`.husky/`) and reinstalled husky 4.x with `yarn`, but husky doesn't seem to trigger `pre-commit` or `pre-push` anymore.

**Comment by jakejarvis** [comment]
I had to run `git config --unset core.hooksPath` (on top of everything else you've already reverted) and v4 worked again. https://github.com/typicode/husky-4-to-5#clean

**Comment by roberto-sobachi-cko** [comment]
Thanks @jakejarvis 🙏🏻

Still not ideal if the code is maintained by some developers. Maybe it works on `postinstall`?

**Comment by typicode** [comment]
In case other people find this issue, there are downgrade instructions in v4 and v5 docs:
https://typicode.github.io/husky/#/?id=uninstall

Husky has a `preuninstall` scripts with `git config --unset core.hooksPath` that is run automatically by `npm` but needs to be run manually with `yarn`.

**Comment by Zannisdf** [comment]
Is v4 still going to be supported in the future? V5 provides a much worse dev experience, is much harder to configure and it does not provide any real benefits.
