### ISSUE TITLE
git commit hooks never get created when husky v5 is installed

### ISSUE THREAD

**Issue by DouglasDev** [typicode/husky#866]
Installing husky 5 with `npm i husky` doesn't create the commit hooks when used with git version 2.20.1, node v14.15.4, and npm v6.14.10 on mac in a new project. I confirmed this by opening the .git folder for my project and checking the hooks folder, and it was unchanged after installation. I think I was having the same issue as several other people in this issue: https://github.com/typicode/husky/issues/326

I spent hours trying all the methods listed in that issue and the only one that worked was installing husky@4.2.3 which fixed the problem immediately, leading me to believe that there was a bug introduced in version 5. Please let me know if you need any other details.

**Comment by typicode** [comment]
Hi @DouglasDev,

It's normal behaviour with v5. You need to run `npx husky install` and create hooks with `npx husky add .husky/pre-commit ...`.

You can check that it's working by creating a new folder and running the following commands:

```sh
$ cd /tmp
$ mkdir test && cd test
$ git init && npm init -y && npm install husky -D

$ npx husky install
$ npx husky add .husky/pre-commit "echo hello"
$ git add package.json
$ git commit -m "test: hello should be printed"
```

**Comment by jimyhdolores** [comment]
@typicode  the command you provide does not work

![image](https://user-images.githubusercontent.com/10909792/107784176-22c6dc80-6d19-11eb-9b80-0299e1688e8e.png)

version husky ^5.0.9

**Comment by DouglasDev** [comment]
I will take your word for it but that seems like a very confusing change in the installation process since none the dozens of tutorials on the internet on how to add husky to a project (for example the create react app docs) mention this.

**Comment by WendelSantosD** [comment]
husky@4.2.3 works

**Comment by csantos1113** [comment]
I have the same issue!
I upgraded to `husky@5.0.9` and just noticed my `pre-commit` and `pre-push` hooks are not being triggered.

They worked well with `husky@4.3.8`

**Comment by KrisGerhard** [comment]
Could be related to https://github.com/typicode/husky/issues/869. Try the fix provided in this issue.

**Comment by galilmori** [comment]
I have the same issue since i upgraded to 5.0.9, i am using lint-staged 10.5.4

**Comment by BePo65** [comment]
In windows environments the same problem exists (see #871). In that case it can be solved by calling the locally installed version of husky (`.\node_modules\.bin\husky add .husky/pre-commit "echo hello"`).
Seems to me like calling husky with npx has a path problem.

**Comment by Pezmc** [comment]
@typicode I think people are likely just missing that Husky 5 doesn't read the config found in package.json anymore

To setup lint-staged with husky 5, just run:

```bash
npx husky add .husky/pre-commit "yarn run lint-staged"
# or
npx husky add .husky/pre-commit "npx lint-staged"
```

**Comment by BePo65** [comment]
for me the problem was npx. I am on a windows 10 machine with node LTS (V14 with npm v6).
Using the command from the documentation (the same as @typicode  mentioned above) just resulted in the husky help in my command window. Only using the husky installation in my project solved the issue (`.\node_modules\.bin\husky add .husky/pre-commit "echo hello"`).

That the husky configuration change with V5 is clearly described in the documentation (and has a longer discussion in an issue :-)

**Comment by gmonte** [comment]
I have the same issue with node v12.20.1, yarn v1.22.10, macOS v11.2.
Husky v4.2.3 work fine to me.

**Comment by typicode** [comment]
Apparently it's a bug with npx on Windows, it seems to be fixed in npm v7.5.4

**Comment by SuperITMan** [comment]
Same issue here, we're still using npm@6 and the command `npx --no` is not yet available.
On my side, I added 2 scripts in my "package.json" file : 
```json
"scripts": {
  "commitlint": "commitlint",
  "lint-staged": "lint-staged",
}
```

And thanks to that, my 2 files (with shebang as proposed here: https://github.com/typicode/husky/issues/864#issuecomment-778857821) are now triggered when I do `git commit -m "my commit message"`

".husky/commit-msg":
```sh
#!/usr/bin/env bash

npm run commitlint -- --edit $1
```

".husky/pre-commit":
```sh
#!/usr/bin/env bash

npm run lint-staged
```

If it can help someone 😊 

Thanks for this upgrade @typicode !

**Comment by jordanbtucker** [comment]
@typicode Can you point me to the bug in npx?

**Comment by typicode** [comment]
> @typicode Can you point me to the bug in npx?

I don't have a link sorry. However a temporary fix was provided here before the official one https://github.com/typicode/husky/pull/873 (I did some tests too, and I think it's fixed in npm v7.4).

**Comment by typicode** [comment]
Recently, a new command has been introduced to simplify setup.

You can now just run:

```
npm i husky -D
npx husky init
```

`package.json` will be automatically updated, a sample `pre-commit` will be created and configured to run `npm test` on pre-commit.

I hope it makes things more straightforward :)

Docs have been updated. Also if you're using npm, pnpm or yarn v1, you can just have `prepare` script instead of the more complex `postinstall [ + pinst ]` combo.

**Comment by gaspard-hk** [comment]
I added backslash as a workaround.
npx husky add .husky/pre-commit \"npm run test\"

**Comment by pakyinwww** [comment]
I added backslash as a workaround.
npx husky add .husky/pre-commit "npm run test"

**Comment by nguyentrancong** [comment]
1. npx husky install
2. npx husky add .husky/pre-commit "npm run lint-staged"

I did it, It work for me, can you try it. lucky
![image](https://github.com/typicode/husky/assets/19172262/a5aba513-d14d-44c1-8653-844767dc0dda)
