### ISSUE TITLE
husky postinstall script does not work with `yarn install --production`

### ISSUE THREAD

**Issue by foray1010** [typicode/husky#867]
I am using husky 5.0.9, I have a postinstall script as suggested `husky install`
But it won't work in the CI because I was building docker image for production, I install with `yarn install --production`, therefore:

1. husky is not installed as it is a dev dependency as suggested in guideline
2. the postinstall `husky install` will fail due to `husky: not found`

I fixed it by `command -v husky >/dev/null && husky install || exit 0`, but it is not cross platform, I would like to ask if you know a better way to do it, and would be nice if we can update the documentation

**Comment by nenadfilipovic** [comment]
I usually don't install dependencies in my CI with --production, I use just npm ci.

**Comment by daniielgak** [comment]
Try to use in your CI  the tag `--ingnore-scripts`. For what I've seen, it's not possible to disable only postinstall scripts.

So `yarn install --production --ignore-scripts` should work for installing the dependencies and not running the postinstall yarn script.

**Comment by nenadfilipovic** [comment]
That will disable scripts for all packages you install and it will even disable your scripts like npm run ...

**Comment by nicolas-goudry** [comment]
Use [is-ci](https://github.com/watson/is-ci) to condition `husky install` execution: 

```json
// package.json
{
  "scripts": {
    "postinstall": "is-ci || husky install"
  }
}
```

This is in the [Disabling hooks in CI](https://typicode.github.io/husky/#/?id=disable-hooks-in-ci) section of the doc.

Furthermore, I agree with @nenadfilipovic , you could use `npm ci` or `yarn install --frozen-lockfile` in order to have access to dev dependencies. What if you would need to run your linter? Or tests? Using production flag will not allow you to do so.

**Comment by foray1010** [comment]
@nicolas-goudry To be clear, I still use husky in CI, such as linter
But I (and presume many others) do not need dev dependencies when building docker image for production usage, where we would want minimal image size and less unused code.
So, neither `npm ci`, `yarn install --frozen-lockfile` nor `is-ci` work in this case

**Comment by nicolas-goudry** [comment]
You could add a step to your CI job where you do not need dev dependencies, just before the install step:

`npx --no-install pinst --disable`

This will disable the postinstall script. You can enable it back with `--enable`.

Would this work for you?

**Comment by nenadfilipovic** [comment]
For production image create multi stage dockerfile.

**Comment by foray1010** [comment]
Thank you @nicolas-goudry and @nenadfilipovic !

I am able to fix it by adding this line in Dockerfile, the image size is still the same as before

```diff
+ RUN npx --quiet pinst --disable
RUN yarn install --frozen-lockfile --production
```

**Comment by pinalbhatt** [comment]
With Husky 6 its using prepare script and adding --ignore-scripts worked for me 
`
RUN npm ci --only=production --ignore-scripts
`

**Comment by arlukin** [comment]
I solved it with this, and then I don't copy my .husky folder to the docker image

`"postinstall": "[ -d '.husky' ] && husky install || true",`
