### ISSUE TITLE
#!/bin/sh shebang in hooks

### ISSUE THREAD

**Issue by jdbruijn** [typicode/husky#869]
**Context**
Please describe your issue and provide some context:
- Terminal or GUI client (PowerShell, Git Bash, GitHub Desktop, ...)
  Not particular interesting, but on Linux with `zsh`.
- If applicable, content of the failing hook
  n/a
- If possible, minimal steps to reproduce the issue
  n/a

First of all, I'm no expert at shell scripts. As the hooks are shell scripts, shouldn't they start with a shebang line? I'd think `#!/bin/sh`, just like is used in the generated `husky.sh` script. The scripts are executed either way, but I was thinking the scripts should have a shebang line.

If they indeed need a `#!/bin/sh` shebang line I'd be happy to PR with updated examples in the docs.

**Comment by typicode** [comment]
You're right. In the docs, I'm using `# ...` instead of the full hook script to focus on the command rather than the parts generated by `husky add ...`. But `husky add ...` should create a hook with the shebang , a small husky script and the command provided.

Maybe I'll modify that. Thanks for the feedback.

**Comment by jdbruijn** [comment]
I understand where you're point of view as well. I created my scripts manually so didn't see what `husky add ...` would be creating. I personally don't think adding the shebang makes the examples that much longer or harder to understand.

I understand both sides, so feel free to close this issue if you won't be updating the docs for this. If I can do anything for this, let me know!
