### ISSUE TITLE
Husky v5 add command fails in Windows using npx

### ISSUE THREAD

**Issue by aarongoldenthal** [typicode/husky#871]
When using the `npx husky` command in Windows (cmd or PowerShell, using single or double quotes), the arguments including the desired hook script are split on spaces, so the command fails with too may arguments.  When running in Linux or in Windows by executing the husky bin command directly, the add command is properly processed.

An example adding `console.log(process.argv)` before the arguments are processed.

In Linux

```sh
/app # npx husky add .husky/pre-commit "npm test"
[
  '/usr/local/bin/node',
  '/app/node_modules/husky/lib/bin.js',
  'add',
  '.husky/pre-commit',
  'npm test'
]
add
created .husky/pre-commit
```

In Windows

```sh
PS C:\mymodule> npx husky add .husky/pre-commit "npm test"
[
  'C:\\Program Files\\nodejs\\node.exe',
  'C:\\mymodule\\node_modules\\husky\\lib\\bin.js',
  'add',
  '.husky/pre-commit',
  'npm',
  'test'
]
Usage

  husky install [dir] (default: .husky)
  husky uninstall
  husky add <file> [cmd]

Examples

  husky install
  husky install .config/husky

  husky add .husky/pre-commit
  husky add .husky/pre-commit "npm test"
  husky add .config/husky/pre-commit "npm test"

PS C:\mymodule>> .\node_modules\.bin\husky add .husky/pre-commit "npm test"
[
  'C:\\Program Files\\nodejs\\node.exe',
  'C:\\mymodule\\node_modules\\husky\\lib\\bin.js',
  'add',
  '.husky/pre-commit',
  'npm test'
]
[ '.husky/pre-commit', 'npm test' ]
created .husky\pre-commit
```

**Comment by typicode** [comment]
Seems to be fixed in npm v7.5.4

**Comment by vladkasianenko** [comment]
I still have error.

![image](https://user-images.githubusercontent.com/14053728/113318287-fee74680-9318-11eb-904a-ba3e4b21e5e1.png)

``` json
"@commitlint/cli": "^12.0.1",
"@commitlint/config-conventional": "^12.0.1",
"husky": "^6.0.0",
```

**Comment by typicode** [comment]
As a temporary workaround, could you try:

```
npx add .husky/commit-msg
```

Then manually add `npx commitlint --edit $1`

**Comment by vladkasianenko** [comment]
@typicode, it's not working.

**Comment by vladkasianenko** [comment]
So, I tried one more time and everything went OK. Strange.

**Comment by pj** [comment]
Had the same problem on macOS, upgrading npm to the latest version seemed to fix the issue.

**Comment by RaccoonCode96** [comment]
`npx husky-init`

**Comment by bobbylight** [comment]
If you're stuck on an old version of node for reasons out of your control, you can work around this by bypassing npx entirely:

```
./node_modules/.bin/husky add .husky/pre-commit "your-pre-commit-hook"
```

**Comment by Rob4226** [comment]
Doesn't work on Windows:
```powershell
PS G:\git\test-husky-changelog-gen> npx husky add .husky/commit-msg "npx --no-install commitlint --edit '$1'"
Usage:
  husky install [dir] (default: .husky)
  husky uninstall
  husky set|add <file> [cmd]

PS G:\git\test-husky-changelog-gen> npm -v
6.14.13
```

**Comment by Thiago-cez** [comment]
> npx husky-init

cool, it's worked for me! thanks!!

**Comment by Ajeossi-Mz** [comment]
For windows：node_modules/.bin/husky add .husky/commit-msg 'npx --no-install commitlint --edit "$1"'
 --> https://typicode.github.io/husky/#/?id=automatic-recommended

**Comment by lisonge** [comment]
still not working at husky@7.0.0

**Comment by cscleison** [comment]
i second what @lisonge reports. using `npx` on husky 7 on windows does not work. only works when i specify the `node_modules` bin path

**Comment by Cubone7** [comment]
> `npx husky-init`

Thanks!
It's worked for me

**Comment by mcclaim** [comment]
> 

Thank you, after this command `pre-commit` file created and all ok!

**Comment by mcclaim** [comment]
> `npx husky-init`

Thank you, after this command pre-commit file created and all ok!
