### ISSUE TITLE
Husky precommit not always called in monorepo in v5.0.9

### ISSUE THREAD

**Issue by najibla** [typicode/husky#872]
**Context**
Using MacOs Big Sur    -    Husky >=4 (5.0.9)   -   yarn 1.22.10 

I am using husky >=4 (5.0.9) in a monorepo environment.  

The content of the pre-commit hook is as follow
```
  "husky": {
    "hooks": {
      "pre-commit": "lerna run --concurrency 1 --stream precommit --since HEAD --exclude-dependents"
    }
  }
```

I tried with both bash and fish as shells, and both just skip the precommit hook. Sometimes I clean node_modules and reinstall the dependencies (`yarn install`) and it works, but not always.

I also tried `rm -rf .git/hooks/` but it also didnt help.

**Comment by joneff** [comment]
The same happens with non-lerna commands: 

```json
"husky": {
    "hooks": {
      "pre-commit": "npm run lint && npm run test"
    }
}
```

* husky 5.0.9
* node 12.1.0
* npm 6.14.11
* macos catalina 10.15.7

Had to downgrade t0 4.3.8

**Comment by typicode** [comment]
Hi,

There are breaking changes with v5. Configuring hooks in `package.json` or `.huskyrc` is not supported in v5. 

See https://typicode.github.io/husky/#/?id=install or for simple migration, you can use https://github.com/typicode/husky-4-to-5

**Comment by najibla** [comment]
Thanks. That seems to have fixed it.

**Comment by typicode** [comment]
Great :)
