### ISSUE TITLE
How can we share husky config in v5?

### ISSUE THREAD

**Issue by JounQin** [typicode/husky#874]
In v4, although we don't have official shared config support, but we can use:

```js
// .huskyrc.js
module.exports = require('your-shared-config')
```

But in v5, it seems that it's not possible anymore, it blocks me to upgrade to v5 at the meantime.

**Comment by typicode** [comment]
Currently, it's not possible in an easy way I guess. I have some ideas though to support it later :+1:

**Comment by JounQin** [comment]
So bad.

**Comment by JounQin** [comment]
ping

**Comment by adamtay** [comment]
@typicode - do you have any updates on this topic?

For organizations with **several dozen** of applications, not being able to share configurations is a huge blocker for us in order to upgrade to the latest version.

**Comment by JounQin** [comment]
I've migrated to [simple-git-hooks](https://github.com/toplenboren/simple-git-hooks) instead.

**Comment by astorije** [comment]
Hi @typicode!
 
> Currently, it's not possible in an easy way I guess. I have some ideas though to support it later 👍

We are still stuck on v4 for that exact reason, what would be your recommendation to share configs across multiple (non-monorepo) repositories at this time?

Thank you!
