### ISSUE TITLE
NPM page should not show MIT license

### ISSUE THREAD

**Issue by pmer** [typicode/husky#877]
Hello, this is just an FYI that the license listed on https://www.npmjs.com/package/husky is out of date.

![Screen Shot 2021-02-16 at 7 07 56 PM](https://user-images.githubusercontent.com/107998/108150933-75dabf80-708a-11eb-8733-bed09ec2d35e.png)

**Comment by typicode** [comment]
Hi @pmer,

Thanks, it's an issue on their side, I've reported the issue to npm support (https://github.com/typicode/husky/issues/807).

**Comment by pmer** [comment]
Oops, I missed the old issue in my search to see if you had an issue for this already. Sorry about that! :)

**Comment by typicode** [comment]
No worries :)
