### ISSUE TITLE
Regression of issue #452

### ISSUE THREAD

**Issue by jimisaacs** [typicode/husky#878]
Pretty sure there is a regression of issue #452 because any an all methods of upgrading fails with the following error message when trying to run it from any subdirectory within my git repo:
```
.git can't be found
```

**Comment by typicode** [comment]
Hi @jimisaacs 

Husky 5 needs to be run at the same level as `.git`. Maybe you're in the following case:
https://typicode.github.io/husky/#/?id=custom-directory

Let me know if it's something else.
