### ISSUE TITLE
Update hook is in the wrong directory

### ISSUE THREAD

**Issue by pajtai** [typicode/husky#88]
Thanks for this great npm. Pre-commit works great, but having issue with an update hook.

I added some echo statements to `.git/hooks/update` and it looks like pwd is showing `project/.git` instead of `project`:

so the following at `.git/hooks/update` is on the remote (Ubuntu) and is correctly triggered after a git push from my local:

```
#!/bin/sh
# husky
cd .
echo $(pwd) 
[ -f package.json ] && cat package.json | grep -q '"update"\s*:'
[ $? -ne 0 ] && exit 0
```

however the echo above shows `/home/ubuntu/project/.git`

    $ git push -f user@my.remote.com:/home/user/project HEAD:develop       
    remote: /home/user/project/.git    

Not sure why the dir is different in this case and what the best fix would be that wouldn't affect the other hooks.

Manually changing `cd .` to `cd ..` fixes the issue for this hook, but I assume it would break the others.

**Comment by pajtai** [comment]
In terms of the final script, something like the following would work:

```
if [ "${PWD##*/}" = ".git" ]; then cd ..; else cd .; fi
```

I'll play around with how to generate that for [normalizedPath](https://github.com/typicode/husky/blob/master/src/index.js#L52)

**Comment by typicode** [comment]
Thanks for the feedback and suggested fix 👍 
Closing as next version is a complete rewrite and doesn't use the same code
