### ISSUE TITLE
Husky install fails in NestJS monorepo

### ISSUE THREAD

**Issue by svorcan** [typicode/husky#880]
We are trying to setup Husky and pre-commit hooks in [NestJS monorepo](https://docs.nestjs.com/cli/monorepo).

`package.json` is not located in the root of the Git repo, but under `/src/services`. 

When the following commands are run, an error is encountered:
```
yarn add husky --dev
yarn husky install
```

```
Error: .git can't be found
    at Object.install (/Users/stalker92/JSProjects/my-project/src/services/node_modules/husky/lib/commands/install.js:20:15)
    at Object.<anonymous> (/Users/stalker92/JSProjects/my-project/src/services/node_modules/husky/lib/bin.js:43:19)
```

From the brief `install.ts` inspection seems that it won't install unless `package.json` is in the root level of the Git repo. 
Is there a way to work around this limitation?

**Comment by novaknole** [comment]
@svorcan Hi, 

how have you solved this ?

**Comment by svorcan** [comment]
> @svorcan Hi,
> 
> how have you solved this ?

I did, but to be honest I do not remember how. :(
