### ISSUE TITLE
GIT version mismatch

### ISSUE THREAD

**Issue by ankurmakadia** [typicode/husky#882]
I have a cloudways server with AWS instance
and their all server comes with the Debian 9 OS.  
Node v14 installed.
And Cloudways server told me that their all servers are having Debian 9 OS only. 

They mentioned:
Unfortunately, it seems that Git 2.11.0. is currently the latest available version for the Operating System on the server we have.

git is already the newest version (1:2.11.0-3+deb9u7).

The server is running Debian 9.13
There might be a newer git version available in some repositories, but due to our custom server configuration, it is currently not possible to have a greater version of a git of 2.11.0.
Git v2.11.0 is fully supported by the current Debian OS version 9.
Git is available on the server, but not version 2.13.0. I suggest checking this with theme developers to see if there is an alternative way of installation.

And I think the theme package needs GIT version 2.13.0
What do you suggest?
How can I install the ScandiPWA theme with the current Debian OS 9.13 and GIT version 2.11.0?

**Comment by typicode** [comment]
Husky v4 only supports Git 2.13+ but husky v5 supports Git 2.9+
