### ISSUE TITLE
huskyrc with nvm causing command not found errors

### ISSUE THREAD

**Issue by mrwillis** [typicode/husky#883]
**Troubleshoot**
Before creating an issue, please check:
https://typicode.github.io/husky/#/?id=troubleshoot

If you're migrating from husky 4, see:
https://typicode.github.io/husky/#/?id=migrate-from-v4-to-v5

**Context**
Please describe your issue and provide some context:
- Terminal or GUI client (PowerShell, Git Bash, GitHub Desktop, ...)
Visual Studio Code
- If applicable, content of the failing hook
```
#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
npm run compile
npm run lint

```

- If possible, minimal steps to reproduce the issue

Ubuntu 18. I have `~/.huskyrc` looking like this
```
. ~/.nvm/nvm.sh
```

and I'm using `nvm@0.35.3`

But when I run any hook it seems like `. ~/.nvm/nvm.sh` is still not adding to the PATH causing 

`.husky/pre-commit: 4: .husky/pre-commit: npm: not found`

The only thing that works is for example in `./husky/pre-commit`

```
#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
PATH=$PATH:$HOME/.nvm/versions/node/v12.18.3/bin
npm run lint
```

which is of course incorrect

Thank you!

**Comment by mrwillis** [comment]
Interestingly, if I do

```
# ~/.huskyrc 
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
```

as per 

https://www.npmjs.com/package/husky/v/4.3.0

it does work.

**Comment by typicode** [comment]
Interesting, I've updated docs. I suppose it's better to have `NVM_DIR` defined.
Thanks for the issue.
