### ISSUE TITLE
del-cli command not found on npm update

### ISSUE THREAD

**Issue by Cherviakov** [typicode/husky#887]
Linux ubuntu 16.04
Node v15.0.1
Npm 7.0.3
husky 5.0.6

error in the end of npm update command execution:
```sh
/node_modules/husky
command failed
command /bin/bash -c npm run build && node lib/bin install
husky@5.1.1 prebuild
del-cli lib
/bin/bash del-cli: command not found
```

**Comment by Cherviakov** [comment]
Tried to install globally del-cli for this one time, but next got following error, now with typescript:
```sh
npm ERR! path /node_modules/husky
npm ERR! command failed
npm ERR! command /bin/bash -c npm run build && node lib/bin install
npm ERR! > husky@5.1.1 prebuild
npm ERR! > del-cli lib
npm ERR! 
npm ERR! 
npm ERR! > husky@5.1.1 build
npm ERR! > tsc
npm ERR! 
npm ERR! Version 4.1.3
npm ERR! Syntax:   tsc [options] [file...]
npm ERR! 
npm ERR! Examples: tsc hello.ts
npm ERR!           tsc --outFile file.js file.ts
npm ERR!           tsc @args.txt
npm ERR!           tsc --build tsconfig.json
```

**Comment by hdmr14** [comment]
same issue here.

Linux Ubuntu 20.04
Node v14.15.5
npm 7.5.4
husky 5.1.1

**Comment by typicode** [comment]
Hi,

The `build` script shouldn't run when you install `husky`. May I ask the command you used to get this error message and where you've run it?

**Comment by Cherviakov** [comment]
I used npm update, justed wanted to udpate deps of my project.

**Comment by Cherviakov** [comment]
Tried today, npm update worked normally, no error.

**Comment by typicode** [comment]
> Tried today, npm update worked normally, no error.

Great, thanks for the update :)
