### ISSUE TITLE
prepare should be used instead of postinstall

### ISSUE THREAD

**Issue by VincentLanglet** [typicode/husky#888]
Husky is installed as a devDependencies, so If the developer is using `yarn --env=prod` it won't be install.
And then the postinstall script will run and fail.

prepare should be used instead https://docs.npmjs.com/cli/v7/using-npm/scripts

**Comment by typicode** [comment]
You're right, that will be better, thanks! :)

**Comment by typicode** [comment]
Closing, docs have been updated :+1:
