### ISSUE TITLE
Run hooks only when certain files change

### ISSUE THREAD

**Issue by Npervic** [typicode/husky#889]
Is it possible to setup husky to run only when relevant code changes? My team uses the same repo for fe and be code and its really annoying to have my js lint and test run whenever a branch with be work is being pushed.

**Comment by typicode** [comment]
Hi @Npervic,

I think this answer https://superuser.com/questions/552617/execute-git-pre-commit-hook-only-if-files-in-certain-directory-modified should work. You can add it to `.husky/pre-commit` and modify it to run your front-end tests only if matches the pattern you're looking for.
