### ISSUE TITLE
husky uninstall

### ISSUE THREAD

**Issue by kylemh** [typicode/husky#893]
**Context**
Please describe your issue and provide some context:
- I had upgraded to Husky v5 from v4. I got Husky working, but `commitizen` and `git-cz` failed to interop on `yarn lerna publish`. Specifically, my CHANGELOG was no longer updating during that command's execution.
- I don't have to resolve the issue and wish simply to revert the changes.
- Removing `.husky/`, re-adding `.huskyrc`, and downgrading the husky dependency fail doesn't return my repo to it's previous behavior.

What are my options here?

**Comment by typicode** [comment]
I would try running:

```shell
git config --unset core.hooksPath
```

Also, if husky 4 doesn't work again, I'd try 

```
yarn add husky@4 && yarn rebuild
```

Let me know if that doesn't work.

**Comment by icetbr** [comment]
Did this got removed from the docs? Npm uninstall didn't called the unset hook for me.

https://github.com/typicode/husky/pull/853/files

**Comment by casvil** [comment]
lefthook 1.11.14 and `git config --unset core.hooksPath` worked perfectly
