### ISSUE TITLE
`add` command accidentally expands variables in the given command

### ISSUE THREAD

**Issue by chalkygames123** [typicode/husky#895]
The command `npx husky add .husky/commit-msg 'npx --no-install commitlint --edit "$1"'` from the documentation will replace `$1` and produce the following.

```
#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npx --no-install commitlint --edit ""
```

**Comment by typicode** [comment]
Good catch! Thanks for the report.
Seems to be related to `npx` as the same command with `yarn` works.

**Comment by chalkygames123** [comment]
AFAIK, it seems reproducible with npx v7 that ships with npm v7.

**Comment by nemchik** [comment]
This may also be dependant on which shell you're using to run `npx husky add .husky/commit-msg 'npx --no-install commitlint --edit "$1"'`. Your shell may be interpreting `$1` before actually handing it into the commands. It might work if you escape the `$` but again that may vary from one shell to another.

**Comment by fenying** [comment]
Same here. I use a trick like below:
```sh
npx husky add .husky/commit-msg 'npx --no-install commitlint "$(echo $)1"'
```

**Comment by chalkygames123** [comment]
@typicode This is still an issue.
