### ISSUE TITLE
v4.3.8 It doesn't seem to create pre-commit in .git/hooks

### ISSUE THREAD

**Issue by Nanchenk** [typicode/husky#896]
After npm i -D husky@4, version 4.3.8 will be installed, but pre-commit has not been executed effectively. Check .git/hooks and found that there is no pre-commit and husky configuration files.

**Context**
husky: 4.3.8
node: 15.3.0
git：2.29.2

**Comment by typicode** [comment]
Could you try running npm rebuild?

**Comment by Nanchenk** [comment]
> Could you try running npm rebuild?

Rebuild many times, install husky@4.3.7 and it will be no problem

**Comment by mrcnw** [comment]
same here

**Comment by typicode** [comment]
The only change between 4.3.7 and 4.3.8 is this https://github.com/typicode/husky/commit/674f833d182071a628f9795bf21105edc71edd97

It doesn't look like it could cause a problem in install.

I've tried `rm -rf .git/hooks && npm rebuild` with 4.3.8 and hooks were recreated. I'm on npm 7.6.1, if that can help.

**Comment by Nanchenk** [comment]
I will try it, thank you

**Comment by gMorning-Wp** [comment]
I also encountered the same issue....

**Comment by gMorning-Wp** [comment]
I can use it after lower the version of node

**Comment by GLObus303** [comment]
Hey same issue, the husky is not running on `4.3.8` (pre-commit). 

I wonder if it is connected that we did update by accident to v5. Finding out later, that it is not free to use. I did clear everything, cloned the repo again. Did `git config --unset core.hookspath` as well. The only rollback solved it.

**Comment by Zeyvo92** [comment]
> Hey same issue, the husky is not running on `4.3.8` (pre-commit).
> 
> I wonder if it is connected that we did update by accident to v5. Finding out later, that it is not free to use. I did clear everything, cloned the repo again.
> 
> Seems like `git config --unset core.hookspath` fixed the issue. I must say, that v5 being publicly accessible, yet not open source made life harder across few teams I had the chance to work within this short period.

Thank you, it worked for me !

**Comment by nemchik** [comment]
> I must say, that v5 being publicly accessible, yet not open source made life harder across few teams I had the chance to work within this short period.

v6 has changed back to the MIT license.

**Comment by MarkosKon** [comment]
I want to add that If you install dependencies inside a Docker container, make sure you have git installed inside the container. 

Tried with 4.3.8 and fails silently if it doesn't find git and doesn't create the hooks.
