### ISSUE TITLE
Husky v5 npx command not found in Intellij IDEA

### ISSUE THREAD

**Issue by HugoGresse** [typicode/husky#898]
**Context**
Commit from CLI work without issue and hook are runned correctly, but not from the Intellij IDEA vcs/git integration. 

In this case, upon using the "Commit" button, an error occured: 
```
0 file committed, 3 files failed to commit: COMMITNAME .husky/pre-commit: line 4: npx: command not found husky - pre-commit hook exited with code 127 (error)
```

- Terminal or GUI client: Intellij IDEA Ultimate 2020.3
- Husky `5.1.3` 
- `.husky/pre-commit` content: 
    ```
    #!/bin/sh
    . "$(dirname "$0")/_/husky.sh"
    
    npx --no-install lint-staged
    
    ````
- Reproduction [here](https://github.com/HugoGresse/open-feedback)

**Comment by typicode** [comment]
Looks like a PATH issue
https://typicode.github.io/husky/#/?id=command-not-found

**Comment by HugoGresse** [comment]
Thanks for the link! The lint-staged now works with it failed on the gpg 
```
cannot run gpg: No such file or directory gpg failed to sign the data failed to write commit object
```

I've checked a few answers on SO whitout being able to fix this. Husky v4 has no issue at all no matter this cli or IDEs used.

**Comment by HugoGresse** [comment]
probably an issue on my side, going to investigate, thanks!

**Comment by swushi** [comment]
Did anybody have a solution for this?

**Comment by HugoGresse** [comment]
I was able to solve this but don't remember what I changed. Maybe restarted Intellij was enough. 
Also, Intellij 2021.2 include gpg now.

**Comment by swushi** [comment]
I was able to solve by copying my entire `~/.zshrc` into a newly created `~/.huskyrc`

**Comment by jcpeden** [comment]
@swushi, I'm not sure you need the entire contents of that file...rather just the $PATH variable?

https://typicode.github.io/husky/#/?id=command-not-found

**Comment by swushi** [comment]
@jcpeden correct. Just checked and I had only added path.

**Comment by akinnee** [comment]
> I was able to solve this but don't remember what I changed. Maybe restarted Intellij was enough. Also, Intellij 2021.2 include gpg now.

Restarting VSCode fixed it for me.

**Comment by thebiltheory** [comment]
Article moved to https://typicode.github.io/husky/troubleshooting.html

**Comment by fabienric** [comment]
Article moved (again) to https://typicode.github.io/husky/troubleshoot.html

**Comment by tmyroadctfig** [comment]
On mac I'd set my shell from zsh back to bash, and I needed to set the same setting in Intellij's settings:

![Image](https://github.com/user-attachments/assets/137f6c14-8708-4873-9ffd-67763cc1a7c5)
