### ISSUE TITLE
npx husky add .husky/commit-msg "npm test"  failed

### ISSUE THREAD

**Issue by Brolly0204** [typicode/husky#899]
![image](https://user-images.githubusercontent.com/16096724/110325702-9e832300-8052-11eb-9223-7fcdeb693143.png)

![image](https://user-images.githubusercontent.com/16096724/110325983-03d71400-8053-11eb-95ba-0c555765af97.png)

**Context**
husky v5.1.3
If npx is added in front of the command, it will not succeed. I will be prompted how to use it. If I remove npx, the global installation of husky will succeed

**Comment by typicode** [comment]
Could you try updating npm to latest version?
