### ISSUE TITLE
`husky init` overwrites prepare script

### ISSUE THREAD

**Issue by Mrtenz** [typicode/husky#900]
When upgrading from v4 to v5, I ran `husky init` (which seems to be the recommended way to do it?). That overwrote my existing `prepare` script in `package.json`. Unfortunately I didn't catch this change soon enough, and it broke other functionality. Husky shouldn't overwrite the `prepare` script without at least some kind of warning or confirmation.

**Comment by typicode** [comment]
Thanks for the report, I'll update docs/the tool.

**Comment by typicode** [comment]
Should be fixed with latest version of `husky-init`
