### ISSUE TITLE
npx husky install command not found

### ISSUE THREAD

**Issue by TerrySmithDC** [typicode/husky#901]
Hi there, I've always been a big fan of this project. Unfortunately I'm having some issues on one of my projects since upgrading to husky 5. Previously this was working using husky 5.1.3, however I cleared my npm cache today and now I'm unable to install or commit on the project.

I have read [Troubleshooting: Command not found](https://typicode.github.io/husky/#/?id=command-not-found) however this seems like a separate issue so I thought I'd make a ticket.

### Info
* Using Item2 / zsh
* Recently cleared npm cache with `npm cache clean --force`
* I've tried deleting node_modules and package-lock.json followed with `npm install` in various combinations.

```package.json
  "scripts": {
    ....
    "postinstall": "husky install"
  },
    "devDependencies": {
    ...
    "husky": "^5.1.3",
  },
```

### Error

```
➜ npm i
> project@0.1.0 postinstall
> husky install

sh: husky: command not found
```

I also tried `npx husky install` which I would have expected to work here. To check my npm/npx is ok I tested out `npx serve .`  and it worked with no problems.

```
➜ npx husky install
sh: husky: command not found
```

This feels like a bug / maybe a missing bin file in the registry? Not sure... Any help would be appreciated.

**Comment by wolfmaster8** [comment]
We're having the same error. We're trying to install a RN dependency that has a postinstall script and it uses husky underneath.
```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-native-device-info@8.0.3 postinstall: `husky install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-native-device-info@8.0.3 postinstall script.
```

**Comment by typicode** [comment]
Hmm I can't seem to reproduce the error, sorry. I would have done the same, delete `package-lock.json/node_modules` and reinstall.

@wolfmaster8 it seems to have been fixed in 8.0.5

**Comment by anaetrezve** [comment]
Deleting `node_modules` and `package-lock.json` then running `npm install` fixed the issue.

**Comment by TerrySmithDC** [comment]
Deleting `node_modules` and `package-lock.json` never did work for me. 

However over the week end I ended up [uninstalling nvm](https://github.com/nvm-sh/nvm/issues/298), got the same node/npm version, ran `npm install` and husky is back to working totally fine.

**Comment by bilal-younus** [comment]
Delete **node_modules** and **package-lock.json** never did work for me.
So i run these two commands and boom magic
****npx husky-init && npm install**
npm install husky --save-dev**
**_npx husky install_**

Thanks me later.

**Comment by JairTorres1003** [comment]
I have a problem related to the husky install command since when said command is executed the `.husky/_/husky.sh` file is empty, which prevents it from working correctly.

I don't know if this has happened to anyone and they have already been able to find a solution.
