### ISSUE TITLE
Husky init - .git Error

### ISSUE THREAD

**Issue by joaofranciscosantos** [typicode/husky#902]
I'm following the documentation https://typicode.github.io/husky/#/?id=automatic-recommended

When I ran `npx husky init` I get 
```
husky - updated package.json
C:\...\services\presentation\node_modules\husky\lib\commands\install.js:20
        throw new Error(".git can't be found");
        ^
Error: .git can't be found
    at Object.install (C:\U...
```

Because I'm in sub-folder, It will not find .git

**Comment by typicode** [comment]
Hi @joaofranciscosantos,

See https://typicode.github.io/husky/#/?id=custom-directory for sub-folder :)

**Comment by joaofranciscosantos** [comment]
Thanks👍
