### ISSUE TITLE
Sourcetree

### ISSUE THREAD

**Issue by codler** [typicode/husky#904]
Husky 5 doesn't work well with Sourcetree. When I commit Im getting this error
```
.husky/pre-commit: Line 4 yarn: command not found

**Comment by typicode** [comment]
Hi @codler, looks like a PATH issue, see https://typicode.github.io/husky/#/?id=command-not-found for a fix :)

**Comment by daviddelusenet** [comment]
@typicode I'm getting multiple errors in Sourcetree:

```bash
git --no-optional-locks -c color.branch=false -c color.diff=false -c color.status=false -c diff.mnemonicprefix=false -c core.quotepath=false -c credential.helper=sourcetree commit -q -F /var/folders/jf/2wd2jwr96kq49m1ct0tq0jgc0000gn/T/SourceTreeTemp.Tkbiko 
.husky/prepare-commit-msg: line 4: /dev/tty: Device not configured
.husky/commit-msg: line 4: npx: command not found
husky - commit-msg hook exited with code 127 (error)
Completed with errors, see above
```

Contents of my `.huskyrc`:

```bash
export NPM_DIR="$HOME/.npm"
[ -s "$NPM_DIR/npm.sh" ] && \. "$NPM_DIR/npm.sh"
```

**Comment by k-utsumi** [comment]
I solved it on my environment with https://github.com/typicode/husky/issues/390#issuecomment-596969011.
Command is...

```
$ echo 'export PATH="/usr/local/bin/:$PATH"' >> ~/.huskyrc
```

**Comment by WumaCoder** [comment]
> Husky 5 doesn't work well with Sourcetree. When I commit Im getting this error
> 
> ```
> .husky/pre-commit: Line 4 yarn: command not found
> ```
To perform a

echo "export PATH=\":/usr/local/bin/:$PATH\"" > ~/.huskyrc

**Comment by LuckyMona** [comment]
this works for me:

move sourcetree from /Applications to ~/Applications

**Comment by EmmanDizon** [comment]
encoutering the same issue

**Comment by brewster1134** [comment]
if you are using nvm and homebrew, this should work in your `.huskyrc`

```sh
HOMEBREW_DIR=$(brew --prefix)
. "$HOMEBREW_DIR/opt/nvm/nvm.sh"
PATH=$NVM_BIN:$PATH
```

**Comment by andrejstas** [comment]
This worked for me:

Solution for Apple m1 Pro chip MacBook Pro - macOS 12.4 - using homebrew:
> Settings -> Git -> Use System Git -> "/opt/homebrew/bin/git" (NOT "/usr/*/git")

https://jira.atlassian.com/browse/SRCTREE-7184

**Comment by wsrfde** [comment]
> 这对我有用：
> 
> 苹果m1 Pro芯片MacBook Pro的解决方案 - macOS 12.4 - 使用自制软件：
> 
> > SourceTree -> Settings -> Git -> Use System Git -> “/opt/homebrew/bin/git” （NOT “/usr/*/git”）
> 
> https://jira.atlassian.com/browse/SRCTREE-7184



> 如果您使用的是nvm和homebrew，这应该可以在您的`.huskyrc`
> 
> ```shell
> HOMEBREW_DIR=$(brew --prefix)
> . "$HOMEBREW_DIR/opt/nvm/nvm.sh"
> PATH=$NVM_BIN:$PATH
> ```

这两个配置我都用了，并且用brew 重新安装了git和nvm。
来自Mac m2 Air

**Comment by wsrfde** [comment]
> Hi @codler, looks like a PATH issue, see https://typicode.github.io/husky/#/?id=command-not-found for a fix :)

有用，果然有问题还是得看官网

**Comment by cat-kun** [comment]
> This worked for me:
> 
> Solution for Apple m1 Pro chip MacBook Pro - macOS 12.4 - using homebrew:
> 
> > SourceTree -> Settings -> Git -> Use System Git -> "/opt/homebrew/bin/git" (NOT "/usr/*/git")
> 
> https://jira.atlassian.com/browse/SRCTREE-7184

这个可以搞定

**Comment by arthursady** [comment]
> This worked for me:
> 
> Solution for Apple m1 Pro chip MacBook Pro - macOS 12.4 - using homebrew:
> 
> > SourceTree -> Settings -> Git -> Use System Git -> "/opt/homebrew/bin/git" (NOT "/usr/*/git")
> 
> https://jira.atlassian.com/browse/SRCTREE-7184

This one worked for me too. You got to install git via brew though if you haven't installed, the path won't be there otherwise.

**Comment by elderdog** [comment]
> 

this works

**Comment by elderdog** [comment]
> > Husky 5 doesn't work well with Sourcetree. When I commit Im getting this error
> > ```
> > .husky/pre-commit: Line 4 yarn: command not found
> > ```
> 
> To perform a
> 
> echo "export PATH=":/usr/local/bin/:$PATH"" > ~/.huskyrc

this works
