### ISSUE TITLE
how to use husky v5 after sponsoring

### ISSUE THREAD

**Issue by verhichi** [typicode/husky#909]
The organization I'm currently in is sponsoring, but not sure what to do to use husky v5.
Do we just upgrade to husky v5 and use it? 
Are there any special steps involved to verify that we've actually sponsored husky?
(sorry in advance if this question has been answered somewhere already or is written somewhere in the docs)

**Comment by typicode** [comment]
> Do we just upgrade to husky v5 and use it?

Yes, just that :) Hope you'll enjoy this new release. Feel free if you have any other questions.

> sorry in advance if this question has been answered somewhere already or is written somewhere in the docs

That's actually a good question, I may update docs later.
