### ISSUE TITLE
should be as simple as `simple-git-hooks`

### ISSUE THREAD

**Issue by JounQin** [typicode/husky#910]
v4 is much easier to use than v5, if you want small size, you should look at https://github.com/toplenboren/simple-git-hooks, I love husky before v5, I think v5 is a bad design personally.

Hoping husky to be better.

**Comment by typicode** [comment]
> Hoping husky to be better.

Have you tried `husky init`? I still think it's good design, I'll try to improve.

**Comment by JounQin** [comment]
> Have you tried husky init?

No, and I won't, the emitted hooks are sharable, and too verbose to config.

`.huskyrc.js` is a better design IMO.

**Comment by JounQin** [comment]
As you can see, more and more packages are moving away.

![image](https://user-images.githubusercontent.com/8336744/112247969-1e82cd00-8c90-11eb-9c2f-11ecfdb29586.png)

And you can check https://github.com/okonet/lint-staged/pull/954#issue-598110918

`lint-staged` has changed its recommendation.
