### ISSUE TITLE
Bug commit from vscode

### ISSUE THREAD

**Issue by RigottiG** [typicode/husky#912]
After upgrade to husky v5, git commit from vscode always fail (via terminal is ok). 

![image](https://user-images.githubusercontent.com/13246770/112457404-7e35b280-8d3a-11eb-8780-cc7e521ca3c7.png)

```
> git -c user.useConfigOnly=true commit --quiet --allow-empty-message --file -
.husky/pre-commit: line 4: npx: command not found
husky - pre-commit hook exited with code 127 (error)
```

npm version: 7.5.1
node version: 15.8.0

**Hooks**
```
// pre-commit
#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npx lint-staged
```

**Comment by typicode** [comment]
Hi @RigottiG, could you try https://typicode.github.io/husky/#/?id=command-not-found

**Comment by natakina** [comment]
The same issue with Webstorm

**Comment by feugy** [comment]
@RigottiG I also had the issue with VSCode.
I'm using nvm, and creating an `~/.huskyrc` file as the Typicode recommended fixed it.

**Comment by lensbart** [comment]
Having the same issue, but the suggestion by **typicode** doesn’t work:

```shellscript
# .huskyrc
# See https://typicode.github.io/husky/#/?id=command-not-found
# This loads nvm.sh and sets the correct PATH before running hook
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
```

**Comment by yhlchao** [comment]
I have the same issue.

**Comment by DeanIfalo** [comment]
Hi @typicode 
There are too many such problems. May I suggest that this step should be performed by the package itself(husky.sh).
In this way, most users do not need to set up the .huskyrc file. Although more work needs to be done, I think it is worth it.
I can provide the code I have used(pre-commit)
```
#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

export NVM_DIR="$HOME/.nvm/nvm.sh"
. "$(dirname $NVM_DIR)/nvm.sh"

export NVM_DIR="$HOME/.nvm"
a=$(nvm ls | grep 'node')
b=${a#*(-> }
v=${b%%[)| ]*}

export PATH="$NVM_DIR/versions/node/$v/bin:$PATH"
yarn lint-staged
```
Or change "~/.huskyrc" to ".huskyrc". It is convenient for a third party to help modify it.
For the great library, cheers!

**Comment by lensbart** [comment]
In the meantime, I was able to resolve my issue by setting the right PATH variables via `source ~/.profile` in the pre-commit file

**Comment by mzvast** [comment]
> Hi @typicode
> There are too many such problems. May I suggest that this step should be implemented by the package itself(husky.sh).
> In this way, most users do not need to set up the .huskyrc file. Although more work needs to be done, I think it is worth it.
> I can provide the code I have used(pre-commit)
> 
> ```
> #!/bin/sh
> . "$(dirname "$0")/_/husky.sh"
> 
> export NVM_DIR="$HOME/.nvm/nvm.sh"
> . "$(dirname $NVM_DIR)/nvm.sh"
> 
> export NVM_DIR="$HOME/.nvm"
> a=$(nvm ls | grep 'node')
> b=${a#*(-> }
> v=${b%%[)| ]*}
> 
> export PATH="$NVM_DIR/versions/node/$v/bin:$PATH"
> yarn lint-staged
> ```
> 
> Or change "~/.huskyrc" to ".huskyrc". It is convenient for a third party to help modify it.
> For the great library, cheers!

You saved my day!
I'm not familiar with sh at all~

I also add one line to make it work with someone install node naked into OS~, but not that useful.

```
# NVM

export NVM_DIR="$HOME/.nvm/nvm.sh"
. "$(dirname $NVM_DIR)/nvm.sh"

export NVM_DIR="$HOME/.nvm"
a=$(nvm ls | grep 'node')
b=${a#*(-> }
v=${b%%[)| ]*}

export PATH="$NVM_DIR/versions/node/$v/bin:$PATH"

# NORMAL INSTALL
export PATH="/usr/local/bin/:$PATH"
```

**Comment by emartini** [comment]
> In the meantime, I was able to resolve my issue by setting the right PATH variables via `source ~/.profile` in the pre-commit file
I ended in the following post which recommends the same approach
https://ntsim.uk/posts/running-git-hooks-with-environment-variables-in-intellij

**Comment by xinkule** [comment]
> Hi @RigottiG, could you try https://typicode.github.io/husky/#/?id=command-not-found

Is there any way I can solve this within the project folder ? we have a large group of developers (and it's growing), I cannot tell everyone to create a husky config file on their computer to solve the issue. 

This problem may trouble most of developers who use [vscode's](https://code.visualstudio.com/) git to commit, cause it might not resolve the correct path, at least in the version 1.58.0

**Comment by xencodes** [comment]
> > Hi @RigottiG, could you try https://typicode.github.io/husky/#/?id=command-not-found
> 
> Is there any way I can solve this within the project folder ? we have a large group of developers (and it's growing), I cannot tell everyone to create a husky config file on their computer to solve the issue.
> 
> This problem may trouble most of developers who use [vscode's](https://code.visualstudio.com/) git to commit, cause it might not resolve the correct path, at least in the version 1.58.0

you found any solution?

**Comment by alexeychikk** [comment]
I use VS Code and husky 7. Yesterday everything was working, today I tried to commit and got the same error
`.husky/pre-commit: line 4: npm: command not found`

**Comment by std4453** [comment]
Met the same problem, I wonder what command did VS Code use to run the git command? It seem to have ignored my `.bashrc`, `.profile` and `fish-nvm`, which shell does it use?

**Comment by alexeychikk** [comment]
I downgraded VS Code to the previous version and it fixed the problem.

**Comment by happycollision** [comment]
This definitely seems like a bug in VSCode. In the meantime, you'll probably need to just reference the exact path needed for anything relying on `brew --prefix whatever`.

FYI for those using `brew` to determine paths, apparently that can cause issues, too. 

For example, I use `asdf` for versioning `npm`. `asdf` has a setup script that gets all the shims set properly in your path, and that script is usually loaded by running `. "$(brew --prefix asdf)/asdf.sh"` in your `.zshrc` file. So in my case, I needed to just hardcode the path returned from `brew` and put the resulting command in my `~/.huskyrc` file:

```
. /opt/homebrew/opt/asdf/asdf.sh
```

**Comment by ekrresa** [comment]
I use VS Code and Husky v6.

I ran `echo $PATH` from the root of my project.
Then I copied the output to the pre-commit file in the .husky directory.

My pre-commit file looks like this:

```sh
#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
npx lint-staged
```
Solved the issue for me.

**Comment by JoCa96** [comment]
> > > Hi @RigottiG, could you try https://typicode.github.io/husky/#/?id=command-not-found
> > 
> > 
> > Is there any way I can solve this within the project folder ? we have a large group of developers (and it's growing), I cannot tell everyone to create a husky config file on their computer to solve the issue.
> > This problem may trouble most of developers who use [vscode's](https://code.visualstudio.com/) git to commit, cause it might not resolve the correct path, at least in the version 1.58.0
> 
> you found any solution?

same here. Did you find a way to fix this?

**Comment by cmacdonnacha** [comment]
It's not ideal to have to tell all our devs to go and add this PATH, is there any way that this can be done inside the library itself? I might just go back to husky v4 using `package.json` which was actually a bit more straightforward.

**Comment by cmacdonnacha** [comment]
> . "$(dirname "$0")/_/husky.sh"
> 
> export NVM_DIR="$HOME/.nvm/nvm.sh"
> . "$(dirname $NVM_DIR)/nvm.sh"
> 
> export NVM_DIR="$HOME/.nvm"
> a=$(nvm ls | grep 'node')
> b=${a#*(-> }
> v=${b%%[)| ]*}
> 
> export PATH="$NVM_DIR/versions/node/$v/bin:$PATH"

This worked for me and at least it can be checked into source control so it's a fix for all devs.

**Comment by TrejGun** [comment]
nice article with explanation and fix

https://ntsim.uk/posts/running-git-hooks-with-environment-variables-in-intellij

**Comment by cmacdonnacha** [comment]
I just downgraded to v3, otherwise you require devs to install `nvm`.

**Comment by hardik2801** [comment]
> Hi @typicode
> There are too many such problems. May I suggest that this step should be implemented by the package itself(husky.sh).
> In this way, most users do not need to set up the .huskyrc file. Although more work needs to be done, I think it is worth it.
> I can provide the code I have used(pre-commit)
> 
> ```
> #!/bin/sh
> . "$(dirname "$0")/_/husky.sh"
> 
> export NVM_DIR="$HOME/.nvm/nvm.sh"
> . "$(dirname $NVM_DIR)/nvm.sh"
> 
> export NVM_DIR="$HOME/.nvm"
> a=$(nvm ls | grep 'node')
> b=${a#*(-> }
> v=${b%%[)| ]*}
> 
> export PATH="$NVM_DIR/versions/node/$v/bin:$PATH"
> yarn lint-staged
> ```
> 
> Or change "~/.huskyrc" to ".huskyrc". It is convenient for a third party to help modify it.
> For the great library, cheers!

This works.

**Comment by christian-hawk** [comment]
adding 2 cents: it happened with me when I switched default shell from `bash` to `zsh`

**Comment by uniquejava** [comment]
It happened to me when I upgraded my vscode from `1.59` to `1.60` today. My project suddenly not work.

It worked well yesterday.
```
.husky/pre-commit: line 4: npx: command not found
husky - pre-commit hook exited with code 127 (error)
```

**Comment by tatupesonen** [comment]
> It happened to me when I upgraded my vscode from `1.59` to `1.60` today. My project suddenly not work.
> 
> It worked well yesterday.
> 
> ```
> .husky/pre-commit: line 4: npx: command not found
> husky - pre-commit hook exited with code 127 (error)
> ```

Facing the exact same issue. Running VSCode version 1.60 and husky@7.0.2 on Big Sur 11.4.

**Comment by pjaws** [comment]
> This is the `~/.huskyrc` that worked for me on my MacBookPro on BigSur 11.6
> 
> ```shell
> # First load nvm and provide access to the nvm command.
> export NVM_DIR="$HOME/.nvm"
>   [ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"
> 
> # Use the nvm ls command to detect the version being used.
> export NVM_DIR="$HOME/.nvm"
> a=$(nvm ls | grep 'node')
> b=${a#*(-> }
> v=${b%%[)| ]*}
> 
> # Export the current version in your path for husky to find.
> export PATH="$NVM_DIR/versions/node/$v/bin:$PATH"
> ```
> 
> I hope this helps someone. I definitely think this needs to be done in your local project directory moving forward.

With this solution I get `nvm: command not found`.


> Hi @typicode There are too many such problems. May I suggest that this step should be implemented by the package itself(husky.sh). In this way, most users do not need to set up the .huskyrc file. Although more work needs to be done, I think it is worth it. I can provide the code I have used(pre-commit)
> 
> ```
> #!/bin/sh
> . "$(dirname "$0")/_/husky.sh"
> 
> export NVM_DIR="$HOME/.nvm/nvm.sh"
> . "$(dirname $NVM_DIR)/nvm.sh"
> 
> export NVM_DIR="$HOME/.nvm"
> a=$(nvm ls | grep 'node')
> b=${a#*(-> }
> v=${b%%[)| ]*}
> 
> export PATH="$NVM_DIR/versions/node/$v/bin:$PATH"
> yarn lint-staged
> ```
> 
> Or change "~/.huskyrc" to ".huskyrc". It is convenient for a third party to help modify it. For the great library, cheers!

With this one, I get an error related to my `.nvmrc`: `N/A: version "lts/* -> N/A" is not yet installed.`. Doesn't matter if a specify a version or not.



> I use VS Code and Husky v6.
> 
> I ran `echo $PATH` from the root of my project. Then I copied the output to the pre-commit file in the .husky directory.
> 
> My pre-commit file looks like this:
> 
> ```shell
> #!/bin/sh
> . "$(dirname "$0")/_/husky.sh"
> 
> export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
> npx lint-staged
> ```
> 
> Solved the issue for me.

This did nothing for me.

And like others, this was simply working one day, broken the next. At a loss for how to fix this.

**Comment by Bartewicz** [comment]
For anyone facing the issue from WSL2, my PATH (check with `echo $PATH` in terminal) included paths from Windows OS and for me it worked to enable `appendWindowsPath=false` at `/etc/wsl.conf`, so my wsl config looks like this now:
```
[interop]
appendWindowsPath=false
```
After that wsl has to be restarted, e.g. from PowerShell run `wsl --shutdown` and open vs code with remote repository again. Hope that helps someone

**Comment by suprewen** [comment]
restart vscode solved my problem...

**Comment by wangmeijian** [comment]
> 嗨@RigottiG，你能试试https://typicode.github.io/husky/#/?id=command-not-found

work for me

**Comment by john-cognizant** [comment]
My solution was to commit via git bash on windows, not via gitHub desktop. ` git commit -m "First commit"`

**Comment by kylemh** [comment]
New project with latest husky...

VS Code's SCM Commit gets same result as OP on a Mac.

I see the "Command not found" helper section in the docs, but none of it is helpful for me.

1. The first suggestion - the `~/.huskyrc` file only solves the issue for me and not my teammates.

2. I didn't install Husky with Brew.

3. I don't know how to change VS Codes path, nor do I want altering VS Code to be the resolution for all of my teammates.

**Comment by timo-kang** [comment]
I just tried `update and restart` on VScode, and it worked!

**Comment by egemon** [comment]
> This is the `~/.huskyrc` that worked for me on my MacBookPro on BigSur 11.6
> 
> ```shell
> # First load nvm and provide access to the nvm command.
> export NVM_DIR="$HOME/.nvm"
>   [ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"
> 
> # Use the nvm ls command to detect the version being used.
> export NVM_DIR="$HOME/.nvm"
> a=$(nvm ls | grep 'node')
> b=${a#*(-> }
> v=${b%%[)| ]*}
> 
> # Export the current version in your path for husky to find.
> export PATH="$NVM_DIR/versions/node/$v/bin:$PATH"
> ```
> 
> I hope this helps someone. I definitely think this needs to be done in your local project directory moving forward.

Thanks! That worked, agree that it shouldn't be done globally.

**Comment by Zerzavot** [comment]
I find two temporary solution like that

    git config --unset core.hooksPath  

or

    git commit -m "message" --no-verify 

But these are not permanent solutions. if you change pre-commit file as [suggested][1], you can commit your changes without any trouble.

    #!/bin/sh
    # ~/.huskyrc
    # This loads nvm.sh and sets the correct PATH before running hook
    export NVM_DIR="$HOME/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"



  [1]: https://typicode.github.io/husky/#/?id=command-not-found

**Comment by DanielCollins96** [comment]
source for fix: https://typicode.github.io/husky/#/?id=command-not-found

I had a pre-commit file and hooksPath set so I needed to create a ~/.huskyrc (mac) and add:

# ~/.huskyrc
# This loads nvm.sh and sets the correct PATH before running hook
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"


as mentioned in link

**Comment by lscarneiro** [comment]
On my macOS Big Sur, what "solved" for me was unchecking the `Terminal > Integrated: Inherit Env` setting in VSCode (it's located in the `User` area).

In my case, I installed `node` using the standard `.pkg` installer and it made my `node`, `npm` and `npx` available on `/usr/local/bin`, but for "some reason" when I did `echo $PATH` from within the `pre-commit` husky file, it didn't show `/usr/local/bin`, so that's why I was having this same `npx: command not found` problem.

After I unchecked this setting and restarted VSCode, I was able to commit via VSCode GUI again.

**Comment by supernaut** [comment]
Is there any fix for this that does not require that developers make local configuration or that their environments are so similar that a check-in path is true for all of them? I work on a team with many developers in the same repository and as it stands now we are looking at removing husky and lint-staged as there doesn't seem to be a team-wide solution.

**Comment by shoyuf** [comment]
> Is there any fix for this that does not require that developers make local configuration or that their environments are so similar that a check-in path is true for all of them? I work on a team with many developers in the same repository and as it stands now we are looking at removing husky and lint-staged as there doesn't seem to be a team-wide solution.

it's VSCode Issue, you can upgrade VSCode version to latest

**Comment by qubitsky** [comment]
> restart vscode solved my problem...

that worked for me, but why?

**Comment by rafee-7peaks** [comment]
Updated husky to latest version solves my problem. I updated from husky v5 to v8

**Comment by michael-sumner** [comment]
I installed node using NVM. So simply adding the code mentioned in the docs here for nvm in the code example worked:
https://typicode.github.io/husky/#/?id=command-not-found

In your terminal:
```sh
code ~/.huskyrc
```

Then paste the code:
```sh
# This loads nvm.sh and sets the correct PATH before running hook
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
```

Save the file. And then source it. In the terminal:
```sh
source ~/.huskyrc
```

Performing the commit should work ok.

**Comment by avitorio** [comment]
Thank you @TomerAtarScopio!

**Comment by orhalimi** [comment]
In my case it was related to homebrew paths won't loaded on vscode when commit from the UI.
So i got nice YARN not found error.

Anyway, I just put the $PATH content under HUSKY_PATH variable in my env file and added this piece of code to the hooks:

`ENV_FILE="./.env"
if [ -f $ENV_FILE ]; then
    source $ENV_FILE
    if ! [[ -z "${HUSKY_PATH}" ]]; then
        export PATH=$HUSKY_PATH
    fi
fi`

So every programmer can set their path in .env file and it will work for them.

**Comment by taixiangfei** [comment]
> Hi @typicode There are too many such problems. May I suggest that this step should be implemented by the package itself(husky.sh). In this way, most users do not need to set up the .huskyrc file. Although more work needs to be done, I think it is worth it. I can provide the code I have used(pre-commit)
> 
> ```
> #!/bin/sh
> . "$(dirname "$0")/_/husky.sh"
> 
> export NVM_DIR="$HOME/.nvm/nvm.sh"
> . "$(dirname $NVM_DIR)/nvm.sh"
> 
> export NVM_DIR="$HOME/.nvm"
> a=$(nvm ls | grep 'node')
> b=${a#*(-> }
> v=${b%%[)| ]*}
> 
> export PATH="$NVM_DIR/versions/node/$v/bin:$PATH"
> yarn lint-staged
> ```
> 
> Or change "~/.huskyrc" to ".huskyrc". It is convenient for a third party to help modify it. For the great library, cheers!



> Hi @typicode There are too many such problems. May I suggest that this step should be implemented by the package itself(husky.sh). In this way, most users do not need to set up the .huskyrc file. Although more work needs to be done, I think it is worth it. I can provide the code I have used(pre-commit)
> 
> ```
> #!/bin/sh
> . "$(dirname "$0")/_/husky.sh"
> 
> export NVM_DIR="$HOME/.nvm/nvm.sh"
> . "$(dirname $NVM_DIR)/nvm.sh"
> 
> export NVM_DIR="$HOME/.nvm"
> a=$(nvm ls | grep 'node')
> b=${a#*(-> }
> v=${b%%[)| ]*}
> 
> export PATH="$NVM_DIR/versions/node/$v/bin:$PATH"
> yarn lint-staged
> ```
> 
> Or change "~/.huskyrc" to ".huskyrc". It is convenient for a third party to help modify it. For the great library, cheers!

Thanks! It worked

**Comment by pzps94038** [comment]
that worked for me

#!/bin/sh
# ~/.huskyrc
# This loads nvm.sh and sets the correct PATH before running hook
export NVM_DIR="$HOME/.nvm"

if [ -s "$NVM_DIR/nvm.sh" ]; then
  # Load nvm
  . "$NVM_DIR/nvm.sh"
fi

. "$(dirname "$0")/_/husky.sh"

npx pretty-quick --staged

**Comment by OgulcanCelik** [comment]
for `fish` and `nvm.fish`

```
# Export the current version in your path for husky to find.
export PATH="$HOME/.local/share/nvm/v16.20.0/bin:$PATH"
```

solved the issue for me.

**Comment by ianaa** [comment]
> Just dropping this here incase someone was puzzled by why it just "suddenly" happened in my case it was because: I usually open vscode via the terminal (which contains my env vars) but after restarting my mac, vscode opened automatically (which did not start up with my env vars - which are exported in my shell rc)

Thank you!!!!

**Comment by avosalmon** [comment]
> I installed node using NVM. So simply adding the code mentioned in the docs here for nvm in the code example worked: https://typicode.github.io/husky/#/?id=command-not-found
> 
> In your terminal:
> 
> ```shell
> code ~/.huskyrc
> ```
> 
> Then paste the code:
> 
> ```shell
> # This loads nvm.sh and sets the correct PATH before running hook
> export NVM_DIR="$HOME/.nvm"
> [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
> ```
> 
> Save the file. And then source it. In the terminal:
> 
> ```shell
> source ~/.huskyrc
> ```
> 
> Performing the commit should work ok.

In 2024, you should add this to `~/.config/husky/init.sh` instead. `~/.huskyrc` is deprecated.
https://typicode.github.io/husky/how-to.html#startup-files

**Comment by Shamzic** [comment]
> > I installed node using NVM. So simply adding the code mentioned in the docs here for nvm in the code example worked: https://typicode.github.io/husky/#/?id=command-not-found
> > In your terminal:
> > ```shell
> > code ~/.huskyrc
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Then paste the code:
> > ```shell
> > # This loads nvm.sh and sets the correct PATH before running hook
> > export NVM_DIR="$HOME/.nvm"
> > [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Save the file. And then source it. In the terminal:
> > ```shell
> > source ~/.huskyrc
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Performing the commit should work ok.
> 
> In 2024, you should add this to `~/.config/husky/init.sh` instead. `~/.huskyrc` is deprecated. https://typicode.github.io/husky/how-to.html#startup-files

Thanks, this was the solution for me!

**Comment by euxx** [comment]
For mise https://github.com/jdx/mise/issues/726, 

~/.config/husky/init.sh
```
export PATH="$HOME/.local/share/mise/shims:$PATH"
```

**Comment by sLurPPPeRsTaR** [comment]
> restart vscode solved my problem...

TBH he is right... thanks

**Comment by brandonjcg** [comment]
> Hi @RigottiG, could you try https://typicode.github.io/husky/#/?id=command-not-found

Dead link :(

**Comment by JonasGruenwald** [comment]
> > Hi @RigottiG, could you try https://typicode.github.io/husky/#/?id=command-not-found
> 
> Dead link :(

The relevant section of the husky docs would be this one:

https://typicode.github.io/husky/how-to.html#startup-files

The solution is to add the mise shims to path in the husky init.sh, as described above by @euxx

**Comment by mengxi-ream** [comment]
> > I installed node using NVM. So simply adding the code mentioned in the docs here for nvm in the code example worked: [typicode.github.io/husky#/?id=command-not-found](https://typicode.github.io/husky/#/?id=command-not-found)
> > In your terminal:
> > ```shell
> > code ~/.huskyrc
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Then paste the code:
> > ```shell
> > # This loads nvm.sh and sets the correct PATH before running hook
> > export NVM_DIR="$HOME/.nvm"
> > [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Save the file. And then source it. In the terminal:
> > ```shell
> > source ~/.huskyrc
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Performing the commit should work ok.
> 
> In 2024, you should add this to `~/.config/husky/init.sh` instead. `~/.huskyrc` is deprecated. [typicode.github.io/husky/how-to.html#startup-files](https://typicode.github.io/husky/how-to.html#startup-files)

After this, I got 
```
> git -c user.useConfigOnly=true commit --quiet --allow-empty-message --file -
[STARTED] Preparing lint-staged...
[COMPLETED] Preparing lint-staged...
[STARTED] Running tasks for staged files...
[STARTED] .lintstagedrc.json — 1 file
[STARTED] **/*.+(js|jsx|ts|tsx) — 1 file
[STARTED] * — 1 file
[STARTED] eslint
[STARTED] pnpm format:staged
[FAILED] pnpm format:staged [ENOENT]
[FAILED] pnpm format:staged [ENOENT]
[COMPLETED] Running tasks for staged files...
[STARTED] Applying modifications from tasks...
[SKIPPED] Skipped because of errors from tasks.
[STARTED] Reverting to original state because of errors...
[FAILED] eslint [KILLED]
[FAILED] eslint [KILLED]
[COMPLETED] Reverting to original state because of errors...
[STARTED] Cleaning up temporary files...
[COMPLETED] Cleaning up temporary files...

✖ pnpm format:staged failed without output (ENOENT).

✖ eslint failed without output (KILLED).
husky - pre-commit script failed (code 1)
```

**Comment by mengxi-ream** [comment]
> > > I installed node using NVM. So simply adding the code mentioned in the docs here for nvm in the code example worked: [typicode.github.io/husky#/?id=command-not-found](https://typicode.github.io/husky/#/?id=command-not-found)
> > > In your terminal:
> > > ```shell
> > > code ~/.huskyrc
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Then paste the code:
> > > ```shell
> > > # This loads nvm.sh and sets the correct PATH before running hook
> > > export NVM_DIR="$HOME/.nvm"
> > > [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Save the file. And then source it. In the terminal:
> > > ```shell
> > > source ~/.huskyrc
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Performing the commit should work ok.
> > 
> > 
> > In 2024, you should add this to `~/.config/husky/init.sh` instead. `~/.huskyrc` is deprecated. [typicode.github.io/husky/how-to.html#startup-files](https://typicode.github.io/husky/how-to.html#startup-files)
> 
> After this, I got
> 
> ```
> > git -c user.useConfigOnly=true commit --quiet --allow-empty-message --file -
> [STARTED] Preparing lint-staged...
> [COMPLETED] Preparing lint-staged...
> [STARTED] Running tasks for staged files...
> [STARTED] .lintstagedrc.json — 1 file
> [STARTED] **/*.+(js|jsx|ts|tsx) — 1 file
> [STARTED] * — 1 file
> [STARTED] eslint
> [STARTED] pnpm format:staged
> [FAILED] pnpm format:staged [ENOENT]
> [FAILED] pnpm format:staged [ENOENT]
> [COMPLETED] Running tasks for staged files...
> [STARTED] Applying modifications from tasks...
> [SKIPPED] Skipped because of errors from tasks.
> [STARTED] Reverting to original state because of errors...
> [FAILED] eslint [KILLED]
> [FAILED] eslint [KILLED]
> [COMPLETED] Reverting to original state because of errors...
> [STARTED] Cleaning up temporary files...
> [COMPLETED] Cleaning up temporary files...
> 
> ✖ pnpm format:staged failed without output (ENOENT).
> 
> ✖ eslint failed without output (KILLED).
> husky - pre-commit script failed (code 1)
> ```

After I change the `.lintstagedrc.json` to, it works perfectly

```
{
  "**/*.+(js|jsx|ts|tsx)": ["eslint"],
  "*": ["prettier --write --cache"]
}
```

**Comment by airtonix** [comment]
or just prefix your commands with `mise x -- thecmd` 


```
#!/usr/bin/env bash

mise x -- yarn lint-staged
```
