### ISSUE TITLE
When I install the other package, husky will remove all dependencies in my project 

### ISSUE THREAD

**Issue by neroneroffy** [typicode/husky#915]
**Troubleshoot**
Before creating an issue, please check:
https://typicode.github.io/husky/#/?id=troubleshoot

If you're migrating from husky 4, see:
https://typicode.github.io/husky/#/?id=migrate-from-v4-to-v5

**Context**
Please describe your issue and provide some context:
- Terminal or GUI client (PowerShell, Git Bash, GitHub Desktop, ...)
- If applicable, content of the failing hook
- If possible, minimal steps to reproduce the issue

When I run `npm install umi` or `npm install` or `yarn`, if installed to husky, the script of `preuninstall` will run, confusingly, the rest of the dependencies in my project will be removed.

* node: v4.15.3
* npm: 6.14.10
* yarn: 1.9.4
* OS: windows 10

```
npm install umi

> yorkie@2.0.0 uninstall F:\tenxcloud\monitor-panel-portal\node_modules\yorkie
> node bin/uninstall.js

husky
uninstalling Git hooks
done


> husky@4.3.8 preuninstall F:\tenxcloud\monitor-panel-portal\node_modules\husky
> node husky uninstall

missing lib directory
npm WARN rm not removing F:\tenxcloud\monitor-panel-portal\node_modules\.bin\rimraf.cmd as it wasn't installed by F:\tenxcloud\monitor-panel-portal\node_modules\rimraf
npm WARN rm not removing F:\tenxcloud\monitor-panel-portal\node_modules\.bin\rimraf as it wasn't installed by F:\tenxcloud\monitor-panel-portal\node_modules\rimraf
npm WARN rm not removing F:\tenxcloud\monitor-panel-portal\node_modules\.bin\uuid.cmd as it wasn't installed by F:\tenxcloud\monitor-panel-portal\node_modules\uuid
npm WARN rm not removing F:\tenxcloud\monitor-panel-portal\node_modules\.bin\uuid as it wasn't installed by F:\tenxcloud\monitor-panel-portal\node_modules\uuid

```

Thank you!

**Comment by typicode** [comment]
Hi @neroneroffy,

Not sure how to reproduce the issue. Yorkie (the fork of husky that umi uses) appears to be correctly set in the devDependencies in the repo (and is not present here https://unpkg.com/browse/umi@3.4.7/package.json) so I don't know how it runs here? 

Also there's no code in husky that should remove other dependencies as well.

Personally, I'd check if it's not something else? Or if you can share some additional commands that I can run?
