### ISSUE TITLE
[husky@6] husky-init overrides any pre-commit hook

### ISSUE THREAD

**Issue by notaphplover** [typicode/husky#919]
## Context

husky v6.0.0 overrides any `pre-commit` hook with the following one:

```
#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npm test
```

### Steps to reproduce:

1. Start an npm package: `npm init`
2. install husky@6: `npm i --save-dev husky`
3. install husky-init: `npm i --save-dev husky-init`
4. Add a precommit hook at the .husky folder of the project
5. run husky-init: npx husky-init

The precommit hook is now overridden.

### Expected behavior

git hooks should not be overridden.

**Comment by derekschinke** [comment]
Yeah, instructions for upgrading from 5 to 6 are unclear as well

**Comment by typicode** [comment]
@derekschinke which parts are unclear? I'd be happy to improve docs.

**Comment by typicode** [comment]
Thanks for the steps to reproduces.

Just in case someone stumbles on this issue, `husky-init` is optional, needs to be done once and shouldn't be installed in the project devDependencies.

**Comment by notaphplover** [comment]
@typicode ok I understand It now. Docs are **now** clear to me, I probably made a mistake reading them.

I would suggest to open a new issue related to docs if necessary instead of using this issue.

**Comment by typicode** [comment]
No worries, I've updated docs.
