### ISSUE TITLE
Prepare Commit Message existing hook

### ISSUE THREAD

**Issue by daminufe** [typicode/husky#92]
I am trying to use Husky for a project. But the problem is that I have several git hooks which are really specific and I still want to run them using bash.

I tried, but it seems they are not taking the parameters. Are there a way to keep using the existing hooks plus the ones on the package.json?

**Comment by typicode** [comment]
Hi @daminufe,

Yes, husky won't overwrite any existing hook. So, if you have existing hooks, you can keep using them plus the ones from package.json.

Of course, you can also move them out of `.git/hooks` if you want to version them:

```json
{
  "scripts": {
    "precommit": "sh scripts/my-specific-hook.sh"
  }
}
```

**Comment by daminufe** [comment]
It won't work.

I have the following structure:

* `git-hooks/prepare-commit-msg`
* `package.json`

The content of the `prepare-commit-msg` is:

```
#!/bin/sh
COMMIT_EDITMSG=$1
TYPE=$2 # one of message, template, merge, squash, commit
REF=$3 # optional, when TYPE is commit

COMMIT_REGEX='JIRA-[0-9a-zA-Z\-]+'
BRANCH_REF=$(git rev-parse --abbrev-ref HEAD)

case "$TYPE,$REF" in
  merge,)
    # Remove "Conflicts" lines from merges (from prepare-commit-msg.sample)
    /usr/bin/perl -i.bak -ne 's/^/# /, s/^# #/#/ if /^Conflicts/ .. /#/; print' "$1" ;;
  ,|message,|template,)
    if ! echo "$BRANCH_REF" | grep -iqE "$COMMIT_REGEX"; then
      echo "branch is not matching pattern $COMMIT_REGEX, skipping prefix" >&2
      sleep 1
      exit 0
    fi
    # Prepend branch ref if not already having a reference
    if ! grep -iqE "\[$COMMIT_REGEX\]" "$COMMIT_EDITMSG"; then
      printf "[$BRANCH_REF] $(cat $COMMIT_EDITMSG)" > $COMMIT_EDITMSG
    fi
    ;;
  *) ;;
esac
```

Then I got this output from the console when I commit:

```
git commit -m "One more git prepare commit message" -a

> app-backend@1.0.0 preparecommitmsg /Users/david/dev/app-backend
> sh git-hooks/prepare-commit-msg

grep: : No such file or directory
git-hooks/prepare-commit-msg: line 21: $COMMIT_EDITMSG: ambiguous redirect
```

I tried several prepare-commit-msg files and none works.

**Comment by redoPop** [comment]
Looks like Husky exports these arguments to a `GIT_PARAMS` environment variable, which you can pass along to your Bash hook like so:

```json
"preparecommitmsg": "git-hooks/prepare-commit-msg ${GIT_PARAMS}",
```

**Comment by HjoshM** [comment]
Should parameters after **$** always be enclosed within curly braces?

I am following the first simple example in the [Git Hooks Atlassian](https://www.atlassian.com/git/tutorials/git-hooks), but putting the following line in my **pre-commit** hook file throws an "**ambiguous redirect**" error message.

What am I doing wrong with this line?

```
#!/bin/sh
echo "# Please include a useful commit message!" > $1
```

**Comment by AnneTee** [comment]
In case anyone else ends up here, I had to use ${HUSKY_GIT_PARAMS} as noted in #113

**Comment by typicode** [comment]
Thanks for providing a solution :+1: 
With husky 5, Git params are directly accessible and not stored in a HUSKY_GIT_PARAMS anymore.
