### ISSUE TITLE
Skip installing hooks on CI

### ISSUE THREAD

**Issue by ismay** [typicode/husky#920]
This concerns husky v6. I've added the recommended script to `package.json`:

```
"prepare": "husky install"
```

I'm using npm, locally and on CI. Now on CI, `husky install` is installing the hooks as well. I'd expect `husky install` to skip hook installation when a CI environment is detected. See for example here, in this GH actions CI run:

<img width="927" alt="Screenshot 2021-03-29 at 18 40 54" src="https://user-images.githubusercontent.com/7355199/112870284-55a51400-90be-11eb-8b75-81b13916df6c.png">

**Comment by pinalbhatt** [comment]
Seeing problem when we run `npm ci --only=production`  during CI/CD flow and building docker image.

`> husky install

sh: husky: not found
npm notice 
npm notice New minor version of npm available! 7.6.3 -> 7.7.6
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v7.7.6>
npm notice Run `npm install -g npm@7.7.6` to update!
npm notice 
npm ERR! code 127
npm ERR! path /root
npm ERR! command failed
npm ERR! command sh -c husky install`

**Comment by typicode** [comment]
Hi @ismay,

https://typicode.github.io/husky/#/?id=disable-hooks-in-ci

Alternatively, you can also run:

```shell
npm set-script prepare ""
npm ci --only=production
```

**Comment by typicode** [comment]
As @pinalbhatt suggested, there's also:

```
npm ci --only=production --ignore-scripts
```

**Comment by ismay** [comment]
Ah perfect, that resolved the issue. Sorry I didn't notice this in the docs. I did go through them, but must have glanced over this. Thanks for the help!

**Comment by typicode** [comment]
No worries, it's easy to miss. I've updated docs with @pinalbhatt solution (many thanks!) and added Docker mention.

**Comment by ismay** [comment]
Awesome, thanks 🙏!

**Comment by maxpain** [comment]
> As @pinalbhatt suggested, there's also:
> 
> ```
> npm ci --only=production --ignore-scripts
> ```

But what if some of my node modules requires to install binaries via scripts?

**Comment by sammort** [comment]
@t

> > As @pinalbhatt suggested, there's also:
> > ```
> > npm ci --only=production --ignore-scripts
> > ```
> 
> But what if some of my node modules requires to install binaries via scripts?

@typicode I see this suggestion has made it in to the docs and I don't think it is really suitable. As @maxpain mentions this stops all scripts from running, including those of other dependencies.

```
npm set-script prepare ""
npm ci --only=production
```

Looks like a good suggestion, I've just been working on this as we are building a docker image with `npm ci --production` where husky is a dev dependency only, so docker build was failing when running prepare script.

My solution was to add a prepare script

```
#!/bin/sh
if [ -d './node_modules/husky' ]; then
  npx husky install
fi
```

**Comment by Yuliang-Lee** [comment]
https://typicode.github.io/husky/#/?id=disable-husky-in-cidocker

**Comment by techeverri** [comment]
> https://typicode.github.io/husky/#/?id=disable-husky-in-cidocker

The link changed a bit https://typicode.github.io/husky/#/?id=disable-husky-in-cidockerprod

**Comment by jonataswalker** [comment]
`npm set-script` is deprecated, go for `npm pkg set scripts.prepare="exit 0"`

**Comment by maxpain** [comment]
@jonataswalker we use `npm pkg delete scripts.prepare`

**Comment by jonataswalker** [comment]
`npm pkg delete scripts.prepare`

Much better, didn't notice in the docs.

**Comment by jgbernalp** [comment]
I think `HUSKY=0 npm ci` is a better option as it does not disable other prepare scripts.

```
> husky install

husky - HUSKY env variable is set to 0, skipping install
...
```

**Comment by mipicdev** [comment]
> I think `HUSKY=0 npm ci` is a better option as it does not disable other prepare scripts.
> 
> ```
> > husky install
> 
> husky - HUSKY env variable is set to 0, skipping install
> ...
> ```

In my opinion this is a cleaner solution. But I had to set `HUSKY: 0` as a CI/CD variable.
