### ISSUE TITLE
`husky install` prepare script fails

### ISSUE THREAD

**Issue by thasmo** [typicode/husky#922]
When running `npm ci` the installation process exits with the following error at the end:
```
npm ERR! Cannot read property 'length' of undefined
```

The log gives more insight into the problem:
```
15422 info lifecycle undefined@undefined~install: undefined@undefined
15423 info lifecycle undefined@undefined~postinstall: undefined@undefined
15424 info buildTree Done in 3.859s
15425 info garbageCollect Done in 0s
15426 info lifecycle undefined@undefined~prepublish: undefined@undefined
15427 info runScript Done in 0.001s
15428 info lifecycle undefined@undefined~prepare: undefined@undefined
15429 verbose stack TypeError: Cannot read property 'length' of undefined
15429 verbose stack     at _incorrectWorkingDirectory (/home/user/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:114:60)
15429 verbose stack     at /home/user/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:86:44
15429 verbose stack     at /home/user/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:218:12
15429 verbose stack     at callback (/home/user/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:295:20)
15429 verbose stack     at FSReqCallback.oncomplete (fs.js:167:5)
15430 verbose cwd /home/user/projects/project
15431 verbose Linux 4.4.0-206-generic
15432 verbose argv "/home/user/.nvm/versions/node/v12.16.1/bin/node" "/home/user/.nvm/versions/node/v12.16.1/bin/npm" "ci"
15433 verbose node v12.16.1
15434 verbose npm  v6.14.12
15435 error Cannot read property 'length' of undefined
15436 verbose exit [ 1, true ]
```

When removing `"prepare": "husky install"` from the `package.json` file, `npm ci` runs just fine, but `husky` will not be installed, obviously.

This happens with `nvm@0.38.0`, `node@12.16.1` and `npm@6.14.12`.

This may be a problem with either `nvm` or `npm`, I guess. When looking at the docs, it seems that various examples and commands regarding `npm` suggest that `husky@6` was developed/designed with `npm@7`, which we do not use yet, because it has a lot of bugs.

Could it be that `nvm` is the problem instead?

I do have a `~/.huskyrc` file with this contents; and it worked well will `husky@4`:
```
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
```

Thanks a lot for your time and help!

**Comment by thasmo** [comment]
Okay, this seems to happen with any `prepare` script, which indicates that it's not a problem with `husky` in the first place. Feel free to close the issue. Thanks for your time!

**Comment by thasmo** [comment]
Nevermind, this seems exactly to be the [problem described in a stackoverflow thread](https://stackoverflow.com/questions/59777226/npm-ci-throws-exception-cannot-read-property-length-of-undefined).

**Comment by thasmo** [comment]
@typicode, thanks for maintaining and improving `husky`. :1st_place_medal:

**Comment by typicode** [comment]
> @typicode, thanks for maintaining and improving husky. 1st_place_medal

Thanks!
