### ISSUE TITLE
Migrating prepare-commit-msg and commit-msg hooks does not work as documented on npm/npx >= 7

### ISSUE THREAD

**Issue by anthony-telljohann** [typicode/husky#924]
Migrating `prepare-commit-msg` and `commit-msg` hooks does not work as documented on `npm`/`npx` `>= 7`.  When `husky add`ing a command that contains `"$1"`, `husky`'s commit hook file will resolve as `""`.

## Steps to reproduce
```shell
npx husky add .husky/commit-msg 'npx --no-install commitlint --edit "$1"'
```

**expected** `.husky/commit-msg`

```shell
#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npx --no-install commitlint --edit "$1"
```

**actual** `.husky/commit-msg`

```shell
#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npx --no-install commitlint --edit ""
```

### commitlint

add the hook **without** `"$1"`

```shell
npx husky add .husky/commit-msg 'npx --no-install commitlint --edit'
```

append the hook with `"$1"`

```shell
sed -i 's/^npx.*/& "$1"/' .husky/commit-msg
```

### jira-prepare-commit-msg

add the hook **without** `"$1"`

```shell
npx husky add .husky/prepare-commit-msg 'npx --no-install jira-prepare-commit-msg'
```

append the hook with `"$1"`

```shell
sed -i 's/^npx.*/& "$1"/' .husky/prepare-commit-msg
```

**Comment by jmtelljohann** [comment]
I had the same problem

**Comment by bk201-** [comment]
Hi! I've checked the issue. Unfortunately, I couldn't repro this. I've done the following steps:
I use Windows. If you have another system, please ping me, I will check it on Linux.
1. Create a new folder
2. `git init`
3. `npm init`
4. `npm install husky -D`
5. `npm set-script prepare "husky install"`
6. `npm run prepare`
7. `npx husky add .husky/prepare-commit-msg 'npx --no-install jira-prepare-commit-msg "$1"'`
![image](https://user-images.githubusercontent.com/6812525/114154325-f0a4b600-9928-11eb-9f5f-fdbfef60103b.png)
8. Check file `.husky/prepare-commit-msg`
![image](https://user-images.githubusercontent.com/6812525/114154540-2fd30700-9929-11eb-98ae-7d1263d4fdd2.png)

**Comment by anthony-telljohann** [comment]
We tested on macOS with Terminal.app using a bash shell, and on Windows with Git Bash using a bash shell.

**Comment by anthony-telljohann** [comment]
It does not work as documented when using `npm`/`npx` `@^7.0.0` but does work as documented with `npm`/`npx` `@^6.0.0`.

**Comment by bk201-** [comment]
![image](https://user-images.githubusercontent.com/6812525/114388118-f3f3a800-9b9b-11eb-8f44-81f672909919.png)
![image](https://user-images.githubusercontent.com/6812525/114388424-551b7b80-9b9c-11eb-9593-ca310bfa1e54.png)

I reproduced it on Linux. I tried to debug npm, and found next:

npm@6
![image](https://user-images.githubusercontent.com/6812525/114401529-ada64500-9bab-11eb-8e86-0f5bc60c2041.png)

It runs husky as a module (point 1), not as a cmd (point 2)

npm@7
![image](https://user-images.githubusercontent.com/6812525/114402408-75ebcd00-9bac-11eb-8537-ffc8bb210978.png)

It creates the following arguments and runs as cmd
``` 
sh [
  '-c',
  'husky "add" ".husky/prepare-commit-msg" "npx --no-install jira-prepare-commit-msg \\"$1\\""'
]
```
