### ISSUE TITLE
Automatically installing git hooks

### ISSUE THREAD

**Issue by yoavain-sundaysky** [typicode/husky#925]
**Troubleshoot**
Before creating an issue, please check:
https://typicode.github.io/husky/#/?id=troubleshoot

If you're migrating from husky 4, see:
https://typicode.github.io/husky/#/?id=migrate-from-v4-to-v6

**Context**
I just migrated from v4 to v6.
In version 4, if someone checked out my project, and ran `npm install`, the hooks just worked.
In version 6, when checking out the project, running `npm install` is not enough. There's a need to run `husky install` in order to setup the git hooks. 

My question is why isn't it part of the Husky "post install" script?

**Comment by yoavain** [comment]
![brain-hey-youre-going-to-sleep-yes-now-shut-up-i-think-i-figuerd-out-how-to-debug-your-program-comic 1](https://user-images.githubusercontent.com/644871/113199680-14546600-9270-11eb-8104-1062dd3e31aa.jpg)

**Comment by mcmillion** [comment]
Yeah, I don't understand this change either. My entire reason for using Husky was to not have to manually install hooks.
