### ISSUE TITLE
`npm install` is generating additional files in `.husky` folder

### ISSUE THREAD

**Issue by TabithaLarkin** [typicode/husky#926]
**Context**
This is something that has been occurring across our development team, usually when switching branches, as Visual Studio likes to "helpfully" run an install each time there is a branch change.

Only a `pre-commit` file has been specified and created. This works as expected, but for some reason I can't track down, husky occasionally seems to be generating a file for each of the other hooks too. Their content however is a little different from the `pre-commit` file, as they all include:
```sh
#!/bin/sh
command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/post-checkout.\n"; exit 2; }
git lfs post-checkout "$@"
```

This is doubly confusing as `git-lfs` is most definitely installed as well.

**Comment by typicode** [comment]
Hi @TabithaLarkin

This looks like `git-lfs` generated code. If that can help `husky` doesn't contain/generate such code.

**Comment by TabithaLarkin** [comment]
Okay no problem, we've resolved it on our end by adding them to our `.gitignore`. Thanks for your help.
