### ISSUE TITLE
What’s the point of husky.sh?

### ISSUE THREAD

**Issue by remcohaszing** [typicode/husky#929]
I love how the latest husky incorporates `core.hooksPath`. This makes it so much simpler.

I noticed husky creates `.husky/_/husky.sh` (and `.husky/.gitignore`), but I don’t really see the point of this file. As far as I can tell, it’s unused.

Could someone explain what this is for? Perhaps it belongs in the FAQ.

**Comment by typicode** [comment]
Hi @remcohaszing,

Thanks :)

Did you create hooks with `husky add` (or `husky set`)? It should create them with `husky.sh` being sourced at the beginning of the file.

Good suggestion for the FAQ.

**Comment by remcohaszing** [comment]
No, I created `.husky/pre-commit` with the following contents:

```sh
#!/usr/bin/env sh

yarn lint-staged
```

And of course I added the following to `package.json`:

```js
  // …
  "scripts": {
    // …
    "prepare": "husky install"
  },
  // …
```

This _just works_.

**Comment by nemchik** [comment]
`husky set ...` doesn't seem to be documented anywhere on https://typicode.github.io/husky/#/

**Comment by thasmo** [comment]
@typicode, wondering if `husky` should use `#!/usr/bin/env sh` instead of `#!/bin/sh` in all it's scripts.

**Comment by typicode** [comment]
Generally speaking, I'd recommend keeping `husky.sh`. It contains code that can be useful for GUI users cloning the project and may have some additional features in future versions of husky.

@thasmo I picked the shebang used by Git hooks samples (in `.git/hooks`). I'm not against `env sh` but what would be good reasons to change it?

**Comment by remcohaszing** [comment]
Using `#!/usr/bin/env some-shell` allows `some-shell` to be detected from the environment, whereas specifying an exact path in the shebang forces the user to install the shell to that specific location. Some practival examples:

- `#!/usr/bin/env node` works with `nvm`.
- `#!/usr/bin/env python` works with Python virtual environments.
- `#!/usr/bin/env bash` allows users to install a specific version of bash. I.e. I recall system bash was outdated on MacOS at some point.

For `husky.sh` the shebang is unused. It’s supposed to be `source`d from a script, not to be called as a script directly.

**Comment by remcohaszing** [comment]
All of my questions have been answered. Thanks!

**Comment by TravisBallard** [comment]
Why is husky.sh added to the .gitignore file? This means anyone who checks out the code in my repo can still commit without the hooks running. The hooks wont run until the user runs `npx husky install` to generate the `_` folder that's missing from the repo since it's being ignored?

**Comment by blueblakk** [comment]
@TravisBallard I was wondering the same thing.

**Comment by TravisBallard** [comment]
adding a `prepare` script to `package.json` solved it for me. 

`{ "scripts": {"prepare": "husky install"}}`

**Comment by remcohaszing** [comment]
@joetidee I don’t know why you’d want that, but you can use `git add -f` to ignore the `.gitignore` file.

```sh
git add -f .husky/_/husky.sh
```

**Comment by joetidee** [comment]
> @joetidee I don’t know why you’d want that, but you can use `git add -f` to ignore the `.gitignore` file.
> 
> ```shell
> git add -f .husky/_/husky.sh
> ```

I'm not sure why I wouldn't want that :) - could you elaborate on why it shouldn't be included?

**Comment by remcohaszing** [comment]
> I'm not sure why I wouldn't want that :) - could you elaborate on why it shouldn't be included?

It’s autogenerated by husky. Generally I think committing autogenerated files is a bad idea. Husky creates a `.gitignore` file for it for a reason.

**Comment by joetidee** [comment]
ok, so why doesn't it autogenerate when I checkout master?

**Comment by remcohaszing** [comment]
The `prepare` script in `package.json` run when you run `npm install` (or `yarn`), not when you switch branches.

**Comment by joetidee** [comment]
Right, so if it disappears when switching branches, that is a pain in the backside :)

**Comment by iameduardod** [comment]
@husky team - not including this shell script and forcing new repo users to do the init overrides the existing repo's .husky/pre-commit file. 

Not very cash money....
