### ISSUE TITLE
Expose git stdin parameters for pre-push

### ISSUE THREAD

**Issue by Necroskillz** [typicode/husky#93]
As you can see in the pre-push sample: https://github.com/git/git/blob/master/templates/hooks--pre-push.sample, they use some stdin parameters to determine local and remote sha and ref.

Main usecases for having these parameters are:
 - To not execute pre-push hook when you are deleting a remote branch (this is the most important, since it's kind of annoying when hooks starts when you just want to delete a branch)
 - To filter branch names which you want to execute pre-push hooks on

**Comment by callmephilip** [comment]
+1: I am trying to determine the name of the branch in pre-push and cannot seem to find a way to do this with husky ($GIT_PARAMS only contains information regarding remote + repository uri)

**Comment by okonet** [comment]
I have similar use-case with post-checkout: https://gist.github.com/okonet/9706ec3b7f29e05109f3744fbc1fc91e

So I think parameters should be exposed for all hooks by default.

ghooks package does it but it's deprecated in favor of this one.
