### ISSUE TITLE
How to call `husky.sh` inside hook using `#!/usr/bin/env node`?

### ISSUE THREAD

**Issue by Saeris** [typicode/husky#930]
Related to #929, as I don't know why you'd need to call `husky.sh` at the beginning of a hook (it doesn't appear to be documented at all). My question is simply how would this line: `. "$(dirname "$0")/_/husky.sh"` be called from node? The docs appear to assume your hooks will all be bash scripts and there's nothing addressing node scripts.

If we can just omit the call to `husky.sh` entirely, that should be documented as well.

**Comment by remcohaszing** [comment]
It’s a shell script which can be sourced from bourne compatible shells. It can’t be called from NodeJS. Also it can be omitted. Looking at its contents, this script:

1. adds a small amount of debugging information if `$HUSKY_DEBUG` is set to `1`;
2. exits the shell if `$HUSKY` is set to `0`; (Hooks can also be skipped by passing `-n` or `--no-verify` to `git` commands.)
3. sources `~/.huskyrc` if it exists.

**Comment by typicode** [comment]
Thanks @remcohaszing :)

Among other things `husky.sh` contains code for GUI other users cloning your project. In the future, it may contain other features.
So unless, you're the only user and really want to be minimalist, I'd recommend keeping it. But in the end use what makes most sense for your case.

For node, I'd do this personally:

```sh
#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

node ./pre-commit.js
```

**Comment by xeladejo** [comment]
It's probably a stupid, but then because not use:

```sh
#!/bin/sh
. node_modules/husky/lib/husky.sh

node ./pre-commit.js
```

This would allow close all `.gitignore` related issues.
