### ISSUE TITLE
Husky install: .git can't be found

### ISSUE THREAD

**Issue by czescwojtek** [typicode/husky#937]
Environment:
WSL Ubuntu, bash terminal
Yarn workspaces + lerna monorepo

I've migrated from v4 to v6 as per instruction (https://typicode.github.io/husky/#/?id=migrate-from-v4-to-v6). The .git directory, package.json file and the .husky all live at the **same level** (INB4: https://typicode.github.io/husky/#/?id=custom-directory).
Command `husky install` (@package.json, scripts.prepare) fails with "Error: .git can't be found (see https://typicode.github.io/husky/#/?id=custom-directory)" message. I can assure you the .git dir is there and I have all the required permissions

The line that fails:
```
if (!fs.existsSync('.git')) {
    throw new Error(`.git can't be found (see ${url})`);
}
```

Thank you!

**Comment by czescwojtek** [comment]
Closing! The order of the scripts in package.json's scripts.prepare was the issue.

**Comment by kaneru** [comment]
@czescwojtek, Hello, i'm running into the same issue. I have lerna and yarn workspaces setup too. How exactly did you solve your issue? This is what I have in my `package.json` file as `"prepare"` script:

`"prepare": "husky install"`

**Comment by czescwojtek** [comment]
Hi @kaneru, as far as I can recall I had bloated "prepare" script. I mean "husky install" wasn't the only part of the scripts.prepare, like: "prepare": "cd here && do this && cd .. && husky install". That mixed content was the issue.

**Comment by kaneru** [comment]
@czescwojtek, thanks for the reply. I didn't manage to solve my issue, but still your information you provided is helpful for me.

**Comment by harikumaraj07** [comment]
Please follow the link below.
https://typicode.github.io/husky/#/?id=custom-directory
