### ISSUE TITLE
v6's postinstall breaks Yarn 2's "workspaces focus" command

### ISSUE THREAD

**Issue by jalovatt** [typicode/husky#939]
After upgrading to v6 everything appeared to be working fine, until I ran our build pipeline. When building Docker images, we use:
```
yarn workspaces focus @projectname/package
```
to strip down `node_modules` to just what that package needs. Since Husky is a root dependency, it isn't installed, so `"postinstall": "husky install"` fails and causes the build to error out.
```
❯ cat /tmp/xfs-54164c20/build.log
# This file contains the result of Yarn building a package (root@workspace:.)
# Script name: postinstall

command not found: husky
```

`yarn workspaces focus` unfortunately doesn't have a `--ignore-scripts` flag, so in our case I've had to wrap the hook to check that Husky is available first:
```
"postinstall": "sh -c 'if [ command -v ./node_modules/.bin/husky ]; then ./node_modules/.bin/husky install; fi;'"
```

- Discussion of what's happening: https://github.com/yarnpkg/berry/issues/2209 - it sounds like one Yarn step prints a warning about soft links, then a separate one tries to run the `postinstall` anyway.
- Yarn docs for the relevant error code: https://yarnpkg.com/advanced/error-codes#yn0006---soft_link_build
- It should be noted that Yarn are also trying to discourage the use of lifecycle scripts in general, particularly `postinstall`, as they've been moving toward being able to load packages straight from the cache and lifecycles make that trickier. See: https://yarnpkg.com/advanced/lifecycle-scripts#a-note-about-postinstall

Cheers.

#### Versions
Husky 6.0.0
Yarn 2.4.1

**Comment by brunojppb** [comment]
Since you are probably running `npm ci --production` during CI, you can workaround this with the following update in `prepare` hook:

```json
"scripts": {
  "prepare": "[[ \"$NODE_ENV\" == \"production\" ]] && echo \"skipping husky during CI\" || $(npm bin)/husky install"
}```

**Comment by greenhat616** [comment]
@typicode yes, after upgrading to v6. it will breaks yarn 2 command `yarn workspaces focus --production` similar to npm command `npm install --production` or yarn v1 command `yarn install --production`. This issue is similar to #914

**Comment by makrandgupta** [comment]
Still running into this issue. Are there any plans to address this?
