### ISSUE TITLE
post-checkout error in CI

### ISSUE THREAD

**Issue by grit96** [typicode/husky#940]
**Context**

I'm getting the following error in my CI builds because the `post-checkout` hook gets run before `husky install` gets run.

```
.husky/post-checkout: line 2: .husky/_/husky.sh: No such file or directory
```

I can reproduce it locally by removing `.husky/_/husky.sh` and checking out to another branch. This scenario would also happen when checking out from a husky v4 branch to a husky v6 branch.

I think the ideal solution would be to check `.husky/_/husky.sh` into git but every time `husky install` is run a new `.gitignore` is generated.

**Comment by andorfermichael** [comment]
I've added the following line to each of my hook files:

`[ -n "$CI" ] && exit 0`

Resulting in:

```
#!/bin/sh
[ -n "$CI" ] && exit 0
. "$(dirname "$0")/_/husky.sh"

yarn install
```
