### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by 2RajShaikh** [typicode/husky#944]
The first time pre-commit hooks after husky installation worked fine, but later on, out of nowhere, I am started seeing the below issue.

`.husky/pre-commit: line 3: .husky/_/husky.sh: No such file or directory`

husky version ^3.1.0

**Comment by czescwojtek** [comment]
Been there, especially when switching between branches. Running `npx husky-init` does the trick but you'll have to backup pre-commit file content **before** you run `npx` as the `husky-init` will replace pre-commit file content with default/sample code.

**Comment by 2RajShaikh** [comment]
Thank you @czescwojtek 

Any reason why _/husky.sh file has been added to .gitignore?
To me, this seems to be annoying as there are many developers in my team who will keep changing the branches.
Should I just go ahead and remove it from .gitignore and commit husky.sh file? Do you see any red flags? Any other suggestions?

**Comment by czescwojtek** [comment]
Sorry, that's all I know.

**Comment by DoctorDerek** [comment]
> Thank you @czescwojtek
> 
> Any reason why _/husky.sh file has been added to .gitignore?
> To me, this seems to be annoying as there are many developers in my team who will keep changing the branches.
> Should I just go ahead and remove it from .gitignore and commit husky.sh file? Do you see any red flags? Any other suggestions?

Yeah I have no idea either, husky is supposed to reduce maintainability issues, so I have no understanding at all why there would be magical ignored files.

Nothing in husky v4 was .gitignored, but now it seems that a portion is -- I guess because of something having to do with the `npx husky-init` process?

**Comment by DoctorDerek** [comment]
This seems like a pretty insidious bug, because if I clone a repository using husky without manually running `npx husky-init` then the husky hooks simply don't work -- no error, no nothing.

**Comment by DoctorDerek** [comment]
But then if I actually run `npx husky-init` then my pre-commit hook gets overwritten with the default:
```
#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npm test
```

So basically a tool commonly used to keep git commits tidy (husky) is actually making git completely unusable. 😅

**Comment by DoctorDerek** [comment]
That said, the current workflow is supposed to be the following:
1. npm install
2. "prepare" script in package.json generates /_/husky.sh
3. ... (profit?)

And you'd only need to run `npx husky-init` the first time -- as long as that "prepare" script is there you'll get the default `/_/husky.sh` script automatically after your first npm install.

Indeed, while poorly documented, this does appear to be on purpose: https://blog.typicode.com/husky-git-hooks-autoinstall/

**Comment by Twintails** [comment]
@typicode should we override the .gitignore and add the  `/_/husky.sh` to the first commit after update from 4-6?
Is that _/husky.sh file needed to travel with the repo to other devs, but be ignored from future updates?
`git add .husky/_/husky.sh`

**Comment by alexb-uk** [comment]
Neither running `npm run prepare`  nor `npx husky install` directly fixes this issue.
The only way is to re-run `npx husky-init` which destroys the contents of `.husky/pre-commit`.
This has to be done every time the branch is switched.

Is this not a bug as I'm pretty sure I've followed all the install instructions as documented?

**Comment by stalinkay** [comment]
Fixed it with `!.husky/_/husky.sh` per @Twintails's comment.
