### ISSUE TITLE
Message reminding about the `--no-verify` option is missing

### ISSUE THREAD

**Issue by Golodhros** [typicode/husky#946]
**Context**
- Git bash on MacOS
- STR: run failing hook

Expected:
It would remind the user about the `--no-verify` option as it used to do in version 4.

**Comment by jhyman2** [comment]
I think this could be accomplished in the `.husky/pre-commit` script. I am exploring that now, and will post an update if I figure it out.

**Comment by jhyman2** [comment]
Seems that you'll have to echo the instructions before running your other scripts because the script will exit early. Here is what I have in my script. Obviously it's not the same as what you are requesting but it can be used to notify other devs that they can override husky.

```
#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "If pre-commit hook fails, add --no-verify to bypass"
npm run pre-commit
```

**Comment by Golodhros** [comment]
Hi @jhyman2, thanks for your response!

So, you would add that echo in all your pre commit and pre push hooks?

It seems like an OK workaround, but I do use Husky in a number of repositories, and copy/pasting this all over the place and remembering to do it again once I add more hooks seems a bit non-optimal.

Thanks anyways for this!

**Comment by jhyman2** [comment]
> So, you would add that echo in all your pre commit and pre push hooks?

Yes, but I am just a mere user of Husky. It'll be fine for my use-case, but I agree it's not ideal.
