### ISSUE TITLE
When installing husky, it corrupts my project (new configuration files, new lines in package.json)

### ISSUE THREAD

**Issue by mickaeltr** [typicode/husky#95]
Hello,

When I install my project, husky (^0.13.1) sometimes:

1. Adds new configuration files in my project:

- .depcheckrc
- .eslintignore
- .eslintrc

2. Adds new lines in my package.json

<img width="719" alt="screen shot 2017-01-27 at 09 55 57" src="https://cloud.githubusercontent.com/assets/378910/22365987/a27d7ece-e47a-11e6-8e88-526caecc9032.png">
<img width="133" alt="screen shot 2017-01-27 at 09 56 11" src="https://cloud.githubusercontent.com/assets/378910/22365994/ab8b7ce6-e47a-11e6-8e15-8d9d51691a9a.png">

Unfortunately, I haven't found reproduction steps yet… 

Thanks

**Comment by typicode** [comment]
Hi @mickaeltr,

These files aren't part of husky, so I would suspect maybe some other `dependency` or `devDependency` are doing this.

Also `husky` hooks in `package.json` are defined using `precommit` and not `pre-commit`, I would say there's maybe another hook manager (this can cause some issues as husky won't be able to install git hooks).

Here are the dependencies husky installs https://github.com/typicode/husky/blob/master/package.json#L43

You can try installing husky only using `npm install --save-dev husky` to be sure.

I would also suggest checking if in `package.json` if you have an `install` or `prepublish` script that does some additional setup when you run `npm install`.

Hope this will help :)

PS: quick tip if you have a recent version of npm, and not related to the question, but you can omit `./node_modules/.bin` in your scripts and call directly things directly (i.e. `"lint": "eslint ."`)

**Comment by mickaeltr** [comment]
Hi @typicode,
I though it was coming from _husky_ but actually I am pretty sure now that it actually comes from another package (https://github.com/doublesharp/lru-cache-for-clusters-as-promised) which installs _developer-tools_ (https://github.com/doublesharp/node-developer-tools) which overwrites Git hooks!
Many thanks
