### ISSUE TITLE
Hooks not working with #!/bin/sh on zsh

### ISSUE THREAD

**Issue by marcesdan** [typicode/husky#953]
This is my pre-commit hook

``` bash
#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

lerna run --concurrency 1 --stream precommit --since HEAD --exclude-dependents
```

It fails due to

```
.husky/pre-commit: 4: lerna: not found
husky - pre-commit hook exited with code 127 (error)
```

but it works if i change it to

``` bash
#!/bin/zsh
...
```

How do I make it shell agnostic?

**Comment by ciesielskico** [comment]
THANKS. I was going crazy, this fixed it.

**Comment by marcesdan** [comment]
@ciesielskico You're welcome, but this is not a fix. You may need copy the content (paths that you need) fromyour .zshrc and paste in ~/.huskyrc. That's no portable... but works in zsh envs.

**Comment by Yash-Singh1** [comment]
Could this be reopened?

**Comment by leomarlo** [comment]
yes, I'm facing the same issue. Please reopen!

**Comment by typicode** [comment]
It's a PATH issue, see https://typicode.github.io/husky/#/?id=command-not-found

Version managers work by modifying PATH in your terminal. GUI don't source `.zshrc` and therefore are incompatible with version managers.

If Node is installed globally, GUI will find it in the PATH. If GUI are open from the terminal, they'll inherit environment variables (including PATH).

The other solution to bridge the gap is to load version managers in ~/.huskyrc which is sourced before running hooks (even in GUIs).

**Comment by nico-limo** [comment]
Hello, I would like to know if there is a solution on this?
I am using zsh with oh my zsh and husky is not working anymore. I have WSL 2 installed

**Comment by typicode** [comment]
@nico-limo which version manager are you using? try running in zsh `echo $PATH && sh -c 'echo $PATH'` are there differences?

**Comment by nico-limo** [comment]
Hello, zsh 5.8.1 (x86_64-ubuntu-linux-gnu) and WSL 2. I solved the issue by following the command Automatic (recommended),
```bash
npx husky-init && yarn
 ``` 

Doing it manually seems that not work
```bash
npx husky install
 ```
