### ISSUE TITLE
'npx husky add .husky/precommit "npm test"' prints Usage

### ISSUE THREAD

**Issue by hsk-kr** [typicode/husky#954]
- OS: Windows10
- Command line tool: git-bash
- husky version: "^6.0.0"

```shell
$ npm i -D husky
$ git init
$ npx husky install # .husky directory had been created here
$ npx husky add .husky/pre-commit "npm test"
Usage
  husky install [dir] (default: .husky)
  husky uninstall
  husky set|add <file> [cmd]
```

I tried to make a hook pre-commit but 
the command `npx husky add .husky/pre-commit "npm test"` displays The usage message.
What did I do wrong?

---

P.S

I reinstalled husky as a v4.3.8. and the command worked.
Isn't the command able to use in v6?

**Comment by ywymoshi** [comment]
This problem occurs when I use single quotes，Using double quotes works

**Comment by mudssky** [comment]
i got this problem too.
win10 powershell 7.1.3 husky6(  excute succeed in other win10 machine )
`npx husky add` can't create  pre-commit file
```
npx husky add .husky/pre-commit 'npm test'
Usage
  husky install [dir] (default: .husky)
  husky uninstall
  husky set|add <file> [cmd]
```
but 
`npx husky-init ` can create the  pre-commit file

**Comment by marcinmajkowski** [comment]
I have the same problem, changing between single and double quotes did not help. As a workaround, I was able to execute the command by saving it as a script in package.json and running it with npm.

Win 10, tried both PowerShell and Git Bash. Husky 6.0.0.

**Comment by shivapoudel** [comment]
Same problem. I tried to add the hook but instead returns the usage screen. Unfortunately, I have to try `npx husky add '.husky/pre-commit'` to generate the file and manually changed the required changes for lint-staged.

**Comment by hsk-kr** [comment]
I resolved this problem from downgrade husky version ^6 to ^4.3.8.

**Comment by KirillBudenko** [comment]
Same here trying to add `commit-msg`. 
Solved the issue using WSL on windows machine.
