### ISSUE TITLE
Docs don't mention supported hooks (i.e. all Git Hooks)

### ISSUE THREAD

**Issue by DoctorDerek** [typicode/husky#956]
It's not the least bit obvious to a new user the type of commit hooks that would be supported by husky, though it tends to be the first thing mentioned in any article about using husky.

Unfortunately, husky v6 is so different from husky v4 that all husky articles are out-of-date, so the docs should mention this simple fact:
* What types of hooks does husky support? Husky supports all Git hooks except server-side hooks; see https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks for details

Reference: https://maksimivanov.com/posts/git-husky/

**Comment by wesvetter** [comment]
From [the docs](https://github.com/typicode/husky/commit/c61ba5fbbe8135216309d9ef9843b8b6d873b329) (emphasis mine):

> You can use it to lint your commit messages, run tests, lint code, etc... when you commit or push. **Husky supports [all](https://git-scm.com/docs/githooks) Git hooks.**

**Comment by DoctorDerek** [comment]
Ok, thanks for that. Maybe making "all Git hooks" the link would be clearer?

It's the only mention, and the link "all" is not the least bit descriptive.
