### ISSUE TITLE
makesure node_modules/.husky is exist

### ISSUE THREAD

**Issue by zWingz** [typicode/husky#958]
**Troubleshoot**
when i run `npm CI` in CI, it throw error
'not such dir or file /path/to/node_modules/.husky`

can use `fs.ensureDir` instead `fs.mkdir` ?

https://github.com/typicode/husky/blob/main/packages/husky/src/index.ts#L31

**Comment by typicode** [comment]
Not sure to sure to see how it's related. You may want to try disabling husky in CI
https://typicode.github.io/husky/#/?id=disable-husky-in-cidocker

**Comment by zWingz** [comment]
@typicode no, i just want to install husky in custom dir.
- `npx husky install my_husky_path`

if `my_husky_path` not exist, it will throw error.
