### ISSUE TITLE
Release 1.0.0

### ISSUE THREAD

**Issue by voxpelli** [typicode/husky#96]
I think we're quite a few who uses this module actively and have done so for years so it would be great if it could migrate to a stable version number as SemVer defines stable version numbers.

Is there anything specific blocking a `1.0.0` release that can't instead wait for a future `2.0.0`?

**Comment by typicode** [comment]
@voxpelli you're right, a `v1.0.0` could have been released.

At the time, I felt differently and wanted to address some issues before (especially `yarn`, if I remember correctly).

There were also things I wanted to do, like: config support, have less logic written in shell, be less dependent to `npm` command, etc...

In the end, `husky` has been completely rewritten. Work is now happening in [`dev`](https://github.com/typicode/husky/tree/dev) branch and if everything goes fine (which it seems like), `v0.15` should become the first stable release :)

There are `beta` versions available for testing as well.
