### ISSUE TITLE
Command not found when using yarn --cwd

### ISSUE THREAD

**Issue by dschinkel** [typicode/husky#962]
Is there some reason husky can't run this command:
`yarn --cwd src/graphql test-graphql-integration`

When I run that from the root of my project just by itself it runs fine.  But when I try to include it in the husky hook, I get ` Command "test-graphql-integration" not found`

`"update-husky-hook": "node_modules/.bin/npx husky add .husky/pre-commit \"yarn lint-staged && yarn --cwd src/graphql test-graphql-integration \"",` - this update script is in my root package.json

**Comment by typicode** [comment]
Hmm, I don't know sorry. Never used `--cwd` arg.

If you still have the issue, I would add `pwd` in `pre-commit` to see what's the current working directory and debug using that.

Husky isn't doing anything particular regarding path or env variables. Also `_/husky.sh` can be commented if you want to be sure there's not side-effect from husky.
