### ISSUE TITLE
How to support custom user hooks in v6

### ISSUE THREAD

**Issue by wesvetter** [typicode/husky#964]
I want to setup Husky for a large project (30+ active contributors) but I want my co-workers to be able to specify their own custom hooks. I'd like to specify a minimum set of hooks (mainly linting), but allow my collaborators to specify additional hooks if they want (like running the test suites or spellchecking their commit messages).

As far as I can tell, there does not appear to be a built-in mechanism for users to extend the base set of hooks.

I've worked around this by creating a shell script that optionally calls any custom hooks specified in `.husky/custom/` (which is `.gitignore`'d).

I've put together a [demo repo](https://github.com/wesvetter/husky-custom-hooks) that illustrates this technique but I feel like I'm missing a feature. **Is there a built-in feature or canonical recipe for users to specify custom hooks?**

Apologies in advance if the instructions for this exist elsewhere but I didn't see an obvious recipe for this in the docs and searching in GitHub issues is... challenging. The approach for [Yarn on Windows](https://typicode.github.io/husky/#/?id=yarn-on-windows) sort of condones something similar, or at least doesn't _discourage_ creating a shell script and referencing it in each hook.

**Comment by typicode** [comment]
Husky is pretty much unopinionaded about what goes in scripts. So if it works for you and your team, that's great :+1:

Alternatively, there's `~/.huskyrc.sh` that is loaded everytime a hook is running. It can be another place where users can put custom scripts.

**Comment by wesvetter** [comment]
Thanks for clarifying 🙇
