### ISSUE TITLE
husky Error: .git can't be found in monorepo

### ISSUE THREAD

**Issue by novaknole** [typicode/husky#966]
* I am using `husky:6.0.0`.
* I am using monorepo with `yarn workspace` and `lerna`. 
* In the root's package.json, i have added 
```
"nohoist": [
   "husky"
]
```

Now, I go to one of my sub package and do this:

`yarn husky install` but this produces 

> Error: .git can't be found (see https://typicode.github.io/husky/#/?id=custom-directory)

I understand the problem, but don't know the best practice solution. Should I be having `.husky` folder in the root and not in the subpackage ? is this an idea and will it work ? 

I added this in my `scripts` in the root package.json, but no luck.

```
"prepare": "cd ./packages/govern-console && husky install"
```

**Comment by Avivhdr** [comment]
Hi @novaknole 
How did you solve this issue?

**Comment by Daniel0liver** [comment]
Add a custom directory to install husky if you using monorepo

Doc: [ https://typicode.github.io/husky/#/?id=custom-directory]( https://typicode.github.io/husky/#/?id=custom-directory)

Exemplo with my folder struture:

In the`package.json` file:
```json

"scripts": {
   "postinstall": "cd .. && husky install app/.husky"
}
```
and run the command `yarn postinstall`

The command `cd ..` return to the folder with the name of your repository that has the .git file and install husky in the folder where you have your front-end code with the .husky folder.


My monorepo structure:

```
- my-monorepo/
   - server/
   - app/
```

**Comment by Avivhdr** [comment]
Thank you @Daniel0liver!
