### ISSUE TITLE
any documentation on how to update commit-msg?

### ISSUE THREAD

**Issue by Thatkookooguy** [typicode/husky#97]
I want to create a hook to add a line at the end of the commit message.

so, if a user wrote:
```
change files
```

I want the commit to change to
```
change files

-something I added
```

I see in [the hooks support page](https://github.com/typicode/husky/blob/master/HOOKS.md) that `husky` does support this event, but I can't seem to find how to change the commit message.
Most cases I found online just validate the commit message and don't edit it.

is it possible?

Also, can't seem to see a URL to documentation anywhere. If there is any, can you please give me a link to it?

thanks!

**Comment by iamstarkov** [comment]
It seems like you need commit message templates and not hooks https://robots.thoughtbot.com/better-commit-messages-with-a-gitmessage-template

**Comment by Thatkookooguy** [comment]
@iamstarkov I don't want a template. This change shouldn't effect anything the committer actually wrote. it just adds a string to the end of the commit to mark some commits
I want to add this only on some of the commits.

So, a commit message template isn't the right solution here.

**Comment by iamstarkov** [comment]
Have you tried asking on StackOverflow? By the way, git has examples for all hook: take a look https://github.com/git/git/blob/master/templates/hooks--commit-msg.sample

I wanted to note that the only husky's responsibility is to invoke hooks, not actual hooks implementation.

**Comment by Thatkookooguy** [comment]
I already now how to make this in bash.
But there's no clear documentation on where to set or get the commit message file for husky.
I prefer to change the implementation to use javascript instead if possible.

If it's not possible (meaning I'll have to use the original script), that's fine too.

But if there is a way to change the commit message with husky (and javascript), that's what I'm trying to figure out.

The example you added is in bash so it's not exactly what I'm looking for

**Comment by Thatkookooguy** [comment]
seems like
```
I wanted to note that the only husky's responsibility is to invoke hooks, not actual hooks implementation.
```

This was the right answer.

**Comment by TechQuery** [comment]
@Thatkookooguy , you can set the **commit message** by code like below:

```JavaScript
require('fs').writeFileSync(process.env.GIT_PARAMS, 'some message edited');
```
just like what Vim or other command-line editor does~

**Comment by Thatkookooguy** [comment]
@TechQuery thanks! that's exactly what I needed! :-)
