### ISSUE TITLE
Proper Installation of Husky v6 when .git is in a parent directory to package.json? 

### ISSUE THREAD

**Issue by deduced** [typicode/husky#974]
My project setup is as follows: 
```
.git
server/
   package.json
client/
   package.json

```

I want to set up husky on `server`, so from within `server`, I ran the following commands: 
* `npm install husky --save-dev`
* `cd ..; npx husky install server/`

That did not create the `.husky` folder, so I created the following script in server/packages.json

```
scripts: {
"prepare": "cd .. && husky install server/.husky",
}
```

Then I ran `npm install prepare`. 

Everything seemed to work and I was then able to set up a precommit. However, when I attempt a commit I get the following error: 

```
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /Users/username/Sites/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/Users/username/Sites/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/username/.npm/_logs/2021-05-20T04_35_22_169Z-debug.log
husky - pre-commit hook exited with code 254 (error)

```

**Comment by typicode** [comment]
In `.husky/pre-commit` file, do you have `cd server` as well before `npm run ...`?
For a complete example: https://typicode.github.io/husky/#/?id=custom-directory

**Comment by deduced** [comment]
> In `.husky/pre-commit` file, do you have `cd server` as well before `npm run ...`?

That was it! I was missing `cd server` above `npm test` from within `.husky/pre-commit`.
