### ISSUE TITLE
Which's the added value of husky???????????????????????????

### ISSUE THREAD

**Issue by yunielrc** [typicode/husky#977]
What's problem does it solves?

For to work with git hooks I just need to do the following:

```sh
mkdir .git-hooks
git config --local core.hooksPath .git-hooks
vim .git-hooks/pre-commit # edit the script
chmod +x .git-hooks/pre-commit # only the first time
```

I don't understand for what do I need husky.

**Comment by typicode** [comment]
Hi,

Friendly user/error messages with real exit code, `~/.huskyrc` for GUI clients and safe guards.
It can be useful when working in teams with beginners or for Open Source projects with many contributors.

That said, your example is perfectly valid and may be sufficient. Depends on the needs and personal preferences :)

**Comment by yunielrc** [comment]
Thanks @typicode

**Comment by typicode** [comment]
You're welcome
