### ISSUE TITLE
Getting set/add usage displayed when using proper command line

### ISSUE THREAD

**Issue by xorbis** [typicode/husky#978]
**Context**
Using Git Bash for Windows
Node 14.16.1
npm 6.14.12
```
$ npx husky set .husky/pre-commit 'npm run lint'
Usage
  husky install [dir] (default: .husky)
  husky uninstall
  husky set|add <file> [cmd]
```
But using this works and creates an empty file:
```
$ npx husky set .husky/pre-commit
```

**Comment by xorbis** [comment]
At the prompt, this works.
```
npx husky set .husky/pre-commit \"npm run lint\"
```

**Comment by rifftual** [comment]
Workaround doesn't work on Windows 10 (PowerShell) with Husky v. 6.0.0

**Comment by lkjimy** [comment]
Same issue   
`node: 12.22.1` `npm: 6.14.12` `husky: ^6.0.0`   

Powershell   
```bash
# MS PowerShell v.5.1.19041.906

> npx husky set .husky/pre-commit "npm test"
Usage
  husky install [dir] (default: .husky)
  husky uninstall
  husky set|add <file> [cmd]

> npx husky set .husky/pre-commit \"npm test\"
Usage
  husky install [dir] (default: .husky)
  husky uninstall
  husky set|add <file> [cmd]

> npx husky set .husky/pre-commit
husky - created .husky/pre-commit
```  

Command Prompt   
```bash
# MS Windows 10.0.19042.928 Command Prompt

> npx husky set .husky/pre-commit "npm test"
Usage
  husky install [dir] (default: .husky)
  husky uninstall
  husky set|add <file> [cmd]

> npx husky set .husky/pre-commit \"npm test\"
husky - created .husky/pre-commit

> npx husky set .husky/pre-commit
husky - created .husky/pre-commit
```

WSL Ubuntu `node: 10.15.3` `npm: 6.4.1`   
```bash
# WSL Ubuntu 18.04.1 LTS

$ npx husky set .husky/pre-commit "npm test"
husky - created .husky/pre-commit

$ npx husky set .husky/pre-commit \"npm test\"
Usage
  husky install [dir] (default: .husky)
  husky uninstall
  husky set|add <file> [cmd]

$ npx husky set .husky/pre-commit
husky - created .husky/pre-commit
```

**Comment by nearzeno** [comment]
![image](https://user-images.githubusercontent.com/22211269/121475645-457fae00-c9f8-11eb-9b89-f68da082517c.png)

the husky/lib/bin.js was wrong! if you want use "npx add/set" command you can remove the length limit

![image](https://user-images.githubusercontent.com/22211269/121476176-ed957700-c9f8-11eb-9546-aa17f24d4974.png)

**Comment by OfficerHalf** [comment]
Seeing the same on windows 10.

With node v14.17.0, npm v6.14.13
```
$ npx husky add .husky\pre-commit "npx lint-staged"
Usage
  husky install [dir] (default: .husky)
  husky uninstall
  husky set|add <file> [cmd]
```

With node v16.1.0, npm v7.11.2
```
$ npx husky add .husky\pre-commit "npx lint-staged"
husky - created .husky\\pre-commit
```

**Comment by arsize** [comment]
> Seeing the same on windows 10. Using a newer version of node/npm fixes it. But I can't rely on all end users having a non LTS version of node.
> 
> With node v14.17.0, npm v6.14.13
> 
> ```
> $ npx husky add .husky/pre-commit "npx lint-staged"
> Usage
>   husky install [dir] (default: .husky)
>   husky uninstall
>   husky set|add <file> [cmd]
> ```
> 
> With node v16.1.0, npm v7.11.2
> 
> ```
> $ npx husky add .husky/pre-commit "npx lint-staged"
> husky - created .husky/pre-commit
> ```
> 
> Not sure if the issue lies here or with node/npm though. Maybe the handling of quotes or `process.argv` changed between the standalone npx and `npm exec` which is used under the hood in v7+?
> 
> EDIT:
> Thinking that might be the case. Directly running husky with node works fine:
> 
> ```
> $ npx husky add .husky/pre-commit "npx lint-staged"
> Usage
>   husky install [dir] (default: .husky)
>   husky uninstall
>   husky set|add <file> [cmd]
> 
> $ node node_modules\husky\lib\bin.js add .husky/pre-commit "npx lint-staged"
> husky - updated .husky/pre-commit
> ```

it's works for me

**Comment by typicode** [comment]
I'd say it's related to `npm`. 

```js
// index.js
console.log(process.argv)
```

```sh
node index.js a b "c d" '$1'
# is correctly parsed 
```

There's not much that can be down on husky's side unfortunately. Hope it gets solved soon (if it hasn't already with most recent versions)
