### ISSUE TITLE
How can I prevent hooks from being used in CI

### ISSUE THREAD

**Issue by Xenfo** [typicode/husky#979]
**Context**
Please describe your issue and provide some context:
- Terminal or GUI client (PowerShell, Git Bash, GitHub Desktop, ...) `Github actions`
- If applicable, content of the failing hook `exec < /dev/tty && yarn cz --hook || true`
- If possible, minimal steps to reproduce the issue `Run in CI`

**Comment by typicode** [comment]
There are multiple ways to do so, see:
https://typicode.github.io/husky/#/?id=disable-husky-in-cidocker

**Comment by Xenfo** [comment]
Thanks that worked
