### ISSUE TITLE
 node is not recognized as an internal or external command 

### ISSUE THREAD

**Issue by Brolly0204** [typicode/husky#980]
**Troubleshoot**
Before creating an issue, please check:
https://typicode.github.io/husky/#/?id=troubleshoot

If you're migrating from husky 4, see:
https://typicode.github.io/husky/#/?id=migrate-from-v4-to-v6

**Context**
Please describe your issue and provide some context:
- Terminal or GUI client (PowerShell, Git Bash, GitHub Desktop, ...)
- If applicable, content of the failing hook
- If possible, minimal steps to reproduce the issue

Thank you!

**Comment by typicode** [comment]
Most probably https://typicode.github.io/husky/#/?id=command-not-found
Are you using a GUI client?

**Comment by jannikkeye** [comment]
I have the same problem since the start of the last week. Adding the nvm stuff to .huskyrc doesn't resolve it sadly. I checked, and ~/.huskyrc is loaded and the contents are correct but the issue still persists.

**Comment by typicode** [comment]
I would need more info to be able to reproduce. That said, it's likely to be something external to husky.
I would try echoing $PATH in `pre-commit` or in `.huskyrc` and see how it's different from the terminal.

**Comment by typicode** [comment]
Thanks for the details. Everything looks good in `~/.huskyrc` but somehow `nvm` fails to load.
Do you have `~/.nvm/nvm.sh` file or is it somewhere else? Seems like nvm is now put in `$XDG_CONFIG_HOME`
https://github.com/nvm-sh/nvm#install--update-script

**Comment by Elias-cug** [comment]
I have the same problem. After I use nvm, I have reinstalled node, but It doesn`t work.

**Comment by jannikkeye** [comment]
Nevermind, I'm a big dumb dumb and didn't set a default node version in NVM so it always failed to find one. @Elias-cug maybe that's your issue too. I did a fresh install of my MacBook and forgot to set a default. Probably thought it would be set automatically.

**Comment by nikolaiborisik** [comment]
In my case reinstalling nvm solved issue
