### ISSUE TITLE
remap husky_velocity_controller/odom to something else

### ISSUE THREAD

**Issue by jinbae9875** [typicode/husky#987]
So by default, the wheel odometry topic is published on husky_velocity_controller/odom. How do I change that so that I can remap it to something else? It looks like the node that's publishing to it is gazebo and husky_velocity_controller is spawned by controller_manager. Do I need to set a particular parameter to achieve that? Or do I have to make a custom node that reads in husky_velocity_controller/odom to something else? Thanks.

**Comment by typicode** [comment]
Wrong repo :)
