### ISSUE TITLE
How to use husky only in local without pushing husky hooks to repo

### ISSUE THREAD

**Issue by adelin-b** [typicode/husky#993]
Im used to use husky hooks but it takes time sometime for projects to adopt it, I would like to not depends on it and I wonder how to use husky from outside the git repo or without ending up pushing it to the remote.

I tryed to just run an alias on lints for `git commit`  but I really need a more global solution that works also when I commit from inside an editor

**Comment by typicode** [comment]
There's not one way to do it, but something like that could work:

```sh
project$ cd ..
$ mkdir husky-hooks && cd husky-hooks
husky-hooks$ npm init -y && npm install husky -D && npx husky install . && npx husky add . "npm test"
husky-hooks$ cd ../project
project$ git config core.hooksPath ../husky-hooks
# now if you commit ../husky-hooks/pre-commit will run for you only
```
