### ISSUE TITLE
error: husky asking for .git 

### ISSUE THREAD

**Issue by iamayushdas** [typicode/husky#995]
**Troubleshoot**
Before creating an issue, please check:
https://typicode.github.io/husky/#/?id=troubleshoot

If you're migrating from husky 4, see:
https://typicode.github.io/husky/#/?id=migrate-from-v4-to-v6

**Context**
Please describe your issue and provide some context:
see I want to install husky inside my subfolder that consists of package.json but .git is present in root folder.
is there any way to install husky to subfolder(Website) that does not contain .git
- Terminal or GUI client (PowerShell, Git Bash, GitHub Desktop, ...)
   
![image](https://user-images.githubusercontent.com/40708551/123502105-4b67c700-d667-11eb-9fa2-38e370ffe961.png)

my folder architecture

main 
  - .git
  -  file1
  - website (folder) 
                 - package.json
                 - other files

I want to install husky in website folder

                                       

- If applicable, content of the failing hook
- If possible, minimal steps to reproduce the issue

Thank you!

**Comment by iamayushdas** [comment]
cc @bfaulk36

**Comment by typicode** [comment]
Hi @iamayushdas 

See https://typicode.github.io/husky/#/?id=custom-directory
