### ISSUE TITLE
husky v6.0.0 cannot create pre-commit hook in .git directory

### ISSUE THREAD

**Issue by lyhper** [typicode/husky#996]
husky v6.0.0 pre-commit hook not working, but v4.3.8 working well.

node version v14.17.0

![image](https://user-images.githubusercontent.com/13343726/123591893-20c06e80-d81f-11eb-860f-0d7d22ab8bc5.png)

![image](https://user-images.githubusercontent.com/13343726/123591973-3a61b600-d81f-11eb-8fc7-aa68ed259b58.png)

**Comment by typicode** [comment]
Hi @lyhper,

Husky 6 works differently so it's normal :)
You need to run `husky install` and `husky add ...`. Hooks are now created in `.husky/` directory.

See:
https://github.com/typicode/husky#usage
https://typicode.github.io/husky/#/?id=usage

And https://github.com/typicode/lowdb for a live example.
