### ISSUE TITLE
'husky install' fails : "not a Git repository, skipping hooks installation"

### ISSUE THREAD

**Issue by David-Chaille** [typicode/husky#998]
Reopen #851

`Husky install` still fail in version **6.0.0** even tho the .git folder exists

![image](https://user-images.githubusercontent.com/79449439/123667523-853cf700-d83a-11eb-810d-19801a56154f.png)

**Comment by typicode** [comment]
This message is triggered when `git rev-parse` returns an exit code different that 0.
What do you get when running:

```
git rev-parse
echo $? # should be 0 if you're in a Git repository
```

**Comment by HuaManYing** [comment]
Did you solve this problem？ I have the same problem
